import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { isOperatorOrServiceRoleAuthorized, matchesRequiredSecret } from '../../supabase/functions/_shared/harbourview-auth'
const root=process.cwd(), read=(p:string)=>readFileSync(join(root,p),'utf8')
const migration=(v:string)=>{const f=readdirSync(join(root,'supabase/migrations')).find(n=>n.startsWith(v+'_')&&n.endsWith('.sql'));if(!f)throw new Error(`canonical migration ${v} is missing`);return read(join('supabase/migrations',f))}
const paths={jobRefresh:'supabase/functions/job-refresh/index.ts',schemaDrift:'supabase/functions/schema-drift-monitor/index.ts',sourcePull:'supabase/functions/hv-source-pull-runner/index.ts',privatePipeline:'supabase/functions/hv-private-pipeline-runner/index.ts',passport:'supabase/functions/compute-passport-score/index.ts',snapshot:'supabase/functions/generate-org-snapshot/index.ts'}
describe('production Edge Function authentication hardening',()=>{
it('fails closed for missing/wrong cron secrets',()=>{expect(matchesRequiredSecret('','')).toBe(false);expect(matchesRequiredSecret(undefined,'anything')).toBe(false);expect(matchesRequiredSecret('expected-secret','wrong-secret')).toBe(false);expect(matchesRequiredSecret('expected-secret','expected-secret')).toBe(true)})
it('accepts valid operator/service credentials and rejects fake service_role bearer strings',()=>{const operatorKey='operatorSecret' as const,serviceKey='serviceRoleKey' as const,callerKey='callerSecret' as const,base={[operatorKey]:'operator-secret-value',[serviceKey]:'service-role-key-value'};expect(isOperatorOrServiceRoleAuthorized({...base,[callerKey]:'operator-secret-value',authorization:null})).toBe(true);expect(isOperatorOrServiceRoleAuthorized({...base,[callerKey]:null,authorization:'Bearer service-role-key-value'})).toBe(true);expect(isOperatorOrServiceRoleAuthorized({...base,[callerKey]:'wrong-secret',authorization:'Bearer service_role'})).toBe(false);expect(isOperatorOrServiceRoleAuthorized({...base,[callerKey]:null,authorization:'Bearer attacker-service_role-token'})).toBe(false)})
it('canonicalizes job-refresh',()=>{const s=read(paths.jobRefresh);expect(s).toContain("Deno.env.get('JOB_REFRESH_CRON_SECRET')");expect(s).toContain('matchesRequiredSecret');expect(s).toContain('x-harbourview-cron-secret');expect(s).not.toMatch(/ADZUNA_APP_KEY\s*=\s*['"][^'"]+['"]/);expect(s).not.toMatch(/ADZUNA_APP_ID\s*=\s*['"][^'"]+['"]/ )})
it('requires dedicated schema-drift auth',()=>{const s=read(paths.schemaDrift);expect(s).toContain('SCHEMA_DRIFT_CRON_SECRET');expect(s).toContain('matchesRequiredSecret');expect(s).toContain('x-harbourview-cron-secret')})
it('restricts schema-drift RPCs to service_role',()=>{const s=read('supabase/migrations/20260815013000_lock_down_api_schema_drift_rpcs.sql').toLowerCase();expect(s).toContain('grant execute on function api.get_tables_missing_from_api_schema() to service_role;');expect(s).toContain('grant execute on function public.get_functions_missing_from_api_schema() to service_role;');expect(s).not.toMatch(/grant\s+execute\s+on\s+function\s+(?:api|public)\.[a-z_]+\(\)\s+to\s+(?:public|anon|authenticated)\b/)})
it('removes static caller strings',()=>{const a=read(paths.sourcePull),b=read(paths.privatePipeline);expect(a).toContain('HV_SOURCE_PULL_RUNNER_SECRET');expect(a).toContain('matchesRequiredSecret');expect(a).not.toContain('EXPECTED_CRON_CALLER');expect(a).not.toContain('pg_cron_hv_source_pull_runner');expect(b).toContain('HV_PRIVATE_PIPELINE_RUNNER_SECRET');expect(b).toContain('matchesRequiredSecret')})
it('uses exact auth helper in passport functions',()=>{for(const s of [read(paths.passport),read(paths.snapshot)]){expect(s).toContain('isOperatorOrServiceRoleAuthorized');expect(s).not.toContain('includes("service_role")');expect(s).not.toContain("includes('service_role')")}})
it('uses Vault-backed cron helpers without secret values',()=>{const s=migration('20260912103836');for(const n of ['job_refresh_cron_secret','schema_drift_cron_secret','hv_source_pull_runner_secret'])expect(s).toContain(n);expect(s).toContain('vault.decrypted_secrets');expect(s).toContain("select public.invoke_job_refresh();");expect(s).toContain("select public.invoke_schema_drift_monitor();");expect(s).toContain("select public.hv_trigger_source_pull_runner();")})
it('preserves downstream behavior',()=>{expect(read(paths.sourcePull)).toContain('/functions/v1/source-engine-fetch');expect(read(paths.privatePipeline)).toContain('callFunction("hv-extract"');expect(read(paths.privatePipeline)).toContain('callFunction("hv-score"');expect(read(paths.passport)).toContain('/functions/v1/generate-org-snapshot')})
})