import type { ComplianceExplainer } from './types'
import { coreComplianceDisclaimer } from './disclaimers'

export const complianceExplainers: ComplianceExplainer[] = [
  {
    slug: 'eu-gmp',
    title: 'EU GMP',
    summary: 'EU Good Manufacturing Practice covers the quality system requirements for cannabis manufacturing intended for European regulated markets, including facility controls, batch documentation, personnel, testing, QP release and CAPA.',
    whoItAppliesTo: ['Licensed cannabis manufacturers', 'Exporters supplying EU markets', 'Secondary processors', 'Contract manufacturers', 'Quality professionals and QPs'],
    commercialRelevance: 'EU GMP certification is a baseline requirement for most European regulated cannabis import routes. Without it, batches cannot be QP-released and importers cannot accept product into the EU distribution chain.',
    coreRequirements: [
      'Site Master File or equivalent facility documentation covering manufacturing scope, licence basis and key personnel.',
      'Quality Management System with version-controlled SOPs, change control, deviation management and CAPA records.',
      'Qualified Person designation with documented scope of authority for batch certification and release.',
      'Facility and equipment qualification — IQ, OQ, PQ for critical equipment and utilities.',
      'Validated analytical methods and accredited laboratory for finished product testing and CoA generation.',
      'Batch manufacturing records covering every production step with in-process controls, deviations and sign-offs.',
      'Stability programme with appropriate shelf-life data to support product specifications.',
    ],
    documentsUsuallyInvolved: [
      'EU GMP certificate (issued by competent authority or third-party inspector)',
      'Site Master File (SMF)',
      'Product dossier / Technical File',
      'Certificate of Analysis (batch-specific)',
      'Batch Manufacturing Record (BMR)',
      'CAPA log and deviation register',
      'Stability data summary',
    ],
    operationalControls: [
      'Environmental monitoring programme for classified manufacturing areas.',
      'Personnel hygiene, gowning and training qualification records.',
      'Cleaning validation and residue limit documentation for multi-product facilities.',
      'Computerised system validation for any GxP systems used in manufacturing or QC.',
      'Supplier qualification programme with approved supplier lists and re-qualification schedules.',
    ],
    commonFailurePoints: [
      'Incomplete batch records — missing in-process results, unsigned steps or unresolved deviations.',
      'QP designation gaps — QP not formally appointed, scope not documented or QP not accessible for certification.',
      'Stability data shortfalls — accelerated data available but no real-time data supporting the shelf life claimed.',
      'CAPA records closed without effectiveness verification.',
      'Change control not applied to manufacturing process, specification or facility changes.',
    ],
    countryVariation: 'EU GMP is required in Germany, UK, Netherlands, Portugal, Italy, Poland and most other European import markets. The specific EU GMP annex applicable to cannabis (Annex 7 for herbal medicinal products, Annex 1 for sterile) varies by product form. UK GMP (post-Brexit) operates under MHRA oversight with separate batch importation requirements.',
    harbourviewCanScreen: [
      'GMP certificate validity and scope alignment with the product and route under review.',
      'Documentation package completeness against standard EU import requirements.',
      'QP release process suitability for the specific product category and route.',
    ],
    specialistAdviceRequired: 'EU GMP compliance conclusions, QP release authorisation, MHRA or national competent authority submissions, and GMP inspection preparation require qualified person, regulatory consultant or legal advisor engagement.',
    relatedCountries: ['de', 'gb', 'nl', 'pt', 'it', 'pl', 'fr', 'cz'],
    relatedServiceCategories: ['quality-compliance', 'import-export'],
    disclaimer: coreComplianceDisclaimer,
  },
  {
    slug: 'gacp',
    title: 'GACP',
    summary: 'Good Agricultural and Collection Practice covers the quality controls for cannabis cultivation, harvesting, drying and primary processing required by regulated import markets and pharmaceutical-grade supply chains.',
    whoItAppliesTo: ['Cannabis cultivators and licensed growers', 'Exporters of flower and plant-derived material', 'Primary processors', 'Procurement teams evaluating supply sources'],
    commercialRelevance: 'GACP certification is typically required by EU and other regulated import markets as evidence that plant material was grown and harvested under documented quality controls. Without it, plant-origin cannabis products cannot enter pharmaceutical-grade supply chains.',
    coreRequirements: [
      'Site identity, geographic location, soil assessment, water source documentation and environmental monitoring.',
      'Seed or cutting origin records, variety identity, propagation documentation and genetic consistency evidence.',
      'Cultivation input records covering fertilisers, pesticides and growth regulators with prohibited substance avoidance.',
      'Harvest timing records, harvesting method documentation and fresh weight yield.',
      'Post-harvest handling records covering drying temperature, humidity, moisture content and storage conditions.',
      'Batch traceability from cultivation through primary processing with batch identification and yield records.',
    ],
    documentsUsuallyInvolved: [
      'GACP certificate (third-party audit and certificate)',
      'Cultivation batch records',
      'Pesticide application and residue records',
      'Drying and moisture content records',
      'Post-harvest storage and chain of custody documentation',
      'Certificate of Analysis for pesticide residue, heavy metals, mycotoxins and microbial counts',
    ],
    operationalControls: [
      'Pest and disease monitoring programme with integrated pest management records.',
      'Water quality testing for irrigation sources.',
      'Input substance register with supplier documentation and application batch records.',
      'Post-harvest contamination controls — segregation, temperature management and foreign matter exclusion.',
      'GACP-aligned SOP library covering all critical agricultural and post-harvest steps.',
    ],
    commonFailurePoints: [
      'GACP certificate scope limited to a single site or harvest year — does not cover subsequent batches.',
      'Pesticide records incomplete — application dates, quantities or active substances not documented.',
      'Insufficient post-harvest temperature and humidity records to demonstrate contaminant control.',
      'CoA contaminant limits not aligned with the import destination requirements.',
      'Traceability gap between cultivation batch and finished batch CoA.',
    ],
    countryVariation: 'GACP requirements follow WHO GACP guidelines in most markets but specific implementations vary. EU markets generally require WHO or EU GACP-aligned certification. Some jurisdictions accept domestically produced plant material under national standards without third-party GACP audit.',
    harbourviewCanScreen: [
      'GACP certificate scope, validity and audit body recognition against the destination market requirements.',
      'CoA completeness and limit alignment with EU or destination-country import requirements.',
      'Supply source documentation package completeness before procurement or export engagement.',
    ],
    specialistAdviceRequired: 'GACP certification audits, phytosanitary authority interactions, cultivation licence compliance and jurisdiction-specific GACP implementation questions require qualified agronomist, regulatory consultant or legal advisor engagement.',
    relatedCountries: ['de', 'pt', 'co', 'ug', 'za', 'au'],
    relatedServiceCategories: ['quality-compliance', 'import-export'],
    disclaimer: coreComplianceDisclaimer,
  },
  {
    slug: 'gdp-distribution',
    title: 'GDP Distribution',
    summary: 'Good Distribution Practice covers the quality requirements for wholesale storage, temperature-controlled transport, chain of custody and controlled-drug distribution of regulated cannabis across import and distribution networks.',
    whoItAppliesTo: ['Wholesale distributors', 'Importers with distribution obligations', 'Third-party logistics providers', 'Pharmacy-channel suppliers', 'Operators evaluating distribution partners'],
    commercialRelevance: 'GDP certification is a regulatory requirement for wholesale distribution of medicinal cannabis in most European and pharmaceutical-grade markets. Importers without GDP-certified storage and distribution infrastructure cannot legally hold, release or supply cannabis to pharmacy channels.',
    coreRequirements: [
      'Wholesale distribution authorisation from the relevant competent authority covering the applicable product category and controlled drug schedule.',
      'Qualified Person designation or responsible person appointment with documented GDP authority.',
      'Temperature-controlled storage facility with environmental monitoring, validated temperature mapping and alarm systems.',
      'GDP-aligned SOP library covering receipt, quarantine, release, pick, dispatch, returns and recall.',
      'Controlled drug balance reconciliation — receipt, distribution, destruction or return records aligned with narcotics licence conditions.',
      'Chain of custody documentation from receipt at the distribution facility through to pharmacy or end-customer delivery.',
    ],
    documentsUsuallyInvolved: [
      'GDP certificate (competent authority or third-party audit)',
      'Wholesale distribution authorisation',
      'Temperature mapping report for storage facility',
      'Controlled drug licence and balance records',
      'Chain of custody and batch release records',
      'Third-party logistics agreements with GDP compliance obligations',
    ],
    operationalControls: [
      'Incoming goods verification — product identity, CoA review, physical condition and temperature excursion check on receipt.',
      'Segregated quarantine, approved, rejected and returns areas with controlled access.',
      'Dispatch checks — correct batch, quantity, condition, documentation and controlled drug balance adjustment before release.',
      'Temperature excursion management — documented assessment, QP or responsible person decision, records retained.',
      'Recall management — ability to identify and withdraw all product from a batch within defined timelines.',
    ],
    commonFailurePoints: [
      'Temperature mapping gaps — storage areas qualified but transit vehicles or interim storage not mapped.',
      'Controlled drug balance discrepancies — receipt, dispensing or destruction records not reconciled.',
      'Chain of custody breaks — gaps in documentation between import border clearance and pharmacy receipt.',
      'Third-party logistics not under GDP oversight — carrier agreements without temperature monitoring obligations.',
      'Returns handling — returned product not quarantined before disposition decision.',
    ],
    countryVariation: 'EU GDP guidelines (2013/C 343/01) apply across EU member states. UK GDP (MHRA) operates under separate post-Brexit guidelines. Country-specific controlled drug balance requirements and reporting frequencies vary significantly across tracked markets.',
    harbourviewCanScreen: [
      'GDP certificate validity, scope and competent authority recognition for the distribution role and market.',
      'Controlled drug licence scope alignment with the product category and distribution activities.',
      'Distribution chain documentation completeness for import and pharmacy supply route review.',
    ],
    specialistAdviceRequired: 'GDP audit preparation, wholesale distribution authorisation applications, controlled drug licence matters, pharmacy admission and competent authority submissions require qualified person, regulatory consultant or legal advisor engagement.',
    relatedCountries: ['de', 'gb', 'nl', 'pt', 'it', 'pl'],
    relatedServiceCategories: ['quality-compliance', 'import-export'],
    disclaimer: coreComplianceDisclaimer,
  },
  {
    slug: 'import-export',
    title: 'Import and Export Documentation',
    summary: 'Import and export documentation covers the narcotics permit, product certificate, phytosanitary and customs documentation required to legally move regulated cannabis across international borders.',
    whoItAppliesTo: ['Exporters and licensed producers', 'Importers and distributors', 'Freight forwarders and customs brokers', 'Legal and regulatory affairs teams', 'Procurement and supply chain professionals'],
    commercialRelevance: 'Missing or incorrect import/export documentation results in customs delays, product seizure, permit invalidation or licence suspension. Documentation requirements must be confirmed for each corridor and shipment before goods are loaded.',
    coreRequirements: [
      'Narcotics export permit from the exporting country competent authority — typically issued by the health ministry or narcotics authority.',
      'Narcotics import order or import authorisation from the destination country competent authority.',
      'Certificate of Analysis for the specific batch being shipped, aligned with destination country requirements.',
      'GACP or GMP certificate for the product category, valid at time of shipment.',
      'Phytosanitary certificate for plant material (flower, trim, plant-derived extracts) — issued by the agricultural authority of the exporting country.',
      'Commercial invoice, packing list, bill of lading or air waybill, and certificate of origin where required.',
    ],
    documentsUsuallyInvolved: [
      'Narcotics export permit (exporting country)',
      'Narcotics import order (destination country)',
      'Certificate of Analysis (batch-specific)',
      'GACP or GMP certificate',
      'Phytosanitary certificate',
      'Commercial invoice and packing list',
      'Bill of lading or air waybill',
      'Certificate of origin',
      'Single Convention Schedule III or IV declaration where required',
    ],
    operationalControls: [
      'Pre-shipment document review — confirm all required documents are present, valid and aligned with each other before goods are loaded.',
      'Permit quantity reconciliation — verify export permit quantities match invoice, packing list and narcotics balance records.',
      'Transit country controls — confirm no prohibited transit routing and obtain transit permits where required.',
      'Post-shipment confirmation — import order closure, arrival confirmation and narcotics balance adjustment at the receiving end.',
    ],
    commonFailurePoints: [
      'Narcotics permit quantities mismatched with invoice or CoA batch quantities.',
      'Phytosanitary certificate issued after dispatch — must be issued before product leaves the country.',
      'Import order not activated before shipment arrives — leads to border hold.',
      'Product description inconsistency between documents — different THC values, product names or batch numbers across permit, CoA and invoice.',
      'Transit country narcotics permits not obtained for connecting routes through controlled jurisdictions.',
    ],
    countryVariation: 'Documentation requirements vary by corridor. Germany, UK, Netherlands and most EU markets require a full documentation package. Some markets accept simplified import notifications for specific product categories. Australia, Canada and Israel have distinctive import authority structures and permit formats.',
    harbourviewCanScreen: [
      'Document package completeness against standard requirements for a specific export corridor.',
      'Permit and CoA alignment review before goods are shipped.',
      'Documentation gap identification before commercial engagement with a new import market.',
    ],
    specialistAdviceRequired: 'Narcotics permit applications, customs classification, import authority submissions, border clearance disputes and corridor-specific legal requirements require qualified legal advisor, customs broker and regulatory affairs engagement.',
    relatedCountries: ['de', 'gb', 'nl', 'pt', 'au', 'il', 'pl'],
    relatedServiceCategories: ['import-export', 'quality-compliance'],
    disclaimer: coreComplianceDisclaimer,
  },
  {
    slug: 'facility-environment',
    title: 'Facility, Environment and Security Compliance',
    summary: 'Facility, environment and security compliance covers the physical infrastructure, environmental controls, access security and monitoring requirements for cannabis manufacturing, storage and distribution under GMP, GACP and GDP frameworks.',
    whoItAppliesTo: ['Licensed manufacturers and cultivators', 'Importers and distributors with controlled drug storage obligations', 'Facility managers and quality teams', 'Operators undergoing regulatory inspection or supplier qualification audit'],
    commercialRelevance: 'Facility non-compliance — inadequate environmental controls, access failures, cross-contamination risk or undocumented security — is a primary audit failure point. Supply chain partners and importing regulators assess facility compliance before approving product flows.',
    coreRequirements: [
      'Facility design documentation — flow diagrams, room classifications, access controls, HVAC system descriptions and zoning plans.',
      'Environmental monitoring programme covering temperature, humidity, particulate counts and microbial monitoring for classified areas.',
      'Physical security controls — access logging, CCTV coverage, alarm systems and vault or cage requirements for controlled drug storage.',
      'Utilities qualification — water system validation, HVAC qualification, compressed air testing and other process utilities relevant to the manufacturing scope.',
      'Pest control programme with documented contractor records, monitoring device maps and inspection frequency.',
      'Waste management procedures — controlled drug destruction records, waste classification, segregation and disposal documentation.',
    ],
    documentsUsuallyInvolved: [
      'Facility floor plans with room classifications and zoning',
      'Environmental monitoring SOPs and data records',
      'HVAC qualification report',
      'Security system records and access logs',
      'Controlled drug storage qualification and inventory records',
      'Pest control contractor records and monitoring maps',
    ],
    operationalControls: [
      'Periodic environmental monitoring review with out-of-limit investigation and CAPA records.',
      'Access control audits — review of personnel access logs against authorised access lists.',
      'Maintenance and calibration schedules for environmental monitoring equipment.',
      'Controlled drug storage balance reconciliation at defined frequencies.',
    ],
    commonFailurePoints: [
      'Environmental monitoring data not reviewed for trends — out-of-limit results not investigated.',
      'HVAC qualification not repeated after maintenance or modification.',
      'Access logs not reviewed — unauthorised access not identified or documented.',
      'Controlled drug storage not physically separate from general product storage.',
      'Pest control records not linked to facility maps — monitoring device locations not verified.',
    ],
    countryVariation: 'Physical security requirements for controlled drug storage vary significantly — Schedule I/II product storage typically requires vault-grade security in most markets. EU GMP Annex 1 applies specific environmental controls for sterile product manufacturing. Agricultural facility requirements under GACP are distinct from pharmaceutical manufacturing standards.',
    harbourviewCanScreen: [
      'Facility compliance documentation package completeness against standard audit expectations.',
      'Security and controlled drug storage suitability for the import or distribution role under review.',
    ],
    specialistAdviceRequired: 'Facility qualification programmes, regulatory inspection preparation, controlled drug storage licence applications and jurisdiction-specific facility compliance matters require qualified person, regulatory consultant or legal advisor engagement.',
    relatedCountries: [],
    relatedServiceCategories: ['quality-compliance'],
    disclaimer: coreComplianceDisclaimer,
  },
  {
    slug: 'documentation-audit',
    title: 'Documentation and Audit Readiness',
    summary: 'Documentation and audit readiness covers the records, procedures, version control systems and internal quality culture required to pass regulatory inspections, supplier qualification audits and GMP, GACP or GDP assessments.',
    whoItAppliesTo: ['Quality managers and QPs', 'Compliance teams preparing for regulatory inspection', 'Operators undergoing supplier qualification', 'Export-ready cannabis businesses entering new regulated markets'],
    commercialRelevance: 'Audit readiness determines whether a business can qualify as a supplier, retain a distribution relationship or maintain its licence. Documentation failures are the most common audit finding across all quality standard frameworks applicable to cannabis.',
    coreRequirements: [
      'Document control system — version numbering, review schedules, change control process and controlled copy distribution.',
      'SOP library covering all GxP-applicable processes — manufacturing, QC, distribution, complaints, deviations, CAPA, change control.',
      'Training records — personnel qualification, GxP training completion, SOP read-and-understood records and role-specific competency evidence.',
      'Deviation and OOS log — all deviations raised, investigated, root-caused and closed with CAPA where required.',
      'CAPA system — corrective and preventive actions documented, assigned, implemented and effectiveness-checked.',
      'Internal audit programme — scheduled audits, findings, responses and closure records.',
    ],
    documentsUsuallyInvolved: [
      'Document control SOP and master document register',
      'SOP library with version history',
      'Training records and competency assessments',
      'Deviation and OOS register',
      'CAPA log with effectiveness check records',
      'Internal audit schedule and findings reports',
      'Change control register',
    ],
    operationalControls: [
      'Periodic document review — SOPs reviewed on schedule, updated for process changes and version-controlled.',
      'Trend analysis on deviations, OOS and complaints to identify systemic issues before inspection.',
      'Mock audits or gap assessments against applicable standards before scheduled regulatory inspections.',
      'Training gap reviews — new SOP versions trigger retraining records before implementation.',
    ],
    commonFailurePoints: [
      'Obsolete SOP versions in use — document control not enforced, staff using printed copies not on the current version.',
      'Deviation records closed without root cause identified or CAPA implemented.',
      'Training records incomplete — staff performing GxP tasks without documented training.',
      'CAPA effectiveness checks not conducted — actions implemented but outcome not verified.',
      'Internal audit findings not responded to within defined timelines.',
    ],
    countryVariation: 'Document control and audit requirements are largely harmonised across EU GMP, UK GMP, WHO GMP and PIC/S frameworks. Specific record retention periods vary by jurisdiction — typically 5 years minimum for batch records, longer for stability and validation data.',
    harbourviewCanScreen: [
      'Documentation package completeness and version control discipline before an external audit or regulatory inspection.',
      'CAPA and deviation record discipline as part of supplier qualification document review.',
      'Audit readiness gap identification against standard EU GMP or GDP expectations.',
    ],
    specialistAdviceRequired: 'Regulatory inspection preparation, GMP certification gap assessments, audit response drafting and qualified person advisory services require qualified person, regulatory consultant or legal advisor engagement.',
    relatedCountries: [],
    relatedServiceCategories: ['quality-compliance'],
    disclaimer: coreComplianceDisclaimer,
  },
  {
    slug: 'testing-coa',
    title: 'Testing, CoA, Packaging and Labelling',
    summary: 'Testing, CoA, packaging and labelling compliance covers the analytical testing requirements, certificate of analysis format standards, packaging controls and labelling rules applicable to regulated cannabis export and import.',
    whoItAppliesTo: ['Quality control and QA teams', 'Exporters and manufacturers preparing product for international supply', 'Procurement and import teams evaluating product documentation', 'Regulatory affairs professionals'],
    commercialRelevance: 'A CoA that does not align with import destination requirements — wrong test parameters, unaccredited laboratory, missing stability data or packaging that does not comply with pharmacy-channel requirements — will block product admission regardless of the quality of the underlying product.',
    coreRequirements: [
      'Testing at an ISO 17025-accredited laboratory for all required parameters — potency, pesticide residue, heavy metals, mycotoxins, microbial counts and solvents where applicable.',
      'CoA format including laboratory identity, accreditation details, sample receipt documentation, method references, result with units, specification limits and pass/fail statement.',
      'Stability data supporting the proposed shelf life — real-time data preferred, accelerated data as interim support.',
      'Packaging compliant with the destination market requirements — child-resistant, tamper-evident, light-protective and appropriately sized.',
      'Labelling compliant with destination country requirements — product name, batch number, manufacture date, expiry date, storage conditions, THC and CBD content declaration and required warning statements.',
    ],
    documentsUsuallyInvolved: [
      'Certificate of Analysis (batch-specific, from accredited laboratory)',
      'Laboratory accreditation certificate (ISO 17025)',
      'Stability study report or accelerated stability summary',
      'Finished product specification',
      'Packaging specification and artwork',
      'Labelling content approval record',
    ],
    operationalControls: [
      'CoA review against specification before batch release — results, units, limits and laboratory identity all checked.',
      'Stability data review schedule — real-time data pulled and assessed at defined timepoints.',
      'Packaging and labelling artwork approval process — sign-off before print and before use in production.',
      'Retest date tracking — batch records linked to stability protocol so retest obligations are not missed.',
    ],
    commonFailurePoints: [
      'CoA laboratory not ISO 17025 accredited for cannabis matrices or specific test methods.',
      'Pesticide residue limits on CoA not aligned with destination country MRL requirements.',
      'Shelf life not supported by stability data — CoA claims 24 months but only 6-month data available.',
      'Packaging not child-resistant where required by destination pharmacy channel.',
      'THC and CBD declaration on label not aligned with CoA results — rounding or conversion errors.',
    ],
    countryVariation: 'Test parameter requirements vary significantly. Germany, UK and Australia have specific MRL and microbial limit lists that must be matched. Some markets accept product tested against WHO or European Pharmacopoeia limits. Labelling language, required warnings and content format differ across EU member states, UK and non-EU markets.',
    harbourviewCanScreen: [
      'CoA format and laboratory accreditation alignment with destination market requirements.',
      'Stability data adequacy review against the proposed shelf life and product form.',
      'Packaging and labelling compliance overview against standard pharmacy-channel requirements for a specific market.',
    ],
    specialistAdviceRequired: 'Analytical method validation, pharmacopoeial compliance assessments, labelling sign-off for specific markets and regulatory authority submissions require qualified person, regulatory consultant, laboratory specialist or legal advisor engagement.',
    relatedCountries: ['de', 'gb', 'au', 'nl', 'pt'],
    relatedServiceCategories: ['quality-compliance', 'import-export'],
    disclaimer: coreComplianceDisclaimer,
  },
]

export function getExplainer(slug: string) {
  return complianceExplainers.find((e) => e.slug === slug)
}
