-- Harbourview Marketplace industry-wide procurement catalogue v2
-- Reference/catalogue taxonomy only. No live supplier, stock, price, licence,
-- certification, availability, or regulatory approval is implied.
-- Idempotent by slug.

insert into public.listings (
  slug,title,description,marketplace_section,category,product_type,
  public_visibility,status,sold_by_harbourview,is_featured,
  high_level_specs,compliance_flags
)
select v.slug,v.title,v.description,v.section,v.category::marketplace_category,v.product_type,
       true,'approved',false,false,
       jsonb_build_object('catalogue',true,'review_required',true,'procurement_domain',v.domain),
       jsonb_build_object('review_required',true)
from (values
('mro-bearings','Industrial Bearings & Replacement Components','Reference MRO category covering bearings and replacement components.','equipment','new_products','bearings','MRO'),
('mro-belts','Industrial Belts & Drive Components','Reference MRO category covering belts and drive components.','equipment','new_products','drive_components','MRO'),
('mro-valves-fittings','Industrial Valves, Fittings & Hoses','Reference process-maintenance category covering valves, fittings and hoses.','equipment','new_products','valves_fittings','MRO'),
('mro-pumps','Industrial Pumps & Replacement Pump Parts','Reference maintenance category for process and facility pumps.','equipment','new_products','pumps','MRO'),
('mro-fasteners','Industrial Fasteners & Hardware','Reference maintenance supply category for commercial hardware and fasteners.','consumables','consumables','fasteners','MRO'),
('mro-tools','Industrial Hand & Power Tools','Reference maintenance tool category.','equipment','new_products','industrial_tools','MRO'),
('electrical-distribution','Electrical Distribution Equipment','Reference facility electrical infrastructure category.','equipment','new_products','electrical_distribution','Utilities'),
('transformers-switchgear','Transformers & Switchgear','Reference commercial power-distribution equipment category.','equipment','new_products','switchgear','Utilities'),
('commercial-compressors','Industrial Air Compressors','Reference compressed-air equipment category.','equipment','new_products','compressors','Utilities'),
('commercial-chillers','Commercial Chillers','Reference facility cooling equipment category.','equipment','new_products','chillers','Utilities'),
('wastewater-system','Industrial Wastewater Treatment System','Reference wastewater infrastructure category.','equipment','new_products','wastewater','Utilities'),
('facility-retrofit','Facility Retrofit & Installation Services','Reference facility retrofit/installation service category.','professional_services','professional_services','facility_retrofit','Facilities'),
('loading-dock-equipment','Loading Dock Equipment','Reference warehouse loading infrastructure category.','equipment','new_products','dock_equipment','Facilities'),
('industrial-robotics','Industrial Robotics & Automation','Reference automation equipment category.','equipment','new_products','robotics','Automation'),
('plc-control-system','PLC & Industrial Control System','Reference controls/automation category.','equipment','new_products','plc_controls','Automation'),
('machine-vision','Machine Vision Inspection System','Reference automated inspection category.','equipment','new_products','machine_vision','Automation'),
('scada-integration','SCADA & Controls Integration Service','Reference industrial controls integration service.','services','services','scada','Automation'),
('industrial-ppe','Industrial PPE Supply','Reference industrial safety supply category.','consumables','consumables','ppe','EHS'),
('gas-detection','Gas Detection & Monitoring System','Reference facility gas-detection category.','equipment','new_products','gas_detection','EHS'),
('lockout-tagout','Lockout/Tagout Safety Supplies','Reference workplace safety supply category.','consumables','consumables','lockout_tagout','EHS'),
('spill-response','Spill Response & Containment Supplies','Reference environmental/safety supply category.','consumables','consumables','spill_response','EHS'),
('safety-training','Industrial Safety Training Services','Reference workplace safety training category.','professional_services','professional_services','safety_training','EHS'),
('waste-management','Industrial & Regulated Waste Management Service','Reference waste-management service; applicable classification and jurisdiction require verification.','services','services','waste_management','Waste'),
('recycling-service','Commercial Recycling & Material Recovery','Reference recycling/material-recovery service category.','services','services','recycling','Waste'),
('industrial-cleaning','Industrial Cleaning & Sanitation Service','Reference commercial cleaning service category.','services','services','industrial_cleaning','Sanitation'),
('washdown-system','Industrial Washdown System','Reference facility sanitation/washdown equipment category.','equipment','new_products','washdown','Sanitation'),
('security-cameras','Commercial Security Camera System','Reference physical security technology category.','equipment','new_products','video_security','Security'),
('access-control-integration','Access Control & Security Integration','Reference security integration service category.','services','services','security_integration','Security'),
('secure-vault-storage','Secure Storage & Vault Infrastructure','Reference secure-storage infrastructure category.','equipment','new_products','secure_storage','Security'),
('retail-display','Retail Display & Merchandising Fixtures','Reference dispensary/retail fixture category.','equipment','new_products','retail_display','Retail'),
('retail-pos-hardware','Retail POS Hardware','Reference retail point-of-sale hardware category.','equipment','new_products','pos_hardware','Retail'),
('retail-signage','Retail Signage & Wayfinding','Reference retail signage category.','consumables','new_products','retail_signage','Retail'),
('office-computing','Business Computing Hardware','Reference corporate IT hardware category.','equipment','new_products','computing','Corporate'),
('networking-wifi','Business Networking & Wi-Fi Infrastructure','Reference network infrastructure category.','equipment','new_products','networking','IT'),
('endpoint-management','Endpoint Management & Device Services','Reference managed-device technology service category.','services','services','endpoint_management','IT'),
('erp-integration','ERP Implementation & Integration Service','Reference enterprise software implementation category.','services','services','erp','Software'),
('wms-integration','Warehouse Management System Integration','Reference WMS implementation/integration category.','services','services','wms','Software'),
('lims-integration','Laboratory Information Management Integration','Reference LIMS implementation/integration category.','services','services','lims','Software'),
('document-management','Document & Quality Management Software','Reference document/QMS software category.','services','services','document_management','Software'),
('accounting-services','Accounting & Bookkeeping Services','Reference business accounting service category.','professional_services','professional_services','accounting','Professional Services'),
('legal-services','Commercial & Regulatory Legal Services','Reference legal-service category; jurisdiction and professional credentials require verification.','professional_services','professional_services','legal','Professional Services'),
('recruiting-services','Recruiting & Staffing Services','Reference workforce/recruiting service category.','professional_services','professional_services','recruiting','HR'),
('training-services','Workforce Training & Certification Services','Reference workforce training category.','professional_services','professional_services','training','HR'),
('insurance-brokerage','Commercial Insurance Brokerage Services','Reference commercial insurance brokerage category.','professional_services','professional_services','insurance','Risk'),
('trade-finance','Trade Finance & Commercial Financing Services','Reference financing category; eligibility and terms require underwriting.','professional_services','professional_services','trade_finance','Finance'),
('equipment-leasing','Equipment Leasing & Rental Services','Reference equipment finance/rental category.','services','services','equipment_leasing','Finance'),
('customs-brokerage','Customs Brokerage & Trade Compliance','Reference import/export service category.','services','services','customs','Trade'),
('freight-forwarding','International Freight Forwarding','Reference international logistics service category.','logistics','logistics','freight_forwarding','Trade'),
('bonded-warehousing','Bonded Warehousing Services','Reference bonded warehousing category; jurisdictional eligibility requires verification.','logistics','logistics','bonded_warehouse','Trade'),
('courier-services','Commercial Courier & Parcel Services','Reference commercial parcel logistics category.','logistics','logistics','courier','Transportation'),
('fleet-services','Commercial Fleet Leasing & Maintenance','Reference fleet services category.','services','services','fleet','Transportation'),
('print-packaging','Commercial Packaging Printing Services','Reference packaging/label printing service category.','packaging','services','printing','Printing'),
('label-inspection','Label Inspection & Verification System','Reference automated label QA category.','equipment','new_products','label_inspection','Manufacturing'),
('contract-manufacturing','Contract Manufacturing Services','Reference eligible contract-manufacturing category; scope and regulatory qualification require verification.','services','professional_services','contract_manufacturing','Manufacturing'),
('contract-packaging','Contract Packaging & Kitting Services','Reference contract packaging/kitting category.','services','professional_services','contract_packaging','Manufacturing'),
('product-development','Product Development & Prototyping Services','Reference product-development service category.','professional_services','professional_services','product_development','R&D'),
('stability-programs','Product Stability Program Services','Reference stability-program service category; applicable methods and credentials require verification.','labs_testing','professional_services','stability','R&D'),
('microbiology-testing','Microbiology Testing Services','Reference microbiology testing category; laboratory scope/accreditation requires verification.','labs_testing','services','microbiology','Laboratory'),
('pesticide-testing','Pesticide Residue Testing Services','Reference analytical testing category; methods and jurisdiction require verification.','labs_testing','services','pesticide_testing','Laboratory'),
('mycotoxin-testing','Mycotoxin Testing Services','Reference analytical testing category; methods and jurisdiction require verification.','labs_testing','services','mycotoxin_testing','Laboratory'),
('terpene-testing','Terpene Analytical Testing Services','Reference analytical testing category.','labs_testing','services','terpene_testing','Laboratory'),
('lab-reagents','Laboratory Reagents & Consumables','Reference laboratory consumables category.','consumables','consumables','lab_reagents','Laboratory'),
('lab-standards','Laboratory Reference Standards','Reference analytical standards category; suitability and documentation require verification.','consumables','consumables','reference_standards','Laboratory'),
('cultivation-genetics','Seeds, Clones & Propagation Genetics','Reference genetics/propagation category; legality and jurisdictional eligibility require verification.','genetics','genetics','genetics','Agriculture'),
('tissue-culture','Plant Tissue Culture Services','Reference propagation service category.','services','professional_services','tissue_culture','Agriculture'),
('agricultural-inputs','Agricultural Inputs & Growing Supplies','Reference broad cultivation-input category.','consumables','consumables','agricultural_inputs','Agriculture'),
('regulatory-consulting','Regulatory & Market-Access Consulting','Reference professional service category; jurisdiction and credentials require verification.','professional_services','professional_services','regulatory','Professional Services'),
('import-export-consulting','Import/Export Documentation Consulting','Reference trade-compliance consulting category.','professional_services','professional_services','import_export','Trade')
) v(slug,title,description,section,category,product_type,domain)
where v.section in ('consumables','genetics','labs_testing','logistics','packaging','processing','professional_services','services','equipment')
  and not exists (select 1 from public.listings l where l.slug=v.slug);
