<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><IsTestProject>true</IsTestProject></PropertyGroup><ItemGroup><PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="xunit" /><PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" /></ItemGroup><ItemGroup><ProjectReference Include="..\..\src\WinBgControlCenter.Core\WinBgControlCenter.Core.csproj" /><ProjectReference Include="..\..\src\WinBgControlCenter.Simulation\WinBgControlCenter.Simulation.csproj" /></ItemGroup></Project>
