#!/usr/bin/env python3
from pathlib import Path
import json
import re
import pycountry

ROOT = Path(__file__).resolve().parents[2]
source = ROOT / 'lib/country-data/generated-country-identity-rows.ts'
out = ROOT / 'lib/country-data/generated-iso-region-rows.ts'
text = source.read_text(encoding='utf-8')
match = re.search(r'export const countryIdentityRows =\s*(\[.*\])\s*as const', text, re.S)
if not match:
    raise SystemExit('Unable to parse countryIdentityRows')
rows = json.loads(match.group(1))
overrides = {'XKX': 'XK'}
output = []
missing = []
for row in rows:
    if len(row) < 5:
        raise SystemExit(f'Malformed country identity row: {row}')
    identity = row[0]
    region = row[3] or ''
    subregion = row[4] or ''
    if not isinstance(identity, str) or not identity.startswith('country_area:'):
        continue
    alpha3 = identity.split(':', 1)[1].upper()
    alpha2 = overrides.get(alpha3)
    if not alpha2:
        country = pycountry.countries.get(alpha_3=alpha3)
        alpha2 = country.alpha_2 if country else None
    if not alpha2:
        missing.append(alpha3)
        continue
    output.append([alpha2, alpha3, region, subregion])
if missing:
    raise SystemExit(f'Unmapped ISO-3 identities: {missing}')
output.sort(key=lambda row: row[0])
if len(output) != 248:
    raise SystemExit(f'Expected exactly 248 country/area mappings, got {len(output)}')
if len({row[0] for row in output}) != len(output):
    raise SystemExit('Duplicate ISO-2 output')
if len({row[1] for row in output}) != len(output):
    raise SystemExit('Duplicate ISO-3 output')
body = json.dumps(output, indent=2, ensure_ascii=False)
out.write_text(
    '// Generated by scripts/country-data/generate-iso-region-rows.py\n'
    '// ISO conversion: pycountry 24.6.1; region/subregion: checked-in UN M49-derived Harbourview identities.\n'
    f'export const isoRegionRows = {body} as const\n',
    encoding='utf-8',
)
print(f'wrote {len(output)} ISO region rows')
