import { NextResponse } from 'next/server'
import { getPlaybook, DIFFICULTY_LABEL } from '@/lib/intelligence/jurisdictionPlaybooks'
import { PdfDoc } from '@/lib/reports/pdfBuilder'

export const dynamic = 'force-dynamic'

type Params = { params: Promise<{ country: string }> }

export async function GET(_req: Request, { params }: Params) {
  const { country } = await params
  const playbook = await getPlaybook(country)

  if (!playbook) {
    return NextResponse.json({ error: 'Playbook not found' }, { status: 404 })
  }

  const doc = new PdfDoc()

  doc.heading(`${playbook.country_name} — Cannabis Licensing Pathway`)
  doc.paragraph(
    `Generated by Harbourview Intelligence on ${new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })}.`,
  )
  doc.spacer(10)

  doc.subheading('Pathway overview')
  doc.paragraph(`Complexity: ${DIFFICULTY_LABEL[playbook.difficulty] ?? playbook.difficulty}`)
  if (playbook.typical_timeline_months != null) {
    doc.paragraph(`Typical timeline: ${playbook.typical_timeline_months} months`)
  }
  if (playbook.estimated_cost_range) {
    doc.paragraph(`Estimated cost range: ${playbook.estimated_cost_range}`)
  }
  doc.spacer(10)

  if (playbook.legal_framework_summary) {
    doc.subheading('Legal framework')
    doc.paragraph(playbook.legal_framework_summary)
    doc.spacer(10)
  }

  if (playbook.steps.length > 0) {
    doc.subheading('Licensing steps')
    for (const step of playbook.steps) {
      doc.paragraph(`${step.step}. ${step.title} — ${step.required ? 'Required' : 'Optional'}, est. ${step.estimated_weeks} wk${step.estimated_weeks === 1 ? '' : 's'}`, { bold: true })
      doc.paragraph(step.description)
      doc.spacer(6)
    }
    doc.spacer(4)
  }

  if (playbook.key_regulators.length > 0) {
    doc.subheading('Key regulators')
    for (const reg of playbook.key_regulators) {
      doc.bullet(`${reg.name} — ${reg.role}`)
    }
    doc.spacer(10)
  }

  if (playbook.common_pitfalls.length > 0) {
    doc.subheading('Common pitfalls')
    for (const pitfall of playbook.common_pitfalls) {
      doc.bullet(pitfall)
    }
    doc.spacer(10)
  }

  const lastVerifiedRaw = playbook.last_verified_at ?? playbook.last_reviewed
  const lastVerified = new Date(lastVerifiedRaw).toLocaleDateString('en-US', { year: 'numeric', month: 'long' })
  doc.subheading('Status')
  doc.paragraph(`Last reviewed: ${lastVerified}`)
  doc.paragraph(
    'This pathway summary is orientation-level only. It does not confirm licence eligibility or route ' +
      'viability for any specific operator. Verify current requirements with qualified local legal counsel ' +
      'and the relevant competent authority before acting.',
  )

  const pdfBytes = doc.build()

  return new NextResponse(pdfBytes, {
    status: 200,
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${playbook.country_iso2}-licensing-pathway.pdf"`,
      'Cache-Control': 'private, max-age=3600',
    },
  })
}
