import type { CapabilityCriticality, CapabilityStatus, CapabilityVisibility } from '@/lib/platform/contentStatus'

export type MarketplaceCategoryCapability = {
  id: string
  label: string
  route: string
  capabilityStatus: CapabilityStatus
  visibility: CapabilityVisibility
  criticality: CapabilityCriticality
  publicLabel: string
  liveDataExpectation: 'live-approved-records' | 'static-orientation' | 'request-capture' | 'private-routing'
  privateBoundary: string
  relatedCapabilityIds: string[]
  acceptanceTests: string[]
}

export const marketplaceCategoryCapabilityMap: MarketplaceCategoryCapability[] = [
  {
    id: 'reviewed-listings',
    label: 'Reviewed Network Listings',
    route: '/marketplace/listings',
    capabilityStatus: 'partial',
    visibility: 'public',
    criticality: 'launch-critical',
    publicLabel: 'Reviewed public summaries; private details withheld',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Public DTOs must not expose provenance, evidence, internal review notes, seller authorization status or counterparty details.',
    relatedCapabilityIds: ['marketplace-listings', 'public-private-dto-boundary'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'used-surplus',
    label: 'Used & Surplus Equipment',
    route: '/marketplace/used-surplus',
    capabilityStatus: 'partial',
    visibility: 'public',
    criticality: 'launch-critical',
    publicLabel: 'Open used and surplus listings with price and contact via form',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Public listings show price, condition and location. Seller contact is via Harbourview form; full diligence stays optional after contact.',
    relatedCapabilityIds: ['marketplace-hub', 'public-private-dto-boundary'],
    acceptanceTests: ['npm run test:used-surplus-public-leakage'],
  },
  {
    id: 'business-opportunities',
    label: 'Business Opportunities',
    route: '/marketplace/business-opportunities',
    capabilityStatus: 'partial',
    visibility: 'public',
    criticality: 'launch-critical',
    publicLabel: 'Reviewed summaries; confidential review before full disclosure',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Parties, terms, assets, distress context, diligence packs and dealroom access are private unless explicitly approved for public-safe summary.',
    relatedCapabilityIds: ['marketplace-business-opportunities', 'reviewed-connections'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'consumables',
    label: 'Consumables & Operating Supplies',
    route: '/marketplace/consumables',
    capabilityStatus: 'partial',
    visibility: 'public',
    criticality: 'launch-critical',
    publicLabel: 'Open listings with price and contact via Harbourview form',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Public listings show price and high-level specs. Seller contact is via Harbourview form; raw email/phone stay private.',
    relatedCapabilityIds: ['marketplace-hub'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'new-products',
    label: 'New Products',
    route: '/marketplace/new-products',
    capabilityStatus: 'partial',
    visibility: 'public',
    criticality: 'launch-critical',
    publicLabel: 'Reviewed product summaries; procurement review required',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Supplier claims, specs, certification evidence and procurement terms require review.',
    relatedCapabilityIds: ['marketplace-hub'],
    acceptanceTests: ['npm run test:new-products-equipment-intake'],
  },
  {
    id: 'licensed-inventory',
    label: 'Cannabis Inventory',
    route: '/marketplace/cannabis-inventory',
    capabilityStatus: 'request-only',
    visibility: 'private',
    criticality: 'launch-critical',
    publicLabel: 'Licensed-only review and private routing',
    liveDataExpectation: 'private-routing',
    privateBoundary: 'Licensed product availability, seller identity, batch documentation, pricing and import/export eligibility remain private and review-gated.',
    relatedCapabilityIds: ['marketplace-hub', 'public-private-dto-boundary'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'services',
    label: 'Services',
    route: '/marketplace/services',
    capabilityStatus: 'fallback-backed',
    visibility: 'public',
    criticality: 'launch-critical',
    publicLabel: 'Approved service listings when available; orientation otherwise',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Service provider contact details, diligence evidence and availability remain private until reviewed routing.',
    relatedCapabilityIds: ['marketplace-services'],
    acceptanceTests: ['npm run test:full-scope:fallbacks', 'npm run test:services-public-leakage'],
  },
  {
    id: 'wanted-requests',
    label: 'Wanted Requests',
    route: '/marketplace/wanted',
    capabilityStatus: 'request-only',
    visibility: 'mixed',
    criticality: 'launch-critical',
    publicLabel: 'Demand capture reviewed before routing',
    liveDataExpectation: 'request-capture',
    privateBoundary: 'Buyer identity, demand specifics and procurement criteria are private unless a public-safe wanted summary is approved.',
    relatedCapabilityIds: ['marketplace-wanted'],
    acceptanceTests: ['npm run test:intake-workflow-safety'],
  },
  {
    id: 'genetics',
    label: 'Genetics, Seeds & Tissue Culture',
    route: '/marketplace/genetics',
    capabilityStatus: 'partial',
    visibility: 'mixed',
    criticality: 'launch-critical',
    publicLabel: 'Controlled showcase; compliance-gated routing',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Propagation details, licensing terms, jurisdiction eligibility and counterparty access require review.',
    relatedCapabilityIds: ['marketplace-hub', 'public-private-dto-boundary'],
    acceptanceTests: ['npm run test:genetics-profile-redaction', 'npm run test:genetics-routing'],
  },
  {
    id: 'request-introduction',
    label: 'Request Introduction',
    route: '/intake',
    capabilityStatus: 'request-only',
    visibility: 'mixed',
    criticality: 'launch-critical',
    publicLabel: 'Confidential routing request; no automatic introduction',
    liveDataExpectation: 'request-capture',
    privateBoundary: 'Introductions, counterparty identity and commercial terms require Harbourview review and party approval.',
    relatedCapabilityIds: ['confidential-intake', 'reviewed-connections'],
    acceptanceTests: ['npm run test:intake-workflow-safety'],
  },
  {
    id: 'cultivation-equipment',
    label: 'Cultivation Equipment & Infrastructure',
    route: '/marketplace/cultivation-equipment',
    capabilityStatus: 'partial',
    visibility: 'public',
    criticality: 'launch-critical',
    publicLabel: 'Open equipment listings with price and contact via form',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Public listings show price, condition and high-level specs. Seller contact is via Harbourview form; identity details stay private until the seller responds.',
    relatedCapabilityIds: ['marketplace-hub', 'used-surplus'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'distressed-inventory',
    label: 'Distressed Inventory',
    route: '/marketplace/distressed-inventory',
    capabilityStatus: 'request-only',
    visibility: 'mixed',
    criticality: 'launch-critical',
    publicLabel: 'Confidential intake; sanitised summaries only',
    liveDataExpectation: 'private-routing',
    privateBoundary: 'Seller identity, product details, pricing and diligence materials are never disclosed without qualification and party approval.',
    relatedCapabilityIds: ['marketplace-hub', 'reviewed-connections', 'business-opportunities'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'distressed-businesses',
    label: 'Distressed Businesses & Assets',
    route: '/marketplace/distressed-businesses',
    capabilityStatus: 'request-only',
    visibility: 'mixed',
    criticality: 'launch-critical',
    publicLabel: 'Confidential intake; qualified counterparty access only',
    liveDataExpectation: 'private-routing',
    privateBoundary: 'Party identity, financials, distress context, diligence packs and dealroom access are private unless explicitly approved for public-safe summary.',
    relatedCapabilityIds: ['business-opportunities', 'reviewed-connections', 'qualified-access'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'qualified-access',
    label: 'Qualified Access & Protected Dealrooms',
    route: '/marketplace/qualified-access',
    capabilityStatus: 'request-only',
    visibility: 'mixed',
    criticality: 'launch-critical',
    publicLabel: 'Request-only; Harbourview review before any access granted',
    liveDataExpectation: 'private-routing',
    privateBoundary: 'Dealroom documents, counterparty identity, transaction terms and diligence materials require qualification, review and party approval.',
    relatedCapabilityIds: ['reviewed-connections', 'distressed-businesses', 'business-opportunities'],
    acceptanceTests: ['npm run test:intake-workflow-safety'],
  },
  {
    id: 'export-ready',
    label: 'Export-Ready Supply',
    route: '/marketplace/export-ready',
    capabilityStatus: 'partial',
    visibility: 'public',
    criticality: 'launch-critical',
    publicLabel: 'Reviewed export-ready summaries; documentation and credentials private',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Producer identity, batch documentation, export authorisation, pricing and INCB quota status require Harbourview review before any introduction.',
    relatedCapabilityIds: ['marketplace-hub', 'licensed-inventory'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'import-demand',
    label: 'Import Demand',
    route: '/marketplace/import-demand',
    capabilityStatus: 'partial',
    visibility: 'public',
    criticality: 'launch-critical',
    publicLabel: 'Reviewed import demand summaries; buyer identity and terms private',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Buyer identity, procurement criteria, regulatory pathway and commercial terms require Harbourview review before supplier introduction.',
    relatedCapabilityIds: ['marketplace-hub', 'licensed-inventory'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'labs-testing',
    label: 'Labs & Testing Services',
    route: '/marketplace/labs-testing',
    capabilityStatus: 'partial',
    visibility: 'public',
    criticality: 'later-enabled',
    publicLabel: 'Reviewed lab and testing provider summaries',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Provider contact details, pricing, accreditation evidence and availability require Harbourview review before routing.',
    relatedCapabilityIds: ['services', 'marketplace-hub'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'logistics',
    label: 'Logistics & Distribution',
    route: '/marketplace/logistics',
    capabilityStatus: 'partial',
    visibility: 'public',
    criticality: 'later-enabled',
    publicLabel: 'Reviewed logistics and distribution provider summaries',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Provider identity, lane pricing, carrier agreements and routing details remain private until Harbourview review.',
    relatedCapabilityIds: ['services', 'marketplace-hub'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'packaging',
    label: 'Packaging',
    route: '/marketplace/packaging',
    capabilityStatus: 'partial',
    visibility: 'public',
    criticality: 'later-enabled',
    publicLabel: 'Open packaging listings; contact via form',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Public listings show price and MOQ when provided. Seller contact is via Harbourview form; raw contact details stay private.',
    relatedCapabilityIds: ['consumables', 'marketplace-hub'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'processing-equipment',
    label: 'Processing Equipment',
    route: '/marketplace/processing-equipment',
    capabilityStatus: 'partial',
    visibility: 'public',
    criticality: 'later-enabled',
    publicLabel: 'Open processing equipment listings; contact via form',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Public listings show price, condition and high-level specs. Seller contact is via Harbourview form.',
    relatedCapabilityIds: ['cultivation-equipment', 'used-surplus', 'marketplace-hub'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'professional-services',
    label: 'Professional Services',
    route: '/marketplace/professional-services',
    capabilityStatus: 'partial',
    visibility: 'public',
    criticality: 'later-enabled',
    publicLabel: 'Reviewed professional service provider summaries',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Provider contact details, engagement terms, fee structures and diligence evidence remain private until Harbourview review.',
    relatedCapabilityIds: ['services', 'marketplace-hub'],
    acceptanceTests: ['npm run test:visibility'],
  },
]

export function getMarketplaceCategoryCapability(id: string) {
  return marketplaceCategoryCapabilityMap.find((category) => category.id === id)
}
