import type { CapabilityCriticality, CapabilityStatus, CapabilityVisibility } from '@/lib/platform/contentStatus'

export type MarketplaceCategoryCapability = {
  id: string
  label: string
  route: string
  capabilityStatus: CapabilityStatus
  visibility: CapabilityVisibility
  criticality: CapabilityCriticality
  publicLabel: string
  liveDataExpectation: 'live-approved-records' | 'static-orientation' | 'request-capture' | 'private-routing'
  privateBoundary: string
  relatedCapabilityIds: string[]
  acceptanceTests: string[]
}

export const marketplaceCategoryCapabilityMap: MarketplaceCategoryCapability[] = [
  {
    id: 'reviewed-listings',
    label: 'Reviewed Network Listings',
    route: '/marketplace/listings',
    capabilityStatus: 'partial',
    visibility: 'public',
    criticality: 'launch-critical',
    publicLabel: 'Reviewed public summaries; private details withheld',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Public DTOs must not expose provenance, evidence, internal review notes, seller authorization status or counterparty details.',
    relatedCapabilityIds: ['marketplace-listings', 'public-private-dto-boundary'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'used-surplus',
    label: 'Used & Surplus Equipment',
    route: '/marketplace/used-surplus',
    capabilityStatus: 'partial',
    visibility: 'public',
    criticality: 'launch-critical',
    publicLabel: 'Reviewed asset summaries; diligence and availability private',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Availability, source, counterparty identity, pricing and diligence materials require reviewed private routing.',
    relatedCapabilityIds: ['marketplace-hub', 'public-private-dto-boundary'],
    acceptanceTests: ['npm run test:used-surplus-public-leakage'],
  },
  {
    id: 'business-opportunities',
    label: 'Business Opportunities',
    route: '/marketplace/business-opportunities',
    capabilityStatus: 'request-only',
    visibility: 'mixed',
    criticality: 'launch-critical',
    publicLabel: 'Confidential review before disclosure',
    liveDataExpectation: 'private-routing',
    privateBoundary: 'Parties, terms, assets, distress context, diligence packs and dealroom access are private unless explicitly approved for public-safe summary.',
    relatedCapabilityIds: ['marketplace-business-opportunities', 'reviewed-connections'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'consumables',
    label: 'Consumables & Operating Supplies',
    route: '/marketplace/consumables',
    capabilityStatus: 'partial',
    visibility: 'public',
    criticality: 'launch-critical',
    publicLabel: 'Category orientation with reviewed routing',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Supplier identity, terms, certifications and pricing remain private until reviewed routing.',
    relatedCapabilityIds: ['marketplace-hub'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'new-products',
    label: 'New Products',
    route: '/marketplace/new-products',
    capabilityStatus: 'partial',
    visibility: 'public',
    criticality: 'launch-critical',
    publicLabel: 'Reviewed product summaries; procurement review required',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Supplier claims, specs, certification evidence and procurement terms require review.',
    relatedCapabilityIds: ['marketplace-hub'],
    acceptanceTests: ['npm run test:new-products-equipment-intake'],
  },
  {
    id: 'licensed-inventory',
    label: 'Cannabis Inventory',
    route: '/marketplace/cannabis-inventory',
    capabilityStatus: 'request-only',
    visibility: 'private',
    criticality: 'launch-critical',
    publicLabel: 'Licensed-only review and private routing',
    liveDataExpectation: 'private-routing',
    privateBoundary: 'Licensed product availability, seller identity, batch documentation, pricing and import/export eligibility remain private and review-gated.',
    relatedCapabilityIds: ['marketplace-hub', 'public-private-dto-boundary'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'services',
    label: 'Services',
    route: '/marketplace/services',
    capabilityStatus: 'fallback-backed',
    visibility: 'public',
    criticality: 'launch-critical',
    publicLabel: 'Approved service listings when available; orientation otherwise',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Service provider contact details, diligence evidence and availability remain private until reviewed routing.',
    relatedCapabilityIds: ['marketplace-services'],
    acceptanceTests: ['npm run test:full-scope:fallbacks', 'npm run test:services-public-leakage'],
  },
  {
    id: 'wanted-requests',
    label: 'Wanted Requests',
    route: '/marketplace/wanted',
    capabilityStatus: 'request-only',
    visibility: 'mixed',
    criticality: 'launch-critical',
    publicLabel: 'Demand capture reviewed before routing',
    liveDataExpectation: 'request-capture',
    privateBoundary: 'Buyer identity, demand specifics and procurement criteria are private unless a public-safe wanted summary is approved.',
    relatedCapabilityIds: ['marketplace-wanted'],
    acceptanceTests: ['npm run test:intake-workflow-safety'],
  },
  {
    id: 'genetics',
    label: 'Genetics, Seeds & Tissue Culture',
    route: '/marketplace/genetics',
    capabilityStatus: 'partial',
    visibility: 'mixed',
    criticality: 'launch-critical',
    publicLabel: 'Controlled showcase; compliance-gated routing',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Propagation details, licensing terms, jurisdiction eligibility and counterparty access require review.',
    relatedCapabilityIds: ['marketplace-hub', 'public-private-dto-boundary'],
    acceptanceTests: ['npm run test:genetics-profile-redaction', 'npm run test:genetics-routing'],
  },
  {
    id: 'request-introduction',
    label: 'Request Introduction',
    route: '/intake',
    capabilityStatus: 'request-only',
    visibility: 'mixed',
    criticality: 'launch-critical',
    publicLabel: 'Confidential routing request; no automatic introduction',
    liveDataExpectation: 'request-capture',
    privateBoundary: 'Introductions, counterparty identity and commercial terms require Harbourview review and party approval.',
    relatedCapabilityIds: ['confidential-intake', 'reviewed-connections'],
    acceptanceTests: ['npm run test:intake-workflow-safety'],
  },
  {
    id: 'cultivation-equipment',
    label: 'Cultivation Equipment & Infrastructure',
    route: '/marketplace/cultivation-equipment',
    capabilityStatus: 'partial',
    visibility: 'public',
    criticality: 'launch-critical',
    publicLabel: 'Reviewed equipment summaries; diligence and availability private',
    liveDataExpectation: 'live-approved-records',
    privateBoundary: 'Equipment authority, specification, pricing and counterparty identity require Harbourview review and qualification.',
    relatedCapabilityIds: ['marketplace-hub', 'used-surplus'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'distressed-inventory',
    label: 'Distressed Inventory',
    route: '/marketplace/distressed-inventory',
    capabilityStatus: 'request-only',
    visibility: 'mixed',
    criticality: 'launch-critical',
    publicLabel: 'Confidential intake; sanitised summaries only',
    liveDataExpectation: 'private-routing',
    privateBoundary: 'Seller identity, product details, pricing and diligence materials are never disclosed without qualification and party approval.',
    relatedCapabilityIds: ['marketplace-hub', 'reviewed-connections', 'business-opportunities'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'distressed-businesses',
    label: 'Distressed Businesses & Assets',
    route: '/marketplace/distressed-businesses',
    capabilityStatus: 'request-only',
    visibility: 'mixed',
    criticality: 'launch-critical',
    publicLabel: 'Confidential intake; qualified counterparty access only',
    liveDataExpectation: 'private-routing',
    privateBoundary: 'Party identity, financials, distress context, diligence packs and dealroom access are private unless explicitly approved for public-safe summary.',
    relatedCapabilityIds: ['business-opportunities', 'reviewed-connections', 'qualified-access'],
    acceptanceTests: ['npm run test:visibility'],
  },
  {
    id: 'qualified-access',
    label: 'Qualified Access & Protected Dealrooms',
    route: '/marketplace/qualified-access',
    capabilityStatus: 'request-only',
    visibility: 'mixed',
    criticality: 'launch-critical',
    publicLabel: 'Request-only; Harbourview review before any access granted',
    liveDataExpectation: 'private-routing',
    privateBoundary: 'Dealroom documents, counterparty identity, transaction terms and diligence materials require qualification, review and party approval.',
    relatedCapabilityIds: ['reviewed-connections', 'distressed-businesses', 'business-opportunities'],
    acceptanceTests: ['npm run test:intake-workflow-safety'],
  },
]

export function getMarketplaceCategoryCapability(id: string) {
  return marketplaceCategoryCapabilityMap.find((category) => category.id === id)
}
