export const NEW_PRODUCTS_CATEGORY = 'New Products' as const;
export const EQUIPMENT_SUBCATEGORIES = ['Extraction Equipment','Cultivation Equipment','Packaging Equipment','Post-Harvest Equipment','Climate Control Equipment','Processing Equipment','Facility Infrastructure','Lab Equipment'] as const;
export const EQUIPMENT_LISTING_TYPES = ['Equipment Listing','Supplier Equipment Listing','Equipment Inquiry Candidate'] as const;
export const EQUIPMENT_IMAGE_STATUSES = ['supplier_provided','licensed_stock','public_source_reviewed','verified'] as const;
const UNSAFE_PUBLIC_CLAIM_TERMS = ['guaranteed buyer','guaranteed route','confirmed buyers','exclusive access','available now','licensed supplier','verified supplier','health canada approved','fda approved'] as const;
export type EquipmentSubcategory = (typeof EQUIPMENT_SUBCATEGORIES)[number];
export type EquipmentListingType = (typeof EQUIPMENT_LISTING_TYPES)[number];
export function isEquipmentSubcategory(value: string): value is EquipmentSubcategory { return (EQUIPMENT_SUBCATEGORIES as readonly string[]).includes(value); }
export function isEquipmentListingType(value: string): value is EquipmentListingType { return (EQUIPMENT_LISTING_TYPES as readonly string[]).includes(value); }
export function findUnsafePublicEquipmentClaims(value: string) { const haystack = value.toLowerCase(); return UNSAFE_PUBLIC_CLAIM_TERMS.filter((term) => new RegExp(`(^|[^a-z0-9])${term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}([^a-z0-9]|$)`, 'i').test(haystack)); }
export type EquipmentCandidateDraftReviewInput = { marketplace_category: string; subcategory: string | null; listing_type: string | null; title_public_draft: string | null; description_public_draft: string | null; title_internal: string | null; description_internal: string | null; restricted_item: boolean; requires_license_review: boolean; };
export function getEquipmentDraftApprovalBlockers(candidate: EquipmentCandidateDraftReviewInput) { const blockers: string[] = []; const combinedText = [candidate.title_internal,candidate.description_internal,candidate.title_public_draft,candidate.description_public_draft].filter(Boolean).join(' '); const unsafeClaims = findUnsafePublicEquipmentClaims(combinedText); if (candidate.marketplace_category !== NEW_PRODUCTS_CATEGORY) blockers.push('Invalid marketplace category.'); if (!candidate.subcategory || !isEquipmentSubcategory(candidate.subcategory)) blockers.push('Invalid or missing equipment subcategory.'); if (!candidate.listing_type || !isEquipmentListingType(candidate.listing_type)) blockers.push('Invalid or missing equipment listing type.'); if (!candidate.title_public_draft?.trim()) blockers.push('Public draft title is required.'); if (!candidate.description_public_draft?.trim()) blockers.push('Public draft description is required.'); if (candidate.restricted_item || unsafeClaims.length > 0) blockers.push('This equipment candidate contains unsafe public claims and cannot be approved for public marketplace use.'); if (candidate.requires_license_review) blockers.push('This equipment candidate requires licence review before public marketplace use.'); return blockers; }
