import type {
  MarketplaceCategoryKey,
  MarketplaceListingTypeKey,
  MarketplaceMonetizationPath,
  MarketplaceRecordType,
  MarketplaceSection,
  MarketplaceVisibilityMode,
} from './marketplaceTypes'

export type MarketplaceCategoryDefinition = {
  key: MarketplaceCategoryKey
  publicLabel: string
  internalLabel: string
  route: string
  parentKey?: MarketplaceCategoryKey
  marketplaceSection: MarketplaceSection
  allowedListingTypes: MarketplaceListingTypeKey[]
  allowedRecordTypes: MarketplaceRecordType[]
  publicVisibilityMode: MarketplaceVisibilityMode
  defaultCtaLabel: string
  defaultMonetizationPath: MarketplaceMonetizationPath
  requiresLicenseReview: boolean
  restrictedByDefault: boolean
  requiredVerificationFields: string[]
  requiredPublicFields: string[]
  allowedPublicFields: string[]
  forbiddenPublicClaims: string[]
}

const DEFAULT_PUBLIC_FIELDS = [
  'id',
  'slug',
  'title',
  'description',
  'category',
  'subcategory',
  'marketplace_section',
  'product_type',
  'region',
  'condition',
  'location_country',
  'location_region',
  'price_display',
  'price_currency',
  'is_featured',
  'high_level_specs',
  'created_at',
  'cta_label',
]

const DEFAULT_FORBIDDEN_CLAIMS = [
  'guaranteed availability',
  'verified seller contact',
  'certified supply',
  'guaranteed licence status',
  'guaranteed transaction',
]

function category(input: Omit<MarketplaceCategoryDefinition, 'requiredPublicFields' | 'allowedPublicFields' | 'forbiddenPublicClaims'> & Partial<Pick<MarketplaceCategoryDefinition, 'requiredPublicFields' | 'allowedPublicFields' | 'forbiddenPublicClaims'>>): MarketplaceCategoryDefinition {
  return {
    ...input,
    requiredPublicFields: input.requiredPublicFields ?? ['id', 'title', 'description', 'category', 'marketplace_section', 'created_at'],
    allowedPublicFields: input.allowedPublicFields ?? DEFAULT_PUBLIC_FIELDS,
    forbiddenPublicClaims: input.forbiddenPublicClaims ?? DEFAULT_FORBIDDEN_CLAIMS,
  }
}

export const MARKETPLACE_TAXONOMY: MarketplaceCategoryDefinition[] = [
  category({
    key: 'consumables',
    publicLabel: 'Consumables & Operating Supplies',
    internalLabel: 'Consumables supply',
    route: '/marketplace/consumables',
    marketplaceSection: 'supply',
    allowedListingTypes: ['consumables', 'wanted_request'],
    allowedRecordTypes: ['consumable', 'supplier', 'buyer_demand_signal'],
    publicVisibilityMode: 'public_allowed',
    defaultCtaLabel: 'Contact seller',
    defaultMonetizationPath: 'quote_routing',
    requiresLicenseReview: false,
    restrictedByDefault: false,
    requiredVerificationFields: ['source_url', 'category_fit', 'commercial_relevance', 'seller_or_source_identity'],
  }),
  category({
    key: 'packaging',
    publicLabel: 'Packaging',
    internalLabel: 'Packaging supply',
    route: '/marketplace/packaging',
    parentKey: 'consumables',
    marketplaceSection: 'supply',
    allowedListingTypes: ['consumables', 'new_product', 'wanted_request'],
    allowedRecordTypes: ['consumable', 'supplier'],
    publicVisibilityMode: 'public_allowed',
    defaultCtaLabel: 'Contact seller',
    defaultMonetizationPath: 'quote_routing',
    requiresLicenseReview: false,
    restrictedByDefault: false,
    requiredVerificationFields: ['source_url', 'material_or_format', 'region_available', 'seller_or_source_identity'],
  }),
  category({
    key: 'new_products',
    publicLabel: 'New Products',
    internalLabel: 'New product supply',
    route: '/marketplace/new-products',
    marketplaceSection: 'supply',
    allowedListingTypes: ['new_product', 'consumables'],
    allowedRecordTypes: ['equipment', 'consumable', 'supplier'],
    publicVisibilityMode: 'public_allowed',
    defaultCtaLabel: 'Request quote',
    defaultMonetizationPath: 'quote_routing',
    requiresLicenseReview: false,
    restrictedByDefault: false,
    requiredVerificationFields: ['source_url', 'seller_or_source_identity', 'commercial_relevance'],
  }),
  category({
    key: 'used_surplus',
    publicLabel: 'Used & Surplus',
    internalLabel: 'Used and surplus equipment',
    route: '/marketplace/used-surplus',
    marketplaceSection: 'used_surplus',
    allowedListingTypes: ['used_surplus_equipment', 'distressed_inventory', 'wanted_request'],
    allowedRecordTypes: ['used_equipment', 'distressed_asset', 'equipment'],
    publicVisibilityMode: 'public_allowed',
    defaultCtaLabel: 'Contact seller',
    defaultMonetizationPath: 'seller_commission',
    requiresLicenseReview: false,
    restrictedByDefault: false,
    requiredVerificationFields: ['condition', 'location', 'seller_authority', 'availability_status'],
  }),
  category({
    key: 'cultivation_equipment',
    publicLabel: 'Cultivation Equipment',
    internalLabel: 'Cultivation equipment',
    route: '/marketplace/cultivation-equipment',
    marketplaceSection: 'equipment',
    allowedListingTypes: ['cultivation_equipment', 'used_surplus_equipment', 'wanted_request'],
    allowedRecordTypes: ['equipment', 'used_equipment', 'supplier'],
    publicVisibilityMode: 'public_allowed',
    defaultCtaLabel: 'Contact seller',
    defaultMonetizationPath: 'seller_commission',
    requiresLicenseReview: false,
    restrictedByDefault: false,
    requiredVerificationFields: ['equipment_specs', 'condition_or_new_status', 'seller_or_source_identity'],
  }),
  category({
    key: 'processing_equipment',
    publicLabel: 'Processing Equipment',
    internalLabel: 'Processing equipment',
    route: '/marketplace/processing-equipment',
    marketplaceSection: 'equipment',
    allowedListingTypes: ['processing_equipment', 'used_surplus_equipment', 'wanted_request'],
    allowedRecordTypes: ['equipment', 'used_equipment', 'supplier'],
    publicVisibilityMode: 'public_allowed',
    defaultCtaLabel: 'Contact seller',
    defaultMonetizationPath: 'seller_commission',
    requiresLicenseReview: false,
    restrictedByDefault: false,
    requiredVerificationFields: ['equipment_specs', 'condition_or_new_status', 'seller_or_source_identity'],
  }),
  category({
    key: 'lab_testing',
    publicLabel: 'Labs & Testing',
    internalLabel: 'Lab and testing',
    route: '/marketplace/labs-testing',
    marketplaceSection: 'services',
    allowedListingTypes: ['service', 'new_product', 'wanted_request'],
    allowedRecordTypes: ['service', 'equipment', 'consumable', 'partner'],
    publicVisibilityMode: 'public_allowed',
    defaultCtaLabel: 'Request quote',
    defaultMonetizationPath: 'service_provider_referral',
    requiresLicenseReview: true,
    restrictedByDefault: false,
    requiredVerificationFields: ['jurisdiction_served', 'service_scope', 'source_url'],
  }),
  category({
    key: 'logistics',
    publicLabel: 'Logistics',
    internalLabel: 'Logistics and warehousing',
    route: '/marketplace/logistics',
    marketplaceSection: 'services',
    allowedListingTypes: ['service', 'wanted_request'],
    allowedRecordTypes: ['service', 'partner'],
    publicVisibilityMode: 'public_allowed',
    defaultCtaLabel: 'Request quote',
    defaultMonetizationPath: 'service_provider_referral',
    requiresLicenseReview: true,
    restrictedByDefault: false,
    requiredVerificationFields: ['jurisdiction_served', 'service_scope', 'source_url'],
  }),
  category({
    key: 'services',
    publicLabel: 'Services',
    internalLabel: 'Marketplace services',
    route: '/marketplace/services',
    marketplaceSection: 'services',
    allowedListingTypes: ['service', 'wanted_request'],
    allowedRecordTypes: ['service', 'partner'],
    publicVisibilityMode: 'public_allowed',
    defaultCtaLabel: 'Request quote',
    defaultMonetizationPath: 'service_provider_referral',
    requiresLicenseReview: false,
    restrictedByDefault: false,
    requiredVerificationFields: ['service_scope', 'jurisdiction_served', 'source_url'],
  }),
  category({
    key: 'professional_services',
    publicLabel: 'Professional Services',
    internalLabel: 'Professional services',
    route: '/marketplace/professional-services',
    marketplaceSection: 'services',
    allowedListingTypes: ['service'],
    allowedRecordTypes: ['service', 'partner'],
    publicVisibilityMode: 'public_allowed',
    defaultCtaLabel: 'Request quote',
    defaultMonetizationPath: 'service_provider_referral',
    requiresLicenseReview: false,
    restrictedByDefault: false,
    requiredVerificationFields: ['service_scope', 'source_url', 'jurisdiction_served'],
  }),
  category({
    key: 'distressed_inventory',
    publicLabel: 'Distressed Inventory',
    internalLabel: 'Distressed inventory',
    route: '/marketplace/distressed-inventory',
    marketplaceSection: 'distressed',
    allowedListingTypes: ['distressed_inventory', 'used_surplus_equipment'],
    allowedRecordTypes: ['distressed_asset', 'used_equipment'],
    publicVisibilityMode: 'teaser_only',
    defaultCtaLabel: 'Request confidential review',
    defaultMonetizationPath: 'distressed_asset_mandate',
    requiresLicenseReview: true,
    restrictedByDefault: true,
    requiredVerificationFields: ['distress_signal', 'seller_authority', 'confidentiality_level'],
  }),
  category({
    key: 'distressed_businesses',
    publicLabel: 'Distressed Businesses',
    internalLabel: 'Distressed businesses',
    route: '/marketplace/distressed-businesses',
    marketplaceSection: 'distressed',
    allowedListingTypes: ['distressed_businesses', 'business_opportunity'],
    allowedRecordTypes: ['distressed_asset', 'partner'],
    publicVisibilityMode: 'private_gated',
    defaultCtaLabel: 'Request private access',
    defaultMonetizationPath: 'distressed_asset_mandate',
    requiresLicenseReview: true,
    restrictedByDefault: true,
    requiredVerificationFields: ['seller_authority', 'confidentiality_level', 'diligence_materials_available'],
  }),
  category({
    key: 'business_opportunities',
    publicLabel: 'Business Opportunities',
    internalLabel: 'Business opportunities',
    route: '/marketplace/business-opportunities',
    marketplaceSection: 'trade',
    allowedListingTypes: ['business_opportunity', 'featured_network_opportunity'],
    allowedRecordTypes: ['partner', 'data_signal'],
    publicVisibilityMode: 'teaser_only',
    defaultCtaLabel: 'Request opportunity review',
    defaultMonetizationPath: 'success_fee',
    requiresLicenseReview: true,
    restrictedByDefault: true,
    requiredVerificationFields: ['commercial_context', 'source_url', 'confidentiality_level'],
  }),
  category({
    key: 'export_ready',
    publicLabel: 'Export Ready',
    internalLabel: 'Export-ready supply',
    route: '/marketplace/export-ready',
    marketplaceSection: 'trade',
    allowedListingTypes: ['cannabis_inventory', 'qualified_access_request'],
    allowedRecordTypes: ['supplier', 'buyer_demand_signal'],
    publicVisibilityMode: 'private_gated',
    defaultCtaLabel: 'Request export access review',
    defaultMonetizationPath: 'success_fee',
    requiresLicenseReview: true,
    restrictedByDefault: true,
    requiredVerificationFields: ['licence_review', 'jurisdiction', 'counterparty_qualification'],
  }),
  category({
    key: 'import_demand',
    publicLabel: 'Import Demand',
    internalLabel: 'Import demand',
    route: '/marketplace/import-demand',
    marketplaceSection: 'trade',
    allowedListingTypes: ['wanted_request', 'qualified_access_request'],
    allowedRecordTypes: ['buyer_demand_signal'],
    publicVisibilityMode: 'private_gated',
    defaultCtaLabel: 'Request demand access review',
    defaultMonetizationPath: 'buyer_sourcing_mandate',
    requiresLicenseReview: true,
    restrictedByDefault: true,
    requiredVerificationFields: ['buyer_qualification', 'jurisdiction', 'documentation_required'],
  }),
  category({
    key: 'cannabis_inventory',
    publicLabel: 'Cannabis Inventory',
    internalLabel: 'Cannabis inventory',
    route: '/marketplace/cannabis-inventory',
    marketplaceSection: 'trade',
    allowedListingTypes: ['cannabis_inventory'],
    allowedRecordTypes: ['supplier', 'buyer_demand_signal'],
    publicVisibilityMode: 'private_gated',
    defaultCtaLabel: 'Request qualified access',
    defaultMonetizationPath: 'success_fee',
    requiresLicenseReview: true,
    restrictedByDefault: true,
    requiredVerificationFields: ['licence_review', 'seller_authority', 'buyer_qualification'],
  }),
  category({
    key: 'genetics',
    publicLabel: 'Genetics',
    internalLabel: 'Genetics program',
    route: '/marketplace/genetics',
    marketplaceSection: 'trade',
    allowedListingTypes: ['genetics_program', 'qualified_access_request'],
    allowedRecordTypes: ['supplier', 'partner'],
    publicVisibilityMode: 'private_gated',
    defaultCtaLabel: 'Request genetics access review',
    defaultMonetizationPath: 'success_fee',
    requiresLicenseReview: true,
    restrictedByDefault: true,
    requiredVerificationFields: ['licence_review', 'jurisdiction', 'seller_authority'],
  }),
  category({
    key: 'wanted_requests',
    publicLabel: 'Wanted Requests',
    internalLabel: 'Buyer wanted requests',
    route: '/marketplace/wanted',
    marketplaceSection: 'wanted',
    allowedListingTypes: ['wanted_request'],
    allowedRecordTypes: ['buyer_demand_signal'],
    publicVisibilityMode: 'teaser_only',
    defaultCtaLabel: 'Submit matching supply',
    defaultMonetizationPath: 'buyer_sourcing_mandate',
    requiresLicenseReview: true,
    restrictedByDefault: false,
    requiredVerificationFields: ['buyer_type', 'required_specs', 'delivery_region'],
  }),
  category({
    key: 'qualified_access',
    publicLabel: 'Qualified Access',
    internalLabel: 'Qualified access',
    route: '/marketplace/qualified-access',
    marketplaceSection: 'qualified_access',
    allowedListingTypes: ['qualified_access_request'],
    allowedRecordTypes: ['buyer_demand_signal', 'source_only'],
    publicVisibilityMode: 'admin_only',
    defaultCtaLabel: 'Request access review',
    defaultMonetizationPath: 'manual_review',
    requiresLicenseReview: true,
    restrictedByDefault: true,
    requiredVerificationFields: ['identity_review', 'licence_review', 'routing_context'],
  }),
  category({
    key: 'education',
    publicLabel: 'Education',
    internalLabel: 'Marketplace education',
    route: '/education',
    marketplaceSection: 'education',
    allowedListingTypes: ['education_resource', 'service'],
    allowedRecordTypes: ['education', 'partner', 'service'],
    publicVisibilityMode: 'public_allowed',
    defaultCtaLabel: 'Review education resource',
    defaultMonetizationPath: 'education_to_introduction',
    requiresLicenseReview: false,
    restrictedByDefault: false,
    requiredVerificationFields: ['provider_source', 'audience', 'topic'],
  }),
]

export const MARKETPLACE_CATEGORY_KEYS = MARKETPLACE_TAXONOMY.map((category) => category.key)

export function getMarketplaceCategory(key: string | null | undefined) {
  if (!key) return undefined
  return MARKETPLACE_TAXONOMY.find((category) => category.key === key)
}

export function isMarketplaceCategoryKey(value: string): value is MarketplaceCategoryKey {
  return MARKETPLACE_CATEGORY_KEYS.includes(value as MarketplaceCategoryKey)
}

export function getPublicMarketplaceCategories() {
  return MARKETPLACE_TAXONOMY.filter((category) => category.publicVisibilityMode !== 'admin_only')
}
