import { requireAdminAuth } from '@/lib/auth/adminGuard';
import { fetchAdminSupabaseJson, getAdminError } from '@/lib/supabase/adminDataClient';
import { markEducationModuleReviewed } from './actions';

// Force dynamic: admin content must never be statically cached
export const dynamic = 'force-dynamic';

type EducationModuleRow = {
  id: string;
  slug: string;
  title: string;
  track_id: string | null;
  sensitivity: string | null;
  publication_state: string | null;
  content_review_status: string | null;
  reviewed_by: string | null;
  reviewed_at: string | null;
  updated_at: string;
};

export default async function EducationReviewPage() {
  await requireAdminAuth();

  const result = await fetchAdminSupabaseJson<EducationModuleRow[]>(
    '/rest/v1/education_modules?select=id,slug,title,track_id,sensitivity,publication_state,content_review_status,reviewed_by,reviewed_at,updated_at&order=updated_at.desc',
  );

  if (!result.ok) {
    const error = getAdminError(result);
    return (
      <div className="rounded-2xl border border-amber-500/30 bg-amber-500/10 p-5 text-sm text-amber-200">
        {error.message}
      </div>
    );
  }

  const modules = result.data ?? [];
  const pending = modules.filter((m) => m.content_review_status === 'ai_generated_pending_review');
  const reviewed = modules.filter((m) => m.content_review_status !== 'ai_generated_pending_review');

  return (
    <div className="space-y-8">
      <div>
        <h2 className="text-xl font-semibold text-[#F5F1E8]">Education content review</h2>
        <p className="mt-1 max-w-2xl text-sm leading-6 text-[#F5F1E8]/60">
          {pending.length} item{pending.length === 1 ? '' : 's'} generated by the batch content pipeline and never
          reviewed. Marking an item reviewed does not change its publication state — published items stay published
          either way. This list reflects <code>education_modules</code> directly; it does not cover the separate
          <code> clinical_education_modules</code> table (6 rows, last touched Jun 22) or the unrelated, empty
          <code> hv_claims</code>/<code>hv_claim_reviews</code> tables, which were investigated and found to have no
          producer and no data — out of scope for this pass.
        </p>
      </div>

      {pending.length > 0 && (
        <section>
          <h3 className="mb-3 text-xs uppercase tracking-[0.2em] text-amber-400">
            Pending review ({pending.length})
          </h3>
          <div className="space-y-3">
            {pending.map((item) => (
              <div key={item.id} className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-4">
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div>
                    <p className="font-medium text-[#F5F1E8]">{item.title}</p>
                    <p className="mt-1 text-xs text-[#F5F1E8]/50">
                      {item.slug} · track {item.track_id ?? '—'} · sensitivity {item.sensitivity ?? '—'} ·{' '}
                      <span className={item.publication_state === 'published' ? 'text-amber-400' : ''}>
                        {item.publication_state === 'published' ? 'LIVE, published' : item.publication_state ?? '—'}
                      </span>
                    </p>
                  </div>
                  <form action={markEducationModuleReviewed.bind(null, item.id)}>
                    <button
                      type="submit"
                      className="rounded-full border border-[#C6A55A]/40 px-3 py-1.5 text-xs text-[#C6A55A] transition hover:bg-[#C6A55A]/10"
                    >
                      Mark reviewed
                    </button>
                  </form>
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      <section>
        <h3 className="mb-3 text-xs uppercase tracking-[0.2em] text-[#F5F1E8]/40">
          Reviewed / original ({reviewed.length})
        </h3>
        <div className="space-y-2">
          {reviewed.map((item) => (
            <div
              key={item.id}
              className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-white/10 px-4 py-2 text-sm"
            >
              <span className="text-[#F5F1E8]/80">{item.title}</span>
              <span className="text-xs text-[#F5F1E8]/40">
                {item.content_review_status ?? '—'}
                {item.reviewed_at ? ` · reviewed ${new Date(item.reviewed_at).toLocaleDateString()}` : ''}
              </span>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
