// lib/scrapers/sources.ts
// Master source registry for all marketplace categories.
// status: 'enabled' → live fetch. 'needs-review' → fetch but don't auto-insert. 'disabled' → skip.

import type { ScraperSource } from './types'

export const scraperSources: ScraperSource[] = [

  // ── USED & SURPLUS EQUIPMENT ────────────────────────────────────────────────
  {
    id: 'aaron-equipment',
    name: 'Aaron Equipment Company',
    url: 'https://www.aaronequipment.com',
    searchUrl: 'https://www.aaronequipment.com/listing/pharmaceutical-processing-equipment/',
    category: 'used_surplus',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 24,
    region: 'north_america',
    notes: 'Worlds largest stocking used pharmaceutical and cannabis processing equipment dealer.',
  },
  {
    id: 'federal-equipment',
    name: 'Federal Equipment Company',
    url: 'https://www.fedequip.com',
    searchUrl: 'https://www.fedequip.com/extraction-and-growing-technologies',
    category: 'used_surplus',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 24,
    region: 'north_america',
    notes: 'Used extraction and growing technology equipment listings.',
  },
  {
    id: 'surplus-record-cannabis',
    name: 'Surplus Record — Cannabis Processing',
    url: 'https://www.surplusrecord.com',
    searchUrl: 'https://www.surplusrecord.com/machinery-equipment/cannabis-processing-machinery/',
    category: 'used_surplus',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 12,
    region: 'north_america',
    notes: 'Active used cannabis processing machinery listings — Apeks, Precision, Vitalis.',
  },
  {
    id: '420equipment',
    name: '420Equipment.com',
    url: 'https://www.420equipment.com',
    searchUrl: 'https://www.420equipment.com/listings',
    category: 'used_surplus',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 12,
    region: 'north_america',
    notes: 'Primary peer-to-peer cannabis equipment marketplace. Private sellers and facility closures.',
  },
  {
    id: 'urth-fyre',
    name: 'Urth & Fyre Equipment',
    url: 'https://www.urthfyre.com',
    searchUrl: 'https://www.urthfyre.com/listings',
    category: 'used_surplus',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 24,
    region: 'north_america',
    notes: 'Verified cannabis equipment marketplace — condition-checked before listing.',
  },

  // ── PROCESSING EQUIPMENT ────────────────────────────────────────────────────
  {
    id: 'bidspotter-cannabis',
    name: 'BidSpotter — Cannabis & Processing Auctions',
    url: 'https://www.bidspotter.com',
    searchUrl: 'https://www.bidspotter.com/en-us/auction-catalogues?q=cannabis+extraction',
    category: 'processing_equipment',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 12,
    region: 'north_america',
    notes: 'Industrial auction platform — heritage global, Aaron Equipment, and other houses list here.',
  },
  {
    id: 'machinio-extraction',
    name: 'Machinio — Extraction Equipment',
    url: 'https://www.machinio.com',
    searchUrl: 'https://www.machinio.com/search?q=extraction+equipment&subcategory=cannabis',
    category: 'processing_equipment',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 24,
    region: 'global',
    notes: 'Global machinery marketplace aggregator. Covers CO2, ethanol, hydrocarbon extractors.',
  },

  // ── CULTIVATION EQUIPMENT ───────────────────────────────────────────────────
  {
    id: 'horticulture-source',
    name: 'Horticulture Source — Commercial Grow Equipment',
    url: 'https://www.horticulture-source.com',
    searchUrl: 'https://www.horticulture-source.com/commercial',
    category: 'cultivation_equipment',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 48,
    region: 'north_america',
    notes: 'Commercial horticultural equipment supplier — LEDs, HVAC, benching, controls.',
  },
  {
    id: 'growershouse',
    name: 'Growers House — Commercial Grow',
    url: 'https://growershouse.com',
    searchUrl: 'https://growershouse.com/collections/commercial-grow-equipment',
    category: 'cultivation_equipment',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 48,
    region: 'north_america',
    notes: 'Commercial cannabis cultivation equipment and infrastructure.',
  },

  // ── PACKAGING ───────────────────────────────────────────────────────────────
  {
    id: 'dragon-chewer',
    name: 'Dragon Chewer Wholesale Packaging',
    url: 'https://www.dragonchewer.com',
    searchUrl: 'https://www.dragonchewer.com/wholesale',
    category: 'packaging',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 48,
    region: 'north_america',
    notes: 'Cannabis-specific wholesale packaging: CR bags, pop-tops, pre-roll tubes, mylar, labels.',
  },
  {
    id: 'mj-wholesale-packaging',
    name: 'MJ Wholesale — Packaging',
    url: 'https://mjwholesale.com',
    searchUrl: 'https://mjwholesale.com/collections/packaging',
    category: 'packaging',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 48,
    region: 'north_america',
    notes: 'Wide range of compliant cannabis packaging formats. CR mylar bags, jars, tubes.',
  },
  {
    id: 'medlock-canada',
    name: 'MedLock (CannaLock) — Pharmaceutical Packaging',
    url: 'https://www.medlockglobal.com',
    searchUrl: 'https://www.medlockglobal.com/cannabis',
    category: 'packaging',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 72,
    region: 'north_america',
    notes: 'Canadian cannabis packaging certified to Cannabis Act, FDA, EU standards.',
  },

  // ── LABS & TESTING ──────────────────────────────────────────────────────────
  {
    id: 'anab-cannabis-labs',
    name: 'ANAB ISO 17025 Cannabis Lab Directory',
    url: 'https://anab.ansi.org',
    searchUrl: 'https://search.anab.org/search?q=cannabis&accreditation=ISO+17025',
    category: 'labs_testing',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168, // weekly — directory is stable
    region: 'north_america',
    notes: 'Official ANAB accreditation directory. ISO 17025 cannabis labs — authoritative source.',
  },
  {
    id: 'labstat-certified-group',
    name: 'Labstat — Certified Group',
    url: 'https://www.labstat.com',
    searchUrl: 'https://www.labstat.com/services/cannabis-testing',
    category: 'labs_testing',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'ISO 17025, GMP-compliant. Meets Health Canada and EU export requirements.',
  },
  {
    id: 'certified-laboratories',
    name: 'Certified Laboratories',
    url: 'https://www.certifiedlabs.com',
    searchUrl: 'https://www.certifiedlabs.com/cannabis-testing',
    category: 'labs_testing',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'ISO 17025, DEA-registered, multiple cGMP-certified locations.',
  },

  // ── LOGISTICS ───────────────────────────────────────────────────────────────
  {
    id: 'mmm-transport',
    name: 'MMM Transport — Cannabis Logistics',
    url: 'https://www.mmmtransport.com',
    searchUrl: 'https://www.mmmtransport.com/services',
    category: 'logistics',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Licensed cannabis transporter. MA, CT, NY, NJ, MI, MN expansion. ~70% MA market.',
  },
  {
    id: 'ziing-cannabis',
    name: 'Ziing — Cannabis Logistics',
    url: 'https://www.ziing.com',
    searchUrl: 'https://www.ziing.com/cannabis',
    category: 'logistics',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Coast-to-coast cannabis logistics, temperature control, IoT tracking, chain-of-signature.',
  },

  // ── PROFESSIONAL SERVICES ───────────────────────────────────────────────────
  {
    id: 'verdant-strategies',
    name: 'Verdant Strategies — Cannabis Advisory',
    url: 'https://www.verdantstrategies.com',
    searchUrl: 'https://www.verdantstrategies.com/services',
    category: 'professional_services',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'CPA and advisory firm: accounting, tax, CFO, M&A, investor readiness, litigation.',
  },
  {
    id: 'new-holland-group',
    name: 'New Holland Group — Market Access',
    url: 'https://www.newhollandgroup.com',
    searchUrl: 'https://www.newhollandgroup.com/services',
    category: 'professional_services',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'global',
    notes: 'Capital, compliance, cross-border expansion — EU-US transatlantic operators.',
  },

  // ── CANNABIS INVENTORY / EXPORT-READY ──────────────────────────────────────
  {
    id: 'mjbizdirectory-producers',
    name: 'MJBizDirectory — Licensed Producers',
    url: 'https://mjbizdirectory.com',
    searchUrl: 'https://mjbizdirectory.com/category/cultivators-growers/',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'needs-review',
    cadenceHours: 168,
    region: 'global',
    notes: 'Industry directory — cultivators and producers. Requires parser validation.',
  },
  {
    id: 'eu-gmp-database',
    name: 'EMA EudraGMDP — EU GMP Certified Cannabis Producers',
    url: 'https://eudragmdp.ema.europa.eu',
    searchUrl: 'https://eudragmdp.ema.europa.eu/inspections/view/searchGMPNonCompliance.xhtml',
    category: 'export_ready',
    parserType: 'html-card',
    status: 'needs-review',
    cadenceHours: 168,
    region: 'europe',
    notes: 'EMA official EU GMP compliance database. Authoritative for EU export-ready qualification.',
  },
]

export function getEnabledSources(): ScraperSource[] {
  return scraperSources.filter((s) => s.status === 'enabled')
}

export function getSourcesByCategory(category: string): ScraperSource[] {
  return scraperSources.filter((s) => s.category === category && s.status !== 'disabled')
}
