// lib/scrapers/sources.ts
// Master source registry for all marketplace categories.
// status: 'enabled' → live fetch. 'needs-review' → fetch but don't auto-insert. 'disabled' → skip.

import type { ScraperSource } from './types'

export const scraperSources: ScraperSource[] = [

  // ── USED & SURPLUS EQUIPMENT ────────────────────────────────────────────────
  {
    id: 'aaron-equipment',
    name: 'Aaron Equipment Company',
    url: 'https://www.aaronequipment.com',
    searchUrl: 'https://www.aaronequipment.com/listing/pharmaceutical-processing-equipment/',
    category: 'used_surplus',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 24,
    region: 'north_america',
    notes: 'Worlds largest stocking used pharmaceutical and cannabis processing equipment dealer.',
  },
  {
    id: 'federal-equipment',
    name: 'Federal Equipment Company',
    url: 'https://www.fedequip.com',
    searchUrl: 'https://www.fedequip.com/extraction-and-growing-technologies',
    category: 'used_surplus',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 24,
    region: 'north_america',
    notes: 'Used extraction and growing technology equipment listings.',
  },
  {
    id: 'surplus-record-cannabis',
    name: 'Surplus Record — Cannabis Processing',
    url: 'https://www.surplusrecord.com',
    searchUrl: 'https://www.surplusrecord.com/machinery-equipment/cannabis-processing-machinery/',
    category: 'used_surplus',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 12,
    region: 'north_america',
    notes: 'Active used cannabis processing machinery listings — Apeks, Precision, Vitalis.',
  },
  {
    id: '420equipment',
    name: '420Equipment.com',
    url: 'https://www.420equipment.com',
    searchUrl: 'https://www.420equipment.com/listings',
    category: 'used_surplus',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 12,
    region: 'north_america',
    notes: 'Primary peer-to-peer cannabis equipment marketplace. Private sellers and facility closures.',
  },
  {
    id: 'urth-fyre',
    name: 'Urth & Fyre Equipment',
    url: 'https://www.urthfyre.com',
    searchUrl: 'https://www.urthfyre.com/listings',
    category: 'used_surplus',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 24,
    region: 'north_america',
    notes: 'Verified cannabis equipment marketplace — condition-checked before listing.',
  },

  // ── PROCESSING EQUIPMENT ────────────────────────────────────────────────────
  {
    id: 'bidspotter-cannabis',
    name: 'BidSpotter — Cannabis & Processing Auctions',
    url: 'https://www.bidspotter.com',
    searchUrl: 'https://www.bidspotter.com/en-us/auction-catalogues?q=cannabis+extraction',
    category: 'processing_equipment',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 12,
    region: 'north_america',
    notes: 'Industrial auction platform — heritage global, Aaron Equipment, and other houses list here.',
  },
  {
    id: 'machinio-extraction',
    name: 'Machinio — Extraction Equipment',
    url: 'https://www.machinio.com',
    searchUrl: 'https://www.machinio.com/search?q=extraction+equipment&subcategory=cannabis',
    category: 'processing_equipment',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 24,
    region: 'global',
    notes: 'Global machinery marketplace aggregator. Covers CO2, ethanol, hydrocarbon extractors.',
  },

  // ── CULTIVATION EQUIPMENT ───────────────────────────────────────────────────
  {
    id: 'horticulture-source',
    name: 'Horticulture Source — Commercial Grow Equipment',
    url: 'https://www.horticulture-source.com',
    searchUrl: 'https://www.horticulture-source.com/commercial',
    category: 'cultivation_equipment',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 48,
    region: 'north_america',
    notes: 'Commercial horticultural equipment supplier — LEDs, HVAC, benching, controls.',
  },
  {
    id: 'growershouse',
    name: 'Growers House — Commercial Grow',
    url: 'https://growershouse.com',
    searchUrl: 'https://growershouse.com/collections/commercial-grow-equipment',
    category: 'cultivation_equipment',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 48,
    region: 'north_america',
    notes: 'Commercial cannabis cultivation equipment and infrastructure.',
  },

  // ── PACKAGING ───────────────────────────────────────────────────────────────
  {
    id: 'dragon-chewer',
    name: 'Dragon Chewer Wholesale Packaging',
    url: 'https://www.dragonchewer.com',
    searchUrl: 'https://www.dragonchewer.com/wholesale',
    category: 'packaging',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 48,
    region: 'north_america',
    notes: 'Cannabis-specific wholesale packaging: CR bags, pop-tops, pre-roll tubes, mylar, labels.',
  },
  {
    id: 'mj-wholesale-packaging',
    name: 'MJ Wholesale — Packaging',
    url: 'https://mjwholesale.com',
    searchUrl: 'https://mjwholesale.com/collections/packaging',
    category: 'packaging',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 48,
    region: 'north_america',
    notes: 'Wide range of compliant cannabis packaging formats. CR mylar bags, jars, tubes.',
  },
  {
    id: 'medlock-canada',
    name: 'MedLock (CannaLock) — Pharmaceutical Packaging',
    url: 'https://www.medlockglobal.com',
    searchUrl: 'https://www.medlockglobal.com/cannabis',
    category: 'packaging',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 72,
    region: 'north_america',
    notes: 'Canadian cannabis packaging certified to Cannabis Act, FDA, EU standards.',
  },

  // ── LABS & TESTING ──────────────────────────────────────────────────────────
  {
    id: 'anab-cannabis-labs',
    name: 'ANAB ISO 17025 Cannabis Lab Directory',
    url: 'https://anab.ansi.org',
    searchUrl: 'https://search.anab.org/search?q=cannabis&accreditation=ISO+17025',
    category: 'labs_testing',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168, // weekly — directory is stable
    region: 'north_america',
    notes: 'Official ANAB accreditation directory. ISO 17025 cannabis labs — authoritative source.',
  },
  {
    id: 'labstat-certified-group',
    name: 'Labstat — Certified Group',
    url: 'https://www.labstat.com',
    searchUrl: 'https://www.labstat.com/services/cannabis-testing',
    category: 'labs_testing',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'ISO 17025, GMP-compliant. Meets Health Canada and EU export requirements.',
  },
  {
    id: 'certified-laboratories',
    name: 'Certified Laboratories',
    url: 'https://www.certifiedlabs.com',
    searchUrl: 'https://www.certifiedlabs.com/cannabis-testing',
    category: 'labs_testing',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'ISO 17025, DEA-registered, multiple cGMP-certified locations.',
  },

  // ── LOGISTICS ───────────────────────────────────────────────────────────────
  {
    id: 'mmm-transport',
    name: 'MMM Transport — Cannabis Logistics',
    url: 'https://www.mmmtransport.com',
    searchUrl: 'https://www.mmmtransport.com/services',
    category: 'logistics',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Licensed cannabis transporter. MA, CT, NY, NJ, MI, MN expansion. ~70% MA market.',
  },
  {
    id: 'ziing-cannabis',
    name: 'Ziing — Cannabis Logistics',
    url: 'https://www.ziing.com',
    searchUrl: 'https://www.ziing.com/cannabis',
    category: 'logistics',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Coast-to-coast cannabis logistics, temperature control, IoT tracking, chain-of-signature.',
  },

  // ── PROFESSIONAL SERVICES ───────────────────────────────────────────────────
  {
    id: 'verdant-strategies',
    name: 'Verdant Strategies — Cannabis Advisory',
    url: 'https://www.verdantstrategies.com',
    searchUrl: 'https://www.verdantstrategies.com/services',
    category: 'professional_services',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'CPA and advisory firm: accounting, tax, CFO, M&A, investor readiness, litigation.',
  },
  {
    id: 'new-holland-group',
    name: 'New Holland Group — Market Access',
    url: 'https://www.newhollandgroup.com',
    searchUrl: 'https://www.newhollandgroup.com/services',
    category: 'professional_services',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'global',
    notes: 'Capital, compliance, cross-border expansion — EU-US transatlantic operators.',
  },

  // ── CANNABIS INVENTORY / EXPORT-READY ──────────────────────────────────────
  {
    id: 'mjbizdirectory-producers',
    name: 'MJBizDirectory — Licensed Producers',
    url: 'https://mjbizdirectory.com',
    searchUrl: 'https://mjbizdirectory.com/category/cultivators-growers/',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'needs-review',
    cadenceHours: 168,
    region: 'global',
    notes: 'Industry directory — cultivators and producers. Requires parser validation.',
  },
  {
    id: 'eu-gmp-database',
    name: 'EMA EudraGMDP — EU GMP Certified Cannabis Producers',
    url: 'https://eudragmdp.ema.europa.eu',
    searchUrl: 'https://eudragmdp.ema.europa.eu/inspections/view/searchGMPNonCompliance.xhtml',
    category: 'export_ready',
    parserType: 'html-card',
    status: 'needs-review',
    cadenceHours: 168,
    region: 'europe',
    notes: 'EMA official EU GMP compliance database. Authoritative for EU export-ready qualification.',
  },
]

export function getEnabledSources(): ScraperSource[] {
  return scraperSources.filter((s) => s.status === 'enabled')
}

export function getSourcesByCategory(category: string): ScraperSource[

  // ── US STATE REGULATORY DATABASES ──────────────────────────────────────────
  {
    id: 'michigan-cra-licensees',
    name: 'Michigan CRA — Cannabis Licensee Search',
    url: 'https://michigan.gov/cra',
    searchUrl: 'https://michigan.gov/cra/0,9548,7-406-98178_98834---,00.html',
    category: 'cannabis_inventory',
    parserType: 'html-table',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Michigan Cannabis Regulatory Agency. Public licensee database — cultivators, processors, retailers, microbusinesses. Large market.',
  },
  {
    id: 'massachusetts-ccc-licensees',
    name: 'Massachusetts CCC — License Directory',
    url: 'https://masscannabiscontrol.com',
    searchUrl: 'https://masscannabiscontrol.com/licensing/license-type-directory/',
    category: 'cannabis_inventory',
    parserType: 'html-table',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Massachusetts Cannabis Control Commission. Public license directory by type. Adult-use and medical.',
  },
  {
    id: 'new-york-ocm-licensees',
    name: 'New York OCM — Active Licensees',
    url: 'https://cannabis.ny.gov',
    searchUrl: 'https://cannabis.ny.gov/licensing',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'New York Office of Cannabis Management. Rapidly expanding market. CAURD, retail, cultivation, processing licenses.',
  },
  {
    id: 'illinois-ccb-licensees',
    name: 'Illinois CCB — Cannabis License Lookup',
    url: 'https://idfpr.illinois.gov',
    searchUrl: 'https://idfpr.illinois.gov/LicenseLookup/licenseelookup.asp',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Illinois Cannabis Control Board. IDFPR license lookup — cultivators, infusers, dispensers, transporters.',
  },
  {
    id: 'nevada-ccb-licensees',
    name: 'Nevada CCB — Active License List',
    url: 'https://ccb.nv.gov',
    searchUrl: 'https://ccb.nv.gov/list-of-licensed-establishments/',
    category: 'cannabis_inventory',
    parserType: 'html-table',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Nevada Cannabis Compliance Board. Licensed cultivators, producers, distributors, retailers. CSV download available.',
  },
  {
    id: 'washington-lcb-licensees',
    name: 'Washington LCB — Cannabis Licensee Map',
    url: 'https://lcb.wa.gov',
    searchUrl: 'https://lcb.wa.gov/licensing/cannabis-licensing',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Washington State Liquor and Cannabis Board. Public license list — producers, processors, retailers. Includes tier info.',
  },
  {
    id: 'arizona-adhs-licensees',
    name: 'Arizona ADHS — Cannabis Licensee Registry',
    url: 'https://azdhs.gov',
    searchUrl: 'https://azdhs.gov/licensing/medical-marijuana/index.php',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Arizona Department of Health Services. Medical and adult-use dispensary, cultivator, and manufacturer list.',
  },
  {
    id: 'oklahoma-omma-licensees',
    name: 'Oklahoma OMMA — License Search',
    url: 'https://omma.ok.gov',
    searchUrl: 'https://omma.ok.gov/licensing/license-search/',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Oklahoma Medical Marijuana Authority. One of US largest per-capita markets. Growers, processors, dispensaries, transporters.',
  },
  {
    id: 'missouri-dhss-licensees',
    name: 'Missouri DHSS — Cannabis License Lookup',
    url: 'https://cannabis.mo.gov',
    searchUrl: 'https://cannabis.mo.gov/resources/licensee-information/',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Missouri Department of Health and Senior Services. Adult-use licensed facilities. Fast-growing new market.',
  },
  {
    id: 'maryland-mca-licensees',
    name: 'Maryland MCA — License Registry',
    url: 'https://cannabis.maryland.gov',
    searchUrl: 'https://cannabis.maryland.gov/pages/licensing',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Maryland Cannabis Administration. Adult-use launched 2023. Growers, processors, dispensaries, micro-licenses.',
  },
  {
    id: 'new-jersey-crc-licensees',
    name: 'New Jersey CRC — Approved Licenses',
    url: 'https://www.nj.gov/cannabis',
    searchUrl: 'https://www.nj.gov/cannabis/businesses/recreational/approved-licenses/',
    category: 'cannabis_inventory',
    parserType: 'html-table',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'New Jersey Cannabis Regulatory Commission. Approved license list by type. High-value northeast US market.',
  },
  {
    id: 'connecticut-dcp-licensees',
    name: 'Connecticut DCP — Cannabis Licensees',
    url: 'https://portal.ct.gov/DCP',
    searchUrl: 'https://portal.ct.gov/DCP/Medical-Marijuana-Program/Medical-Marijuana---Program-Overview',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Connecticut Department of Consumer Protection. Cannabis producer, retailer, and hybrid retailer license list.',
  },
  {
    id: 'florida-ommu-dispensaries',
    name: 'Florida OMMU — Licensed Dispensing Organizations',
    url: 'https://knowthefactsmmj.com',
    searchUrl: 'https://knowthefactsmmj.com/mmtc/',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Florida Office of Medical Marijuana Use. Licensed treatment centers — vertically integrated. Large medical-only market.',
  },
  {
    id: 'new-mexico-ccd-licensees',
    name: 'New Mexico RLD — Cannabis License Registry',
    url: 'https://www.rld.nm.gov',
    searchUrl: 'https://www.rld.nm.gov/cannabis/',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'New Mexico Regulation and Licensing Department. Cannabis Control Division licensees.',
  },
  {
    id: 'pennsylvania-doh-dispensaries',
    name: 'Pennsylvania DOH — Medical Cannabis Dispensaries',
    url: 'https://www.pa.gov',
    searchUrl: 'https://www.pa.gov/en/agencies/doh/programs-and-services/medical-marijuana.html',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Pennsylvania Department of Health. Approved dispensary and grower/processor list. Medical-only, large population market.',
  },

  // ── CANADIAN PROVINCIAL WHOLESALE ─────────────────────────────────────────
  {
    id: 'aglc-cannabis-wholesale',
    name: 'AGLC — Alberta Cannabis Wholesale',
    url: 'https://aglc.ca',
    searchUrl: 'https://aglc.ca/cannabis/cannabis-industry/cannabis-suppliers',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Alberta Gaming Liquor & Cannabis. Provincial wholesale purchasing authority. Supplier list and product catalogue — live listings from licensed producers.',
  },
  {
    id: 'ocs-ontario-wholesale',
    name: 'OCS — Ontario Cannabis Store Wholesale',
    url: 'https://ocs.ca',
    searchUrl: 'https://ocs.ca/pages/cannabis-retailers',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Ontario Cannabis Store. Provincial wholesaler. Public product listings — SKUs, prices, LP provenance. High signal for active LP products.',
  },
  {
    id: 'bcldb-cannabis-wholesale',
    name: 'BC Cannabis Secretariat — Wholesale',
    url: 'https://www2.gov.bc.ca',
    searchUrl: 'https://www2.gov.bc.ca/gov/content/employment-business/business/liquor-regulation-licensing/cannabis',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'BC Liquor Distribution Branch cannabis distribution. Licensed supplier and product listings.',
  },
  {
    id: 'sqdc-quebec-products',
    name: 'SQDC — Quebec Cannabis Product Catalogue',
    url: 'https://www.sqdc.ca',
    searchUrl: 'https://www.sqdc.ca/en-CA/products',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Société québécoise du cannabis. Public product catalogue. Real LP and product signal for Quebec market access.',
  },
  {
    id: 'slga-saskatchewan-cannabis',
    name: 'SLGA — Saskatchewan Cannabis Licensees',
    url: 'https://www.slga.com',
    searchUrl: 'https://www.slga.com/cannabis',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Saskatchewan Liquor and Gaming Authority. Cannabis retailer and wholesale listings.',
  },

  // ── INTERNATIONAL REGULATORY (ADDITIONAL) ─────────────────────────────────
  {
    id: 'mhra-uk-cannabis',
    name: 'MHRA — UK Cannabis Licences',
    url: 'https://www.gov.uk',
    searchUrl: 'https://www.gov.uk/guidance/cannabis-based-products-for-medicinal-use-in-humans',
    category: 'import_demand',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'europe',
    notes: 'UK Medicines and Healthcare products Regulatory Agency. Licensed cannabis importers and manufacturers for CBPM market.',
  },
  {
    id: 'omc-netherlands',
    name: 'OMC — Netherlands Bureau for Medicinal Cannabis',
    url: 'https://www.cannabisbureau.nl',
    searchUrl: 'https://www.cannabisbureau.nl/en/',
    category: 'import_demand',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'europe',
    notes: 'Dutch Office for Medicinal Cannabis. Government wholesale monopoly — import/export licences and authorised suppliers list.',
  },
  {
    id: 'israel-moh-cannabis',
    name: 'Israel MOH — Medical Cannabis Import/Export',
    url: 'https://www.health.gov.il',
    searchUrl: 'https://www.health.gov.il/English/Topics/Cannabis/Pages/default.aspx',
    category: 'import_demand',
    parserType: 'html-card',
    status: 'needs-review',
    cadenceHours: 168,
    region: 'middle_east',
    notes: 'Israel Ministry of Health. Licensed importer/exporter list. Major EU export destination. Requires parser validation — Hebrew/English.',
  },
  {
    id: 'swissmedic-cannabis',
    name: 'Swissmedic — Swiss Cannabis Authorisations',
    url: 'https://www.swissmedic.ch',
    searchUrl: 'https://www.swissmedic.ch/swissmedic/en/home/humanarzneimittel/authorisation--hma-/cannabishaltige-arzneimittel.html',
    category: 'import_demand',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'europe',
    notes: 'Swiss Therapeutic Products Agency. Authorised cannabis products and importers. Switzerland as high-value EU-adjacent market.',
  },
  {
    id: 'infarmed-portugal-cannabis',
    name: 'INFARMED — Portugal Cannabis Authorisations',
    url: 'https://www.infarmed.pt',
    searchUrl: 'https://www.infarmed.pt/web/infarmed-en/canabinoides',
    category: 'import_demand',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'europe',
    notes: 'Portuguese national medicines authority. Licensed cannabis cultivators, producers, importers for medical programme.',
  },
  {
    id: 'iss-italy-cannabis',
    name: 'ISS — Italian Medical Cannabis Programme',
    url: 'https://www.iss.it',
    searchUrl: 'https://www.iss.it/en/web/guest/cannabis-medica',
    category: 'import_demand',
    parserType: 'html-card',
    status: 'needs-review',
    cadenceHours: 168,
    region: 'europe',
    notes: 'Istituto Superiore di Sanità. Italian cannabis programme — import authorisations, licensed operators. Military (SIMC) supply chain.',
  },
  {
    id: 'dkma-denmark-cannabis',
    name: 'DKMA — Danish Cannabis Pilot Programme',
    url: 'https://laegemiddelstyrelsen.dk',
    searchUrl: 'https://laegemiddelstyrelsen.dk/en/special-initiatives/medical-cannabis-pilot-programme/',
    category: 'import_demand',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'europe',
    notes: 'Danish Medicines Agency. Medical cannabis pilot — licensed importers and products list. Public register, well-structured.',
  },
  {
    id: 'sukl-czech-cannabis',
    name: 'SÚKL — Czech Cannabis Authorised Products',
    url: 'https://www.sukl.eu',
    searchUrl: 'https://www.sukl.eu/en/special-medicinal-products/cannabis',
    category: 'import_demand',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'europe',
    notes: 'State Institute for Drug Control (Czech). Authorized medical cannabis products and import licences.',
  },
  {
    id: 'malta-medicines-authority',
    name: 'Malta Medicines Authority — Cannabis Licences',
    url: 'https://medicinesauthority.gov.mt',
    searchUrl: 'https://medicinesauthority.gov.mt/cannabis',
    category: 'import_demand',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'europe',
    notes: 'Malta Medicines Authority. EU-based cannabis cultivation and export licences. Strategic EU/GMP export hub.',
  },
  {
    id: 'sahpra-south-africa',
    name: 'SAHPRA — South Africa Cannabis Licences',
    url: 'https://www.sahpra.org.za',
    searchUrl: 'https://www.sahpra.org.za/complementary-medicines/cannabis/',
    category: 'export_ready',
    parserType: 'html-card',
    status: 'needs-review',
    cadenceHours: 168,
    region: 'africa',
    notes: 'SA Health Products Regulatory Authority. Cannabis for private purposes regulation. Growing export-focused cultivation sector.',
  },
  {
    id: 'anvisa-brazil-cannabis',
    name: 'ANVISA — Brazil Cannabis RDC 327',
    url: 'https://www.gov.br/anvisa',
    searchUrl: 'https://www.gov.br/anvisa/pt-br/assuntos/regulamentacao/legislacao/produtos-derivados-da-cannabis',
    category: 'import_demand',
    parserType: 'html-card',
    status: 'needs-review',
    cadenceHours: 168,
    region: 'latin_america',
    notes: 'Brazilian health regulator. RDC 327 licensed cannabis importers and product registrations. Large patient population, import-dependent.',
  },
  {
    id: 'jamaica-cla-licences',
    name: 'Jamaica Cannabis Licensing Authority',
    url: 'https://www.cla.gov.jm',
    searchUrl: 'https://www.cla.gov.jm/licensed-operators',
    category: 'export_ready',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'latin_america',
    notes: 'Jamaica CLA. Licensed cultivators, processors, retailers, researchers. Heritage genetics and GMP export focus.',
  },
  {
    id: 'thailand-fda-cannabis',
    name: 'Thai FDA — Cannabis Licences',
    url: 'https://www.fda.moph.go.th',
    searchUrl: 'https://www.fda.moph.go.th/sites/Drug/Pages/Cannabis.aspx',
    category: 'import_demand',
    parserType: 'html-card',
    status: 'needs-review',
    cadenceHours: 168,
    region: 'asia_pacific',
    notes: 'Thailand Food and Drug Administration. Licensed cannabis operators. Rapidly evolving regulatory framework — requires monitoring.',
  },
  {
    id: 'colombia-minjusticia-cannabis',
    name: 'Colombia MinJusticia — Cannabis Export Licences',
    url: 'https://www.minjusticia.gov.co',
    searchUrl: 'https://www.minjusticia.gov.co/programas-co/politica-de-drogas/cannabis-medicinal',
    category: 'export_ready',
    parserType: 'html-card',
    status: 'needs-review',
    cadenceHours: 168,
    region: 'latin_america',
    notes: 'Colombian Ministry of Justice. Cannabis export licence registry — large-scale outdoor production. Major global supply chain player.',
  },
  {
    id: 'eof-greece-cannabis',
    name: 'EOF — Greek National Cannabis Register',
    url: 'https://www.eof.gr',
    searchUrl: 'https://www.eof.gr/web/guest/cannabis',
    category: 'import_demand',
    parserType: 'html-card',
    status: 'needs-review',
    cadenceHours: 168,
    region: 'europe',
    notes: 'Ethnikos Organismos Farmakon (Greek medicines agency). Medical cannabis cultivation and import authorisations.',
  },
  {
    id: 'noma-norway-cannabis',
    name: 'NOMA — Norwegian Cannabis Medicines',
    url: 'https://legemiddelverket.no',
    searchUrl: 'https://legemiddelverket.no/english/medical-cannabis',
    category: 'import_demand',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'europe',
    notes: 'Norwegian Medicines Agency. Authorised cannabis products and importers under Section 2 compassionate access.',
  },

  // ── B2B WHOLESALE PLATFORMS (ADDITIONAL) ──────────────────────────────────
  {
    id: 'confident-cannabis',
    name: 'Confident Cannabis — Wholesale Marketplace',
    url: 'https://confidentcannabis.com',
    searchUrl: 'https://confidentcannabis.com/wholesale',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 24,
    region: 'north_america',
    notes: 'B2B wholesale marketplace with third-party lab results attached to listings. High-trust signal — COA-verified inventory.',
  },
  {
    id: 'nabis-wholesale',
    name: 'NABIS — California Wholesale Distributor',
    url: 'https://www.nabis.com',
    searchUrl: 'https://www.nabis.com/brands',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'needs-review',
    cadenceHours: 48,
    region: 'north_america',
    notes: 'Largest CA cannabis distributor. Public brand and product directory. Good California market access signal.',
  },
  {
    id: 'dutchie-wholesale-menus',
    name: 'Dutchie — Dispensary Wholesale Menus',
    url: 'https://dutchie.com',
    searchUrl: 'https://dutchie.com/dispensary-map',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'needs-review',
    cadenceHours: 48,
    region: 'north_america',
    notes: 'Major POS/ordering platform. Public dispensary menu pages contain live product and pricing data. Requires parser development.',
  },
  {
    id: 'meadow-california-b2b',
    name: 'Meadow — California B2B Listings',
    url: 'https://getmeadow.com',
    searchUrl: 'https://getmeadow.com/brands',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'needs-review',
    cadenceHours: 48,
    region: 'north_america',
    notes: 'California B2B cannabis ordering. Public brand directory with product categories.',
  },

  // ── FINANCIAL & CAPITAL INTELLIGENCE ──────────────────────────────────────
  {
    id: 'sec-edgar-cannabis',
    name: 'SEC EDGAR — Cannabis Company Filings',
    url: 'https://efts.sec.gov',
    searchUrl: 'https://efts.sec.gov/LATEST/search-index?q=%22cannabis%22&dateRange=custom&startdt=2024-01-01&forms=8-K,10-Q,10-K',
    category: 'business_opportunities',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 24,
    region: 'north_america',
    notes: 'SEC EDGAR full-text search. 8-K, 10-Q, 10-K filings — M&A, distress signals, facility expansion, capital raises. High-value intelligence.',
  },
  {
    id: 'sedar-canadian-lp-filings',
    name: 'SEDAR+ — Canadian LP Regulatory Filings',
    url: 'https://www.sedarplus.ca',
    searchUrl: 'https://www.sedarplus.ca/landingpage/',
    category: 'business_opportunities',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 48,
    region: 'north_america',
    notes: 'Canadian securities filing system. LP quarterly/annual reports — production volumes, export figures, financial distress signals.',
  },
  {
    id: 'viridian-capital-deals',
    name: 'Viridian Capital Advisors — Deal Tracker',
    url: 'https://viridiancapitaladvisors.com',
    searchUrl: 'https://viridiancapitaladvisors.com/cannabis-deal-tracker/',
    category: 'business_opportunities',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 48,
    region: 'global',
    notes: 'Weekly cannabis M&A and capital raise tracker. Debt, equity, M&A by sector — leading distress and consolidation signal.',
  },
  {
    id: 'pacer-cannabis-bankruptcy',
    name: 'CourtListener — Cannabis Bankruptcy Filings',
    url: 'https://www.courtlistener.com',
    searchUrl: 'https://www.courtlistener.com/?q=%22cannabis%22+%22chapter+11%22&type=r&order_by=score+desc',
    category: 'distressed_businesses',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 48,
    region: 'north_america',
    notes: 'PACER-backed public court records. Cannabis Chapter 11/7 filings — distressed asset and equipment acquisition opportunities.',
  },

  // ── TRADE EVENTS & DIRECTORIES ─────────────────────────────────────────────
  {
    id: 'mjbizcon-exhibitors',
    name: 'MJBizCon — Exhibitor Directory',
    url: 'https://mjbizconference.com',
    searchUrl: 'https://mjbizconference.com/exhibitors/',
    category: 'professional_services',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'global',
    notes: 'Worlds largest cannabis trade show. Annual exhibitor list — equipment vendors, service providers, new entrants, international delegations.',
  },
  {
    id: 'hall-of-flowers-exhibitors',
    name: 'Hall of Flowers — Brand Directory',
    url: 'https://hallofflowers.com',
    searchUrl: 'https://hallofflowers.com/brands/',
    category: 'cannabis_inventory',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Premium cannabis trade show. Exhibiting brands are vetted — strong signal for quality producers seeking wholesale relationships.',
  },
  {
    id: 'necann-exhibitors',
    name: 'NECANN — Northeast Cannabis Business Conference',
    url: 'https://necann.com',
    searchUrl: 'https://necann.com/exhibitors/',
    category: 'professional_services',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Northeast regional cannabis trade show. Exhibitor and sponsor list — service providers, equipment vendors, ancillary businesses.',
  },

  // ── IP & PATENT INTELLIGENCE ───────────────────────────────────────────────
  {
    id: 'google-patents-cannabis',
    name: 'Google Patents — Cannabis Patent Filings',
    url: 'https://patents.google.com',
    searchUrl: 'https://patents.google.com/?q=cannabis+cultivation+extraction&after=priority:20220101&assignee=',
    category: 'new_products',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'global',
    notes: 'USPTO and international cannabis patents. New extraction tech, genetics IP, formulation patents — R&D signal and competitive intelligence.',
  },
  {
    id: 'cipo-cannabis-patents',
    name: 'CIPO — Canadian Cannabis Patent Database',
    url: 'https://www.ic.gc.ca',
    searchUrl: 'https://ised-isde.canada.ca/site/canadian-intellectual-property-office/en',
    category: 'new_products',
    parserType: 'html-card',
    status: 'needs-review',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Canadian Intellectual Property Office. Cannabis-related patent filings — genetics, processing, formulation innovations.',
  },

  // ── ADDITIONAL NEWS & RESEARCH ─────────────────────────────────────────────
  {
    id: 'marijuana-moment-news',
    name: 'Marijuana Moment — Policy & Legislation',
    url: 'https://www.marijuanamoment.net',
    searchUrl: 'https://www.marijuanamoment.net/feed/',
    category: 'new_products',
    parserType: 'rss-feed',
    status: 'enabled',
    cadenceHours: 6,
    region: 'global',
    notes: 'Policy and legislation focused. Tracks US federal reform, state ballot initiatives, international regulatory changes. RSS available.',
  },
  {
    id: 'cannabis-wire-news',
    name: 'Cannabis Wire — Investigative News',
    url: 'https://cannabiswire.com',
    searchUrl: 'https://cannabiswire.com/feed/',
    category: 'new_products',
    parserType: 'rss-feed',
    status: 'enabled',
    cadenceHours: 12,
    region: 'north_america',
    notes: 'Independent investigative cannabis journalism. Deep regulatory and enforcement coverage not found in trade press.',
  },
  {
    id: 'headset-market-data',
    name: 'Headset — Public Cannabis Market Reports',
    url: 'https://headset.io',
    searchUrl: 'https://headset.io/insights/',
    category: 'new_products',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'north_america',
    notes: 'Cannabis data analytics. Free public market reports — category share, pricing trends, brand rankings by state.',
  },
  {
    id: 'new-frontier-data-reports',
    name: 'New Frontier Data — Public Research',
    url: 'https://newfrontierdata.com',
    searchUrl: 'https://newfrontierdata.com/cannabis-reports/',
    category: 'new_products',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'global',
    notes: 'Global cannabis market research firm. Public free reports on international market sizing, regulatory forecasts, investment trends.',
  },
  {
    id: 'prohibition-partners-reports',
    name: 'Prohibition Partners — EU/APAC Research',
    url: 'https://prohibitionpartners.com',
    searchUrl: 'https://prohibitionpartners.com/reports/',
    category: 'new_products',
    parserType: 'html-card',
    status: 'enabled',
    cadenceHours: 168,
    region: 'europe',
    notes: 'European-focused cannabis intelligence. Free executive summaries and public reports on EU, APAC, LatAm regulatory developments.',
  },


]
 {
  return scraperSources.filter((s) => s.category === category && s.status !== 'disabled')
}
