import type { CapabilityCriticality, CapabilityStatus, CapabilityVisibility } from './contentStatus'

export type CapabilityOwnerArea =
  | 'brand'
  | 'education'
  | 'medical'
  | 'compliance'
  | 'marketplace'
  | 'services'
  | 'intelligence'
  | 'signals'
  | 'diligence'
  | 'admin'
  | 'legal'
  | 'security'
  | 'ops'

export type CapabilityRegistryEntry = {
  id: string
  title: string
  requiredCapability: string
  routes: string[]
  visibility: CapabilityVisibility
  criticality: CapabilityCriticality
  status: CapabilityStatus
  publicStatusLabel: string
  falseGoRisk: string
  evidenceFiles: string[]
  acceptanceTests: string[]
  ownerArea: CapabilityOwnerArea
}

export const capabilityRegistry: CapabilityRegistryEntry[] = [
  {
    id: 'home-platform-spine',
    title: 'Homepage platform spine',
    requiredCapability: 'Public route map for Harbourview Network, Exchange, Intelligence, Education, Professionals, Trust and Reviewed Connections.',
    routes: ['/', '/platform'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'partial',
    publicStatusLabel: 'Platform map — route capability labels required',
    falseGoRisk: 'Homepage IA can imply complete product capability before downstream routes and workflows are evidenced.',
    evidenceFiles: ['app/page.tsx', 'lib/institutional/content.ts'],
    acceptanceTests: ['npm run test:full-scope:routes', 'npm run test:visibility'],
    ownerArea: 'brand',
  },
  {
    id: 'marketplace-hub',
    title: 'Marketplace hub',
    requiredCapability: 'Public-safe exchange hub with category status, private-routing boundary and inquiry paths.',
    routes: ['/marketplace'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'partial',
    publicStatusLabel: 'Controlled network hub — categories are reviewed before routing',
    falseGoRisk: 'Category list can be read as live inventory or automatic marketplace access.',
    evidenceFiles: ['app/marketplace/page.tsx', 'lib/marketplace/categoryCapabilityMap.ts'],
    acceptanceTests: ['npm run test:full-scope:marketplace', 'npm run test:visibility'],
    ownerArea: 'marketplace',
  },
  {
    id: 'marketplace-services',
    title: 'Marketplace services',
    requiredCapability: 'Public services page with reviewed service listings when available and explicit fallback/orientation labeling otherwise.',
    routes: ['/marketplace/services'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'fallback-backed',
    publicStatusLabel: 'Reviewed listings when available; orientation displayed when live approvals are absent',
    falseGoRisk: 'Fallback fixture services can be mistaken for live approved providers.',
    evidenceFiles: ['app/marketplace/services/page.tsx', 'lib/marketplace/liveServices.ts'],
    acceptanceTests: ['npm run test:full-scope:fallbacks', 'npm run test:services-public-leakage'],
    ownerArea: 'services',
  },
  {
    id: 'marketplace-listings',
    title: 'Reviewed marketplace listings',
    requiredCapability: 'Public-safe listing surfaces with DTO allowlisting and no provenance or private evidence leakage.',
    routes: ['/marketplace/listings'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'partial',
    publicStatusLabel: 'Reviewed listing orientation — routing requires Harbourview review',
    falseGoRisk: 'Public listing pages could leak source, supplier authorization, evidence or admin review fields.',
    evidenceFiles: ['lib/marketplace/publicListings.ts', 'app/marketplace/listings/page.tsx'],
    acceptanceTests: ['npm run test:visibility'],
    ownerArea: 'marketplace',
  },
  {
    id: 'marketplace-wanted',
    title: 'Wanted requests',
    requiredCapability: 'Buyer/operator demand capture routed through private review before any counterparty exposure.',
    routes: ['/marketplace/wanted', '/marketplace/sell?type=wanted'],
    visibility: 'mixed',
    criticality: 'launch-critical',
    status: 'request-only',
    publicStatusLabel: 'Wanted requests are reviewed before routing',
    falseGoRisk: 'Wanted request CTA can imply public buyer demand board or automatic matching.',
    evidenceFiles: ['app/api/marketplace/capture/route.ts'],
    acceptanceTests: ['npm run test:intake-workflow-safety'],
    ownerArea: 'marketplace',
  },
  {
    id: 'marketplace-sell',
    title: 'Submit opportunity/listing',
    requiredCapability: 'Seller/operator submission capture with review boundary and no automatic publication.',
    routes: ['/marketplace/sell'],
    visibility: 'mixed',
    criticality: 'launch-critical',
    status: 'request-only',
    publicStatusLabel: 'Submissions are reviewed before publication or routing',
    falseGoRisk: 'Submission form can be mistaken for automatic listing publication.',
    evidenceFiles: ['app/api/marketplace/capture/route.ts'],
    acceptanceTests: ['npm run test:intake-workflow-safety'],
    ownerArea: 'marketplace',
  },
  {
    id: 'marketplace-business-opportunities',
    title: 'Business opportunities and distressed assets',
    requiredCapability: 'Confidential-first opportunity intake for facilities, distressed assets, partnerships and business packages.',
    routes: ['/marketplace/business-opportunities'],
    visibility: 'mixed',
    criticality: 'launch-critical',
    status: 'request-only',
    publicStatusLabel: 'Confidential review required before opportunity disclosure',
    falseGoRisk: 'Public opportunity route can imply live dealroom or public distressed-asset inventory.',
    evidenceFiles: ['app/marketplace/business-opportunities/page.tsx'],
    acceptanceTests: ['npm run test:visibility'],
    ownerArea: 'marketplace',
  },
  {
    id: 'confidential-intake',
    title: 'Confidential intake',
    requiredCapability: 'Private-context inquiry capture with no automatic legal, medical, regulatory or commercial conclusion.',
    routes: ['/intake'],
    visibility: 'mixed',
    criticality: 'launch-critical',
    status: 'partial',
    publicStatusLabel: 'Confidential requests are reviewed before routing',
    falseGoRisk: 'Users may assume submission creates protected access, dealroom access or definitive advice.',
    evidenceFiles: ['app/intake/ConfidentialIntakeForm.tsx', 'app/api/marketplace/capture/route.ts'],
    acceptanceTests: ['npm run test:intake-workflow-safety'],
    ownerArea: 'diligence',
  },
  {
    id: 'intelligence-hub',
    title: 'Intelligence hub',
    requiredCapability: 'Public-safe intelligence IA with private evidence and analyst material kept out of public routes.',
    routes: ['/intelligence'],
    visibility: 'mixed',
    criticality: 'launch-critical',
    status: 'static-orientation',
    publicStatusLabel: 'Public intelligence orientation — deeper review by request',
    falseGoRisk: 'Route labels can imply complete analyst-grade intelligence products are live.',
    evidenceFiles: ['lib/institutional/content.ts'],
    acceptanceTests: ['npm run test:intelligence-fixtures', 'npm run test:visibility'],
    ownerArea: 'intelligence',
  },
  {
    id: 'intelligence-country-briefs',
    title: 'Country briefs',
    requiredCapability: 'Country-level public-safe market context with source status and request path.',
    routes: ['/intelligence/country-briefs', '/markets'],
    visibility: 'mixed',
    criticality: 'launch-critical',
    status: 'static-orientation',
    publicStatusLabel: 'Country orientation — source-backed briefs require review',
    falseGoRisk: 'Generic country pages can be mistaken for verified country intelligence.',
    evidenceFiles: ['lib/institutional/content.ts', 'lib/compliance/countries.ts'],
    acceptanceTests: ['npm run test:full-scope:compliance'],
    ownerArea: 'intelligence',
  },
  {
    id: 'intelligence-licensing-pathways',
    title: 'Licensing pathways',
    requiredCapability: 'Licensing pathway orientation separated from legal advice and private route review.',
    routes: ['/intelligence/licensing-pathways'],
    visibility: 'mixed',
    criticality: 'launch-critical',
    status: 'request-only',
    publicStatusLabel: 'Licensing pathway orientation — jurisdiction review required',
    falseGoRisk: 'Public route can imply legal/regulatory conclusions.',
    evidenceFiles: ['lib/institutional/content.ts'],
    acceptanceTests: ['npm run test:full-scope:routes'],
    ownerArea: 'intelligence',
  },
  {
    id: 'intelligence-regulatory-pathways',
    title: 'Regulatory pathways',
    requiredCapability: 'Regulatory pathway orientation with no import eligibility, approval or compliance guarantee.',
    routes: ['/intelligence/regulatory-pathways', '/compliance'],
    visibility: 'mixed',
    criticality: 'launch-critical',
    status: 'request-only',
    publicStatusLabel: 'Regulatory pathway orientation — specialist review required',
    falseGoRisk: 'Public route can be misread as official guidance or legal advice.',
    evidenceFiles: ['lib/institutional/content.ts', 'lib/compliance/countries.ts'],
    acceptanceTests: ['npm run test:compliance-visibility'],
    ownerArea: 'compliance',
  },
  {
    id: 'intelligence-counterparty',
    title: 'Counterparty intelligence',
    requiredCapability: 'Private counterparty review framing without public exposure of identities, evidence or analyst notes.',
    routes: ['/intelligence/counterparty-intelligence'],
    visibility: 'private',
    criticality: 'launch-critical',
    status: 'request-only',
    publicStatusLabel: 'Counterparty review is private and request-routed',
    falseGoRisk: 'Public route can imply searchable counterparty database or public due diligence dossiers.',
    evidenceFiles: ['lib/institutional/content.ts'],
    acceptanceTests: ['npm run test:visibility'],
    ownerArea: 'diligence',
  },
  {
    id: 'intelligence-logistics-trade-routes',
    title: 'Logistics and trade routes',
    requiredCapability: 'Controlled logistics and chain-of-custody orientation with route-specific review before reliance.',
    routes: ['/intelligence/logistics-trade-routes'],
    visibility: 'mixed',
    criticality: 'launch-critical',
    status: 'request-only',
    publicStatusLabel: 'Trade-route orientation — route review required',
    falseGoRisk: 'Public route can imply validated shipment route feasibility.',
    evidenceFiles: ['lib/institutional/content.ts'],
    acceptanceTests: ['npm run test:full-scope:routes'],
    ownerArea: 'intelligence',
  },
  {
    id: 'signals-public',
    title: 'Public regulatory signals',
    requiredCapability: 'Public-safe regulatory signals with live/fallback origin disclosure and no private evidence exposure.',
    routes: ['/signals'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'fallback-backed',
    publicStatusLabel: 'Public signals show published records when available; fallback orientation otherwise',
    falseGoRisk: 'Static fallback signals can be mistaken for live current intelligence.',
    evidenceFiles: ['app/signals/page.tsx', 'lib/regulatory-signals/public.ts', 'lib/regulatory-signals/safety.ts'],
    acceptanceTests: ['npm run test:full-scope:fallbacks', 'npm run test:signals-public-leakage:direct', 'npm run test:regulatory-signals-contract'],
    ownerArea: 'signals',
  },
  {
    id: 'education-hub',
    title: 'Education hub',
    requiredCapability: 'Non-promotional education system across clinical, pharmacy, quality, compliance, import/export, policy and safety tracks.',
    routes: ['/education'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'static-orientation',
    publicStatusLabel: 'Education orientation — review status varies by track',
    falseGoRisk: 'Education track list can imply complete accredited or reviewed education library.',
    evidenceFiles: ['lib/institutional/content.ts', 'lib/platform/contentInventory.ts'],
    acceptanceTests: ['npm run test:full-scope:content'],
    ownerArea: 'education',
  },
  {
    id: 'clinical-education',
    title: 'Clinical education',
    requiredCapability: 'Non-promotional clinical education with source basis, reviewer gate, patient boundary and publication sensitivity metadata.',
    routes: ['/network/clinical-education', '/network/clinical-education/[slug]', '/network/clinical-education/request'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'partial',
    publicStatusLabel: 'Clinical education — controlled topics require professional review',
    falseGoRisk: 'Medical topic pages can be mistaken for medical advice, prescribing guidance or reviewed clinical claims.',
    evidenceFiles: ['lib/fixtures/clinical-education.ts', 'components/clinical-education/ClinicalEducationComponents.tsx'],
    acceptanceTests: ['npm run test:full-scope:education', 'npm run test:clinical-education'],
    ownerArea: 'medical',
  },
  {
    id: 'medical-cannabis-education',
    title: 'Medical cannabis education',
    requiredCapability: 'Medical-market education framed for professional orientation only and separated from patient-specific guidance.',
    routes: ['/education', '/network/clinical-education'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'partial',
    publicStatusLabel: 'Medical-market education — non-prescriptive and review-sensitive',
    falseGoRisk: 'Medical-market copy can be mistaken for treatment claims or patient advice.',
    evidenceFiles: ['lib/institutional/content.ts', 'lib/fixtures/clinical-education.ts'],
    acceptanceTests: ['npm run test:full-scope:education'],
    ownerArea: 'medical',
  },
  {
    id: 'eu-gmp-education',
    title: 'EU GMP education',
    requiredCapability: 'EU GMP orientation separated from QP, importer and legal/regulatory conclusions unless source-backed and reviewed.',
    routes: ['/education', '/compliance'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'static-orientation',
    publicStatusLabel: 'EU GMP orientation — route-specific review required',
    falseGoRisk: 'Users may assume shipment or QP release readiness from general GMP education.',
    evidenceFiles: ['lib/institutional/content.ts', 'lib/compliance/countries.ts'],
    acceptanceTests: ['npm run test:full-scope:content', 'npm run test:compliance-visibility'],
    ownerArea: 'compliance',
  },
  {
    id: 'gacp-education',
    title: 'GACP education',
    requiredCapability: 'GACP orientation with clear boundary against full cultivation/export compliance conclusions.',
    routes: ['/education', '/compliance'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'static-orientation',
    publicStatusLabel: 'GACP orientation — jurisdiction and product-path review required',
    falseGoRisk: 'Public education may be mistaken for certification or exporter readiness.',
    evidenceFiles: ['lib/institutional/content.ts'],
    acceptanceTests: ['npm run test:full-scope:content'],
    ownerArea: 'education',
  },
  {
    id: 'gdp-education',
    title: 'GDP education',
    requiredCapability: 'GDP/logistics orientation with route-specific validation boundary.',
    routes: ['/education', '/compliance'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'static-orientation',
    publicStatusLabel: 'GDP orientation — route-specific review required',
    falseGoRisk: 'Public copy can imply shipment readiness or distributor qualification.',
    evidenceFiles: ['lib/institutional/content.ts'],
    acceptanceTests: ['npm run test:full-scope:content'],
    ownerArea: 'education',
  },
  {
    id: 'qp-release-education',
    title: 'QP release education',
    requiredCapability: 'QP release orientation requiring official-source and specialist review before route-specific reliance.',
    routes: ['/education', '/compliance'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'static-orientation',
    publicStatusLabel: 'QP release orientation — specialist review required',
    falseGoRisk: 'Users may interpret public education as QP certification guidance.',
    evidenceFiles: ['lib/institutional/content.ts'],
    acceptanceTests: ['npm run test:full-scope:content'],
    ownerArea: 'compliance',
  },
  {
    id: 'import-export-education',
    title: 'Import/export education',
    requiredCapability: 'Import/export orientation with jurisdiction, permit and controlled-substance caveats.',
    routes: ['/education', '/compliance', '/markets'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'static-orientation',
    publicStatusLabel: 'Import/export orientation — permit and route review required',
    falseGoRisk: 'Public content can imply import/export eligibility.',
    evidenceFiles: ['lib/institutional/content.ts', 'lib/compliance/countries.ts'],
    acceptanceTests: ['npm run test:compliance-visibility'],
    ownerArea: 'compliance',
  },
  {
    id: 'canada-germany-pathway',
    title: 'Canada-to-Germany pathway',
    requiredCapability: 'Canada-to-Germany medical cannabis pathway education with source-backed, route-dependent controls before use.',
    routes: ['/education', '/compliance/country-pathways/germany'],
    visibility: 'public',
    criticality: 'later-enabled',
    status: 'draft-orientation',
    publicStatusLabel: 'Draft pathway orientation — source-backed pathway pack required',
    falseGoRisk: 'General compliance copy can be mistaken for shipment-readiness guidance.',
    evidenceFiles: ['lib/compliance/countries.ts'],
    acceptanceTests: ['npm run test:full-scope:compliance'],
    ownerArea: 'compliance',
  },
  {
    id: 'quality-systems-education',
    title: 'Quality systems education',
    requiredCapability: 'Quality systems and documentation education with clear boundary against certification or audit outcome claims.',
    routes: ['/education', '/professionals'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'static-orientation',
    publicStatusLabel: 'Quality systems orientation — evidence review required',
    falseGoRisk: 'Quality education can be mistaken for audit readiness certification.',
    evidenceFiles: ['lib/institutional/content.ts'],
    acceptanceTests: ['npm run test:full-scope:content'],
    ownerArea: 'education',
  },
  {
    id: 'batch-evidence-education',
    title: 'Batch evidence education',
    requiredCapability: 'Batch document and COA education with no private batch record publication.',
    routes: ['/education', '/network/clinical-education/product-documentation'],
    visibility: 'mixed',
    criticality: 'launch-critical',
    status: 'partial',
    publicStatusLabel: 'Batch evidence education — documentation context only',
    falseGoRisk: 'Public page could imply review of specific private batch documents.',
    evidenceFiles: ['lib/fixtures/clinical-education.ts'],
    acceptanceTests: ['npm run test:full-scope:education'],
    ownerArea: 'education',
  },
  {
    id: 'supplier-qualification-education',
    title: 'Supplier qualification education',
    requiredCapability: 'Supplier qualification education separated from counterparty approval or endorsement.',
    routes: ['/education', '/assessments'],
    visibility: 'mixed',
    criticality: 'launch-critical',
    status: 'request-only',
    publicStatusLabel: 'Supplier qualification education — reviewed assessment required',
    falseGoRisk: 'Users may treat Harbourview as endorsing suppliers without private diligence.',
    evidenceFiles: ['lib/institutional/content.ts'],
    acceptanceTests: ['npm run test:full-scope:content'],
    ownerArea: 'diligence',
  },
  {
    id: 'compliance-hub',
    title: 'Compliance hub',
    requiredCapability: 'Compliance orientation with legal/regulatory advice boundary and source-status labeling.',
    routes: ['/compliance'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'partial',
    publicStatusLabel: 'Compliance orientation — specialist review required for reliance',
    falseGoRisk: 'Compliance hub can be mistaken for legal advice or regulator guidance.',
    evidenceFiles: ['app/compliance/page.tsx', 'lib/compliance/countries.ts'],
    acceptanceTests: ['npm run test:compliance-visibility', 'npm run test:full-scope:compliance'],
    ownerArea: 'compliance',
  },
  {
    id: 'compliance-country-pathways',
    title: 'Compliance country pathways',
    requiredCapability: 'Country pathway pages with explicit maturity, source confidence, review status and draft orientation labels.',
    routes: ['/compliance/country-pathways/[country]'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'draft-orientation',
    publicStatusLabel: 'Draft country orientation — jurisdiction-specific review required',
    falseGoRisk: 'Country pages generated from generic skeleton can be mistaken for verified jurisdiction briefs.',
    evidenceFiles: ['lib/compliance/countries.ts', 'app/compliance/country-pathways/[country]/page.tsx'],
    acceptanceTests: ['npm run test:full-scope:compliance', 'npm run test:compliance-visibility'],
    ownerArea: 'compliance',
  },
  {
    id: 'assessments-hub',
    title: 'Assessments hub',
    requiredCapability: 'Reviewed request paths for market-access, documentation, counterparty and due diligence readiness assessments.',
    routes: ['/assessments'],
    visibility: 'mixed',
    criticality: 'launch-critical',
    status: 'request-only',
    publicStatusLabel: 'Assessment requests are reviewed; no automated conclusion',
    falseGoRisk: 'Assessment route can imply instant legal, medical, compliance or investment conclusion.',
    evidenceFiles: ['lib/institutional/content.ts'],
    acceptanceTests: ['npm run test:full-scope:routes'],
    ownerArea: 'diligence',
  },
  {
    id: 'professionals-hub',
    title: 'Professionals hub',
    requiredCapability: 'Role-specific public routing for clinicians, pharmacists, lawyers, QA/GMP, regulators, researchers, investors and institutions.',
    routes: ['/professionals'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'static-orientation',
    publicStatusLabel: 'Professional role orientation — reviewed workflows vary by role',
    falseGoRisk: 'Professional route can imply credentialed program, advice or endorsement.',
    evidenceFiles: ['lib/institutional/content.ts'],
    acceptanceTests: ['npm run test:full-scope:routes'],
    ownerArea: 'education',
  },
  {
    id: 'policy-standards',
    title: 'Policy and standards',
    requiredCapability: 'Neutral policy and standards orientation without government endorsement or official guidance claims.',
    routes: ['/policy-standards'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'static-orientation',
    publicStatusLabel: 'Policy and standards orientation — not official guidance',
    falseGoRisk: 'Policy pages can imply official endorsement or legal authority.',
    evidenceFiles: ['lib/institutional/content.ts'],
    acceptanceTests: ['npm run test:full-scope:routes'],
    ownerArea: 'compliance',
  },
  {
    id: 'source-methodology',
    title: 'Source methodology',
    requiredCapability: 'Public source-methodology explanation without raw source captures, private evidence or analyst notes.',
    routes: ['/source-methodology'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'static-orientation',
    publicStatusLabel: 'Methodology explanation — raw evidence remains private',
    falseGoRisk: 'Source explanation can expose or imply publication of private evidence.',
    evidenceFiles: ['lib/institutional/content.ts'],
    acceptanceTests: ['npm run test:visibility'],
    ownerArea: 'diligence',
  },
  {
    id: 'trust-governance',
    title: 'Trust and governance',
    requiredCapability: 'Public trust layer for confidentiality, correction, source standards, marketplace rules and public/private boundary.',
    routes: ['/trust-governance'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'static-orientation',
    publicStatusLabel: 'Trust standards orientation — operational proof required for launch GO',
    falseGoRisk: 'Governance copy can be mistaken for enforceable workflow completion.',
    evidenceFiles: ['lib/institutional/content.ts'],
    acceptanceTests: ['npm run test:full-scope:content'],
    ownerArea: 'legal',
  },
  {
    id: 'reviewed-connections',
    title: 'Reviewed connections',
    requiredCapability: 'Request-routed introductions and protected dealroom orientation without automatic access or public counterparty exposure.',
    routes: ['/reviewed-connections'],
    visibility: 'mixed',
    criticality: 'launch-critical',
    status: 'request-only',
    publicStatusLabel: 'Reviewed connections — no automatic access or disclosure',
    falseGoRisk: 'Public route can imply live protected dealroom, automatic matching or disclosed counterparties.',
    evidenceFiles: ['lib/institutional/content.ts'],
    acceptanceTests: ['npm run test:visibility'],
    ownerArea: 'diligence',
  },
  {
    id: 'legal-privacy',
    title: 'Privacy policy',
    requiredCapability: 'Public privacy route linked from forms and footer.',
    routes: ['/legal/privacy'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'partial',
    publicStatusLabel: 'Privacy route required for public forms',
    falseGoRisk: 'Forms can collect inquiry data without adequate privacy/retention context.',
    evidenceFiles: ['lib/institutional/content.ts'],
    acceptanceTests: ['npm run test:full-scope:routes'],
    ownerArea: 'legal',
  },
  {
    id: 'legal-terms',
    title: 'Terms of use',
    requiredCapability: 'Public terms route linked from footer and relevant public workflows.',
    routes: ['/legal/terms'],
    visibility: 'public',
    criticality: 'launch-critical',
    status: 'partial',
    publicStatusLabel: 'Terms route required for public platform use',
    falseGoRisk: 'Marketplace and education use can proceed without clear use boundaries.',
    evidenceFiles: ['lib/institutional/content.ts'],
    acceptanceTests: ['npm run test:full-scope:routes'],
    ownerArea: 'legal',
  },
  {
    id: 'admin-dashboard',
    title: 'Admin dashboard',
    requiredCapability: 'Admin/operator-only control surface with anonymous/viewer/analyst denial.',
    routes: ['/admin'],
    visibility: 'admin-only',
    criticality: 'launch-critical',
    status: 'admin-backed',
    publicStatusLabel: 'Admin only',
    falseGoRisk: 'Admin route can leak private content or allow unauthorized access if guard/RLS is misconfigured.',
    evidenceFiles: ['lib/auth/adminGuard.ts', 'lib/auth/adminRoles.ts'],
    acceptanceTests: ['npm run test:admin-guard'],
    ownerArea: 'admin',
  },
  {
    id: 'admin-sources',
    title: 'Admin source registry',
    requiredCapability: 'Private source registry and source-snapshot queue restricted to admin/operator workflows.',
    routes: ['/admin/sources'],
    visibility: 'admin-only',
    criticality: 'launch-critical',
    status: 'admin-backed',
    publicStatusLabel: 'Admin source registry — never public evidence',
    falseGoRisk: 'Source URLs, raw captures, analyst notes or evidence could leak to public bundles/routes.',
    evidenceFiles: ['app/admin/(protected)/sources/page.tsx', 'lib/marketplace/candidates.ts'],
    acceptanceTests: ['npm run test:admin-guard', 'npm run test:visibility'],
    ownerArea: 'admin',
  },
  {
    id: 'admin-candidates',
    title: 'Admin candidate review',
    requiredCapability: 'Candidate review queue with audited status transitions before public publication.',
    routes: ['/admin/candidates'],
    visibility: 'admin-only',
    criticality: 'launch-critical',
    status: 'admin-backed',
    publicStatusLabel: 'Admin candidate review — publication requires approved projection',
    falseGoRisk: 'Candidate approval may be confused with public publication or may expose private fields.',
    evidenceFiles: ['app/admin/(protected)/candidates/page.tsx', 'lib/marketplace/candidates.ts'],
    acceptanceTests: ['npm run test:admin-guard', 'npm run test:visibility'],
    ownerArea: 'admin',
  },
  {
    id: 'admin-signals',
    title: 'Admin regulatory signal publishing',
    requiredCapability: 'Admin signal review and publication workflow with public-safe projection gates.',
    routes: ['/admin/signals'],
    visibility: 'admin-only',
    criticality: 'launch-critical',
    status: 'admin-backed',
    publicStatusLabel: 'Admin signal publishing — public projection only',
    falseGoRisk: 'Signal records could publish private fields or unreviewed records.',
    evidenceFiles: ['lib/regulatory-signals/public.ts', 'lib/regulatory-signals/safety.ts'],
    acceptanceTests: ['npm run test:regulatory-signals-contract', 'npm run test:signals-public-leakage:direct'],
    ownerArea: 'admin',
  },
  {
    id: 'admin-inquiries',
    title: 'Admin inquiries',
    requiredCapability: 'Private review of captured marketplace and confidential intake submissions.',
    routes: ['/admin/inquiries'],
    visibility: 'admin-only',
    criticality: 'launch-critical',
    status: 'admin-backed',
    publicStatusLabel: 'Admin inquiry review — private routing only',
    falseGoRisk: 'Inquiry capture may not have operator review, ownership or privacy controls if route is missing.',
    evidenceFiles: ['app/api/marketplace/capture/route.ts'],
    acceptanceTests: ['npm run test:intake-workflow-safety', 'npm run test:admin-guard'],
    ownerArea: 'admin',
  },
  {
    id: 'admin-role-guard',
    title: 'Admin role guard',
    requiredCapability: 'Role-based admin guard allowing admin/operator and denying anonymous/viewer/analyst.',
    routes: ['/admin', '/admin/*'],
    visibility: 'admin-only',
    criticality: 'launch-critical',
    status: 'admin-backed',
    publicStatusLabel: 'Admin/operator only',
    falseGoRisk: 'Admin route may appear protected in code but fail in runtime token/RLS configuration.',
    evidenceFiles: ['lib/auth/adminGuard.ts', 'lib/auth/adminRoles.ts'],
    acceptanceTests: ['npm run test:admin-guard'],
    ownerArea: 'security',
  },
  {
    id: 'dashboard-home',
    title: 'Dashboard home',
    requiredCapability: 'Country-aware dashboard routing home.',
    routes: ['/dashboard'],
    visibility: 'mixed',
    criticality: 'launch-critical',
    status: 'partial',
    publicStatusLabel: 'Dashboard route spine active',
    falseGoRisk: 'Dashboard route may imply complete country intelligence.',
    evidenceFiles: ['app/dashboard/page.tsx', 'lib/dashboard/countries.ts'],
    acceptanceTests: ['vitest run tests/dashboard/routing.test.ts'],
    ownerArea: 'intelligence',
  },
  {
    id: 'public-private-dto-boundary',
    title: 'Public/private DTO boundary',
    requiredCapability: 'Public pages project only allowlisted fields and suppress source/evidence/provenance/review/counterparty data.',
    routes: ['/', '/marketplace/*', '/signals', '/compliance/*', '/network/clinical-education/*'],
    visibility: 'mixed',
    criticality: 'launch-critical',
    status: 'partial',
    publicStatusLabel: 'Public projections only — private evidence remains internal',
    falseGoRisk: 'Private source/evidence/admin/review fields could leak through public HTML or client bundles.',
    evidenceFiles: ['lib/marketplace/publicListings.ts', 'lib/marketplace/publicServiceProjection.ts', 'lib/regulatory-signals/safety.ts'],
    acceptanceTests: ['npm run test:visibility', 'npm run test:services-public-leakage', 'npm run test:signals-public-leakage:direct'],
    ownerArea: 'security',
  },
]

export const capabilityRegistryById = new Map(capabilityRegistry.map((entry) => [entry.id, entry]))

export function getCapabilityById(id: string) {
  return capabilityRegistryById.get(id)
}

export const requiredCapabilityIds = capabilityRegistry.map((entry) => entry.id)
