import type {
  ProprietaryDataset,
  ReinforcementEvent,
  CommercialPrediction,
  RelationshipTrustScore,
  AICopilotTask,
  AutonomousExecutionQueueItem,
  OperatorCommandItem,
  InstitutionalWorkflowRecord,
  StrategicDashboardMetric,
} from './types'

export const fixtureDatasets: ProprietaryDataset[] = [
  {
    id: 'ds-001',
    name: 'EU Buyer Demand Registry',
    category: 'buyer_demand',
    record_count: 312,
    freshness_days: 3,
    coverage_markets: ['DE', 'NL', 'PT', 'PL', 'CZ'],
    coverage_categories: ['cannabis_inventory', 'eu_gmp', 'consumables'],
    last_updated: '2026-06-17T09:00:00Z',
    completeness_pct: 91,
    status: 'active',
  },
  {
    id: 'ds-002',
    name: 'UK Importer & Distributor Index',
    category: 'importer_distributor',
    record_count: 87,
    freshness_days: 8,
    coverage_markets: ['UK'],
    coverage_categories: ['importers', 'distributors', 'cannabis_inventory'],
    last_updated: '2026-06-11T14:22:00Z',
    completeness_pct: 78,
    status: 'active',
  },
  {
    id: 'ds-003',
    name: 'LATAM Seller Supply Map',
    category: 'seller_supply',
    record_count: 204,
    freshness_days: 14,
    coverage_markets: ['LATAM'],
    coverage_categories: ['cannabis_inventory', 'eu_gmp'],
    last_updated: '2026-06-05T08:00:00Z',
    completeness_pct: 62,
    status: 'stale',
  },
  {
    id: 'ds-004',
    name: 'DE Market Pathway Intelligence',
    category: 'market_pathway',
    record_count: 56,
    freshness_days: 2,
    coverage_markets: ['DE'],
    coverage_categories: ['market_access', 'eu_gmp', 'importers'],
    last_updated: '2026-06-17T16:00:00Z',
    completeness_pct: 88,
    status: 'active',
  },
  {
    id: 'ds-005',
    name: 'CA Documentation Requirements',
    category: 'documentation',
    record_count: 143,
    freshness_days: 6,
    coverage_markets: ['CA'],
    coverage_categories: ['cannabis_inventory', 'services', 'market_access'],
    last_updated: '2026-06-13T10:30:00Z',
    completeness_pct: 84,
    status: 'active',
  },
  {
    id: 'ds-006',
    name: 'AU Counterparty Registry',
    category: 'counterparty',
    record_count: 98,
    freshness_days: 19,
    coverage_markets: ['AU'],
    coverage_categories: ['importers', 'distributors', 'cannabis_inventory'],
    last_updated: '2026-05-31T07:45:00Z',
    completeness_pct: 47,
    status: 'stale',
  },
  {
    id: 'ds-007',
    name: 'PL–CZ Deal Flow Tracker',
    category: 'deal_flow',
    record_count: 71,
    freshness_days: 4,
    coverage_markets: ['PL', 'CZ'],
    coverage_categories: ['cannabis_inventory', 'eu_gmp'],
    last_updated: '2026-06-15T11:00:00Z',
    completeness_pct: 73,
    status: 'active',
  },
  {
    id: 'ds-008',
    name: 'Global Source Reliability Scores',
    category: 'source_reliability',
    record_count: 389,
    freshness_days: 1,
    coverage_markets: ['DE', 'UK', 'PT', 'CA', 'AU', 'PL', 'CZ', 'NL', 'LATAM'],
    coverage_categories: ['cannabis_inventory', 'eu_gmp', 'services', 'packaging', 'equipment'],
    last_updated: '2026-06-18T23:00:00Z',
    completeness_pct: 96,
    status: 'active',
  },
  {
    id: 'ds-009',
    name: 'Introduction Outcomes Log',
    category: 'introduction_outcomes',
    record_count: 218,
    freshness_days: 5,
    coverage_markets: ['DE', 'UK', 'NL', 'PT'],
    coverage_categories: ['cannabis_inventory', 'importers', 'distributors'],
    last_updated: '2026-06-14T08:30:00Z',
    completeness_pct: 82,
    status: 'active',
  },
  {
    id: 'ds-010',
    name: 'NL Packaging & Equipment Demand',
    category: 'buyer_demand',
    record_count: 34,
    freshness_days: 0,
    coverage_markets: ['NL'],
    coverage_categories: ['packaging', 'equipment'],
    last_updated: '2026-06-19T00:00:00Z',
    completeness_pct: 38,
    status: 'building',
  },
  {
    id: 'ds-011',
    name: 'PT Commercial Response Memory',
    category: 'commercial_response',
    record_count: 112,
    freshness_days: 7,
    coverage_markets: ['PT'],
    coverage_categories: ['cannabis_inventory', 'eu_gmp', 'market_access'],
    last_updated: '2026-06-12T13:00:00Z',
    completeness_pct: 69,
    status: 'active',
  },
  {
    id: 'ds-012',
    name: 'Evidence & Compliance Archive',
    category: 'evidence',
    record_count: 1042,
    freshness_days: 12,
    coverage_markets: ['DE', 'UK', 'PT', 'CA', 'AU', 'PL', 'CZ', 'NL', 'LATAM'],
    coverage_categories: ['eu_gmp', 'cannabis_inventory', 'services'],
    last_updated: '2026-06-07T09:00:00Z',
    completeness_pct: 88,
    status: 'active',
  },
  {
    id: 'ds-013',
    name: 'Relationship Memory Network',
    category: 'relationship_memory',
    record_count: 267,
    freshness_days: 2,
    coverage_markets: ['DE', 'UK', 'NL', 'PL', 'CZ'],
    coverage_categories: ['cannabis_inventory', 'importers', 'distributors', 'services'],
    last_updated: '2026-06-17T18:00:00Z',
    completeness_pct: 91,
    status: 'active',
  },
  {
    id: 'ds-014',
    name: 'Market Coverage Gap Analysis',
    category: 'market_coverage',
    record_count: 0,
    freshness_days: 0,
    coverage_markets: ['LATAM', 'AU'],
    coverage_categories: ['equipment', 'packaging'],
    last_updated: '2026-06-01T00:00:00Z',
    completeness_pct: 12,
    status: 'gap',
  },
]

export const fixtureReinforcementEvents: ReinforcementEvent[] = [
  { id: 're-001', event_type: 'buyer_responded', entity_type: 'buyer', entity_label: 'MedLeaf GmbH', market: 'DE', category: 'cannabis_inventory', score_impact: 8, created_at: '2026-06-18T10:00:00Z', operator: 'system' },
  { id: 're-002', event_type: 'deal_won', entity_type: 'seller', entity_label: 'CannaSource LATAM', market: 'LATAM', category: 'eu_gmp', score_impact: 20, created_at: '2026-06-17T14:30:00Z', operator: 'tyler@harbourview.com' },
  { id: 're-003', event_type: 'docs_received', entity_type: 'importer', entity_label: 'Pharma Import UK', market: 'UK', category: 'cannabis_inventory', score_impact: 5, created_at: '2026-06-17T09:15:00Z', operator: 'system' },
  { id: 're-004', event_type: 'buyer_ignored', entity_type: 'buyer', entity_label: 'NL BioDistrib', market: 'NL', category: 'packaging', score_impact: -4, created_at: '2026-06-16T16:00:00Z', operator: 'system' },
  { id: 're-005', event_type: 'intro_accepted', entity_type: 'buyer', entity_label: 'PharmaVerde PT', market: 'PT', category: 'cannabis_inventory', score_impact: 12, created_at: '2026-06-16T11:30:00Z', operator: 'tyler@harbourview.com' },
  { id: 're-006', event_type: 'deal_stalled', entity_type: 'distributor', entity_label: 'CannaDistrib PL', market: 'PL', category: 'cannabis_inventory', score_impact: -8, created_at: '2026-06-15T14:00:00Z', operator: 'system' },
  { id: 're-007', event_type: 'market_pathway_validated', entity_type: 'route', entity_label: 'LATAM → DE GMP Route', market: 'DE', category: 'eu_gmp', score_impact: 15, created_at: '2026-06-15T09:00:00Z', operator: 'tyler@harbourview.com' },
  { id: 're-008', event_type: 'docs_incomplete', entity_type: 'seller', entity_label: 'AU CannaCo', market: 'AU', category: 'cannabis_inventory', score_impact: -6, created_at: '2026-06-14T17:00:00Z', operator: 'system' },
  { id: 're-009', event_type: 'relationship_upgraded', entity_type: 'buyer', entity_label: 'CZ MedImport', market: 'CZ', category: 'importers', score_impact: 10, created_at: '2026-06-14T12:00:00Z', operator: 'tyler@harbourview.com' },
  { id: 're-010', event_type: 'seller_responded', entity_type: 'seller', entity_label: 'CannaSource Colombia', market: 'LATAM', category: 'cannabis_inventory', score_impact: 7, created_at: '2026-06-13T10:00:00Z', operator: 'system' },
  { id: 're-011', event_type: 'intro_rejected', entity_type: 'buyer', entity_label: 'UK PharmaGroup', market: 'UK', category: 'cannabis_inventory', score_impact: -10, created_at: '2026-06-13T08:30:00Z', operator: 'system' },
  { id: 're-012', event_type: 'deal_moved_forward', entity_type: 'deal', entity_label: 'DE–LATAM Q3 Supply', market: 'DE', category: 'cannabis_inventory', score_impact: 18, created_at: '2026-06-12T15:00:00Z', operator: 'tyler@harbourview.com' },
  { id: 're-013', event_type: 'intro_sent', entity_type: 'buyer', entity_label: 'NL NaturaPharma', market: 'NL', category: 'cannabis_inventory', score_impact: 3, created_at: '2026-06-12T10:00:00Z', operator: 'tyler@harbourview.com' },
  { id: 're-014', event_type: 'docs_requested', entity_type: 'importer', entity_label: 'DE ImportCo', market: 'DE', category: 'eu_gmp', score_impact: 2, created_at: '2026-06-11T14:00:00Z', operator: 'system' },
  { id: 're-015', event_type: 'market_pathway_blocked', entity_type: 'route', entity_label: 'CA → AU Direct Route', market: 'AU', category: 'market_access', score_impact: -12, created_at: '2026-06-11T09:00:00Z', operator: 'system' },
  { id: 're-016', event_type: 'relationship_downgraded', entity_type: 'distributor', entity_label: 'PT DistribGroup', market: 'PT', category: 'distributors', score_impact: -9, created_at: '2026-06-10T16:30:00Z', operator: 'tyler@harbourview.com' },
  { id: 're-017', event_type: 'deal_lost', entity_type: 'deal', entity_label: 'AU Market Entry Q2', market: 'AU', category: 'cannabis_inventory', score_impact: -20, created_at: '2026-06-10T11:00:00Z', operator: 'system' },
  { id: 're-018', event_type: 'seller_ignored', entity_type: 'seller', entity_label: 'PL GreenGrow', market: 'PL', category: 'cannabis_inventory', score_impact: -5, created_at: '2026-06-09T14:00:00Z', operator: 'system' },
  { id: 're-019', event_type: 'intro_proposed', entity_type: 'buyer', entity_label: 'CZ PharmaCo', market: 'CZ', category: 'cannabis_inventory', score_impact: 1, created_at: '2026-06-09T10:00:00Z', operator: 'tyler@harbourview.com' },
  { id: 're-020', event_type: 'buyer_responded', entity_type: 'buyer', entity_label: 'UK MedAccess', market: 'UK', category: 'cannabis_inventory', score_impact: 8, created_at: '2026-06-08T15:00:00Z', operator: 'system' },
  { id: 're-021', event_type: 'docs_received', entity_type: 'seller', entity_label: 'LATAM CannaExport', market: 'LATAM', category: 'eu_gmp', score_impact: 5, created_at: '2026-06-08T11:00:00Z', operator: 'system' },
  { id: 're-022', event_type: 'deal_moved_forward', entity_type: 'deal', entity_label: 'NL Packaging Supply Q3', market: 'NL', category: 'packaging', score_impact: 15, created_at: '2026-06-07T14:00:00Z', operator: 'tyler@harbourview.com' },
  { id: 're-023', event_type: 'relationship_upgraded', entity_type: 'advisor', entity_label: 'EU Regulatory Advisor', market: 'DE', category: 'market_access', score_impact: 8, created_at: '2026-06-07T09:00:00Z', operator: 'tyler@harbourview.com' },
  { id: 're-024', event_type: 'market_pathway_validated', entity_type: 'route', entity_label: 'PT → UK Import Corridor', market: 'UK', category: 'market_access', score_impact: 14, created_at: '2026-06-06T10:00:00Z', operator: 'system' },
]

export const fixtureCommercialPredictions: CommercialPrediction[] = [
  { id: 'cp-001', prediction_type: 'buyer_seller_fit', entity_label: 'MedLeaf GmbH + CannaSource LATAM', market: 'DE', category: 'cannabis_inventory', confidence_score: 0.89, predicted_value: 'Strong fit — aligned on volumes, GMP requirements, and Q3 timing', supporting_factors: ['Both active on EU GMP track', 'Volume alignment: 500kg/mo', 'Responded within 24h historically'], created_at: '2026-06-18T08:00:00Z', status: 'active' },
  { id: 'cp-002', prediction_type: 'importer_fit', entity_label: 'Pharma Import UK', market: 'UK', category: 'importers', confidence_score: 0.76, predicted_value: 'Good fit for mid-volume LATAM product', supporting_factors: ['Prior import record from LATAM', 'UK licence current', 'Known for faster processing'], created_at: '2026-06-17T10:00:00Z', status: 'active' },
  { id: 'cp-003', prediction_type: 'deal_probability', entity_label: 'DE–LATAM Q3 Supply Deal', market: 'DE', category: 'cannabis_inventory', confidence_score: 0.82, predicted_value: '82% probability of close within 45 days', supporting_factors: ['Stage: term sheet', 'Both parties responsive', 'GMP certificates in hand'], created_at: '2026-06-17T14:00:00Z', status: 'active' },
  { id: 'cp-004', prediction_type: 'response_probability', entity_label: 'NL BioDistrib', market: 'NL', category: 'packaging', confidence_score: 0.41, predicted_value: 'Low probability of response within 7 days', supporting_factors: ['3 ignored outreach attempts', 'Q2 was slow period for NL packaging buyers', 'No seasonal trigger identified'], created_at: '2026-06-16T09:00:00Z', status: 'active' },
  { id: 'cp-005', prediction_type: 'documentation_readiness', entity_label: 'CannaSource Colombia', market: 'LATAM', category: 'eu_gmp', confidence_score: 0.71, predicted_value: 'COA and GMP cert likely ready within 2 weeks', supporting_factors: ['Docs requested 10 days ago', 'Historical turnaround: 14 days', 'Previous docs were complete'], created_at: '2026-06-16T12:00:00Z', status: 'active' },
  { id: 'cp-006', prediction_type: 'market_pathway_fit', entity_label: 'LATAM → DE via PT Gateway', market: 'PT', category: 'market_access', confidence_score: 0.85, predicted_value: 'PT gateway reduces import lead time by 3 weeks', supporting_factors: ['PT has established import framework', 'PT–DE re-export corridor validated in 2 prior deals', 'Regulatory contact in PT confirmed available'], created_at: '2026-06-15T11:00:00Z', status: 'validated' },
  { id: 'cp-007', prediction_type: 'distributor_fit', entity_label: 'CannaDistrib PL', market: 'PL', category: 'distributors', confidence_score: 0.58, predicted_value: 'Moderate fit — strong logistics but payment terms misaligned', supporting_factors: ['Good regional coverage', 'Misaligned on 60-day net terms', 'Stalled on previous deal'], created_at: '2026-06-15T15:00:00Z', status: 'active' },
  { id: 'cp-008', prediction_type: 'urgency', entity_label: 'UK PharmaGroup', market: 'UK', category: 'cannabis_inventory', confidence_score: 0.67, predicted_value: 'High urgency — Q3 product launch window closing', supporting_factors: ['Product launch announced for September', 'Current supplier delayed', 'Regulatory submission due July 15'], created_at: '2026-06-14T09:00:00Z', status: 'active' },
  { id: 'cp-009', prediction_type: 'next_best_action', entity_label: 'CZ MedImport', market: 'CZ', category: 'importers', confidence_score: 0.91, predicted_value: 'Send intro brief to 2 qualified LATAM sellers this week', supporting_factors: ['Relationship upgraded last week', 'Expressed preference for LATAM origin', 'Budget confirmed for H2'], created_at: '2026-06-14T13:00:00Z', status: 'active' },
  { id: 'cp-010', prediction_type: 'stale_deal_reactivation', entity_label: 'AU CannaCo – AU Market Entry', market: 'AU', category: 'cannabis_inventory', confidence_score: 0.44, predicted_value: 'Reactivation possible if docs gap resolved within 3 weeks', supporting_factors: ['Deal lost due to incomplete docs', 'Market conditions improved', 'Contact still responsive on LinkedIn'], created_at: '2026-06-13T10:00:00Z', status: 'active' },
  { id: 'cp-011', prediction_type: 'market_timing', entity_label: 'DE Market Q3 Entry Window', market: 'DE', category: 'cannabis_inventory', confidence_score: 0.88, predicted_value: 'Optimal entry window: July–September 2026', supporting_factors: ['CanG wave 2 implementation imminent', 'Buyer procurement cycles active', 'GMP supply constrained — premium pricing'], created_at: '2026-06-13T08:00:00Z', status: 'active' },
  { id: 'cp-012', prediction_type: 'buyer_seller_fit', entity_label: 'PharmaVerde PT + AU CannaCo', market: 'PT', category: 'cannabis_inventory', confidence_score: 0.62, predicted_value: 'Moderate fit — quality aligned but logistics complex', supporting_factors: ['Both GMP certified', 'AU to PT logistics adds 3 weeks lead', 'PT buyer prefers EU-sourced where possible'], created_at: '2026-06-12T11:00:00Z', status: 'active' },
  { id: 'cp-013', prediction_type: 'response_probability', entity_label: 'PT DistribGroup', market: 'PT', category: 'distributors', confidence_score: 0.29, predicted_value: 'Low — relationship downgraded; re-engagement unlikely short term', supporting_factors: ['3 ignored follow-ups post downgrade', 'No new supply match identified', 'Seasonal slowdown in PT market'], created_at: '2026-06-12T15:00:00Z', status: 'active' },
  { id: 'cp-014', prediction_type: 'deal_probability', entity_label: 'NL Packaging Supply Q3', market: 'NL', category: 'packaging', confidence_score: 0.79, predicted_value: '79% probability of close — awaiting final price confirmation', supporting_factors: ['Deal moved forward 7 June', 'Price delta <5%', 'Both parties motivated for Q3 delivery'], created_at: '2026-06-11T10:00:00Z', status: 'validated' },
  { id: 'cp-015', prediction_type: 'importer_fit', entity_label: 'DE ImportCo', market: 'DE', category: 'importers', confidence_score: 0.83, predicted_value: 'Strong fit for GMP-certified EU supply', supporting_factors: ['BfArM licence current', 'Processed 4 similar shipments', 'Docs turnaround: 8 days avg'], created_at: '2026-06-11T14:00:00Z', status: 'active' },
  { id: 'cp-016', prediction_type: 'documentation_readiness', entity_label: 'PL GreenGrow', market: 'PL', category: 'eu_gmp', confidence_score: 0.34, predicted_value: 'Docs unlikely ready within 30 days — audit gap identified', supporting_factors: ['GMP audit overdue', 'Seller ignored 3 doc requests', 'Compliance officer unresponsive'], created_at: '2026-06-10T09:00:00Z', status: 'active' },
  { id: 'cp-017', prediction_type: 'urgency', entity_label: 'CA Cannabis Services RFP', market: 'CA', category: 'services', confidence_score: 0.55, predicted_value: 'Medium urgency — RFP closes August 1', supporting_factors: ['Government RFP posted June 15', 'Submission window: 45 days', '3 known competitors identified'], created_at: '2026-06-10T14:00:00Z', status: 'active' },
  { id: 'cp-018', prediction_type: 'next_best_action', entity_label: 'UK MedAccess', market: 'UK', category: 'cannabis_inventory', confidence_score: 0.87, predicted_value: 'Draft intro packet for 3 LATAM sellers — respond within 5 days', supporting_factors: ['Responded to last 2 outreaches', 'Q3 supply gap confirmed', 'Price range: £2,800–3,200/kg'], created_at: '2026-06-09T10:00:00Z', status: 'active' },
  { id: 'cp-019', prediction_type: 'market_pathway_fit', entity_label: 'CA → UK Medical Channel', market: 'UK', category: 'market_access', confidence_score: 0.72, predicted_value: 'Viable but requires additional Home Office documentation', supporting_factors: ['CA–UK bilateral framework active', 'Home Office import team known', 'Lead time: 8–10 weeks'], created_at: '2026-06-08T11:00:00Z', status: 'expired' },
  { id: 'cp-020', prediction_type: 'stale_deal_reactivation', entity_label: 'CZ PharmaCo – H1 Supply', market: 'CZ', category: 'cannabis_inventory', confidence_score: 0.66, predicted_value: 'Reactivation viable — new intro proposed; await response', supporting_factors: ['Intro proposed June 9', 'Market conditions: improved pricing', 'New seller match identified'], created_at: '2026-06-08T14:00:00Z', status: 'active' },
  { id: 'cp-021', prediction_type: 'distributor_fit', entity_label: 'NL NaturaPharma', market: 'NL', category: 'distributors', confidence_score: 0.81, predicted_value: 'Strong fit — aligned on logistics and payment terms', supporting_factors: ['Prior distribution relationship', 'Same-day response rate historically', 'Volume: 200–400kg/mo capacity'], created_at: '2026-06-07T09:00:00Z', status: 'active' },
  { id: 'cp-022', prediction_type: 'buyer_seller_fit', entity_label: 'AU CannaCo + LATAM CannaExport', market: 'AU', category: 'cannabis_inventory', confidence_score: 0.70, predicted_value: 'Viable fit if import docs are resolved', supporting_factors: ['Volume needs aligned', 'LATAM seller willing to front docs cost', 'AU TGA pathway confirmed'], created_at: '2026-06-07T13:00:00Z', status: 'active' },
  { id: 'cp-023', prediction_type: 'deal_probability', entity_label: 'PT Consumables Tender', market: 'PT', category: 'consumables', confidence_score: 0.48, predicted_value: '48% probability — competitive tender with 5 bidders', supporting_factors: ['Public tender stage', '5 known competitors', 'Harbourview connection at INFARMED'], created_at: '2026-06-06T10:00:00Z', status: 'active' },
  { id: 'cp-024', prediction_type: 'market_timing', entity_label: 'PL Market Expansion Window', market: 'PL', category: 'cannabis_inventory', confidence_score: 0.77, predicted_value: 'Window: H2 2026 — regulatory framework stabilising', supporting_factors: ['Ministry consultations completing Q2', 'First licensed distributors expected Q3', 'Demand forecasted: 12T/year by 2027'], created_at: '2026-06-05T11:00:00Z', status: 'active' },
]

export const fixtureTrustScores: RelationshipTrustScore[] = [
  { id: 'ts-001', entity_label: 'MedLeaf GmbH', entity_type: 'buyer', market: 'DE', category: 'cannabis_inventory', trust_score: 92, responsiveness: 95, document_quality: 88, intro_success: 90, commercial_reliability: 94, relationship_strength: 91, status: 'priority', last_interaction: '2026-06-18T10:00:00Z' },
  { id: 'ts-002', entity_label: 'Pharma Import UK', entity_type: 'importer', market: 'UK', category: 'importers', trust_score: 81, responsiveness: 78, document_quality: 85, intro_success: 80, commercial_reliability: 83, relationship_strength: 79, status: 'priority', last_interaction: '2026-06-17T09:15:00Z' },
  { id: 'ts-003', entity_label: 'CannaSource LATAM', entity_type: 'seller', market: 'LATAM', category: 'eu_gmp', trust_score: 87, responsiveness: 84, document_quality: 91, intro_success: 85, commercial_reliability: 89, relationship_strength: 86, status: 'priority', last_interaction: '2026-06-17T14:30:00Z' },
  { id: 'ts-004', entity_label: 'NL BioDistrib', entity_type: 'distributor', market: 'NL', category: 'packaging', trust_score: 54, responsiveness: 40, document_quality: 62, intro_success: 55, commercial_reliability: 58, relationship_strength: 50, status: 'watch', last_interaction: '2026-06-16T16:00:00Z' },
  { id: 'ts-005', entity_label: 'PharmaVerde PT', entity_type: 'buyer', market: 'PT', category: 'cannabis_inventory', trust_score: 76, responsiveness: 80, document_quality: 74, intro_success: 75, commercial_reliability: 77, relationship_strength: 78, status: 'priority', last_interaction: '2026-06-16T11:30:00Z' },
  { id: 'ts-006', entity_label: 'CannaDistrib PL', entity_type: 'distributor', market: 'PL', category: 'cannabis_inventory', trust_score: 61, responsiveness: 55, document_quality: 67, intro_success: 60, commercial_reliability: 62, relationship_strength: 58, status: 'watch', last_interaction: '2026-06-15T14:00:00Z' },
  { id: 'ts-007', entity_label: 'AU CannaCo', entity_type: 'seller', market: 'AU', category: 'cannabis_inventory', trust_score: 44, responsiveness: 52, document_quality: 36, intro_success: 42, commercial_reliability: 45, relationship_strength: 48, status: 'reengage', last_interaction: '2026-06-14T17:00:00Z' },
  { id: 'ts-008', entity_label: 'CZ MedImport', entity_type: 'importer', market: 'CZ', category: 'importers', trust_score: 79, responsiveness: 82, document_quality: 77, intro_success: 80, commercial_reliability: 78, relationship_strength: 81, status: 'priority', last_interaction: '2026-06-14T12:00:00Z' },
  { id: 'ts-009', entity_label: 'CannaSource Colombia', entity_type: 'seller', market: 'LATAM', category: 'cannabis_inventory', trust_score: 71, responsiveness: 74, document_quality: 69, intro_success: 70, commercial_reliability: 72, relationship_strength: 73, status: 'standard', last_interaction: '2026-06-13T10:00:00Z' },
  { id: 'ts-010', entity_label: 'UK PharmaGroup', entity_type: 'buyer', market: 'UK', category: 'cannabis_inventory', trust_score: 58, responsiveness: 45, document_quality: 65, intro_success: 50, commercial_reliability: 60, relationship_strength: 55, status: 'watch', last_interaction: '2026-06-13T08:30:00Z' },
  { id: 'ts-011', entity_label: 'PT DistribGroup', entity_type: 'distributor', market: 'PT', category: 'distributors', trust_score: 38, responsiveness: 30, document_quality: 42, intro_success: 35, commercial_reliability: 40, relationship_strength: 32, status: 'reengage', last_interaction: '2026-06-10T16:30:00Z' },
  { id: 'ts-012', entity_label: 'EU Regulatory Advisor', entity_type: 'advisor', market: 'DE', category: 'market_access', trust_score: 88, responsiveness: 91, document_quality: 86, intro_success: 88, commercial_reliability: 87, relationship_strength: 90, status: 'priority', last_interaction: '2026-06-07T09:00:00Z' },
  { id: 'ts-013', entity_label: 'DE ImportCo', entity_type: 'importer', market: 'DE', category: 'importers', trust_score: 84, responsiveness: 87, document_quality: 89, intro_success: 82, commercial_reliability: 85, relationship_strength: 83, status: 'priority', last_interaction: '2026-06-11T14:00:00Z' },
  { id: 'ts-014', entity_label: 'NL NaturaPharma', entity_type: 'distributor', market: 'NL', category: 'distributors', trust_score: 82, responsiveness: 89, document_quality: 80, intro_success: 83, commercial_reliability: 81, relationship_strength: 84, status: 'priority', last_interaction: '2026-06-12T10:00:00Z' },
  { id: 'ts-015', entity_label: 'PL GreenGrow', entity_type: 'seller', market: 'PL', category: 'cannabis_inventory', trust_score: 36, responsiveness: 28, document_quality: 32, intro_success: 38, commercial_reliability: 40, relationship_strength: 35, status: 'reengage', last_interaction: '2026-06-09T14:00:00Z' },
  { id: 'ts-016', entity_label: 'LATAM CannaExport', entity_type: 'seller', market: 'LATAM', category: 'eu_gmp', trust_score: 69, responsiveness: 72, document_quality: 74, intro_success: 67, commercial_reliability: 68, relationship_strength: 70, status: 'standard', last_interaction: '2026-06-08T11:00:00Z' },
]

export const fixtureCopilotTasks: AICopilotTask[] = [
  { id: 'ct-001', copilot: 'sourcing', title: 'Match 3 LATAM sellers to DE buyer demand', summary: 'Identify top 3 LATAM GMP-certified sellers aligned with MedLeaf GmbH Q3 volume and quality requirements.', market: 'DE', category: 'cannabis_inventory', priority: 'high', status: 'ready', created_at: '2026-06-18T08:00:00Z' },
  { id: 'ct-002', copilot: 'market_access', title: 'Build PT gateway entry brief', summary: 'Document the LATAM → PT → EU re-export pathway including regulatory contacts, lead times, and required documentation.', market: 'PT', category: 'market_access', priority: 'high', status: 'in_progress', created_at: '2026-06-17T10:00:00Z' },
  { id: 'ct-003', copilot: 'intro_packet', title: 'Draft intro brief: CZ MedImport ↔ CannaSource LATAM', summary: 'Generate structured introduction packet for CZ MedImport to review 2 LATAM seller profiles with volume, quality, and pricing summaries.', market: 'CZ', category: 'cannabis_inventory', priority: 'high', status: 'pending_review', created_at: '2026-06-17T14:00:00Z' },
  { id: 'ct-004', copilot: 'document_readiness', title: 'Review CannaSource Colombia doc package', summary: 'Check completeness of GMP certificate, COA, and export licence. Flag missing items and estimated completion timeline.', market: 'LATAM', category: 'eu_gmp', priority: 'high', status: 'ready', created_at: '2026-06-16T09:00:00Z' },
  { id: 'ct-005', copilot: 'deal_flow', title: 'Stage update: DE–LATAM Q3 Supply Deal', summary: 'Move deal to "term sheet" stage. Draft next steps memo for distribution to both counterparties.', market: 'DE', category: 'cannabis_inventory', priority: 'high', status: 'in_progress', created_at: '2026-06-16T12:00:00Z' },
  { id: 'ct-006', copilot: 'counterparty_research', title: 'Profile NL BioDistrib for re-engagement', summary: 'Build updated profile on NL BioDistrib including recent activity signals, competitive alternatives, and optimal re-engagement timing.', market: 'NL', category: 'packaging', priority: 'medium', status: 'ready', created_at: '2026-06-15T11:00:00Z' },
  { id: 'ct-007', copilot: 'follow_up', title: 'Follow-up sequence: UK PharmaGroup intro rejection', summary: 'Design a 3-step re-engagement sequence following intro rejection. Focus on alternative seller profiles and adjusted value proposition.', market: 'UK', category: 'cannabis_inventory', priority: 'medium', status: 'ready', created_at: '2026-06-15T15:00:00Z' },
  { id: 'ct-008', copilot: 'public_listing', title: 'Draft public listing: DE GMP flower availability', summary: 'Create buyer-facing public listing card for German medical cannabis flower — Q3 batch, GMP EU certified, Lot A available August.', market: 'DE', category: 'cannabis_inventory', priority: 'medium', status: 'pending_review', created_at: '2026-06-14T09:00:00Z' },
  { id: 'ct-009', copilot: 'prediction', title: 'Generate response probability: PT DistribGroup', summary: 'Run response probability model for PT DistribGroup after relationship downgrade. Determine optimal re-engagement window.', market: 'PT', category: 'distributors', priority: 'low', status: 'complete', created_at: '2026-06-14T13:00:00Z' },
  { id: 'ct-010', copilot: 'sourcing', title: 'Source packaging suppliers for NL buyers', summary: 'Identify 5+ EU-based packaging suppliers meeting NL BioDistrib specifications: child-resistant, cannabis-compliant, Q3 availability.', market: 'NL', category: 'packaging', priority: 'medium', status: 'in_progress', created_at: '2026-06-13T10:00:00Z' },
  { id: 'ct-011', copilot: 'market_access', title: 'AU TGA pathway analysis for LATAM seller', summary: 'Document the TGA import pathway for LATAM-origin GMP cannabis flower. Identify regulatory contacts and lead time estimates.', market: 'AU', category: 'market_access', priority: 'medium', status: 'ready', created_at: '2026-06-13T08:00:00Z' },
  { id: 'ct-012', copilot: 'intro_packet', title: 'Draft intro brief: AU CannaCo ↔ LATAM CannaExport', summary: 'Generate introduction document for AU CannaCo to review LATAM CannaExport seller profile including docs status and volume capacity.', market: 'AU', category: 'cannabis_inventory', priority: 'medium', status: 'ready', created_at: '2026-06-12T11:00:00Z' },
  { id: 'ct-013', copilot: 'operator_command', title: 'Execute: send DE buyer demand update to LATAM sellers', summary: 'Broadcast updated DE buyer requirements to 6 qualified LATAM sellers. Track open and response rates.', market: 'DE', category: 'cannabis_inventory', priority: 'high', status: 'complete', created_at: '2026-06-12T15:00:00Z' },
  { id: 'ct-014', copilot: 'deal_flow', title: 'Reactivate: AU Market Entry Q2', summary: 'Assess reactivation viability for lost AU deal. Identify doc gap resolution path and updated seller match.', market: 'AU', category: 'cannabis_inventory', priority: 'low', status: 'ready', created_at: '2026-06-11T10:00:00Z' },
  { id: 'ct-015', copilot: 'document_readiness', title: 'Flag PL GreenGrow doc deficiencies', summary: 'Compile list of outstanding documents for PL GreenGrow. Issue formal document request and set 21-day deadline.', market: 'PL', category: 'eu_gmp', priority: 'medium', status: 'pending_review', created_at: '2026-06-10T09:00:00Z' },
  { id: 'ct-016', copilot: 'public_listing', title: 'Draft CA services listing: regulatory consulting', summary: 'Create public listing for CA-based cannabis regulatory consulting services available for international market access mandates.', market: 'CA', category: 'services', priority: 'low', status: 'complete', created_at: '2026-06-09T10:00:00Z' },
  { id: 'ct-017', copilot: 'prediction', title: 'PL market timing prediction: H2 entry window', summary: 'Run market timing model for PL cannabis market. Identify optimal entry point based on regulatory trajectory and buyer demand signals.', market: 'PL', category: 'cannabis_inventory', priority: 'medium', status: 'complete', created_at: '2026-06-08T11:00:00Z' },
  { id: 'ct-018', copilot: 'counterparty_research', title: 'Profile UK MedAccess for intro packet', summary: 'Build counterparty research summary for UK MedAccess: supply preferences, volume needs, price sensitivity, decision timeline.', market: 'UK', category: 'cannabis_inventory', priority: 'high', status: 'in_progress', created_at: '2026-06-08T14:00:00Z' },
  { id: 'ct-019', copilot: 'sourcing', title: 'Equipment sourcing: CZ and PL lab equipment buyers', summary: 'Identify 4 EU equipment suppliers matching CZ and PL buyer specifications for cannabis testing lab build-outs.', market: 'CZ', category: 'equipment', priority: 'low', status: 'ready', created_at: '2026-06-07T09:00:00Z' },
  { id: 'ct-020', copilot: 'follow_up', title: 'Follow-up: CZ PharmaCo intro proposed', summary: 'Trigger 5-day follow-up on intro proposed to CZ PharmaCo. Prepare alternative seller option if no response.', market: 'CZ', category: 'cannabis_inventory', priority: 'medium', status: 'in_progress', created_at: '2026-06-06T10:00:00Z' },
]

export const fixtureExecutionQueue: AutonomousExecutionQueueItem[] = [
  { id: 'eq-001', queue_type: 'intro_brief_draft', title: 'CZ MedImport ↔ CannaSource LATAM Intro Packet', entity_label: 'CZ MedImport', market: 'CZ', category: 'cannabis_inventory', priority: 'high', status: 'draft_pending_review', due_date: '2026-06-20T17:00:00Z', created_at: '2026-06-17T14:00:00Z' },
  { id: 'eq-002', queue_type: 'document_request_draft', title: 'PL GreenGrow — GMP Document Request', entity_label: 'PL GreenGrow', market: 'PL', category: 'eu_gmp', priority: 'high', status: 'draft_pending_review', due_date: '2026-06-21T12:00:00Z', created_at: '2026-06-17T10:00:00Z' },
  { id: 'eq-003', queue_type: 'buyer_seller_summary', title: 'MedLeaf GmbH Demand Summary — Q3 2026', entity_label: 'MedLeaf GmbH', market: 'DE', category: 'cannabis_inventory', priority: 'high', status: 'ready_to_execute', due_date: '2026-06-19T16:00:00Z', created_at: '2026-06-18T08:00:00Z' },
  { id: 'eq-004', queue_type: 'deal_stage_update', title: 'DE–LATAM Q3 Supply Deal: Move to Term Sheet', entity_label: 'CannaSource LATAM', market: 'DE', category: 'cannabis_inventory', priority: 'high', status: 'ready_to_execute', due_date: '2026-06-19T18:00:00Z', created_at: '2026-06-16T12:00:00Z' },
  { id: 'eq-005', queue_type: 'public_listing_draft', title: 'DE GMP Flower — Q3 Availability Card', entity_label: 'DE GMP Lot A', market: 'DE', category: 'cannabis_inventory', priority: 'medium', status: 'draft_pending_review', due_date: '2026-06-22T12:00:00Z', created_at: '2026-06-14T09:00:00Z' },
  { id: 'eq-006', queue_type: 'follow_up_task', title: 'UK PharmaGroup — Re-engagement Follow-up #1', entity_label: 'UK PharmaGroup', market: 'UK', category: 'cannabis_inventory', priority: 'medium', status: 'follow_up_due', due_date: '2026-06-19T09:00:00Z', created_at: '2026-06-13T08:30:00Z' },
  { id: 'eq-007', queue_type: 'market_access_review_packet', title: 'PT Gateway Pathway Review Packet', entity_label: 'PT Gateway Route', market: 'PT', category: 'market_access', priority: 'high', status: 'draft_pending_review', due_date: '2026-06-21T17:00:00Z', created_at: '2026-06-17T10:00:00Z' },
  { id: 'eq-008', queue_type: 'stale_opportunity_reactivation', title: 'AU Market Entry Q2 — Reactivation Plan', entity_label: 'AU CannaCo', market: 'AU', category: 'cannabis_inventory', priority: 'low', status: 'ready_to_execute', due_date: '2026-06-25T12:00:00Z', created_at: '2026-06-13T10:00:00Z' },
  { id: 'eq-009', queue_type: 'importer_distributor_review_packet', title: 'UK Import Landscape — Q3 Readiness Report', entity_label: 'Pharma Import UK', market: 'UK', category: 'importers', priority: 'medium', status: 'draft_pending_review', due_date: '2026-06-23T12:00:00Z', created_at: '2026-06-15T11:00:00Z' },
  { id: 'eq-010', queue_type: 'evidence_enrichment', title: 'AU CannaCo — Missing Docs Enrichment', entity_label: 'AU CannaCo', market: 'AU', category: 'eu_gmp', priority: 'medium', status: 'ready_to_execute', due_date: '2026-06-22T17:00:00Z', created_at: '2026-06-14T17:00:00Z' },
  { id: 'eq-011', queue_type: 'relationship_reactivation', title: 'PT DistribGroup — 90-Day Re-engagement Plan', entity_label: 'PT DistribGroup', market: 'PT', category: 'distributors', priority: 'low', status: 'ready_to_execute', due_date: null, created_at: '2026-06-10T16:30:00Z' },
  { id: 'eq-012', queue_type: 'intro_brief_draft', title: 'AU CannaCo ↔ LATAM CannaExport Intro Brief', entity_label: 'AU CannaCo', market: 'AU', category: 'cannabis_inventory', priority: 'medium', status: 'draft_pending_review', due_date: '2026-06-24T12:00:00Z', created_at: '2026-06-12T11:00:00Z' },
  { id: 'eq-013', queue_type: 'buyer_seller_summary', title: 'UK MedAccess — Q3 Supply Requirements Summary', entity_label: 'UK MedAccess', market: 'UK', category: 'cannabis_inventory', priority: 'high', status: 'ready_to_execute', due_date: '2026-06-20T12:00:00Z', created_at: '2026-06-08T14:00:00Z' },
  { id: 'eq-014', queue_type: 'deal_stage_update', title: 'NL Packaging Supply — Move to Final Negotiation', entity_label: 'NL NaturaPharma', market: 'NL', category: 'packaging', priority: 'medium', status: 'complete', due_date: '2026-06-18T17:00:00Z', created_at: '2026-06-07T14:00:00Z' },
  { id: 'eq-015', queue_type: 'follow_up_task', title: 'CZ PharmaCo — 5-Day Follow-up on Intro', entity_label: 'CZ PharmaCo', market: 'CZ', category: 'cannabis_inventory', priority: 'medium', status: 'follow_up_due', due_date: '2026-06-19T12:00:00Z', created_at: '2026-06-06T10:00:00Z' },
  { id: 'eq-016', queue_type: 'market_access_review_packet', title: 'AU TGA Pathway — LATAM Seller Entry Brief', entity_label: 'LATAM CannaExport', market: 'AU', category: 'market_access', priority: 'medium', status: 'ready_to_execute', due_date: '2026-06-26T12:00:00Z', created_at: '2026-06-13T08:00:00Z' },
  { id: 'eq-017', queue_type: 'document_request_draft', title: 'CannaSource Colombia — COA + Export Licence Request', entity_label: 'CannaSource Colombia', market: 'LATAM', category: 'eu_gmp', priority: 'high', status: 'ready_to_execute', due_date: '2026-06-20T17:00:00Z', created_at: '2026-06-16T09:00:00Z' },
  { id: 'eq-018', queue_type: 'stale_opportunity_reactivation', title: 'CZ H1 Supply — Reactivation via New Intro', entity_label: 'CZ PharmaCo', market: 'CZ', category: 'cannabis_inventory', priority: 'low', status: 'ready_to_execute', due_date: null, created_at: '2026-06-08T14:00:00Z' },
  { id: 'eq-019', queue_type: 'public_listing_draft', title: 'CA Regulatory Consulting Services Card', entity_label: 'CA Services Provider', market: 'CA', category: 'services', priority: 'low', status: 'complete', due_date: '2026-06-15T17:00:00Z', created_at: '2026-06-09T10:00:00Z' },
  { id: 'eq-020', queue_type: 'evidence_enrichment', title: 'DE ImportCo — Licence Verification Enrichment', entity_label: 'DE ImportCo', market: 'DE', category: 'importers', priority: 'medium', status: 'complete', due_date: '2026-06-17T12:00:00Z', created_at: '2026-06-11T14:00:00Z' },
]

export const fixtureOperatorCommands: OperatorCommandItem[] = [
  { id: 'oc-001', command_type: 'highest_value_action', title: 'Close DE–LATAM Q3 supply deal', description: 'Move DE–LATAM Q3 deal from term sheet to signed agreement. Both parties aligned. Estimated deal value: €480,000.', market: 'DE', category: 'cannabis_inventory', urgency: 'today', entity_label: 'CannaSource LATAM + MedLeaf GmbH', action_label: 'Draft term sheet', created_at: '2026-06-18T08:00:00Z' },
  { id: 'oc-002', command_type: 'best_buyer_seller_match', title: 'MedLeaf GmbH + CannaSource LATAM — confidence 89%', description: 'Best current buyer–seller match in the system. Aligned on volumes, GMP, and Q3 timing. Introduce now.', market: 'DE', category: 'cannabis_inventory', urgency: 'today', entity_label: 'MedLeaf GmbH', action_label: 'Send intro packet', created_at: '2026-06-18T08:30:00Z' },
  { id: 'oc-003', command_type: 'follow_up_due', title: 'UK PharmaGroup — re-engagement follow-up due today', description: 'First follow-up in 3-step re-engagement sequence is due. Send alternative seller profile to reignite interest.', market: 'UK', category: 'cannabis_inventory', urgency: 'today', entity_label: 'UK PharmaGroup', action_label: 'Send follow-up', created_at: '2026-06-18T09:00:00Z' },
  { id: 'oc-004', command_type: 'missing_document', title: 'PL GreenGrow — GMP certificate missing', description: 'GMP certificate overdue by 14 days. Deal cannot proceed without it. Issue formal document request today.', market: 'PL', category: 'eu_gmp', urgency: 'today', entity_label: 'PL GreenGrow', action_label: 'Issue doc request', created_at: '2026-06-18T09:30:00Z' },
  { id: 'oc-005', command_type: 'best_importer_match', title: 'DE ImportCo — best fit for current LATAM supply', description: 'DE ImportCo is the best import match for the CannaSource LATAM batch. BfArM licence current, 8-day doc turnaround.', market: 'DE', category: 'importers', urgency: 'today', entity_label: 'DE ImportCo', action_label: 'Engage importer', created_at: '2026-06-18T10:00:00Z' },
  { id: 'oc-006', command_type: 'deal_likely_to_move', title: 'NL Packaging Supply Q3 — 79% close probability', description: 'NL Packaging deal at 79% close probability. Only remaining blocker is final price confirmation. Resolve today.', market: 'NL', category: 'packaging', urgency: 'this_week', entity_label: 'NL NaturaPharma', action_label: 'Confirm pricing', created_at: '2026-06-18T10:30:00Z' },
  { id: 'oc-007', command_type: 'counterparty_to_contact', title: 'CZ MedImport — ready for LATAM intro this week', description: 'CZ MedImport relationship upgraded, budget confirmed for H2. Window to send LATAM seller intro brief is now.', market: 'CZ', category: 'cannabis_inventory', urgency: 'this_week', entity_label: 'CZ MedImport', action_label: 'Send intro brief', created_at: '2026-06-17T14:00:00Z' },
  { id: 'oc-008', command_type: 'new_signal', title: 'PL regulatory framework stabilising — H2 entry window open', description: 'Ministry consultations completing Q2. First licensed distributors expected Q3. PL market access window opening.', market: 'PL', category: 'cannabis_inventory', urgency: 'this_week', entity_label: 'PL Market', action_label: 'Review PL pipeline', created_at: '2026-06-17T11:00:00Z' },
  { id: 'oc-009', command_type: 'public_card_to_publish', title: 'DE GMP Flower Q3 Availability — listing pending review', description: 'Public listing card for DE GMP flower lot A is drafted and pending approval. Publish before Q3 buyer window opens.', market: 'DE', category: 'cannabis_inventory', urgency: 'this_week', entity_label: 'DE GMP Lot A', action_label: 'Review and publish', created_at: '2026-06-14T09:00:00Z' },
  { id: 'oc-010', command_type: 'market_access_review', title: 'PT Gateway pathway review — ready for operator sign-off', description: 'PT gateway pathway review packet is complete. Operator review required before briefing counterparties.', market: 'PT', category: 'market_access', urgency: 'this_week', entity_label: 'PT Gateway Route', action_label: 'Review packet', created_at: '2026-06-17T10:00:00Z' },
  { id: 'oc-011', command_type: 'trust_change', title: 'AU CannaCo trust score declined to 44 — review relationship', description: 'Trust score dropped 12 points following incomplete docs submission. Determine if relationship is worth continuing.', market: 'AU', category: 'cannabis_inventory', urgency: 'this_week', entity_label: 'AU CannaCo', action_label: 'Review trust score', created_at: '2026-06-14T17:00:00Z' },
  { id: 'oc-012', command_type: 'stale_deal_reactivation', title: 'AU Market Entry Q2 — reactivation viable if docs resolved', description: 'Lost deal reactivation possible within 3 weeks if AU CannaCo resolves docs gap. Initiate enrichment plan.', market: 'AU', category: 'cannabis_inventory', urgency: 'this_week', entity_label: 'AU CannaCo', action_label: 'Start reactivation', created_at: '2026-06-13T10:00:00Z' },
  { id: 'oc-013', command_type: 'prediction_change', title: 'PT DistribGroup response probability dropped to 29%', description: 'Following relationship downgrade, response probability is now critically low. Consider 90-day reactivation plan or alternative.', market: 'PT', category: 'distributors', urgency: 'when_possible', entity_label: 'PT DistribGroup', action_label: 'Review reactivation plan', created_at: '2026-06-12T15:00:00Z' },
  { id: 'oc-014', command_type: 'new_signal', title: 'UK Q3 supply gap — premium pricing window open', description: 'UK MedAccess confirmed Q3 supply gap. Current pricing £2,800–3,200/kg. 3 LATAM sellers in range. Intro this week.', market: 'UK', category: 'cannabis_inventory', urgency: 'this_week', entity_label: 'UK MedAccess', action_label: 'Draft intro packet', created_at: '2026-06-09T10:00:00Z' },
  { id: 'oc-015', command_type: 'follow_up_due', title: 'CZ PharmaCo — 5-day follow-up on intro proposal', description: 'Intro was proposed June 9. 5-day follow-up is due today. Prepare alternative seller option if no response received.', market: 'CZ', category: 'cannabis_inventory', urgency: 'today', entity_label: 'CZ PharmaCo', action_label: 'Send follow-up', created_at: '2026-06-06T10:00:00Z' },
  { id: 'oc-016', command_type: 'counterparty_to_contact', title: 'CA RFP — submission window closing August 1', description: 'Government CA cannabis services RFP submission due August 1. Identify 2 qualified service providers and begin submission prep.', market: 'CA', category: 'services', urgency: 'when_possible', entity_label: 'CA RFP Authority', action_label: 'Begin RFP prep', created_at: '2026-06-10T14:00:00Z' },
]

export const fixtureInstitutionalWorkflows: InstitutionalWorkflowRecord[] = [
  {
    id: 'iw-001',
    title: 'DE–LATAM GMP Import Readiness Review',
    workflow_steps: [
      { key: 'seller_gmp_cert', label: 'Seller GMP certificate verified', completed: true },
      { key: 'coa_reviewed', label: 'COA reviewed and approved', completed: true },
      { key: 'importer_licence', label: 'Importer BfArM licence confirmed', completed: true },
      { key: 'logistics_pathway', label: 'Logistics pathway documented', completed: true },
      { key: 'term_sheet_signed', label: 'Term sheet signed by both parties', completed: false },
      { key: 'shipment_scheduled', label: 'Shipment scheduled', completed: false },
    ],
    completeness_pct: 67,
    market: 'DE',
    category: 'eu_gmp',
    status: 'incomplete',
    analyst_notes: 'Term sheet being drafted. All pre-conditions met. Expected completion: June 25.',
    created_at: '2026-06-10T09:00:00Z',
  },
  {
    id: 'iw-002',
    title: 'UK Importer Due Diligence: Pharma Import UK',
    workflow_steps: [
      { key: 'licence_verified', label: 'Home Office import licence verified', completed: true },
      { key: 'company_check', label: 'Company house check completed', completed: true },
      { key: 'financial_review', label: 'Financial standing reviewed', completed: true },
      { key: 'refs_contacted', label: 'References contacted', completed: true },
      { key: 'approval', label: 'Internal approval granted', completed: true },
    ],
    completeness_pct: 100,
    market: 'UK',
    category: 'importers',
    status: 'approved',
    analyst_notes: 'Full due diligence complete. Approved as preferred UK importer.',
    created_at: '2026-05-28T10:00:00Z',
  },
  {
    id: 'iw-003',
    title: 'PT Market Access Gateway Assessment',
    workflow_steps: [
      { key: 'infarmed_contact', label: 'INFARMED regulatory contact established', completed: true },
      { key: 'import_framework', label: 'Import framework documented', completed: true },
      { key: 'reexport_pathway', label: 'Re-export to EU pathway confirmed', completed: true },
      { key: 'lead_times', label: 'Lead times and cost structure documented', completed: false },
      { key: 'operator_signoff', label: 'Operator sign-off received', completed: false },
    ],
    completeness_pct: 60,
    market: 'PT',
    category: 'market_access',
    status: 'review_ready',
    analyst_notes: 'Lead times being finalised with PT logistics partner. Operator review scheduled June 21.',
    created_at: '2026-06-05T09:00:00Z',
  },
  {
    id: 'iw-004',
    title: 'CZ MedImport Relationship Qualification',
    workflow_steps: [
      { key: 'initial_contact', label: 'Initial outreach completed', completed: true },
      { key: 'volume_confirmed', label: 'Volume requirements confirmed', completed: true },
      { key: 'budget_confirmed', label: 'H2 budget confirmed', completed: true },
      { key: 'intro_sent', label: 'Introduction brief sent', completed: false },
      { key: 'response_received', label: 'Response received from counterparty', completed: false },
    ],
    completeness_pct: 60,
    market: 'CZ',
    category: 'cannabis_inventory',
    status: 'incomplete',
    analyst_notes: 'Intro brief in draft pending review. Expected to be sent by June 20.',
    created_at: '2026-06-08T10:00:00Z',
  },
  {
    id: 'iw-005',
    title: 'AU Regulatory Pathway — TGA Medical Cannabis Import',
    workflow_steps: [
      { key: 'tga_framework', label: 'TGA import framework documented', completed: true },
      { key: 'ods_pathway', label: 'Office of Drug Control pathway confirmed', completed: true },
      { key: 'sponsor_identified', label: 'Authorised sponsor identified', completed: false },
      { key: 'importer_engaged', label: 'Importer engaged', completed: false },
      { key: 'pathway_approved', label: 'Pathway approved by operator', completed: false },
    ],
    completeness_pct: 40,
    market: 'AU',
    category: 'market_access',
    status: 'incomplete',
    analyst_notes: 'Sponsor search in progress. 2 candidates identified. Expected resolution: July 2026.',
    created_at: '2026-06-01T09:00:00Z',
  },
  {
    id: 'iw-006',
    title: 'PL GreenGrow Seller Qualification',
    workflow_steps: [
      { key: 'company_verified', label: 'Company registration verified', completed: true },
      { key: 'gmp_cert', label: 'GMP certificate reviewed', completed: false },
      { key: 'coa_reviewed', label: 'COA for current batch reviewed', completed: false },
      { key: 'export_licence', label: 'Export licence confirmed', completed: false },
      { key: 'approval', label: 'Seller approved for platform', completed: false },
    ],
    completeness_pct: 20,
    market: 'PL',
    category: 'eu_gmp',
    status: 'flagged',
    analyst_notes: 'GMP certificate overdue. Seller unresponsive to 3 requests. Consider disqualification if no response by June 30.',
    created_at: '2026-05-20T09:00:00Z',
  },
  {
    id: 'iw-007',
    title: 'NL Packaging Supply Contract Readiness',
    workflow_steps: [
      { key: 'supplier_qualified', label: 'Packaging supplier qualified', completed: true },
      { key: 'specs_confirmed', label: 'Product specifications confirmed', completed: true },
      { key: 'pricing_agreed', label: 'Pricing agreed in principle', completed: true },
      { key: 'contract_drafted', label: 'Supply contract drafted', completed: true },
      { key: 'legal_review', label: 'Legal review completed', completed: false },
      { key: 'contract_signed', label: 'Contract signed', completed: false },
    ],
    completeness_pct: 67,
    market: 'NL',
    category: 'packaging',
    status: 'review_ready',
    analyst_notes: 'Contract drafted and awaiting legal review. Expected signing by June 26.',
    created_at: '2026-06-02T09:00:00Z',
  },
  {
    id: 'iw-008',
    title: 'LATAM Seller Onboarding: CannaSource Colombia',
    workflow_steps: [
      { key: 'company_registered', label: 'Company registration and licences verified', completed: true },
      { key: 'gmp_cert', label: 'EU GMP certificate verified', completed: true },
      { key: 'coa_baseline', label: 'Baseline COA for primary strains reviewed', completed: true },
      { key: 'export_licence', label: 'Export licence and phytosanitary certificates reviewed', completed: false },
      { key: 'nda_signed', label: 'NDA signed', completed: true },
      { key: 'platform_approved', label: 'Approved for platform', completed: false },
    ],
    completeness_pct: 67,
    market: 'LATAM',
    category: 'eu_gmp',
    status: 'review_ready',
    analyst_notes: 'Export licence expected within 2 weeks. COA and GMP in excellent order.',
    created_at: '2026-06-09T09:00:00Z',
  },
  {
    id: 'iw-009',
    title: 'CA RFP Response: Regulatory Consulting Services',
    workflow_steps: [
      { key: 'rfp_reviewed', label: 'RFP document reviewed', completed: true },
      { key: 'provider_shortlisted', label: 'Provider shortlist compiled', completed: true },
      { key: 'submission_drafted', label: 'Submission drafted', completed: false },
      { key: 'review_complete', label: 'Internal review completed', completed: false },
      { key: 'submitted', label: 'Submission lodged', completed: false },
    ],
    completeness_pct: 40,
    market: 'CA',
    category: 'services',
    status: 'incomplete',
    analyst_notes: 'Submission in progress. Deadline: August 1. On track if draft completed by July 15.',
    created_at: '2026-06-15T09:00:00Z',
  },
  {
    id: 'iw-010',
    title: 'DE Importer Panel: BfArM Licence Review',
    workflow_steps: [
      { key: 'panel_list', label: 'Importer panel list compiled', completed: true },
      { key: 'licences_verified', label: 'All BfArM licences verified', completed: true },
      { key: 'capacity_assessed', label: 'Import capacity assessed', completed: true },
      { key: 'preferred_ranked', label: 'Preferred importers ranked', completed: true },
    ],
    completeness_pct: 100,
    market: 'DE',
    category: 'importers',
    status: 'approved',
    analyst_notes: 'DE importer panel complete. DE ImportCo ranked #1. Review annually.',
    created_at: '2026-05-15T09:00:00Z',
  },
  {
    id: 'iw-011',
    title: 'UK MedAccess Buyer Qualification',
    workflow_steps: [
      { key: 'company_verified', label: 'Company registration verified', completed: true },
      { key: 'licence_confirmed', label: 'Controlled drug licence confirmed', completed: true },
      { key: 'volume_confirmed', label: 'Q3 volume requirements confirmed', completed: true },
      { key: 'price_range', label: 'Accepted price range documented', completed: true },
      { key: 'intro_ready', label: 'Ready for seller introduction', completed: false },
    ],
    completeness_pct: 80,
    market: 'UK',
    category: 'cannabis_inventory',
    status: 'review_ready',
    analyst_notes: 'Buyer profile complete. Intro packet being drafted for 3 LATAM sellers.',
    created_at: '2026-06-08T09:00:00Z',
  },
  {
    id: 'iw-012',
    title: 'NL BioDistrib Re-engagement Assessment',
    workflow_steps: [
      { key: 'history_reviewed', label: 'Relationship history reviewed', completed: true },
      { key: 'market_signals', label: 'Current market signals checked', completed: true },
      { key: 'reengagement_plan', label: 'Re-engagement plan drafted', completed: false },
      { key: 'outreach_sent', label: 'Re-engagement outreach sent', completed: false },
    ],
    completeness_pct: 50,
    market: 'NL',
    category: 'packaging',
    status: 'incomplete',
    analyst_notes: 'Market signals suggest NL packaging demand picking up. Re-engagement plan in progress.',
    created_at: '2026-06-15T09:00:00Z',
  },
  {
    id: 'iw-013',
    title: 'PL Market Entry Strategy Review',
    workflow_steps: [
      { key: 'regulatory_review', label: 'Regulatory landscape reviewed', completed: true },
      { key: 'buyer_mapping', label: 'Buyer demand mapping completed', completed: true },
      { key: 'pathway_identified', label: 'Market entry pathway identified', completed: true },
      { key: 'importer_shortlist', label: 'Importer shortlist compiled', completed: false },
      { key: 'strategy_approved', label: 'Strategy approved by operator', completed: false },
    ],
    completeness_pct: 60,
    market: 'PL',
    category: 'market_access',
    status: 'review_ready',
    analyst_notes: 'Strategy is solid. Awaiting operator review to approve importer shortlist and timeline.',
    created_at: '2026-06-12T09:00:00Z',
  },
  {
    id: 'iw-014',
    title: 'LATAM CannaExport AU Market Entry Docs',
    workflow_steps: [
      { key: 'tga_docs', label: 'TGA-required documentation package compiled', completed: true },
      { key: 'phytosanitary', label: 'Phytosanitary certificate obtained', completed: false },
      { key: 'gmp_translated', label: 'GMP cert translated to English', completed: true },
      { key: 'sponsor_confirmed', label: 'AU authorised sponsor confirmed', completed: false },
      { key: 'submission_ready', label: 'Ready for TGA submission', completed: false },
    ],
    completeness_pct: 40,
    market: 'AU',
    category: 'eu_gmp',
    status: 'incomplete',
    analyst_notes: 'Phytosanitary process underway. Sponsor search ongoing. Target submission: July 15.',
    created_at: '2026-06-07T09:00:00Z',
  },
  {
    id: 'iw-015',
    title: 'DE GMP Flower Listing Approval Workflow',
    workflow_steps: [
      { key: 'listing_drafted', label: 'Public listing card drafted', completed: true },
      { key: 'compliance_check', label: 'Compliance and accuracy check completed', completed: true },
      { key: 'operator_review', label: 'Operator review completed', completed: false },
      { key: 'published', label: 'Listed on public marketplace', completed: false },
    ],
    completeness_pct: 50,
    market: 'DE',
    category: 'cannabis_inventory',
    status: 'review_ready',
    analyst_notes: 'Listing ready for operator review. Approve before June 22 to catch Q3 buyer window.',
    created_at: '2026-06-14T09:00:00Z',
  },
  {
    id: 'iw-016',
    title: 'PT DistribGroup Relationship Recovery Plan',
    workflow_steps: [
      { key: 'downgrade_documented', label: 'Relationship downgrade documented', completed: true },
      { key: 'root_cause', label: 'Root cause analysis completed', completed: true },
      { key: 'recovery_plan', label: '90-day recovery plan drafted', completed: false },
      { key: 'outreach_initiated', label: 'Re-engagement outreach initiated', completed: false },
      { key: 'response_tracked', label: 'Response tracked and scored', completed: false },
    ],
    completeness_pct: 40,
    market: 'PT',
    category: 'distributors',
    status: 'incomplete',
    analyst_notes: 'Root cause: payment terms dispute and competing offer from EU supplier. Recovery plan in progress.',
    created_at: '2026-06-10T09:00:00Z',
  },
]

export const fixtureStrategicMetrics: StrategicDashboardMetric[] = [
  { id: 'sm-001', metric_type: 'market_coverage', label: 'Markets with Active Intelligence', value: 9, unit: 'markets', trend: 'stable', target: 12, market: null },
  { id: 'sm-002', metric_type: 'category_coverage', label: 'Categories with Active Datasets', value: 7, unit: 'categories', trend: 'up', target: 9, market: null },
  { id: 'sm-003', metric_type: 'counterparty_coverage', label: 'Qualified Counterparties', value: 142, unit: 'counterparties', trend: 'up', target: 200, market: null },
  { id: 'sm-004', metric_type: 'deal_velocity', label: 'Deals Moved Forward (30d)', value: 8, unit: 'deals', trend: 'up', target: 12, market: null },
  { id: 'sm-005', metric_type: 'intelligence_freshness', label: 'Avg Dataset Freshness', value: 6, unit: 'days', trend: 'stable', target: 5, market: null },
  { id: 'sm-006', metric_type: 'prediction_confidence', label: 'Avg Prediction Confidence', value: 71, unit: '%', trend: 'up', target: 80, market: null },
  { id: 'sm-007', metric_type: 'response_rate', label: 'Counterparty Response Rate (30d)', value: 64, unit: '%', trend: 'stable', target: 75, market: null },
  { id: 'sm-008', metric_type: 'introduction_success', label: 'Intro Acceptance Rate (30d)', value: 58, unit: '%', trend: 'up', target: 65, market: null },
  { id: 'sm-009', metric_type: 'documentation_readiness', label: 'Sellers with Full Doc Package', value: 43, unit: '%', trend: 'down', target: 70, market: null },
  { id: 'sm-010', metric_type: 'revenue_opportunity', label: 'Open Deal Pipeline Value', value: 2.4, unit: 'M EUR', trend: 'up', target: 4, market: null },
  { id: 'sm-011', metric_type: 'follow_up_load', label: 'Follow-up Tasks Due This Week', value: 6, unit: 'tasks', trend: 'up', target: 4, market: null },
  { id: 'sm-012', metric_type: 'automation_throughput', label: 'AI Tasks Completed (7d)', value: 14, unit: 'tasks', trend: 'up', target: 20, market: null },
  { id: 'sm-013', metric_type: 'market_coverage', label: 'DE Active Intelligence Score', value: 88, unit: '%', trend: 'up', target: 95, market: 'DE' },
  { id: 'sm-014', metric_type: 'relationship_strength', label: 'DE Avg Relationship Score', value: 84, unit: 'pts', trend: 'stable', target: 85, market: 'DE' },
  { id: 'sm-015', metric_type: 'pathway_coverage', label: 'Validated Market Pathways', value: 5, unit: 'pathways', trend: 'up', target: 8, market: null },
  { id: 'sm-016', metric_type: 'source_coverage', label: 'Active Data Sources', value: 28, unit: 'sources', trend: 'up', target: 40, market: null },
  { id: 'sm-017', metric_type: 'market_coverage', label: 'UK Active Intelligence Score', value: 74, unit: '%', trend: 'stable', target: 90, market: 'UK' },
  { id: 'sm-018', metric_type: 'deal_velocity', label: 'AU Deal Velocity (30d)', value: 1, unit: 'deals', trend: 'down', target: 4, market: 'AU' },
  { id: 'sm-019', metric_type: 'counterparty_coverage', label: 'LATAM Qualified Sellers', value: 18, unit: 'sellers', trend: 'up', target: 30, market: 'LATAM' },
  { id: 'sm-020', metric_type: 'intelligence_freshness', label: 'LATAM Seller Data Freshness', value: 12, unit: 'days', trend: 'down', target: 7, market: 'LATAM' },
]
