import 'server-only'
import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import type Stripe from 'stripe'
import { stripe, tierFromPriceId } from '@/lib/stripe/server'
import { SUPABASE_DB_SCHEMA } from '@/lib/supabase/env'
function getSupabaseAdmin(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('[harbourview:webhook] NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY missing.');return createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false},db:{schema:SUPABASE_DB_SCHEMA}})}
type Admin=ReturnType<typeof getSupabaseAdmin>;type HarbourviewTier='free'|'intel'|'operator'
async function alreadyProcessed(s:Admin,id:string){const{data,error}=await s.from('stripe_webhook_events').select('id').eq('id',id).maybeSingle();if(error)throw new Error(`Webhook idempotency lookup failed: ${error.message}`);return Boolean(data)}
async function markProcessed(s:Admin,e:Stripe.Event){const{error}=await s.from('stripe_webhook_events').insert({id:e.id,type:e.type,processed_at:new Date().toISOString()});if(error)throw new Error(`Webhook idempotency insert failed: ${error.message}`)}
async function findUserIdByCustomer(s:Admin,c:string){const{data,error}=await s.from('user_profiles').select('id').eq('stripe_customer_id',c).maybeSingle();if(error)throw new Error(`Customer mapping lookup failed: ${error.message}`);return data?.id??null}
async function repairCustomerMappingFromMetadata(s:Admin,sub:Stripe.Subscription,c:string){const uid=sub.metadata?.supabase_user_id;if(!uid)return null;const{data:p,error}=await s.from('user_profiles').select('id,stripe_customer_id').eq('id',uid).maybeSingle();if(error)throw new Error(`Subscription metadata profile lookup failed: ${error.message}`);if(!p)return null;if(p.stripe_customer_id&&p.stripe_customer_id!==c)throw new Error('Subscription metadata user is already mapped to a different Stripe customer.');if(!p.stripe_customer_id){const{error:e}=await s.from('user_profiles').update({stripe_customer_id:c,updated_at:new Date().toISOString()}).eq('id',uid);if(e)throw new Error(`Customer mapping repair failed: ${e.message}`)}return uid}
async function syncAppMetadataTier(s:Admin,uid:string,tier:HarbourviewTier){const{error}=await s.auth.admin.updateUserById(uid,{app_metadata:{subscription_tier:tier}});if(error)throw new Error(`app_metadata tier sync failed: ${error.message}`)}
async function recomputeUserEntitlement(s:Admin,uid:string){const{data:subs,error}=await s.from('subscriptions').select('tier,status').eq('user_id',uid);if(error)throw new Error(`Subscription entitlement query failed: ${error.message}`);let tier:HarbourviewTier='free';for(const sub of subs??[]){if(sub.status!=='active'&&sub.status!=='trialing')continue;if(sub.tier==='operator'){tier='operator';break}if(sub.tier==='intel')tier='intel'}const{error:e}=await s.from('user_profiles').update({tier,updated_at:new Date().toISOString()}).eq('id',uid);if(e)throw new Error(`user_profiles tier update failed: ${e.message}`);await syncAppMetadataTier(s,uid,tier);return tier}
async function syncSubscription(s:Admin,sub:Stripe.Subscription){const customerId=typeof sub.customer==='string'?sub.customer:sub.customer.id;const item=sub.items.data[0];const priceId=item?.price?.id??null;const tier=priceId?tierFromPriceId(priceId):null;if(!tier){console.info('[harbourview:webhook] ignoring non-Harbourview subscription',{subscriptionId:sub.id,priceId});return}let uid=await findUserIdByCustomer(s,customerId);if(!uid)uid=await repairCustomerMappingFromMetadata(s,sub,customerId);if(!uid)return;const{error}=await s.from('subscriptions').upsert({id:sub.id,user_id:uid,stripe_customer_id:customerId,status:sub.status,tier,price_id:priceId,current_period_start:item?.current_period_start?new Date(item.current_period_start*1000).toISOString():null,current_period_end:item?.current_period_end?new Date(item.current_period_end*1000).toISOString():null,cancel_at_period_end:sub.cancel_at_period_end,canceled_at:sub.canceled_at?new Date(sub.canceled_at*1000).toISOString():null,updated_at:new Date().toISOString()},{onConflict:'id'});if(error)throw new Error(`subscriptions upsert failed: ${error.message}`);await recomputeUserEntitlement(s,uid)}
async function handleCancellation(s:Admin,sub:Stripe.Subscription){const customerId=typeof sub.customer==='string'?sub.customer:sub.customer.id;let uid=await findUserIdByCustomer(s,customerId);if(!uid){const{data,error}=await s.from('subscriptions').select('user_id').eq('id',sub.id).maybeSingle();if(error)throw new Error(`Canceled subscription lookup failed: ${error.message}`);uid=data?.user_id??null}if(!uid)return;const{error}=await s.from('subscriptions').update({status:'canceled',canceled_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',sub.id);if(error)throw new Error(`Subscription cancellation persistence failed: ${error.message}`);await recomputeUserEntitlement(s,uid)}
async function handleMarketEntryCheckout(s:Admin,session:Stripe.Checkout.Session){if(session.metadata?.product!=='market_entry_report')return;const missionId=session.metadata.mission_id;const uid=session.metadata.supabase_user_id;if(!missionId||!uid)throw new Error('Market Entry checkout is missing mission/user metadata.');if(session.payment_status!=='paid')return;const paymentIntentId=typeof session.payment_intent==='string'?session.payment_intent:session.payment_intent?.id??null;const{data:mission,error}=await s.from('market_entry_missions').select('id,owner_user_id,status,payment_status,plan_snapshot').eq('id',missionId).maybeSingle();if(error)throw new Error(`Market Entry mission lookup failed: ${error.message}`);if(!mission)throw new Error('Market Entry mission referenced by Stripe checkout does not exist.');if(mission.owner_user_id!==uid)throw new Error('Market Entry checkout user does not own the referenced mission.');if(mission.payment_status==='paid')return;const{error:updateError}=await s.from('market_entry_missions').update({payment_status:'paid',report_status:'ready',stripe_payment_intent_id:paymentIntentId,report_snapshot:mission.plan_snapshot,paid_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',missionId).eq('owner_user_id',uid);if(updateError)throw new Error(`Market Entry payment persistence failed: ${updateError.message}`);const{error:eventError}=await s.from('market_entry_events').insert({mission_id:missionId,actor_user_id:uid,event_type:'report_paid',from_status:mission.status,to_status:mission.status,payload:{checkoutSessionId:session.id,paymentIntentId}});if(eventError)throw new Error(`Market Entry payment audit event failed: ${eventError.message}`)}
export async function POST(req:NextRequest){const body=await req.text();const signature=req.headers.get('stripe-signature');const secret=process.env.STRIPE_WEBHOOK_SECRET;if(!signature||!secret)return NextResponse.json({error:'Missing stripe-signature or webhook secret.'},{status:400});let event:Stripe.Event;try{event=stripe.webhooks.constructEvent(body,signature,secret)}catch(err){console.error('[harbourview:webhook] signature verification failed',err);return NextResponse.json({error:'Webhook signature invalid.'},{status:400})}const s=getSupabaseAdmin();try{if(await alreadyProcessed(s,event.id))return NextResponse.json({received:true,deduped:true});switch(event.type){case'checkout.session.completed':{const session=event.data.object as Stripe.Checkout.Session;if(session.subscription){const subscriptionId=typeof session.subscription==='string'?session.subscription:session.subscription.id;await syncSubscription(s,await stripe.subscriptions.retrieve(subscriptionId))}else await handleMarketEntryCheckout(s,session);break}case'customer.subscription.created':case'customer.subscription.updated':await syncSubscription(s,event.data.object as Stripe.Subscription);break;case'customer.subscription.deleted':await handleCancellation(s,event.data.object as Stripe.Subscription);break;default:break}await markProcessed(s,event)}catch(err){console.error('[harbourview:webhook] handler error',err);return NextResponse.json({error:'Webhook handler failed.'},{status:500})}return NextResponse.json({received:true})}
