import 'server-only'
import {createHash} from 'node:crypto'
import type {CorridorPlan} from '@/lib/intelligence/workflowEngine'
import {createSupabaseServiceClient} from '@/lib/supabase/server'
import type {EvidenceRef,EvidenceSnapshot,EvidenceStatus} from './types'
const fresh=90
type Row={claim_key:string;jurisdiction_iso2:string;claim_text:string;product_class:string;authority_name:string;authority_url:string;source_effective_date:string|null;retrieved_at:string|null;verified_at:string|null;expires_at:string|null;evidence_status:string;source_snapshot_sha256:string|null}
const date=(v:string|null)=>{if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()}
const classify=(r:Row,now:Date):EvidenceStatus=>{if(!r.verified_at||!r.expires_at)return'unverified';if(Date.parse(r.expires_at)<=now.getTime())return'stale';if(r.evidence_status==='rejected'||r.evidence_status==='superseded')return'conflicted';if(!r.authority_url||!r.source_effective_date||!r.retrieved_at||!r.source_snapshot_sha256)return'partial';return Math.floor((now.getTime()-Date.parse(r.verified_at))/86400000)>fresh?'stale':r.evidence_status==='verified'?'verified':'partial'}
export async function buildEvidenceSnapshot(plan:CorridorPlan,options:{now?:Date;productClass?:string}={}):Promise<EvidenceSnapshot>{const now=options.now??new Date();const p=options.productClass??'any';const missing=(iso:string):EvidenceRef=>({id:createHash('sha256').update(`missing-claim-ledger|${iso}`).digest('hex').slice(0,24),jurisdictionIso2:iso,claim:'No claim-level regulatory evidence is available for this jurisdiction/product combination.',status:'unverified',sourceName:'No authoritative claim record available',sourceUrl:null,effectiveAt:null,verifiedAt:null,expiresAt:null,retrievedAt:now.toISOString(),hash:null});try{const s=await createSupabaseServiceClient();const is=[plan.origin.iso2,plan.destination.iso2];const{data,error}=await s.from('regulatory_market_access_claims').select('claim_key,jurisdiction_iso2,claim_text,product_class,authority_name,authority_url,source_effective_date,retrieved_at,verified_at,expires_at,evidence_status,source_snapshot_sha256').in('jurisdiction_iso2',is).in('product_class',['any',p]).order('verified_at',{ascending:false});if(error)throw error;const rows=(data??[])as Row[];const refs=is.map(iso=>{const c=rows.filter(r=>r.jurisdiction_iso2===iso).find(r=>r.product_class===p&&r.product_class!=='any')??rows.find(r=>r.jurisdiction_iso2===iso);if(!c)return missing(iso);return{id:c.claim_key,jurisdictionIso2:iso,claim:c.claim_text,status:classify(c,now),sourceName:c.authority_name,sourceUrl:c.authority_url||null,effectiveAt:date(c.source_effective_date),verifiedAt:date(c.verified_at),expiresAt:date(c.expires_at),retrievedAt:date(c.retrieved_at)??now.toISOString(),hash:c.source_snapshot_sha256}});return{snapshotId:createHash('sha256').update(JSON.stringify(refs)).digest('hex'),generatedAt:now.toISOString(),freshnessDays:fresh,references:refs,sourceCount:refs.filter(r=>Boolean(r.sourceUrl&&r.hash)).length}}catch{return{snapshotId:createHash('sha256').update(JSON.stringify([plan.origin.iso2,plan.destination.iso2])).digest('hex'),generatedAt:now.toISOString(),freshnessDays:fresh,references:[missing(plan.origin.iso2),missing(plan.destination.iso2)],sourceCount:0}}}
