import 'server-only'
import {createHash,randomUUID} from 'node:crypto'
import {deriveCorridorPlan} from '@/lib/intelligence/workflowEngine'
import {APPLICABLE_TRADE_JURISDICTIONS,type ProductClass} from '@/lib/intelligence/tradeCorridors'
import {buildEvidenceSnapshot} from './evidence'
import {buildExecutionGraph} from './executionGraph'
import type {CostComponent,CostEstimate,CorridorDecisionRecord,ExecutionGraph,MarketEntryInput,MarketEntryPlan,ReadinessGate} from './types'
const PRODUCTS:Array<ProductClass|'any'>=['any','flower','extract','finished_product','starting_material']
const role=(code:string,side:'origin'|'destination')=>{const j=APPLICABLE_TRADE_JURISDICTIONS.find(x=>x.iso2===code);return Boolean(j&&(j.role==='both'||j.role===side))}
function costs(plan:Awaited<ReturnType<typeof deriveCorridorPlan>>):CostEstimate{if(!plan)return{currency:'USD',components:[],knownLow:null,knownHigh:null,unknownCount:1,disclaimer:'No cost estimate is available without a valid corridor plan.'};const components:CostComponent[]=plan.estimatedCostRanges.map(e=>{const nums=[...e.range.matchAll(/\d[\d,]*(?:\.\d+)?/g)].map(m=>Number(m[0].replace(/,/g,'')));const cur=(e.range.match(/(USD|EUR|CAD|GBP|AUD|NZD|CHF|JPY)/i)?.[1]??'USD').toUpperCase();return{id:`jurisdiction-${e.country_iso2}`,category:'unknown',side:e.country_iso2===plan.origin.iso2?'export':'import',amountLow:nums[0]??null,amountHigh:nums[1]??nums[0]??null,currency:nums.length?cur:null,basis:'Editorial jurisdiction playbook range; not a landed-cost quotation.',evidenceIds:[],confidence:'partial'}});const currencies=[...new Set(components.map(c=>c.currency).filter(Boolean))];const known=components.filter(c=>c.amountLow!==null&&c.amountHigh!==null&&c.currency===currencies[0]);return{currency:currencies.length===1?currencies[0]!:'USD',components,knownLow:known.length?known.reduce((s,c)=>s+c.amountLow!,0):null,knownHigh:known.length?known.reduce((s,c)=>s+c.amountHigh!,0):null,unknownCount:components.filter(c=>c.amountLow===null||c.currency===null).length,disclaimer:'Planning estimate only; it excludes unstructured or unverified licensing, testing, customs, duties, brokerage, logistics, insurance, tax, facility, and professional-service costs.'}}
function decision(input:MarketEntryInput,plan:NonNullable<Awaited<ReturnType<typeof deriveCorridorPlan>>>,e:Awaited<ReturnType<typeof buildEvidenceSnapshot>>,g:ExecutionGraph):CorridorDecisionRecord{const gates:ReadinessGate[]=[{id:'origin-role',label:'Origin trade role',state:role(input.originIso2,'origin')?'pass':'fail',reason:role(input.originIso2,'origin')?'Jurisdiction is configured as an origin or both.':'Jurisdiction is not configured as an eligible origin.',evidenceIds:[]},{id:'destination-role',label:'Destination trade role',state:role(input.destinationIso2,'destination')?'pass':'fail',reason:role(input.destinationIso2,'destination')?'Jurisdiction is configured as a destination or both.':'Jurisdiction is not configured as an eligible destination.',evidenceIds:[]},{id:'product-compatibility',label:'Product compatibility',state:plan.corridorRef||input.productClass==='any'?'pass':'fail',reason:plan.corridorRef||input.productClass==='any'?'The selected product is represented by the corridor model.':'The selected product is not represented by the tracked corridor matrix.',evidenceIds:[]}];const verified=e.references.length>0&&e.references.every(r=>r.status==='verified');gates.push({id:'primary-source-evidence',label:'Claim-level primary-source evidence',state:verified?'pass':'fail',reason:verified?'Current claim-level primary-source evidence is verified.':'Complete current claim-level primary-source evidence is required before execution.',evidenceIds:e.references.map(r=>r.id)},{id:'execution-graph',label:'Execution dependency graph',state:g.cycleDetected?'fail':'pass',reason:g.cycleDetected?'A dependency cycle was detected.':'Execution tasks form an acyclic dependency graph.',evidenceIds:[]});const blockers=gates.filter(x=>x.state==='fail').map(x=>x.reason);const warnings=gates.filter(x=>x.state==='warn').map(x=>x.reason);return{decision:blockers.length?'conditional':'permitted',executable:!blockers.length&&!warnings.length,gates,blockers,warnings}}
export async function buildMarketEntryPlan(raw:MarketEntryInput,options:{now?:Date;freshnessDays?:number}={}):Promise<MarketEntryPlan|null>{const o=raw.originIso2.trim().toUpperCase(),d=raw.destinationIso2.trim().toUpperCase(),p=PRODUCTS.includes(raw.productClass)?raw.productClass:null;if(!/^[A-Z]{2}$/.test(o)||!/^[A-Z]{2}$/.test(d)||o===d||!p)return null;const input={originIso2:o,destinationIso2:d,productClass:p,requestedAt:raw.requestedAt};const plan=await deriveCorridorPlan(o,d,{productClass:p});if(!plan)return null;const evidence=await buildEvidenceSnapshot(plan,{...options,productClass:p});const execution=buildExecutionGraph(plan);const dec=decision(input,plan,evidence,execution);return{planVersion:2,planId:randomUUID(),input,status:dec.executable?'ready':dec.blockers.length?'blocked':'orientation',generatedAt:(options.now??new Date()).toISOString(),decision:dec,evidence,execution,documentation:{required:plan.documentationChecklist.filter(x=>x.required).map(x=>x.label),optional:plan.documentationChecklist.filter(x=>!x.required).map(x=>x.label),orientationOnly:!dec.executable},costs:costs(plan),notes:plan.notes,sourceTrust:plan.trust.confidenceLabel,reproducibilityKey:createHash('sha256').update(JSON.stringify({input,evidence:evidence.snapshotId,execution})).digest('hex')}}
export function listAllApplicableJurisdictions(){return[...APPLICABLE_TRADE_JURISDICTIONS].sort((a,b)=>a.name.localeCompare(b.name))}
export function getCoverageStats(){return{jurisdictions:APPLICABLE_TRADE_JURISDICTIONS.length,products:PRODUCTS}}
