// Generated by scripts/country-data/generate-iso-region-rows.py
// ISO conversion: pycountry 24.6.1; region/subregion: checked-in UN M49-derived Harbourview identities.
export const isoRegionRows = [
  [
    "AD",
    "AND",
    "Europe",
    "Southern Europe"
  ],
  [
    "AE",
    "ARE",
    "Asia",
    "Western Asia"
  ],
  [
    "AF",
    "AFG",
    "Asia",
    "Southern Asia"
  ],
  [
    "AG",
    "ATG",
    "Americas",
    "Caribbean"
  ],
  [
    "AI",
    "AIA",
    "Americas",
    "Caribbean"
  ],
  [
    "AL",
    "ALB",
    "Europe",
    "Southern Europe"
  ],
  [
    "AM",
    "ARM",
    "Asia",
    "Western Asia"
  ],
  [
    "AO",
    "AGO",
    "Africa",
    "Middle Africa"
  ],
  [
    "AQ",
    "ATA",
    "",
    ""
  ],
  [
    "AR",
    "ARG",
    "Americas",
    "South America"
  ],
  [
    "AS",
    "ASM",
    "Oceania",
    "Polynesia"
  ],
  [
    "AT",
    "AUT",
    "Europe",
    "Western Europe"
  ],
  [
    "AU",
    "AUS",
    "Oceania",
    "Australia and New Zealand"
  ],
  [
    "AW",
    "ABW",
    "Americas",
    "Caribbean"
  ],
  [
    "AX",
    "ALA",
    "Europe",
    "Northern Europe"
  ],
  [
    "AZ",
    "AZE",
    "Asia",
    "Western Asia"
  ],
  [
    "BA",
    "BIH",
    "Europe",
    "Southern Europe"
  ],
  [
    "BB",
    "BRB",
    "Americas",
    "Caribbean"
  ],
  [
    "BD",
    "BGD",
    "Asia",
    "Southern Asia"
  ],
  [
    "BE",
    "BEL",
    "Europe",
    "Western Europe"
  ],
  [
    "BF",
    "BFA",
    "Africa",
    "Western Africa"
  ],
  [
    "BG",
    "BGR",
    "Europe",
    "Eastern Europe"
  ],
  [
    "BH",
    "BHR",
    "Asia",
    "Western Asia"
  ],
  [
    "BI",
    "BDI",
    "Africa",
    "Eastern Africa"
  ],
  [
    "BJ",
    "BEN",
    "Africa",
    "Western Africa"
  ],
  [
    "BL",
    "BLM",
    "Americas",
    "Caribbean"
  ],
  [
    "BM",
    "BMU",
    "Americas",
    "Northern America"
  ],
  [
    "BN",
    "BRN",
    "Asia",
    "South-eastern Asia"
  ],
  [
    "BO",
    "BOL",
    "Americas",
    "South America"
  ],
  [
    "BQ",
    "BES",
    "Americas",
    "Caribbean"
  ],
  [
    "BR",
    "BRA",
    "Americas",
    "South America"
  ],
  [
    "BS",
    "BHS",
    "Americas",
    "Caribbean"
  ],
  [
    "BT",
    "BTN",
    "Asia",
    "Southern Asia"
  ],
  [
    "BV",
    "BVT",
    "Americas",
    "South America"
  ],
  [
    "BW",
    "BWA",
    "Africa",
    "Southern Africa"
  ],
  [
    "BY",
    "BLR",
    "Europe",
    "Eastern Europe"
  ],
  [
    "BZ",
    "BLZ",
    "Americas",
    "Central America"
  ],
  [
    "CA",
    "CAN",
    "Americas",
    "Northern America"
  ],
  [
    "CC",
    "CCK",
    "Oceania",
    "Australia and New Zealand"
  ],
  [
    "CD",
    "COD",
    "Africa",
    "Middle Africa"
  ],
  [
    "CF",
    "CAF",
    "Africa",
    "Middle Africa"
  ],
  [
    "CG",
    "COG",
    "Africa",
    "Middle Africa"
  ],
  [
    "CH",
    "CHE",
    "Europe",
    "Western Europe"
  ],
  [
    "CI",
    "CIV",
    "Africa",
    "Western Africa"
  ],
  [
    "CK",
    "COK",
    "Oceania",
    "Polynesia"
  ],
  [
    "CL",
    "CHL",
    "Americas",
    "South America"
  ],
  [
    "CM",
    "CMR",
    "Africa",
    "Middle Africa"
  ],
  [
    "CN",
    "CHN",
    "Asia",
    "Eastern Asia"
  ],
  [
    "CO",
    "COL",
    "Americas",
    "South America"
  ],
  [
    "CR",
    "CRI",
    "Americas",
    "Central America"
  ],
  [
    "CU",
    "CUB",
    "Americas",
    "Caribbean"
  ],
  [
    "CV",
    "CPV",
    "Africa",
    "Western Africa"
  ],
  [
    "CW",
    "CUW",
    "Americas",
    "Caribbean"
  ],
  [
    "CX",
    "CXR",
    "Oceania",
    "Australia and New Zealand"
  ],
  [
    "CY",
    "CYP",
    "Asia",
    "Western Asia"
  ],
  [
    "CZ",
    "CZE",
    "Europe",
    "Eastern Europe"
  ],
  [
    "DE",
    "DEU",
    "Europe",
    "Western Europe"
  ],
  [
    "DJ",
    "DJI",
    "Africa",
    "Eastern Africa"
  ],
  [
    "DK",
    "DNK",
    "Europe",
    "Northern Europe"
  ],
  [
    "DM",
    "DMA",
    "Americas",
    "Caribbean"
  ],
  [
    "DO",
    "DOM",
    "Americas",
    "Caribbean"
  ],
  [
    "DZ",
    "DZA",
    "Africa",
    "Northern Africa"
  ],
  [
    "EC",
    "ECU",
    "Americas",
    "South America"
  ],
  [
    "EE",
    "EST",
    "Europe",
    "Northern Europe"
  ],
  [
    "EG",
    "EGY",
    "Africa",
    "Northern Africa"
  ],
  [
    "EH",
    "ESH",
    "Africa",
    "Northern Africa"
  ],
  [
    "ER",
    "ERI",
    "Africa",
    "Eastern Africa"
  ],
  [
    "ES",
    "ESP",
    "Europe",
    "Southern Europe"
  ],
  [
    "ET",
    "ETH",
    "Africa",
    "Eastern Africa"
  ],
  [
    "FI",
    "FIN",
    "Europe",
    "Northern Europe"
  ],
  [
    "FJ",
    "FJI",
    "Oceania",
    "Melanesia"
  ],
  [
    "FK",
    "FLK",
    "Americas",
    "South America"
  ],
  [
    "FM",
    "FSM",
    "Oceania",
    "Micronesia"
  ],
  [
    "FO",
    "FRO",
    "Europe",
    "Northern Europe"
  ],
  [
    "FR",
    "FRA",
    "Europe",
    "Western Europe"
  ],
  [
    "GA",
    "GAB",
    "Africa",
    "Middle Africa"
  ],
  [
    "GB",
    "GBR",
    "Europe",
    "Northern Europe"
  ],
  [
    "GD",
    "GRD",
    "Americas",
    "Caribbean"
  ],
  [
    "GE",
    "GEO",
    "Asia",
    "Western Asia"
  ],
  [
    "GF",
    "GUF",
    "Americas",
    "South America"
  ],
  [
    "GG",
    "GGY",
    "Europe",
    "Northern Europe"
  ],
  [
    "GH",
    "GHA",
    "Africa",
    "Western Africa"
  ],
  [
    "GI",
    "GIB",
    "Europe",
    "Southern Europe"
  ],
  [
    "GL",
    "GRL",
    "Americas",
    "Northern America"
  ],
  [
    "GM",
    "GMB",
    "Africa",
    "Western Africa"
  ],
  [
    "GN",
    "GIN",
    "Africa",
    "Western Africa"
  ],
  [
    "GP",
    "GLP",
    "Americas",
    "Caribbean"
  ],
  [
    "GQ",
    "GNQ",
    "Africa",
    "Middle Africa"
  ],
  [
    "GR",
    "GRC",
    "Europe",
    "Southern Europe"
  ],
  [
    "GS",
    "SGS",
    "Americas",
    "South America"
  ],
  [
    "GT",
    "GTM",
    "Americas",
    "Central America"
  ],
  [
    "GU",
    "GUM",
    "Oceania",
    "Micronesia"
  ],
  [
    "GW",
    "GNB",
    "Africa",
    "Western Africa"
  ],
  [
    "GY",
    "GUY",
    "Americas",
    "South America"
  ],
  [
    "HK",
    "HKG",
    "Asia",
    "Eastern Asia"
  ],
  [
    "HM",
    "HMD",
    "Oceania",
    "Australia and New Zealand"
  ],
  [
    "HN",
    "HND",
    "Americas",
    "Central America"
  ],
  [
    "HR",
    "HRV",
    "Europe",
    "Southern Europe"
  ],
  [
    "HT",
    "HTI",
    "Americas",
    "Caribbean"
  ],
  [
    "HU",
    "HUN",
    "Europe",
    "Eastern Europe"
  ],
  [
    "ID",
    "IDN",
    "Asia",
    "South-eastern Asia"
  ],
  [
    "IE",
    "IRL",
    "Europe",
    "Northern Europe"
  ],
  [
    "IL",
    "ISR",
    "Asia",
    "Western Asia"
  ],
  [
    "IM",
    "IMN",
    "Europe",
    "Northern Europe"
  ],
  [
    "IN",
    "IND",
    "Asia",
    "Southern Asia"
  ],
  [
    "IO",
    "IOT",
    "Africa",
    "Eastern Africa"
  ],
  [
    "IQ",
    "IRQ",
    "Asia",
    "Western Asia"
  ],
  [
    "IR",
    "IRN",
    "Asia",
    "Southern Asia"
  ],
  [
    "IS",
    "ISL",
    "Europe",
    "Northern Europe"
  ],
  [
    "IT",
    "ITA",
    "Europe",
    "Southern Europe"
  ],
  [
    "JE",
    "JEY",
    "Europe",
    "Northern Europe"
  ],
  [
    "JM",
    "JAM",
    "Americas",
    "Caribbean"
  ],
  [
    "JO",
    "JOR",
    "Asia",
    "Western Asia"
  ],
  [
    "JP",
    "JPN",
    "Asia",
    "Eastern Asia"
  ],
  [
    "KE",
    "KEN",
    "Africa",
    "Eastern Africa"
  ],
  [
    "KG",
    "KGZ",
    "Asia",
    "Central Asia"
  ],
  [
    "KH",
    "KHM",
    "Asia",
    "South-eastern Asia"
  ],
  [
    "KI",
    "KIR",
    "Oceania",
    "Micronesia"
  ],
  [
    "KM",
    "COM",
    "Africa",
    "Eastern Africa"
  ],
  [
    "KN",
    "KNA",
    "Americas",
    "Caribbean"
  ],
  [
    "KP",
    "PRK",
    "Asia",
    "Eastern Asia"
  ],
  [
    "KR",
    "KOR",
    "Asia",
    "Eastern Asia"
  ],
  [
    "KW",
    "KWT",
    "Asia",
    "Western Asia"
  ],
  [
    "KY",
    "CYM",
    "Americas",
    "Caribbean"
  ],
  [
    "KZ",
    "KAZ",
    "Asia",
    "Central Asia"
  ],
  [
    "LA",
    "LAO",
    "Asia",
    "South-eastern Asia"
  ],
  [
    "LB",
    "LBN",
    "Asia",
    "Western Asia"
  ],
  [
    "LC",
    "LCA",
    "Americas",
    "Caribbean"
  ],
  [
    "LI",
    "LIE",
    "Europe",
    "Western Europe"
  ],
  [
    "LK",
    "LKA",
    "Asia",
    "Southern Asia"
  ],
  [
    "LR",
    "LBR",
    "Africa",
    "Western Africa"
  ],
  [
    "LS",
    "LSO",
    "Africa",
    "Southern Africa"
  ],
  [
    "LT",
    "LTU",
    "Europe",
    "Northern Europe"
  ],
  [
    "LU",
    "LUX",
    "Europe",
    "Western Europe"
  ],
  [
    "LV",
    "LVA",
    "Europe",
    "Northern Europe"
  ],
  [
    "LY",
    "LBY",
    "Africa",
    "Northern Africa"
  ],
  [
    "MA",
    "MAR",
    "Africa",
    "Northern Africa"
  ],
  [
    "MC",
    "MCO",
    "Europe",
    "Western Europe"
  ],
  [
    "MD",
    "MDA",
    "Europe",
    "Eastern Europe"
  ],
  [
    "ME",
    "MNE",
    "Europe",
    "Southern Europe"
  ],
  [
    "MF",
    "MAF",
    "Americas",
    "Caribbean"
  ],
  [
    "MG",
    "MDG",
    "Africa",
    "Eastern Africa"
  ],
  [
    "MH",
    "MHL",
    "Oceania",
    "Micronesia"
  ],
  [
    "MK",
    "MKD",
    "Europe",
    "Southern Europe"
  ],
  [
    "ML",
    "MLI",
    "Africa",
    "Western Africa"
  ],
  [
    "MM",
    "MMR",
    "Asia",
    "South-eastern Asia"
  ],
  [
    "MN",
    "MNG",
    "Asia",
    "Eastern Asia"
  ],
  [
    "MO",
    "MAC",
    "Asia",
    "Eastern Asia"
  ],
  [
    "MP",
    "MNP",
    "Oceania",
    "Micronesia"
  ],
  [
    "MQ",
    "MTQ",
    "Americas",
    "Caribbean"
  ],
  [
    "MR",
    "MRT",
    "Africa",
    "Western Africa"
  ],
  [
    "MS",
    "MSR",
    "Americas",
    "Caribbean"
  ],
  [
    "MT",
    "MLT",
    "Europe",
    "Southern Europe"
  ],
  [
    "MU",
    "MUS",
    "Africa",
    "Eastern Africa"
  ],
  [
    "MV",
    "MDV",
    "Asia",
    "Southern Asia"
  ],
  [
    "MW",
    "MWI",
    "Africa",
    "Eastern Africa"
  ],
  [
    "MX",
    "MEX",
    "Americas",
    "Central America"
  ],
  [
    "MY",
    "MYS",
    "Asia",
    "South-eastern Asia"
  ],
  [
    "MZ",
    "MOZ",
    "Africa",
    "Eastern Africa"
  ],
  [
    "NA",
    "NAM",
    "Africa",
    "Southern Africa"
  ],
  [
    "NC",
    "NCL",
    "Oceania",
    "Melanesia"
  ],
  [
    "NE",
    "NER",
    "Africa",
    "Western Africa"
  ],
  [
    "NF",
    "NFK",
    "Oceania",
    "Australia and New Zealand"
  ],
  [
    "NG",
    "NGA",
    "Africa",
    "Western Africa"
  ],
  [
    "NI",
    "NIC",
    "Americas",
    "Central America"
  ],
  [
    "NL",
    "NLD",
    "Europe",
    "Western Europe"
  ],
  [
    "NO",
    "NOR",
    "Europe",
    "Northern Europe"
  ],
  [
    "NP",
    "NPL",
    "Asia",
    "Southern Asia"
  ],
  [
    "NR",
    "NRU",
    "Oceania",
    "Micronesia"
  ],
  [
    "NU",
    "NIU",
    "Oceania",
    "Polynesia"
  ],
  [
    "NZ",
    "NZL",
    "Oceania",
    "Australia and New Zealand"
  ],
  [
    "OM",
    "OMN",
    "Asia",
    "Western Asia"
  ],
  [
    "PA",
    "PAN",
    "Americas",
    "Central America"
  ],
  [
    "PE",
    "PER",
    "Americas",
    "South America"
  ],
  [
    "PF",
    "PYF",
    "Oceania",
    "Polynesia"
  ],
  [
    "PG",
    "PNG",
    "Oceania",
    "Melanesia"
  ],
  [
    "PH",
    "PHL",
    "Asia",
    "South-eastern Asia"
  ],
  [
    "PK",
    "PAK",
    "Asia",
    "Southern Asia"
  ],
  [
    "PL",
    "POL",
    "Europe",
    "Eastern Europe"
  ],
  [
    "PM",
    "SPM",
    "Americas",
    "Northern America"
  ],
  [
    "PN",
    "PCN",
    "Oceania",
    "Polynesia"
  ],
  [
    "PR",
    "PRI",
    "Americas",
    "Caribbean"
  ],
  [
    "PS",
    "PSE",
    "Asia",
    "Western Asia"
  ],
  [
    "PT",
    "PRT",
    "Europe",
    "Southern Europe"
  ],
  [
    "PW",
    "PLW",
    "Oceania",
    "Micronesia"
  ],
  [
    "PY",
    "PRY",
    "Americas",
    "South America"
  ],
  [
    "QA",
    "QAT",
    "Asia",
    "Western Asia"
  ],
  [
    "RE",
    "REU",
    "Africa",
    "Eastern Africa"
  ],
  [
    "RO",
    "ROU",
    "Europe",
    "Eastern Europe"
  ],
  [
    "RS",
    "SRB",
    "Europe",
    "Southern Europe"
  ],
  [
    "RU",
    "RUS",
    "Europe",
    "Eastern Europe"
  ],
  [
    "RW",
    "RWA",
    "Africa",
    "Eastern Africa"
  ],
  [
    "SA",
    "SAU",
    "Asia",
    "Western Asia"
  ],
  [
    "SB",
    "SLB",
    "Oceania",
    "Melanesia"
  ],
  [
    "SC",
    "SYC",
    "Africa",
    "Eastern Africa"
  ],
  [
    "SD",
    "SDN",
    "Africa",
    "Northern Africa"
  ],
  [
    "SE",
    "SWE",
    "Europe",
    "Northern Europe"
  ],
  [
    "SG",
    "SGP",
    "Asia",
    "South-eastern Asia"
  ],
  [
    "SH",
    "SHN",
    "Africa",
    "Western Africa"
  ],
  [
    "SI",
    "SVN",
    "Europe",
    "Southern Europe"
  ],
  [
    "SJ",
    "SJM",
    "Europe",
    "Northern Europe"
  ],
  [
    "SK",
    "SVK",
    "Europe",
    "Eastern Europe"
  ],
  [
    "SL",
    "SLE",
    "Africa",
    "Western Africa"
  ],
  [
    "SM",
    "SMR",
    "Europe",
    "Southern Europe"
  ],
  [
    "SN",
    "SEN",
    "Africa",
    "Western Africa"
  ],
  [
    "SO",
    "SOM",
    "Africa",
    "Eastern Africa"
  ],
  [
    "SR",
    "SUR",
    "Americas",
    "South America"
  ],
  [
    "SS",
    "SSD",
    "Africa",
    "Eastern Africa"
  ],
  [
    "ST",
    "STP",
    "Africa",
    "Middle Africa"
  ],
  [
    "SV",
    "SLV",
    "Americas",
    "Central America"
  ],
  [
    "SX",
    "SXM",
    "Americas",
    "Caribbean"
  ],
  [
    "SY",
    "SYR",
    "Asia",
    "Western Asia"
  ],
  [
    "SZ",
    "SWZ",
    "Africa",
    "Southern Africa"
  ],
  [
    "TC",
    "TCA",
    "Americas",
    "Caribbean"
  ],
  [
    "TD",
    "TCD",
    "Africa",
    "Middle Africa"
  ],
  [
    "TF",
    "ATF",
    "Africa",
    "Eastern Africa"
  ],
  [
    "TG",
    "TGO",
    "Africa",
    "Western Africa"
  ],
  [
    "TH",
    "THA",
    "Asia",
    "South-eastern Asia"
  ],
  [
    "TJ",
    "TJK",
    "Asia",
    "Central Asia"
  ],
  [
    "TK",
    "TKL",
    "Oceania",
    "Polynesia"
  ],
  [
    "TL",
    "TLS",
    "Asia",
    "South-eastern Asia"
  ],
  [
    "TM",
    "TKM",
    "Asia",
    "Central Asia"
  ],
  [
    "TN",
    "TUN",
    "Africa",
    "Northern Africa"
  ],
  [
    "TO",
    "TON",
    "Oceania",
    "Polynesia"
  ],
  [
    "TR",
    "TUR",
    "Asia",
    "Western Asia"
  ],
  [
    "TT",
    "TTO",
    "Americas",
    "Caribbean"
  ],
  [
    "TV",
    "TUV",
    "Oceania",
    "Polynesia"
  ],
  [
    "TZ",
    "TZA",
    "Africa",
    "Eastern Africa"
  ],
  [
    "UA",
    "UKR",
    "Europe",
    "Eastern Europe"
  ],
  [
    "UG",
    "UGA",
    "Africa",
    "Eastern Africa"
  ],
  [
    "UM",
    "UMI",
    "Oceania",
    "Micronesia"
  ],
  [
    "US",
    "USA",
    "Americas",
    "Northern America"
  ],
  [
    "UY",
    "URY",
    "Americas",
    "South America"
  ],
  [
    "UZ",
    "UZB",
    "Asia",
    "Central Asia"
  ],
  [
    "VA",
    "VAT",
    "Europe",
    "Southern Europe"
  ],
  [
    "VC",
    "VCT",
    "Americas",
    "Caribbean"
  ],
  [
    "VE",
    "VEN",
    "Americas",
    "South America"
  ],
  [
    "VG",
    "VGB",
    "Americas",
    "Caribbean"
  ],
  [
    "VI",
    "VIR",
    "Americas",
    "Caribbean"
  ],
  [
    "VN",
    "VNM",
    "Asia",
    "South-eastern Asia"
  ],
  [
    "VU",
    "VUT",
    "Oceania",
    "Melanesia"
  ],
  [
    "WF",
    "WLF",
    "Oceania",
    "Polynesia"
  ],
  [
    "WS",
    "WSM",
    "Oceania",
    "Polynesia"
  ],
  [
    "YE",
    "YEM",
    "Asia",
    "Western Asia"
  ],
  [
    "YT",
    "MYT",
    "Africa",
    "Eastern Africa"
  ],
  [
    "ZA",
    "ZAF",
    "Africa",
    "Southern Africa"
  ],
  [
    "ZM",
    "ZMB",
    "Africa",
    "Eastern Africa"
  ],
  [
    "ZW",
    "ZWE",
    "Africa",
    "Eastern Africa"
  ]
] as const
