import type { RoleFamily, RoleFamilyDefinition } from './types'

export const roleFamilies = [
  { key: 'genetics_breeding_ip', label: 'Genetics, breeding & IP', description: 'Cultivar, breeding, tissue-culture and IP commercialization pathways.', baselineModules: ['country_status', 'evidence_gap', 'cultivar_passport', 'ip_licensing', 'documents', 'counterparties'], primaryCta: 'create_cultivar_passport' },
  { key: 'cultivation_production', label: 'Cultivation & production', description: 'Licensed production, propagation, readiness and post-harvest operations.', baselineModules: ['country_status', 'evidence_gap', 'production_readiness', 'gacp_gmp_readiness', 'documents', 'counterparties'], primaryCta: 'check_production_readiness' },
  { key: 'processing_manufacturing', label: 'Processing & manufacturing', description: 'Extraction, manufacturing, formulation, packaging and batch-release operations.', baselineModules: ['country_status', 'evidence_gap', 'product_readiness_file', 'batch_release', 'documents', 'counterparties'], primaryCta: 'build_product_readiness_file' },
  { key: 'trade_distribution', label: 'Trade & distribution', description: 'Importer, exporter, distribution, broker and logistics corridor pathways.', baselineModules: ['country_status', 'evidence_gap', 'trade_corridor', 'customs_logistics', 'documents', 'counterparties'], primaryCta: 'assess_trade_corridor' },
  { key: 'buyers_procurement', label: 'Buyers & procurement', description: 'Demand-side sourcing, supplier review and procurement readiness.', baselineModules: ['country_status', 'evidence_gap', 'verified_suppliers', 'procurement_watchlist', 'documents', 'counterparties'], primaryCta: 'review_verified_suppliers' },
  { key: 'medical_clinical', label: 'Medical & clinical', description: 'Clinical education, access pathways and professional boundaries.', baselineModules: ['country_status', 'evidence_gap', 'clinical_pathway', 'patient_access', 'documents', 'counterparties'], primaryCta: 'open_clinical_pathway' },
  { key: 'pharmacy_dispensing', label: 'Pharmacy & dispensing', description: 'Dispensing controls, procurement and medication-safety pathways.', baselineModules: ['country_status', 'evidence_gap', 'pharmacy_checklist', 'dispensing_controls', 'documents', 'counterparties'], primaryCta: 'open_pharmacy_checklist' },
  { key: 'labs_qa_verification', label: 'Labs, QA & verification', description: 'Testing, COA, QP, audit and certification readiness.', baselineModules: ['country_status', 'evidence_gap', 'verification_services', 'coa_review', 'documents', 'counterparties'], primaryCta: 'offer_verification_services' },
  { key: 'research_academia_trials', label: 'Research, academia & trials', description: 'Research collaborations, trials, ethics and registries.', baselineModules: ['country_status', 'evidence_gap', 'research_collaboration', 'trial_readiness', 'documents', 'counterparties'], primaryCta: 'find_research_collaborations' },
  { key: 'regulators_policy_government', label: 'Regulators, policy & government', description: 'Evidence coverage, policy queue and public-sector review surfaces.', baselineModules: ['country_status', 'evidence_gap', 'evidence_coverage', 'policy_queue', 'documents', 'counterparties'], primaryCta: 'review_evidence_coverage' },
  { key: 'finance_investment_insurance', label: 'Finance, investment & insurance', description: 'Market readiness, diligence, risk and capital pathways.', baselineModules: ['country_status', 'evidence_gap', 'market_readiness', 'diligence_room', 'documents', 'counterparties'], primaryCta: 'assess_market_readiness' },
  { key: 'equipment_facilities_services', label: 'Equipment, facilities & services', description: 'Operator demand, equipment, facilities and service-provider routing.', baselineModules: ['country_status', 'evidence_gap', 'operator_demand', 'service_marketplace', 'documents', 'counterparties'], primaryCta: 'find_operator_demand' },
  { key: 'legal_compliance_professional', label: 'Legal, compliance & professional', description: 'Compliance demand, licensing and professional advisory routing.', baselineModules: ['country_status', 'evidence_gap', 'compliance_demand', 'licensing_tracker', 'documents', 'counterparties'], primaryCta: 'find_compliance_demand' },
  { key: 'data_intelligence_media', label: 'Data, intelligence & media', description: 'Market intelligence, methodology, publishing and data-provider surfaces.', baselineModules: ['country_status', 'evidence_gap', 'market_intelligence', 'source_methodology', 'documents', 'counterparties'], primaryCta: 'open_market_intelligence' },
  { key: 'harbourview_admin_operator', label: 'Harbourview admin & operator', description: 'Internal review queues, exposure review and source operations.', baselineModules: ['country_status', 'evidence_gap', 'review_queue', 'admin_exposure_review', 'documents', 'counterparties'], primaryCta: 'open_review_queue' },
] as const satisfies readonly RoleFamilyDefinition[]

export const roleFamilyMap = Object.fromEntries(roleFamilies.map((family) => [family.key, family])) as unknown as Record<RoleFamily, RoleFamilyDefinition>
