import type { CounterpartyType, DocumentType, EvidenceType, ModuleKey, RoleFamily, RoleProfile } from './types'
import { roleFamilyMap } from './role-families'

type Seed = readonly [string, string]

const roleSeeds: Record<RoleFamily, readonly Seed[]> = {
  genetics_breeding_ip: [
    ['breeder', 'Breeder'], ['geneticist', 'Geneticist'], ['cultivar_owner', 'Cultivar owner'], ['seed_company', 'Seed company'], ['tissue_culture_provider', 'Tissue-culture provider'], ['nursery_clone_provider', 'Nursery / clone provider'], ['licensing_agent', 'Licensing agent'], ['ip_manager', 'IP manager'], ['phenotype_evaluator', 'Phenotype evaluator'], ['genomics_lab', 'Genomics lab'], ['trial_coordinator', 'Trial coordinator'], ['research_breeder', 'Research breeder'], ['legacy_genetics_holder', 'Legacy genetics holder'], ['commercialization_partner', 'Commercialization partner'],
  ],
  cultivation_production: [
    ['licensed_cultivator', 'Licensed cultivator'], ['licensed_producer', 'Licensed producer'], ['greenhouse_producer', 'Greenhouse producer'], ['indoor_producer', 'Indoor producer'], ['outdoor_producer', 'Outdoor producer'], ['micro_producer', 'Micro producer'], ['craft_producer', 'Craft producer'], ['medical_producer', 'Medical producer'], ['eu_gmp_producer', 'EU-GMP producer'], ['gacp_producer', 'GACP producer'], ['propagation_facility', 'Propagation facility'], ['nursery_facility', 'Nursery facility'], ['contract_grower', 'Contract grower'], ['master_grower', 'Master grower'], ['production_manager', 'Production manager'], ['post_harvest_manager', 'Post-harvest manager'], ['agronomy_advisor', 'Agronomy advisor'],
  ],
  processing_manufacturing: [
    ['processor', 'Processor'], ['extractor', 'Extractor'], ['manufacturer', 'Manufacturer'], ['white_label_manufacturer', 'White-label manufacturer'], ['contract_manufacturer', 'Contract manufacturer'], ['product_developer', 'Product developer'], ['formulation_scientist', 'Formulation scientist'], ['edible_manufacturer', 'Edible manufacturer'], ['beverage_manufacturer', 'Beverage manufacturer'], ['oil_manufacturer', 'Oil manufacturer'], ['extract_manufacturer', 'Extract manufacturer'], ['pre_roll_manufacturer', 'Pre-roll manufacturer'], ['packaging_operator', 'Packaging operator'], ['quality_manager', 'Quality manager'], ['batch_release_manager', 'Batch-release manager'], ['product_registration_manager', 'Product-registration manager'],
  ],
  trade_distribution: [
    ['exporter', 'Exporter'], ['importer', 'Importer'], ['distributor', 'Distributor'], ['wholesaler', 'Wholesaler'], ['trade_broker', 'Trade broker'], ['customs_broker', 'Customs broker'], ['freight_provider', 'Freight provider'], ['logistics_provider', 'Logistics provider'], ['cold_chain_provider', 'Cold-chain provider'], ['licensed_importer', 'Licensed importer'], ['licensed_exporter', 'Licensed exporter'], ['eu_gmp_exporter', 'EU-GMP exporter'], ['domestic_distributor', 'Domestic distributor'], ['regional_distributor', 'Regional distributor'], ['pharmaceutical_distributor', 'Pharmaceutical distributor'], ['medical_distributor', 'Medical distributor'],
  ],
  buyers_procurement: [
    ['licensed_buyer', 'Licensed buyer'], ['procurement_buyer', 'Procurement buyer'], ['retail_buyer', 'Retail buyer'], ['medical_buyer', 'Medical buyer'], ['pharmacy_buyer', 'Pharmacy buyer'], ['hospital_buyer', 'Hospital buyer'], ['clinic_buyer', 'Clinic buyer'], ['distributor_buyer', 'Distributor buyer'], ['government_buyer', 'Government buyer'], ['wholesale_buyer', 'Wholesale buyer'], ['private_label_buyer', 'Private-label buyer'], ['brand_buyer', 'Brand buyer'], ['multi_site_operator', 'Multi-site operator'], ['purchasing_cooperative', 'Purchasing cooperative'], ['category_manager', 'Category manager'], ['sourcing_manager', 'Sourcing manager'],
  ],
  medical_clinical: [
    ['doctor', 'Doctor'], ['specialist_physician', 'Specialist physician'], ['pain_physician', 'Pain physician'], ['oncology_physician', 'Oncology physician'], ['psychiatry_physician', 'Psychiatry physician'], ['neurology_physician', 'Neurology physician'], ['palliative_physician', 'Palliative physician'], ['family_physician', 'Family physician'], ['nurse_practitioner', 'Nurse practitioner'], ['physician_assistant', 'Physician assistant'], ['clinic_director', 'Clinic director'], ['medical_director', 'Medical director'], ['cannabis_clinic_operator', 'Cannabis clinic operator'], ['patient_educator', 'Patient educator'], ['clinical_educator', 'Clinical educator'], ['care_coordinator', 'Care coordinator'], ['patient_access_manager', 'Patient-access manager'], ['telemedicine_provider', 'Telemedicine provider'], ['hospital_administrator', 'Hospital administrator'],
  ],
  pharmacy_dispensing: [
    ['pharmacist', 'Pharmacist'], ['pharmacy_owner', 'Pharmacy owner'], ['pharmacy_chain_operator', 'Pharmacy chain operator'], ['hospital_pharmacist', 'Hospital pharmacist'], ['compounding_pharmacist', 'Compounding pharmacist'], ['dispensary_pharmacist', 'Dispensary pharmacist'], ['pharmacy_procurement_officer', 'Pharmacy procurement officer'], ['pharmacy_compliance_officer', 'Pharmacy compliance officer'], ['dispensing_manager', 'Dispensing manager'], ['patient_counselling_pharmacist', 'Patient-counselling pharmacist'], ['medication_safety_officer', 'Medication-safety officer'], ['pharmacy_wholesaler', 'Pharmacy wholesaler'],
  ],
  labs_qa_verification: [
    ['cannabis_lab', 'Cannabis lab'], ['analytical_lab', 'Analytical lab'], ['microbiology_lab', 'Microbiology lab'], ['genomics_testing_lab', 'Genomics testing lab'], ['stability_lab', 'Stability lab'], ['qa_provider', 'QA provider'], ['qc_manager', 'QC manager'], ['qualified_person', 'Qualified person'], ['batch_release_specialist', 'Batch-release specialist'], ['compliance_testing_provider', 'Compliance testing provider'], ['coa_reviewer', 'COA reviewer'], ['audit_provider', 'Audit provider'], ['certification_body', 'Certification body'], ['inspection_provider', 'Inspection provider'], ['gmp_consultant', 'GMP consultant'], ['gacp_consultant', 'GACP consultant'],
  ],
  research_academia_trials: [
    ['university_researcher', 'University researcher'], ['clinical_researcher', 'Clinical researcher'], ['agricultural_researcher', 'Agricultural researcher'], ['pharmacology_researcher', 'Pharmacology researcher'], ['public_health_researcher', 'Public-health researcher'], ['trial_sponsor', 'Trial sponsor'], ['trial_site', 'Trial site'], ['ethics_board_coordinator', 'Ethics-board coordinator'], ['research_institution', 'Research institution'], ['principal_investigator', 'Principal investigator'], ['data_scientist', 'Data scientist'], ['epidemiologist', 'Epidemiologist'], ['patient_registry_operator', 'Patient registry operator'], ['cultivar_trial_coordinator', 'Cultivar trial coordinator'], ['observational_study_operator', 'Observational study operator'], ['institutional_collaboration_lead', 'Institutional collaboration lead'],
  ],
  regulators_policy_government: [
    ['regulator', 'Regulator'], ['policy_analyst', 'Policy analyst'], ['health_ministry_official', 'Health ministry official'], ['agriculture_ministry_official', 'Agriculture ministry official'], ['economic_development_officer', 'Economic development officer'], ['trade_commissioner', 'Trade commissioner'], ['customs_authority', 'Customs authority'], ['public_health_official', 'Public-health official'], ['procurement_official', 'Procurement official'], ['municipal_official', 'Municipal official'], ['cannabis_authority', 'Cannabis authority'], ['licensing_authority', 'Licensing authority'], ['inspection_authority', 'Inspection authority'], ['standards_body', 'Standards body'], ['government_researcher', 'Government researcher'],
  ],
  finance_investment_insurance: [
    ['investor', 'Investor'], ['strategic_acquirer', 'Strategic acquirer'], ['pe_analyst', 'PE analyst'], ['vc_analyst', 'VC analyst'], ['lender', 'Lender'], ['banker', 'Banker'], ['insurer', 'Insurer'], ['broker', 'Broker'], ['underwriter', 'Underwriter'], ['risk_analyst', 'Risk analyst'], ['credit_analyst', 'Credit analyst'], ['ma_advisor', 'M&A advisor'], ['diligence_advisor', 'Diligence advisor'], ['family_office', 'Family office'], ['real_estate_investor', 'Real-estate investor'], ['distressed_asset_buyer', 'Distressed-asset buyer'],
  ],
  equipment_facilities_services: [
    ['equipment_seller', 'Equipment seller'], ['used_equipment_seller', 'Used-equipment seller'], ['distressed_equipment_seller', 'Distressed-equipment seller'], ['facility_designer', 'Facility designer'], ['greenhouse_builder', 'Greenhouse builder'], ['hvac_provider', 'HVAC provider'], ['lighting_provider', 'Lighting provider'], ['irrigation_provider', 'Irrigation provider'], ['security_provider', 'Security provider'], ['packaging_equipment_provider', 'Packaging equipment provider'], ['extraction_equipment_provider', 'Extraction equipment provider'], ['lab_equipment_provider', 'Lab-equipment provider'], ['software_provider', 'Software provider'], ['erp_provider', 'ERP provider'], ['track_and_trace_provider', 'Track-and-trace provider'], ['consultant', 'Consultant'], ['recruiter', 'Recruiter'], ['trainer', 'Trainer'], ['maintenance_provider', 'Maintenance provider'], ['real_estate_provider', 'Real-estate provider'], ['construction_contractor', 'Construction contractor'],
  ],
  legal_compliance_professional: [
    ['cannabis_lawyer', 'Cannabis lawyer'], ['regulatory_lawyer', 'Regulatory lawyer'], ['licensing_lawyer', 'Licensing lawyer'], ['corporate_lawyer', 'Corporate lawyer'], ['ip_lawyer', 'IP lawyer'], ['trade_lawyer', 'Trade lawyer'], ['cannabis_consultant', 'Cannabis consultant'], ['regulatory_consultant', 'Regulatory consultant'], ['licensing_consultant', 'Licensing consultant'], ['compliance_officer', 'Compliance officer'], ['tax_advisor', 'Tax advisor'], ['accountant', 'Accountant'], ['auditor', 'Auditor'], ['security_consultant', 'Security consultant'], ['aml_kyc_provider', 'AML/KYC provider'], ['insurance_broker', 'Insurance broker'], ['hr_consultant', 'HR consultant'], ['recall_consultant', 'Recall consultant'], ['quality_consultant', 'Quality consultant'], ['privacy_consultant', 'Privacy consultant'], ['data_protection_consultant', 'Data-protection consultant'],
  ],
  data_intelligence_media: [
    ['market_analyst', 'Market analyst'], ['commercial_analyst', 'Commercial analyst'], ['trade_analyst', 'Trade analyst'], ['competitive_analyst', 'Competitive analyst'], ['pricing_analyst', 'Pricing analyst'], ['supply_demand_analyst', 'Supply-demand analyst'], ['policy_analyst_data', 'Policy analyst'], ['forecasting_analyst', 'Forecasting analyst'], ['data_provider', 'Data provider'], ['research_publisher', 'Research publisher'], ['industry_media', 'Industry media'], ['journalist', 'Journalist'], ['benchmarking_provider', 'Benchmarking provider'], ['database_provider', 'Database provider'],
  ],
  harbourview_admin_operator: [
    ['harbourview_admin', 'Harbourview admin'], ['evidence_reviewer', 'Evidence reviewer'], ['source_reviewer', 'Source reviewer'], ['claim_reviewer', 'Claim reviewer'], ['counterparty_reviewer', 'Counterparty reviewer'], ['cultivar_reviewer', 'Cultivar reviewer'], ['coa_reviewer_admin', 'COA reviewer'], ['supplier_reviewer', 'Supplier reviewer'], ['marketplace_moderator', 'Marketplace moderator'], ['jurisdiction_data_editor', 'Jurisdiction data editor'], ['role_profile_editor', 'Role profile editor'], ['public_private_exposure_reviewer', 'Public/private exposure reviewer'], ['audit_log_reviewer', 'Audit-log reviewer'], ['ingestion_operator', 'Ingestion operator'], ['support_operator', 'Support operator'], ['sales_operator', 'Sales operator'],
  ],
}

const familyCopy: Record<RoleFamily, { question: string; priority: string; modules: ModuleKey[]; documents: DocumentType[]; counterparties: CounterpartyType[]; evidence: EvidenceType[]; empty: string; language: string }> = {
  genetics_breeding_ip: { question: 'Can this genetics/IP pathway be evidenced, protected, and responsibly commercialized in this market?', priority: 'Protect provenance before introducing genetics to counterparties.', modules: ['cultivar_passport', 'ip_licensing'], documents: ['cultivar_passport', 'ip_licence'], counterparties: ['breeder', 'lab', 'lawyer_consultant'], evidence: ['ip_chain_of_title', 'country_law', 'licence_registry'], empty: 'No verified cultivar, IP, or genetics commercialization record has been published for this country-role pathway.', language: 'genetics/IP readiness' },
  cultivation_production: { question: 'What evidence is required before production capacity can be treated as market-ready?', priority: 'Sequence licence, production and quality readiness before buyer routing.', modules: ['production_readiness', 'gacp_gmp_readiness'], documents: ['production_readiness_file', 'gacp_file', 'gmp_file'], counterparties: ['cultivator', 'buyer', 'lab'], evidence: ['licence_registry', 'gacp_certificate', 'gmp_certificate'], empty: 'No verified production readiness evidence has been published for this country-role pathway.', language: 'production readiness' },
  processing_manufacturing: { question: 'What file proves this product or batch can move through a regulated channel?', priority: 'Assemble product, quality and release evidence before commercial claims.', modules: ['product_readiness_file', 'batch_release'], documents: ['product_readiness_file', 'batch_release_file', 'coa'], counterparties: ['manufacturer', 'lab', 'distributor'], evidence: ['coa', 'gmp_certificate', 'regulatory_guidance'], empty: 'No verified product readiness file has been published for this country-role pathway.', language: 'manufacturing readiness' },
  trade_distribution: { question: 'Is this corridor evidenced enough for import/export or distribution review?', priority: 'Validate corridor, permits and logistics constraints before introductions.', modules: ['trade_corridor', 'customs_logistics'], documents: ['import_permit', 'export_permit', 'supplier_packet'], counterparties: ['exporter', 'importer', 'distributor'], evidence: ['import_export_permit', 'regulatory_guidance', 'supplier_verification'], empty: 'No verified trade corridor record has been published for this country-role pathway.', language: 'trade corridor readiness' },
  buyers_procurement: { question: 'Which verified supply options and documents should this buyer review first?', priority: 'Keep buyer workflow supplier-first and evidence-gated.', modules: ['verified_suppliers', 'procurement_watchlist'], documents: ['supplier_packet', 'coa', 'gmp_file'], counterparties: ['buyer', 'supplier', 'distributor'], evidence: ['supplier_verification', 'coa', 'gmp_certificate'], empty: 'No verified supplier shortlist has been published for this country-role pathway.', language: 'procurement readiness' },
  medical_clinical: { question: 'What is the safe clinical education and access pathway for this professional role?', priority: 'Keep clinical surfaces education-first and claim-safe.', modules: ['clinical_pathway', 'patient_access'], documents: ['clinical_protocol', 'policy_brief'], counterparties: ['doctor', 'clinic', 'pharmacy'], evidence: ['clinical_guidance', 'country_law', 'regulatory_guidance'], empty: 'No verified clinical pathway has been published for this country-role pathway.', language: 'clinical pathway education' },
  pharmacy_dispensing: { question: 'What dispensing, procurement and safety controls must the pharmacy verify first?', priority: 'Keep pharmacy workflow dispensing-first and medication-safety gated.', modules: ['pharmacy_checklist', 'dispensing_controls'], documents: ['pharmacy_sop', 'supplier_packet', 'coa'], counterparties: ['pharmacy', 'distributor', 'doctor'], evidence: ['regulatory_guidance', 'coa', 'supplier_verification'], empty: 'No verified pharmacy dispensing checklist has been published for this country-role pathway.', language: 'pharmacy dispensing readiness' },
  labs_qa_verification: { question: 'What verification service, scope or COA evidence is needed for confidence?', priority: 'Separate public verification status from private COA review internals.', modules: ['verification_services', 'coa_review'], documents: ['lab_scope', 'coa', 'batch_release_file'], counterparties: ['lab', 'manufacturer', 'cultivator'], evidence: ['coa', 'gmp_certificate', 'admin_review'], empty: 'No verified lab, QA, or COA pathway has been published for this country-role pathway.', language: 'verification readiness' },
  research_academia_trials: { question: 'Which collaboration or study pathway can be evidenced without overstating findings?', priority: 'Make research routing protocol-first and evidence-bound.', modules: ['research_collaboration', 'trial_readiness'], documents: ['trial_protocol', 'clinical_protocol'], counterparties: ['research_institution', 'doctor', 'regulator'], evidence: ['clinical_guidance', 'regulatory_guidance', 'admin_review'], empty: 'No verified research collaboration pathway has been published for this country-role pathway.', language: 'research collaboration readiness' },
  regulators_policy_government: { question: 'Where does Harbourview have sufficient evidence coverage for policy review?', priority: 'Make public-sector surfaces evidence-coverage-first.', modules: ['evidence_coverage', 'policy_queue'], documents: ['policy_brief', 'admin_review_packet'], counterparties: ['regulator', 'research_institution', 'data_provider'], evidence: ['country_law', 'regulatory_guidance', 'admin_review'], empty: 'No verified government or policy evidence map has been published for this country-role pathway.', language: 'policy evidence coverage' },
  finance_investment_insurance: { question: 'Is the market ready enough for diligence, credit, insurance or investment review?', priority: 'Separate investability signals from private deal and counterparty data.', modules: ['market_readiness', 'diligence_room'], documents: ['diligence_memo', 'market_report'], counterparties: ['investor', 'service_provider', 'lawyer_consultant'], evidence: ['market_signal', 'licence_registry', 'admin_review'], empty: 'No verified market readiness dossier has been published for this country-role pathway.', language: 'diligence readiness' },
  equipment_facilities_services: { question: 'Where is verified operator demand for this equipment, facility or service category?', priority: 'Route services from operator demand, not unsupported market claims.', modules: ['operator_demand', 'service_marketplace'], documents: ['service_capability_statement', 'market_report'], counterparties: ['service_provider', 'cultivator', 'manufacturer'], evidence: ['market_signal', 'supplier_verification', 'admin_review'], empty: 'No verified operator demand record has been published for this country-role pathway.', language: 'operator demand' },
  legal_compliance_professional: { question: 'Which compliance demand and licensing constraints should this professional review first?', priority: 'Keep advisory routing compliance-first and jurisdiction-specific.', modules: ['compliance_demand', 'licensing_tracker'], documents: ['legal_memo', 'policy_brief'], counterparties: ['lawyer_consultant', 'regulator', 'service_provider'], evidence: ['country_law', 'regulatory_guidance', 'admin_review'], empty: 'No verified compliance demand record has been published for this country-role pathway.', language: 'compliance demand' },
  data_intelligence_media: { question: 'What can be published or analyzed with transparent source methodology?', priority: 'Make intelligence surfaces methodology-first and avoid unsupported metrics.', modules: ['market_intelligence', 'source_methodology'], documents: ['market_report', 'policy_brief'], counterparties: ['data_provider', 'research_institution', 'regulator'], evidence: ['market_signal', 'country_law', 'regulatory_guidance'], empty: 'No verified intelligence coverage has been published for this country-role pathway.', language: 'market intelligence' },
  harbourview_admin_operator: { question: 'Which review queue, exposure flag, or source gap should Harbourview resolve next?', priority: 'Expose admin-only workflow only through admin DTO allowlists.', modules: ['review_queue', 'admin_exposure_review'], documents: ['admin_review_packet', 'policy_brief'], counterparties: ['harbourview_reviewer', 'data_provider', 'regulator'], evidence: ['admin_review', 'country_law', 'regulatory_guidance'], empty: 'No admin review packet has been initialized for this country-role pathway.', language: 'admin operations' },
}

function toProfile(family: RoleFamily, [slug, label]: Seed): RoleProfile {
  const copy = familyCopy[family]
  const key = slug
  const blockedModules: ModuleKey[] = family === 'medical_clinical' ? ['verified_suppliers', 'cultivar_passport'] : family === 'pharmacy_dispensing' ? ['cultivar_passport', 'ip_licensing'] : family === 'genetics_breeding_ip' ? ['clinical_pathway', 'pharmacy_checklist'] : []
  return {
    key,
    slug,
    label,
    shortLabel: label,
    family,
    aliases: [label.toLowerCase(), slug.replace(/_/g, ' ')],
    operatingQuestion: copy.question,
    priority: copy.priority,
    primaryCta: roleFamilyMap[family].primaryCta,
    language: copy.language,
    roleModules: copy.modules,
    blockedModules,
    documentTypes: copy.documents,
    counterpartyTypes: copy.counterparties,
    evidenceRequirements: copy.evidence,
    emptyState: copy.empty,
  }
}

export const roleProfiles = Object.entries(roleSeeds).flatMap(([family, seeds]) => seeds.map((seed) => toProfile(family as RoleFamily, seed)))
export const roleProfileMap = Object.fromEntries(roleProfiles.map((role) => [role.slug, role])) as Record<string, RoleProfile>
export const allRoleSlugs = roleProfiles.map((role) => role.slug)
export const seededRoleFamilyUniverse = Object.keys(roleSeeds) as RoleFamily[]
