import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { buildMarketEntryPlan } from '@/lib/market-entry-os'
import type { MarketEntryInput } from '@/lib/market-entry-os/types'
export const dynamic='force-dynamic'
export const runtime='nodejs'
function isInput(v:unknown):v is MarketEntryInput { if(!v||typeof v!=='object')return false; const i=v as Record<string,unknown>; return typeof i.originIso2==='string'&&typeof i.destinationIso2==='string'&&typeof i.productClass==='string' }
export async function GET(){const s=await createClient();const{data:{user},error:a}=await s.auth.getUser();if(a||!user)return NextResponse.json({error:'Authentication required'},{status:401});const{data,error}=await s.from('market_entry_missions').select('id,origin_iso2,destination_iso2,product_class,status,plan_version,reproducibility_key,payment_status,report_status,created_at,updated_at').order('created_at',{ascending:false}).limit(50);if(error)return NextResponse.json({error:'Mission workspace is unavailable.'},{status:503});return NextResponse.json({missions:data??[]})}
export async function POST(request:NextRequest){const s=await createClient();const{data:{user},error:a}=await s.auth.getUser();if(a||!user)return NextResponse.json({error:'Authentication required'},{status:401});let body:unknown;try{body=await request.json()}catch{return NextResponse.json({error:'Request body must be valid JSON.'},{status:400})}if(!isInput(body))return NextResponse.json({error:'originIso2, destinationIso2, and productClass are required.'},{status:400});const plan=await buildMarketEntryPlan(body);if(!plan)return NextResponse.json({error:'Invalid or unsupported market-entry corridor input.'},{status:400});const{data:mission,error}=await s.from('market_entry_missions').insert({owner_user_id:user.id,origin_iso2:plan.input.originIso2,destination_iso2:plan.input.destinationIso2,product_class:plan.input.productClass,status:plan.status,plan_version:plan.planVersion,plan_snapshot:plan,evidence_snapshot:plan.evidence,reproducibility_key:plan.reproducibilityKey}).select('id,origin_iso2,destination_iso2,product_class,status,plan_version,reproducibility_key,payment_status,report_status,created_at,updated_at').single();if(error||!mission)return NextResponse.json({error:'Unable to persist the mission workspace.'},{status:503});const taskRows=plan.execution.tasks.map(t=>({mission_id:mission.id,task_key:t.id,title:t.title,description:t.description,side:t.side,status:t.status,prerequisite_task_keys:t.prerequisiteIds,estimated_weeks:t.estimatedWeeks,evidence_ids:t.evidenceIds}));if(taskRows.length){const{error:e}=await s.from('market_entry_tasks').insert(taskRows);if(e){await s.from('market_entry_missions').delete().eq('id',mission.id);return NextResponse.json({error:'Unable to persist mission tasks.'},{status:503})}}const{error:eventError}=await s.from('market_entry_events').insert({mission_id:mission.id,actor_user_id:user.id,event_type:'mission_created',to_status:plan.status,payload:{planVersion:plan.planVersion,reproducibilityKey:plan.reproducibilityKey}});if(eventError){await s.from('market_entry_missions').delete().eq('id',mission.id);return NextResponse.json({error:'Unable to record the mission audit event.'},{status:503})}return NextResponse.json({mission,plan},{status:201})}
