import type {
  EcosystemVertical,
  OperatorWorkflowItem,
  EnterpriseDealRoom,
  IntroPacket,
  DocumentReadinessPacket,
  EnterpriseDashboardMetric,
  StrategicIntegrationPlaceholder,
  ReputationRecord,
  DataFlywheelEvent,
  CommercialCoordinationWorkflow,
} from './types'

export const ecosystemVerticals: EcosystemVertical[] = [
  {
    id: 'ev-001',
    name: 'EU Licensed Producers Network',
    vertical_type: 'licensed_producer',
    record_count: 142,
    markets_covered: ['DE', 'PT', 'NL', 'CZ', 'PL'],
    categories_covered: ['cannabis_inventory', 'eu_gmp'],
    high_value_count: 38,
    status: 'active',
  },
  {
    id: 'ev-002',
    name: 'UK Import Partners',
    vertical_type: 'importer',
    record_count: 47,
    markets_covered: ['UK'],
    categories_covered: ['importers', 'cannabis_inventory'],
    high_value_count: 12,
    status: 'active',
  },
  {
    id: 'ev-003',
    name: 'Canadian Exporters',
    vertical_type: 'licensed_producer',
    record_count: 89,
    markets_covered: ['CA'],
    categories_covered: ['cannabis_inventory', 'eu_gmp', 'market_access'],
    high_value_count: 24,
    status: 'active',
  },
  {
    id: 'ev-004',
    name: 'EU GMP Consultants',
    vertical_type: 'gmp_consultant',
    record_count: 31,
    markets_covered: ['DE', 'NL', 'PT'],
    categories_covered: ['eu_gmp', 'services'],
    high_value_count: 9,
    status: 'active',
  },
  {
    id: 'ev-005',
    name: 'Australian Distributors',
    vertical_type: 'distributor',
    record_count: 28,
    markets_covered: ['AU'],
    categories_covered: ['distributors', 'cannabis_inventory'],
    high_value_count: 7,
    status: 'building',
  },
  {
    id: 'ev-006',
    name: 'Packaging Suppliers — Europe',
    vertical_type: 'packaging_supplier',
    record_count: 54,
    markets_covered: ['DE', 'NL', 'CZ', 'PL'],
    categories_covered: ['packaging'],
    high_value_count: 14,
    status: 'active',
  },
  {
    id: 'ev-007',
    name: 'Cannabis Testing Labs',
    vertical_type: 'lab',
    record_count: 63,
    markets_covered: ['DE', 'UK', 'NL', 'CA', 'AU'],
    categories_covered: ['services', 'eu_gmp'],
    high_value_count: 19,
    status: 'active',
  },
  {
    id: 'ev-008',
    name: 'LATAM Producers',
    vertical_type: 'licensed_producer',
    record_count: 22,
    markets_covered: ['LATAM'],
    categories_covered: ['cannabis_inventory', 'market_access'],
    high_value_count: 5,
    status: 'building',
  },
  {
    id: 'ev-009',
    name: 'QA & Compliance Specialists',
    vertical_type: 'qa_compliance',
    record_count: 18,
    markets_covered: ['DE', 'UK', 'PT'],
    categories_covered: ['services', 'eu_gmp'],
    high_value_count: 6,
    status: 'building',
  },
  {
    id: 'ev-010',
    name: 'Equipment Vendors — Extraction',
    vertical_type: 'equipment_vendor',
    record_count: 41,
    markets_covered: ['DE', 'NL', 'CA'],
    categories_covered: ['equipment'],
    high_value_count: 11,
    status: 'active',
  },
  {
    id: 'ev-011',
    name: 'Legal & Compliance Advisors',
    vertical_type: 'legal_compliance',
    record_count: 27,
    markets_covered: ['DE', 'UK', 'AU', 'CA'],
    categories_covered: ['services'],
    high_value_count: 8,
    status: 'active',
  },
  {
    id: 'ev-012',
    name: 'Logistics Partners — Cold Chain',
    vertical_type: 'logistics',
    record_count: 19,
    markets_covered: ['DE', 'NL', 'UK'],
    categories_covered: ['services'],
    high_value_count: 4,
    status: 'building',
  },
  {
    id: 'ev-013',
    name: 'Market Access Partners — APAC',
    vertical_type: 'market_access_partner',
    record_count: 14,
    markets_covered: ['AU'],
    categories_covered: ['market_access'],
    high_value_count: 3,
    status: 'underbuilt',
  },
  {
    id: 'ev-014',
    name: 'M&A Distressed Asset Advisors',
    vertical_type: 'ma_distressed',
    record_count: 9,
    markets_covered: ['CA', 'DE'],
    categories_covered: ['services', 'market_access'],
    high_value_count: 4,
    status: 'building',
  },
  {
    id: 'ev-015',
    name: 'White Label Producers',
    vertical_type: 'white_label',
    record_count: 33,
    markets_covered: ['PT', 'NL', 'CZ'],
    categories_covered: ['cannabis_inventory'],
    high_value_count: 10,
    status: 'active',
  },
  {
    id: 'ev-016',
    name: 'Insurance Providers — Cannabis',
    vertical_type: 'insurance',
    record_count: 8,
    markets_covered: ['UK', 'CA', 'AU'],
    categories_covered: ['services'],
    high_value_count: 2,
    status: 'underbuilt',
  },
  {
    id: 'ev-017',
    name: 'Cannabis Financiers',
    vertical_type: 'financier',
    record_count: 11,
    markets_covered: ['CA', 'UK'],
    categories_covered: ['services'],
    high_value_count: 5,
    status: 'building',
  },
  {
    id: 'ev-018',
    name: 'Route-to-Market Specialists',
    vertical_type: 'route_to_market',
    record_count: 16,
    markets_covered: ['DE', 'UK', 'AU', 'PL'],
    categories_covered: ['market_access', 'distributors'],
    high_value_count: 6,
    status: 'building',
  },
]

export const operatorWorkflowItems: OperatorWorkflowItem[] = [
  {
    id: 'ow-001',
    title: 'Review DE licensed producer supply package',
    owner: 'sarah.b',
    status: 'my_queue',
    priority: 'high',
    market: 'DE',
    category: 'cannabis_inventory',
    due_date: '2026-06-22',
    created_at: '2026-06-17T09:00:00Z',
    notes: 'EU GMP cert expires Q3 — verify renewal status',
  },
  {
    id: 'ow-002',
    title: 'Prepare intro packet for UK importer',
    owner: 'james.k',
    status: 'review',
    priority: 'high',
    market: 'UK',
    category: 'importers',
    due_date: '2026-06-20',
    created_at: '2026-06-16T11:30:00Z',
    notes: 'Counterparty confirmed availability',
  },
  {
    id: 'ow-003',
    title: 'Follow up — AU distributor non-responsive',
    owner: 'sarah.b',
    status: 'follow_up',
    priority: 'medium',
    market: 'AU',
    category: 'distributors',
    due_date: '2026-06-21',
    created_at: '2026-06-14T08:00:00Z',
    notes: 'Second follow-up — escalate if no response',
  },
  {
    id: 'ow-004',
    title: 'Approve document readiness for PT exporter',
    owner: 'alex.m',
    status: 'approval',
    priority: 'high',
    market: 'PT',
    category: 'eu_gmp',
    due_date: '2026-06-19',
    created_at: '2026-06-15T14:00:00Z',
    notes: 'CoA and EU GMP cert both uploaded',
  },
  {
    id: 'ow-005',
    title: 'Coordinate NL packaging supplier review',
    owner: 'james.k',
    status: 'team_queue',
    priority: 'medium',
    market: 'NL',
    category: 'packaging',
    due_date: '2026-06-25',
    created_at: '2026-06-18T10:00:00Z',
    notes: 'New supplier onboarding — needs full review',
  },
  {
    id: 'ow-006',
    title: 'Handoff CA producer to intro packet stage',
    owner: 'alex.m',
    status: 'handoff',
    priority: 'high',
    market: 'CA',
    category: 'cannabis_inventory',
    due_date: '2026-06-20',
    created_at: '2026-06-17T16:00:00Z',
    notes: 'DE buyer confirmed — ready for formal intro',
  },
  {
    id: 'ow-007',
    title: 'Review PL distributor compliance docs',
    owner: 'sarah.b',
    status: 'review',
    priority: 'medium',
    market: 'PL',
    category: 'distributors',
    due_date: '2026-06-23',
    created_at: '2026-06-16T09:30:00Z',
    notes: 'Import licence and distribution agreement required',
  },
  {
    id: 'ow-008',
    title: 'Update CZ equipment surplus deal room',
    owner: 'james.k',
    status: 'my_queue',
    priority: 'low',
    market: 'CZ',
    category: 'equipment',
    due_date: null,
    created_at: '2026-06-15T12:00:00Z',
    notes: 'Buyer list needs refreshing',
  },
  {
    id: 'ow-009',
    title: 'LATAM supply — match to EU buyers',
    owner: 'alex.m',
    status: 'team_queue',
    priority: 'high',
    market: 'LATAM',
    category: 'cannabis_inventory',
    due_date: '2026-06-24',
    created_at: '2026-06-18T08:30:00Z',
    notes: 'GACP certified — strong fit for DE market',
  },
  {
    id: 'ow-010',
    title: 'DE market access pathway review',
    owner: 'sarah.b',
    status: 'my_queue',
    priority: 'high',
    market: 'DE',
    category: 'market_access',
    due_date: '2026-06-21',
    created_at: '2026-06-17T11:00:00Z',
    notes: 'Lauer-Taxe listing strategy review needed',
  },
  {
    id: 'ow-011',
    title: 'UK buyer requirement documentation review',
    owner: 'james.k',
    status: 'review',
    priority: 'medium',
    market: 'UK',
    category: 'buyer_requirement',
    due_date: '2026-06-22',
    created_at: '2026-06-16T14:00:00Z',
    notes: 'MHRA import requirements checklist outstanding',
  },
  {
    id: 'ow-012',
    title: 'Stale deal reactivation — NL buyer',
    owner: 'alex.m',
    status: 'follow_up',
    priority: 'medium',
    market: 'NL',
    category: 'cannabis_inventory',
    due_date: '2026-06-26',
    created_at: '2026-06-10T09:00:00Z',
    notes: 'Deal went cold 3 weeks ago — new supply match available',
  },
  {
    id: 'ow-013',
    title: 'AU GMP consultant onboarding',
    owner: 'sarah.b',
    status: 'approval',
    priority: 'low',
    market: 'AU',
    category: 'services',
    due_date: '2026-06-28',
    created_at: '2026-06-18T15:00:00Z',
    notes: 'Profile complete — pending final approval',
  },
  {
    id: 'ow-014',
    title: 'DE buyer — spec sheet request fulfilled',
    owner: 'james.k',
    status: 'handoff',
    priority: 'high',
    market: 'DE',
    category: 'cannabis_inventory',
    due_date: '2026-06-19',
    created_at: '2026-06-18T10:30:00Z',
    notes: 'Spec sheets sent — awaiting buyer confirmation',
  },
  {
    id: 'ow-015',
    title: 'PL packaging supplier compliance check',
    owner: 'alex.m',
    status: 'team_queue',
    priority: 'medium',
    market: 'PL',
    category: 'packaging',
    due_date: '2026-06-27',
    created_at: '2026-06-17T13:00:00Z',
    notes: 'EU regulation compliance review',
  },
  {
    id: 'ow-016',
    title: 'CA M&A distressed asset — initial review',
    owner: 'sarah.b',
    status: 'my_queue',
    priority: 'high',
    market: 'CA',
    category: 'services',
    due_date: '2026-06-20',
    created_at: '2026-06-18T09:00:00Z',
    notes: 'Asset list received — value assessment needed',
  },
  {
    id: 'ow-017',
    title: 'PT white label product matching',
    owner: 'james.k',
    status: 'review',
    priority: 'medium',
    market: 'PT',
    category: 'cannabis_inventory',
    due_date: '2026-06-23',
    created_at: '2026-06-16T11:00:00Z',
    notes: 'UK buyer specifications matched to PT producer',
  },
  {
    id: 'ow-018',
    title: 'CZ importer introduction packet',
    owner: 'alex.m',
    status: 'follow_up',
    priority: 'low',
    market: 'CZ',
    category: 'importers',
    due_date: '2026-06-25',
    created_at: '2026-06-15T15:00:00Z',
    notes: 'Intro sent — no response in 5 days',
  },
  {
    id: 'ow-019',
    title: 'DE equipment surplus buyer coordination',
    owner: 'sarah.b',
    status: 'team_queue',
    priority: 'medium',
    market: 'DE',
    category: 'equipment',
    due_date: '2026-06-24',
    created_at: '2026-06-17T14:30:00Z',
    notes: 'Three interested buyers — coordinate viewing',
  },
  {
    id: 'ow-020',
    title: 'UK services coordination — logistics review',
    owner: 'james.k',
    status: 'approval',
    priority: 'high',
    market: 'UK',
    category: 'services',
    due_date: '2026-06-21',
    created_at: '2026-06-18T08:00:00Z',
    notes: 'Cold chain logistics partner — final approval stage',
  },
]

export const enterpriseDealRooms: EnterpriseDealRoom[] = [
  {
    id: 'dr-001',
    room_type: 'buyer_seller',
    title: 'DE Pharmacy Group × CA Licensed Producer',
    participants: ['PharmaCann DE GmbH', 'Maple Leaf Cannabis Inc'],
    market: 'DE',
    category: 'cannabis_inventory',
    status: 'active',
    next_action: 'Awaiting updated CoA from producer',
    created_at: '2026-06-10T09:00:00Z',
  },
  {
    id: 'dr-002',
    room_type: 'importer_introduction',
    title: 'UK Importer × PT Producer Introduction',
    participants: ['Pharma Import UK Ltd', 'CannaMed Portugal SA'],
    market: 'UK',
    category: 'importers',
    status: 'ready_for_intro',
    next_action: 'Send formal introduction email',
    created_at: '2026-06-12T11:00:00Z',
  },
  {
    id: 'dr-003',
    room_type: 'distributor_review',
    title: 'AU Distributor Qualification Review',
    participants: ['MedCann Australia Pty', 'Harbourview Ops'],
    market: 'AU',
    category: 'distributors',
    status: 'waiting_documents',
    next_action: 'Request TGA distribution licence',
    created_at: '2026-06-08T14:00:00Z',
  },
  {
    id: 'dr-004',
    room_type: 'market_access_review',
    title: 'DE Market Access Pathway — LATAM Producer',
    participants: ['ColCanna LATAM', 'DE Market Access Advisor'],
    market: 'DE',
    category: 'market_access',
    status: 'active',
    next_action: 'Review Lauer-Taxe reimbursement pathway',
    created_at: '2026-06-14T10:30:00Z',
  },
  {
    id: 'dr-005',
    room_type: 'documentation_review',
    title: 'EU GMP Documentation — NL Producer',
    participants: ['Dutch Flower Co BV', 'GMP Consult EU'],
    market: 'NL',
    category: 'eu_gmp',
    status: 'waiting_documents',
    next_action: 'Upload site master file',
    created_at: '2026-06-11T09:30:00Z',
  },
  {
    id: 'dr-006',
    room_type: 'equipment_surplus',
    title: 'CA Extraction Equipment — EU Buyers',
    participants: ['CannaEquip CA', 'DE Processing GmbH', 'CZ Extract sro'],
    market: 'CA',
    category: 'equipment',
    status: 'active',
    next_action: 'Coordinate equipment inspection',
    created_at: '2026-06-13T12:00:00Z',
  },
  {
    id: 'dr-007',
    room_type: 'packaging_supplier',
    title: 'PL Packaging Supplier — UK Buyer',
    participants: ['PackPol Sp z oo', 'UK Cannabis Retail Ltd'],
    market: 'PL',
    category: 'packaging',
    status: 'waiting_counterparty',
    next_action: 'UK buyer to confirm spec requirements',
    created_at: '2026-06-09T15:00:00Z',
  },
  {
    id: 'dr-008',
    room_type: 'services_coordination',
    title: 'DE Legal Compliance Review — CA Exporter',
    participants: ['Cannabis Law DE', 'Maple Leaf Cannabis Inc'],
    market: 'DE',
    category: 'services',
    status: 'active',
    next_action: 'Review BtMG compliance checklist',
    created_at: '2026-06-15T11:00:00Z',
  },
  {
    id: 'dr-009',
    room_type: 'ma_distressed_asset',
    title: 'CA Distressed Producer — Asset Review',
    participants: ['M&A Advisor CA', 'EU Cannabis Fund'],
    market: 'CA',
    category: 'cannabis_inventory',
    status: 'stalled',
    next_action: 'Pending regulatory clearance',
    created_at: '2026-05-28T10:00:00Z',
  },
  {
    id: 'dr-010',
    room_type: 'buyer_seller',
    title: 'CZ Pharmacies × PT Producer',
    participants: ['Česká Farmacia AS', 'LusoMed Cannabis Lda'],
    market: 'CZ',
    category: 'cannabis_inventory',
    status: 'ready_for_intro',
    next_action: 'Prepare formal introduction letter',
    created_at: '2026-06-16T14:00:00Z',
  },
  {
    id: 'dr-011',
    room_type: 'importer_introduction',
    title: 'AU Importer × NL Producer',
    participants: ['MedImport AU', 'Dutch Flower Co BV'],
    market: 'AU',
    category: 'importers',
    status: 'complete',
    next_action: 'Archive — intro completed',
    created_at: '2026-06-01T09:00:00Z',
  },
  {
    id: 'dr-012',
    room_type: 'distributor_review',
    title: 'UK Distribution Network Expansion',
    participants: ['UK Pharma Dist Ltd', 'Harbourview Ops'],
    market: 'UK',
    category: 'distributors',
    status: 'active',
    next_action: 'Review distribution territory agreements',
    created_at: '2026-06-17T10:00:00Z',
  },
]

export const introPackets: IntroPacket[] = [
  {
    id: 'ip-001',
    packet_type: 'buyer_seller',
    title: 'PharmaCann DE × Maple Leaf CA',
    counterparties: ['PharmaCann DE GmbH', 'Maple Leaf Cannabis Inc'],
    market: 'DE',
    category: 'cannabis_inventory',
    fit_score: 92,
    trust_score: 88,
    documentation_status: 'complete',
    status: 'sent',
    owner: 'sarah.b',
    created_at: '2026-06-11T09:00:00Z',
  },
  {
    id: 'ip-002',
    packet_type: 'importer',
    title: 'UK Import Introduction — CannaMed PT',
    counterparties: ['Pharma Import UK Ltd', 'CannaMed Portugal SA'],
    market: 'UK',
    category: 'importers',
    fit_score: 87,
    trust_score: 91,
    documentation_status: 'complete',
    status: 'ready_for_review',
    owner: 'james.k',
    created_at: '2026-06-14T11:00:00Z',
  },
  {
    id: 'ip-003',
    packet_type: 'distributor',
    title: 'AU Distribution — MedCann Network',
    counterparties: ['MedCann Australia Pty', 'ColCanna LATAM'],
    market: 'AU',
    category: 'distributors',
    fit_score: 74,
    trust_score: 68,
    documentation_status: 'partial',
    status: 'follow_up_needed',
    owner: 'alex.m',
    created_at: '2026-06-08T14:00:00Z',
  },
  {
    id: 'ip-004',
    packet_type: 'market_access',
    title: 'DE Market Access — LATAM GACP Producer',
    counterparties: ['ColCanna LATAM', 'DE Market Access Advisor'],
    market: 'DE',
    category: 'market_access',
    fit_score: 81,
    trust_score: 76,
    documentation_status: 'partial',
    status: 'draft',
    owner: 'sarah.b',
    created_at: '2026-06-15T10:30:00Z',
  },
  {
    id: 'ip-005',
    packet_type: 'supplier',
    title: 'NL White Label Supply — UK Buyer',
    counterparties: ['Dutch Flower Co BV', 'UK Cannabis Retail Ltd'],
    market: 'NL',
    category: 'cannabis_inventory',
    fit_score: 89,
    trust_score: 85,
    documentation_status: 'complete',
    status: 'sent',
    owner: 'james.k',
    created_at: '2026-06-09T13:00:00Z',
  },
  {
    id: 'ip-006',
    packet_type: 'equipment',
    title: 'CA Equipment Sale — DE Processor',
    counterparties: ['CannaEquip CA', 'DE Processing GmbH'],
    market: 'CA',
    category: 'equipment',
    fit_score: 78,
    trust_score: 83,
    documentation_status: 'complete',
    status: 'outcome_captured',
    owner: 'alex.m',
    created_at: '2026-06-05T09:00:00Z',
  },
  {
    id: 'ip-007',
    packet_type: 'packaging_supplier',
    title: 'PL Packaging × UK Retail Chain',
    counterparties: ['PackPol Sp z oo', 'UK Cannabis Retail Ltd'],
    market: 'PL',
    category: 'packaging',
    fit_score: 72,
    trust_score: 79,
    documentation_status: 'partial',
    status: 'draft',
    owner: 'sarah.b',
    created_at: '2026-06-16T14:00:00Z',
  },
  {
    id: 'ip-008',
    packet_type: 'buyer_seller',
    title: 'CZ Pharmacies × PT Producer',
    counterparties: ['Česká Farmacia AS', 'LusoMed Cannabis Lda'],
    market: 'CZ',
    category: 'cannabis_inventory',
    fit_score: 85,
    trust_score: 80,
    documentation_status: 'complete',
    status: 'ready_for_review',
    owner: 'james.k',
    created_at: '2026-06-17T10:00:00Z',
  },
  {
    id: 'ip-009',
    packet_type: 'service_provider',
    title: 'EU GMP Consultant — NL Producer',
    counterparties: ['GMP Consult EU', 'Dutch Flower Co BV'],
    market: 'NL',
    category: 'eu_gmp',
    fit_score: 94,
    trust_score: 92,
    documentation_status: 'complete',
    status: 'sent',
    owner: 'alex.m',
    created_at: '2026-06-10T11:00:00Z',
  },
  {
    id: 'ip-010',
    packet_type: 'importer',
    title: 'AU Importer × NL Producer Introduction',
    counterparties: ['MedImport AU', 'Dutch Flower Co BV'],
    market: 'AU',
    category: 'importers',
    fit_score: 88,
    trust_score: 86,
    documentation_status: 'complete',
    status: 'outcome_captured',
    owner: 'sarah.b',
    created_at: '2026-06-03T09:00:00Z',
  },
  {
    id: 'ip-011',
    packet_type: 'buyer_seller',
    title: 'UK Hospital Group × CA Dried Flower',
    counterparties: ['NHS Specialist Pharmacy', 'Maple Leaf Cannabis Inc'],
    market: 'UK',
    category: 'cannabis_inventory',
    fit_score: 76,
    trust_score: 82,
    documentation_status: 'partial',
    status: 'follow_up_needed',
    owner: 'james.k',
    created_at: '2026-06-13T14:00:00Z',
  },
  {
    id: 'ip-012',
    packet_type: 'market_access',
    title: 'PL Market Access — CA Producer',
    counterparties: ['PL Pharma Import Sp', 'Maple Leaf Cannabis Inc'],
    market: 'PL',
    category: 'market_access',
    fit_score: 63,
    trust_score: 71,
    documentation_status: 'missing',
    status: 'draft',
    owner: 'alex.m',
    created_at: '2026-06-18T09:00:00Z',
  },
  {
    id: 'ip-013',
    packet_type: 'supplier',
    title: 'LATAM Organic Supply — DE Buyer',
    counterparties: ['ColCanna LATAM', 'PharmaCann DE GmbH'],
    market: 'LATAM',
    category: 'cannabis_inventory',
    fit_score: 79,
    trust_score: 73,
    documentation_status: 'partial',
    status: 'draft',
    owner: 'sarah.b',
    created_at: '2026-06-17T16:00:00Z',
  },
  {
    id: 'ip-014',
    packet_type: 'distributor',
    title: 'DE Distribution Network — PT Producer',
    counterparties: ['DE Pharma Dist GmbH', 'CannaMed Portugal SA'],
    market: 'DE',
    category: 'distributors',
    fit_score: 91,
    trust_score: 89,
    documentation_status: 'complete',
    status: 'sent',
    owner: 'james.k',
    created_at: '2026-06-12T10:00:00Z',
  },
  {
    id: 'ip-015',
    packet_type: 'service_provider',
    title: 'UK Legal Compliance — CA Exporter',
    counterparties: ['Cannabis Law UK', 'Maple Leaf Cannabis Inc'],
    market: 'UK',
    category: 'services',
    fit_score: 87,
    trust_score: 90,
    documentation_status: 'complete',
    status: 'ready_for_review',
    owner: 'alex.m',
    created_at: '2026-06-15T13:00:00Z',
  },
  {
    id: 'ip-016',
    packet_type: 'equipment',
    title: 'DE Processing Equipment — CZ Extractor',
    counterparties: ['DE Processing GmbH', 'CZ Extract sro'],
    market: 'DE',
    category: 'equipment',
    fit_score: 82,
    trust_score: 78,
    documentation_status: 'partial',
    status: 'follow_up_needed',
    owner: 'sarah.b',
    created_at: '2026-06-16T11:00:00Z',
  },
]

export const documentReadinessPackets: DocumentReadinessPacket[] = [
  {
    id: 'dp-001',
    packet_category: 'eu_gmp',
    title: 'EU GMP Certificate — Maple Leaf CA',
    entity_label: 'Maple Leaf Cannabis Inc',
    market: 'CA',
    status: 'approved',
    completeness_pct: 100,
    missing_items: [],
    created_at: '2026-06-10T09:00:00Z',
  },
  {
    id: 'dp-002',
    packet_category: 'coa',
    title: 'CoA Package — Dutch Flower Co NL',
    entity_label: 'Dutch Flower Co BV',
    market: 'NL',
    status: 'ready',
    completeness_pct: 100,
    missing_items: [],
    created_at: '2026-06-12T10:00:00Z',
  },
  {
    id: 'dp-003',
    packet_category: 'seller_supply_package',
    title: 'Supply Package — CannaMed PT',
    entity_label: 'CannaMed Portugal SA',
    market: 'PT',
    status: 'in_review',
    completeness_pct: 85,
    missing_items: ['Updated spec sheet', 'Product photos (high-res)'],
    created_at: '2026-06-13T11:00:00Z',
  },
  {
    id: 'dp-004',
    packet_category: 'import_docs',
    title: 'UK Import Documentation — Pharma Import UK',
    entity_label: 'Pharma Import UK Ltd',
    market: 'UK',
    status: 'missing_documents',
    completeness_pct: 60,
    missing_items: ['MHRA import licence', 'Home Office controlled drug licence', 'Supplier CoA'],
    created_at: '2026-06-14T09:30:00Z',
  },
  {
    id: 'dp-005',
    packet_category: 'gacp',
    title: 'GACP Certificate — ColCanna LATAM',
    entity_label: 'ColCanna LATAM',
    market: 'LATAM',
    status: 'in_review',
    completeness_pct: 90,
    missing_items: ['Audit report translation (EN)'],
    created_at: '2026-06-11T14:00:00Z',
  },
  {
    id: 'dp-006',
    packet_category: 'buyer_requirement',
    title: 'DE Buyer Requirements — PharmaCann',
    entity_label: 'PharmaCann DE GmbH',
    market: 'DE',
    status: 'ready',
    completeness_pct: 100,
    missing_items: [],
    created_at: '2026-06-09T10:00:00Z',
  },
  {
    id: 'dp-007',
    packet_category: 'market_access_package',
    title: 'DE Market Access Package — LATAM Entry',
    entity_label: 'ColCanna LATAM',
    market: 'DE',
    status: 'missing_documents',
    completeness_pct: 45,
    missing_items: ['BfArM registration', 'German GMP certificate', 'DEA equivalent', 'Import permit'],
    created_at: '2026-06-15T09:00:00Z',
  },
  {
    id: 'dp-008',
    packet_category: 'licence',
    title: 'AU TGA Licence — MedCann Australia',
    entity_label: 'MedCann Australia Pty',
    market: 'AU',
    status: 'approved',
    completeness_pct: 100,
    missing_items: [],
    created_at: '2026-06-06T10:00:00Z',
  },
  {
    id: 'dp-009',
    packet_category: 'distributor_review_package',
    title: 'AU Distributor Review Package',
    entity_label: 'MedCann Australia Pty',
    market: 'AU',
    status: 'in_review',
    completeness_pct: 75,
    missing_items: ['TGA distribution agreement', 'Cold chain SOP'],
    created_at: '2026-06-08T14:00:00Z',
  },
  {
    id: 'dp-010',
    packet_category: 'export_docs',
    title: 'CA Export Documentation Package',
    entity_label: 'Maple Leaf Cannabis Inc',
    market: 'CA',
    status: 'ready',
    completeness_pct: 100,
    missing_items: [],
    created_at: '2026-06-07T11:00:00Z',
  },
  {
    id: 'dp-011',
    packet_category: 'spec_sheet',
    title: 'Product Spec Sheets — LusoMed PT',
    entity_label: 'LusoMed Cannabis Lda',
    market: 'PT',
    status: 'missing_documents',
    completeness_pct: 50,
    missing_items: ['Full cannabinoid profile', 'Terpene profile', 'Pesticide residue report'],
    created_at: '2026-06-16T10:00:00Z',
  },
  {
    id: 'dp-012',
    packet_category: 'importer_review_package',
    title: 'CZ Importer Review Package',
    entity_label: 'CZ MedImport sro',
    market: 'CZ',
    status: 'in_review',
    completeness_pct: 80,
    missing_items: ['SUKL import authorisation update'],
    created_at: '2026-06-14T13:00:00Z',
  },
  {
    id: 'dp-013',
    packet_category: 'product_photos',
    title: 'Product Photography — Dutch Flower Co',
    entity_label: 'Dutch Flower Co BV',
    market: 'NL',
    status: 'approved',
    completeness_pct: 100,
    missing_items: [],
    created_at: '2026-06-11T09:30:00Z',
  },
  {
    id: 'dp-014',
    packet_category: 'seller_supply_package',
    title: 'Supply Package — PL White Label Producer',
    entity_label: 'Polskie Konopie SA',
    market: 'PL',
    status: 'missing_documents',
    completeness_pct: 35,
    missing_items: ['EU GMP certificate', 'CoA (last 6 batches)', 'Site master file', 'QP declaration'],
    created_at: '2026-06-17T11:00:00Z',
  },
  {
    id: 'dp-015',
    packet_category: 'eu_gmp',
    title: 'EU GMP Certificate — LusoMed PT',
    entity_label: 'LusoMed Cannabis Lda',
    market: 'PT',
    status: 'in_review',
    completeness_pct: 70,
    missing_items: ['GMP certificate renewal', 'QP qualification proof'],
    created_at: '2026-06-15T14:00:00Z',
  },
  {
    id: 'dp-016',
    packet_category: 'market_access_package',
    title: 'UK Market Access — CA Producer',
    entity_label: 'Maple Leaf Cannabis Inc',
    market: 'UK',
    status: 'ready',
    completeness_pct: 100,
    missing_items: [],
    created_at: '2026-06-08T10:00:00Z',
  },
]

export const enterpriseDashboardMetrics: EnterpriseDashboardMetric[] = [
  {
    id: 'dm-001',
    category: 'market_coverage',
    label: 'Active Markets',
    value: 9,
    unit: 'markets',
    trend: 'up',
    target: 12,
  },
  {
    id: 'dm-002',
    category: 'ecosystem_coverage',
    label: 'Ecosystem Verticals',
    value: 18,
    unit: 'verticals',
    trend: 'up',
    target: 20,
  },
  {
    id: 'dm-003',
    category: 'deal_velocity',
    label: 'Active Deal Rooms',
    value: 7,
    unit: 'rooms',
    trend: 'up',
    target: 15,
  },
  {
    id: 'dm-004',
    category: 'introduction_success',
    label: 'Intro Packets Sent',
    value: 6,
    unit: 'packets',
    trend: 'up',
    target: 10,
  },
  {
    id: 'dm-005',
    category: 'document_readiness',
    label: 'Documents Ready',
    value: 62,
    unit: '%',
    trend: 'stable',
    target: 85,
  },
  {
    id: 'dm-006',
    category: 'operator_workload',
    label: 'My Queue Items',
    value: 6,
    unit: 'items',
    trend: 'down',
    target: 4,
  },
  {
    id: 'dm-007',
    category: 'trust_reputation',
    label: 'Avg Trust Score',
    value: 82,
    unit: 'score',
    trend: 'up',
    target: 90,
  },
  {
    id: 'dm-008',
    category: 'automation_throughput',
    label: 'Workflows Automated',
    value: 14,
    unit: 'workflows',
    trend: 'up',
    target: 25,
  },
  {
    id: 'dm-009',
    category: 'revenue_opportunity',
    label: 'Pipeline Value',
    value: 4.2,
    unit: 'M EUR',
    trend: 'up',
    target: 10,
  },
  {
    id: 'dm-010',
    category: 'follow_up_load',
    label: 'Pending Follow-ups',
    value: 8,
    unit: 'items',
    trend: 'down',
    target: 5,
  },
  {
    id: 'dm-011',
    category: 'network_growth',
    label: 'New Contacts (30d)',
    value: 47,
    unit: 'contacts',
    trend: 'up',
    target: 60,
  },
  {
    id: 'dm-012',
    category: 'source_freshness',
    label: 'Stale Sources',
    value: 3,
    unit: 'sources',
    trend: 'stable',
    target: 0,
  },
  {
    id: 'dm-013',
    category: 'category_coverage',
    label: 'Categories Active',
    value: 9,
    unit: 'categories',
    trend: 'stable',
    target: 9,
  },
  {
    id: 'dm-014',
    category: 'introduction_success',
    label: 'Intro Success Rate',
    value: 68,
    unit: '%',
    trend: 'up',
    target: 75,
  },
  {
    id: 'dm-015',
    category: 'prediction_accuracy',
    label: 'Match Accuracy',
    value: 79,
    unit: '%',
    trend: 'up',
    target: 85,
  },
  {
    id: 'dm-016',
    category: 'deal_velocity',
    label: 'Avg Deal Cycle',
    value: 18,
    unit: 'days',
    trend: 'down',
    target: 14,
  },
  {
    id: 'dm-017',
    category: 'ecosystem_coverage',
    label: 'High Value Records',
    value: 157,
    unit: 'records',
    trend: 'up',
    target: 200,
  },
  {
    id: 'dm-018',
    category: 'market_coverage',
    label: 'Countries with Live Data',
    value: 9,
    unit: 'countries',
    trend: 'up',
    target: 15,
  },
  {
    id: 'dm-019',
    category: 'operator_workload',
    label: 'Team Queue Items',
    value: 5,
    unit: 'items',
    trend: 'stable',
    target: 4,
  },
  {
    id: 'dm-020',
    category: 'document_readiness',
    label: 'Approved Packets',
    value: 5,
    unit: 'packets',
    trend: 'up',
    target: 12,
  },
]

export const strategicIntegrations: StrategicIntegrationPlaceholder[] = [
  {
    id: 'si-001',
    integration_category: 'email',
    name: 'Gmail / Outlook Integration',
    description: 'Sync counterparty email threads to deal rooms and workflow items automatically',
    status: 'in_development',
    data_flow: 'Email → Deal Room → Operator Queue',
    priority: 'high',
  },
  {
    id: 'si-002',
    integration_category: 'calendar',
    name: 'Google Calendar / Outlook Calendar',
    description: 'Sync introductions and follow-up meetings to operator calendars',
    status: 'planned',
    data_flow: 'Intro Packet → Calendar Event → Operator Notification',
    priority: 'medium',
  },
  {
    id: 'si-003',
    integration_category: 'document_storage',
    name: 'Google Drive / SharePoint',
    description: 'Secure document intake and storage for compliance packets and CoAs',
    status: 'ready_to_connect',
    data_flow: 'Counterparty Upload → Document Packet → Readiness Check',
    priority: 'high',
  },
  {
    id: 'si-004',
    integration_category: 'crm_export',
    name: 'HubSpot / Salesforce Export',
    description: 'Export qualified counterparties and deal rooms to CRM for pipeline management',
    status: 'planned',
    data_flow: 'Intro Packet Sent → CRM Contact → Pipeline Stage',
    priority: 'medium',
  },
  {
    id: 'si-005',
    integration_category: 'regulatory_feeds',
    name: 'Regulatory Signal Feeds',
    description: 'Ingest live regulatory changes from BfArM, MHRA, TGA, Health Canada',
    status: 'in_development',
    data_flow: 'Regulatory Feed → Signal → Market Access Review',
    priority: 'high',
  },
  {
    id: 'si-006',
    integration_category: 'web_crawlers',
    name: 'Licence & Product Web Crawlers',
    description: 'Automated scraping of public licence registries and product databases',
    status: 'in_development',
    data_flow: 'Web Source → Staging → Signal Pipeline → Ecosystem Record',
    priority: 'high',
  },
  {
    id: 'si-007',
    integration_category: 'secure_file_intake',
    name: 'Secure File Intake Portal',
    description: 'Branded secure upload portal for counterparties to submit compliance documents',
    status: 'planned',
    data_flow: 'Counterparty → Secure Upload → Document Packet → Operator Review',
    priority: 'high',
  },
  {
    id: 'si-008',
    integration_category: 'data_providers',
    name: 'IQVIA / Kompass Data',
    description: 'Enrich counterparty records with third-party pharma and trade data',
    status: 'planned',
    data_flow: 'Data Provider → Enrichment → Ecosystem Record → Trust Score Update',
    priority: 'medium',
  },
  {
    id: 'si-009',
    integration_category: 'contact_enrichment',
    name: 'Apollo.io / Clearbit Enrichment',
    description: 'Automatically enrich counterparty contact records with verified business data',
    status: 'planned',
    data_flow: 'New Contact → Enrichment API → Ecosystem Record',
    priority: 'medium',
  },
  {
    id: 'si-010',
    integration_category: 'spreadsheet',
    name: 'Google Sheets / Excel Import',
    description: 'Bulk import of counterparty lists and market data from spreadsheets',
    status: 'ready_to_connect',
    data_flow: 'Spreadsheet Upload → Validation → Ecosystem Record Batch Create',
    priority: 'medium',
  },
  {
    id: 'si-011',
    integration_category: 'notification',
    name: 'Slack / Teams Notifications',
    description: 'Real-time operator alerts for deal room activity and intro packet status changes',
    status: 'planned',
    data_flow: 'Deal Event → Notification → Operator Channel',
    priority: 'low',
  },
  {
    id: 'si-012',
    integration_category: 'accounting',
    name: 'Xero / QuickBooks Integration',
    description: 'Sync completed deal introductions to accounting for fee tracking',
    status: 'planned',
    data_flow: 'Outcome Captured → Invoice Draft → Accounting System',
    priority: 'low',
  },
]

export const reputationRecords: ReputationRecord[] = [
  {
    id: 'rr-001',
    entity_label: 'Maple Leaf Cannabis Inc',
    entity_type: 'counterparty',
    market: 'CA',
    category: 'cannabis_inventory',
    trust_score: 92,
    responsiveness: 95,
    document_quality: 91,
    intro_quality: 88,
    reliability: 93,
    relationship_value: 90,
    status: 'priority',
  },
  {
    id: 'rr-002',
    entity_label: 'Dutch Flower Co BV',
    entity_type: 'counterparty',
    market: 'NL',
    category: 'cannabis_inventory',
    trust_score: 89,
    responsiveness: 85,
    document_quality: 94,
    intro_quality: 87,
    reliability: 91,
    relationship_value: 86,
    status: 'priority',
  },
  {
    id: 'rr-003',
    entity_label: 'MedCann Australia Pty',
    entity_type: 'counterparty',
    market: 'AU',
    category: 'distributors',
    trust_score: 72,
    responsiveness: 60,
    document_quality: 78,
    intro_quality: 71,
    reliability: 68,
    relationship_value: 74,
    status: 'watch_carefully',
  },
  {
    id: 'rr-004',
    entity_label: 'CannaMed Portugal SA',
    entity_type: 'counterparty',
    market: 'PT',
    category: 'cannabis_inventory',
    trust_score: 86,
    responsiveness: 88,
    document_quality: 82,
    intro_quality: 84,
    reliability: 87,
    relationship_value: 83,
    status: 'standard',
  },
  {
    id: 'rr-005',
    entity_label: 'EU Licensed Producers Network',
    entity_type: 'ecosystem',
    market: 'DE',
    category: 'cannabis_inventory',
    trust_score: 88,
    responsiveness: 84,
    document_quality: 90,
    intro_quality: 86,
    reliability: 89,
    relationship_value: 87,
    status: 'priority',
  },
  {
    id: 'rr-006',
    entity_label: 'ColCanna LATAM',
    entity_type: 'counterparty',
    market: 'LATAM',
    category: 'cannabis_inventory',
    trust_score: 74,
    responsiveness: 79,
    document_quality: 68,
    intro_quality: 72,
    reliability: 76,
    relationship_value: 70,
    status: 'watch_carefully',
  },
  {
    id: 'rr-007',
    entity_label: 'PackPol Sp z oo',
    entity_type: 'counterparty',
    market: 'PL',
    category: 'packaging',
    trust_score: 81,
    responsiveness: 77,
    document_quality: 83,
    intro_quality: 80,
    reliability: 82,
    relationship_value: 78,
    status: 'standard',
  },
  {
    id: 'rr-008',
    entity_label: 'PharmaCann DE GmbH',
    entity_type: 'counterparty',
    market: 'DE',
    category: 'cannabis_inventory',
    trust_score: 94,
    responsiveness: 92,
    document_quality: 96,
    intro_quality: 93,
    reliability: 95,
    relationship_value: 91,
    status: 'priority',
  },
  {
    id: 'rr-009',
    entity_label: 'GMP Consult EU',
    entity_type: 'counterparty',
    market: 'DE',
    category: 'eu_gmp',
    trust_score: 93,
    responsiveness: 90,
    document_quality: 95,
    intro_quality: 92,
    reliability: 94,
    relationship_value: 89,
    status: 'priority',
  },
  {
    id: 'rr-010',
    entity_label: 'CannaEquip CA',
    entity_type: 'counterparty',
    market: 'CA',
    category: 'equipment',
    trust_score: 83,
    responsiveness: 86,
    document_quality: 80,
    intro_quality: 82,
    reliability: 84,
    relationship_value: 85,
    status: 'standard',
  },
  {
    id: 'rr-011',
    entity_label: 'Česká Farmacia AS',
    entity_type: 'counterparty',
    market: 'CZ',
    category: 'importers',
    trust_score: 78,
    responsiveness: 82,
    document_quality: 76,
    intro_quality: 79,
    reliability: 80,
    relationship_value: 77,
    status: 'standard',
  },
  {
    id: 'rr-012',
    entity_label: 'LusoMed Cannabis Lda',
    entity_type: 'counterparty',
    market: 'PT',
    category: 'cannabis_inventory',
    trust_score: 65,
    responsiveness: 58,
    document_quality: 62,
    intro_quality: 67,
    reliability: 63,
    relationship_value: 60,
    status: 'reengage_later',
  },
  {
    id: 'rr-013',
    entity_label: 'Cannabis Testing Labs Vertical',
    entity_type: 'vertical',
    market: 'DE',
    category: 'services',
    trust_score: 87,
    responsiveness: 85,
    document_quality: 89,
    intro_quality: 86,
    reliability: 88,
    relationship_value: 84,
    status: 'priority',
  },
  {
    id: 'rr-014',
    entity_label: 'Polskie Konopie SA',
    entity_type: 'counterparty',
    market: 'PL',
    category: 'cannabis_inventory',
    trust_score: 52,
    responsiveness: 45,
    document_quality: 48,
    intro_quality: 54,
    reliability: 50,
    relationship_value: 47,
    status: 'reengage_later',
  },
  {
    id: 'rr-015',
    entity_label: 'UK Cannabis Retail Ltd',
    entity_type: 'counterparty',
    market: 'UK',
    category: 'distributors',
    trust_score: 85,
    responsiveness: 88,
    document_quality: 83,
    intro_quality: 86,
    reliability: 87,
    relationship_value: 84,
    status: 'standard',
  },
  {
    id: 'rr-016',
    entity_label: 'DE Processing GmbH',
    entity_type: 'counterparty',
    market: 'DE',
    category: 'equipment',
    trust_score: 90,
    responsiveness: 87,
    document_quality: 92,
    intro_quality: 89,
    reliability: 91,
    relationship_value: 88,
    status: 'priority',
  },
]

export const dataFlywheelEvents: DataFlywheelEvent[] = [
  {
    id: 'fe-001',
    event_type: 'new_intake',
    description: 'New EU GMP certified producer onboarded from DE licensing database',
    impact: 'high',
    market: 'DE',
    category: 'cannabis_inventory',
    dataset_enriched: 'ecosystemVerticals.licensed_producer',
    created_at: '2026-06-18T09:00:00Z',
  },
  {
    id: 'fe-002',
    event_type: 'new_buyer_demand',
    description: 'UK pharmacy chain submitted buy-side demand for 50kg/month dried flower',
    impact: 'high',
    market: 'UK',
    category: 'cannabis_inventory',
    dataset_enriched: 'operatorWorkflowItems.buyer_demand',
    created_at: '2026-06-18T10:30:00Z',
  },
  {
    id: 'fe-003',
    event_type: 'new_supply',
    description: 'PT producer uploaded new product catalogue with 8 SKUs',
    impact: 'medium',
    market: 'PT',
    category: 'cannabis_inventory',
    dataset_enriched: 'ecosystemVerticals.licensed_producer',
    created_at: '2026-06-17T14:00:00Z',
  },
  {
    id: 'fe-004',
    event_type: 'new_intro',
    description: 'Formal introduction sent — PharmaCann DE × Maple Leaf CA',
    impact: 'high',
    market: 'DE',
    category: 'cannabis_inventory',
    dataset_enriched: 'introPackets.sent',
    created_at: '2026-06-17T16:00:00Z',
  },
  {
    id: 'fe-005',
    event_type: 'new_document',
    description: 'EU GMP certificate uploaded for Dutch Flower Co NL',
    impact: 'medium',
    market: 'NL',
    category: 'eu_gmp',
    dataset_enriched: 'documentReadinessPackets.eu_gmp',
    created_at: '2026-06-17T11:30:00Z',
  },
  {
    id: 'fe-006',
    event_type: 'new_outcome',
    description: 'Successful intro outcome captured — AU Importer × NL Producer deal closed',
    impact: 'high',
    market: 'AU',
    category: 'importers',
    dataset_enriched: 'reputationRecords.intro_quality',
    created_at: '2026-06-16T15:00:00Z',
  },
  {
    id: 'fe-007',
    event_type: 'new_signal',
    description: 'DE regulatory update — BtMG amendment affecting import procedures',
    impact: 'high',
    market: 'DE',
    category: 'market_access',
    dataset_enriched: 'ecosystemVerticals.market_access_partner',
    created_at: '2026-06-16T09:00:00Z',
  },
  {
    id: 'fe-008',
    event_type: 'new_trust_update',
    description: 'Trust score updated for ColCanna LATAM after document quality review',
    impact: 'medium',
    market: 'LATAM',
    category: 'cannabis_inventory',
    dataset_enriched: 'reputationRecords.trust_score',
    created_at: '2026-06-15T14:00:00Z',
  },
  {
    id: 'fe-009',
    event_type: 'new_deal_movement',
    description: 'CZ Pharmacies × PT Producer deal room advanced to ready_for_intro',
    impact: 'high',
    market: 'CZ',
    category: 'cannabis_inventory',
    dataset_enriched: 'enterpriseDealRooms.status',
    created_at: '2026-06-15T11:00:00Z',
  },
  {
    id: 'fe-010',
    event_type: 'new_relationship_note',
    description: 'Operator note added — MedCann AU responsiveness concern flagged',
    impact: 'medium',
    market: 'AU',
    category: 'distributors',
    dataset_enriched: 'reputationRecords.responsiveness',
    created_at: '2026-06-14T16:00:00Z',
  },
  {
    id: 'fe-011',
    event_type: 'new_source',
    description: 'New web crawler source added — UK MHRA import licence registry',
    impact: 'medium',
    market: 'UK',
    category: 'importers',
    dataset_enriched: 'ecosystemVerticals.importer',
    created_at: '2026-06-14T10:00:00Z',
  },
  {
    id: 'fe-012',
    event_type: 'new_prediction_feedback',
    description: 'Fit score model updated after successful DE × CA intro outcome',
    impact: 'high',
    market: 'DE',
    category: 'cannabis_inventory',
    dataset_enriched: 'introPackets.fit_score',
    created_at: '2026-06-13T09:00:00Z',
  },
  {
    id: 'fe-013',
    event_type: 'new_supply',
    description: 'CA distressed producer asset list added to M&A vertical',
    impact: 'medium',
    market: 'CA',
    category: 'services',
    dataset_enriched: 'ecosystemVerticals.ma_distressed',
    created_at: '2026-06-12T14:00:00Z',
  },
  {
    id: 'fe-014',
    event_type: 'new_pathway_review',
    description: 'LATAM to DE market access pathway reviewed — 4 compliance gaps identified',
    impact: 'high',
    market: 'LATAM',
    category: 'market_access',
    dataset_enriched: 'documentReadinessPackets.market_access_package',
    created_at: '2026-06-12T11:00:00Z',
  },
  {
    id: 'fe-015',
    event_type: 'new_intake',
    description: 'PL packaging supplier added via trade directory crawl',
    impact: 'low',
    market: 'PL',
    category: 'packaging',
    dataset_enriched: 'ecosystemVerticals.packaging_supplier',
    created_at: '2026-06-11T15:00:00Z',
  },
  {
    id: 'fe-016',
    event_type: 'new_buyer_demand',
    description: 'AU hospital network submitted equipment procurement requirements',
    impact: 'medium',
    market: 'AU',
    category: 'equipment',
    dataset_enriched: 'operatorWorkflowItems.buyer_demand',
    created_at: '2026-06-11T10:30:00Z',
  },
  {
    id: 'fe-017',
    event_type: 'new_document',
    description: 'GACP translation uploaded for ColCanna LATAM audit report',
    impact: 'medium',
    market: 'LATAM',
    category: 'eu_gmp',
    dataset_enriched: 'documentReadinessPackets.gacp',
    created_at: '2026-06-10T14:00:00Z',
  },
  {
    id: 'fe-018',
    event_type: 'new_deal_movement',
    description: 'UK Distribution Network Expansion deal room activated',
    impact: 'medium',
    market: 'UK',
    category: 'distributors',
    dataset_enriched: 'enterpriseDealRooms.status',
    created_at: '2026-06-10T09:00:00Z',
  },
  {
    id: 'fe-019',
    event_type: 'new_intro',
    description: 'NL white label supply intro packet sent to UK buyer',
    impact: 'medium',
    market: 'NL',
    category: 'cannabis_inventory',
    dataset_enriched: 'introPackets.sent',
    created_at: '2026-06-09T13:00:00Z',
  },
  {
    id: 'fe-020',
    event_type: 'new_trust_update',
    description: 'PharmaCann DE trust score increased after third successful intro',
    impact: 'high',
    market: 'DE',
    category: 'cannabis_inventory',
    dataset_enriched: 'reputationRecords.trust_score',
    created_at: '2026-06-08T11:00:00Z',
  },
]

export const commercialCoordinationWorkflows: CommercialCoordinationWorkflow[] = [
  {
    id: 'cw-001',
    workflow_type: 'supply_to_buyer',
    title: 'CA Flower Supply → DE Pharmacy Buyers',
    market: 'DE',
    category: 'cannabis_inventory',
    status: 'ready_for_intro',
    next_action: 'Send formal introduction packet',
    owner: 'sarah.b',
    created_at: '2026-06-11T09:00:00Z',
  },
  {
    id: 'cw-002',
    workflow_type: 'buyer_demand_to_supplier',
    title: 'UK Hospital Demand → EU Supplier Match',
    market: 'UK',
    category: 'cannabis_inventory',
    status: 'ready_for_action',
    next_action: 'Match demand spec to PT and NL producers',
    owner: 'james.k',
    created_at: '2026-06-14T11:00:00Z',
  },
  {
    id: 'cw-003',
    workflow_type: 'importer_need_to_supplier',
    title: 'CZ Importer Requirement → Matched Suppliers',
    market: 'CZ',
    category: 'importers',
    status: 'waiting_counterparty',
    next_action: 'Awaiting importer specification update',
    owner: 'alex.m',
    created_at: '2026-06-13T10:00:00Z',
  },
  {
    id: 'cw-004',
    workflow_type: 'opportunity_to_intro_packet',
    title: 'PT Producer Opportunity → UK Intro Packet',
    market: 'PT',
    category: 'cannabis_inventory',
    status: 'ready_for_action',
    next_action: 'Compile intro packet from existing docs',
    owner: 'sarah.b',
    created_at: '2026-06-15T14:00:00Z',
  },
  {
    id: 'cw-005',
    workflow_type: 'document_packet_to_market_access',
    title: 'LATAM Document Package → DE Market Entry',
    market: 'LATAM',
    category: 'market_access',
    status: 'waiting_documents',
    next_action: 'Request GMP certificate from producer',
    owner: 'james.k',
    created_at: '2026-06-12T09:00:00Z',
  },
  {
    id: 'cw-006',
    workflow_type: 'source_signal_to_opportunity',
    title: 'DE Regulatory Signal → Compliance Opportunity',
    market: 'DE',
    category: 'market_access',
    status: 'ready_for_action',
    next_action: 'Brief affected counterparties on BtMG change',
    owner: 'alex.m',
    created_at: '2026-06-16T09:00:00Z',
  },
  {
    id: 'cw-007',
    workflow_type: 'distributor_need_to_product',
    title: 'AU Distributor Gap → Product Matching',
    market: 'AU',
    category: 'distributors',
    status: 'waiting_counterparty',
    next_action: 'Distributor to confirm product preferences',
    owner: 'sarah.b',
    created_at: '2026-06-10T11:00:00Z',
  },
  {
    id: 'cw-008',
    workflow_type: 'equipment_lead_to_buyer',
    title: 'CA Equipment Surplus → EU Equipment Buyers',
    market: 'CA',
    category: 'equipment',
    status: 'ready_for_intro',
    next_action: 'Coordinate joint viewing with DE and CZ buyers',
    owner: 'james.k',
    created_at: '2026-06-13T12:00:00Z',
  },
  {
    id: 'cw-009',
    workflow_type: 'stale_deal_reactivation',
    title: 'NL Buyer Reactivation — Stalled 3 Weeks',
    market: 'NL',
    category: 'cannabis_inventory',
    status: 'ready_for_action',
    next_action: 'Contact buyer with new supply option',
    owner: 'alex.m',
    created_at: '2026-06-10T09:00:00Z',
  },
  {
    id: 'cw-010',
    workflow_type: 'supply_to_buyer',
    title: 'NL White Label → UK Branded Product Buyer',
    market: 'NL',
    category: 'cannabis_inventory',
    status: 'complete',
    next_action: 'Archive — outcome captured',
    owner: 'sarah.b',
    created_at: '2026-06-05T10:00:00Z',
  },
  {
    id: 'cw-011',
    workflow_type: 'opportunity_to_intro_packet',
    title: 'CZ Pharmacy × PT Producer — Packet Build',
    market: 'CZ',
    category: 'cannabis_inventory',
    status: 'ready_for_intro',
    next_action: 'Final review before sending',
    owner: 'james.k',
    created_at: '2026-06-16T14:00:00Z',
  },
  {
    id: 'cw-012',
    workflow_type: 'prediction_to_operator_action',
    title: 'High-Fit Match Alert — DE Buyer × CA Seller',
    market: 'DE',
    category: 'cannabis_inventory',
    status: 'ready_for_action',
    next_action: 'Operator to review and approve match',
    owner: 'alex.m',
    created_at: '2026-06-17T08:30:00Z',
  },
  {
    id: 'cw-013',
    workflow_type: 'document_packet_to_market_access',
    title: 'UK Import Package → Market Clearance',
    market: 'UK',
    category: 'importers',
    status: 'waiting_documents',
    next_action: 'Importer to upload MHRA licence',
    owner: 'sarah.b',
    created_at: '2026-06-14T09:30:00Z',
  },
  {
    id: 'cw-014',
    workflow_type: 'buyer_demand_to_supplier',
    title: 'PL Pharmacy Demand → EU Supplier Network',
    market: 'PL',
    category: 'cannabis_inventory',
    status: 'ready_for_action',
    next_action: 'Shortlist 3 matching EU producers',
    owner: 'james.k',
    created_at: '2026-06-18T10:00:00Z',
  },
  {
    id: 'cw-015',
    workflow_type: 'stale_deal_reactivation',
    title: 'CA M&A Lead Reactivation — EU Buyer Fund',
    market: 'CA',
    category: 'services',
    status: 'stalled',
    next_action: 'Pending CA regulatory clearance before reactivation',
    owner: 'alex.m',
    created_at: '2026-05-28T10:00:00Z',
  },
  {
    id: 'cw-016',
    workflow_type: 'importer_need_to_supplier',
    title: 'AU Importer Requirement → NL Supply Match',
    market: 'AU',
    category: 'importers',
    status: 'complete',
    next_action: 'Archive — intro completed successfully',
    owner: 'sarah.b',
    created_at: '2026-06-01T09:00:00Z',
  },
  {
    id: 'cw-017',
    workflow_type: 'source_signal_to_opportunity',
    title: 'UK MHRA Source → Import Pathway Update',
    market: 'UK',
    category: 'market_access',
    status: 'ready_for_action',
    next_action: 'Update affected importer pathway documents',
    owner: 'james.k',
    created_at: '2026-06-14T10:00:00Z',
  },
  {
    id: 'cw-018',
    workflow_type: 'distributor_need_to_product',
    title: 'UK Distribution Gap — CA Flower Products',
    market: 'UK',
    category: 'distributors',
    status: 'waiting_counterparty',
    next_action: 'UK distributor to confirm volume capacity',
    owner: 'alex.m',
    created_at: '2026-06-17T10:00:00Z',
  },
  {
    id: 'cw-019',
    workflow_type: 'supply_to_buyer',
    title: 'LATAM GACP Supply → DE Buyer Pipeline',
    market: 'LATAM',
    category: 'cannabis_inventory',
    status: 'waiting_documents',
    next_action: 'LATAM producer to complete GACP translation',
    owner: 'sarah.b',
    created_at: '2026-06-15T16:00:00Z',
  },
  {
    id: 'cw-020',
    workflow_type: 'equipment_lead_to_buyer',
    title: 'DE Processor Surplus → CZ Extraction Buyer',
    market: 'DE',
    category: 'equipment',
    status: 'ready_for_intro',
    next_action: 'Prepare equipment intro packet for CZ buyer',
    owner: 'james.k',
    created_at: '2026-06-16T11:00:00Z',
  },
]
