#!/usr/bin/env bash
set -euo pipefail

git config user.name 'Harbourview Repair Operator'
git config user.email 'repair-operator@users.noreply.github.com'

python3 -m pip install --disable-pip-version-check 'pycountry==24.6.1'

mkdir -p scripts/country-data
cat > scripts/country-data/generate-iso-region-rows.py <<'PY'
#!/usr/bin/env python3
from pathlib import Path
import json
import re
import pycountry

ROOT = Path(__file__).resolve().parents[2]
source = ROOT / 'lib/country-data/generated-country-identity-rows.ts'
out = ROOT / 'lib/country-data/generated-iso-region-rows.ts'
text = source.read_text(encoding='utf-8')
match = re.search(r'export const countryIdentityRows =\s*(\[.*\])\s*as const', text, re.S)
if not match:
    raise SystemExit('Unable to parse countryIdentityRows')
rows = json.loads(match.group(1))
overrides = {'XKX': 'XK'}
output = []
missing = []
for row in rows:
    if len(row) < 5:
        raise SystemExit(f'Malformed country identity row: {row}')
    identity = row[0]
    region = row[3] or ''
    subregion = row[4] or ''
    if not isinstance(identity, str) or not identity.startswith('country_area:'):
        continue
    alpha3 = identity.split(':', 1)[1].upper()
    alpha2 = overrides.get(alpha3)
    if not alpha2:
        country = pycountry.countries.get(alpha_3=alpha3)
        alpha2 = country.alpha_2 if country else None
    if not alpha2:
        missing.append(alpha3)
        continue
    output.append([alpha2, alpha3, region, subregion])
if missing:
    raise SystemExit(f'Unmapped ISO-3 identities: {missing}')
output.sort(key=lambda row: row[0])
if len(output) != 248:
    raise SystemExit(f'Expected exactly 248 country/area mappings, got {len(output)}')
if len({row[0] for row in output}) != len(output):
    raise SystemExit('Duplicate ISO-2 output')
if len({row[1] for row in output}) != len(output):
    raise SystemExit('Duplicate ISO-3 output')
body = json.dumps(output, indent=2, ensure_ascii=False)
out.write_text(
    '// Generated by scripts/country-data/generate-iso-region-rows.py\n'
    '// ISO conversion: pycountry 24.6.1; region/subregion: checked-in UN M49-derived Harbourview identities.\n'
    f'export const isoRegionRows = {body} as const\n',
    encoding='utf-8',
)
print(f'wrote {len(output)} ISO region rows')
PY
chmod +x scripts/country-data/generate-iso-region-rows.py
python3 scripts/country-data/generate-iso-region-rows.py

python3 - <<'PY'
from pathlib import Path

path = Path('lib/signals/routing.ts')
text = path.read_text(encoding='utf-8')
text = text.replace(
    "import { countryIdentityRows } from '@/lib/country-data/generated-country-identity-rows'\n",
    "import { isoRegionRows } from '@/lib/country-data/generated-iso-region-rows'\n",
)
text = text.replace("import { countries, getCountryByIso3 } from '@/lib/dashboard/countries'\n", '')

comment_start = text.index('/**\n * ISO-3166-1 alpha-2 for a signal.')
function_start = text.index('export function signalCountryIso2', comment_start)
new_comment = '''/**
 * ISO-3166-1 alpha-2 for a signal.
 *
 * Prefers the structured `country_iso2` column, then resolves a free-text
 * country through the deterministic 248-country ISO-3/ISO-2 bridge generated
 * from the checked-in Harbourview identity table. Region and bloc labels still
 * return null here and are handled by the regional audience matcher.
 */
'''
text = text[:comment_start] + new_comment + text[function_start:]
text = text.replace(
    "  return normaliseIso2(getCountryByIso3(resolved.code)?.iso2)\n",
    "  return ISO2_BY_ISO3.get(resolved.code.toUpperCase()) ?? null\n",
)

region_comment_start = text.index('/**\n * ISO-3166-1 alpha-2 → UN macro-region.')
region_block_end = text.index('function matchesGeography', region_comment_start)
new_region_block = r'''/**
 * Deterministic ISO and UN M49 geography bridge for all 248 checked identities.
 * The generated rows are static runtime data; regeneration is pinned and checked
 * in CI so production does not depend on Python or an external lookup service.
 */
type RegionMetadata = { region: string; subregion: string }

const ISO2_BY_ISO3: ReadonlyMap<string, string> = new Map(
  isoRegionRows.map(([iso2, iso3]) => [iso3, iso2]),
)

const REGION_METADATA_BY_ISO2: ReadonlyMap<string, RegionMetadata> = new Map(
  isoRegionRows.map(([iso2, _iso3, region, subregion]) => [
    iso2,
    { region: region.toLowerCase(), subregion: subregion.toLowerCase() },
  ]),
)

/** Current 27-member European Union set, verified against the official EU list on 2026-08-02. */
const EU_MEMBER_ISO2 = new Set([
  'AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR',
  'HU', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK',
  'SI', 'ES', 'SE',
])

const LATAM_SUBREGIONS = new Set(['caribbean', 'central america', 'south america'])
const UN_MACRO_REGIONS = new Set(['africa', 'americas', 'asia', 'europe', 'oceania'])

function normaliseRegionalLabel(value: unknown): string | null {
  if (typeof value !== 'string') return null
  const label = value.trim().toLowerCase().replace(/[._-]+/g, ' ').replace(/\s+/g, ' ')
  return label || null
}

function regionalAudienceLabel(row: SignalRoutingRow): string | null {
  return normaliseRegionalLabel(row.country) ?? normaliseRegionalLabel(row.geo_region)
}

function regionalAudienceDisplayLabel(row: SignalRoutingRow): string | null {
  for (const value of [row.country, row.geo_region]) {
    if (typeof value === 'string' && value.trim()) return value.trim()
  }
  return null
}

function matchesRegionalAudience(row: SignalRoutingRow, profileIso2: Set<string>): boolean {
  const explicitCountryLabel = normaliseRegionalLabel(row.country)
  const label = explicitCountryLabel ?? normaliseRegionalLabel(row.geo_region)
  if (!label) return false

  return [...profileIso2].some((iso2) => {
    const metadata = REGION_METADATA_BY_ISO2.get(iso2)
    if (!metadata) return false

    switch (label) {
      case 'eu':
      case 'european union':
        return EU_MEMBER_ISO2.has(iso2)
      case 'latam':
      case 'latin america':
      case 'latin america and the caribbean':
      case 'latin america & caribbean':
      case 'latin america and caribbean':
        return LATAM_SUBREGIONS.has(metadata.subregion)
      case 'caribbean':
        return metadata.subregion === 'caribbean'
      case 'middle east':
        // Controlled Harbourview definition: UN M49 Western Asia plus Egypt.
        // It deliberately does not widen to all Asia or all MENA.
        return metadata.subregion === 'western asia' || iso2 === 'EG'
      case 'pacific':
      case 'pacific islands':
        return metadata.region === 'oceania'
      default:
        // A retained but unknown bloc label must fail closed rather than widen
        // to the signal's coarser macro-region. Macro-regions remain explicit.
        return !explicitCountryLabel && UN_MACRO_REGIONS.has(label)
          ? metadata.region === label
          : UN_MACRO_REGIONS.has(label) && metadata.region === label
    }
  })
}

'''
text = text[:region_comment_start] + new_region_block + text[region_block_end:]

geography_start = text.index("    case 'region': {", text.index('function matchesGeography'))
geography_end = text.index("    case 'global':", geography_start)
text = text[:geography_start] + "    case 'region':\n      return matchesRegionalAudience(row, wanted)\n" + text[geography_end:]

explain_start = text.index("    case 'region': {", text.index('export function explainMatch'))
explain_end = text.index("    case 'global':", explain_start)
text = text[:explain_start] + '''    case 'region': {
      const audience = regionalAudienceDisplayLabel(row)
      return audience
        ? `Affects ${audience}, a region or bloc you cover${suffix}`
        : `Matches your watch profile${suffix}`
    }
''' + text[explain_end:]

path.write_text(text, encoding='utf-8')
PY

python3 - <<'PY'
from pathlib import Path

path = Path('tests/signals/routing.test.ts')
text = path.read_text(encoding='utf-8')
start = text.index("  it('fails open for jurisdictions with no region mapping")
end = text.index("  it('delivers global signals to everyone'", start)
replacement = '''  it('uses the complete checked ISO mapping for Singapore', () => {
    const singapore: OperatorProfile = { countryIso2: ['SG'], roleFamilies: cultivation }
    const asia = routed({ geo_scope: 'region', geo_region: 'Asia', role_families: cultivation })
    const europe = routed({ geo_scope: 'region', geo_region: 'Europe', role_families: cultivation })
    expect(matchesOperatorProfile(asia, singapore)).toBe(true)
    expect(matchesOperatorProfile(europe, singapore)).toBe(false)
  })

  it('does not widen LATAM to all of the Americas', () => {
    const usa: OperatorProfile = { countryIso2: ['US'], roleFamilies: cultivation }
    const colombia: OperatorProfile = { countryIso2: ['CO'], roleFamilies: cultivation }
    const signal = routed({ geo_scope: 'region', geo_region: 'Americas', country: 'LATAM', role_families: cultivation })
    expect(matchesOperatorProfile(signal, usa)).toBe(false)
    expect(matchesOperatorProfile(signal, colombia)).toBe(true)
  })

  it('matches Caribbean as a subregion rather than all Americas', () => {
    const barbados: OperatorProfile = { countryIso2: ['BB'], roleFamilies: cultivation }
    const usa: OperatorProfile = { countryIso2: ['US'], roleFamilies: cultivation }
    const signal = routed({ geo_scope: 'region', geo_region: 'Americas', country: 'Caribbean', role_families: cultivation })
    expect(matchesOperatorProfile(signal, barbados)).toBe(true)
    expect(matchesOperatorProfile(signal, usa)).toBe(false)
  })

  it('matches European Union membership independently of UN macro-region', () => {
    const cyprus: OperatorProfile = { countryIso2: ['CY'], roleFamilies: cultivation }
    const uk: OperatorProfile = { countryIso2: ['GB'], roleFamilies: cultivation }
    const signal = routed({ geo_scope: 'region', geo_region: 'Europe', country: 'European Union', role_families: cultivation })
    expect(matchesOperatorProfile(signal, cyprus)).toBe(true)
    expect(matchesOperatorProfile(signal, uk)).toBe(false)
  })

  it('does not widen Middle East to all of Asia or North Africa', () => {
    const egypt: OperatorProfile = { countryIso2: ['EG'], roleFamilies: cultivation }
    const uae: OperatorProfile = { countryIso2: ['AE'], roleFamilies: cultivation }
    const singapore: OperatorProfile = { countryIso2: ['SG'], roleFamilies: cultivation }
    const morocco: OperatorProfile = { countryIso2: ['MA'], roleFamilies: cultivation }
    const signal = routed({ geo_scope: 'region', geo_region: 'Asia', country: 'Middle East', role_families: cultivation })
    expect(matchesOperatorProfile(signal, egypt)).toBe(true)
    expect(matchesOperatorProfile(signal, uae)).toBe(true)
    expect(matchesOperatorProfile(signal, singapore)).toBe(false)
    expect(matchesOperatorProfile(signal, morocco)).toBe(false)
  })

  it('matches Pacific to Oceania without widening globally', () => {
    const australia: OperatorProfile = { countryIso2: ['AU'], roleFamilies: cultivation }
    const japan: OperatorProfile = { countryIso2: ['JP'], roleFamilies: cultivation }
    const signal = routed({ geo_scope: 'region', geo_region: 'Oceania', country: 'Pacific', role_families: cultivation })
    expect(matchesOperatorProfile(signal, australia)).toBe(true)
    expect(matchesOperatorProfile(signal, japan)).toBe(false)
  })

  it.each([
    ['Africa', 'LS', 'DE'],
    ['Americas', 'US', 'DE'],
    ['Asia', 'SG', 'DE'],
    ['Europe', 'DE', 'LS'],
    ['Oceania', 'AU', 'DE'],
  ])('matches the UN macro-region %s exactly', (region, included, excluded) => {
    const signal = routed({ geo_scope: 'region', geo_region: region, role_families: cultivation })
    expect(matchesOperatorProfile(signal, { countryIso2: [included], roleFamilies: cultivation })).toBe(true)
    expect(matchesOperatorProfile(signal, { countryIso2: [excluded], roleFamilies: cultivation })).toBe(false)
  })

  it('fails closed for an unknown retained bloc label', () => {
    const signal = routed({ geo_scope: 'region', geo_region: 'Americas', country: 'Unknown bloc', role_families: cultivation })
    expect(matchesOperatorProfile(signal, { countryIso2: ['US'], roleFamilies: cultivation })).toBe(false)
  })

'''
text = text[:start] + replacement + text[end:]
text = text.replace(
    "Affects Europe, a region you cover (cultivation & production)",
    "Affects Europe, a region or bloc you cover (cultivation & production)",
)
path.write_text(text, encoding='utf-8')
PY

cat > docs/control/REGIONAL_ROUTING_DEFINITIONS.md <<'EOF'
# Regional routing definitions

Status: active internal routing control.

This document controls how a retained regional or bloc label is matched to an
operator's declared ISO-2 countries. It prevents a specific audience such as
LATAM or the European Union from being widened to a broader UN macro-region.

## Data sources

- ISO-2/ISO-3 conversion is generated with pinned `pycountry 24.6.1`.
- Region and subregion values come from Harbourview's checked-in 248-row country
  identity table, derived from the UN M49 classification.
- European Union membership is the official current 27-member list, verified on
  2026-08-02.

## Controlled audience rules

- `Africa`, `Americas`, `Asia`, `Europe`, and `Oceania` match the corresponding
  UN M49 macro-region.
- `LATAM`, `Latin America`, and `Latin America and the Caribbean` match the UN
  M49 Caribbean, Central America, and South America subregions. Northern America
  is excluded.
- `Caribbean` matches only the UN M49 Caribbean subregion.
- `European Union` / `EU` matches the controlled 27-member ISO-2 set. Cyprus is
  included despite its UN M49 placement in Western Asia; the United Kingdom is
  excluded.
- `Middle East` uses Harbourview's explicit operational definition of UN M49
  Western Asia plus Egypt. It does not widen to all Asia or all MENA.
- `Pacific` matches the UN M49 Oceania macro-region.
- An unknown retained bloc label fails closed instead of inheriting a broader
  macro-region.
- An invalid or unmapped operator country does not fail open into every regional
  audience.

Any definition or membership change requires the mapping generator, tests,
control record, and evidence log to change in the same PR.
EOF

cat >> docs/control/EVIDENCE_LOG.md <<'EOF'

## 2026-08-02 — Regional/bloc routing forward fix after PR #1231

- Added a deterministic 248-row ISO-2/ISO-3 bridge generated from pinned
  `pycountry 24.6.1` and the checked-in UN M49-derived identity table.
- Replaced the incomplete 193-country dashboard bridge and removed regional
  fail-open behavior for unmapped country codes.
- Preserved explicit European Union, LATAM, Caribbean, Middle East, Pacific, and
  UN macro-region audience semantics.
- Added regression cases covering Singapore, the US versus Colombia, Barbados
  versus the US, Cyprus versus the UK, Egypt/UAE versus Singapore/Morocco,
  Australia versus Japan, all five UN macro-regions, and unknown-bloc fail-closed
  behavior.
- No production migration, database write, deployment, alias movement, or secret
  access was performed by this forward-fix branch.
- Required evidence: generated-data reproducibility, routing tests, lint,
  typecheck, full tests, production build, public-boundary checks, and the
  PostgreSQL 17 pipeline-hardening migration fixture.
EOF

npm ci
npm run test:signal-routing
npm run lint
npm run typecheck
npm run test
npm run build
npm run test:visibility
npm run test:security
psql -v ON_ERROR_STOP=1 -f tests/sql/pr1224_pipeline_hardening_dry_run.sql
git diff --check

git add lib/signals/routing.ts \
  lib/country-data/generated-iso-region-rows.ts \
  scripts/country-data/generate-iso-region-rows.py \
  tests/signals/routing.test.ts \
  docs/control/REGIONAL_ROUTING_DEFINITIONS.md \
  docs/control/EVIDENCE_LOG.md

git commit -m 'fix: route regional signals by explicit audience definitions'
git push origin HEAD:fix/routing-regional-audiences
