/**
 * Tier-1 authority registry expansion
 * Completes CA / DE / AU / GB packs with full authority rows.
 * Merge into or replace the thin entries in authorityRegistry.ts.
 * Links only — zero clinical claims.
 */

import type { ClinicalAuthorityRecord } from './authorityRegistry'

const strength = 'Primary authority — evidence strength not graded by source' as const
const verified = '2026-08-18'

export const TIER1_AUTHORITY_PACK: ClinicalAuthorityRecord[] = [
  // ---------- CANADA (deep) ----------
  {
    id: 'federal-authority',
    label: 'Authorization framework',
    purpose: 'Current federal authority for health care practitioners under the Cannabis Regulations.',
    jurisdiction: 'Canada',
    countryIso2: 'CA',
    evidenceType: 'regulation',
    evidenceStrength: strength,
    sourceName: 'Justice Laws Website · Cannabis Regulations §272',
    href: 'https://laws-lois.justice.gc.ca/eng/regulations/SOR-2018-144/section-272.html',
    verifiedAt: verified,
  },
  {
    id: 'medical-document',
    label: 'Medical document requirements',
    purpose: 'Required contents and validity of the federal medical document.',
    jurisdiction: 'Canada',
    countryIso2: 'CA',
    evidenceType: 'regulation',
    evidenceStrength: strength,
    sourceName: 'Justice Laws Website · Cannabis Regulations §273',
    href: 'https://laws-lois.justice.gc.ca/eng/regulations/SOR-2018-144/section-273.html',
    verifiedAt: verified,
  },
  {
    id: 'safety-interactions',
    label: 'Safety & interaction guidance',
    purpose: 'Current federal safety, contraindication-like and interaction guidance for cannabis used for medical purposes.',
    jurisdiction: 'Canada',
    countryIso2: 'CA',
    evidenceType: 'safety-guidance',
    evidenceStrength: strength,
    sourceName: 'Health Canada · Cannabis for medical purposes',
    href: 'https://www.canada.ca/en/health-canada/topics/accessing-cannabis-for-medical-purposes/cannabis-medical-purposes.html',
    verifiedAt: verified,
  },
  {
    id: 'pharmacovigilance',
    label: 'Adverse-reaction reporting',
    purpose: 'Current federal health-professional guidance for reporting suspected adverse reactions to cannabis.',
    jurisdiction: 'Canada',
    countryIso2: 'CA',
    evidenceType: 'pharmacovigilance-guidance',
    evidenceStrength: strength,
    sourceName: 'Health Canada · Report a side effect to cannabis: Health care professionals',
    href: 'https://www.canada.ca/en/health-canada/services/drugs-medication/cannabis/recalls-adverse-reactions-reporting/report-side-effects-cannabis-products/health-care-professionals.html',
    verifiedAt: verified,
  },

  // ---------- GERMANY ----------
  {
    id: 'federal-authority',
    label: 'Competent authority (BfArM)',
    purpose: 'Primary medicines and narcotics competent authority context for medical cannabis in Germany.',
    jurisdiction: 'Germany',
    countryIso2: 'DE',
    evidenceType: 'regulation',
    evidenceStrength: strength,
    sourceName: 'BfArM',
    href: 'https://www.bfarm.de/EN/Home/_node.html',
    verifiedAt: verified,
  },
  {
    id: 'medical-document',
    label: 'Prescribing & reimbursement context',
    purpose: 'Medical cannabis within the German medicines/narcotics framework; reimbursement involves G-BA and statutory insurers.',
    jurisdiction: 'Germany',
    countryIso2: 'DE',
    evidenceType: 'federal-guidance',
    evidenceStrength: strength,
    sourceName: 'BfArM / G-BA context',
    href: 'https://www.bfarm.de/EN/Home/_node.html',
    verifiedAt: verified,
  },
  {
    id: 'safety-interactions',
    label: 'Safety & product information',
    purpose: 'Use authorized product information and BfArM safety communications. Harbourview does not provide a structured interaction checker.',
    jurisdiction: 'Germany',
    countryIso2: 'DE',
    evidenceType: 'safety-guidance',
    evidenceStrength: strength,
    sourceName: 'BfArM · Safety',
    href: 'https://www.bfarm.de/EN/Home/_node.html',
    verifiedAt: verified,
  },
  {
    id: 'pharmacovigilance',
    label: 'Adverse-reaction reporting',
    purpose: 'Health-professional pathway for suspected adverse reactions in Germany.',
    jurisdiction: 'Germany',
    countryIso2: 'DE',
    evidenceType: 'pharmacovigilance-guidance',
    evidenceStrength: strength,
    sourceName: 'BfArM / national PV',
    href: 'https://www.bfarm.de/EN/Home/_node.html',
    verifiedAt: verified,
  },

  // ---------- AUSTRALIA ----------
  {
    id: 'federal-authority',
    label: 'Competent authority (TGA / ODC)',
    purpose: 'Primary therapeutic goods and controlled-substance authority for medicinal cannabis.',
    jurisdiction: 'Australia',
    countryIso2: 'AU',
    evidenceType: 'regulation',
    evidenceStrength: strength,
    sourceName: 'TGA · Medicinal cannabis',
    href: 'https://www.tga.gov.au/products/unapproved-therapeutic-goods/medicinal-cannabis',
    verifiedAt: verified,
  },
  {
    id: 'medical-document',
    label: 'SAS / Authorised Prescriber pathways',
    purpose: 'Special Access Scheme and Authorised Prescriber routes; import may require ODC licensing.',
    jurisdiction: 'Australia',
    countryIso2: 'AU',
    evidenceType: 'federal-guidance',
    evidenceStrength: strength,
    sourceName: 'TGA · Medicinal cannabis access',
    href: 'https://www.tga.gov.au/products/unapproved-therapeutic-goods/medicinal-cannabis',
    verifiedAt: verified,
  },
  {
    id: 'safety-interactions',
    label: 'Safety & product information',
    purpose: 'Use TGA-authorised product information. Harbourview does not provide a structured interaction checker.',
    jurisdiction: 'Australia',
    countryIso2: 'AU',
    evidenceType: 'safety-guidance',
    evidenceStrength: strength,
    sourceName: 'TGA',
    href: 'https://www.tga.gov.au/products/unapproved-therapeutic-goods/medicinal-cannabis',
    verifiedAt: verified,
  },
  {
    id: 'pharmacovigilance',
    label: 'Adverse-reaction reporting',
    purpose: 'Health-professional reporting pathway for suspected adverse reactions in Australia.',
    jurisdiction: 'Australia',
    countryIso2: 'AU',
    evidenceType: 'pharmacovigilance-guidance',
    evidenceStrength: strength,
    sourceName: 'TGA · Reporting',
    href: 'https://www.tga.gov.au/safety/reporting-problems',
    verifiedAt: verified,
  },

  // ---------- UNITED KINGDOM ----------
  {
    id: 'federal-authority',
    label: 'Competent authority (MHRA / Home Office)',
    purpose: 'Primary medicines and controlled-drug authority context for CBPMs.',
    jurisdiction: 'United Kingdom',
    countryIso2: 'GB',
    evidenceType: 'regulation',
    evidenceStrength: strength,
    sourceName: 'GOV.UK · Medicinal cannabis',
    href: 'https://www.gov.uk/government/collections/medicinal-cannabis-information-and-resources',
    verifiedAt: verified,
  },
  {
    id: 'medical-document',
    label: 'Specialist CBPM prescribing',
    purpose: 'CBPMs restricted to GMC specialist-register prescribers under current rules.',
    jurisdiction: 'United Kingdom',
    countryIso2: 'GB',
    evidenceType: 'federal-guidance',
    evidenceStrength: strength,
    sourceName: 'MHRA / Home Office guidance',
    href: 'https://www.gov.uk/government/collections/medicinal-cannabis-information-and-resources',
    verifiedAt: verified,
  },
  {
    id: 'safety-interactions',
    label: 'Safety & product information',
    purpose: 'Use authorised product information and MHRA safety communications.',
    jurisdiction: 'United Kingdom',
    countryIso2: 'GB',
    evidenceType: 'safety-guidance',
    evidenceStrength: strength,
    sourceName: 'MHRA',
    href: 'https://www.gov.uk/government/organisations/medicines-and-healthcare-products-regulatory-agency',
    verifiedAt: verified,
  },
  {
    id: 'pharmacovigilance',
    label: 'Adverse-reaction reporting (Yellow Card)',
    purpose: 'Health-professional pathway for suspected adverse reactions in the UK.',
    jurisdiction: 'United Kingdom',
    countryIso2: 'GB',
    evidenceType: 'pharmacovigilance-guidance',
    evidenceStrength: strength,
    sourceName: 'MHRA Yellow Card',
    href: 'https://yellowcard.mhra.gov.uk/',
    verifiedAt: verified,
  },
]
