-- HISTORICAL RECOVERY ARTIFACT
-- Production migration version: 20260925101503
-- Recovered verbatim from production supabase_migrations.schema_migrations.statements.
-- DO NOT REPLAY: archival source only.

create table if not exists public.jurisdiction_data_depth_capture_invocations (
  id uuid primary key default gen_random_uuid(),
  function_name text not null default 'full-depth-authority-capture',
  request_id text,
  worker_version text,
  contract_version text not null default '2026-09-23.v2',
  requested_limit integer not null check (requested_limit between 1 and 25),
  status text not null check (status in ('running','completed','failed')),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  duration_ms integer,
  selected_jobs integer not null default 0,
  claimed_jobs integer not null default 0,
  completed_jobs integer not null default 0,
  needs_review_jobs integer not null default 0,
  blocked_jobs integer not null default 0,
  skipped_jobs integer not null default 0,
  failed_jobs integer not null default 0,
  response_status integer,
  error_code text,
  error_message text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_full_depth_capture_invocations_started
  on public.jurisdiction_data_depth_capture_invocations(started_at desc);

create index if not exists idx_full_depth_capture_invocations_status
  on public.jurisdiction_data_depth_capture_invocations(status, started_at desc);

create table if not exists public.jurisdiction_data_depth_capture_invocation_events (
  id bigint generated by default as identity primary key,
  invocation_id uuid not null references public.jurisdiction_data_depth_capture_invocations(id) on delete cascade,
  job_id uuid references public.jurisdiction_data_depth_capture_jobs(id) on delete set null,
  event_type text not null check (event_type in (
    'invocation_started','jobs_selected','job_claimed','source_selected',
    'snapshot_captured','job_completed','job_needs_review','job_blocked',
    'job_skipped','job_failed','invocation_completed','invocation_failed'
  )),
  jurisdiction_key text,
  dimension_key text,
  status text,
  error_code text,
  error_message text,
  source_registry_id uuid,
  source_snapshot_id uuid,
  occurred_at timestamptz not null default now(),
  duration_ms integer,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_full_depth_capture_invocation_events_invocation
  on public.jurisdiction_data_depth_capture_invocation_events(invocation_id, occurred_at);

create index if not exists idx_full_depth_capture_invocation_events_job
  on public.jurisdiction_data_depth_capture_invocation_events(job_id, occurred_at);

create index if not exists idx_full_depth_capture_invocation_events_type
  on public.jurisdiction_data_depth_capture_invocation_events(event_type, occurred_at desc);

alter table public.jurisdiction_data_depth_capture_invocations enable row level security;
alter table public.jurisdiction_data_depth_capture_invocation_events enable row level security;

drop policy if exists "full depth capture invocations authenticated read" on public.jurisdiction_data_depth_capture_invocations;
create policy "full depth capture invocations authenticated read"
  on public.jurisdiction_data_depth_capture_invocations for select to authenticated using (true);

drop policy if exists "full depth capture invocation events authenticated read" on public.jurisdiction_data_depth_capture_invocation_events;
create policy "full depth capture invocation events authenticated read"
  on public.jurisdiction_data_depth_capture_invocation_events for select to authenticated using (true);

revoke insert, update, delete, truncate on public.jurisdiction_data_depth_capture_invocations from anon, authenticated;
revoke insert, update, delete, truncate on public.jurisdiction_data_depth_capture_invocation_events from anon, authenticated;

comment on table public.jurisdiction_data_depth_capture_invocations is
  'Operational invocation telemetry for full-depth authority capture. Does not imply evidence completeness.';
comment on table public.jurisdiction_data_depth_capture_invocation_events is
  'Per-invocation operational events for full-depth authority capture. Does not imply evidence completeness.';

