-- HISTORICAL RECOVERY ARTIFACT
-- Production migration version: 20260923080456
-- Recovered verbatim from production supabase_migrations.schema_migrations.statements.
-- DO NOT REPLAY: archival source only.

update public.source_registry set source_url='https://www.ncc.gov.gh/cannabis-regulations/',source_name='Narcotics Control Commission Ghana — Cannabis Regulations',tier=1,regulator_class='drug_control_authority',adapter='html_snapshot',is_active=true,crawl_allowed=true,relevance_status='active',next_crawl_at=now(),updated_at=now() where jurisdiction_code='GH' and source_name='Narcotics Control Commission Ghana — Cannabis Regulations';
update public.source_registry set source_url='https://www.gov.il/he/service/cannabis-practice-license',source_name='Israel Ministry of Health — Medical cannabis practice licence',tier=1,regulator_class='drug_control_authority',adapter='html_snapshot',is_active=true,crawl_allowed=true,relevance_status='active',next_crawl_at=now(),updated_at=now() where jurisdiction_code='IL' and source_name='IMCA – Israel Medical Cannabis Agency';
update public.source_registry set source_url='https://www.eof.gr/en/%CE%B1%CE%BD%CE%B1%CE%BA%CE%BF%CE%B9%CE%BD%CF%89%CF%83%CE%B7/',source_name='Greece EOF — Cannabis retail-sale regulatory notice',tier=1,regulator_class='drug_control_authority',adapter='html_snapshot',is_active=true,crawl_allowed=true,relevance_status='active',next_crawl_at=now(),updated_at=now() where jurisdiction_code='GR' and source_name='Greece EOF';
update public.source_registry set source_url='https://medicinesauthority.gov.mt/cannabisformedicinalandresearchpurposes',source_name='Malta Medicines Authority — Cannabis for medicinal and research purposes',tier=1,regulator_class='drug_control_authority',adapter='html_snapshot',is_active=true,crawl_allowed=true,relevance_status='active',next_crawl_at=now(),updated_at=now() where jurisdiction_code='MT' and source_name='Malta Medicines Authority';
update public.source_registry set source_url='https://police.public.lu/fr/legislation/stupefiants.html',source_name='Luxembourg Police — Narcotics legislation and cannabis rules',tier=1,regulator_class='drug_control_authority',adapter='html_snapshot',is_active=true,crawl_allowed=true,relevance_status='active',next_crawl_at=now(),updated_at=now() where jurisdiction_code='LU' and source_name='Legilux Luxembourg';
update public.source_registry set source_url='https://adilet.zan.kz/eng/docs/P2500000797',source_name='Kazakhstan Adilet — Industrial cannabis cultivation requirements',tier=1,regulator_class='drug_control_authority',adapter='html_snapshot',is_active=true,crawl_allowed=true,relevance_status='active',next_crawl_at=now(),updated_at=now() where jurisdiction_code='KZ' and source_name='Kazakhstan Adilet — Government Decree No. 797 industrial cannabis THC requirements';
update public.source_registry set source_url='https://zdravstvo.gov.mk/en-GB/kontakt/cpp-cesto-postavuvani-prasanja',source_name='North Macedonia Ministry of Health — Cannabis cultivation approval',tier=1,regulator_class='drug_control_authority',adapter='html_snapshot',is_active=true,crawl_allowed=true,relevance_status='active',next_crawl_at=now(),updated_at=now() where jurisdiction_code='MK' and source_name='North Macedonia MALMED';
