-- SUPERSEDED. This file's version prefix (20260729000000, later renumbered to
-- 20260729000002 to resolve a collision with platform_optimizations.sql) does
-- not match its actual applied ledger version. The real applied migration is
-- 20260729095416_fix_jurisdiction_playbooks_missing_grant.sql (identical
-- content: grant select on public.jurisdiction_playbooks to anon, authenticated).
-- Retired per docs/control/PENDING_PRODUCTION_MIGRATION_DECISIONS_2026-08-02.md.
-- No-op placeholder -- do not add statements here.
