-- Give public.listings.status the production type, immediately after the table
-- is created and before anything builds a view on it.
--
-- Production types this column as the listing_status enum, defaulting to
-- 'pending_review'. The repository's creator, 20260528033000, builds it as
-- `status text not null default 'draft'`. Neither a CREATE TABLE nor an
-- ALTER ... TYPE for public.listings appears anywhere in
-- supabase_migrations.schema_migrations, so production's shape was established
-- outside recorded history and there is no recorded body to restore.
--
-- The divergence has to be fixed in the schema rather than worked around in
-- consumers, because the last migration in the candidate --
-- 20260804234000_marketplace_exposure_forward_repair.sql -- is generated by the
-- pinned assembler at CI time, is not present in this repository, and rebuilds
-- public.marketplace_listings_public_view with:
--   where status = 'approved'::public.listing_status
-- Zero-state replay fails there with:
--   ERROR: operator does not exist: text = listing_status (SQLSTATE 42883)
-- That file cannot be edited from here, so the column must satisfy it.
--
-- Placed here, not later, specifically to avoid dependent views. An
-- ALTER COLUMN ... TYPE fails outright when a view depends on the column, and
-- capturing and replaying view definitions around the change does not work:
-- pg_get_viewdef bakes the resolved literal type into the stored definition, so
-- a view whose source says `status = 'approved'` is stored as
-- `status = 'approved'::text` and will not replay against a converted column.
-- I implemented that approach first and a local test with nested views
-- reproduced exactly this failure.
--
-- At this point in replay there is no such problem: 20260528033000 is the first
-- migration in the repository to create public.listings, and the only earlier
-- migration that builds a view on it, 20260304001000, is rewritten by the
-- assembler to guard on `to_regclass('public.listings') is not null` and so
-- skips. Every view built after this point is therefore built over the enum and
-- stores a consistent enum comparison.
--
-- Verified compatible with every later consumer in the repository. Three forms
-- appear, and all work against an enum column:
--   status = 'approved'                  -- unknown literal, resolves to enum
--   status::text = 'approved'            -- 20260704160603, 20260709010000, 20260731145108
--   status = 'approved'::listing_status  -- the assembler's generated repair
-- The one form that would break, `status = 'approved'::text`, does not occur.
--
-- Value mapping: production's labels are pending_review, approved, rejected and
-- archived. The repository's text CHECK admits two more, so both are mapped to
-- the production label with the same meaning -- 'draft' to 'pending_review'
-- (production's own default, the same pre-review state) and 'published' to
-- 'approved' (the same publicly-visible state). Any other value must already be
-- a valid label; if one is not, the cast raises rather than silently coercing.
-- No migration inserts into public.listings before this point, so in practice
-- the table is empty here and the mapping is a safety net, not a data change.
--
-- Idempotent: returns immediately if the column is already listing_status.

do $convert_listings_status$
declare
  v_atttypid oid;
  v_views    text;
begin
  if to_regclass('public.listings') is null then
    raise notice 'public.listings not present; skipping status conversion';
    return;
  end if;

  select a.atttypid into v_atttypid
  from pg_attribute a
  where a.attrelid = 'public.listings'::regclass
    and a.attname = 'status'
    and not a.attisdropped;

  if v_atttypid is null then
    raise notice 'public.listings.status not present; skipping conversion';
    return;
  end if;

  if to_regtype('public.listing_status') is null then
    create type public.listing_status as enum (
      'pending_review',
      'approved',
      'rejected',
      'archived'
    );
    raise notice 'created enum public.listing_status';
  end if;

  if v_atttypid = 'public.listing_status'::regtype then
    raise notice 'public.listings.status is already listing_status; nothing to do';
    return;
  end if;

  -- Defensive: this migration is only safe while nothing depends on the column.
  -- If that ever stops being true, say so plainly instead of failing with a
  -- bare Postgres dependency error.
  select string_agg(c.oid::regclass::text, ', ')
    into v_views
  from pg_depend d
  join pg_rewrite r on r.oid = d.objid
  join pg_class c on c.oid = r.ev_class
  where d.refobjid = 'public.listings'::regclass
    and d.refobjsubid = (
      select attnum from pg_attribute
      where attrelid = 'public.listings'::regclass and attname = 'status'
    )
    and c.relkind in ('v', 'm')
    and c.oid <> 'public.listings'::regclass;

  if v_views is not null then
    raise exception
      'cannot convert public.listings.status: view(s) already depend on it (%). '
      'This migration must run before any view is built over the column.', v_views;
  end if;

  -- 20260528033000 adds a text CHECK on this column:
  --   check (status = any (array['draft','pending_review','approved',
  --                              'published','rejected','archived']))
  -- It cannot survive the conversion -- re-checking it against an enum column
  -- raises `operator does not exist: listing_status = text` -- and it is
  -- redundant afterwards, because the enum enforces a stricter domain. It also
  -- admits two labels the enum does not have. Production carries no such
  -- constraint, relying on the enum exactly as this does.
  alter table public.listings drop constraint if exists listings_status_check;

  alter table public.listings alter column status drop default;

  alter table public.listings
    alter column status type public.listing_status
    using (case status::text
             when 'draft' then 'pending_review'
             when 'published' then 'approved'
             else status::text
           end)::public.listing_status;

  alter table public.listings
    alter column status set default 'pending_review'::public.listing_status;

  raise notice 'public.listings.status converted to listing_status';
end
$convert_listings_status$;
