-- Harbourview-direct supply catalog: Canada starter seed (68 SKUs).
-- NOTE: this data was already inserted directly against the live project
-- this session via Supabase migration tooling (see PR description for
-- disclosure). This file exists so repo history matches production data.
-- NOT safe to blindly re-run against an environment where it has already
-- been applied -- there is no natural-key ON CONFLICT guard, so re-running
-- this file twice against the same database will duplicate all 68 rows.
-- Intended as a one-time seed / historical record, consistent with this
-- repo's other seed-style migrations.

insert into public.listings
  (id, category, title, description, product_type, region, price_range, seller_type,
   high_level_specs, status, public_visibility, is_featured, price_amount, price_currency,
   location_country, condition, brand, model, quantity, unit, slug, marketplace_section,
   sold_by_harbourview, sku, stock_qty, lead_time_days, moq, compliance_flags, target_countries,
   created_at, updated_at, listing_type)
values
(gen_random_uuid(),'packaging','Child-Resistant Mylar Pouch — 3.5g (Matte Black)','CR zipper mylar pouch, matte black, opaque, smell-proof. Meets CSA Z76.1 CR standard and Health Canada plain packaging rules.','pouch','north_america','negotiable','distributor','{"size":"3.5g","material":"mylar","finish":"matte black","cr":true}','approved',true,false,0.09,'CAD','CA','new','Harbourview Supply','HV-POUCH-35',1000,'each','cr-mylar-pouch-3-5g-matte-black','packaging',true,'HVP-PCH-035',50000,10,1000,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now(),'supply'),
(gen_random_uuid(),'packaging','Child-Resistant Mylar Pouch — 7g (Matte Black)','CR zipper mylar pouch, matte black, opaque, smell-proof.','pouch','north_america','negotiable','distributor','{"size":"7g","material":"mylar","finish":"matte black","cr":true}','approved',true,false,0.11,'CAD','CA','new','Harbourview Supply','HV-POUCH-7',1000,'each','cr-mylar-pouch-7g-matte-black','packaging',true,'HVP-PCH-007',40000,10,1000,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now(),'supply'),
(gen_random_uuid(),'packaging','Child-Resistant Mylar Pouch — 14g (Matte Black)','CR zipper mylar pouch, matte black, opaque, smell-proof.','pouch','north_america','negotiable','distributor','{"size":"14g","material":"mylar","finish":"matte black","cr":true}','approved',true,false,0.14,'CAD','CA','new','Harbourview Supply','HV-POUCH-14',1000,'each','cr-mylar-pouch-14g-matte-black','packaging',true,'HVP-PCH-014',30000,10,1000,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now(),'supply'),
(gen_random_uuid(),'packaging','Child-Resistant Mylar Pouch — 28g / 1oz (Matte Black)','CR zipper mylar pouch, matte black, opaque, smell-proof. Bulk flower / trim format.','pouch','north_america','negotiable','distributor','{"size":"28g","material":"mylar","finish":"matte black","cr":true}','approved',true,false,0.19,'CAD','CA','new','Harbourview Supply','HV-POUCH-28',1000,'each','cr-mylar-pouch-28g-matte-black','packaging',true,'HVP-PCH-028',20000,10,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now(),'supply'),
(gen_random_uuid(),'packaging','CR Glass Jar — 30mL (3.5g, Matte Black)','Child-resistant glass flower jar, matte black, tamper-evident cap.','jar','north_america','negotiable','distributor','{"size":"30mL","material":"glass","finish":"matte black","cr":true}','approved',true,true,0.85,'CAD','CA','new','Harbourview Supply','HV-JAR-30',1000,'each','cr-glass-jar-30ml-matte-black','packaging',true,'HVP-JAR-030',15000,14,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now(),'supply'),
(gen_random_uuid(),'packaging','CR Glass Jar — 60mL (7g, Matte Black)','Child-resistant glass flower jar, matte black, tamper-evident cap.','jar','north_america','negotiable','distributor','{"size":"60mL","material":"glass","finish":"matte black","cr":true}','approved',true,false,1.05,'CAD','CA','new','Harbourview Supply','HV-JAR-60',1000,'each','cr-glass-jar-60ml-matte-black','packaging',true,'HVP-JAR-060',12000,14,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now(),'supply'),
(gen_random_uuid(),'packaging','CR Pop-Top Plastic Jar — 13 Dram','Child-resistant pop-top plastic jar, opaque, standard dispensary format.','jar','north_america','negotiable','distributor','{"size":"13 dram","material":"plastic","cr":true}','approved',true,false,0.22,'CAD','CA','new','Harbourview Supply','HV-JAR-13D',1000,'each','cr-pop-top-jar-13-dram','packaging',true,'HVP-JAR-13D',25000,10,1000,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now(),'supply'),
(gen_random_uuid(),'packaging','Pre-Roll Tube — 84mm CR Pop-Top (Single)','Child-resistant pop-top tube for single pre-rolls.','pre_roll_tube','north_america','negotiable','distributor','{"length":"84mm","cr":true}','approved',true,false,0.14,'CAD','CA','new','Harbourview Supply','HV-TUBE-84',1000,'each','pre-roll-tube-84mm-cr','packaging',true,'HVP-TUB-084',30000,10,1000,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now(),'supply'),
(gen_random_uuid(),'packaging','Pre-Roll Tube — 116mm CR Pop-Top (King)','Child-resistant pop-top tube for king-size pre-rolls.','pre_roll_tube','north_america','negotiable','distributor','{"length":"116mm","cr":true}','approved',true,false,0.18,'CAD','CA','new','Harbourview Supply','HV-TUBE-116',1000,'each','pre-roll-tube-116mm-cr','packaging',true,'HVP-TUB-116',20000,10,1000,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now(),'supply'),
(gen_random_uuid(),'packaging','Pre-Roll Multi-Pack Box — 5-Count CR Slider','Child-resistant slider box for 5-count pre-roll multipacks.','pre_roll_box','north_america','negotiable','distributor','{"count":5,"cr":true}','approved',true,true,0.55,'CAD','CA','new','Harbourview Supply','HV-BOX-5PK',1000,'each','pre-roll-multipack-box-5ct-cr','packaging',true,'HVP-BOX-5PK',10000,14,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now(),'supply'),
(gen_random_uuid(),'consumables','Unbleached Pre-Roll Cones — 84mm (Bulk)','Pre-rolled unbleached cones with filter tip, bulk case.','cone','north_america','negotiable','distributor','{"length":"84mm","material":"unbleached paper"}','approved',true,false,0.09,'CAD','CA','new','Harbourview Supply','HV-CONE-84',1000,'each','pre-roll-cones-84mm-unbleached','consumables',true,'HVP-CON-084',100000,7,1000,'{}','{CA}',now(),now(),'supply'),
(gen_random_uuid(),'consumables','Unbleached Pre-Roll Cones — 109mm King (Bulk)','Pre-rolled unbleached king-size cones with filter tip, bulk case.','cone','north_america','negotiable','distributor','{"length":"109mm","material":"unbleached paper"}','approved',true,false,0.11,'CAD','CA','new','Harbourview Supply','HV-CONE-109',1000,'each','pre-roll-cones-109mm-king-unbleached','consumables',true,'HVP-CON-109',80000,7,1000,'{}','{CA}',now(),now(),'supply'),
(gen_random_uuid(),'consumables','Rolling Papers — Unbleached Hemp, King Slim (Booklet of 32)','Unbleached hemp rolling papers, king slim size.','papers','north_america','negotiable','distributor','{"size":"king slim","material":"hemp","count":32}','approved',true,false,0.28,'CAD','CA','new','Harbourview Supply','HV-PAPER-KS',1000,'booklet','rolling-papers-unbleached-hemp-king-slim','consumables',true,'HVP-PAP-KS1',20000,7,500,'{}','{CA}',now(),now(),'supply'),
(gen_random_uuid(),'consumables','Organic Pre-Roll Filter Tips (Bulk, per 1000)','Unbleached organic filter tips for pre-roll production.','filter_tip','north_america','negotiable','distributor','{"material":"organic unbleached"}','approved',true,false,0.03,'CAD','CA','new','Harbourview Supply','HV-FILTIP',1000,'each','organic-pre-roll-filter-tips-bulk','consumables',true,'HVP-FIL-001',150000,7,5000,'{}','{CA}',now(),now(),'supply'),
(gen_random_uuid(),'consumables','Humidity Control Packs — 62% RH (Case of 100)','2-way humidity control packs for cured flower and pre-roll freshness.','humidity_pack','north_america','negotiable','distributor','{"rh":"62%"}','approved',true,false,0.35,'CAD','CA','new','Harbourview Supply','HV-HUMID-62',500,'each','humidity-control-packs-62rh','consumables',true,'HVP-HUM-062',10000,10,100,'{}','{CA}',now(),now(),'supply'),
(gen_random_uuid(),'processing_equipment','Twister T2 Pre-Roll Machine (Compact)','Compact automated pre-roll filling machine, entry throughput tier.','pre_roll_machine','north_america','negotiable','distributor','{"throughput":"~250 cones/run","tier":"compact"}','approved',true,true,3200.00,'CAD','CA','new','Twister','T2',5,'unit','twister-t2-pre-roll-machine','processing',true,'HVP-EQP-T2',5,21,1,'{}','{CA}',now(),now(),'equipment'),
(gen_random_uuid(),'processing_equipment','Twister T4 Pre-Roll Machine (Mid-Volume)','Mid-tier automated pre-roll filling machine for growing production lines.','pre_roll_machine','north_america','negotiable','distributor','{"throughput":"~500-1000 cones/run","tier":"mid"}','approved',true,true,6800.00,'CAD','CA','new','Twister','T4',3,'unit','twister-t4-pre-roll-machine','processing',true,'HVP-EQP-T4',3,21,1,'{}','{CA}',now(),now(),'equipment'),
(gen_random_uuid(),'processing_equipment','Twister T6 Pre-Roll Machine (High-Volume)','High-volume automated pre-roll filling machine for commercial operators.','pre_roll_machine','north_america','negotiable','distributor','{"throughput":"high volume","tier":"commercial"}','approved',true,false,14500.00,'CAD','CA','new','Twister','T6',2,'unit','twister-t6-pre-roll-machine','processing',true,'HVP-EQP-T6',2,28,1,'{}','{CA}',now(),now(),'equipment'),
(gen_random_uuid(),'processing_equipment','Industrial Bud Shredder / De-Stemmer','Industrial-grade shredder and de-stemmer for pre-roll production feedstock.','shredder','north_america','negotiable','distributor','{}','approved',true,false,4200.00,'CAD','CA','new','Harbourview Supply','HV-SHRED-1',4,'unit','industrial-bud-shredder-de-stemmer','processing',true,'HVP-EQP-SHR',4,21,1,'{}','{CA}',now(),now(),'equipment'),
(gen_random_uuid(),'processing_equipment','Digital Compliance Scale (0.01g Precision)','Bench-top digital scale for compliant dosing and fill weights.','scale','north_america','negotiable','distributor','{"precision":"0.01g"}','approved',true,false,180.00,'CAD','CA','new','Harbourview Supply','HV-SCALE-1',10,'unit','digital-compliance-scale-0-01g','processing',true,'HVP-EQP-SCL',10,7,1,'{}','{CA}',now(),now(),'equipment')
on conflict do nothing;
