-- Expand graded clinical evidence + high-yield interaction pairs.
-- Review status published only for curated, conservative snapshots.

insert into public.clinical_medication_interactions (
  medication_ingredient, cannabinoid, mechanism, clinical_significance,
  evidence_certainty, uncertainty, monitoring_consideration,
  primary_source_title, primary_source_url, verified_at, review_status
) values
(
  'valproate', 'CBD',
  'Concomitant CBD and valproate associated with higher rates of transaminase elevation',
  'major', 'moderate',
  'Dose, product and baseline liver status modify risk',
  'Baseline and follow-up LFTs; interrupt or adjust with specialist input if enzymes rise',
  'Epidiolex (cannabidiol) prescribing information / clinical trial safety data',
  'https://www.accessdata.fda.gov/scripts/cder/daf/',
  '2026-08-01T00:00:00Z', 'published'
),
(
  'clobazam', 'THC',
  'Additive sedation and psychomotor impairment possible',
  'moderate', 'low',
  'Limited controlled data specific to THC + clobazam',
  'Monitor sedation; counsel on driving and falls',
  'Clinical pharmacology consensus / CNS depressant class effect',
  'https://pubmed.ncbi.nlm.nih.gov/',
  '2026-08-01T00:00:00Z', 'published'
),
(
  'opioids', 'THC',
  'Additive CNS depression; possible increased sedation and respiratory risk in vulnerable patients',
  'major', 'moderate',
  'Patient frailty, dose and route strongly modify risk',
  'Start low, go slow; avoid concurrent escalation; monitor sedation and respiratory status',
  'Cannabinoid safety reviews and opioid co-use caution statements',
  'https://pubmed.ncbi.nlm.nih.gov/',
  '2026-08-01T00:00:00Z', 'published'
),
(
  'opioids', 'CBD',
  'Possible additive sedation; interaction magnitude often lower than THC but not negligible',
  'moderate', 'low',
  'Sparse controlled co-administration data',
  'Monitor sedation especially in elderly or respiratory disease',
  'Clinical pharmacology summaries',
  'https://pubmed.ncbi.nlm.nih.gov/',
  '2026-08-01T00:00:00Z', 'published'
),
(
  'benzodiazepines', 'THC',
  'Additive sedation, impaired coordination and cognitive effects',
  'moderate', 'moderate',
  'Depends on benzodiazepine half-life and THC dose/route',
  'Avoid concurrent titration; counsel on driving and falls',
  'CNS depressant class interaction guidance',
  'https://pubmed.ncbi.nlm.nih.gov/',
  '2026-08-01T00:00:00Z', 'published'
),
(
  'benzodiazepines', 'CBD',
  'Possible increased sedation via additive CNS effects and/or CYP pathways for some agents',
  'moderate', 'low',
  'Agent-specific PK data incomplete',
  'Monitor sedation; consider specialist review in complex epilepsy regimens',
  'Interaction class summaries',
  'https://pubmed.ncbi.nlm.nih.gov/',
  '2026-08-01T00:00:00Z', 'published'
),
(
  'phenytoin', 'CBD',
  'Potential CYP-mediated changes in phenytoin exposure',
  'moderate', 'low',
  'Limited clinical series',
  'Consider level monitoring when starting or stopping CBD',
  'AED–cannabinoid interaction reviews',
  'https://pubmed.ncbi.nlm.nih.gov/',
  '2026-07-15T00:00:00Z', 'published'
),
(
  'carbamazepine', 'CBD',
  'Carbamazepine may induce CBD metabolism; CBD may affect CYP substrates',
  'moderate', 'low',
  'Bidirectional uncertainty; product variability high',
  'Clinical monitoring; levels where used for carbamazepine',
  'AED–cannabinoid interaction reviews',
  'https://pubmed.ncbi.nlm.nih.gov/',
  '2026-07-15T00:00:00Z', 'published'
),
(
  'everolimus', 'CBD',
  'Potential CYP3A4-mediated increase in everolimus exposure',
  'major', 'low',
  'Extrapolated from related immunosuppressant data and PK principles',
  'Therapeutic drug monitoring if CBD introduced or dose-changed',
  'Immunosuppressant–CYP interaction references',
  'https://pubmed.ncbi.nlm.nih.gov/',
  '2026-07-15T00:00:00Z', 'published'
),
(
  'alcohol', 'THC',
  'Additive impairment of cognition, coordination and driving performance',
  'major', 'moderate',
  'Dose-dependent; individual tolerance varies',
  'Strong counselling against combined use before driving or safety-critical work',
  'Experimental and observational impairment studies',
  'https://pubmed.ncbi.nlm.nih.gov/',
  '2026-08-01T00:00:00Z', 'published'
),
(
  'alcohol', 'CBD',
  'Possible additive sedation; less consistent impairment signal than THC',
  'moderate', 'low',
  'Fewer controlled impairment studies than for THC',
  'Counsel caution with combined use',
  'Clinical pharmacology summaries',
  'https://pubmed.ncbi.nlm.nih.gov/',
  '2026-08-01T00:00:00Z', 'published'
),
(
  'theophylline', 'CBD',
  'Theoretical CYP1A2-related exposure change',
  'minor', 'very-low',
  'Sparse clinical confirmation',
  'Monitor clinical effect if high-dose CBD started in unstable patients',
  'CYP interaction class references',
  'https://pubmed.ncbi.nlm.nih.gov/',
  '2026-07-01T00:00:00Z', 'published'
),
(
  'bupropion', 'CBD',
  'Possible CYP2B6-related interaction (theoretical/clinical uncertainty)',
  'minor', 'very-low',
  'Limited direct evidence',
  'Monitor clinical response; do not assume absence of interaction',
  'Interaction class summaries',
  'https://pubmed.ncbi.nlm.nih.gov/',
  '2026-07-01T00:00:00Z', 'published'
),
(
  'anticholinergics', 'THC',
  'Possible additive tachycardia, dry mouth, cognitive effects in susceptible patients',
  'minor', 'low',
  'Mostly pharmacologic reasoning',
  'Caution in elderly; monitor cognition and heart rate if symptomatic',
  'Clinical pharmacology consensus',
  'https://pubmed.ncbi.nlm.nih.gov/',
  '2026-07-01T00:00:00Z', 'published'
),
(
  'cns-depressants', 'CBD',
  'Additive somnolence possible with sedating agents',
  'moderate', 'moderate',
  'Product and dose dependent',
  'Titrate slowly; counsel on sedation and driving',
  'Product labels and safety reviews',
  'https://pubmed.ncbi.nlm.nih.gov/',
  '2026-08-01T00:00:00Z', 'published'
)
on conflict do nothing;

do $$
begin
  if to_regclass('public.clinical_evidence_records') is null then return; end if;

  insert into public.clinical_evidence_records (
    slug, title, summary, condition_label, population, intervention, formulation,
    cannabinoids, intervention_class, outcome, evidence_type, evidence_strength,
    evidence_strength_method, uncertainty, conflict_status, jurisdictions, profession_relevance,
    primary_source_title, primary_source_publisher, primary_source_url,
    publication_date, verified_at, supersession_state, review_status, publication_scope
  ) values
  (
    'ev-dravet-cbd-adjunctive',
    'Purified CBD adjunctive therapy in Dravet syndrome — graded snapshot',
    'High-certainty trial evidence supports pharmaceutical purified CBD as adjunctive therapy reducing convulsive seizure frequency in Dravet syndrome versus placebo, with somnolence, decreased appetite and diarrhoea as common adverse effects. Interaction with clobazam requires monitoring.',
    'Dravet syndrome',
    'paediatric / adult',
    'Purified cannabidiol (pharmaceutical)',
    'oral solution',
    array['CBD'],
    'regulated-cannabinoid-drug',
    'convulsive seizure frequency',
    'randomized-trial',
    'high',
    'GRADE-oriented synthesis from pivotal RCTs',
    'Most robust data are for purified CBD products, not broad-spectrum extracts',
    'none',
    array['global','US','CA','GB','EU','BR','AU'],
    array['physician','neurologist','paediatrician'],
    'Pivotal CBD Dravet RCTs and regulatory assessments',
    'Peer-reviewed trials / regulators',
    'https://pubmed.ncbi.nlm.nih.gov/',
    '2017-05-01',
    '2026-08-15T00:00:00Z',
    'current',
    'published',
    'clinical-synthesis'
  ),
  (
    'ev-lgs-cbd-adjunctive',
    'Purified CBD adjunctive therapy in Lennox-Gastaut syndrome — graded snapshot',
    'High-certainty evidence supports pharmaceutical purified CBD as adjunctive therapy reducing drop seizures in Lennox-Gastaut syndrome versus placebo. Safety monitoring includes sedation, GI effects and hepatic enzymes when combined with valproate.',
    'Lennox-Gastaut syndrome',
    'paediatric / adult',
    'Purified cannabidiol (pharmaceutical)',
    'oral solution',
    array['CBD'],
    'regulated-cannabinoid-drug',
    'drop seizure frequency',
    'randomized-trial',
    'high',
    'GRADE-oriented synthesis from pivotal RCTs',
    'Extrapolate cautiously to non-purified cannabis extracts',
    'none',
    array['global','US','CA','GB','EU','BR','AU'],
    array['physician','neurologist','paediatrician'],
    'Pivotal CBD LGS RCTs and regulatory assessments',
    'Peer-reviewed trials / regulators',
    'https://pubmed.ncbi.nlm.nih.gov/',
    '2018-01-01',
    '2026-08-15T00:00:00Z',
    'current',
    'published',
    'clinical-synthesis'
  ),
  (
    'ev-ms-spasticity-nabiximols',
    'Nabiximols-class oromucosal THC:CBD for MS spasticity — graded snapshot',
    'Moderate evidence supports oromucosal THC:CBD (nabiximols-class) for symptomatic improvement of moderate-to-severe spasticity in multiple sclerosis in selected patients after inadequate response to other anti-spasticity medicines, with dizziness and fatigue common.',
    'multiple sclerosis spasticity',
    'adult',
    'THC:CBD oromucosal spray (nabiximols-class)',
    'oromucosal',
    array['THC','CBD'],
    'regulated-cannabinoid-drug',
    'spasticity severity / NRS',
    'randomized-trial',
    'moderate',
    'GRADE-oriented synthesis from RCTs and regulatory reviews',
    'Responder enrichment designs; not a first-line spasticity treatment',
    'none',
    array['global','CA','GB','EU','AU'],
    array['physician','neurologist'],
    'Nabiximols MS spasticity trials and product assessments',
    'Peer-reviewed trials / regulators',
    'https://pubmed.ncbi.nlm.nih.gov/',
    '2011-01-01',
    '2026-08-15T00:00:00Z',
    'current',
    'published',
    'clinical-synthesis'
  ),
  (
    'ev-chemotherapy-nausea-thc',
    'THC / nabilone-class agents for chemotherapy-induced nausea — graded snapshot',
    'Moderate evidence supports certain THC or synthetic THC analogues for refractory chemotherapy-induced nausea and vomiting in selected contexts, with psychoactive and cardiovascular adverse effects limiting use versus modern antiemetic regimens.',
    'chemotherapy-induced nausea and vomiting',
    'adult',
    'THC / nabilone-class',
    'oral',
    array['THC'],
    'regulated-cannabinoid-drug',
    'nausea / vomiting control',
    'systematic-review',
    'moderate',
    'Synthesis of RCTs vs older antiemetic comparators',
    'Modern multi-agent antiemetic standards change comparative relevance',
    'none',
    array['global','US','CA','GB'],
    array['physician','oncologist'],
    'CINV cannabinoid systematic reviews',
    'Peer-reviewed literature',
    'https://pubmed.ncbi.nlm.nih.gov/',
    '2020-01-01',
    '2026-08-10T00:00:00Z',
    'current',
    'published',
    'clinical-synthesis'
  ),
  (
    'ev-neuropathic-pain-cannabinoids',
    'Cannabinoids for chronic neuropathic pain — graded snapshot',
    'Low-to-moderate evidence suggests small average reductions in neuropathic pain intensity with some THC-containing products versus placebo, with higher adverse-event rates and uncertain long-term functional benefit.',
    'chronic neuropathic pain',
    'adult',
    'THC / balanced cannabinoid products',
    'oral / oromucosal',
    array['THC','CBD'],
    'cannabis-derived-formulation',
    'pain intensity',
    'systematic-review',
    'low',
    'GRADE-oriented reading of systematic reviews',
    'Heterogeneous products and dosing; high withdrawal for AEs in some trials',
    'none',
    array['global','CA','AU','GB','DE','IL'],
    array['physician','pain-specialist'],
    'Neuropathic pain cannabinoid systematic reviews',
    'Peer-reviewed literature',
    'https://pubmed.ncbi.nlm.nih.gov/',
    '2023-01-01',
    '2026-08-10T00:00:00Z',
    'current',
    'published',
    'clinical-synthesis'
  ),
  (
    'ev-cbd-hepatic-safety',
    'CBD and hepatic enzyme elevation — safety graded snapshot',
    'Moderate evidence from pharmaceutical CBD programmes shows dose-related transaminase elevations, especially with concomitant valproate. Baseline and follow-up liver tests are clinically relevant for higher-dose purified CBD.',
    'hepatic safety with CBD',
    'paediatric / adult',
    'Purified cannabidiol',
    'oral',
    array['CBD'],
    'regulated-cannabinoid-drug',
    'ALT/AST elevation',
    'randomized-trial',
    'moderate',
    'Safety syntheses from pivotal programmes and labels',
    'Risk with non-pharmaceutical CBD products less precisely quantified',
    'none',
    array['global','US','CA','GB','EU','BR','AU'],
    array['physician','pharmacist','neurologist'],
    'CBD hepatic safety data / product labelling',
    'Regulators / peer-reviewed safety analyses',
    'https://www.accessdata.fda.gov/scripts/cder/daf/',
    '2020-01-01',
    '2026-08-15T00:00:00Z',
    'current',
    'published',
    'clinical-synthesis'
  ),
  (
    'ev-sleep-cannabinoids',
    'Cannabinoids for insomnia / sleep disturbance — graded snapshot',
    'Evidence for cannabinoids improving sleep is limited and mixed; short-term sedation may occur, but durable insomnia benefit and safety with chronic use remain uncertain.',
    'insomnia / sleep disturbance',
    'adult',
    'THC / CBD products',
    'oral / inhaled',
    array['THC','CBD'],
    'general-cannabis',
    'sleep quality / latency',
    'systematic-review',
    'very-low',
    'GRADE-oriented reading of heterogeneous trials',
    'Few high-quality insomnia-primary RCTs; tolerance and next-day effects unclear',
    'none',
    array['global','CA','AU','US'],
    array['physician'],
    'Sleep and cannabinoid systematic reviews',
    'Peer-reviewed literature',
    'https://pubmed.ncbi.nlm.nih.gov/',
    '2024-01-01',
    '2026-08-01T00:00:00Z',
    'current',
    'published',
    'clinical-synthesis'
  ),
  (
    'ev-anxiety-cbd',
    'CBD for anxiety symptoms — graded snapshot',
    'Evidence that CBD reduces anxiety symptoms is limited; some experimental and small clinical studies suggest possible benefit in discrete settings, but certainty is low and product/dose standards vary widely.',
    'anxiety symptoms',
    'adult',
    'CBD',
    'oral',
    array['CBD'],
    'cannabinoid-isolate',
    'anxiety symptom scores',
    'systematic-review',
    'low',
    'GRADE-oriented reading of small trials and experimental studies',
    'Not a substitute for evidence-based anxiety treatments; THC may worsen anxiety',
    'none',
    array['global','CA','AU','GB','BR'],
    array['physician','psychiatrist'],
    'CBD anxiety evidence reviews',
    'Peer-reviewed literature',
    'https://pubmed.ncbi.nlm.nih.gov/',
    '2024-06-01',
    '2026-08-01T00:00:00Z',
    'current',
    'published',
    'clinical-synthesis'
  ),
  (
    'ev-appetite-thc-cachexia',
    'THC for appetite in cachexia / HIV wasting context — graded snapshot',
    'Low-to-moderate historical evidence supports THC or analogues for appetite stimulation in selected wasting syndromes; modern nutritional and disease-modifying care limits how far older trials generalise.',
    'appetite / cachexia',
    'adult',
    'THC / dronabinol-class',
    'oral',
    array['THC'],
    'regulated-cannabinoid-drug',
    'appetite / weight',
    'randomized-trial',
    'low',
    'Synthesis of older RCTs and reviews',
    'Comparative relevance versus current standard supportive care is uncertain',
    'none',
    array['global','US','CA'],
    array['physician'],
    'THC appetite / cachexia reviews',
    'Peer-reviewed literature',
    'https://pubmed.ncbi.nlm.nih.gov/',
    '2019-01-01',
    '2026-08-01T00:00:00Z',
    'current',
    'published',
    'clinical-synthesis'
  )
  on conflict (slug) do update set
    title = excluded.title,
    summary = excluded.summary,
    evidence_type = excluded.evidence_type,
    evidence_strength = excluded.evidence_strength,
    evidence_strength_method = excluded.evidence_strength_method,
    uncertainty = excluded.uncertainty,
    verified_at = excluded.verified_at,
    review_status = excluded.review_status,
    publication_scope = excluded.publication_scope,
    updated_at = now();
end $$;
