-- Reconstructed from production.
--
-- This file previously contained no DDL. It carried a short comment saying it
-- had been applied directly to production via Supabase MCP and existed only to
-- satisfy local/remote migration history parity, followed by `SELECT 1;`.
--
-- That placeholder satisfied the version-number ledger while executing nothing,
-- so `supabase db reset --local` could not rebuild the schema this migration is
-- supposed to create. The statements below are the verbatim text production
-- ran, read back from supabase_migrations.schema_migrations.statements for
-- version 20260716205117.
--
-- Rewriting this file cannot affect production: 20260716205117 is already recorded
-- in schema_migrations, so `supabase db push` skips it. This is a
-- repository-only repair of replay fidelity.
--
-- Regenerate with: node scripts/reconstruct-stub-migrations.mjs

-- Adds the per-signal analysis layer: what changed, who's affected,
-- deadline if any, recommended action. This is what actually makes a
-- signal commercially useful vs a bare headline -- the gap identified
-- from live screenshots of the Mexico Intel tab (72% confidence next to
-- a vague headline, no synthesis, no "so what").
--
-- Structured as JSONB rather than separate columns for iteration speed;
-- can be normalized into columns later if query patterns demand it.
ALTER TABLE public.signals
  ADD COLUMN IF NOT EXISTS analysis JSONB,
  ADD COLUMN IF NOT EXISTS analysis_generated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS analysis_backend TEXT;

COMMENT ON COLUMN public.signals.analysis IS
  'LLM-generated synthesis: {what_changed, who_is_affected, deadline, recommended_action, confidence_rationale}. Generated by the hv-signal-analysis Edge Function, run over reviewed=true signals lacking analysis. Null means not yet analyzed.';
