-- Research batch 14 of jurisdiction_playbooks: Estonia, Eswatini, Ethiopia, Falkland Islands.
-- Real, sourced content replacing draft stub rows.

INSERT INTO public.source_registry (source_name, source_url, country, iso, region, tier, adapter, crawl_cadence, source_type, notes)
VALUES
  ('MyCannabis — Is Weed Legal in Estonia 2026', 'https://www.mycannabis.com/is-weed-legal-in-estonia/', 'Estonia', 'EE', 'Europe', 2, 'html_snapshot', 'monthly', 'legal_analysis', 'Real 2026 CBD-shop enforcement case, 2026 penalty-softening-without-legalization stance'),
  ('LegalClarity — Is Weed Legal in Estonia', 'https://legalclarity.org/is-weed-legal-in-estonia-recreational-and-medical-laws/', 'Estonia', 'EE', 'Europe', 2, 'html_snapshot', 'quarterly', 'legal_analysis', 'Sept 2022 THC limit update to 0.3% for EU alignment, SAM medical process'),
  ('Prohibition Partners — Estonia Medical Cannabis Legislation', 'https://prohibitionpartners.com/european-cannabis-markets/european-medical-cannabis-legislation-map/estonia/', 'Estonia', 'EE', 'Europe', 2, 'html_snapshot', 'quarterly', 'legal_analysis', 'SAM special-permit unlicensed-medicine process detail'),
  ('CannabisRegulations.ai — Eswatini marijuana', 'https://www.cannabisregulations.ai/country-legality/eswatini-marijuana', 'Eswatini', 'SZ', 'Africa', 2, 'html_snapshot', 'quarterly', 'legal_analysis', '1922 Opium Act, 1929 Pharmacy Act, penalty structure'),
  ('High Times — Eswatini Introduces Medical Cannabis Legislation', 'https://hightimes.com/news/african-county-of-eswatini-introduces-medical-cannabis-legislation/', 'Eswatini', 'SZ', 'Africa', 2, 'html_snapshot', 'monthly', 'trade_press', '2020 bill tabled, resurfaced May 2023, 3/4 supermajority requirement, MRA structure'),
  ('Sensi Seeds — Cannabis in Eswatini', 'https://sensiseeds.com/en/blog/countries/cannabis-in-eswatini-laws-use-history/', 'Eswatini', 'SZ', 'Africa', 2, 'html_snapshot', 'quarterly', 'reference', 'PSIQ 2019 exclusive export license detail'),
  ('Reuters — Swaziland cannabis farmers fear businesses could go up in smoke', 'https://reuters.screenocean.com/record/1418191', 'Eswatini', 'SZ', 'Africa', 1, 'html_snapshot', 'quarterly', 'news', 'Real 2019 case: Profile Solutions Inc. 10-year export license alongside ongoing small-farmer prosecution'),
  ('Leafwell — Is Marijuana Legal in Ethiopia', 'https://leafwell.com/blog/is-marijuana-legal-in-ethiopia', 'Ethiopia', 'ET', 'Africa', 2, 'html_snapshot', 'quarterly', 'legal_analysis', 'Border enforcement, Shashamane Rastafarian informal tolerance, 2019 field destruction'),
  ('AllAboutEthio — Everything About Cannabis in Ethiopia (May 2026)', 'https://allaboutethio.com/everything-about-cannabis-in-ethiopia-laws-price-and-quality.html', 'Ethiopia', 'ET', 'Africa', 2, 'html_snapshot', 'monthly', 'legal_analysis', 'Tiered penalty structure: 6mo simple possession vs 10yr growing/selling'),
  ('Leafwell — Is Marijuana Legal in the Falkland Islands', 'https://leafwell.com/blog/is-marijuana-legal-in-the-falkland-islands', 'Falkland Islands', 'FK', 'South America (UK Overseas Territory)', 2, 'html_snapshot', 'quarterly', 'legal_analysis', 'Misuse of Drugs Ordinance 1987 detail, cannabis-specific reduced penalty tier, 2022 CBD exception (1mg THC/component)'),
  ('MercoPress — Falklands approves CBD importation/sale (official ExCo decision)', 'https://en.mercopress.com/2022/07/28/falklands-approves-importation-possession-use-and-sale-of-cannabidiol-cbd', 'Falkland Islands', 'FK', 'South America (UK Overseas Territory)', 1, 'html_snapshot', 'quarterly', 'government_official', 'Official Executive Council 2022 CBD legalization decision')
ON CONFLICT DO NOTHING;

UPDATE public.jurisdiction_playbooks SET
  difficulty = 'high', typical_timeline_months = 18,
  estimated_cost_range = 'Industrial hemp cultivation requires a government license, EU-certified seed, and agricultural-authority registration (standard EU hemp-farming compliance costs, no unusual barrier). Medical cannabis access runs through a case-by-case State Agency of Medicines (SAM) special-permit process for unlicensed medicine — not a commercial licensing pathway.',
  legal_framework_summary = 'Recreational cannabis is illegal in Estonia under the Narcotic Drugs and Psychotropic Substances and Precursors Act, with possession of up to 7.5 grams treated as a misdemeanor (fine up to EUR 1,200 or detention up to 30 days) and larger quantities, sale, or trafficking prosecuted as a criminal offense under Penal Code Section 184 (1-10 years, up to 15 for aggravated trafficking). Medical cannabis has technically been available since 2005 but has no broad program: a specialist doctor must justify use after exhausting licensed treatments, and the application goes through the State Agency of Medicines (SAM) as an unlicensed-medicine special permit — an onerous, case-by-case process most pharmacies rarely handle. Industrial hemp cultivation is legal under government license using EU-certified seed, with the THC limit updated in September 2022 to 0.3% to align with new EU guidelines; hemp-derived CBD products are legal as cosmetics or "technical" goods but ingestible CBD sits in an EU Novel Food gray zone with no clear domestic authorization. Enforcement of the hemp/THC boundary is active: in one documented case, testing of products seized from six CBD shops found many exceeding the legal THC limit, leading to criminal proceedings. Senior officials have repeatedly ruled out broader legalization even while considering softer treatment-focused penalties for users.',
  steps = '[{"step":"Industrial hemp/CBD route","detail":"Obtain a government cultivation license using EU-certified seed; keep THC at or below 0.3%; market CBD as cosmetic/technical product given ingestible CBD''s unresolved EU Novel Food status"},{"step":"Medical cannabis route (narrow)","detail":"A specialist doctor must justify a case-by-case special permit application through the State Agency of Medicines (SAM) after exhausting licensed treatment options; this is not a scalable commercial channel"}]'::jsonb,
  key_regulators = '["Police and Border Guard Board (PPA) — enforcement","Prosecutor''s Office (Riigiprokuratuur)","Ministry of Social Affairs — drug policy","State Agency of Medicines (SAM) — medical cannabis special permits"]'::jsonb,
  common_pitfalls = ARRAY[
    'Assuming decriminalized possession signals a functioning medical cannabis market — the SAM special-permit process is onerous, case-by-case, and most pharmacies have little experience handling it',
    'Assuming ingestible CBD is clearly legal because cosmetic CBD is — ingestible products remain in an EU Novel Food authorization gray zone with no clear domestic green light',
    'Underestimating THC-limit enforcement — a documented case saw multiple CBD shops face criminal proceedings after products tested over the legal limit'
  ],
  status = 'published', last_reviewed = CURRENT_DATE,
  confidence_label = 'high — extensively corroborated across multiple 2026-dated legal-analysis sources with consistent statutory citation and a specific documented enforcement case',
  last_verified_at = now(),
  source_id = (SELECT id FROM public.source_registry WHERE source_url = 'https://www.mycannabis.com/is-weed-legal-in-estonia/')
WHERE country_iso2 = 'EE';

UPDATE public.jurisdiction_playbooks SET
  difficulty = 'very_high', typical_timeline_months = 24,
  estimated_cost_range = 'General cultivation/possession/sale carries no legal cost basis (illegal). A narrow existing licensed-export channel has been granted to select companies (e.g., a 2019 exclusive license to PSIQ, a separate 10-year license to Profile Solutions Inc.) under conditions including strict GMP global health standards — terms not standardized or open to ordinary applicants. A broader medical-legalization bill (tabled 2020, resurfaced 2023) proposes a new Medicines Regulatory Authority but requires a 3/4 supermajority in both the House of Assembly and Senate and has not been confirmed passed.',
  legal_framework_summary = 'Cannabis (locally insangu or dagga) is illegal in Eswatini under the Opium and Habit-Forming Drugs Act 1922 and Pharmacy Act 1929/1992 amendment, with simple possession carrying up to 5 years and sale/trafficking/cultivation for sale up to 15 years plus fines up to EUR/€15,000. Despite this, Eswatini is among the world''s largest per-capita illicit cannabis producers, driven by the globally sought-after "Swazi Gold" landrace strain grown in the Hhohho and Lubombo regions, much of which is trafficked into South Africa despite illegality on both sides of the border. Genuinely complicating the picture: select companies have already been granted narrow cultivation/export licenses under executive authority predating any general reform — a 2019 exclusive license to PSIQ and a separate 10-year license to Florida-based Profile Solutions Inc. — even as small-scale local farmers continue to be prosecuted and have crops destroyed under the general prohibition. A broader medical cannabis legalization bill, first tabled by the Ministry of Health in 2020 and resurfaced in May 2023, would establish a Medicines Regulatory Authority with import/export/wholesale powers, but requires a three-fourths vote in both the House of Assembly and Senate, and no source confirms it has passed as of the most recent reporting. Local growers and the Eswatini Cannabis Association have criticized the bill as favoring large companies over the small farmers who currently sustain their families through illicit cultivation.',
  steps = '[{"step":"General cultivation/sale — do not attempt","detail":"Remains illegal and actively prosecuted for anyone without an existing executive-granted license"},{"step":"Existing narrow executive-license precedent","detail":"At least two companies (PSIQ, Profile Solutions Inc.) have obtained cultivation/export licenses under direct government/executive authorization predating general legalization — precedent exists but terms are not standardized or publicly open"},{"step":"Monitor the pending medical legalization bill","detail":"Track whether the Ministry of Health bill (tabled 2020, resurfaced 2023) achieves the required 3/4 supermajority in both legislative houses; the proposed Medicines Regulatory Authority would centralize import/export/wholesale licensing"}]'::jsonb,
  key_regulators = '["Royal Eswatini Police Service","Eswatini Revenue Service Customs (King Mswati III Intl Airport, Matsapha Airport)","Ministry of Health (proposed Medicines Regulatory Authority under pending bill)"]'::jsonb,
  common_pitfalls = ARRAY[
    'Assuming existing export licenses (PSIQ, Profile Solutions Inc.) reflect an open, general licensing regime — these were granted under narrow executive authority ahead of any general legal reform, and ordinary applicants have no clear standardized pathway',
    'Assuming the pending Ministry of Health bill has passed — it requires a 3/4 supermajority in both legislative houses and no source confirms enactment as of the latest reporting',
    'Overlooking the domestic political economy risk — local farmers and the Eswatini Cannabis Association have organized opposition to the bill''s current structure, viewing it as favoring large companies over smallholder growers who currently sustain the illicit trade'
  ],
  status = 'published', last_reviewed = CURRENT_DATE,
  confidence_label = 'high — well corroborated across Wikipedia, Sensi Seeds, Reuters, High Times, and Semafor Africa, with real documented licensee examples on both the narrow-export and general-prohibition sides',
  last_verified_at = now(),
  source_id = (SELECT id FROM public.source_registry WHERE source_url = 'https://www.cannabisregulations.ai/country-legality/eswatini-marijuana')
WHERE country_iso2 = 'SZ';

UPDATE public.jurisdiction_playbooks SET
  difficulty = 'very_high', typical_timeline_months = 0,
  estimated_cost_range = 'Not applicable — no legal market-entry pathway exists',
  legal_framework_summary = 'Cannabis is illegal in Ethiopia for both medical and recreational use under the Ethiopian Criminal Code, enforced by the Ethiopian Federal Police Counter-Narcotic Division and regulated alongside other substances by the Ethiopian Food and Drug Administration and Control Authority. Penalties are tiered: simple possession carries up to roughly 6 months imprisonment, while growing, transporting, selling, or storing cannabis carries up to 10 years imprisonment and a fine of approximately $3,334. CBD products are equally illegal as a cannabis derivative. Ethiopian police actively monitor borders and points of entry, and cannabis seeds cannot be sent via mail. Despite the legal framework, enforcement varies by location: in Shashamane — a town with deep historical ties to the Rastafari movement — local law enforcement reportedly tolerates personal cannabis use informally, though this is not a legal exemption and Shashamane remains subject to the same national law as the rest of the country; cultivation enforcement is not similarly relaxed, as evidenced by a 2019 police operation destroying 17 acres of marijuana fields nationwide, including in Shashamane. A 2019 industry report estimated Ethiopia''s cannabis market could be worth up to $9.8-10 billion if legalized, with an estimated 7.1 million domestic users, but the government has shown no indication of pursuing reform.',
  steps = '[]'::jsonb,
  key_regulators = '["Ethiopian Federal Police Counter-Narcotic Division","Ethiopian Food and Drug Administration and Control Authority"]'::jsonb,
  common_pitfalls = ARRAY[
    'Assuming Shashamane''s informal tolerance of personal Rastafarian cannabis use constitutes a legal exemption — it does not; the town remains subject to the same national prohibition, and cultivation enforcement (including field destruction) still occurs there',
    'Assuming CBD is treated separately from THC-containing cannabis — Ethiopian law makes no such distinction, and CBD products are equally illegal',
    'Assuming the large estimated market value ($9.8-10 billion) signals imminent government interest in legalization — no legislative movement has been reported despite years of industry reports highlighting the economic opportunity'
  ],
  status = 'published', last_reviewed = CURRENT_DATE,
  confidence_label = 'high — consistently corroborated across multiple independent legal-analysis sources, including a May 2026-dated source confirming the tiered penalty structure remains current',
  last_verified_at = now(),
  source_id = (SELECT id FROM public.source_registry WHERE source_url = 'https://leafwell.com/blog/is-marijuana-legal-in-ethiopia')
WHERE country_iso2 = 'ET';

UPDATE public.jurisdiction_playbooks SET
  difficulty = 'moderate', typical_timeline_months = 12,
  estimated_cost_range = 'CBD retail entry: standard business registration plus compliance with English/Spanish bilingual labeling requirements for products containing no more than 1mg THC per component part. No commercial cultivation or medical cannabis licensing pathway exists — the Governor/Chief Medical Officer license mechanism under Section 7 is narrow and has not been used to establish a general market.',
  legal_framework_summary = 'Cannabis is illegal in the Falkland Islands for both medical and recreational use under the Misuse of Drugs Ordinance 1987, which does not distinguish between the two — importation, exportation, production, supply, possession, and cultivation are all prohibited regardless of purpose, and there is no medical marijuana program comparable to the UK''s. Cannabis is classified as a Class B drug, but the territory''s government has specifically reduced cannabis-specific penalties below the general Class B tier: importation/exportation carries up to 7 years imprisonment and a fine up to £25,000 (versus 14 years/£125,000 for other Class B drugs), reflecting a deliberate cannabis-specific mitigation within an otherwise strict ordinance. Section 7 allows the Governor or Chief Medical Officer to license specific activities (e.g., authorized medical research/prescription) as lawful, but this exception is narrow and has not produced a functioning patient-access system. In July 2022, the Executive Council approved a specific exception legalizing the importation, possession, use, and retail sale of CBD products containing no more than 1 milligram of THC per component part, provided products are in original packaging with English/Spanish labeling — bringing the territory''s CBD access roughly in line with the UK''s.',
  steps = '[{"step":"CBD retail route","detail":"Source or sell CBD products containing no more than 1mg THC per component part, in original packaging with English and/or Spanish labeling, per the 2022 Executive Council exception"},{"step":"Do not plan around cultivation or medical cannabis","detail":"Section 6 bans cultivation of any Cannabis genus plant (including hemp) except under rare Governor/Minister of Health authorization; no general licensing pathway exists"}]'::jsonb,
  key_regulators = '["Falkland Islands Governor / Chief Medical Officer (Section 7 licensing authority)","Royal Falkland Islands Police","Executive Council of the Falkland Islands (CBD exception policy)"]'::jsonb,
  common_pitfalls = ARRAY[
    'Assuming UK medical cannabis legality extends to the Falkland Islands — it is a separate British Overseas Territory with its own ordinance, and no medical marijuana program exists locally',
    'Assuming any hemp cultivation is permitted — Section 6''s ban on "any plant of the genus Cannabis" explicitly includes hemp, with cultivation authorization reserved for rare Governor/Minister of Health cases',
    'Selling CBD products exceeding the 1mg-THC-per-component-part threshold or lacking the required English/Spanish labeling — these fall outside the narrow 2022 exception and remain fully illegal'
  ],
  status = 'published', last_reviewed = CURRENT_DATE,
  confidence_label = 'high — corroborated directly by an official Falkland Islands Executive Council announcement (via MercoPress) plus independent legal-analysis detail on the ordinance''s cannabis-specific penalty structure',
  last_verified_at = now(),
  source_id = (SELECT id FROM public.source_registry WHERE source_url = 'https://en.mercopress.com/2022/07/28/falklands-approves-importation-possession-use-and-sale-of-cannabidiol-cbd')
WHERE country_iso2 = 'FK';

UPDATE public.jurisdiction_playbooks_research_queue
SET playbook_status = 'published', last_researched_at = now(), last_researched_by = 'claude-agent'
WHERE country_code IN ('EE','SZ','ET','FK');
