-- Historical migration marker.
--
-- Production records version 20260607130000 with zero statements because the
-- original Cultivar Passport Network draft never applied successfully. The
-- corrected and complete schema is owned by the forward-fix migration:
--
--   20260621220513_cultivar_passport_network_p0_synfix.sql
--
-- Keeping this version as an intentional no-op reproduces production migration
-- history and prevents duplicate enum, table, policy, view, and storage objects
-- during deterministic zero-state replay.
