-- Backfill public.source_registry.category before the assembler-generated
-- source intake separation copies it into a NOT NULL column.
--
-- 20260804235000_separate_marketplace_source_intake.sql -- generated by the
-- pinned assembler at CI time, not present in this repository -- fails during
-- zero-state replay at its 33rd statement:
--   ERROR: null value in column "source_type" of relation
--   "marketplace_source_registry" violates not-null constraint (SQLSTATE 23502)
-- It copies legacy rows with:
--   insert into public.marketplace_source_registry
--     (id, source_name, source_type, source_url, category_focus, fetch_method, ...)
--   select id, name, category, source_url, category, 'manual_url', ...
--   from public.source_registry
-- so a NULL source_registry.category lands in a NOT NULL source_type.
--
-- This path exists only in replay. The copy is guarded on source_registry
-- having a `source_key` column, and production's source_registry does not have
-- one -- its columns are source_name/jurisdiction/tier/adapter/... with no
-- source_key, no category and no name -- so the block is skipped there
-- entirely and production's marketplace_source_registry is never populated
-- this way. The repository's source_registry is a different table that does
-- have source_key, so the block fires and meets rows the regulatory sources
-- engine seeded without a category.
--
-- The assembler's migration cannot be edited from here, so the data has to
-- satisfy it.
--
-- The fill value is derived from the table rather than hardcoded. The original
-- creator, 20260303000000, declares
--   category text not null check (category in ('used-surplus'))
-- and rows now exist with a NULL category, so something later relaxed that
-- column; whether the CHECK survived is not knowable from the repository alone.
-- Reusing the table's own most common existing category is therefore guaranteed
-- to satisfy whatever constraint is actually in force, where any literal I
-- picked might not. 'used-surplus' is the fallback only when no non-null value
-- exists at all, because it is the one value the original CHECK admits.
--
-- Only category is touched. source_name is nullable in the destination -- the
-- failing row carried a null there without error -- so name is left exactly as
-- it is rather than inventing values for it.
--
-- Idempotent: matches nothing once no NULL category remains.

do $backfill_source_registry_category$
declare
  v_fallback text;
  v_updated  integer;
begin
  if to_regclass('public.source_registry') is null then
    raise notice 'public.source_registry not present; nothing to backfill';
    return;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'source_registry'
      and column_name = 'category'
  ) then
    raise notice 'public.source_registry has no category column; nothing to backfill';
    return;
  end if;

  execute $q$
    select category
    from public.source_registry
    where category is not null
    group by category
    order by count(*) desc, category
    limit 1
  $q$ into v_fallback;

  if v_fallback is null then
    v_fallback := 'used-surplus';
  end if;

  execute format(
    'update public.source_registry set category = %L where category is null',
    v_fallback
  );
  get diagnostics v_updated = row_count;

  if v_updated > 0 then
    raise notice 'backfilled % source_registry row(s) with category %', v_updated, v_fallback;
  else
    raise notice 'no null source_registry.category rows; nothing to backfill';
  end if;
end
$backfill_source_registry_category$;
