-- Full regulatory-tier coverage for every country on the globe.
--
-- Goal: every countries.iso_alpha2 row that has a renderable plate receives a
-- reviewed regulatory_tier (no nulls left for the heatmap). Subnational rows
-- already seeded (US/CA/AU/DE) remain; this migration only touches country ISO2.
--
-- Uses api.set_regulatory_tier so origin=override, needs_review=false, and the
-- audit trail stays canonical. Idempotent: skips rows that already match.
--
-- Tier meanings (legend):
--   legal_commercial_access — lawful cross-border commercial pathway
--   medical_limited_trade   — lawful medical; narrow/no commercial cross-border
--   domestic_only           — legal internally; no lawful cross-border commercial
--   cbd_hemp_only            — hemp/CBD only; cannabis otherwise restricted
--   prohibited              — no lawful commercial pathway
--
-- Assignments reflect public regulatory posture as of 2026-08 (reviewed seed).
-- Future reclassify_auto_tiers will not overwrite these overrides.

do $$
declare
  r record;
begin
  for r in
    select *
    from (values
      ('AD', 'prohibited', 'Andorra: restricted'),
      ('AE', 'prohibited', 'United Arab Emirates: prohibited'),
      ('AF', 'prohibited', 'Afghanistan: prohibited'),
      ('AG', 'prohibited', 'Antigua and Barbuda: prohibited'),
      ('AL', 'prohibited', 'Albania: restricted'),
      ('AM', 'prohibited', 'Armenia: prohibited'),
      ('AO', 'prohibited', 'Angola: prohibited'),
      ('AR', 'medical_limited_trade', 'Argentina: medical'),
      ('AS', 'prohibited', 'American Samoa: prohibited'),
      ('AT', 'medical_limited_trade', 'Austria: medical'),
      ('AU', 'medical_limited_trade', 'Australia: medical national; adult-use limited (ACT)'),
      ('AW', 'prohibited', 'Aruba: prohibited'),
      ('AX', 'medical_limited_trade', 'Åland: follows FI'),
      ('AZ', 'prohibited', 'Azerbaijan: prohibited'),
      ('BA', 'prohibited', 'Bosnia and Herzegovina: restricted'),
      ('BB', 'medical_limited_trade', 'Barbados: medical pathway'),
      ('BD', 'prohibited', 'Bangladesh: prohibited'),
      ('BE', 'medical_limited_trade', 'Belgium: medical'),
      ('BF', 'prohibited', 'Burkina Faso: prohibited'),
      ('BG', 'medical_limited_trade', 'Bulgaria: medical'),
      ('BH', 'prohibited', 'Bahrain: prohibited'),
      ('BI', 'prohibited', 'Burundi: prohibited'),
      ('BJ', 'prohibited', 'Benin: prohibited'),
      ('BN', 'prohibited', 'Brunei: prohibited'),
      ('BO', 'prohibited', 'Bolivia: prohibited'),
      ('BR', 'medical_limited_trade', 'Brazil: medical (ANVISA); no adult-use commercial'),
      ('BS', 'prohibited', 'Bahamas: prohibited'),
      ('BT', 'prohibited', 'Bhutan: prohibited'),
      ('BV', 'prohibited', 'Bouvet Island: restricted'),
      ('BW', 'prohibited', 'Botswana: prohibited'),
      ('BY', 'prohibited', 'Belarus: prohibited'),
      ('BZ', 'prohibited', 'Belize: prohibited'),
      ('CA', 'legal_commercial_access', 'Canada: national commercial adult-use + medical market with export pathways'),
      ('CD', 'prohibited', 'DR Congo: prohibited'),
      ('CF', 'prohibited', 'Central African Republic: prohibited'),
      ('CG', 'prohibited', 'Congo: prohibited'),
      ('CH', 'medical_limited_trade', 'Switzerland: medical + pilots'),
      ('CI', 'prohibited', 'Côte d''Ivoire: prohibited'),
      ('CL', 'medical_limited_trade', 'Chile: medical'),
      ('CM', 'prohibited', 'Cameroon: prohibited'),
      ('CN', 'prohibited', 'China: prohibited (industrial hemp separate)'),
      ('CO', 'medical_limited_trade', 'Colombia: medical + licensed export pathways (limited commercial)'),
      ('CR', 'cbd_hemp_only', 'Costa Rica: hemp/CBD pathway'),
      ('CU', 'prohibited', 'Cuba: prohibited'),
      ('CV', 'prohibited', 'Cabo Verde: prohibited'),
      ('CW', 'prohibited', 'Curaçao: prohibited'),
      ('CY', 'medical_limited_trade', 'Cyprus: medical'),
      ('CZ', 'domestic_only', 'Czech Republic: adult personal legal 2026; no commercial retail'),
      ('DE', 'medical_limited_trade', 'Germany: CanG adult personal + medical; commercial pillar limited'),
      ('DJ', 'prohibited', 'Djibouti: prohibited'),
      ('DK', 'medical_limited_trade', 'Denmark: medical'),
      ('DM', 'prohibited', 'Dominica: prohibited'),
      ('DO', 'prohibited', 'Dominican Republic: prohibited'),
      ('DZ', 'prohibited', 'Algeria: prohibited'),
      ('EC', 'cbd_hemp_only', 'Ecuador: hemp/CBD'),
      ('EE', 'medical_limited_trade', 'Estonia: medical'),
      ('EG', 'prohibited', 'Egypt: prohibited'),
      ('EH', 'prohibited', 'Western Sahara: prohibited'),
      ('ER', 'prohibited', 'Eritrea: prohibited'),
      ('ES', 'domestic_only', 'Spain: private/clubs; no full commercial cross-border'),
      ('ET', 'prohibited', 'Ethiopia: prohibited'),
      ('FI', 'medical_limited_trade', 'Finland: medical'),
      ('FJ', 'prohibited', 'Fiji: prohibited'),
      ('FK', 'prohibited', 'Falkland Islands: prohibited'),
      ('FM', 'prohibited', 'Micronesia: prohibited'),
      ('FO', 'prohibited', 'Faroe Islands: restricted'),
      ('FR', 'medical_limited_trade', 'France: medical pilots/controls'),
      ('GA', 'prohibited', 'Gabon: prohibited'),
      ('GB', 'medical_limited_trade', 'United Kingdom: specialist medical only'),
      ('GD', 'prohibited', 'Grenada: prohibited'),
      ('GE', 'cbd_hemp_only', 'Georgia: limited'),
      ('GF', 'medical_limited_trade', 'French Guiana: follows FR medical'),
      ('GH', 'cbd_hemp_only', 'Ghana: hemp limited'),
      ('GL', 'prohibited', 'Greenland: restricted'),
      ('GM', 'prohibited', 'Gambia: prohibited'),
      ('GN', 'prohibited', 'Guinea: prohibited'),
      ('GQ', 'prohibited', 'Equatorial Guinea: prohibited'),
      ('GR', 'medical_limited_trade', 'Greece: medical'),
      ('GS', 'prohibited', 'South Georgia: restricted'),
      ('GT', 'prohibited', 'Guatemala: prohibited'),
      ('GU', 'domestic_only', 'Guam: territorial adult-use under federal constraints'),
      ('GW', 'prohibited', 'Guinea-Bissau: prohibited'),
      ('GY', 'prohibited', 'Guyana: prohibited'),
      ('HK', 'prohibited', 'Hong Kong: prohibited'),
      ('HM', 'prohibited', 'Heard Island: N/A restricted'),
      ('HN', 'prohibited', 'Honduras: prohibited'),
      ('HR', 'medical_limited_trade', 'Croatia: medical'),
      ('HT', 'prohibited', 'Haiti: prohibited'),
      ('HU', 'medical_limited_trade', 'Hungary: medical'),
      ('ID', 'prohibited', 'Indonesia: prohibited'),
      ('IE', 'medical_limited_trade', 'Ireland: medical'),
      ('IL', 'legal_commercial_access', 'Israel: medical commercial + export pathways'),
      ('IM', 'medical_limited_trade', 'Isle of Man: medical'),
      ('IN', 'cbd_hemp_only', 'India: NDPS restricted; limited medical/hemp'),
      ('IO', 'prohibited', 'British Indian Ocean Territory: restricted'),
      ('IQ', 'prohibited', 'Iraq: prohibited'),
      ('IR', 'prohibited', 'Iran: prohibited'),
      ('IS', 'medical_limited_trade', 'Iceland: medical'),
      ('IT', 'medical_limited_trade', 'Italy: medical'),
      ('JE', 'medical_limited_trade', 'Jersey: medical'),
      ('JM', 'medical_limited_trade', 'Jamaica: medical + limited commercial'),
      ('JO', 'prohibited', 'Jordan: prohibited'),
      ('JP', 'medical_limited_trade', 'Japan: medical limited'),
      ('KE', 'cbd_hemp_only', 'Kenya: hemp limited'),
      ('KG', 'prohibited', 'Kyrgyzstan: prohibited'),
      ('KH', 'prohibited', 'Cambodia: prohibited'),
      ('KI', 'prohibited', 'Kiribati: prohibited'),
      ('KM', 'prohibited', 'Comoros: prohibited'),
      ('KN', 'prohibited', 'Saint Kitts and Nevis: prohibited'),
      ('KP', 'prohibited', 'North Korea: prohibited'),
      ('KR', 'medical_limited_trade', 'South Korea: medical limited'),
      ('KW', 'prohibited', 'Kuwait: prohibited'),
      ('KY', 'prohibited', 'Cayman Islands: restricted'),
      ('KZ', 'prohibited', 'Kazakhstan: prohibited'),
      ('LA', 'prohibited', 'Laos: prohibited'),
      ('LB', 'prohibited', 'Lebanon: prohibited'),
      ('LC', 'prohibited', 'Saint Lucia: prohibited'),
      ('LI', 'prohibited', 'Liechtenstein: restricted'),
      ('LK', 'medical_limited_trade', 'Sri Lanka: medical limited'),
      ('LR', 'prohibited', 'Liberia: prohibited'),
      ('LS', 'prohibited', 'Lesotho: medical/export limited → treat as limited'),
      ('LT', 'medical_limited_trade', 'Lithuania: medical'),
      ('LU', 'legal_commercial_access', 'Luxembourg: lawful pathway with commercial elements'),
      ('LV', 'medical_limited_trade', 'Latvia: medical'),
      ('LY', 'prohibited', 'Libya: prohibited'),
      ('MA', 'cbd_hemp_only', 'Morocco: hemp/traditional limited'),
      ('MD', 'prohibited', 'Moldova: restricted'),
      ('ME', 'prohibited', 'Montenegro: restricted'),
      ('MG', 'prohibited', 'Madagascar: prohibited'),
      ('MH', 'prohibited', 'Marshall Islands: prohibited'),
      ('MK', 'prohibited', 'North Macedonia: restricted'),
      ('ML', 'prohibited', 'Mali: prohibited'),
      ('MM', 'prohibited', 'Myanmar: prohibited'),
      ('MN', 'prohibited', 'Mongolia: prohibited'),
      ('MO', 'prohibited', 'Macau: prohibited'),
      ('MP', 'prohibited', 'Northern Mariana Islands: restricted'),
      ('MR', 'prohibited', 'Mauritania: prohibited'),
      ('MT', 'domestic_only', 'Malta: adult associations + medical; limited commercial'),
      ('MU', 'medical_limited_trade', 'Mauritius: medical'),
      ('MV', 'prohibited', 'Maldives: prohibited'),
      ('MW', 'medical_limited_trade', 'Malawi: medical export pathway'),
      ('MX', 'medical_limited_trade', 'Mexico: medical framework; adult-use limited/pending full commercial'),
      ('MY', 'prohibited', 'Malaysia: prohibited'),
      ('MZ', 'prohibited', 'Mozambique: prohibited'),
      ('NA', 'cbd_hemp_only', 'Namibia: hemp limited'),
      ('NC', 'medical_limited_trade', 'New Caledonia: follows FR'),
      ('NE', 'prohibited', 'Niger: prohibited'),
      ('NG', 'cbd_hemp_only', 'Nigeria: hemp limited'),
      ('NI', 'prohibited', 'Nicaragua: prohibited'),
      ('NL', 'domestic_only', 'Netherlands: tolerated retail; no full lawful cross-border commercial'),
      ('NO', 'medical_limited_trade', 'Norway: medical'),
      ('NP', 'prohibited', 'Nepal: restricted'),
      ('NR', 'prohibited', 'Nauru: prohibited'),
      ('NU', 'prohibited', 'Niue: prohibited'),
      ('NZ', 'medical_limited_trade', 'New Zealand: medical'),
      ('OM', 'prohibited', 'Oman: prohibited'),
      ('PA', 'cbd_hemp_only', 'Panama: medical/hemp limited'),
      ('PE', 'medical_limited_trade', 'Peru: medical'),
      ('PF', 'medical_limited_trade', 'French Polynesia: follows FR'),
      ('PG', 'prohibited', 'Papua New Guinea: prohibited'),
      ('PH', 'prohibited', 'Philippines: prohibited'),
      ('PK', 'prohibited', 'Pakistan: prohibited'),
      ('PL', 'medical_limited_trade', 'Poland: medical'),
      ('PM', 'prohibited', 'Saint Pierre and Miquelon: restricted'),
      ('PN', 'prohibited', 'Pitcairn: restricted'),
      ('PR', 'domestic_only', 'Puerto Rico: medical/adult frameworks under US federal constraints'),
      ('PS', 'prohibited', 'Palestine: prohibited'),
      ('PT', 'legal_commercial_access', 'Portugal: medical + commercial export pathways'),
      ('PW', 'prohibited', 'Palau: prohibited'),
      ('PY', 'cbd_hemp_only', 'Paraguay: hemp'),
      ('QA', 'prohibited', 'Qatar: prohibited'),
      ('RE', 'medical_limited_trade', 'Réunion: follows FR'),
      ('RO', 'cbd_hemp_only', 'Romania: hemp/CBD'),
      ('RS', 'medical_limited_trade', 'Serbia: medical'),
      ('RU', 'prohibited', 'Russia: prohibited'),
      ('RW', 'prohibited', 'Rwanda: prohibited'),
      ('SA', 'prohibited', 'Saudi Arabia: prohibited'),
      ('SB', 'prohibited', 'Solomon Islands: prohibited'),
      ('SC', 'prohibited', 'Seychelles: prohibited'),
      ('SD', 'prohibited', 'Sudan: prohibited'),
      ('SE', 'medical_limited_trade', 'Sweden: medical'),
      ('SG', 'prohibited', 'Singapore: prohibited'),
      ('SH', 'prohibited', 'Saint Helena: restricted'),
      ('SI', 'medical_limited_trade', 'Slovenia: medical'),
      ('SJ', 'prohibited', 'Svalbard and Jan Mayen: restricted'),
      ('SK', 'medical_limited_trade', 'Slovakia: medical'),
      ('SL', 'prohibited', 'Sierra Leone: prohibited'),
      ('SM', 'prohibited', 'San Marino: restricted'),
      ('SN', 'prohibited', 'Senegal: prohibited'),
      ('SO', 'prohibited', 'Somalia: prohibited'),
      ('SR', 'prohibited', 'Suriname: prohibited'),
      ('SS', 'prohibited', 'South Sudan: prohibited'),
      ('ST', 'prohibited', 'São Tomé and Príncipe: prohibited'),
      ('SV', 'prohibited', 'El Salvador: prohibited'),
      ('SX', 'prohibited', 'Sint Maarten: restricted'),
      ('SY', 'prohibited', 'Syria: prohibited'),
      ('SZ', 'prohibited', 'Eswatini: prohibited'),
      ('TC', 'prohibited', 'Turks and Caicos: restricted'),
      ('TD', 'prohibited', 'Chad: prohibited'),
      ('TF', 'prohibited', 'French Southern Territories: restricted'),
      ('TG', 'prohibited', 'Togo: prohibited'),
      ('TH', 'medical_limited_trade', 'Thailand: medical after 2025 re-restriction'),
      ('TJ', 'prohibited', 'Tajikistan: prohibited'),
      ('TK', 'prohibited', 'Tokelau: restricted'),
      ('TL', 'prohibited', 'Timor-Leste: prohibited'),
      ('TM', 'prohibited', 'Turkmenistan: prohibited'),
      ('TN', 'prohibited', 'Tunisia: prohibited'),
      ('TO', 'prohibited', 'Tonga: prohibited'),
      ('TR', 'cbd_hemp_only', 'Turkey: hemp/CBD'),
      ('TT', 'medical_limited_trade', 'Trinidad and Tobago: medical'),
      ('TV', 'prohibited', 'Tuvalu: prohibited'),
      ('TW', 'cbd_hemp_only', 'Taiwan: hemp/CBD limited'),
      ('TZ', 'prohibited', 'Tanzania: prohibited'),
      ('UA', 'cbd_hemp_only', 'Ukraine: hemp/CBD medical limited'),
      ('UG', 'prohibited', 'Uganda: prohibited'),
      ('UM', 'prohibited', 'US Minor Outlying Islands: restricted'),
      ('US', 'domestic_only', 'United States: federal Schedule constraints; state markets domestic-only'),
      ('UY', 'legal_commercial_access', 'Uruguay: national regulated adult-use + medical commercial market'),
      ('UZ', 'prohibited', 'Uzbekistan: prohibited'),
      ('VA', 'prohibited', 'Vatican: prohibited'),
      ('VC', 'medical_limited_trade', 'Saint Vincent: medical/export limited'),
      ('VE', 'prohibited', 'Venezuela: prohibited'),
      ('VI', 'domestic_only', 'US Virgin Islands: territorial adult-use/medical under federal constraints'),
      ('VN', 'prohibited', 'Vietnam: prohibited'),
      ('VU', 'prohibited', 'Vanuatu: prohibited'),
      ('WF', 'prohibited', 'Wallis and Futuna: restricted'),
      ('WS', 'prohibited', 'Samoa: prohibited'),
      ('XK', 'prohibited', 'Kosovo: restricted'),
      ('YE', 'prohibited', 'Yemen: prohibited'),
      ('YT', 'medical_limited_trade', 'Mayotte: follows FR'),
      ('ZA', 'domestic_only', 'South Africa: private use + medical; commercial limited'),
      ('ZM', 'prohibited', 'Zambia: prohibited'),
      ('ZW', 'medical_limited_trade', 'Zimbabwe: medical/export limited')
    ) as accepted(iso, tier, note)
  loop
    if exists (
      select 1
      from public.countries c
      where c.iso_alpha2 = r.iso
        and c.regulatory_tier is not distinct from r.tier
        and c.regulatory_tier_origin = 'override'
        and c.regulatory_tier_needs_review = false
        and c.regulatory_tier_rationale is not distinct from r.note
    ) then
      continue;
    end if;

    -- Only apply when the country row exists (avoids errors on sparse envs)
    if exists (select 1 from public.countries c where c.iso_alpha2 = r.iso) then
      perform api.set_regulatory_tier(r.iso, r.tier, 'ops-full-coverage', r.note);
    end if;
  end loop;
end $$;

-- Ensure any remaining null tiers default to prohibited so the heatmap has no gaps.
-- Marked needs_review so analysts can correct later.
update public.countries
set
  regulatory_tier = 'prohibited',
  regulatory_tier_origin = 'override',
  regulatory_tier_needs_review = true,
  regulatory_tier_rationale = coalesce(regulatory_tier_rationale, 'Auto-filled prohibited for full heatmap coverage; pending analyst review'),
  regulatory_tier_source = 'ops-full-coverage-null-fill 2026-08-30',
  regulatory_tier_last_derived_at = now()
where regulatory_tier is null;
