-- Renamed 2026-08-05: the description ended `..._batch2-4.sql`, and a hyphen is
-- not allowed by scripts/check-migration-filenames.mjs, whose pattern is
-- ^(\d{14})_[a-z0-9_]+\.sql$. It was the last failure in that gate. Only the
-- hyphen became an underscore -- the 20260730220200 version and the SQL below
-- are unchanged, and the version is repository-only (production applied these
-- seeds as three separate ledger rows, 20260730211507/211621/211756), so no
-- recorded migration is renamed by this.
--
-- Harbourview-direct supply catalog: Canada seed batches 2-4 (48 SKUs),
-- continuing supabase/migrations/20260730220100_..._batch1.sql (20 SKUs).
-- Combined total: 68 SKUs, matching what is live in production.
-- Same disclosure/idempotency caveats as batch 1 apply here.

insert into public.listings
  (id, category, title, description, product_type, region, price_range, seller_type,
   high_level_specs, status, public_visibility, is_featured, price_amount, price_currency,
   location_country, condition, brand, model, quantity, unit, slug, marketplace_section,
   sold_by_harbourview, sku, stock_qty, lead_time_days, moq, compliance_flags, target_countries,
   created_at, updated_at)
values
(gen_random_uuid(),'consumables','Empty 510 Vape Cartridge — 0.5mL Ceramic/Glass','Empty ceramic-coil 510 thread vape cartridge for oil filling.','vape_hardware','north_america','negotiable','distributor','{"size":"0.5mL","thread":"510","material":"ceramic/glass"}','approved',true,false,0.65,'CAD','CA','new','Harbourview Supply','HV-CART-05',1000,'each','empty-510-vape-cartridge-0-5ml','consumables',true,'HVP-VAP-C05',20000,14,500,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Empty 510 Vape Cartridge — 1.0mL Ceramic/Glass','Empty ceramic-coil 510 thread vape cartridge for oil filling.','vape_hardware','north_america','negotiable','distributor','{"size":"1.0mL","thread":"510","material":"ceramic/glass"}','approved',true,false,0.85,'CAD','CA','new','Harbourview Supply','HV-CART-10',1000,'each','empty-510-vape-cartridge-1-0ml','consumables',true,'HVP-VAP-C10',15000,14,500,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','510 Thread Battery — Variable Voltage, USB-C','Rechargeable 510 thread battery with variable voltage and USB-C charging.','vape_hardware','north_america','negotiable','distributor','{"thread":"510","charging":"USB-C","voltage":"variable"}','approved',true,false,2.20,'CAD','CA','new','Harbourview Supply','HV-BATT-1',1000,'each','510-thread-battery-variable-voltage-usbc','consumables',true,'HVP-VAP-BAT',12000,14,250,'{}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Vape Cartridge Box — 510 Push-Turn (Single)','Child-resistant push-and-turn carton for single 510 cartridges.','vape_packaging','north_america','negotiable','distributor','{"thread":"510","cr":true}','approved',true,false,0.30,'CAD','CA','new','Harbourview Supply','HV-VBOX-1',1000,'each','cr-vape-cartridge-box-510-push-turn','packaging',true,'HVP-VPK-BOX',20000,10,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Vape Cartridge Tube — 95mm Press-Button (Recyclable Cardboard)','Child-resistant, recyclable cardboard tube with press-button closure for 510 cartridges.','vape_packaging','north_america','negotiable','distributor','{"length":"95mm","material":"recyclable cardboard","cr":true}','approved',true,false,0.28,'CAD','CA','new','Harbourview Supply','HV-VTUBE-95',1000,'each','cr-vape-cartridge-tube-95mm-press-button','packaging',true,'HVP-VPK-TUB',18000,10,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Edible Single-Serving Stand-Up Pouch (10mg)','Child-resistant opaque stand-up pouch sized for a single 10mg THC edible package, per Health Canada''s 10mg/package limit.','edible_packaging','north_america','negotiable','distributor','{"dose_mg":10,"cr":true}','approved',true,true,0.12,'CAD','CA','new','Harbourview Supply','HV-EDPCH-10',1000,'each','cr-edible-single-serving-pouch-10mg','packaging',true,'HVP-EDB-PCH',20000,10,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"max_thc_mg_per_package":10}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Edible Multi-Cavity Blister Card (10 x 1mg)','Child-resistant blister card holding 10 x 1mg THC pieces, total 10mg per Health Canada package limit.','edible_packaging','north_america','negotiable','distributor','{"cavities":10,"dose_mg_each":1,"cr":true}','approved',true,false,0.24,'CAD','CA','new','Harbourview Supply','HV-EDBLIS-10',1000,'each','cr-edible-multi-cavity-blister-10x1mg','packaging',true,'HVP-EDB-BLI',15000,12,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"max_thc_mg_per_package":10}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Outer Carton for Edible Pouch (Health Warning Panel)','Opaque outer carton sized for edible pouches, with dedicated health-warning and cannabis-symbol panel per plain packaging rules.','edible_packaging','north_america','negotiable','distributor','{"cr":true}','approved',true,false,0.20,'CAD','CA','new','Harbourview Supply','HV-EDCARTON-1',1000,'each','cr-outer-carton-edible-pouch','packaging',true,'HVP-EDB-CTN',12000,12,500,'{"CA":{"opaque":true,"plain_packaging":true}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','Health Canada Compliant Label Roll — THC/CBD Panel + Symbol (Blank)','Blank-fill label roll pre-formatted with the standardized cannabis symbol, health warning, and THC/CBD info panel per plain packaging rules.','label','north_america','negotiable','distributor','{"format":"THC/CBD panel + symbol"}','approved',true,false,0.06,'CAD','CA','new','Harbourview Supply','HV-LBL-1','5000','each','hc-compliant-label-roll-thc-cbd-symbol','packaging',true,'HVP-LBL-001',200000,10,5000,'{"CA":{"plain_packaging":true,"cannabis_symbol":true,"health_warning":true}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','Batch/Lot Traceability Barcode Labels (Blank, Roll of 1000)','Blank barcode/lot-tracking labels for batch traceability.','label','north_america','negotiable','distributor','{}','approved',true,false,0.03,'CAD','CA','new','Harbourview Supply','HV-LBL-2',1000,'each','batch-lot-traceability-barcode-labels','packaging',true,'HVP-LBL-002',300000,7,5000,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Bulk Curing Tote / Turkey Bag (Large Format, Food-Grade)','Food-grade large-format bag for bulk curing of flower.','curing_supply','north_america','negotiable','distributor','{"format":"large bulk"}','approved',true,false,1.10,'CAD','CA','new','Harbourview Supply','HV-CURETOTE-1',500,'each','bulk-curing-tote-turkey-bag','consumables',true,'HVP-CUR-TOT',5000,10,100,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Vacuum-Seal Bulk Storage Bag (1kg Format)','Vacuum-seal bag sized for 1kg bulk flower storage.','curing_supply','north_america','negotiable','distributor','{"format":"1kg"}','approved',true,false,0.45,'CAD','CA','new','Harbourview Supply','HV-VACBAG-1KG',1000,'each','vacuum-seal-bulk-storage-bag-1kg','consumables',true,'HVP-CUR-VAC',8000,10,250,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Two-Way Humidity Control Packs — 69% RH (Bulk Case)','2-way humidity control packs, 69% RH, bulk case for larger-format curing.','humidity_pack','north_america','negotiable','distributor','{"rh":"69%"}','approved',true,false,0.40,'CAD','CA','new','Harbourview Supply','HV-HUMID-69',500,'each','humidity-control-packs-69rh-bulk','consumables',true,'HVP-HUM-069',9000,10,100,'{}','{CA}',now(),now()),
(gen_random_uuid(),'processing_equipment','Bench-Top Impulse Heat Sealer (Mylar Pouches)','Impulse heat sealer for sealing mylar pouches at the point of packing.','sealing_equipment','north_america','negotiable','distributor','{}','approved',true,false,210.00,'CAD','CA','new','Harbourview Supply','HV-SEALER-1',15,'unit','bench-top-impulse-heat-sealer','processing',true,'HVP-EQP-SEAL',15,10,1,'{}','{CA}',now(),now()),
(gen_random_uuid(),'processing_equipment','Semi-Automatic Capping Machine (CR Cap Application)','Semi-automatic machine for applying child-resistant caps to jars/bottles at production scale.','capping_equipment','north_america','negotiable','distributor','{}','approved',true,false,5400.00,'CAD','CA','new','Harbourview Supply','HV-CAPPER-1',3,'unit','semi-automatic-capping-machine-cr','processing',true,'HVP-EQP-CAP',3,28,1,'{}','{CA}',now(),now()),
(gen_random_uuid(),'processing_equipment','Semi-Automatic Label Applicator','Semi-automatic label applicator for jars, pouches, and cartons.','labeling_equipment','north_america','negotiable','distributor','{}','approved',true,false,3800.00,'CAD','CA','new','Harbourview Supply','HV-LABELER-1',3,'unit','semi-automatic-label-applicator','processing',true,'HVP-EQP-LBL',3,28,1,'{}','{CA}',now(),now()),
(gen_random_uuid(),'processing_equipment','Vape Cartridge Filling Machine (Semi-Automatic, Peristaltic)','Semi-automatic peristaltic filling machine for 510 vape cartridges.','filling_equipment','north_america','negotiable','distributor','{"mechanism":"peristaltic"}','approved',true,true,7200.00,'CAD','CA','new','Harbourview Supply','HV-FILLER-1',2,'unit','vape-cartridge-filling-machine-semi-auto','processing',true,'HVP-EQP-FIL',2,28,1,'{}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Silicone Concentrate Container — 5mL (Opaque)','Child-resistant opaque silicone concentrate container, non-stick interior.','concentrate_packaging','north_america','negotiable','distributor','{"size":"5mL","material":"silicone","cr":true}','approved',true,false,0.32,'CAD','CA','new','Harbourview Supply','HV-CONC-SIL5',1000,'each','cr-silicone-concentrate-container-5ml','packaging',true,'HVP-CNC-SIL',15000,10,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Glass Concentrate Jar — 5mL','Child-resistant glass concentrate jar with CR lid, opaque black.','concentrate_packaging','north_america','negotiable','distributor','{"size":"5mL","material":"glass","cr":true}','approved',true,false,0.48,'CAD','CA','new','Harbourview Supply','HV-CONC-GLS5',1000,'each','cr-glass-concentrate-jar-5ml','packaging',true,'HVP-CNC-GLS',12000,12,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Unbleached Parchment / Wax Paper Squares (Bulk)','Non-stick unbleached parchment squares for concentrate handling and packaging.','concentrate_supply','north_america','negotiable','distributor','{}','approved',true,false,0.02,'CAD','CA','new','Harbourview Supply','HV-PARCH-1',1000,'each','unbleached-parchment-wax-paper-squares','consumables',true,'HVP-CNC-PAR',200000,7,5000,'{}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Tincture Bottle — 30mL Amber Glass w/ Dropper','Child-resistant amber glass tincture bottle with graduated dropper cap.','tincture_packaging','north_america','negotiable','distributor','{"size":"30mL","material":"amber glass","cr":true}','approved',true,true,0.14,'CAD','CA','new','Harbourview Supply','HV-TINC-30',1000,'each','cr-tincture-bottle-30ml-amber-dropper','packaging',true,'HVP-TIN-030',18000,10,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Tincture Bottle — 10mL Amber Glass w/ Dropper','Child-resistant amber glass tincture bottle with graduated dropper cap.','tincture_packaging','north_america','negotiable','distributor','{"size":"10mL","material":"amber glass","cr":true}','approved',true,false,0.11,'CAD','CA','new','Harbourview Supply','HV-TINC-10',1000,'each','cr-tincture-bottle-10ml-amber-dropper','packaging',true,'HVP-TIN-010',20000,10,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Graduated Glass Droppers (Bulk)','Bulk calibrated glass droppers for tincture bottle assembly.','tincture_supply','north_america','negotiable','distributor','{"graduated":true}','approved',true,false,0.06,'CAD','CA','new','Harbourview Supply','HV-DROP-1',1000,'each','graduated-glass-droppers-bulk','consumables',true,'HVP-TIN-DRP',25000,10,1000,'{}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Topical Jar — 50g (Opaque, CR Lid)','Child-resistant opaque jar for topical creams/balms.','topical_packaging','north_america','negotiable','distributor','{"size":"50g","cr":true}','approved',true,false,0.38,'CAD','CA','new','Harbourview Supply','HV-TOP-JAR50',1000,'each','cr-topical-jar-50g','packaging',true,'HVP-TOP-JAR',10000,12,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Topical Stick / Tube (Deodorant-Style)','Child-resistant deodorant-style twist-up tube for topical sticks.','topical_packaging','north_america','negotiable','distributor','{"format":"twist-up stick","cr":true}','approved',true,false,0.42,'CAD','CA','new','Harbourview Supply','HV-TOP-STICK',1000,'each','cr-topical-stick-tube','packaging',true,'HVP-TOP-STK',8000,12,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Topical Pump Bottle — 100mL','Child-resistant pump-top bottle for liquid/lotion topicals.','topical_packaging','north_america','negotiable','distributor','{"size":"100mL","format":"pump","cr":true}','approved',true,false,0.55,'CAD','CA','new','Harbourview Supply','HV-TOP-PUMP100',1000,'each','cr-topical-pump-bottle-100ml','packaging',true,'HVP-TOP-PMP',6000,14,250,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Master Shipping Case (Corrugated, Retail-Ready)','Corrugated master shipping case sized for retail-ready cannabis product cartons.','shipping_supply','north_america','negotiable','distributor','{}','approved',true,false,1.35,'CAD','CA','new','Harbourview Supply','HV-CASE-1',500,'each','master-shipping-case-corrugated','consumables',true,'HVP-SHP-CAS',6000,10,100,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Void Fill Air Pillows (Bulk)','Bulk air pillow void fill for shipping cartons.','shipping_supply','north_america','negotiable','distributor','{}','approved',true,false,0.02,'CAD','CA','new','Harbourview Supply','HV-VOID-1',5000,'each','void-fill-air-pillows-bulk','consumables',true,'HVP-SHP-VOI',500000,7,10000,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Pallet Stretch Wrap (Bulk Rolls)','Machine-grade stretch wrap for palletized shipments.','shipping_supply','north_america','negotiable','distributor','{}','approved',true,false,18.00,'CAD','CA','new','Harbourview Supply','HV-WRAP-1',200,'roll','pallet-stretch-wrap-bulk-rolls','consumables',true,'HVP-SHP-WRP',1500,7,20,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Tamper-Evident Security Tape (Case Sealing)','Security tape with void/tamper-evident pattern for shipping case sealing.','shipping_supply','north_america','negotiable','distributor','{}','approved',true,false,4.20,'CAD','CA','new','Harbourview Supply','HV-TAPE-1',200,'roll','tamper-evident-security-tape','consumables',true,'HVP-SHP-TAP',3000,7,50,'{}','{CA}',now(),now()),
(gen_random_uuid(),'processing_equipment','Tincture Filling Machine (Semi-Automatic, Volumetric)','Semi-automatic volumetric filling machine for tincture and topical liquid bottles.','filling_equipment','north_america','negotiable','distributor','{"mechanism":"volumetric"}','approved',true,false,6500.00,'CAD','CA','new','Harbourview Supply','HV-TINCFIL-1',2,'unit','tincture-filling-machine-semi-auto','processing',true,'HVP-EQP-TFL',2,28,1,'{}','{CA}',now(),now()),
(gen_random_uuid(),'processing_equipment','Semi-Automatic Case Erector/Sealer','Semi-automatic case erector and sealer for shipping carton assembly.','packing_equipment','north_america','negotiable','distributor','{}','approved',true,false,8900.00,'CAD','CA','new','Harbourview Supply','HV-CASESEAL-1',2,'unit','semi-automatic-case-erector-sealer','processing',true,'HVP-EQP-CES',2,35,1,'{}','{CA}',now(),now()),
(gen_random_uuid(),'processing_equipment','Induction Sealer (Foil Liner Sealing for Bottles)','Induction sealer for foil-liner sealing of tincture/topical bottle caps.','sealing_equipment','north_america','negotiable','distributor','{}','approved',true,false,2600.00,'CAD','CA','new','Harbourview Supply','HV-INDSEAL-1',4,'unit','induction-sealer-foil-liner','processing',true,'HVP-EQP-IND',4,21,1,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Rockwool Propagation Cubes (Case)','Rockwool propagation cubes for clones and seedlings.','grow_media','north_america','negotiable','distributor','{}','approved',true,false,0.09,'CAD','CA','new','Harbourview Supply','HV-ROCKW-1',1500,'each','rockwool-propagation-cubes-case','consumables',true,'HVP-CUL-ROC',300000,10,1500,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Coco Coir Grow Media (Compressed Bale, 50L Expanded)','Compressed coco coir bale, expands to approx. 50L grow media.','grow_media','north_america','negotiable','distributor','{"expanded_volume":"50L"}','approved',true,false,18.00,'CAD','CA','new','Harbourview Supply','HV-COCO-50',300,'bale','coco-coir-grow-media-50l-bale','consumables',true,'HVP-CUL-COC',2000,14,20,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Cannabis Nutrient Line — Grow Base A/B (20L Jug)','Vegetative-stage base nutrient concentrate, 20L jug.','nutrients','north_america','negotiable','distributor','{"stage":"grow","size":"20L"}','approved',true,false,145.00,'CAD','CA','new','Harbourview Supply','HV-NUT-GROW20',100,'jug','cannabis-nutrient-grow-base-20l','consumables',true,'HVP-CUL-NUTG',400,14,4,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Cannabis Nutrient Line — Bloom Base A/B (20L Jug)','Flowering-stage base nutrient concentrate, 20L jug.','nutrients','north_america','negotiable','distributor','{"stage":"bloom","size":"20L"}','approved',true,false,155.00,'CAD','CA','new','Harbourview Supply','HV-NUT-BLM20',100,'jug','cannabis-nutrient-bloom-base-20l','consumables',true,'HVP-CUL-NUTB',400,14,4,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Trellis Netting (100ft Roll)','Support netting for canopy training, 100ft roll.','trellis','north_america','negotiable','distributor','{"length":"100ft"}','approved',true,false,22.00,'CAD','CA','new','Harbourview Supply','HV-TRELLIS-100',200,'roll','trellis-netting-100ft-roll','consumables',true,'HVP-CUL-TRL',1200,10,10,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Cloning Gel (1L Bottle)','Rooting hormone gel for clone propagation, 1L bottle.','cloning_supply','north_america','negotiable','distributor','{"size":"1L"}','approved',true,false,28.00,'CAD','CA','new','Harbourview Supply','HV-CLONEGEL-1',100,'bottle','cloning-gel-1l-bottle','consumables',true,'HVP-CUL-GEL',600,10,6,'{}','{CA}',now(),now()),
(gen_random_uuid(),'cultivation_equipment','Humidity Dome + Tray Propagation Kit','Propagation tray and humidity dome kit for clones/seedlings.','propagation_kit','north_america','negotiable','distributor','{}','approved',true,false,14.00,'CAD','CA','new','Harbourview Supply','HV-DOME-1',200,'kit','humidity-dome-tray-propagation-kit','equipment',true,'HVP-CUL-DOM',800,10,10,'{}','{CA}',now(),now()),
(gen_random_uuid(),'cultivation_equipment','Commercial LED Grow Light Bar — 640W Full-Spectrum','Commercial-grade full-spectrum LED grow light bar for flowering rooms.','grow_light','north_america','negotiable','distributor','{"wattage":"640W","spectrum":"full"}','approved',true,true,850.00,'CAD','CA','new','Harbourview Supply','HV-LED-640',40,'unit','led-grow-light-bar-640w','equipment',true,'HVP-CUL-LED',40,21,1,'{}','{CA}',now(),now()),
(gen_random_uuid(),'cultivation_equipment','Drip Irrigation Kit (Expandable, Per Zone)','Expandable drip irrigation kit configurable per canopy zone.','irrigation','north_america','negotiable','distributor','{}','approved',true,false,320.00,'CAD','CA','new','Harbourview Supply','HV-DRIP-1',30,'kit','drip-irrigation-kit-expandable','equipment',true,'HVP-CUL-DRP',30,21,1,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Tamper-Evident Sample Collection Bags (Bulk)','Tamper-evident bags for COA/lab sample collection and chain of custody.','lab_supply','north_america','negotiable','distributor','{}','approved',true,false,0.15,'CAD','CA','new','Harbourview Supply','HV-SAMPBAG-1',1000,'each','tamper-evident-sample-collection-bags','labs_testing',true,'HVP-LAB-SMP',20000,10,500,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Lab Pipette Tips (Bulk Case, 1000ct)','Disposable pipette tips for lab sampling and testing workflows.','lab_supply','north_america','negotiable','distributor','{"count":1000}','approved',true,false,0.02,'CAD','CA','new','Harbourview Supply','HV-PIPTIP-1',1000,'each','lab-pipette-tips-bulk-1000ct','labs_testing',true,'HVP-LAB-PIP',500000,10,1000,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','pH / EC Calibration Solution Kit','Calibration solution kit for pH and EC meters.','lab_supply','north_america','negotiable','distributor','{}','approved',true,false,45.00,'CAD','CA','new','Harbourview Supply','HV-CALKIT-1',150,'kit','ph-ec-calibration-solution-kit','labs_testing',true,'HVP-LAB-CAL',600,10,5,'{}','{CA}',now(),now()),
(gen_random_uuid(),'labs_testing','Bench-Top Moisture Analyzer (Halogen, Compliance-Grade)','Halogen moisture analyzer for compliance-grade moisture content testing.','lab_equipment','north_america','negotiable','distributor','{"method":"halogen"}','approved',true,false,2100.00,'CAD','CA','new','Harbourview Supply','HV-MOIST-1',6,'unit','moisture-analyzer-halogen-bench-top','labs_testing',true,'HVP-EQP-MOI',6,21,1,'{}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Dispensary Exit Bag (Opaque, Blank)','Child-resistant opaque exit bag for point-of-sale dispensing.','exit_bag','north_america','negotiable','distributor','{"cr":true}','approved',true,false,0.16,'CAD','CA','new','Harbourview Supply','HV-EXITBAG-1',1000,'each','cr-dispensary-exit-bag-opaque','packaging',true,'HVP-RTL-EXB',15000,10,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','In-Store Compliance Signage Kit (Mandatory Health Warnings)','Retail signage kit covering mandatory in-store cannabis health warning postings.','retail_supply','north_america','negotiable','distributor','{}','approved',true,false,35.00,'CAD','CA','new','Harbourview Supply','HV-SIGNKIT-1',80,'kit','in-store-compliance-signage-kit','consumables',true,'HVP-RTL-SIG',300,14,5,'{}','{CA}',now(),now())
on conflict do nothing;
