-- Seed clinical education content (idempotent). Generated from lib/fixtures/clinical-education.ts

insert into public.clinical_education_modules
 (id,slug,title,route,audience,module_status,risk_level,public_summary,education_themes,safe_language,restricted_language,research_status,professional_review_required,source_basis,reviewer_role_required,audience_boundary,last_reviewed,next_review_due,public_use_approved,medical_advice_boundary,country_relevance,format_relevance,disclaimer_type,cta_label,cta_href,sort_order)
values
  ($ce$clinical-overview$ce$, $ce$clinical-education$ce$, $ce$Harbourview Clinical Education$ce$, $ce$/network/clinical-education$ce$, array[$ce$doctors$ce$, $ce$pharmacists$ce$, $ce$clinics$ce$, $ce$regulated participants$ce$]::text[], $ce$Live$ce$, $ce$low$ce$, $ce$Medical cannabis access can expand faster than professional training. Harbourview Clinical Education organizes professional education themes for regulated markets.$ce$, array[$ce$professional education gap$ce$, $ce$product forms$ce$, $ce$country readiness$ce$, $ce$professional review$ce$]::text[], array[$ce$professional education$ce$, $ce$country readiness$ce$, $ce$documentation expectations$ce$]::text[], array[$ce$individualized instruction wording$ce$, $ce$treatment-direction wording$ce$]::text[], $ce$Live framework$ce$, false, $ce$professional-orientation$ce$, array[$ce$Harbourview editorial review$ce$]::text[], $ce$commercial-professional$ce$, $ce$2026-05-17$ce$::date, $ce$Before jurisdiction-specific publication or patient-facing reuse$ce$, true, $ce$Professional education only. Not medical advice, prescribing advice, patient-specific guidance, product recommendation or treatment direction.$ce$, array[$ce$global$ce$]::text[], array[$ce$all formats$ce$]::text[], $ce$standard$ce$, $ce$Request Education Support$ce$, $ce$/network/clinical-education/request$ce$, 0),
  ($ce$dosage-forms$ce$, $ce$dosage-forms$ce$, $ce$Dosage Forms & Routes$ce$, $ce$/network/clinical-education/dosage-forms$ce$, array[$ce$doctors$ce$, $ce$pharmacists$ce$, $ce$importers$ce$, $ce$licensed producers$ce$]::text[], $ce$Live$ce$, $ce$medium$ce$, $ce$A basic education module explaining product forms and routes at a professional overview level.$ce$, array[$ce$oral formats$ce$, $ce$capsules$ce$, $ce$softgels$ce$, $ce$dried formats$ce$, $ce$extracts$ce$, $ce$routes of administration$ce$]::text[], array[$ce$product forms$ce$, $ce$product formats$ce$, $ce$route of administration$ce$]::text[], array[$ce$individualized amount wording$ce$, $ce$prescribing instruction wording$ce$]::text[], $ce$Live basic format education$ce$, false, $ce$professional-orientation$ce$, array[$ce$Harbourview editorial review$ce$, $ce$Clinical/pharmacy reviewer before jurisdiction-specific use$ce$]::text[], $ce$professional-only$ce$, $ce$2026-05-17$ce$::date, $ce$Before any dose, condition, country or patient-facing adaptation$ce$, true, $ce$Professional education only. Not medical advice, prescribing advice, patient-specific guidance, product recommendation or treatment direction.$ce$, array[$ce$global$ce$]::text[], array[$ce$oils$ce$, $ce$capsules$ce$, $ce$softgels$ce$, $ce$flower$ce$, $ce$extracts$ce$]::text[], $ce$dosage$ce$, $ce$Request Format Education Support$ce$, $ce$/network/clinical-education/request$ce$, 1),
  ($ce$product-documentation$ce$, $ce$product-documentation$ce$, $ce$COAs, Potency & Product Documentation$ce$, $ce$/network/clinical-education/product-documentation$ce$, array[$ce$pharmacists$ce$, $ce$importers$ce$, $ce$licensed producers$ce$, $ce$compliance teams$ce$]::text[], $ce$Live$ce$, $ce$low$ce$, $ce$A basic documentation education module covering certificates, profiles, batch references, testing, storage conditions and documentation standards.$ce$, array[$ce$certificates$ce$, $ce$potency$ce$, $ce$batch documentation$ce$, $ce$testing$ce$, $ce$storage conditions$ce$]::text[], array[$ce$certificate basics$ce$, $ce$potency$ce$, $ce$documentation expectations$ce$]::text[], array[$ce$private document wording$ce$, $ce$inventory wording$ce$]::text[], $ce$Live basic documentation education$ce$, false, $ce$professional-orientation$ce$, array[$ce$Harbourview editorial review$ce$, $ce$QA/regulatory reviewer before route-specific reliance$ce$]::text[], $ce$commercial-professional$ce$, $ce$2026-05-17$ce$::date, $ce$Before batch-specific, country-specific or QP-facing adaptation$ce$, true, $ce$Professional education only. Not medical advice, prescribing advice, patient-specific guidance, product recommendation or treatment direction.$ce$, array[$ce$global$ce$]::text[], array[$ce$all formats$ce$]::text[], $ce$standard$ce$, $ce$Request Documentation Education Support$ce$, $ce$/network/clinical-education/request$ce$, 2),
  ($ce$formulas-ratios$ce$, $ce$formulas-ratios$ce$, $ce$Formulas & Ratios$ce$, $ce$/network/clinical-education/formulas-ratios$ce$, array[$ce$doctors$ce$, $ce$pharmacists$ce$, $ce$licensed producers$ce$, $ce$importers$ce$]::text[], $ce$Research in progress$ce$, $ce$high$ce$, $ce$A research-stage module for professional education around formulas and ratios.$ce$, array[$ce$formula considerations$ce$, $ce$ratio concepts$ce$, $ce$professional considerations$ce$]::text[], array[$ce$formula considerations$ce$, $ce$ratio concepts$ce$, $ce$professional considerations$ce$]::text[], array[$ce$patient-matching wording$ce$, $ce$condition-selection wording$ce$]::text[], $ce$Research in progress$ce$, true, $ce$research-in-progress$ce$, array[$ce$Qualified clinical reviewer$ce$, $ce$Regulatory/promotional review before external use$ce$]::text[], $ce$professional-only$ce$, $ce$2026-05-17$ce$::date, $ce$Before public detail expansion or external reuse$ce$, false, $ce$Professional education only. Not medical advice, prescribing advice, patient-specific guidance, product recommendation or treatment direction.$ce$, array[$ce$global$ce$]::text[], array[$ce$all formulas$ce$]::text[], $ce$dosage$ce$, $ce$Request Formula Education Support$ce$, $ce$/network/clinical-education/request$ce$, 3),
  ($ce$onset-duration$ce$, $ce$onset-duration$ce$, $ce$Onset, Duration & Format Differences$ce$, $ce$/network/clinical-education/onset-duration$ce$, array[$ce$doctors$ce$, $ce$pharmacists$ce$, $ce$clinics$ce$]::text[], $ce$Professional review required$ce$, $ce$high$ce$, $ce$A professional-review-required module for timing and format-difference education.$ce$, array[$ce$onset concepts$ce$, $ce$duration concepts$ce$, $ce$format differences$ce$, $ce$monitoring implications$ce$]::text[], array[$ce$onset$ce$, $ce$duration$ce$, $ce$monitoring considerations$ce$]::text[], array[$ce$effect-promise wording$ce$, $ce$outcome-claim wording$ce$]::text[], $ce$Professional review required$ce$, true, $ce$professional-review-required$ce$, array[$ce$Qualified clinical reviewer$ce$, $ce$Medical/legal/promotional review before external use$ce$]::text[], $ce$professional-only$ce$, $ce$2026-05-17$ce$::date, $ce$Before any public detail expansion or clinical-use adaptation$ce$, false, $ce$Professional education only. Not medical advice, prescribing advice, patient-specific guidance, product recommendation or treatment direction.$ce$, array[$ce$global$ce$]::text[], array[$ce$multiple formats$ce$]::text[], $ce$dosage$ce$, $ce$Request Professional Review Briefing$ce$, $ce$/network/clinical-education/request$ce$, 4),
  ($ce$effects-monitoring$ce$, $ce$effects-monitoring$ce$, $ce$Patient-Reported Effects & Monitoring$ce$, $ce$/network/clinical-education/effects-monitoring$ce$, array[$ce$doctors$ce$, $ce$pharmacists$ce$, $ce$clinics$ce$]::text[], $ce$Professional review required$ce$, $ce$high$ce$, $ce$A professional-review-required module for reported effects and monitoring themes.$ce$, array[$ce$reported effects$ce$, $ce$subjective effects$ce$, $ce$adverse-effect awareness$ce$, $ce$monitoring$ce$]::text[], array[$ce$patient-reported effects$ce$, $ce$subjective effects$ce$, $ce$monitoring considerations$ce$]::text[], array[$ce$feeling-promise wording$ce$, $ce$suitability-claim wording$ce$]::text[], $ce$Professional review required$ce$, true, $ce$professional-review-required$ce$, array[$ce$Qualified clinical reviewer$ce$, $ce$Pharmacovigilance/safety reviewer before external use$ce$]::text[], $ce$not-patient-facing$ce$, $ce$2026-05-17$ce$::date, $ce$Before public detail expansion, safety-language reuse or clinical-use adaptation$ce$, false, $ce$Professional education only. Not medical advice, prescribing advice, patient-specific guidance, product recommendation or treatment direction.$ce$, array[$ce$global$ce$]::text[], array[$ce$all formats$ce$]::text[], $ce$patient-boundary$ce$, $ce$Request Effects & Monitoring Briefing$ce$, $ce$/network/clinical-education/request$ce$, 5)
on conflict (id) do nothing;

insert into public.clinical_education_country_readiness
 (country,region,professional_education_readiness,known_training_gap,official_guidance_status,formats_requiring_education,pharmacist_relevance,clinician_relevance,research_status,professional_reviewer_needed,brief_availability,sort_order)
values
  ($ce$Italy$ce$, $ce$Europe$ce$, $ce$Research in progress$ce$, $ce$Professionals may require clearer education on formats, documentation and local context.$ce$, $ce$To be researched$ce$, array[$ce$oils$ce$, $ce$flower$ce$, $ce$capsules$ce$]::text[], $ce$High$ce$, $ce$High$ce$, $ce$Research in progress$ce$, true, $ce$Available by request$ce$, 0),
  ($ce$New Zealand$ce$, $ce$Oceania$ce$, $ce$Official guidance to be reviewed$ce$, $ce$Professionals may require support understanding product forms and documentation.$ce$, $ce$Official sources to be reviewed$ce$, array[$ce$oils$ce$, $ce$capsules$ce$, $ce$dried flower where applicable$ce$]::text[], $ce$High$ce$, $ce$High$ce$, $ce$Research in progress$ce$, true, $ce$Available by request$ce$, 1),
  ($ce$Germany$ce$, $ce$Europe$ce$, $ce$Professional education remains relevant$ce$, $ce$Product formats, pharmacy workflows and documentation remain important education areas.$ce$, $ce$Official and professional sources to be reviewed$ce$, array[$ce$flower$ce$, $ce$extracts$ce$, $ce$oils$ce$, $ce$capsules$ce$]::text[], $ce$High$ce$, $ce$High$ce$, $ce$Research in progress$ce$, true, $ce$Available by request$ce$, 2)
on conflict (country) do nothing;
