-- Historical jurisdiction-unification reconciliation marker.
--
-- Production records version 20260622000004 with the single statement:
--
--   already applied as gap_d_jurisdiction_schema_unification (20260622153847)
--
-- The canonical cross-reference table, RLS policies, unified public view, and
-- population query are owned by:
--
--   20260622153847_gap_d_jurisdiction_schema_unification.sql
--
-- Keeping this version as a no-op prevents the superseded draft from inserting
-- a broader territory list that is not present in the canonical countries
-- table and preserves the exact production migration chronology.
