-- SUPERSEDED. This file's version prefix (20260729020000) does not match
-- its actual applied ledger version. The real applied migration is
-- 20260802134657_fix_candidate_review_and_pathway_template_grants.sql
-- (identical GRANT statements: candidate_review_events, cc_pathway_templates
-- to authenticated).
-- Retired per docs/control/PENDING_PRODUCTION_MIGRATION_DECISIONS_2026-08-02.md.
-- No-op placeholder -- do not add statements here.
