
INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'austria','country','AT','Medical — Prescription Only; CBD Legal',
'Austria permits medical cannabis under the Suchtmittelgesetz (SMG), overseen by the Austrian Agency for Health and Food Safety (AGES). Cannabis-based medicinal products including Sativex and magistral (compounding pharmacy) preparations are accessible via physician prescription for medically appropriate conditions. Austria was among the earlier EU states to allow magistral cannabis formulations, enabling licensed pharmacies to prepare cannabis oils and other preparations directly for patients. Hemp-derived CBD products below 0.3% THC are permitted as nutritional supplements under food law. The Austrian medical cannabis market is served by imported pharmaceutical-grade cannabis and a small number of domestic cultivators licensed by AGES. Patient numbers are estimated in the low tens of thousands, concentrated in pain, neurological, and oncology settings.',
'Austrian patients access medical cannabis through physician prescription without specialist restriction. Most statutory health insurers (Krankenkasse) do not reimburse cannabis prescriptions; out-of-pocket payment is the norm. Magistral preparations from licensed compounding pharmacies are the most accessible route. CBD products below 0.3% THC are sold freely at specialty stores and online.',
'Any Austrian physician licensed by the Österreichische Ärztekammer (AK) may prescribe cannabis-based medicinal products without specialist restriction. Magistral prescriptions must be prepared by licensed compounding pharmacies. Standard SMG controlled substance documentation requirements apply.',
'The Austrian medical cannabis market is moderate in scale. Several pharmacies specialise in cannabis compounding. Austria imports pharmaceutical-grade cannabis from Netherlands, Germany, and Canadian producers. CBD retail is well-established in Vienna, Graz, and Salzburg. Domestic cultivation under AGES licence supplies both domestic and export markets.',
'Austria is monitoring EU regulatory developments closely, particularly Germany''s CanG reform. No near-term framework reform beyond the existing medical prescription route is expected. CBD regulation may tighten in alignment with EFSA Novel Food final rulings.',
'Austrian Agency for Health and Food Safety (AGES) — ages.at; Austrian Medical Chamber (Ärztekammer) — aerztekammer.at; Suchtmittelgesetz (SMG)',
'Austrian Federal Health Ministry publications; AGES regulatory guidance; EMCDDA Austria country report',
'Based on AGES public guidance and EMCDDA data. No patient-level prescription volume data reviewed.',
'Quarterly','National regulatory framework; prescription access; CBD product status; physician prescribing rules; health insurance reimbursement.',
DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='AT' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'belgium','country','BE','Medical — Limited (Sativex); CBD Legal; Personal Use Deprioritised',
'Belgium has a complex cannabis landscape. Personal possession of up to 3 grams for adults is deprioritised for enforcement under a 2003 ministerial directive, though cannabis remains technically illegal. Medical cannabis access is limited to Sativex (nabiximols), approved for multiple sclerosis-related spasticity via specialist prescription. Other cannabis-based medicines may be accessed on a named-patient basis through the Federal Agency for Medicines and Health Products (FAMHP), though this route is rarely used in practice. Hemp-derived CBD products with THC below 0.2% are permitted under food law. Belgium hosts significant cannabis pharmaceutical research activity and is the European base for several cannabis companies. Multiple parliamentary proposals for expanded medical access or a regulated adult-use model have been submitted but not yet enacted.',
'Belgian patients may access Sativex through neurologist prescription with potential RIZIV/INAMI reimbursement for qualifying MS indications. Named-patient access to other cannabis medicines is possible through FAMHP on a case-by-case basis. CBD products below 0.2% THC are available in retail. No broad patient registration programme exists.',
'Belgian neurologists registered with the Order of Physicians may prescribe Sativex. Named-patient compassionate use for other preparations requires FAMHP authorisation with specialist documentation. No general cannabis prescribing right for flower or oils exists outside the Sativex and named-patient pathway.',
'Belgium has an active CBD retail sector in Brussels, Antwerp, and Ghent. Several Belgian companies are pursuing EU-GMP production licences targeting German and UK export markets. Underground cannabis consumption is widespread. The absence of a broader medical programme suppresses the legitimate market relative to population size.',
'Multiple legislative proposals for broader medical access or regulated adult-use reform are active as of 2026. Belgium is expected to follow EU harmonisation trends. A regulatory pilot programme or expanded medical framework is plausible in 2026-2028.',
'Federal Agency for Medicines and Health Products (FAMHP) — fagg-afmps.be; RIZIV/INAMI — riziv.fgov.be',
'FAMHP regulatory guidance; EMCDDA Belgium country report; Belgian parliamentary records on cannabis reform proposals',
'Based on FAMHP public guidance, parliamentary records, and EMCDDA data.',
'Quarterly','Legal framework; Sativex access and reimbursement; CBD regulation; named-patient pathway; reform status.',
DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='BE' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'bulgaria','country','BG','Medical — Limited (Sativex); CBD Legal',
'Bulgaria permits cannabis-based medicinal products under the Law on Narcotics and Precursors, allowing Sativex and approved preparations via prescription. The programme is very limited in practice — most prescribing is concentrated in MS-related spasticity treated with Sativex. Hemp cultivation is legal for industrial and food purposes under EU Common Agricultural Policy rules for low-THC cultivars, and Bulgaria is a significant EU hemp producer. CBD products derived from hemp are permitted below the 0.2% THC limit. Personal cannabis use remains criminalised, and Bulgaria maintains conservative enforcement standards. Reform discussions are in early stages, influenced by developments in Germany and Czechia.',
'Bulgarian patients can access Sativex through specialist prescription. Named-patient access to other cannabis-based medicines exists via the Bulgarian Drug Agency (BDA) but requires case-by-case approval. Out-of-pocket costs are significant as health insurance does not typically cover cannabis medicines. Patient numbers are very small.',
'Bulgarian neurologists and relevant specialists may prescribe Sativex and approved cannabis-based medicines. Named-patient applications for other preparations require BDA approval. No general prescribing right for cannabis flower or oils exists. Physician education on medical cannabis remains limited.',
'The Bulgarian medical cannabis market is very small. Hemp agricultural production is significant — Bulgaria ranks among the top EU hemp producers by cultivated area. CBD product retail has expanded in Sofia and other cities. No significant domestic medical cannabis production industry has developed for human medicines.',
'Bulgaria is monitoring EU reform trajectories. No near-term unilateral domestic reform is expected. EFSA Novel Food rulings on CBD will influence the regulatory approach. A broader medical programme could emerge from EU-level harmonisation pressure.',
'Bulgarian Drug Agency (BDA) — bda.bg; Ministry of Health — mh.government.bg',
'Bulgarian Drug Agency regulatory guidance; EMCDDA Bulgaria country report; EU hemp cultivation statistics',
'Based on BDA public guidance and EMCDDA data. Limited domestic data on prescription volumes.',
'Annual','Legal framework; Sativex access; hemp cultivation status; CBD retail; named-patient pathway.',
DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='BG' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'bosnia-and-herzegovina','country','BA','Prohibited — No Medical Programme',
'Bosnia and Herzegovina maintains cannabis as a prohibited substance under narcotic laws in both the Federation of Bosnia and Herzegovina and Republika Srpska entities, with no medical cannabis programme established. Cannabis possession and use are criminal offences. The country has not advanced formal legislative proposals for medical or adult-use cannabis reform as of 2026. The complex bi-entity political structure makes coordinated reform challenging. Bosnia and Herzegovina is an EU candidate country; its drug policy will eventually face harmonisation pressure. The reform trajectories of neighbouring Balkan states (Serbia, North Macedonia, Croatia) with established medical programmes represent the most immediate external comparison.',
'No legal patient access pathway exists. Patients requiring cannabis-based medicines must seek informal channels or travel to neighbouring Croatia, Serbia, or North Macedonia.',
'No cannabis prescribing right exists for physicians in Bosnia and Herzegovina. Healthcare providers cannot legally recommend or prescribe cannabis.',
'No legal cannabis market exists. Hemp and CBD products are available through informal retail without legal clarity. No licensed cannabis companies operate domestically for medical production.',
'EU accession discussions and the reform trajectories of neighbouring Balkan states are the primary reform pressure points. Cannabis reform is not a current political priority for either entity government.',
'Ministry of Civil Affairs (BiH) — mcp.gov.ba; Entity health ministries',
'EMCDDA BiH country report; national narcotics law review; EU accession assessment documents',
'Based on EMCDDA country reporting and legislative review. No domestic medical cannabis registry data available.',
'Annual','Legal framework; absence of medical programme; hemp status; EU accession context.',
DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='BA' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'croatia','country','HR','Medical — Prescription Programme (Since 2015)',
'Croatia established a formal medical cannabis programme in 2015, making it one of the first countries in the Western Balkans and among the early EU member states to do so. Licensed physicians may prescribe cannabis-based medicinal products for appropriate indications, and HALMED (Croatian Agency for Medicinal Products and Medical Devices) oversees licensing for both import and domestic EU-GMP cultivation. Cannabis remains prohibited for non-medical use, with misdemeanour penalties or treatment referral applicable for personal possession. The Croatian medical cannabis market has developed steadily since 2015, with increasing patient numbers and a growing number of licensed importers and domestic producers exporting to Germany, the UK, and other EU markets.',
'Croatian patients access medical cannabis through physician prescription. The programme covers chronic pain, MS spasticity, epilepsy, and chemotherapy-related nausea. Prescriptions are dispensed at licensed pharmacies. The Croatian Health Insurance Fund (HZZO) may provide partial reimbursement for specific conditions. Patient access has improved significantly since programme inception.',
'Croatian physicians with a valid licence from the Croatian Medical Chamber (HLK) may prescribe medical cannabis for approved indications. HALMED has issued prescribing guidance. Neurology, oncology, and pain medicine specialists lead prescribing in practice. Standard controlled substance documentation is required.',
'Croatia has a small but growing medical cannabis market with several domestic EU-GMP licensed producers. Export activity to Germany, the UK, and other EU markets is increasing. Several licensed importers also supply the domestic market. Croatia has become a minor but notable EU cannabis production country.',
'Croatia is likely to continue expanding its medical programme in alignment with EU regulatory trends. HALMED may broaden approved indications and products. Croatia''s role as an EU production and export hub may grow as German market demand increases under CanG.',
'Croatian Agency for Medicinal Products and Medical Devices (HALMED) — halmed.hr; Croatian Medical Chamber (HLK) — hlk.hr; Croatian Health Insurance Fund (HZZO) — hzzo.hr',
'HALMED regulatory guidance; HZZO reimbursement documentation; EMCDDA Croatia country report',
'Based on HALMED public guidance, EMCDDA data, and published export licensing information.',
'Quarterly','Medical programme legal framework; prescribing access; HZZO reimbursement; domestic production and export; patient numbers.',
DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='HR' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'cyprus','country','CY','Medical — Prescription Programme (Since 2019); Export Hub',
'Cyprus legalised medical cannabis in 2019 under an amendment to the Narcotic Drugs and Psychotropic Substances Law, with the Ministry of Health administering the programme. Licensed physicians may prescribe cannabis-based medicinal products for approved indications, and licensing frameworks exist for both import and domestic EU-GMP cultivation. Cyprus has positioned itself as a Mediterranean pharmaceutical cannabis production hub, attracting significant international investment due to its EU membership, business environment, and strategic location. Multiple large-scale EU-GMP cultivation and processing facilities have been established with production capacity substantially exceeding domestic patient demand, targeting export to Germany, the UK, and Israel. Personal cannabis use remains illegal.',
'Cypriot patients access medical cannabis through physician prescription under Ministry of Health protocols. Approved indications include chronic pain, MS, epilepsy, PTSD, and cancer-related symptoms. Prescriptions are dispensed through licensed pharmacies. No public reimbursement scheme covers cannabis medicines; all costs are out-of-pocket.',
'Cyprus-licensed physicians may prescribe medical cannabis after completing relevant continuing medical education and registering with the Medical Council. Neurologists, pain specialists, and oncologists are the primary prescribers. A physician training and registration requirement distinguishes the Cypriot model from some EU peers.',
'Cyprus has attracted substantial cannabis investment. Multiple large-scale EU-GMP cultivation facilities are operational, with production primarily intended for export. Major international cannabis companies have incorporated or established subsidiaries in Cyprus. The domestic patient market remains small relative to production capacity.',
'Cyprus is expected to continue positioning as a Mediterranean production and export hub. The domestic patient programme may expand modestly. As German market demand grows under CanG, Cyprus-based producers are well-positioned to supply. Regulatory alignment with EU standards will remain the primary driver.',
'Cyprus Ministry of Health — mohph.gov.cy; Cyprus Medical Council — medicalcouncil.org.cy',
'Cyprus Ministry of Health regulatory guidance; EMCDDA Cyprus country report; company investor disclosures',
'Based on Ministry of Health public guidance and EMCDDA reporting. Export volume data from company public disclosures.',
'Quarterly','Medical programme legal framework; specialist prescribing; EU-GMP production capacity; export activity; domestic patient access.',
DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CY' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'czechia','country','CZ','Medical Legal (Since 2013); Adult-Use Reform Advancing',
'Czechia has one of the most progressive cannabis regulatory environments in Europe. Medical cannabis has been legal since 2013 under a structured prescription programme administered by SÚKL (State Institute for Drug Control). Personal possession of up to 10 grams for adults is effectively decriminalised through low-priority enforcement, though it remains technically an administrative offence. In 2024-2025, the Czech government advanced legislation to establish a regulated adult-use cannabis market, positioning Czechia as one of the most reform-oriented EU member states alongside Germany and Luxembourg. Medical cannabis patients number in the tens of thousands, served by a licensed import and domestic EU-GMP production system. Domestic producers supply both the Czech market and export to Germany and the UK.',
'Czech medical cannabis patients access treatment through specialist or GP prescription under the Zákon o návykových látkách. Approved indications include chronic pain, MS spasticity, nausea from chemotherapy, and epilepsy. Health insurance (VZP and others) has provided partial reimbursement for registered patients. Access barriers have decreased significantly since the programme launched.',
'Czech physicians with standard medical licences may prescribe medical cannabis without specialist restriction. SÚKL maintains a list of approved preparations. Neurologists, oncologists, and pain specialists are primary prescribers, but GPs may also prescribe. Electronic prescribing is integrated into the standard system.',
'Czechia has an active medical cannabis market with licensed domestic EU-GMP producers and importers. The CBD retail market is substantial. Informal cannabis use is widespread and the effective decriminalisation framework has created a tolerant enforcement culture. The adult-use reform, if enacted, will create a new licensed retail sector.',
'Czechia is actively advancing adult-use cannabis regulation as of 2026, making it one of the most dynamic regulatory environments in Europe. Legislative progress is expected in 2026-2027. SÚKL continues to expand the approved products list for medical use.',
'State Institute for Drug Control (SÚKL) — sukl.cz; Czech Medical Chamber — lkcr.cz; Ministry of Health — mzcr.cz',
'SÚKL regulatory guidance; EMCDDA Czechia country report; parliamentary records on adult-use legislation; licensed producer disclosures',
'Based on SÚKL guidance, EMCDDA data, and legislative tracking of adult-use reform proposals.',
'Quarterly','Medical programme; decriminalisation framework; adult-use reform progress; EU-GMP production; export activity; health insurance reimbursement.',
DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CZ' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'denmark','country','DK','Medical — Permanent Framework (Post-Pilot, 2022 Onwards)',
'Denmark ran a comprehensive four-year medical cannabis pilot programme from January 2018 to December 2021, during which licensed physicians could prescribe standardised cannabis products for specific conditions. Following pilot evaluation, Denmark established a permanent medical cannabis framework under the Danish Medicines Act administered by the Lægemiddelstyrelsen (Danish Medicines Agency). Cannabis for personal non-medical use remains prohibited, with the Christiania district of Copenhagen historically operating an open cannabis market that has faced periodic law enforcement action. Denmark has significant pharmaceutical and life sciences industry presence, and several Danish companies are active in the medical cannabis production sector.',
'Danish patients access medical cannabis through physician prescription under the permanent framework. Approved products must be authorised by Lægemiddelstyrelsen. The Danish health insurance system has provided reimbursement for qualifying patients under specific criteria. Covered conditions include MS spasticity, chronic pain, and chemotherapy-related nausea.',
'Danish licensed physicians may prescribe authorised medical cannabis products. Specialist recommendation is typically required for initial prescription. Lægemiddelstyrelsen maintains a list of authorised products. Pilot evaluation data directly informed prescribing guidelines for the permanent scheme.',
'Denmark''s medical cannabis market is served by imported products and a small number of domestic EU-GMP licensed cultivators. Export to other EU markets, particularly Germany, is increasing. The domestic patient population has grown steadily. Denmark is a notable hub for cannabis pharmaceutical research.',
'The permanent medical cannabis framework is expected to continue expanding its approved products list and potentially covered indications. Denmark is monitoring EU harmonisation developments. No near-term movement toward adult-use legislation is expected. The Christiania situation remains an ongoing policy challenge.',
'Danish Medicines Agency (Lægemiddelstyrelsen) — laegemiddelstyrelsen.dk; Ministry of Health — sum.dk',
'Lægemiddelstyrelsen regulatory guidance; pilot programme evaluation reports; EMCDDA Denmark country report',
'Based on Lægemiddelstyrelsen guidance, pilot evaluation reports, and EMCDDA data.',
'Quarterly','Permanent medical framework; prescribing access; approved product list; domestic production; export activity; pilot evaluation outcomes.',
DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='DK' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'estonia','country','EE','Medical — Named Patient Only; CBD Legal',
'Estonia has a very limited medical cannabis framework. Cannabis-based medicinal products, including Sativex, may be authorised on a named-patient basis through the State Agency of Medicines (Ravimiamet). Estonia does not have a broad-access medical programme; patients must apply for individual authorisation for specific cannabis products. The programme is minimal in patient numbers. Personal cannabis use remains prohibited with criminal penalties. Estonia has historically maintained strict drug enforcement standards and has not advanced legislative reform proposals for medical expansion or adult-use access.',
'Estonian patients seeking medical cannabis must obtain individual authorisation from Ravimiamet on a named-patient basis. No general prescription programme exists. Access is effectively restricted to patients with specialist documentation for conditions such as MS-related spasticity. Full out-of-pocket costs apply.',
'Estonian physicians may apply to Ravimiamet for named-patient authorisation to prescribe specific cannabis-based medicines. No general prescribing right exists. Neurologists and relevant specialists are typical applicants. The authorisation process is administratively burdensome.',
'The Estonian medical cannabis market is negligible. CBD product retail exists in urban areas, particularly Tallinn. No domestic medical cannabis production industry has developed.',
'Estonia is likely to follow broader EU regulatory developments on medical cannabis harmonisation but is not expected to unilaterally expand its framework in the near term. Conservative drug policy is embedded in the political consensus.',
'State Agency of Medicines (Ravimiamet) — ravimiamet.ee; Ministry of Social Affairs — sm.ee',
'Ravimiamet guidance; EMCDDA Estonia country report',
'Based on Ravimiamet public guidance and EMCDDA data.',
'Annual','Named-patient access; Sativex availability; CBD retail status; absence of general medical programme.',
DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='EE' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'finland','country','FI','Medical — Sativex via Specialist Prescription; CBD Legal',
'Finland permits medical cannabis under the Narcotic Drugs Act, administered by Fimea (Finnish Medicines Agency). Sativex is registered in Finland for MS-related spasticity and available through specialist prescription, with Kela (Social Insurance Institution) reimbursement for qualifying patients. Other cannabis preparations may be authorised on a named-patient basis but are very limited in practice. Personal cannabis use is prohibited, with Finland maintaining one of the stricter drug enforcement cultures in Northern Europe. Citizens'' initiatives on decriminalisation have gathered significant signatures but have not translated into legislative change.',
'Finnish MS patients may access Sativex through neurologist prescription with Kela reimbursement under the high-cost protection scheme. Other cannabis medicines require individual Fimea authorisation and are essentially inaccessible without exceptional circumstances. Patient numbers for cannabis medicines are estimated in the hundreds to low thousands.',
'Finnish neurologists and relevant specialists may prescribe Sativex. Named-patient requests for other cannabis preparations face significant administrative barriers. Finnish physician culture has been conservative regarding cannabis prescribing beyond the narrow Sativex indication. No general GP prescribing right exists.',
'Finland has no commercial medical cannabis market beyond the Sativex prescription segment. CBD products derived from hemp are regulated under food law through Ruokavirasto (Finnish Food Authority). No domestic medical cannabis production. Underground cannabis market is modest relative to neighbouring countries.',
'Finland is likely to remain conservative on cannabis reform in the near term. EU harmonisation and the influence of Denmark''s evolving approach may eventually prompt modest programme expansion. Fimea may align CBD guidance with EFSA rulings.',
'Finnish Medicines Agency (Fimea) — fimea.fi; Kela — kela.fi; Finnish Food Authority (Ruokavirasto) — ruokavirasto.fi',
'Fimea guidance; Kela reimbursement data; EMCDDA Finland country report',
'Based on Fimea public guidance and EMCDDA data.',
'Annual','Sativex access and Kela reimbursement; named-patient pathway; CBD food law status; absence of broad medical programme.',
DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='FI' AND jurisdiction_type='country');
