-- Replay-only foundation for the production jurisdiction data-depth task queue.
--
-- The repository contains consumers of this task table but no canonical CREATE TABLE
-- migration. The temporary table carries the columns exercised by the recovered
-- migrations. It is never a production migration or migration-ledger entry.
create table if not exists public.jurisdiction_data_depth_tasks (
  id bigint generated by default as identity primary key,
  jurisdiction_key text not null,
  dimension_key text not null,
  jurisdiction_level text,
  status text not null default 'open',
  priority integer not null default 0,
  evidence_required boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
