
INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'argentina','country','AR','Medical Legal; Adult-Use Home Cultivation Permitted',
'Argentina legalized medical cannabis in 2017 under the CANNABIS Act (Law 27.350), and Law 27.669 (2022) created a comprehensive National Regulatory Program for medicinal cannabis, industrial hemp, and scientific research. Home cultivation for personal and medical use is permitted. A regulated adult-use commercial market is under legislative development.',
'Patients access cannabis through pharmacies and licensed dispensaries under physician authorization. The national registry (REPROCANN) allows registered patients to cultivate at home. Imported and domestically produced medical products are both available through licensed channels.',
'Physicians may authorize cannabis treatment across a broad range of conditions including pain, epilepsy, anxiety, and palliative care. Prescribers must register with REPROCANN and follow national clinical guidelines. Specialist referral is not required for most conditions.',
'Argentina has a growing domestic cultivation sector supported by government investment. CONICET (national research council) licenses for research and production have expanded significantly. Exports of medicinal cannabis products began in 2021, establishing Argentina as a Southern Cone producer.',
'The regulatory framework continues to mature with adult-use legislation under discussion in Congress. Domestic producers are positioning for export markets in Europe and North America. Policy momentum strongly favors further liberalization over the 2025–2027 period.',
'ANMAT (Administración Nacional de Medicamentos, Alimentos y Tecnología Médica) regulates medical cannabis products. SENASA oversees hemp cultivation. The Secretaría de Políticas Integrales sobre Drogas (SEDRONAR) coordinates national policy.',
'ANMAT regulatory circulars; Law 27.350; Law 27.669; REPROCANN registry data','Current as of Q2 2026; verified against ANMAT official guidance','Quarterly','Full country-level briefing covering medical program, home cultivation rights, and emerging adult-use framework',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='AR' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'barbados','country','BB','Medical Legal; Decriminalized',
'Barbados legalized medical cannabis in 2019 through the Cannabis Control Authority Act. The Cannabis Control Authority (CCA) licenses cultivation, processing, retail, and research activities. Possession of small amounts has been decriminalized for personal use, and the country has positioned itself to develop a licensed cannabis tourism and export sector.',
'Registered patients obtain medical cannabis from licensed dispensaries with a physician recommendation. The CCA maintains a patient registry. Products include oils, capsules, and dried flower where licensed retail is operational.',
'Physicians registered with the Medical Council of Barbados may recommend cannabis for qualifying conditions including chronic pain, cancer, epilepsy, and PTSD. No specialist requirement; general practitioners may recommend.',
'Barbados has actively courted cannabis tourism as an economic development pillar alongside its hospitality sector. Licensed dispensaries operate in Bridgetown and resort areas. Domestic cultivation licenses have been issued to local and joint-venture operators.',
'The CCA is developing export licensing frameworks to allow Barbados to compete with regional peers for European medical cannabis market access. Further adult-use liberalization is politically possible given regional trends in Jamaica and Trinidad.',
'Cannabis Control Authority (CCA) under the Ministry of Economic Affairs and Investment.',
'CCA official gazette notices; Cannabis Control Authority Act 2019; regional regulatory monitoring','Current as of Q2 2026','Quarterly','Country-level briefing covering medical program, decriminalization, and tourism/export development',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='BB' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'belize','country','BZ','Decriminalized; No Formal Medical Program',
'Belize decriminalized possession of up to 10 grams of cannabis for personal use in 2017. There is no formally regulated medical cannabis program. Cannabis cultivation and sale outside of personal-use quantities remains illegal. Hemp has not been separately legalized.',
'No formal patient access pathway exists. Patients seeking cannabis-based medicines must import licensed pharmaceutical products, which is a complex process. No domestic dispensaries or licensed medical supply chains operate.',
'Physicians cannot formally prescribe cannabis as no medical program exists. Anecdotal therapeutic use occurs outside the regulatory framework. Medical tourism to neighboring countries with programs is not structured.',
'The domestic cannabis market is informal. No licensed commercial operators exist. Economic interest in cannabis agriculture has been expressed by farming communities given agricultural conditions, but no licensing framework has emerged.',
'Regional trends including Mexico and Costa Rica establishing medical programs may influence Belizean policy. There is civil society advocacy for medical access. No imminent legislative action anticipated.',
'Ministry of Health and Wellness. Drug enforcement falls under the Belize Police Department.',
'Belize Misuse of Drugs (Amendment) Act 2017; regional policy tracking','Current as of Q2 2026; limited official data available','Annual','Country-level briefing covering decriminalization status and absence of medical framework',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='BZ' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'bolivia','country','BO','Traditional Use Tolerated; No Formal Medical Program',
'Bolivia has a constitutionally protected tradition of coca leaf cultivation and use. Cannabis possession of small amounts is effectively decriminalized in practice, though technically illegal under Law 1008. Bolivia has not established a formal medical cannabis program. The country''s drug policy is shaped by its stance defending coca leaf sovereignty at international forums.',
'No formal patient access pathway exists for cannabis. Patients cannot obtain licensed medical cannabis products through official channels. Any therapeutic use occurs outside the legal framework.',
'Physicians cannot legally prescribe cannabis as no regulated program exists. Medical use of cannabis-derived pharmaceuticals (such as Epidiolex) may be possible through individual import authorization processes.',
'No licensed cannabis market exists. Bolivia''s drug policy focus remains on coca leaf and combating cocaine production. The informal cannabis market operates in major urban areas.',
'Bolivia''s leadership has historically focused drug policy attention on coca leaf rather than cannabis reform. Medical cannabis legislation has not advanced in Congress. Regional pressure from neighboring Argentina and Peru could prompt future action.',
'SENAD (Servicio Nacional para la Prevención y Control del Tráfico Ilícito de Drogas) handles drug enforcement. Ministry of Health oversees pharmaceutical policy.',
'Law 1008 (Ley del Régimen de la Coca y Sustancias Controladas); regional policy monitoring','Current as of Q2 2026','Annual','Country-level briefing covering traditional use context and absence of medical program',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='BO' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'brazil','country','BR','Medical Legal (CBD and THC Products); No Adult-Use',
'Brazil has progressively expanded medical cannabis access since 2015, when ANVISA first permitted CBD-based products. In 2019, THC-containing cannabis products were authorized for medical use. In 2020 and 2021, ANVISA issued comprehensive resolutions establishing licensing for domestic cultivation and industrial production. Brazil is now one of Latin America''s largest medical cannabis markets by patient volume.',
'Patients access cannabis through physician prescription with ANVISA-registered products available at licensed pharmacies. Both imported products (primarily from Canada and Portugal) and domestically produced items are available. Patient registry requirements apply. Costs remain a barrier for lower-income patients, though government reimbursement discussions are ongoing.',
'Physicians registered with the Conselho Federal de Medicina may prescribe authorized cannabis products for conditions including epilepsy, chronic pain, Parkinson''s disease, anxiety, and others. Prescriptions must specify approved products. No specialist-only restriction applies though complexity of conditions may direct patients to specialists.',
'The Brazilian medical cannabis market is estimated at one of the fastest-growing in the Americas, with over 100,000 patients registered by 2025. Domestic production licenses have been issued to multiple companies. International players including Canadian LPs and Portuguese operators have established import partnerships. Market value projections exceed USD 1 billion by 2027.',
'ANVISA continues to refine cultivation and processing regulations. Adult-use legalization is debated in Congress but faces significant opposition from conservative and religious blocs. Medical market expansion with insurance reimbursement is the more likely near-term development. Export potential for domestically produced cannabis is under policy review.',
'ANVISA (Agência Nacional de Vigilância Sanitária) is the primary regulator for medical cannabis products, licensing, and standards. The Conselho Federal de Medicina sets prescriber guidelines.',
'ANVISA Resolution RDC No. 327/2019; Resolution RDC No. 660/2022; ANVISA licensed product list; Conselho Federal de Medicina guidelines','Current as of Q2 2026; verified against ANVISA official registry','Quarterly','Full country-level briefing covering medical program depth, domestic production, and market scale',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='BR' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'chile','country','CL','Medical Legal; Home Cultivation Permitted; No Adult-Use Sale',
'Chile established one of Latin America''s most progressive medical cannabis frameworks, with Law 20.000 amended to permit medical and therapeutic cultivation and Law 21.020 enabling regulated medical access. Home cultivation for personal medical use is permitted. The Chilean Cannabis Institute (ICAL) and private operators supply regulated products. No adult-use commercial market exists, though possession of small amounts is decriminalized.',
'Patients access medical cannabis through licensed pharmacies with a physician prescription. Home cultivation of up to six plants is tolerated for personal medical use. The ISP (Instituto de Salud Pública) maintains a registry of authorized products. Affordability programs exist for low-income patients through public hospital channels.',
'Physicians may prescribe authorized cannabis products for a wide range of conditions. Both public and private sector physicians can prescribe. The Colegio Médico de Chile has issued guidance supporting evidence-based prescription.',
'Chile has a relatively mature medical cannabis supply chain with domestic cultivation, extraction, and pharmaceutical preparation licensed. Exports have begun to European markets, particularly Germany. The market is valued in the hundreds of millions of USD and growing. Several international companies operate in partnership with Chilean growers.',
'Chile''s regulatory framework is among the most developed in South America. Adult-use legalization has public support in polling but has not advanced legislatively. Export market development is a government economic priority. Regulatory refinements for quality standards and GMP compliance are ongoing.',
'ISP (Instituto de Salud Pública de Chile) regulates medical cannabis products. SAG (Servicio Agrícola y Ganadero) licenses cultivation. MINSAL (Ministerio de Salud) sets clinical guidelines.',
'ISP resolution database; Law 20.000 amendments; Law 21.020; SAG cultivation license registry','Current as of Q2 2026; verified against ISP official guidance','Quarterly','Full country-level briefing covering medical access, home cultivation, domestic production, and export activity',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CL' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'costa-rica','country','CR','Medical Legal; No Adult-Use',
'Costa Rica passed Law 10113 in 2022, legalizing medical and therapeutic cannabis and industrial hemp. The law created a licensing system for cultivation, processing, distribution, and research. Implementation regulations have been progressively issued. Costa Rica''s medical cannabis market is in early commercial development as of 2026.',
'Patients access medical cannabis through pharmacies with a valid medical prescription. Licensed importers and domestic producers supply authorized products. Patient costs are currently borne by individuals; social security (CCSS) reimbursement has not yet been implemented.',
'Physicians registered with the Colegio de Médicos y Cirujanos de Costa Rica may prescribe cannabis for qualifying conditions. No specialist-only requirement applies. Clinical guidelines are being developed by the Ministry of Health.',
'Domestic cultivation and processing licenses are being issued under the new framework. Several international cannabis companies have established Costa Rican operations or partnerships, attracted by the country''s agricultural infrastructure and trade relationships. The market is nascent but has strong growth potential.',
'The regulatory framework under Law 10113 continues to be implemented. Adult-use is not on the current legislative agenda. Export market access, particularly to Europe, is a potential economic driver. Clarity on GMP and export certification requirements is expected in 2026–2027.',
'MINISTERIO DE SALUD (Ministry of Health) and the Servicio Nacional de Salud Animal (SENASA) for hemp. MINAE may have involvement for environmental compliance in cultivation.',
'Law 10113 (2022); Ministry of Health implementing regulations; Costa Rica Cannabis Chamber (industry body) reports','Current as of Q2 2026','Quarterly','Country-level briefing covering medical program establishment and early market development',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CR' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'cuba','country','CU','Prohibited',
'Cannabis is prohibited in Cuba under the Ley de la Salud Pública and criminal drug laws. There is no medical cannabis program and no decriminalization framework. The Cuban government has not publicly engaged with cannabis reform at the legislative level.',
'No legal patient access pathway exists. Patients cannot obtain cannabis-based medicines through Cuban healthcare channels. Any therapeutic use of cannabis occurs outside the legal framework.',
'Cuban physicians cannot prescribe cannabis or cannabis-derived products as no regulatory pathway exists. The Cuban healthcare system does not include cannabis-based therapies in its formulary.',
'No licensed cannabis market exists. Cuba''s centrally planned economy and strict drug enforcement make commercial cannabis activity effectively impossible. No foreign investment in cannabis has occurred.',
'Cannabis reform is not a visible policy priority for the Cuban government. Given the political context, significant regulatory change in the near term is unlikely. Regional trends in Caribbean neighbours such as Jamaica and Barbados have not influenced Cuban policy visibly.',
'MINSAP (Ministerio de Salud Pública) and MININT (Ministerio del Interior) oversee health and drug enforcement policy respectively.',
'Cuban criminal code; MINSAP pharmaceutical policy; regional comparative analysis','Current as of Q2 2026','Annual','Country-level briefing noting prohibited status and absence of reform pathway',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CU' AND jurisdiction_type='country');
