UPDATE cc_jurisdiction_briefings SET
  public_summary = 'Australia operates a nationally regulated medical cannabis framework administered by the Therapeutic Goods Administration (TGA) and the Office of Drug Control (ODC). The Special Access Scheme (SAS) and Authorised Prescriber (AP) pathway enable patients to access unapproved cannabis medicines. The April 2021 SAS-B reforms were transformative — they streamlined prescriber approval, eliminated mandatory specialist referral for most products, and produced a rapid expansion of patient numbers from ~30,000 in early 2021 to over 350,000 registered patients nationally by mid-2026. Adult-use cannabis remains federally prohibited under the Criminal Code Act 1995, though the ACT territory enacted personal decriminalisation in 2020 (personal possession up to 50g, cultivation up to 2 plants). Australia is a net exporter of medical cannabis oil and dried flower, with licensed producers exporting to Germany, the UK, and New Zealand.',
  patient_access = 'Patients access medical cannabis through GP or specialist SAS-B approvals (most products) or through Authorised Prescriber arrangements. SAS-B approvals are now largely self-managed by practitioners via the TGA''s Electronic SAS portal. Patient registration is maintained by individual approved prescribers; there is no national patient card system. Products range from CBD isolates and THC/CBD oils to dried flower for vaporisation. Pharmacy dispensing is the standard delivery mechanism. Many patients use dedicated cannabis clinics for initial consultations; telehealth is widely used across all states and territories.',
  physician_access = 'Since the April 2021 SAS reforms, any Australian-registered medical practitioner (GP or specialist) may prescribe most medical cannabis products under SAS-B without prior TGA individual approval. Products on the Therapeutic Goods Register (TGR) — predominantly CBD products — require no SAS approval. High-THC products and novel formulations still require SAS-B application. Authorised Prescriber status, available to specialists treating defined patient populations, allows repeated prescribing without individual SAS applications.',
  market_dynamics = 'Australia''s medical cannabis market was valued at approximately A$750M–900M in 2025 and is growing at 25–35% annually. Approximately 180+ licensed producers, importers, and manufacturers hold ODC licences. Dominant domestic players include Little Green Pharma, Cannatrek, Cann Group, and BOD Science. International supply from Canada, the Netherlands, and Israel supplements domestic production. The dried flower segment has grown fastest since vaporisation-device availability expanded. Cost remains a significant patient access barrier: typical patient spend is A$150–400/month, largely uncovered by Medicare.',
  regulatory_outlook = 'The TGA continues to refine the SAS framework. A formal review of medical cannabis scheduling is underway; rescheduling THC from Schedule 8 to a lower schedule for medical products is under active policy consideration as of mid-2026. Adult-use legalisation at the federal level remains politically sensitive — the Greens advocate for it; Labor has not committed; the Coalition opposes it.',
  data_source_summary = 'TGA SAS patient and prescriber data; ODC licensed producer, importer, and manufacturer lists; TGA Therapeutic Goods Register; ABS health survey data; KPMG/Arcview Australia market research',
  verification_summary = 'Current as of Q2 2026; verified against TGA and ODC official data',
  update_cadence = 'Quarterly',
  last_reviewed_date = DATE '2026-06-22'
WHERE country_iso2 = 'AU' AND jurisdiction_type = 'country';

UPDATE cc_jurisdiction_briefings SET
  public_summary = 'Canada was the second country globally (after Uruguay) and the first G7 nation to legalise adult-use cannabis nationally, via the Cannabis Act (Bill C-45, in force October 17 2018). The federal framework establishes possession limits (up to 30g in public), home cultivation rights (up to 4 plants per household), and minimum standards for retail licensing, product safety, and packaging. Each of the 10 provinces and 3 territories regulates its own retail distribution model — ranging from government monopolies (Quebec SQDC, Nova Scotia NSLC) to fully private markets (Alberta, Newfoundland). Over 4,000 licensed retail storefronts operate nationally as of mid-2026, generating approximately $6.0–7.5B CAD in annual legal retail sales. Canada is also a major medical cannabis jurisdiction serving over 500,000 registered patients.',
  patient_access = 'Medical patients register directly with federally licensed producers (LPs) under the ACMPR framework. Physicians or nurse practitioners authorise medical cannabis documents (not prescriptions); patients choose their LP and order directly via mail. No physical dispensaries are dedicated to medical-only patients; however, many retail stores also serve medical patients. Most provincial drug plans do not cover cannabis; WorkSafeBC and some First Nations health programs are exceptions.',
  physician_access = 'Canadian physicians and nurse practitioners may authorise cannabis under Health Canada''s ACMPR framework. There are no caps on the volume or number of authorisations. The Canadian Medical Association has issued guidance recommending caution for patients under 25, but these are not regulatory restrictions. Practitioners must complete a standard medical document specifying daily quantity.',
  market_dynamics = 'Canada''s legal cannabis market is the world''s most mature regulated market by years of operation. Legal retail has captured an estimated 75–80% of total cannabis market share nationally by 2026, up from ~25% at legalisation. Price compression has been dramatic — legal flower retails for as low as $4–6 CAD/gram in competitive provincial markets (Alberta, Ontario). Major LPs include Tilray, Canopy Growth, Aurora, Cronos, and HEXO; the sector has undergone significant consolidation. Export to Germany and Australia has become a strategic revenue stream for leading LPs.',
  regulatory_outlook = 'Health Canada is reviewing the Cannabis Act framework — a mandatory five-year review was completed in 2023 with recommendations including edibles reform, social equity provisions, and medical access improvements. Indigenous cannabis sovereignty — self-government nations operating outside provincial frameworks — is an evolving legal frontier.',
  data_source_summary = 'Health Canada Cannabis Act annual reports; Statistics Canada retail sales data; provincial regulatory authority data (AGCO, LCRB, AGLC, SQDC, etc.); Cannabis Council of Canada industry data',
  verification_summary = 'Current as of Q2 2026; verified against Health Canada and Statistics Canada official data',
  update_cadence = 'Quarterly',
  last_reviewed_date = DATE '2026-06-22'
WHERE country_iso2 = 'CA' AND jurisdiction_type = 'country';

UPDATE cc_jurisdiction_briefings SET
  public_summary = 'Germany enacted the Cannabisgesetz (CanG) which came into force on April 1 2024, making Germany the largest cannabis market in Europe to implement adult-use reform (Phase 1). Under CanG Phase 1, adults 18+ may possess up to 25g in public and 50g at home, cultivate up to 3 plants, and join non-commercial Cannabis Social Clubs (Anbauvereinigungen / CSCs) of up to 500 members. No commercial cannabis retail is permitted under Phase 1. Phase 2 of CanG, establishing a regulated commercial retail pilot in select regions, is pending federal authorisation. Germany''s medical cannabis programme has been in place since 2017 and now serves approximately 250,000+ registered patients.',
  patient_access = 'Medical cannabis patients in Germany access products through licensed pharmacies following physician prescription. Since CanG, medical cannabis products are also covered by statutory health insurance (GKV) for approved indications. Products dispensed include dried flower (for vaporisation), oils, extracts, and capsules. BfArM (Bundesinstitut für Arzneimittel und Medizinprodukte) oversees medical cannabis quality standards.',
  physician_access = 'German physicians (Fachärzte and general practitioners) may prescribe medical cannabis under SGB V (statutory insurance code). Following CanG, GKV reimbursement is available for serious conditions where other treatments have failed or are inappropriate. Private prescription (PKV) is also available without the GKV evidence threshold.',
  market_dynamics = 'Germany is Europe''s largest medical cannabis market, generating approximately €800M–1.2B EUR annually. Post-CanG Phase 1, CSC formation has been uneven across Länder — progressive city-states (Berlin, Hamburg, Bremen) have issued many permits; Bavaria has blocked most applications. Canada, the Netherlands, Portugal, and Australia are the dominant import suppliers.',
  regulatory_outlook = 'Germany''s cannabis regulatory outlook is the most consequential in Europe. Phase 2 commercial retail pilot implementation timing remains uncertain as of mid-2026. The CDU/CSU has stated it would repeal CanG if it returns to federal government. Medical cannabis is broadly supported and unlikely to be reversed. Germany''s approach is closely watched by France, Italy, Spain, Austria, and Switzerland.',
  data_source_summary = 'BfArM medical cannabis quarterly data; Cannabisgesetz (CanG) federal legislation; Bundesrat voting records; Länder health ministry publications; IMC industry data',
  verification_summary = 'Current as of Q2 2026; verified against BfArM official data and CanG federal legislation',
  update_cadence = 'Quarterly',
  last_reviewed_date = DATE '2026-06-22'
WHERE country_iso2 = 'DE' AND jurisdiction_type = 'country';

UPDATE cc_jurisdiction_briefings SET
  public_summary = 'The Netherlands maintains its iconic gedoogbeleid (tolerance policy) for cannabis — technically illegal under the Opium Act but tolerated for personal use and retail via licensed coffeeshops since the 1970s. Approximately 570 licensed coffeeshops operate nationwide. The fundamental legal contradiction (tolerated retail but unregulated supply — the "back door problem") is being addressed by the Experiment Gesloten Coffeeshopketen (EGCC) — the closed cannabis supply chain experiment — which began in pilot municipalities (Breda, Tilburg, and others) in 2023. Cannabis for medical use is available through the Bureau for Medicinal Cannabis (BMC) at pharmacies via physician prescription.',
  patient_access = 'Dutch medical cannabis patients access products through pharmacies with a physician prescription. The BMC manages the supply of standardised medical cannabis products (dried flower varieties: Bedrocan, Bedrobinol, Bediol, Bedica, Bedrolite). Zorgverzekeringswet (ZVW) health insurance covers medical cannabis for certain indications (notably multiple sclerosis, chronic pain with specific failed treatments).',
  physician_access = 'Dutch physicians prescribe medical cannabis under standard prescription authority. No specialist-only restriction exists. The KNMG (Royal Dutch Medical Association) has issued practice guidance. Medical cannabis can be prescribed for pain, nausea (oncology/HIV), multiple sclerosis spasticity, Tourette syndrome, and other indications.',
  market_dynamics = 'The Netherlands'' coffeeshop market generates approximately €1.0–1.5B EUR annually. Amsterdam''s coffeeshops account for approximately 30–40% of national coffeeshop revenue. The EGCC supply chain experiment is transitioning supply from illicit to licensed domestic cultivators. The experiment''s success is being monitored as a potential model for full national legalisation.',
  regulatory_outlook = 'The Netherlands is at a pivotal regulatory juncture. The EGCC experiment is the most significant cannabis policy development in Dutch history since the coffeeshop system was established. If deemed successful, the Dutch government may proceed to full national commercial cannabis legalisation. Political consensus is fragile: the Schoof coalition has maintained the experiment but full legalisation is not yet committed.',
  data_source_summary = 'Dutch Ministry of Justice and Security cannabis policy documents; BMC official data; Trimbos Instituut cannabis monitor; EGCC experiment progress reports; CBS (Statistics Netherlands) data',
  verification_summary = 'Current as of Q2 2026; verified against BMC official data and EGCC published progress reports',
  update_cadence = 'Quarterly',
  last_reviewed_date = DATE '2026-06-22'
WHERE country_iso2 = 'NL' AND jurisdiction_type = 'country';

UPDATE cc_jurisdiction_briefings SET
  public_summary = 'Spain has a distinctive de facto cannabis tolerance system based on constitutional privacy rights. Cannabis for personal private use (consumo privado) is decriminalised by interpretation of Article 18 of the Spanish Constitution. This has produced the Cannabis Social Club (CSC) model — member-only private associations that cultivate and distribute cannabis collectively to adult members. Approximately 700–1,000 CSCs operate across Spain, concentrated in Catalonia (Barcelona), the Basque Country, and other regions. Medical cannabis in the formal pharmaceutical sense is not available in Spain; Sativex (nabiximols) is the only approved cannabis-based medicine.',
  patient_access = 'Formal medical cannabis access in Spain is extremely limited. Sativex (nabiximols spray) is approved for multiple sclerosis spasticity and is reimbursable through the SNS for this specific indication. No broader medical cannabis programme exists. Patients with other conditions who seek cannabis access do so through CSC membership.',
  physician_access = 'Spanish physicians may prescribe Sativex for approved indications through normal pharmaceutical prescribing channels. No broader cannabis prescribing authority exists. Spanish medical associations (OMC) have called for a regulated medical cannabis framework but no legislation has been enacted.',
  market_dynamics = 'Spain''s CSC market is one of the most developed informal cannabis markets in Europe. Barcelona alone has hundreds of CSCs. Annual market value through CSCs is estimated at €500M–800M. CSC legal status remains contested — the Supreme Court (Tribunal Supremo) has issued limiting decisions on the "shared consumption" doctrine.',
  regulatory_outlook = 'Spain''s cannabis regulatory status is in active evolution. The PSOE-Sumar governing coalition commissioned a parliamentary cannabis commission report (completed 2023) recommending a regulated framework, but no legislation has been enacted as of mid-2026. The Basque Country''s CSC regulation (Ley 1/2017) has survived constitutional challenge and provides the most stable subnational framework.',
  data_source_summary = 'Spanish Ministry of Health (MSCBS) drug policy publications; FAC (Federación de Asociaciones Cannábicas) data; EMCDDA Spain country report; Tribunal Supremo rulings',
  verification_summary = 'Current as of Q2 2026; verified against Spanish government official publications and EMCDDA data',
  update_cadence = 'Quarterly',
  last_reviewed_date = DATE '2026-06-22'
WHERE country_iso2 = 'ES' AND jurisdiction_type = 'country';

UPDATE cc_jurisdiction_briefings SET
  public_summary = 'Israel is a world leader in medical cannabis research and has one of the most developed medical cannabis access frameworks in the Middle East. Medical cannabis has been available since the early 2000s through a Health Ministry permit system. The programme underwent major reform in 2019 (Reform T2019) and again in 2022, shifting from specialist-only prescribing to a GP-accessible pathway and dramatically expanding patient numbers. Over 130,000 registered medical cannabis patients exist in Israel as of mid-2026 — one of the highest per-capita rates in the world. Israel also permits cannabis export to EU countries. Adult-use cannabis legalisation was advanced legislatively in 2022–2023 (the Edelstein bill) but the government collapsed before final passage.',
  patient_access = 'Israeli medical cannabis patients access cannabis via licensed pharmacies and dedicated medical cannabis pharmacies following a physician prescription. The permit system has been streamlined — initial approval now takes weeks rather than months. Products include dried flower, oils, capsules, and inhalers. Medical cannabis is not covered by Kupat Holim (HMO) health funds except for specific palliative care indications; most patients pay out-of-pocket (approximately ₪800–2,000/month).',
  physician_access = 'Following the 2022 reform, Israeli family physicians (GPs) can prescribe medical cannabis for an expanded list of indications without specialist referral. Physicians prescribe via the Ministry of Health''s digital prescription system. Israel has the highest physician familiarity with medical cannabis of any non-North American jurisdiction.',
  market_dynamics = 'Israel''s medical cannabis market generates approximately ₪2.5–3.5B ILS annually. Approximately 20–25 licensed producers operate, including Tikun Olam, InterCure, IM Cannabis, and Canndoc. Israel is a significant cannabis research hub tracing back to Prof. Raphael Mechoulam''s isolation of THC (1964). Cannabis export to Germany, Switzerland, and Australia generates foreign currency revenue.',
  regulatory_outlook = 'Israel''s regulatory posture is stable on the medical side. Adult-use legalisation has broad public support (~60–70% in polls) but faces political obstacles — coalition politics and security preoccupations have deprioritised it. The security situation (regional instability) affects regulatory bandwidth and political capacity for non-security legislation.',
  data_source_summary = 'Israel Ministry of Health (Misrad HaBriut) medical cannabis programme data; Israel Medical Cannabis (IMC) association industry data; Canndoc/InterCure investor disclosures; Hebrew University cannabis research publications',
  verification_summary = 'Current as of Q2 2026; verified against Israel Ministry of Health official patient data',
  update_cadence = 'Quarterly',
  last_reviewed_date = DATE '2026-06-22'
WHERE country_iso2 = 'IL' AND jurisdiction_type = 'country';

UPDATE cc_jurisdiction_briefings SET
  public_summary = 'Thailand made Southeast Asia''s most dramatic cannabis policy pivot in 2022, decriminalising cannabis by removing it from the Category 5 narcotics list (effective June 9 2022). This produced a rapid proliferation of cannabis shops estimated at 6,000–10,000 across the country by 2023. However, a significant legal gap emerged: recreational use was not explicitly legalised, only decriminalised by omission. The Narcotics Act provisions criminalising "intoxicating" cannabis use remained in force. The incoming Pheu Thai-led government (August 2023) announced intent to re-criminalise recreational cannabis. As of mid-2026, a revised Cannabis and Hemp Act is before parliament — the direction is toward a medical-only framework with stricter retail controls.',
  patient_access = 'Medical cannabis is available in Thailand through the Government Pharmaceutical Organisation (GPO) and licensed medical providers following physician recommendation. The TFDA regulates medical cannabis products. Selected public hospitals and private clinics offer cannabis-based consultations. Products include cannabis-infused herbal preparations rooted in traditional Thai medicine, oils, and standardised pharmaceutical products.',
  physician_access = 'Thai physicians registered with the Medical Council of Thailand may recommend cannabis for therapeutic purposes. Traditional Thai medicine practitioners (mor phaen boran) may also recommend cannabis in herbal medicine formulations. The regulatory framework for physician cannabis prescribing is still evolving as the Cannabis and Hemp Act progresses through parliament.',
  market_dynamics = 'The 2022 decriminalisation produced a chaotic but commercially vibrant market. Cannabis cafés and dispensaries proliferated in Bangkok, Chiang Mai, Koh Samui, and Phuket, heavily targeting the tourist market. Revenue estimates range widely ($1–3B USD annually at peak), though market compression is occurring as re-regulation uncertainty creates investor caution.',
  regulatory_outlook = 'Thailand''s cannabis regulatory environment is the most volatile of any major jurisdiction. The Cannabis and Hemp Act''s passage and final content will determine whether Thailand moves to a medical-only system or another framework. International regulatory watchers have significant interest in Thailand''s outcome as a precedent-setting emerging Asian market.',
  data_source_summary = 'Thailand Food and Drug Administration (TFDA) cannabis regulatory data; Thai government parliamentary records; Bangkok Post and The Nation reporting; EMCDDA global trends; WHO cannabis policy reviews',
  verification_summary = 'Current as of Q2 2026; verified against TFDA official publications and Thai government parliamentary records',
  update_cadence = 'Quarterly',
  last_reviewed_date = DATE '2026-06-22'
WHERE country_iso2 = 'TH' AND jurisdiction_type = 'country';

UPDATE cc_jurisdiction_briefings SET
  public_summary = 'France applies one of the strictest cannabis prohibition frameworks among Western European nations. Under the Loi du 31 décembre 1970, cannabis use is a criminal offence, though a 2020 reform introduced a fixed civil penalty (amende forfaitaire délictuelle / AFD) of €200 for simple use. Cultivation, sale, and trafficking remain serious criminal offences. France is the largest cannabis consumer market in Europe by volume (approximately 5M regular users) despite full prohibition. A medical cannabis experiment (ECUM) was launched in 2021, later expanded and extended through 2025–2026. CBD products with <0.3% THC are legal following ECJ rulings (2020), producing a €500M+ CBD market.',
  patient_access = 'French medical cannabis access is limited to participants in the ECUM experiment — approximately 3,000–6,000 patients with specific serious conditions including treatment-resistant epilepsy, refractory pain, oncology/palliative care, multiple sclerosis spasticity, and oncology-related nausea. ECUM products are dispensed through participating hospital pharmacies at no cost to patients.',
  physician_access = 'Only ECUM-participating specialist physicians may recommend cannabis for ECUM patients. GPs are not authorised to participate. The ANSM (Agence nationale de sécurité du médicament et des produits de santé) oversees ECUM physician participation and product authorisation.',
  market_dynamics = 'France''s legal cannabis market is limited to CBD products and the ECUM experiment. The CBD retail market (flowers, oils, cosmetics) is valued at approximately €500M–700M annually. France is a significant illicit cannabis consumer market driven entirely by illicit supply (domestic cultivation and imports from Morocco, Spain, the Netherlands).',
  regulatory_outlook = 'France''s cannabis regulatory posture is slowly evolving. ECUM extension signals growing medical acceptance. The SENAT cannabis working group has produced reports recommending regulated adult-use legalisation, but no legislation has been introduced. France''s influence within the EU drug policy framework means its eventual policy change would have significant European ripple effects.',
  data_source_summary = 'ANSM ECUM official publications; OFDT annual report; Légifrance legislation; MILDECA policy documents',
  verification_summary = 'Current as of Q2 2026; verified against ANSM and OFDT official publications',
  update_cadence = 'Quarterly',
  last_reviewed_date = DATE '2026-06-22'
WHERE country_iso2 = 'FR' AND jurisdiction_type = 'country';

UPDATE cc_jurisdiction_briefings SET
  public_summary = 'The United Kingdom operates a medical cannabis framework established in November 2018 when cannabis was rescheduled from Schedule 1 to Schedule 2 of the Misuse of Drugs Regulations, enabling specialist physician prescribing of cannabis-based products for medicinal use (CBPMs). Approximately 200,000+ patients have been prescribed CBPMs as of mid-2026. However, NHS prescribing of CBPMs remains extremely limited; the vast majority of UK patients access cannabis through private specialist clinics and pay privately (approximately £100–400/month). Adult-use cannabis remains a Class B controlled drug under the Misuse of Drugs Act 1971.',
  patient_access = 'UK patients access CBPMs exclusively through licensed private specialist clinics or via rare NHS prescribing (limited to specific paediatric epilepsy cases and multiple sclerosis spasticity via Sativex). The private clinic model (Curaleaf UK, Sapphire Medical, Releaf, and others) offers specialist consultations, CBPM prescription, and home delivery. UK medical cannabis products are classified as unlicensed specials sourced primarily from Canada, the Netherlands, Portugal, Australia, and Germany.',
  physician_access = 'CBPMs can only be prescribed by specialist physicians (Consultants) on the GMC Specialist Register — GPs are not authorised to initiate CBPM prescriptions. Qualifying specialties include neurology, oncology, pain medicine, psychiatry, and palliative care. NICE has issued limited guidance; the gap between NICE evidence standards and clinical reality has constrained NHS prescribing.',
  market_dynamics = 'The UK CBPM market is estimated at £400M–600M annually. Approximately 20–30 specialist cannabis clinic companies operate. Canadian, Australian, Portuguese, and Israeli LPs dominate UK supply. The UK has no significant domestic licensed cannabis production for medical purposes. The private pay model creates a significant access equity issue.',
  regulatory_outlook = 'UK cannabis regulatory posture is at a crossroads. Medical reform is widely viewed as incomplete given the NHS access gap. The Labour government elected in 2024 has not made cannabis reform a priority but has not excluded it. Adult-use legalisation polling shows growing public support (50–60% in 2024–2026 surveys).',
  data_source_summary = 'MHRA CBPM licensing data; NHS England prescribing statistics; UK Cannabis Industry Council (UKCIC) market data; Drug Science Project Twenty21 results; ACMD reports; Home Office controlled drugs statistics',
  verification_summary = 'Current as of Q2 2026; verified against MHRA and NHS England official data',
  update_cadence = 'Quarterly',
  last_reviewed_date = DATE '2026-06-22'
WHERE country_iso2 = 'GB' AND jurisdiction_type = 'country';

UPDATE cc_jurisdiction_briefings SET
  public_summary = 'The United States has a bifurcated cannabis legal landscape: federal prohibition under the Controlled Substances Act (CSA, Schedule I) coexists with state-level adult-use legalisation in 24 states + DC + 2 territories (USVI, CNMI), medical-only programmes in an additional 14 states, and full prohibition in only a handful of states. The Biden Administration initiated federal rescheduling proceedings in 2023 (DEA proposed rescheduling to Schedule III); as of mid-2026 the process was still working through administrative and potential judicial challenges. Federal rescheduling to Schedule III would not legalise cannabis commercially but would meaningfully change tax treatment (280E repeal) and banking access.',
  patient_access = 'Medical cannabis patient access varies dramatically by state. In adult-use legal states, medical programmes often coexist with recreational retail — medical patients may benefit from lower tax rates and higher purchase limits. In medical-only states, patients register through state health department programmes. The number of medical cannabis patients nationally exceeds 5 million registered patients. Interstate commerce in cannabis remains federally illegal.',
  physician_access = 'US physicians recommend (not prescribe — Schedule I prohibition prevents DEA-registered prescribing) medical cannabis in states with medical programmes. Physicians issue written recommendations or certifications; patients then apply to the state health department for a medical cannabis card. Telehealth medical cannabis recommendations have become widely available since 2020.',
  market_dynamics = 'The US cannabis industry is the world''s largest legal market by revenue — estimated at $30–35B USD in total legal cannabis sales in 2025. The industry remains profoundly fragmented by state-level isolation (no interstate commerce), taxed at punishing rates due to federal 280E treatment, and denied normal banking access. Major multi-state operators (MSOs) include Curaleaf, Green Thumb Industries (GTI), Trulieve, Verano, and Cresco Labs.',
  regulatory_outlook = 'Federal rescheduling to Schedule III is the most consequential near-term regulatory development. If finalised, it would end 280E disallowance, potentially enable SAFE Banking Act passage, and open research pathways. It would NOT legalise interstate commerce or enable national brands. The 2026 and 2028 election cycles will shape the federal regulatory trajectory significantly.',
  data_source_summary = 'DEA rescheduling docket; MJBizDaily US market data; BDSA/Headset state market analytics; Congressional Research Service cannabis reports; FinCEN cannabis banking reports; individual state cannabis authority data',
  verification_summary = 'Current as of Q2 2026; verified against DEA federal register, state cannabis authority data, and MJBizDaily industry research',
  update_cadence = 'Quarterly',
  last_reviewed_date = DATE '2026-06-22'
WHERE country_iso2 = 'US' AND jurisdiction_type = 'country';

UPDATE cc_jurisdiction_briefings SET
  public_summary = 'Colombia was the first country in Latin America to establish a comprehensive regulated medical cannabis framework. Law 1787 of 2016 legalised medical cannabis, and Decree 631 of 2020 created the export licensing framework that has made Colombia a significant global medical cannabis producer. Colombia benefits from ideal growing conditions (tropical climate, near-equatorial light cycles, low-cost labour), making it one of the lowest-cost producers globally. Domestic adult-use remains legally ambiguous — the Constitutional Court decriminalised personal possession (up to 20g) in 1994 (Sentence C-221/94), but selling, buying, and public use remain prohibited. A 2023 bill to legalise adult-use cannabis passed the Senate but not the House; the Petro government has expressed support for adult-use legalisation.',
  patient_access = 'Colombian medical cannabis patients access products through licensed pharmacies and medical dispensaries authorised under the Law 1787 framework. The Ministry of Health (MinSalud) administers patient access. Products include standardised oils, capsules, and dried flower. Domestic medical cannabis is very affordably priced given Colombia''s low production costs. Patient registration is managed through the INVIMA regulatory framework.',
  physician_access = 'Colombian physicians may recommend medical cannabis for qualified patients under the Law 1787 framework. INVIMA oversees product approvals. The Colombian Medical Federation has engaged with cannabis prescribing guidelines. No specialist-only restriction exists at the national level.',
  market_dynamics = 'Colombia is primarily an export market for medical cannabis. Over 1,000 cultivation and production licences have been issued. Major Colombian cannabis companies include Clever Leaves, Khiron Life Sciences, Flora Growth, and PharmaLeaf Colombia. Export destinations include Germany, the UK, Australia, Brazil, and Mexico. Colombia''s cost advantage (production cost as low as $0.10–0.30/gram dried flower) makes it highly competitive globally.',
  regulatory_outlook = 'Colombia''s Petro government (2022–2026) has been the most cannabis-supportive in the country''s history. Adult-use legalisation faces legislative obstacles from conservative parties. If it passes, Colombia would become the first country in South America to fully legalise cannabis. The export framework is stable and well-regarded by importing countries'' regulators.',
  data_source_summary = 'Colombia Ministry of Justice cannabis policy data; INVIMA licensing registry; Colombia Ministerio de Salud y Protección Social publications; Clever Leaves/Khiron investor disclosures; EMCDDA Colombia country data',
  verification_summary = 'Current as of Q2 2026; verified against INVIMA and Colombian government official publications',
  update_cadence = 'Quarterly',
  last_reviewed_date = DATE '2026-06-22'
WHERE country_iso2 = 'CO' AND jurisdiction_type = 'country';
