-- Sources for jurisdiction_playbooks batch 21 (part A of B, see batch21b for
-- playbook content + market metrics). Split across two files due to payload size.

INSERT INTO public.source_registry (source_name, source_url, country, iso, region, tier, adapter, crawl_cadence, source_type, notes)
VALUES
  ('Cannabiz Africa / Cannabis Law Report — Lesotho Completely Overhauls Cannabis Oversight', 'https://cannabislaw.report/cannabiz-africa-report-lesotho-completely-overhauls-cannabis-oversight-with-new-regulations-expected-soon/', 'Lesotho', 'LS', 'Africa', 1, 'html_snapshot', 'monthly', 'news', 'May 2026: LeMeRA + Lesotho Narcotics Bureau formed, new regulations gazetted Dec 2025, technical rules due Q2 2026/7 fiscal year, marketing authorization pathway confirmed'),
  ('GrowerIQ — Africa''s Cannabis Frontier: South Africa and Lesotho 2026', 'https://groweriq.ca/2026/06/23/africa-cannabis-frontier-south-africa-lesotho-2026/', 'Lesotho', 'LS', 'Africa', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'Only 17 of 140 historical licences active at assessment, 1 of 33 licensees GMP-certified, structural export/testing bottlenecks documented, 1% outdoor THC limit'),
  ('PMC — Envisaging challenges for the emerging medicinal Cannabis sector in Lesotho', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11097424/', 'Lesotho', 'LS', 'Africa', 1, 'html_snapshot', 'annual', 'academic', 'Peer-reviewed academic study: 33 companies licensed, 8 registered, 1 GMP-certified, SMME exclusion critique, first licence issued 2017 (MG Health)'),
  ('Cannavigia — Cannabis Compliance in Lesotho Licensing Guide', 'https://www.cannavigia.com/blog-posts/cannabis-country-report-lesotho-how-to-get-a-license-how-to-export-products-abroad', 'Lesotho', 'LS', 'Africa', 2, 'html_snapshot', 'quarterly', 'legal_analysis', '7 licence types, 0% corporate tax outside SACU / 10% within SADC, mandatory South Africa export routing, GMP compliance gap'),
  ('Lesotho National Development Corporation — Medicinal Cannabis Investment', 'https://lndc.org.ls/medicinal-cannabis/', 'Lesotho', 'LS', 'Africa', 1, 'html_snapshot', 'quarterly', 'government_release', 'Official investment promotion page: Drugs of Abuse (Cannabis) Regulations 2018 + 2025 Amendment, EU-GMP/USDA-APHIS/ISO-FSSC target certifications, VAT 15% domestic / 0% direct export'),
  ('Cannavigia — Cannabis Compliance in Malawi Licensing Guide', 'https://www.cannavigia.com/blog-posts/cannabis-country-report-malawi-how-to-get-a-cannabis-license', 'Malawi', 'MW', 'Africa', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'CRA licensing process, 21-day target turnaround, security-plan requirements distinct for industrial hemp vs medical cannabis, licences issued to companies/cooperatives only'),
  ('ICA Malawi — Industrial Hemp and Medical Cannabis FAQs', 'https://www.ica-malawi.org/faqs', 'Malawi', 'MW', 'Africa', 1, 'html_snapshot', 'quarterly', 'reference', 'CRA fee structure, 12-month initial licence validity, self-funded regulator via licence/infringement fees, Cannabis Act Feb 2020'),
  ('Sensi Seeds — Cannabis in Malawi Laws and History', 'https://sensiseeds.com/en/blog/countries/cannabis-in-malawi-laws-use-history/', 'Malawi', 'MW', 'Africa', 2, 'html_snapshot', 'quarterly', 'legal_analysis', '86 licences issued to 35 companies since Nov 2020, recreational sale/distribution still illegal, Malawi Gold excluded from legal medical programme'),
  ('PMC — Medical cannabis and cannabidiol: A new harvest for Malawi', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9356517/', 'Malawi', 'MW', 'Africa', 1, 'html_snapshot', 'annual', 'academic', 'Cannabis Regulation Bill 2020 passed 28 Feb 2020, distinguishes marijuana/hemp/medical cannabis, 20+ years of advocacy history documented'),
  ('LegalClarity — Is Weed Legal in Ireland? Recreational vs Medical', 'https://legalclarity.org/is-weed-legal-in-ireland-a-look-at-the-current-laws/', 'Ireland', 'IE', 'Europe', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'National Drugs Strategy 2026-2029 health-diversion scheme, MCAP HSE reimbursement via community schemes, no legal THC tolerance in food except hemp seed products'),
  ('Herb.co — How to Buy Weed in Ireland in 2026', 'https://herb.co/city-guides/buy-weed-ireland', 'Ireland', 'IE', 'Europe', 2, 'html_snapshot', 'quarterly', 'news', 'April 2026 MCAP formal review launched (Prof. Shane Allwright), 2025 customs seizures ~EUR107M, Oireachtas Committee 59 decrim recommendations Oct 2024'),
  ('Cannigma — Ireland Marijuana Laws 2026', 'https://cannigma.com/regulation/ireland-marijuana-laws/', 'Ireland', 'IE', 'Europe', 2, 'html_snapshot', 'quarterly', 'legal_analysis', 'MCAP excludes flower/high-THC formulations and chronic pain, ministerial-approval route only 63 patients, 6-month consultant prescription cap'),
  ('An Garda Síochána — Is Cannabis Legal? Official Guidance', 'https://www.garda.ie/en/crime/drugs/is-cannabis-legal-.html', 'Ireland', 'IE', 'Europe', 1, 'html_snapshot', 'quarterly', 'government_release', 'Official police guidance: no cultivation licences issued for medical purposes historically, CBD not controlled under Misuse of Drugs legislation, THC edibles explicitly illegal'),
  ('Herb.co — How to Buy Weed in Grenada: 2026 Visitor Guide', 'https://herb.co/city-guides/buy-weed-grenada', 'Grenada', 'GD', 'Americas', 1, 'html_snapshot', 'quarterly', 'news', 'Drug Abuse (Prevention and Control) (Amendment) Act 2026 assented 13 Feb 2026, gazetted 20 Feb 2026, 56g/15g resin threshold, 4 plants per premises, no licensed retail yet'),
  ('International CBC — Grenada''s Parliament Approves Major Cannabis Legislation', 'https://internationalcbc.com/grenadas-parliament-approves-major-cannabis-legislation/', 'Grenada', 'GD', 'Americas', 1, 'html_snapshot', 'quarterly', 'news', 'Automatic expungement of minor offences, Rastafari sacramental use rights in registered places of worship, Health Minister confirms recreational commercial sale not permitted'),
  ('St. Martin News Network — Grenada Parliament Approves Landmark Cannabis Bill', 'https://smn-news.com/index.php/st-maarten-st-martin-news/49861-grenada-parliament-approves-landmark-cannabis-decriminalization-and-regulation-bill.html', 'Grenada', 'GD', 'Americas', 2, 'html_snapshot', 'quarterly', 'news', 'National cannabis policy framework confirmed in development, commercial focus strictly limited to medical/therapeutic sector, severe penalties retained for supply to minors'),
  ('NOW Grenada — Draft Bill and Policy Statement for Decriminalisation', 'https://nowgrenada.com/2026/01/draft-bill-and-policy-statement-for-the-decriminalisation-of-cannabis-in-grenada/', 'Grenada', 'GD', 'Americas', 1, 'html_snapshot', 'quarterly', 'government_release', 'Cannabis Legalisation and Regulation Secretariat draft bill/policy statement publication, tabled in Parliament 20 January 2026'),
  ('Caribbean Today — Grenada Parliament Approves Amendment to Marijuana Legislation', 'https://caribbeantoday.com/sections/politics/grenada-parliament-approves-amendment-to-marijuana-legislation', 'Grenada', 'GD', 'Americas', 2, 'html_snapshot', 'quarterly', 'news', 'Age threshold set at 21 (not 18) after parliamentary debate, PM Mitchell and AG Joseph direct quotes on bipartisan support and framing')
ON CONFLICT DO NOTHING;
