-- Reconstructed from production.
--
-- This file previously contained no DDL. It carried a short comment saying it
-- had been applied directly to production via Supabase MCP and existed only to
-- satisfy local/remote migration history parity, followed by `SELECT 1;`.
--
-- That placeholder satisfied the version-number ledger while executing nothing,
-- so `supabase db reset --local` could not rebuild the schema this migration is
-- supposed to create. The statements below are the verbatim text production
-- ran, read back from supabase_migrations.schema_migrations.statements for
-- version 20260702014108.
--
-- Rewriting this file cannot affect production: 20260702014108 is already recorded
-- in schema_migrations, so `supabase db push` skips it. This is a
-- repository-only repair of replay fidelity.
--
-- Regenerate with: node scripts/reconstruct-stub-migrations.mjs

insert into education_module_sections (module_id, section_order, heading, body, block_type)
select m.id, v.section_order, v.heading, v.body, v.block_type
from (values
  ('drug-interactions', 1, 'Why This Matters', 'Cannabis-based products interact with a meaningful share of commonly prescribed medications through well-characterized pharmacological mechanisms, and a prescriber or pharmacist who treats cannabis as pharmacologically isolated from a patient''s broader medication regimen is missing a genuinely consequential clinical consideration, not just a theoretical one. This matters disproportionately for the patient population most likely to be considered for cannabis-based treatment, since patients pursuing cannabis-based options after conventional treatments have proven inadequate are frequently managing multiple chronic conditions with correspondingly complex existing medication regimens, precisely the population where interaction risk is highest.

This matters for documentation reasons covered directly in the clinical prescribing module elsewhere in this track: a prescribing decision''s documented rationale needs to reflect that the broader medication context was actually considered, and a pharmacist''s counselling obligation specifically extends to addressing potential interactions in combination therapy situations, as flagged in the pharmacy dispensing module. Neither of those documentation obligations can be genuinely satisfied without an actual working understanding of which interaction mechanisms are clinically relevant and why.

This module covers interaction mechanisms and categories at an educational, conceptual level; it does not provide patient-specific interaction assessment or dosing adjustment guidance, which remains the responsibility of the treating clinician and pharmacist applying their own clinical judgment and current reference resources to the specific patient and medication combination in front of them.

A concrete illustrative scenario shows how an unflagged hepatic enzyme interaction can surface clinically. Picture a hypothetical patient stable on a long-standing anticoagulant regimen who begins a cannabis-based treatment for an unrelated chronic condition. Neither the prescribing clinician nor the patient''s existing anticoagulant management team specifically flags the new treatment as interaction-relevant, since neither medication''s name or general category obviously suggests an interaction to someone without a working understanding of the underlying shared hepatic metabolic pathway. Weeks later, routine anticoagulant monitoring reveals the patient''s blood levels have shifted meaningfully outside the expected therapeutic range, a change ultimately traced back to the cannabinoid''s effect on the relevant metabolic enzyme altering how the anticoagulant itself is processed, an interaction that a documented, mechanism-specific interaction check at the time of the original cannabis-based prescribing decision would have flagged proactively rather than requiring discovery through an adverse monitoring result after the fact.

The interaction mechanisms covered in this module operate identically regardless of jurisdiction, meaning the clinical substance of interaction screening doesn''t vary across the global markets covered throughout this track even though the specific documentation format and regulatory reporting obligations attached to that screening, covered in the clinical prescribing and pharmacy dispensing modules elsewhere in this track, do vary by jurisdiction, a useful distinction for any organization building standardized clinical protocols across a multi-jurisdiction footprint.', 'text'),
  ('drug-interactions', 2, 'The Core Framework', 'Cannabis-drug interactions operate through a small number of distinct mechanisms, and understanding which mechanism is relevant for a given concurrent medication matters for assessing the interaction''s likely clinical significance.

Hepatic enzyme-mediated metabolic interactions are the most clinically significant category: THC and CBD are both metabolized through, and can themselves inhibit or induce, hepatic cytochrome P450 enzyme pathways shared by a substantial number of other commonly prescribed medications, meaning concurrent use can alter the blood levels of those other medications, in either direction, independent of any direct pharmacological interaction between the cannabinoid and the other drug''s own mechanism of action.

Additive central nervous system effects represent a more straightforward mechanism, where cannabis''s own sedating or psychoactive effects combine with other CNS-depressant medications, such as benzodiazepines, opioids, or certain antihistamines, to produce greater sedation, impairment, or respiratory depression risk than either substance alone, a mechanism that doesn''t require any metabolic interaction to be clinically relevant.

Cardiovascular interaction considerations are relevant given THC''s documented effects on heart rate and blood pressure, which can interact with medications managing cardiovascular conditions, particularly in patients where the underlying cardiovascular condition itself increases baseline risk.

Anticoagulant and antiplatelet interaction risk has been specifically documented for certain cannabinoid combinations affecting medications managing blood clotting, relevant given how commonly anticoagulant therapy appears in the same patient population frequently considered for cannabis-based treatment of chronic conditions.

Route-of-administration-dependent interaction timing means the practical interaction risk and onset can differ between inhaled and oral cannabis products even for the same underlying mechanism, since the pharmacokinetic profile differences covered in the cannabinoid pharmacology module elsewhere in this track affect not just the cannabinoid''s own behavior but the timing and intensity of its interaction with concurrent medications.

It is worth examining the hepatic enzyme interaction mechanism in slightly more technical depth, since understanding why it''s so broadly consequential helps explain its priority position in the interaction framework. THC and CBD both interact with a small number of hepatic cytochrome P450 enzyme families that are also responsible for metabolizing a very large share of commonly prescribed medications across many therapeutic categories, meaning the interaction risk isn''t limited to medications that share an obvious clinical similarity with cannabis-based treatment, but extends to any medication processed through the same shared metabolic pathway regardless of how clinically unrelated the two treatments otherwise appear, which is precisely why a mechanism-based check, rather than an intuition-based one, is necessary to reliably catch this category of interaction.

It is worth connecting interaction-screening discipline explicitly to the broader documentation-currency principle that recurs throughout this education track, since a patient''s medication list, like a supplier''s compliance documentation or a market''s regulatory status, is a perishable data point requiring periodic re-verification rather than a one-time intake item; building interaction re-screening into a standard recurring clinical workflow, rather than treating it as a single initial-consultation step, mirrors the same currency-maintenance discipline this track applies to proof-pack documentation and regulatory intelligence monitoring.', 'text'),
  ('drug-interactions', 3, 'How This Plays Out in Practice', 'A prescriber documenting a cannabis-based treatment decision for a patient on an existing medication regimen, consistent with the documentation discipline covered in the clinical prescribing module elsewhere in this track, should document not just that the broader medication list was reviewed, but specifically which interaction categories were assessed as relevant or not relevant for this particular patient''s actual medication combination, since a generic note that interactions were "considered" carries the same documentation weakness flagged elsewhere in this track for any undocumented clinical rationale.

Given that hepatic enzyme-mediated interactions can affect a wide range of medications through a shared pathway rather than through any obvious surface-level similarity between drugs, a prescriber or pharmacist should specifically check a patient''s full medication list against current interaction reference resources rather than relying on intuition about which medications "seem like" they might interact with cannabis, since the actual mechanism frequently isn''t obvious without that specific check.

For pharmacists specifically, the counselling obligation around combination therapy covered in the pharmacy dispensing module elsewhere in this track is best satisfied by addressing the specific interaction category relevant to that patient''s actual concurrent medications, rather than providing only generic combination-therapy caution language, since a patient on an anticoagulant benefits from meaningfully different specific counselling than a patient on a CNS-depressant, even though both fall under the broader "combination therapy" documentation category.

Given that interaction risk and timing can differ by route of administration for the same underlying medication combination, a patient transitioning between cannabis product formats, an event that already triggers re-counselling under the pharmacy dispensing module''s framework, should have that re-counselling specifically address whether the interaction profile with their existing medications changes meaningfully with the new format, not just whether the cannabinoid product itself behaves differently.

A further consideration concerns how interaction risk should be reassessed, not just initially screened, over the course of an extended treatment relationship, since a patient''s broader medication regimen frequently changes over time independent of their cannabis-based treatment, with new medications added for unrelated conditions or dosages adjusted for existing ones; a single interaction screen performed only at the original cannabis-based prescribing decision, without a corresponding re-screen whenever the patient''s broader medication list subsequently changes, leaves a documentation and clinical gap that mirrors the broader documentation-currency principle covered throughout this education track.

A globally operating clinic or telemedicine platform should build a single, standardized interaction-screening protocol and reference resource used consistently across every jurisdiction served, since the underlying pharmacological interaction mechanisms don''t differ by jurisdiction, while still layering jurisdiction-specific documentation requirements for how that screening is recorded on top of the shared underlying clinical protocol, avoiding the inefficiency and inconsistency risk of building separate interaction-screening processes independently for each market served.', 'text'),
  ('drug-interactions', 4, 'Common Pitfalls', 'The most common mistake is assessing interaction risk based on superficial similarity between drug names or categories rather than actual shared mechanism, missing genuinely significant hepatic enzyme-mediated interactions that aren''t obvious without specifically checking the metabolic pathway, while sometimes over-flagging interactions between medications that share no actual mechanistic overlap with cannabinoids.

A second frequent error is documenting that a medication review occurred without specifying which interaction categories were actually assessed and found relevant or not relevant, the same generic-documentation weakness flagged throughout the clinical prescribing module elsewhere in this track, leaving a reviewer unable to distinguish a genuinely thorough interaction assessment from a cursory check.

Pharmacists and prescribers also commonly treat combination-therapy counselling as a single generic caution rather than tailoring it to the patient''s actual specific concurrent medications and the corresponding interaction mechanism most relevant to them, missing the opportunity to provide counselling that''s actually clinically specific and actionable for that patient.

Finally, route-of-administration-dependent interaction timing is sometimes overlooked entirely when a patient changes product format, with re-counselling at that transition point focused only on the cannabinoid product''s own behavior rather than also addressing whether the interaction profile with the patient''s existing medications shifts meaningfully alongside the format change.

Pharmacists specifically should think about building interaction-screening discipline into routine dispensing workflow even for refills of an already-established cannabis-based prescription, not just at initial dispensing, since the dispensing pharmacist is frequently the party best positioned to notice a new medication has been added to a patient''s broader regimen, given that community pharmacy dispensing records often capture a fuller, more current picture of a patient''s overall medication list than any single prescriber''s own records might.

Operators building multi-jurisdiction clinical operations should specifically anticipate that patient medication-list completeness and accuracy may vary by market depending on how integrated that jurisdiction''s pharmacy and prescribing record systems are, meaning a market with less integrated health-record infrastructure may require correspondingly more deliberate, proactive intake effort to assemble a genuinely complete medication picture than a market with more centralized prescribing and dispensing records the clinician can more easily cross-reference.', 'text')
) as v(slug, section_order, heading, body, block_type)
join education_modules m on m.slug = v.slug;
