-- Publish Market Access heatmap evidence for neutral US states and priority nationals.
-- Globe colour uses countries.verified_regulatory_tier via api.refresh_verified_market_access_tiers.
-- Adult-use state retail => legal_commercial_access (aligned with currently published US-CA/US-IL).
-- Medical-only programmes => medical_limited_trade.
-- Hemp/CBD-limited => cbd_hemp_only.
-- Federal US remains medical_limited_trade (no verified nationwide interstate pathway).

-- Required because the table enforces one active evidence row per jurisdiction.
-- Existing active rows must be retired before inserting the replacement publication rows.
update public.regulatory_market_access_evidence e
set active = false
where e.jurisdiction_iso2 in (
  'US-AK','US-AZ','US-CO','US-CT','US-DE','US-MA','US-MO','US-NJ','US-NM','US-NV','US-NY','US-OH','US-OR','US-RI','US-WA',
  'US-AR','US-FL','US-LA','US-MS','US-ND','US-NE','US-OK','US-WV',
  'US-IN','US-KS','US-SC','US-WY',
  'US','GB','DE','AU','FR','ES','IT','JP','MX','CO','TH','NZ','ZA'
)
and e.active = true;

insert into public.regulatory_market_access_evidence
  (evidence_key, jurisdiction_iso2, tier, rationale, authority_name, authority_url,
   source_effective_date, verified_at, expires_at, active)
values
  ('hv-heatmap-us-ak-20260924','US-AK','legal_commercial_access',
   'Alaska operates a state-licensed adult-use and medical cannabis retail market under the Marijuana Control Board.',
   'Alaska Alcohol and Marijuana Control Office','https://www.commerce.alaska.gov/web/amco/',
   '2016-02-24', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-az-20260924','US-AZ','legal_commercial_access',
   'Arizona operates licensed adult-use and medical cannabis retail under ADHS cannabis programme.',
   'Arizona Department of Health Services — Cannabis','https://www.azdhs.gov/licensing/cannabis/index.php',
   '2020-11-30', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-co-20260924','US-CO','legal_commercial_access',
   'Colorado licenses adult-use and medical marijuana businesses through the Marijuana Enforcement Division.',
   'Colorado Marijuana Enforcement Division','https://med.colorado.gov/',
   '2014-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-ct-20260924','US-CT','legal_commercial_access',
   'Connecticut operates licensed adult-use and medical cannabis retail under DCP Cannabis Control.',
   'Connecticut Department of Consumer Protection — Cannabis','https://portal.ct.gov/dcp/cannabis',
   '2023-01-10', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-de-20260924','US-DE','legal_commercial_access',
   'Delaware operates licensed adult-use and medical cannabis under state medical/adult-use framework.',
   'Delaware Division of Public Health — Medical Marijuana','https://dhss.delaware.gov/dhss/dph/hsp/mmp.html',
   '2023-08-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-ma-20260924','US-MA','legal_commercial_access',
   'Massachusetts licenses adult-use and medical cannabis establishments through the Cannabis Control Commission.',
   'Massachusetts Cannabis Control Commission','https://masscannabiscontrol.com/',
   '2018-11-20', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-mo-20260924','US-MO','legal_commercial_access',
   'Missouri operates licensed adult-use and medical cannabis under the Division of Cannabis Regulation.',
   'Missouri Division of Cannabis Regulation','https://health.mo.gov/safety/cannabis/',
   '2023-02-03', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-nj-20260924','US-NJ','legal_commercial_access',
   'New Jersey licenses adult-use and medical cannabis through the Cannabis Regulatory Commission.',
   'New Jersey Cannabis Regulatory Commission','https://www.nj.gov/cannabis/',
   '2022-04-21', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-nm-20260924','US-NM','legal_commercial_access',
   'New Mexico operates licensed adult-use and medical cannabis under the Cannabis Control Division.',
   'New Mexico Regulation and Licensing Department — Cannabis Control Division','https://www.rld.nm.gov/cannabis/',
   '2022-04-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-nv-20260924','US-NV','legal_commercial_access',
   'Nevada licenses adult-use and medical cannabis establishments through the Cannabis Compliance Board.',
   'Nevada Cannabis Compliance Board','https://ccb.nv.gov/',
   '2017-07-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-ny-20260924','US-NY','legal_commercial_access',
   'New York licenses adult-use and medical cannabis through the Office of Cannabis Management.',
   'New York Office of Cannabis Management','https://cannabis.ny.gov/',
   '2022-12-29', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-oh-20260924','US-OH','legal_commercial_access',
   'Ohio operates licensed adult-use and medical cannabis under the Division of Cannabis Control.',
   'Ohio Division of Cannabis Control','https://com.ohio.gov/divisions-and-programs/cannabis-control',
   '2023-12-07', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-or-20260924','US-OR','legal_commercial_access',
   'Oregon licenses adult-use and medical cannabis through the Oregon Liquor and Cannabis Commission.',
   'Oregon Liquor and Cannabis Commission','https://www.oregon.gov/olcc/marijuana/pages/default.aspx',
   '2015-10-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-ri-20260924','US-RI','legal_commercial_access',
   'Rhode Island operates licensed adult-use and medical cannabis under the Office of Cannabis Regulation.',
   'Rhode Island Office of Cannabis Regulation','https://dbr.ri.gov/cannabis',
   '2022-12-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-wa-20260924','US-WA','legal_commercial_access',
   'Washington licenses adult-use cannabis retail and production through the Liquor and Cannabis Board.',
   'Washington State Liquor and Cannabis Board','https://lcb.wa.gov/',
   '2014-07-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-ar-20260924','US-AR','medical_limited_trade',
   'Arkansas operates a regulated medical cannabis programme; no operational adult-use retail market verified.',
   'Arkansas Medical Marijuana Commission','https://www.mmc.arkansas.gov/',
   '2017-05-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-fl-20260924','US-FL','medical_limited_trade',
   'Florida operates a regulated medical cannabis (MMTC) programme; no adult-use retail market verified.',
   'Florida Office of Medical Marijuana Use','https://knowthefactsmmj.com/',
   '2017-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-la-20260924','US-LA','medical_limited_trade',
   'Louisiana operates a medical cannabis programme under the Louisiana Department of Health.',
   'Louisiana Department of Health — Medical Marijuana','https://ldh.la.gov/page/medical-marijuana',
   '2019-08-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-ms-20260924','US-MS','medical_limited_trade',
   'Mississippi operates a medical cannabis programme under the Mississippi Department of Health.',
   'Mississippi State Department of Health — Medical Cannabis','https://msdh.ms.gov/',
   '2022-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-nd-20260924','US-ND','medical_limited_trade',
   'North Dakota operates a medical cannabis programme; no adult-use retail market verified.',
   'North Dakota Department of Health and Human Services — Medical Marijuana','https://www.hhs.nd.gov/health/medical-marijuana',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-ne-20260924','US-NE','medical_limited_trade',
   'Nebraska has enacted medical cannabis access; operational adult-use retail is not verified.',
   'Nebraska Legislature — medical cannabis framework','https://nebraskalegislature.gov/',
   '2024-11-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-ok-20260924','US-OK','medical_limited_trade',
   'Oklahoma operates a medical cannabis patient and licensee programme under OMMA.',
   'Oklahoma Medical Marijuana Authority','https://oklahoma.gov/omma.html',
   '2018-07-26', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-wv-20260924','US-WV','medical_limited_trade',
   'West Virginia operates a medical cannabis programme; no adult-use retail market verified.',
   'West Virginia Office of Medical Cannabis','https://dhhr.wv.gov/bph/Pages/Medical-Cannabis.aspx',
   '2019-07-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-in-20260924','US-IN','cbd_hemp_only',
   'Indiana does not operate a full THC medical or adult-use cannabis market; lawful pathways centre on hemp/low-THC products.',
   'Indiana State Department of Agriculture — Hemp','https://www.in.gov/isda/divisions/hemp/',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-ks-20260924','US-KS','cbd_hemp_only',
   'Kansas does not operate a full THC medical or adult-use cannabis market; lawful pathways centre on hemp products.',
   'Kansas Department of Agriculture — Industrial Hemp','https://agriculture.ks.gov/divisions-programs/agricultural-marketing-advocacy-and-outreach-team/industrial-hemp',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-sc-20260924','US-SC','cbd_hemp_only',
   'South Carolina does not operate a full THC medical or adult-use cannabis market; lawful access is limited to hemp/low-THC pathways.',
   'South Carolina Department of Agriculture','https://agriculture.sc.gov/',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-wy-20260924','US-WY','cbd_hemp_only',
   'Wyoming does not operate a full THC medical or adult-use cannabis market; lawful pathways centre on hemp products.',
   'Wyoming Department of Agriculture — Hemp','https://wyagric.state.wy.us/',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-us-federal-20260924','US','medical_limited_trade',
   'State medical and adult-use markets operate under state law; no verified nationwide interstate commercial cannabis pathway is published for globe colouring.',
   'US FDA — cannabis and cannabis-derived products','https://www.fda.gov/news-events/public-health-focus/fda-regulation-cannabis-and-cannabis-derived-products-including-cannabidiol-cbd',
   '1970-10-27', now(), now() + interval '365 days', true),
  ('hv-heatmap-gb-20260924','GB','medical_limited_trade',
   'The United Kingdom permits prescribed specialist medical cannabis products; adult-use commercial retail is not authorised.',
   'UK MHRA / GOV.UK medicinal cannabis resources','https://www.gov.uk/government/collections/medicinal-cannabis-information-and-resources',
   '2018-11-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-de-20260924','DE','legal_commercial_access',
   'Germany permits medical cannabis and limited adult-use personal/association pathways under CanG; licensed medical trade pathways exist.',
   'BfArM — Cannabis','https://www.bfarm.de/DE/Bundesopiumstelle/Cannabis/_node.html',
   '2024-04-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-au-20260924','AU','medical_limited_trade',
   'Australia operates a regulated medicinal cannabis scheme under the TGA; adult-use commercial retail is not authorised at Commonwealth level.',
   'Therapeutic Goods Administration — Medicinal cannabis','https://www.tga.gov.au/products/medicinal-cannabis',
   '2016-11-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-fr-20260924','FR','medical_limited_trade',
   'France authorises limited medical cannabis pathways; general adult-use commercial retail is not authorised.',
   'Agence nationale de sécurité du médicament (ANSM)','https://ansm.sante.fr/',
   '2021-03-26', now(), now() + interval '365 days', true),
  ('hv-heatmap-es-20260924','ES','medical_limited_trade',
   'Spain permits controlled medical cannabis pathways; general adult-use commercial retail is not authorised at national level.',
   'Agencia Española de Medicamentos y Productos Sanitarios','https://www.aemps.gob.es/',
   '2022-06-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-it-20260924','IT','medical_limited_trade',
   'Italy authorises medical cannabis production and prescribing under Ministry of Health frameworks.',
   'Ministero della Salute','https://www.salute.gov.it/',
   '2015-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-jp-20260924','JP','cbd_hemp_only',
   'Japan strictly controls cannabis; lawful commercial pathways centre on non-controlled hemp/CBD products meeting THC limits.',
   'Japan Ministry of Health, Labour and Welfare','https://www.mhlw.go.jp/',
   '1948-07-10', now(), now() + interval '365 days', true),
  ('hv-heatmap-mx-20260924','MX','medical_limited_trade',
   'Mexico has medical and personal-use pathways; a fully operational national adult-use commercial retail licensing scheme is not treated as verified for globe publication.',
   'COFEPRIS','https://www.gob.mx/cofepris',
   '2021-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-co-20260924','CO','legal_commercial_access',
   'Colombia licenses medicinal cannabis cultivation and foreign trade under national authorities.',
   'Instituto Colombiano Agropecuario / INVIMA','https://www.ica.gov.co/',
   '2016-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-th-20260924','TH','medical_limited_trade',
   'Thailand regulates medical cannabis; a stable verified general adult-use commercial retail pathway is not treated as established for globe publication.',
   'Thai Food and Drug Administration','https://www.fda.moph.go.th/',
   '2022-06-09', now(), now() + interval '365 days', true),
  ('hv-heatmap-nz-20260924','NZ','medical_limited_trade',
   'New Zealand operates a medicinal cannabis scheme; adult-use commercial retail was not authorised by referendum.',
   'New Zealand Ministry of Health — Medicinal Cannabis','https://www.health.govt.nz/our-work/regulation-health-and-disability-system/medicinal-cannabis-agency',
   '2020-04-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-za-20260924','ZA','medical_limited_trade',
   'South Africa permits private use under court guidance and regulated medical pathways; general adult-use commercial retail is not fully established as verified.',
   'South African Health Products Regulatory Authority (SAHPRA)','https://www.sahpra.org.za/',
   '2018-09-18', now(), now() + interval '365 days', true)
on conflict (evidence_key) do update set
  tier = excluded.tier,
  rationale = excluded.rationale,
  authority_name = excluded.authority_name,
  authority_url = excluded.authority_url,
  source_effective_date = excluded.source_effective_date,
  verified_at = excluded.verified_at,
  expires_at = excluded.expires_at,
  active = true;

update public.regulatory_market_access_evidence e
set active = false
where e.jurisdiction_iso2 in (
  'US-AK','US-AZ','US-CO','US-CT','US-DE','US-MA','US-MO','US-NJ','US-NM','US-NV','US-NY','US-OH','US-OR','US-RI','US-WA',
  'US-AR','US-FL','US-LA','US-MS','US-ND','US-NE','US-OK','US-WV',
  'US-IN','US-KS','US-SC','US-WY',
  'US','GB','DE','AU','FR','ES','IT','JP','MX','CO','TH','NZ','ZA'
)
and e.evidence_key not like 'hv-heatmap-%-20260924'
and e.active = true;

select * from api.refresh_verified_market_access_tiers('heatmap-publish-us-priority-20260924');
