-- National tranche 2: Europe / LatAm / select openers for Market Access heatmap.
-- Fail-closed publish via regulatory_market_access_evidence + refresh.

insert into public.regulatory_market_access_evidence
  (evidence_key, jurisdiction_iso2, tier, rationale, authority_name, authority_url,
   source_effective_date, verified_at, expires_at, active)
values
  ('hv-heatmap-at-20260925','AT','medical_limited_trade',
   'Austria permits prescribed medical cannabis products under narcotics controls; adult-use commercial retail is not authorised.',
   'AGES / Austrian Federal Office for Safety in Health Care','https://www.basg.gv.at/',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-ch-20260925','CH','medical_limited_trade',
   'Switzerland authorises medical cannabis and limited regulated pathways; adult-use commercial retail is not generally authorised nationwide.',
   'Swissmedic / Federal Office of Public Health','https://www.swissmedic.ch/',
   '2022-08-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-cl-20260925','CL','medical_limited_trade',
   'Chile authorises medical cannabis access and limited cultivation/pharmacy pathways; general adult-use commercial retail is not authorised.',
   'Instituto de Salud Pública de Chile','https://www.ispch.cl/',
   '2015-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-cr-20260925','CR','legal_commercial_access',
   'Costa Rica licenses medicinal cannabis cultivation and related commercial activity including export projects under MAG/health frameworks.',
   'Ministerio de Agricultura y Ganadería (MAG) Costa Rica','https://www.mag.go.cr/',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-cz-20260925','CZ','medical_limited_trade',
   'Czechia operates a regulated medical cannabis prescribing and pharmacy supply framework; adult-use commercial retail is not authorised.',
   'Státní ústav pro kontrolu léčiv (SÚKL)','https://www.sukl.cz/',
   '2013-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-fi-20260925','FI','medical_limited_trade',
   'Finland permits specialised medical cannabis under Fimea controls; adult-use commercial retail is not authorised.',
   'Finnish Medicines Agency (Fimea)','https://fimea.fi/',
   '2008-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-gr-20260925','GR','medical_limited_trade',
   'Greece authorises medical cannabis production and supply under national health/narcotics frameworks; adult-use commercial retail is not authorised.',
   'Greek Ministry of Health / EOF','https://www.eof.gr/',
   '2018-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-hr-20260925','HR','medical_limited_trade',
   'Croatia permits medical cannabis under medicines/narcotics controls; adult-use commercial retail is not authorised.',
   'HALMED — Croatian Agency for Medicinal Products','https://www.halmed.hr/',
   '2015-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-hu-20260925','HU','medical_limited_trade',
   'Hungary permits limited medical cannabis product access under medicines controls; adult-use commercial retail is not authorised.',
   'National Institute of Pharmacy and Nutrition (OGYÉI)','https://ogyei.gov.hu/',
   '2017-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-il-20260925','IL','medical_limited_trade',
   'Israel operates a regulated medical cannabis programme under the Ministry of Health; adult-use commercial retail is not authorised.',
   'Israel Ministry of Health — Medical Cannabis','https://www.health.gov.il/',
   '2011-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-jm-20260925','JM','medical_limited_trade',
   'Jamaica licenses medical and scientific cannabis activity under the Cannabis Licensing Authority; general adult-use commercial retail is not treated as verified for globe publication.',
   'Cannabis Licensing Authority Jamaica','https://www.cla.org.jm/',
   '2015-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-lt-20260925','LT','medical_limited_trade',
   'Lithuania permits medical cannabis products under medicines controls; adult-use commercial retail is not authorised.',
   'State Medicines Control Agency of Lithuania','https://www.vvkt.lt/',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-lu-20260925','LU','medical_limited_trade',
   'Luxembourg authorises medical cannabis; a verified general adult-use commercial retail market is not treated as fully established for globe publication.',
   'Ministry of Health Luxembourg','https://sante.public.lu/',
   '2018-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-lv-20260925','LV','medical_limited_trade',
   'Latvia permits medical cannabis under medicines/narcotics frameworks; adult-use commercial retail is not authorised.',
   'State Agency of Medicines of Latvia','https://www.zva.gov.lv/',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-pe-20260925','PE','medical_limited_trade',
   'Peru authorises medical cannabis under health ministry regulations; adult-use commercial retail is not authorised.',
   'DIGEMID / Ministerio de Salud del Perú','https://www.digemid.minsa.gob.pe/',
   '2017-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-pl-20260925','PL','medical_limited_trade',
   'Poland permits medical cannabis pharmacy supply under pharmaceutical law; adult-use commercial retail is not authorised.',
   'URPL — Office for Registration of Medicinal Products','https://www.urpl.gov.pl/',
   '2017-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-pt-20260925','PT','medical_limited_trade',
   'Portugal authorises medical cannabis under INFARMED; adult-use commercial retail is not authorised.',
   'INFARMED — Autoridade Nacional do Medicamento','https://www.infarmed.pt/',
   '2018-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-se-20260925','SE','medical_limited_trade',
   'Sweden permits limited medical cannabis product access under Läkemedelsverket controls; adult-use commercial retail is not authorised.',
   'Swedish Medical Products Agency (Läkemedelsverket)','https://www.lakemedelsverket.se/',
   '2012-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-si-20260925','SI','medical_limited_trade',
   'Slovenia permits medical cannabis under medicines controls; adult-use commercial retail is not authorised.',
   'JAZMP — Agency for Medicinal Products and Medical Devices','https://www.jazmp.si/',
   '2014-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-sk-20260925','SK','medical_limited_trade',
   'Slovakia permits limited medical cannabis access under medicines controls; adult-use commercial retail is not authorised.',
   'Štátny ústav pre kontrolu liečiv (ŠÚKL)','https://www.sukl.sk/',
   '2018-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-uy-20260925','UY','legal_commercial_access',
   'Uruguay operates a regulated adult-use and medical cannabis framework including pharmacy and club channels under IRCCA.',
   'IRCCA — Instituto de Regulación y Control del Cannabis','https://www.ircca.gub.uy/',
   '2013-12-20', now(), now() + interval '365 days', true),
  ('hv-heatmap-cy-20260925','CY','medical_limited_trade',
   'Cyprus authorises medical cannabis under national medicines/narcotics frameworks; adult-use commercial retail is not authorised.',
   'Cyprus Ministry of Health / Pharmaceutical Services','https://www.moh.gov.cy/',
   '2017-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-bw-20260925','BW','legal_commercial_access',
   'Botswana licenses medical cannabis production and related controlled commercial activity under national drugs control frameworks.',
   'Botswana Medicines Regulatory Authority / Ministry of Health','https://www.moh.gov.bw/',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-gh-20260925','GH','legal_commercial_access',
   'Ghana authorises controlled cannabis cultivation for health/industrial purposes under the Narcotics Control Commission framework; this is not an adult-use retail market.',
   'Narcotics Control Commission Ghana','https://www.ncc.gov.gh/',
   '2020-01-01', now(), now() + interval '365 days', true),
  ('hv-heatmap-ma-20260925','MA','legal_commercial_access',
   'Morocco authorises regulated medical and industrial cannabis activity under ANRAC Law 13-21; adult-use recreational retail is not the published pathway.',
   'ANRAC — Agence Nationale de Réglementation des Activités relatives au Cannabis','https://www.anrac.ma/',
   '2021-01-01', now(), now() + interval '365 days', true)
on conflict (evidence_key) do update set
  tier = excluded.tier,
  rationale = excluded.rationale,
  authority_name = excluded.authority_name,
  authority_url = excluded.authority_url,
  source_effective_date = excluded.source_effective_date,
  verified_at = excluded.verified_at,
  expires_at = excluded.expires_at,
  active = true;

update public.regulatory_market_access_evidence e
set active = false
where e.jurisdiction_iso2 in (
  'AT','CH','CL','CR','CZ','FI','GR','HR','HU','IL','JM','LT','LU','LV',
  'PE','PL','PT','SE','SI','SK','UY','CY','BW','GH','MA'
)
and e.evidence_key not like 'hv-heatmap-%-20260925'
and e.active = true;

select * from api.refresh_verified_market_access_tiers('heatmap-national-tranche2-20260925');
