-- Sources for jurisdiction_playbooks batch 23 (part A of B, see batch23b for
-- playbook content + market metrics). Split across two files due to payload size.

INSERT INTO public.source_registry (source_name, source_url, country, iso, region, tier, adapter, crawl_cadence, source_type, notes)
VALUES
  ('Cannabisregulations.ai — Is Weed Legal in Laos? 2026 Cannabis Laws & Penalties', 'https://www.cannabisregulations.ai/country-legality/laos-marijuana', 'Laos', 'LA', 'Asia', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'Article 146 Penal Code graduated penalties, 3kg death-penalty threshold, LCDC enforcement at Wattay airport and Friendship Bridge crossings'),
  ('CMS Expert Guides — Cannabis law and legislation in Laos', 'https://cms.law/en/int/expert-guides/cms-expert-guide-to-a-legal-roadmap-to-cannabis/laos', 'Laos', 'LA', 'Asia', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'Decision 3789/MOH Dec 2022 hemp control framework, TRIPS patent transition period context'),
  ('Tilleke & Gibbins — Laos Approves Hemp-Related Activities', 'https://www.tilleke.com/insights/laos-approves-hemp-related-activities/', 'Laos', 'LA', 'Asia', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'THC analysis process and feasibility-study requirements still unclarified as of most recent review, ad hoc committee history since 2019'),
  ('WSR Law Group — Laos Allows Controlled Activities of Hemp and Cannabis Sativa L. for Medical Use', 'https://wsrlawgroup.com/laos-allows-controlled-activities-of-hemp-and-cannabis-stiva-l-for-medical-use/', 'Laos', 'LA', 'Asia', 2, 'html_snapshot', 'quarterly', 'legal_analysis', 'THC limited to 0.2% raw/processed, not exceeding 1% by weight; seed registration and origin-authorization requirements'),
  ('Herb.co — How to Buy Weed in Malaysia: 2026 Laws, Penalties & Tourist Guide', 'https://herb.co/city-guides/buy-weed-malaysia', 'Malaysia', 'MY', 'Asia', 1, 'html_snapshot', 'quarterly', 'news', 'No cannabis-based product registered for medical use as of latest MOH guidance, no foreign-national exemption from prosecution, mandatory death penalty abolished July 2023 (Act 846) but death remains available'),
  ('Tripbase — Malaysia Drug Laws: What''s Legal & the Penalties (2026)', 'https://www.tripbase.com/drug-laws/malaysia/cannabis/', 'Malaysia', 'MY', 'Asia', 1, 'html_snapshot', 'quarterly', 'legal_analysis', '200g cannabis statutory trafficking presumption threshold under s.37 Dangerous Drugs Act, narrow 2019 0%-THC CBD pharmaceutical allowance for conditions like epilepsy'),
  ('Leafwell — Is Marijuana Legal in Malaysia?', 'https://leafwell.com/blog/is-marijuana-legal-in-malaysia', 'Malaysia', 'MY', 'Asia', 2, 'html_snapshot', 'quarterly', 'legal_analysis', 'Malaysian Drug Control Authority registration requirement, Malaysian-based study location requirement for research, watching Thailand model'),
  ('Wikipedia — Cannabis in Malaysia', 'https://en.wikipedia.org/wiki/Cannabis_in_Malaysia', 'Malaysia', 'MY', 'Asia', 2, 'html_snapshot', 'quarterly', 'reference', '2021 Khairy Jamaluddin ministerial statement on conditional medical marijuana import/use pathway'),
  ('Herb.co — How to Buy Weed in St. Lucia: 2026 Cannabis Guide', 'https://herb.co/city-guides/buy-weed-st-lucia', 'Saint Lucia', 'LC', 'Americas', 1, 'html_snapshot', 'quarterly', 'news', 'April 2026 GrowerIQ seed-to-sale traceability platform selection, 2021 automatic expungement and PM Pierre Rastafarian apology, Cannabis and Industrial Hemp Bill 2025 context'),
  ('LegalClarity — Is Weed Legal in St. Lucia? Rules and Penalties', 'https://legalclarity.org/is-weed-legal-in-st-lucia-local-laws-explained/', 'Saint Lucia', 'LC', 'Americas', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'Regulated Substances Act No. 26 of 2023 creating Regulated Substances Authority, two-tier Class One/Two product system in pending Cannabis and Industrial Hemp Bill, 4-plant household cultivation limit'),
  ('Hemp Gazette — Saint Lucia Cannabis Legislation Moving Ahead', 'https://hempgazette.com/news/saint-lucia-cannabis-hg2392/', 'Saint Lucia', 'LC', 'Americas', 2, 'html_snapshot', 'quarterly', 'news', 'Cannabis Advisory Council and dispensary licence provisions in draft bill, regional green-climate-agenda cannabis cultivation discussions'),
  ('Leafwell — Is Marijuana Legal in Saint Lucia?', 'https://leafwell.com/blog/is-marijuana-legal-in-saint-lucia', 'Saint Lucia', 'LC', 'Americas', 2, 'html_snapshot', 'quarterly', 'legal_analysis', '2021 Criminal Records and Rehabilitation Amendment Bill, 2019 cannabis commission report, Cannabis Task Force formation history'),
  ('IndicaOnline — Puerto Rico Marijuana Laws 2026', 'https://indicaonline.com/blog/puerto-rico-marijuana-laws/', 'Puerto Rico', 'PR', 'Americas', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'Over 150 operational dispensaries, vertical integration permitted, Act 20/22 tax incentive relocation driver, Act 42-2017 Medical Cannabis Act framework'),
  ('Cannabisregulations.ai — Puerto Rico Hemp Enforcement in 2026', 'https://www.cannabisregulations.ai/cannabis-and-hemp-regulations-compliance-ai-blog/puerto-rico-2025-mislabeled-hemp-crackdown', 'Puerto Rico', 'PR', 'Americas', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'OLIC hemp licensing oversight, 677+ authorized product SKUs as of 2025, Delta-8/synthetic cannabinoid enforcement crackdown'),
  ('Herb.co — How to Buy Weed in Puerto Rico in 2026', 'https://herb.co/city-guides/buy-weed-puerto-rico', 'Puerto Rico', 'PR', 'Americas', 2, 'html_snapshot', 'quarterly', 'news', 'MCRB/JRCM licensing scope, tourism reciprocity rule, smoking/combustion ban in favor of vaporized and non-combustible forms'),
  ('Puerto Rico Cannabis Club — Cannabis Laws in Puerto Rico 2026', 'https://puertoricocannabisclub.com/puerto-rico/medical-card-visitor-info/cannabis-laws-puerto-rico-2026', 'Puerto Rico', 'PR', 'Americas', 1, 'html_snapshot', 'quarterly', 'reference', 'Executive Order 2015-10 origin, no home cultivation permitted, tourism-oriented telehealth clinic ecosystem, JRCM public licensee registry')
ON CONFLICT DO NOTHING;
