-- Primary Samoa regulatory provenance: Narcotics Act 1967.
update public.regulatory_market_access_evidence set active=false where jurisdiction_iso2='WS' and active=true;
insert into public.source_registry (source_name,source_url,jurisdiction,is_active,country,iso,language,crawl_cadence,relevance_status,jurisdiction_code,tier,requires_auth,source_type,crawl_allowed,verification_notes,regulator_class)
values ('Samoa Attorney-General — Narcotics Act 1967','https://www.ag.gov.ws/wp-content/uploads/2024/02/Narcotics-Act-1967.pdf','Samoa',true,'Samoa','WS','en','monthly','verified','WS',1,false,'statute',true,'Primary Samoa statute. Narcotics Act 1967 establishes prohibited plants, unlawful cultivation, possession/use, import/export restrictions and licensing for narcotics dealings.','legislature')
on conflict (source_url) do update set is_active=true,jurisdiction_code='WS',verification_notes=excluded.verification_notes,updated_at=now();
insert into public.regulatory_market_access_evidence (evidence_key,jurisdiction_iso2,tier,rationale,authority_name,authority_url,source_effective_date,verified_at,expires_at,active)
values ('primary-evidence-ws-narcotics-1967','WS','prohibited','Samoa''s Narcotics Act 1967 establishes controls over prohibited plants and narcotics, including unlawful cultivation, possession/use, import/export and supply. The statute provides licensing mechanisms for lawful narcotics dealings but the cited source does not establish a general commercial cannabis retail pathway.','Samoa Attorney-General','https://www.ag.gov.ws/wp-content/uploads/2024/02/Narcotics-Act-1967.pdf','1967-01-01',now(),now()+interval '180 days',true);
insert into public.regulatory_market_access_claims (evidence_key,jurisdiction_iso2,claim_key,claim_text,product_class,jurisdiction_scope,authority_name,authority_url,source_effective_date,retrieved_at,verified_at,expires_at,evidence_status)
values ('primary-evidence-ws-narcotics-1967','WS','primary-evidence-claim:ws-narcotics-1967','Samoa''s Narcotics Act 1967 prohibits unlawful cultivation, possession/use, import/export and supply of prohibited narcotics and provides controlled licensing mechanisms; the cited law does not establish general commercial cannabis retail.','any','national','Samoa Attorney-General','https://www.ag.gov.ws/wp-content/uploads/2024/02/Narcotics-Act-1967.pdf','1967-01-01',now(),now(),now()+interval '180 days','verified');
update public.jurisdiction_dimension_coverage set status='verified_populated',applicability='applicable',evidence_basis='Primary Samoa Narcotics Act 1967.',last_evaluated_at=now() where jurisdiction_key='WS' and dimension_key in ('source_registry','verified_regulatory_evidence','verified_regulatory_claims');
update public.jurisdiction_dimension_coverage set status='verified_empty',applicability='applicable',evidence_basis='Primary statute establishes controls but no general commercial cannabis pathway or product-format rules.',last_evaluated_at=now() where jurisdiction_key='WS' and dimension_key in ('verified_pathways','verified_format_rules');
update public.jurisdiction_data_depth_tasks set status='verified',updated_at=now() where jurisdiction_key='WS' and dimension_key in ('source_registry','verified_regulatory_evidence','verified_regulatory_claims','verified_pathways','verified_format_rules') and status in ('open','in_progress','blocked');