-- Playbook content + market metrics for batch 23 (part B of B, see batch23a
-- for source_registry entries this migration references by source_url).

UPDATE public.jurisdiction_playbooks SET
  difficulty = 'high', typical_timeline_months = 24,
  estimated_cost_range = 'No standard fee schedule has been published, and several core procedural elements remain unclarified as of the most recent legal review — including the exact process for analyzing THC percentages, ongoing reporting requirements, and the contents of required feasibility studies. Any cost estimate at this stage would be speculative; specialized Lao legal counsel engagement is a prerequisite, not an optional cost',
  legal_framework_summary = 'Laos maintains one of the strictest cannabis regimes in Southeast Asia for anything above a narrow hemp carve-out, and any market-entry assessment must sharply distinguish that carve-out from the much larger space of activity that remains a serious criminal matter carrying penalties up to death. Cannabis (marijuana) is classified as a Category I narcotic under the Law on Narcotics No. 50/NA (2007, amended 2008) and the Decree on the Implementation of the Law on Narcotics No. 076/PM (2009), which declares the cannabis plant a narcotic-producing plant and prohibits its cultivation and possession outright; the Penal Code No. 26/NA (2017, revised as Article 146 in later consolidations) sets graduated penalties ranging from 3 months to life imprisonment and fines of LAK 500,000 to 200 million (roughly USD 52-21,200) depending on the quantity and nature of the offense, with trafficking of 500 grams or more carrying 10 years to life imprisonment and quantities above 3 kilograms carrying the death penalty. Enforcement is active at international entry points including Vientiane''s Wattay International Airport, Thai-Lao Friendship Bridge crossings, and the Boten border with China. Within this otherwise absolute prohibition, a narrow and relatively recent carve-out exists: in 2019 the Lao government established an ad hoc committee to study cannabis legalization potential and permitted select local companies to grow cannabis in specific pilot zones, while continuing to strictly prohibit use, commercialization, and consumption of any cannabis-related product regardless of THC content. This culminated in Decision No. 3789/MOH (28 December 2022), issued by the Ministry of Health, which approves regulated cultivation, extraction, production, processing, storage, distribution, utilization, import-export, and transport of hemp specifically — defined with a THC content limit of 0.2% for raw and processed products, not exceeding 1% by weight under Ministry permission — and authorizes use of hemp and hemp-related products by the general population, with certain products restricted to medical prescription. Seeds must be registered with authorized, traceable sources of origin. Critically, several operational aspects of this 2022 framework remain unclarified in practice as of the most recent legal commentary, including the precise procedure for THC percentage analysis, ongoing reporting obligations, and the required contents of feasibility studies companies must submit to the Ministry of Health — legal analysts anticipate these gaps will be resolved through administrative practice over time rather than through further formal regulation, meaning practical implementation guidance is still emerging. There is no indication of imminent broader liberalization: independent tourism-focused legal guides note no known law changes are anticipated in the near term regarding medical or recreational cannabis beyond the existing hemp decision.',
  steps = '[{"step":"Confirm the activity falls strictly within the hemp definition (0.2% THC raw/processed, capped at 1% by weight)","detail":"Decision 3789/MOH covers hemp specifically, not cannabis broadly — any product or activity involving higher-THC material remains prosecutable as a Category I narcotic offense with penalties up to death for large quantities"},{"step":"Engage specialized Lao legal counsel before any cultivation or import planning","detail":"Multiple procedural elements of the 2022 Decision — THC testing methodology, reporting cadence, feasibility study requirements — remain unclarified in publicly available guidance; local counsel with direct Ministry of Health relationships is necessary to navigate this ambiguity"},{"step":"Register seeds with authorized, traceable origin documentation","detail":"The Decision requires cannabis sativa L. seeds used for hemp production to be registered and have their source of origin authorized — build this into procurement planning from the outset"},{"step":"Prepare for likely administrative-practice-based implementation rather than further formal rulemaking","detail":"Legal analysts expect remaining gaps to be clarified through how the Ministry of Health applies the Decision in practice, not through new published regulations — ongoing direct engagement with the regulator is more valuable than waiting for clearer written rules"}]'::jsonb,
  key_regulators = '["Ministry of Health — Decision 3789/MOH hemp licensing, feasibility study review, THC compliance oversight","Lao National Commission for Drug Control and Supervision (LCDC) — narcotics enforcement, anti-narcotics police coordination","Ministry of Public Security — border and domestic narcotics enforcement"]'::jsonb,
  common_pitfalls = ARRAY[
    'Conflating the narrow 2022 hemp allowance with any broader cannabis legalization — Decision 3789/MOH applies specifically to hemp (0.2%-1% THC ceiling); THC-dominant cannabis remains a Category I narcotic with penalties up to death for large-quantity trafficking',
    'Assuming publicly visible informal tolerance (tourist-area "happy pizza" establishments) reflects actual legal status — possession and use remain criminal offenses regardless of casual local enforcement patterns, and this should never inform a compliance assessment',
    'Underestimating procedural ambiguity in the hemp framework — THC testing methodology, reporting requirements, and feasibility study standards are not fully published; treat early engagement with the Ministry of Health as essential rather than assuming a straightforward paper-only application process'
  ],
  status = 'published', last_reviewed = CURRENT_DATE,
  confidence_label = 'high — corroborated across a CMS Expert Guide, two separate Tilleke & Gibbins legal analyses (a Lao/Southeast Asia-focused firm) written at different points in the framework''s development, and WSR Law Group''s regulatory summary, all consistent on the Decision 3789/MOH THC thresholds and the narrow scope of the hemp carve-out relative to the broader narcotics prohibition',
  last_verified_at = now(),
  source_id = (SELECT id FROM public.source_registry WHERE source_url = 'https://cms.law/en/int/expert-guides/cms-expert-guide-to-a-legal-roadmap-to-cannabis/laos')
WHERE country_iso2 = 'LA';

UPDATE public.jurisdiction_playbooks SET
  difficulty = 'high', typical_timeline_months = 30,
  estimated_cost_range = 'Not applicable in practical terms — as of the latest Ministry of Health guidance, no cannabis-based product for human medical treatment is registered in Malaysia at all, and the narrow 2019 allowance covers only specific 0%-THC CBD-based pharmaceutical medicines for conditions such as epilepsy under prescription. There is no established commercial licensing fee structure because there is effectively no operating commercial pathway',
  legal_framework_summary = 'Malaysia maintains one of the world''s strictest drug law regimes, and cannabis in any commercial or recreational form remains fully illegal with no meaningful market-entry pathway as of 2026, despite periodic government statements floating conditional future access. Cannabis, cannabis resin, extracts, and tinctures are controlled substances under the Dangerous Drugs Act 1952, with recreational and medical use both prohibited outright for the general population. Malaysia''s statutory presumption-of-trafficking thresholds are severe: possession of 200 grams or more of cannabis triggers a presumption of trafficking under Section 37 of the Dangerous Drugs Act, carrying the death penalty or life imprisonment plus whipping. The Abolition of Mandatory Death Penalty Act 2023 (Act 846, in force July 2023) removed the mandatory death sentence for trafficking, giving courts discretion to impose life imprisonment plus whipping instead — but death remains a lawful sentence within judicial discretion for the most serious trafficking cases, and the government has stated no plans to remove it from the Act entirely; separately, mandatory caning for possession above 20 grams was unaffected by this reform. There is no foreign-national exception: tourists, students, and business travelers face identical prosecution risk as citizens and permanent residents, and consular access does not affect sentencing outcomes. A narrow medical allowance exists in principle: in November 2021, then-Health Minister Khairy Jamaluddin stated that import and use of medical marijuana would be allowed in rare cases, provided a patient has a doctor''s prescription and the product is registered and licensed by the Malaysian Drug Control Authority — but as of the latest available Ministry of Health guidance, no cannabis-based product for human medical treatment is actually registered in Malaysia, making this a theoretical rather than operational pathway. Companies seeking to bring a medical cannabis product to market face a structurally difficult bar: they must scientifically prove safety and efficacy based on evidence from a Malaysian-based study location, and because of cannabis''s criminalized status, conducting that research domestically is itself extremely difficult — a circular barrier that legal analysts describe as keeping the country in "the earliest phases of its potential end to prohibition." Malaysian officials have publicly referenced watching how neighboring Thailand handles its (subsequently reversed) legalization experiment to inform Malaysia''s own future policy direction, suggesting any material change remains speculative and distant rather than imminent. No CBD or hemp-derived product may legally be imported or possessed, including products legal in the traveler''s home country; customs enforcement includes urine testing at entry points.',
  steps = '[{"step":"Recognize there is no operational commercial pathway as of 2026","detail":"Despite a 2021 ministerial statement floating conditional medical marijuana access, no cannabis-based product is currently registered for medical use in Malaysia — there is no application process to enter because no product has successfully navigated it yet"},{"step":"If pursuing the theoretical medical pathway, budget for the domestic-research circularity problem","detail":"Registration requires proving safety/efficacy via a Malaysian-based study, but cannabis''s criminalized status makes conducting that research within Malaysia extremely difficult — this is a structural barrier, not merely a bureaucratic delay"},{"step":"Monitor Malaysia''s policy response to regional developments, particularly Thailand","detail":"Malaysian officials have publicly stated they are watching how Thailand''s cannabis policy evolves to inform Malaysia''s own approach — regional regulatory shifts are a more useful signal to track than domestic legislative activity, which has been minimal"},{"step":"Treat any hemp/CBD product plans as categorically prohibited, not merely restricted","detail":"Unlike many jurisdictions with a hemp/THC distinction, Malaysia draws no such line for import or possession purposes — all cannabis-derived products, including CBD, are illegal to bring into the country regardless of source-country legality"}]'::jsonb,
  key_regulators = '["Ministry of Health — medical product registration and licensing (currently zero products registered)","Malaysian Drug Control Authority — pharmaceutical licensing for any future medical cannabis product","Royal Malaysia Police and National Anti-Drugs Agency (AADK) — enforcement","Attorney General''s Chambers — prosecution"]'::jsonb,
  common_pitfalls = ARRAY[
    'Treating the 2021 ministerial statement on medical marijuana as an operational program — no cannabis-based product is registered for medical use in Malaysia as of the latest Ministry of Health guidance; this remains a theoretical allowance, not a functioning pathway',
    'Assuming any foreign medical cannabis card, CBD product legality in the traveler''s home country, or declared importation provides any protection — Malaysian law includes no foreign-national exception, and declaring a product at customs does not prevent prosecution',
    'Underestimating the domestic-research circularity barrier — bringing a medical cannabis product to market requires Malaysian-based clinical evidence, but the substance''s fully criminalized status makes that research exceptionally difficult to conduct, a structural chokepoint independent of any paperwork process'
  ],
  status = 'published', last_reviewed = CURRENT_DATE,
  confidence_label = 'high — corroborated across Herb.co''s May 2026 regulatory guide, Tripbase''s detailed penalty-threshold breakdown citing the Dangerous Drugs Act and Act 846 reforms, Leafwell''s policy-history summary quoting the 2021 ministerial statement directly, and Wikipedia''s cited entry, all consistent on the absence of any registered medical product and the 200g trafficking-presumption threshold',
  last_verified_at = now(),
  source_id = (SELECT id FROM public.source_registry WHERE source_url = 'https://herb.co/city-guides/buy-weed-malaysia')
WHERE country_iso2 = 'MY';

INSERT INTO public.market_metrics (country_iso2, metric_name, metric_value, metric_unit, period_start, period_end, period_granularity, data_type, confidence_band, source_name, source_url, source_date, notes)
VALUES
  ('LA', 'Death Penalty Trafficking Threshold', 3, 'kilograms', '2017-01-01', '2026-12-31', 'point_in_time', 'observed', 'high', 'Cannabisregulations.ai', 'https://www.cannabisregulations.ai/country-legality/laos-marijuana', '2026-01-01', 'Quantity threshold above which cannabis trafficking carries the death penalty under Article 146 of the Penal Code'),
  ('LA', 'Hemp THC Ceiling (Processed, Ministry-Permitted)', 1.0, 'percent', '2022-12-28', '2026-12-31', 'point_in_time', 'observed', 'high', 'WSR Law Group', 'https://wsrlawgroup.com/laos-allows-controlled-activities-of-hemp-and-cannabis-stiva-l-for-medical-use/', '2023-01-15', 'Maximum THC by weight for processed hemp products under Ministry of Health special permission; raw/processed default ceiling is 0.2%'),
  ('MY', 'Cannabis Trafficking Presumption Threshold', 200, 'grams', '1952-01-01', '2026-12-31', 'point_in_time', 'observed', 'high', 'Tripbase', 'https://www.tripbase.com/drug-laws/malaysia/cannabis/', '2026-01-01', 'Quantity above which Section 37 of the Dangerous Drugs Act 1952 creates a statutory presumption of trafficking, carrying death penalty or life imprisonment plus whipping within judicial discretion since Act 846 (2023)'),
  ('MY', 'Registered Medical Cannabis Products', 0, 'products', '2026-01-01', '2026-12-31', 'point_in_time', 'observed', 'high', 'Herb.co', 'https://herb.co/city-guides/buy-weed-malaysia', '2026-05-01', 'No cannabis-based product for human medical treatment registered as of the latest Ministry of Health guidance, despite a 2021 ministerial statement floating conditional access'),
  ('LC', 'Personal Possession Decriminalization Threshold', 30, 'grams', '2021-09-01', '2026-12-31', 'point_in_time', 'observed', 'high', 'LegalClarity', 'https://legalclarity.org/is-weed-legal-in-st-lucia-local-laws-explained/', '2026-01-01', 'Decriminalized threshold under the amended Drugs (Prevention of Misuse) Act, alongside 4-plant household cultivation allowance'),
  ('LC', 'Prior Convictions Automatically Expunged', 30, 'grams', '2021-08-01', '2021-08-31', 'point_in_time', 'observed', 'high', 'Leafwell', 'https://leafwell.com/blog/is-marijuana-legal-in-saint-lucia', '2026-01-01', 'Threshold for automatic expungement under the Criminal Records and Rehabilitation Amendment Bill, passed unanimously August 2021'),
  ('PR', 'Operational Dispensaries', 150, 'dispensaries', '2026-01-01', '2026-12-31', 'point_in_time', 'observed', 'high', 'IndicaOnline', 'https://indicaonline.com/blog/puerto-rico-marijuana-laws/', '2026-01-01', 'Over 150 dispensaries operational island-wide as of the most recent count, among the most mature medical cannabis retail networks per capita in the Caribbean/Latin America region'),
  ('PR', 'Authorized Hemp Product SKUs', 677, 'products', '2025-01-01', '2025-12-31', 'point_in_time', 'observed', 'high', 'Cannabisregulations.ai', 'https://www.cannabisregulations.ai/cannabis-and-hemp-regulations-compliance-ai-blog/puerto-rico-2025-mislabeled-hemp-crackdown', '2025-11-01', 'Hemp product SKUs authorized by the Office of Cannabis Regulation (OLIC) as of 2025, ahead of 2026 enforcement action against mislabeled high-THC products marketed as compliant hemp')
ON CONFLICT DO NOTHING;

UPDATE public.jurisdiction_playbooks_research_queue
SET playbook_status = 'published', last_researched_at = now(), last_researched_by = 'claude-agent'
WHERE country_code IN ('LA','MY','LC','PR');
