-- Primary-source enrichment for US-VA, verified 2026-09-22.
begin;
insert into public.source_registry(source_name,source_url,jurisdiction,country,iso,jurisdiction_code,tier,source_type,regulator_class,notes,verification_notes)
select 'Virginia Cannabis Control Authority — Retail Marijuana Market','https://cca.virginia.gov/retailmarijuanamarket','Virginia','United States','US-VA','US-VA',1,'government','other','Official CCA retail marijuana market framework and timeline.','Primary government source verified 2026-09-22.'
where not exists(select 1 from public.source_registry where source_url='https://cca.virginia.gov/retailmarijuanamarket' and jurisdiction_code='US-VA');
insert into public.source_registry(source_name,source_url,jurisdiction,country,iso,jurisdiction_code,tier,source_type,regulator_class,notes,verification_notes)
select 'Virginia Administrative Code — Cannabis Control Authority','https://law.lis.virginia.gov/admincodefull/title3/agency10/','Virginia','United States','US-VA','US-VA',1,'government','other','Official Virginia Administrative Code for medical cannabis operations, product rules, labeling and packaging.','Primary government source verified 2026-09-22.'
where not exists(select 1 from public.source_registry where source_url='https://law.lis.virginia.gov/admincodefull/title3/agency10/' and jurisdiction_code='US-VA');
insert into public.source_registry(source_name,source_url,jurisdiction,country,iso,jurisdiction_code,tier,source_type,regulator_class,notes,verification_notes)
select 'Virginia Code — Medical Cannabis Program definitions','https://law.lis.virginia.gov/vacodeupdates/title4.1/section4.1-1600/','Virginia','United States','US-VA','US-VA',1,'government','other','Official Code of Virginia definitions for medical cannabis, cannabis oil, edible, inhalable and topical cannabis products.','Primary government source verified 2026-09-22.'
where not exists(select 1 from public.source_registry where source_url='https://law.lis.virginia.gov/vacodeupdates/title4.1/section4.1-1600/' and jurisdiction_code='US-VA');
insert into public.regulatory_market_access_evidence(evidence_key,jurisdiction_iso2,tier,rationale,authority_name,authority_url,source_effective_date,verified_at,expires_at,active)
values('primary-evidence-us-va-retail-framework-20260922','VA','legal_commercial_access','Virginia legislation establishes a legal retail marijuana market; CCA states regulations are scheduled for January 2027 and retail sales for July 1, 2027.','Virginia Cannabis Control Authority','https://cca.virginia.gov/retailmarijuanamarket','2026-09-01',now(),now()+interval '180 days',true)
on conflict(evidence_key) do update set rationale=excluded.rationale,authority_name=excluded.authority_name,authority_url=excluded.authority_url,source_effective_date=excluded.source_effective_date,verified_at=excluded.verified_at,expires_at=excluded.expires_at,active=true;
insert into public.regulatory_market_access_claims(evidence_key,jurisdiction_iso2,claim_key,claim_text,product_class,jurisdiction_scope,authority_name,authority_url,source_effective_date,retrieved_at,verified_at,expires_at,evidence_status)
values('primary-evidence-us-va-retail-framework-20260922','VA','primary-evidence-claim:us-va-retail-framework-20260922','Virginia has enacted a legal retail marijuana market framework; CCA states regulations are to be effective in January 2027 and retail sales are scheduled for July 1, 2027.','any','subnational','Virginia Cannabis Control Authority','https://cca.virginia.gov/retailmarijuanamarket','2026-09-01',now(),now(),now()+interval '180 days','verified')
on conflict(claim_key) do update set claim_text=excluded.claim_text,authority_name=excluded.authority_name,authority_url=excluded.authority_url,verified_at=excluded.verified_at,expires_at=excluded.expires_at,evidence_status='verified';
insert into public.regulatory_pathways(country_id,iso_alpha2,slug,name,pathway_type,legal_basis,regulator,status,effective_date,summary,source_urls,verification,last_verified_at)
select c.id,'VA','depth-v1-us-va-retail','Virginia retail marijuana commercial market framework','adult_use_commercial','2026 Virginia legislation establishing a legal retail marijuana market','Virginia Cannabis Control Authority','scheduled','2027-07-01','Legal retail marijuana market enacted; regulations scheduled January 2027 and retail sales scheduled July 1, 2027.','{https://cca.virginia.gov/retailmarijuanamarket}','needs_review',now()
from public.countries c where c.iso_alpha2='US' and not exists(select 1 from public.regulatory_pathways where slug='depth-v1-us-va-retail');
insert into public.regulatory_citations(entity_type,entity_id,instrument,source_type,citation_url,published_date,accessed_date,excerpt)
select 'pathway',id,'Virginia retail marijuana market framework','regulator','https://cca.virginia.gov/retailmarijuanamarket','2026-09-01',current_date,'CCA states that 2026 legislation establishes a legal retail marijuana market and publishes the regulatory and retail-sales timeline.'
from public.regulatory_pathways where slug='depth-v1-us-va-retail' and not exists(select 1 from public.regulatory_citations c where c.entity_type='pathway' and c.entity_id=public.regulatory_pathways.id and c.citation_url='https://cca.virginia.gov/retailmarijuanamarket');
update public.regulatory_pathways set verification='verified',last_verified_at=now() where slug='depth-v1-us-va-retail';
insert into public.regulatory_pathways(country_id,iso_alpha2,slug,name,pathway_type,legal_basis,regulator,status,effective_date,summary,source_urls,verification,last_verified_at)
select c.id,'VA','depth-v1-us-va-medical','Virginia medical cannabis access program','medical_access_program','Virginia Code Chapter 16 and Virginia Administrative Code Title 3 Agency 10','Virginia Cannabis Control Authority','active','2026-03-09','Qualified patients access regulated cannabis products through licensed pharmaceutical processors and cannabis dispensing facilities.','{https://law.lis.virginia.gov/vacodeupdates/title4.1/section4.1-1600/,https://law.lis.virginia.gov/admincode/title3/agency10/chapter50/section80/,https://law.lis.virginia.gov/admincode/title3/agency10/chapter70/section20/}','needs_review',now()
from public.countries c where c.iso_alpha2='US' and not exists(select 1 from public.regulatory_pathways where slug='depth-v1-us-va-medical');
insert into public.regulatory_citations(entity_type,entity_id,instrument,source_type,citation_url,published_date,accessed_date,excerpt)
select 'pathway',id,'Virginia Code Chapter 16 — Medical Cannabis Program','regulator','https://law.lis.virginia.gov/vacodeupdates/title4.1/section4.1-1600/','2026-09-21',current_date,'Virginia law defines botanical cannabis, cannabis oil, cannabis products, edible, inhalable and topical cannabis products.'
from public.regulatory_pathways where slug='depth-v1-us-va-medical' and not exists(select 1 from public.regulatory_citations c where c.entity_type='pathway' and c.entity_id=public.regulatory_pathways.id and c.citation_url='https://law.lis.virginia.gov/vacodeupdates/title4.1/section4.1-1600/');
update public.regulatory_pathways set verification='verified',last_verified_at=now() where slug='depth-v1-us-va-medical';
insert into public.pathway_format_rules(pathway_id,format_id,status,conditions,notes,source_urls,verification,last_verified_at,effective_date,packaging_labelling)
select p.id,f.id,'permitted','{"medical_program":true}'::jsonb,'Virginia source defines and regulates this medical product category.','{https://law.lis.virginia.gov/vacodeupdates/title4.1/section4.1-1600/}','needs_review',now(),'2026-03-09','Virginia medical cannabis labeling and packaging rules apply.'
from public.regulatory_pathways p cross join public.product_formats f where p.slug='depth-v1-us-va-medical' and f.slug in('dried_flower','oral_oil','edibles','vape_products','topicals')
and not exists(select 1 from public.pathway_format_rules r where r.pathway_id=p.id and r.format_id=f.id);
insert into public.regulatory_citations(entity_type,entity_id,instrument,source_type,citation_url,published_date,accessed_date,excerpt)
select 'rule',r.id,'Virginia medical cannabis product definitions and labeling','regulator',r.source_urls[1],'2026-09-21',current_date,'Virginia Code and Administrative Code define and regulate the applicable medical cannabis product category.'
from public.pathway_format_rules r join public.regulatory_pathways p on p.id=r.pathway_id where p.slug='depth-v1-us-va-medical'
and not exists(select 1 from public.regulatory_citations c where c.entity_type='rule' and c.entity_id=r.id and c.citation_url=r.source_urls[1]);
update public.pathway_format_rules r set verification='verified',last_verified_at=now() from public.regulatory_pathways p where r.pathway_id=p.id and p.slug='depth-v1-us-va-medical';
insert into public.regulatory_calendar(iso2,event_type,title,summary,expected_date,confidence,source_url,source_label,status)
select 'VA','effective','Virginia retail marijuana sales scheduled start','CCA states retail marijuana sales begin July 1, 2027.','2027-07-01','confirmed','https://cca.virginia.gov/retailmarijuanamarket','Virginia Cannabis Control Authority','scheduled'
where not exists(select 1 from public.regulatory_calendar where iso2='VA' and title='Virginia retail marijuana sales scheduled start');
update public.jurisdiction_dimension_coverage set status='verified_populated',applicability='applicable',evidence_basis='Primary Virginia Cannabis Control Authority and Virginia Code/Administrative Code sources verified 2026-09-22',last_evaluated_at=now(),notes='Primary-source retail framework, medical pathway and medical product-format rules. Adult-use future-market formats remain open until final regulations are effective.'
where jurisdiction_key='US-VA' and dimension_key in('source_registry','verified_regulatory_evidence','verified_regulatory_claims','verified_pathways','verified_format_rules','regulatory_calendar');
update public.jurisdiction_data_depth_tasks set status='verified',updated_at=now(),notes=coalesce(notes,'')||' Primary US-VA enrichment added 2026-09-22.'
where jurisdiction_key='US-VA' and dimension_key in('source_registry','verified_regulatory_evidence','verified_regulatory_claims','verified_pathways','verified_format_rules','regulatory_calendar');
commit;