
insert into public.listings
  (id, category, title, description, product_type, region, price_range, seller_type,
   high_level_specs, status, public_visibility, is_featured, price_amount, price_currency,
   location_country, condition, brand, model, quantity, unit, slug, marketplace_section,
   sold_by_harbourview, sku, stock_qty, lead_time_days, moq, compliance_flags, target_countries,
   created_at, updated_at)
values
(gen_random_uuid(),'consumables','Empty 510 Vape Cartridge — 0.5mL Ceramic/Glass','Empty ceramic-coil 510 thread vape cartridge for oil filling.','vape_hardware','north_america','negotiable','distributor','{"size":"0.5mL","thread":"510","material":"ceramic/glass"}','approved',true,false,0.65,'CAD','CA','new','Harbourview Supply','HV-CART-05',1000,'each','empty-510-vape-cartridge-0-5ml','consumables',true,'HVP-VAP-C05',20000,14,500,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Empty 510 Vape Cartridge — 1.0mL Ceramic/Glass','Empty ceramic-coil 510 thread vape cartridge for oil filling.','vape_hardware','north_america','negotiable','distributor','{"size":"1.0mL","thread":"510","material":"ceramic/glass"}','approved',true,false,0.85,'CAD','CA','new','Harbourview Supply','HV-CART-10',1000,'each','empty-510-vape-cartridge-1-0ml','consumables',true,'HVP-VAP-C10',15000,14,500,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','510 Thread Battery — Variable Voltage, USB-C','Rechargeable 510 thread battery with variable voltage and USB-C charging.','vape_hardware','north_america','negotiable','distributor','{"thread":"510","charging":"USB-C","voltage":"variable"}','approved',true,false,2.20,'CAD','CA','new','Harbourview Supply','HV-BATT-1',1000,'each','510-thread-battery-variable-voltage-usbc','consumables',true,'HVP-VAP-BAT',12000,14,250,'{}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Vape Cartridge Box — 510 Push-Turn (Single)','Child-resistant push-and-turn carton for single 510 cartridges.','vape_packaging','north_america','negotiable','distributor','{"thread":"510","cr":true}','approved',true,false,0.30,'CAD','CA','new','Harbourview Supply','HV-VBOX-1',1000,'each','cr-vape-cartridge-box-510-push-turn','packaging',true,'HVP-VPK-BOX',20000,10,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Vape Cartridge Tube — 95mm Press-Button (Recyclable Cardboard)','Child-resistant, recyclable cardboard tube with press-button closure for 510 cartridges.','vape_packaging','north_america','negotiable','distributor','{"length":"95mm","material":"recyclable cardboard","cr":true}','approved',true,false,0.28,'CAD','CA','new','Harbourview Supply','HV-VTUBE-95',1000,'each','cr-vape-cartridge-tube-95mm-press-button','packaging',true,'HVP-VPK-TUB',18000,10,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Edible Single-Serving Stand-Up Pouch (10mg)','Child-resistant opaque stand-up pouch sized for a single 10mg THC edible package, per Health Canada''s 10mg/package limit.','edible_packaging','north_america','negotiable','distributor','{"dose_mg":10,"cr":true}','approved',true,true,0.12,'CAD','CA','new','Harbourview Supply','HV-EDPCH-10',1000,'each','cr-edible-single-serving-pouch-10mg','packaging',true,'HVP-EDB-PCH',20000,10,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"max_thc_mg_per_package":10}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Edible Multi-Cavity Blister Card (10 x 1mg)','Child-resistant blister card holding 10 x 1mg THC pieces, total 10mg per Health Canada package limit.','edible_packaging','north_america','negotiable','distributor','{"cavities":10,"dose_mg_each":1,"cr":true}','approved',true,false,0.24,'CAD','CA','new','Harbourview Supply','HV-EDBLIS-10',1000,'each','cr-edible-multi-cavity-blister-10x1mg','packaging',true,'HVP-EDB-BLI',15000,12,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"max_thc_mg_per_package":10}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Outer Carton for Edible Pouch (Health Warning Panel)','Opaque outer carton sized for edible pouches, with dedicated health-warning and cannabis-symbol panel per plain packaging rules.','edible_packaging','north_america','negotiable','distributor','{"cr":true}','approved',true,false,0.20,'CAD','CA','new','Harbourview Supply','HV-EDCARTON-1',1000,'each','cr-outer-carton-edible-pouch','packaging',true,'HVP-EDB-CTN',12000,12,500,'{"CA":{"opaque":true,"plain_packaging":true}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','Health Canada Compliant Label Roll — THC/CBD Panel + Symbol (Blank)','Blank-fill label roll pre-formatted with the standardized cannabis symbol, health warning, and THC/CBD info panel per plain packaging rules.','label','north_america','negotiable','distributor','{"format":"THC/CBD panel + symbol"}','approved',true,false,0.06,'CAD','CA','new','Harbourview Supply','HV-LBL-1','5000','each','hc-compliant-label-roll-thc-cbd-symbol','packaging',true,'HVP-LBL-001',200000,10,5000,'{"CA":{"plain_packaging":true,"cannabis_symbol":true,"health_warning":true}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','Batch/Lot Traceability Barcode Labels (Blank, Roll of 1000)','Blank barcode/lot-tracking labels for batch traceability.','label','north_america','negotiable','distributor','{}','approved',true,false,0.03,'CAD','CA','new','Harbourview Supply','HV-LBL-2',1000,'each','batch-lot-traceability-barcode-labels','packaging',true,'HVP-LBL-002',300000,7,5000,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Bulk Curing Tote / Turkey Bag (Large Format, Food-Grade)','Food-grade large-format bag for bulk curing of flower.','curing_supply','north_america','negotiable','distributor','{"format":"large bulk"}','approved',true,false,1.10,'CAD','CA','new','Harbourview Supply','HV-CURETOTE-1',500,'each','bulk-curing-tote-turkey-bag','consumables',true,'HVP-CUR-TOT',5000,10,100,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Vacuum-Seal Bulk Storage Bag (1kg Format)','Vacuum-seal bag sized for 1kg bulk flower storage.','curing_supply','north_america','negotiable','distributor','{"format":"1kg"}','approved',true,false,0.45,'CAD','CA','new','Harbourview Supply','HV-VACBAG-1KG',1000,'each','vacuum-seal-bulk-storage-bag-1kg','consumables',true,'HVP-CUR-VAC',8000,10,250,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Two-Way Humidity Control Packs — 69% RH (Bulk Case)','2-way humidity control packs, 69% RH, bulk case for larger-format curing.','humidity_pack','north_america','negotiable','distributor','{"rh":"69%"}','approved',true,false,0.40,'CAD','CA','new','Harbourview Supply','HV-HUMID-69',500,'each','humidity-control-packs-69rh-bulk','consumables',true,'HVP-HUM-069',9000,10,100,'{}','{CA}',now(),now()),
(gen_random_uuid(),'processing_equipment','Bench-Top Impulse Heat Sealer (Mylar Pouches)','Impulse heat sealer for sealing mylar pouches at the point of packing.','sealing_equipment','north_america','negotiable','distributor','{}','approved',true,false,210.00,'CAD','CA','new','Harbourview Supply','HV-SEALER-1',15,'unit','bench-top-impulse-heat-sealer','processing',true,'HVP-EQP-SEAL',15,10,1,'{}','{CA}',now(),now()),
(gen_random_uuid(),'processing_equipment','Semi-Automatic Capping Machine (CR Cap Application)','Semi-automatic machine for applying child-resistant caps to jars/bottles at production scale.','capping_equipment','north_america','negotiable','distributor','{}','approved',true,false,5400.00,'CAD','CA','new','Harbourview Supply','HV-CAPPER-1',3,'unit','semi-automatic-capping-machine-cr','processing',true,'HVP-EQP-CAP',3,28,1,'{}','{CA}',now(),now()),
(gen_random_uuid(),'processing_equipment','Semi-Automatic Label Applicator','Semi-automatic label applicator for jars, pouches, and cartons.','labeling_equipment','north_america','negotiable','distributor','{}','approved',true,false,3800.00,'CAD','CA','new','Harbourview Supply','HV-LABELER-1',3,'unit','semi-automatic-label-applicator','processing',true,'HVP-EQP-LBL',3,28,1,'{}','{CA}',now(),now()),
(gen_random_uuid(),'processing_equipment','Vape Cartridge Filling Machine (Semi-Automatic, Peristaltic)','Semi-automatic peristaltic filling machine for 510 vape cartridges.','filling_equipment','north_america','negotiable','distributor','{"mechanism":"peristaltic"}','approved',true,true,7200.00,'CAD','CA','new','Harbourview Supply','HV-FILLER-1',2,'unit','vape-cartridge-filling-machine-semi-auto','processing',true,'HVP-EQP-FIL',2,28,1,'{}','{CA}',now(),now());
