-- Seed country-level cannabis regulatory briefings: Europe
-- Countries: AL, AD, AT, BE, BY, BA, BG, HR, CY, CZ, DK, EE, FI, GR, HU, IS, IE, IT, XK, LV, LI, LT, LU, MT, MD, MC, ME, MK, NO, PL, PT, RO, RS, SK, SI, SE, CH, TR, UA, SM

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'albania','country','AL','Prohibited; Decriminalization Debate',
'Cannabis is prohibited in Albania under Law No. 7975 on Narcotic and Psychotropic Substances. Albania has been a significant illicit cannabis producer, particularly in the Lazarat region prior to 2014 law enforcement operations. Government-backed eradication campaigns have reduced large-scale production. There is no medical cannabis program. EU accession discussions may influence future drug policy reform.',
'No legal patient access pathway exists. Cannabis-based medicines are unavailable through official Albanian healthcare channels.',
'Albanian physicians cannot prescribe cannabis under the existing legal framework.',
'Albania''s illicit cannabis cultivation has been significantly reduced through enforcement operations, but informal production and export continue. No licensed commercial market exists. EU accession aspirations create some alignment pressure toward harm reduction approaches.',
'EU accession negotiations may encourage drug policy modernization. Medical cannabis reform is discussed in some policy circles but no legislation has been introduced. Change is possible over the medium term as EU alignment develops.',
'State Police and the National Anti-Drug Coordinator handle drug enforcement. Ministry of Health oversees pharmaceutical regulation.',
'Albania Law No. 7975; State Police drug enforcement data; EU accession monitoring reports','Current as of Q2 2026','Annual','Country-level briefing covering prohibition status and EU accession policy context',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='AL' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'andorra','country','AD','Prohibited',
'Cannabis is prohibited in Andorra under the Qualified Law on Criminal Provisions. As a small co-principality between France and Spain, Andorra''s drug policy is influenced by its larger neighbors, both of which maintain cannabis prohibition at the national level. There is no medical cannabis program.',
'No legal patient access pathway exists. Cannabis-based medicines are not available through official Andorran healthcare channels.',
'Andorran physicians cannot prescribe cannabis under the existing legal framework.',
'No licensed cannabis market exists. Andorra''s status as a tourist and duty-free shopping destination creates some cross-border informal trade dynamics.',
'No reform is anticipated. Andorra''s small size and co-principality governance structure limit independent drug policy development.',
'Cos de Policia d''Andorra handles drug enforcement. Ministry of Health oversees pharmaceutical regulation.',
'Andorra Qualified Law on Criminal Provisions; Ministry of Health pharmaceutical policy; regional monitoring','Current as of Q2 2026','Annual','Country-level briefing noting prohibition in micro-state context',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='AD' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'austria','country','AT','Medical Legal; Decriminalized',
'Austria legalized medical cannabis in 2008 under the Narcotic Substances Act (Suchtmittelgesetz/SMG). Cannabis for medical use is available through pharmacies with prescription. Austria decriminalized personal possession of small amounts in practice through prosecutorial guidelines. CBD products with THC below 0.3% are available as food supplements. Austria is an active participant in EU medical cannabis regulatory harmonization discussions.',
'Patients access medical cannabis through licensed pharmacies with a physician prescription. Domestic production by licensed operators and imports are both available. Products include standardized cannabis preparations (Bedrocan varieties) and magistral preparations. Cost is partly reimbursed by social insurance for certain conditions.',
'Austrian physicians (Ärzten) may prescribe medical cannabis for conditions including chronic pain, multiple sclerosis spasticity, and chemotherapy-induced nausea. A Suchtmittelrezept (special narcotic prescription) is required. Specialist referral is typically expected for complex conditions.',
'Austria has a functioning medical cannabis market with licensed import and limited domestic production. Several European cannabis operators supply the Austrian market. The magistral preparation pathway allows pharmacies to compound cannabis products from licensed starting material.',
'Austria''s medical program continues to mature. EU medical cannabis regulatory harmonization is expected to influence Austrian frameworks over 2025–2027. Adult-use legalization is debated but not imminent under current coalition dynamics.',
'AGES (Austrian Agency for Health and Food Safety) regulates medical cannabis. Bundesministerium für Gesundheit (BMG) sets health policy.',
'Austrian Suchtmittelgesetz (SMG); AGES regulatory guidance; BMG pharmaceutical policy; EU harmonization monitoring','Current as of Q2 2026; verified against AGES official guidance','Quarterly','Country-level briefing covering medical program, decriminalization, and EU harmonization context',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='AT' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'belarus','country','BY','Prohibited; Strict Enforcement',
'Cannabis is strictly prohibited in Belarus under the Law on Narcotic Drugs, Psychotropic Substances, Precursors and Analogues. Penalties are severe, including lengthy imprisonment. Belarus aligns its drug policy with Russian Federation norms and has not engaged with cannabis reform. There is no medical cannabis program. Belarus''s political context under President Lukashenko makes reform discussion effectively impossible.',
'No legal patient access exists. Cannabis-based medicines are unavailable through official Belarusian healthcare channels.',
'Belarusian physicians cannot prescribe cannabis under the existing legal framework.',
'No licensed cannabis market exists. Belarus enforces strict drug prohibition aligned with Russian drug enforcement norms.',
'No reform is anticipated. Belarus''s political environment under Lukashenko, combined with its alignment with Russian drug policy, makes cannabis liberalization effectively impossible in the near term.',
'Ministry of Internal Affairs handles drug enforcement. Ministry of Health oversees pharmaceutical regulation.',
'Belarus Law on Narcotic Drugs; Ministry of Internal Affairs enforcement data; EMCDDA European monitoring (limited)','Current as of Q2 2026','Annual','Country-level briefing noting strict prohibition aligned with Russian drug enforcement norms',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='BY' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'belgium','country','BE','Decriminalized (1 Plant); No Formal Medical Program',
'Belgium decriminalized personal possession of up to 3 grams and cultivation of one female plant through prosecutorial guidelines (circular). There is no formal national medical cannabis program — Belgium relies on the Schengen-area pharmaceutical framework, allowing physicians to prescribe cannabis preparations on a named-patient basis through import authorization. A national regulatory discussion on medical cannabis formalization has been ongoing. Belgium is a significant transit country for cannabis from the Netherlands.',
'Patients can access cannabis-based medicines including Sativex and Bedrocan varieties on a named-patient basis via pharmacies under physician prescription and import authorization. The process is administratively complex and costs are generally not reimbursed. Some magistral preparations are available through compounding pharmacies.',
'Belgian physicians (médecins/artsen) may prescribe cannabis preparations on a named-patient basis for conditions including multiple sclerosis spasticity, chronic pain, and nausea. No formally authorized domestic medical cannabis product exists, requiring reliance on import pathways.',
'Belgium does not have a licensed domestic medical cannabis production sector. The import authorization pathway allows global medical cannabis products to reach Belgian patients through established pharmaceutical channels. Several major European cannabis companies supply Belgian prescriptions.',
'Belgium is expected to formalize its medical cannabis framework, creating a structured licensing and reimbursement system. The coalition government has discussed harmonization with EU emerging norms. Adult-use reform beyond the current decriminalization is debated but not imminent.',
'FAMHP (Federal Agency for Medicines and Health Products / Federaal Agentschap voor Geneesmiddelen en Gezondheidsproducten) regulates cannabis medicines.',
'FAMHP guidance on cannabis-based medicines; Belgian prosecutorial circular on decriminalization; EMCDDA Belgium national report','Current as of Q2 2026; verified against FAMHP official guidance','Quarterly','Country-level briefing covering decriminalization, named-patient medical access, and formalization prospects',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='BE' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'bosnia-and-herzegovina','country','BA','Prohibited',
'Cannabis is prohibited in Bosnia and Herzegovina under the Law on Prevention and Suppression of Abuse of Narcotic Drugs. Bosnia''s complex governance structure (Federation of Bosnia and Herzegovina, Republika Srpska, and Brčko District) creates some variation in enforcement priorities, but all entities maintain formal prohibition. There is no medical cannabis program at the state or entity level.',
'No legal patient access exists. Cannabis-based medicines are unavailable through official Bosnian healthcare channels.',
'Bosnian physicians cannot prescribe cannabis under any existing legal framework.',
'No licensed cannabis market exists. Bosnia''s geographic position on Balkan drug trafficking routes creates some enforcement complexity.',
'No reform is anticipated in the near term. Bosnia''s complex governance structure and EU accession aspirations may eventually drive policy modernization, but cannabis reform is not a current priority.',
'Drug enforcement is handled by entity police forces (Federation Police and MUP Republika Srpska). Ministry of Civil Affairs coordinates health policy across entities.',
'Bosnia-Herzegovina narcotic drugs law; entity police drug enforcement data; EU accession monitoring','Current as of Q2 2026','Annual','Country-level briefing noting prohibition in complex governance structure',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='BA' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'bulgaria','country','BG','Prohibited; Industrial Hemp Sector',
'Cannabis is prohibited in Bulgaria under the Law on Control of Narcotic Substances and Precursors. There is no medical cannabis program. However, Bulgaria has developed a significant licensed industrial hemp cultivation sector, producing fiber hemp and increasingly hemp seeds and CBD-rich plant material for export. Bulgaria is one of the EU''s largest hemp cultivators, benefiting from favorable climate and agricultural infrastructure.',
'No legal patient access to medical cannabis exists. Cannabis-based pharmaceuticals are not available through official Bulgarian healthcare channels.',
'Bulgarian physicians cannot prescribe cannabis under the existing legal framework.',
'Bulgaria''s industrial hemp sector is a notable commercial success, with significant acreage under cultivation for fiber, seed, and CBD extract production. Bulgarian hemp products are exported throughout the EU. No medical cannabis commercial market exists.',
'Medical cannabis reform is under discussion as EU harmonization progresses. Bulgaria''s established hemp agricultural base positions it to expand into medical cannabis production if regulatory reform occurs, potentially by 2027–2028.',
'Bulgarian Drug Agency (BDA) handles drug control policy. Ministry of Agriculture oversees licensed hemp cultivation. Ministry of Health sets pharmaceutical policy.',
'Bulgaria Law on Control of Narcotic Substances; BDA regulatory guidance; Ministry of Agriculture hemp licensing data; EMCDDA Bulgaria report','Current as of Q2 2026','Quarterly','Country-level briefing covering prohibition with substantial licensed industrial hemp sector',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='BG' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'croatia','country','HR','Medical Legal; Decriminalized',
'Croatia introduced a medical cannabis program in 2015, one of the earliest in the former Yugoslav states. The program permits the prescription of standardized cannabis preparations for qualifying conditions. Personal possession of small amounts is an administrative offense rather than criminal, effectively decriminalizing personal use. Croatia''s Adriatic tourism sector has generated some public interest in cannabis policy modernization.',
'Patients access medical cannabis through licensed pharmacies with a physician prescription. Standardized dried cannabis (Bedrocan varieties) and cannabis oil are available. Products must meet Croatian Institute of Public Health standards. Social insurance reimbursement is available for specific conditions.',
'Croatian physicians may prescribe medical cannabis for conditions including multiple sclerosis, chronic pain, epilepsy, and cancer-related symptoms. Croatian Medical Chamber guidelines support evidence-based prescribing. Prescriptions require specialist endorsement for most indications.',
'Croatia has a small but functional medical cannabis market supplied primarily through imports. Domestic cultivation licenses have been issued to several operators, primarily for industrial hemp but with some medical cannabis production capacity. The market serves a growing patient base.',
'Croatia''s medical program is expected to continue developing. EU harmonization and the country''s growing tourism sector may create further policy momentum. Adult-use reform is discussed but not imminent under current governance.',
'HALMED (Agency for Medicinal Products and Medical Devices of Croatia) regulates medical cannabis products. Ministry of Health sets clinical guidelines.',
'HALMED regulatory guidance; Croatian Institute of Public Health standards; Ministry of Health clinical guidelines; EMCDDA Croatia report','Current as of Q2 2026; verified against HALMED official guidance','Quarterly','Country-level briefing covering medical program and decriminalization framework',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='HR' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'cyprus','country','CY','Medical Legal',
'Cyprus established a medical cannabis program in 2019 through the Medicinal Products (Human Use) Law and subsequent regulations. The program allows licensed cultivation, processing, and prescription of medical cannabis products. Cyprus has actively sought to position itself as a Mediterranean medical cannabis hub given its climate, EU membership, and existing pharmaceutical sector.',
'Patients access medical cannabis through licensed pharmacies with physician prescription. Both locally produced and imported products are available. The program covers conditions including multiple sclerosis, chronic pain, epilepsy, and cancer. Patient access has expanded since the program''s launch.',
'Cypriot physicians registered with the Medical Council may prescribe medical cannabis for qualifying conditions. Specialist recommendation is generally required for initial prescriptions. The Ministry of Health has issued clinical guidance for prescribers.',
'Cyprus has attracted international cannabis investment due to its EU membership, favorable climate, and business environment. Multiple licensed cultivation and production facilities have been established. Cyprus is developing export capabilities targeting EU member state markets.',
'Cyprus''s medical cannabis sector is growing. The country''s EU membership and favorable growing conditions position it well for further export market development. Regulatory refinements continue as the program matures.',
'Pharmaceutical Services (Ministry of Health) regulates medical cannabis licensing and product standards. Cyprus Police handles enforcement.',
'Cyprus Medicinal Products (Human Use) Law; Pharmaceutical Services regulatory guidance; Ministry of Health clinical guidelines; EMCDDA Cyprus report','Current as of Q2 2026; verified against Pharmaceutical Services guidance','Quarterly','Country-level briefing covering medical program and Mediterranean hub development',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CY' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'czech-republic','country','CZ','Medical Legal; Decriminalized',
'The Czech Republic has one of the most progressive cannabis frameworks in Central Europe. Personal possession of up to 10 grams is decriminalized (administrative fine only). A medical cannabis program was established in 2013, though initially limited by import constraints. Regulatory amendments have expanded access to include domestically produced cannabis. Czech society has a long tradition of cannabis tolerance and public polling consistently shows majority support for adult-use legalization.',
'Patients access medical cannabis through licensed pharmacies with physician prescription. Both domestic and imported products are available. Patient registration is not required. Health insurance reimbursement is available for epilepsy (particularly childhood epilepsy) and some other conditions. Out-of-pocket costs apply for most patients.',
'Czech physicians may prescribe medical cannabis for a wide range of conditions including chronic pain, cancer, multiple sclerosis, epilepsy, and palliative care. General practitioners can prescribe; specialist referral is not mandated. The Czech Medical Chamber has issued guidance supporting evidence-based prescribing.',
'The Czech medical cannabis market has grown significantly since domestic production was licensed. Multiple Czech companies hold cultivation and processing licenses. The market is competitive with both domestic brands and imported products from the Netherlands, Canada, and other markets.',
'Czech Republic is actively discussing adult-use legalization. Governing coalition parties have expressed support for reform, and a regulatory proposal has been under development. Medical program expansion and potential adult-use legalization before 2027 are realistic scenarios.',
'SÚKL (State Institute for Drug Control / Státní ústav pro kontrolu léčiv) regulates medical cannabis products and licensing. Ministry of Health sets clinical guidelines.',
'SÚKL regulatory guidance and licensed product database; Ministry of Health clinical guidelines; decriminalization framework; adult-use reform legislative tracking','Current as of Q2 2026; verified against SÚKL official guidance','Quarterly','Country-level briefing covering medical program, decriminalization, and adult-use reform trajectory',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CZ' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'denmark','country','DK','Medical Pilot Program; CBD Legal',
'Denmark launched a four-year medical cannabis pilot program in January 2018, which has subsequently been made permanent through legislative extension. The program permits licensed import and dispensing of standardized cannabis products. CBD products below 0.2% THC are available as food supplements or over-the-counter products. Denmark has also licensed limited domestic cannabis cultivation for the pilot program.',
'Patients access medical cannabis through licensed pharmacies with a general practitioner or specialist prescription. Products include cannabis oils and dried flower from licensed producers. Health insurance reimbursement is not currently available, making cost a barrier for many patients. Patient numbers have grown steadily since 2018.',
'Danish physicians (læger) may prescribe from the approved product list for conditions including multiple sclerosis, chronic pain, and chemotherapy-induced nausea. Prescribing is not limited to specialists. The Danish Health Authority has issued guidance on appropriate prescribing conditions.',
'Denmark''s pilot program has established an import-dependent medical cannabis market. Danish Medic Cannabis has been a key domestic license holder. The program has attracted interest from international cannabis companies seeking market access.',
'Denmark''s permanent medical program is expected to expand its approved product list. Industrial hemp legalization with higher THC limits is under discussion. Adult-use reform is debated but not imminent under current political dynamics.',
'Danish Medicines Agency (Lægemiddelstyrelsen) administers the medical cannabis pilot program and regulates cannabis products. Ministry of Health sets health policy.',
'Danish Medicines Agency pilot program reports; approved product list; Danish Health Authority prescribing guidance; EMCDDA Denmark report','Current as of Q2 2026; verified against Lægemiddelstyrelsen official guidance','Quarterly','Country-level briefing covering permanent medical pilot program and CBD market',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='DK' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'estonia','country','EE','Prohibited; No Formal Medical Program',
'Cannabis is prohibited in Estonia under the Narcotic Drugs and Psychotropic Substances Act. Estonia has one of the stricter drug enforcement postures among Baltic states, with low-threshold criminalization. There is no medical cannabis program. CBD products with very low THC exist in a complex legal gray area. Estonia''s digital-first governance approach has not extended to cannabis policy modernization.',
'No formal patient access exists. Some CBD products are available through commercial channels in uncertain legal status. No medical cannabis pathway through the healthcare system exists.',
'Estonian physicians cannot prescribe cannabis under the existing legal framework.',
'No licensed cannabis market exists. The CBD sector operates under uncertain regulatory conditions. EU harmonization may eventually clarify CBD product status.',
'Medical cannabis reform discussions occur but no legislative action is imminent. EU harmonization of CBD regulations may create some change pressure over 2025–2027.',
'Estonian Police and Border Guard Board handles drug enforcement. State Agency of Medicines (Ravimiamet) oversees pharmaceutical regulation.',
'Estonia Narcotic Drugs Act; Ravimiamet pharmaceutical registry; EMCDDA Estonia report','Current as of Q2 2026','Annual','Country-level briefing noting prohibition with complex CBD status',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='EE' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'finland','country','FI','Medical Legal (Limited); Prohibited for Recreational Use',
'Finland has a limited medical cannabis framework under the Finnish Medicines Act. Cannabis-based medicines including Sativex (approved 2012) and nabiximols are available through prescription. A broader medical cannabis framework has not been enacted, and patient access remains limited compared to many EU peers. CBD products in food supplement form with THC below 0.2% are available commercially.',
'Patients access approved cannabis-based medicines (primarily Sativex for multiple sclerosis spasticity) through licensed pharmacies with specialist prescription. Special authorization (erityislupa) from Fimea is required for non-approved cannabis preparations. Patient numbers remain relatively low due to administrative barriers.',
'Finnish physicians may prescribe approved cannabis-based medicines (Sativex) without special authorization. Non-approved cannabis preparations require special authorization from Fimea, which adds administrative burden.',
'Finland''s cannabis medicine market is small and primarily Sativex-focused. Broader medical cannabis market development is constrained by the absence of a formal licensed supply framework. International cannabis companies have expressed interest in Finland as EU market access potential grows.',
'Finland''s conservative social policies make rapid medical cannabis expansion challenging, but EU harmonization pressures may drive framework development. A formal medical cannabis program broader than the current approved medicines approach is possible over 2026–2028.',
'Finnish Medicines Agency (Fimea) regulates medicinal cannabis products. Ministry of Social Affairs and Health sets health policy.',
'Fimea pharmaceutical registry; Finnish Medicines Act; special authorization (erityislupa) data; EMCDDA Finland report','Current as of Q2 2026; verified against Fimea official guidance','Quarterly','Country-level briefing covering limited approved medicines framework and reform prospects',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='FI' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'greece','country','GR','Medical Legal; Export Focus',
'Greece legalized medical cannabis in 2017 (Law 4523/2018, regulations 2018) and has made medical cannabis cultivation a priority sector for agricultural economic development. Greece offers licensed cultivation and processing with specific focus on export to European markets, particularly Germany. Greece''s Mediterranean climate and existing agricultural infrastructure make it an attractive medical cannabis production hub.',
'Patients access medical cannabis through licensed pharmacies with physician prescription. Both imported and domestically produced products are available. Greek health insurance (EOPYY) provides partial reimbursement for specific indications including multiple sclerosis and epilepsy. Product availability has expanded as domestic production has come online.',
'Greek physicians may prescribe medical cannabis for a broad range of qualifying conditions. Specialist recommendation is expected for complex conditions. Greek Medical Association has issued guidance supporting evidence-based prescribing practices.',
'Greece has developed a competitive licensed medical cannabis cultivation sector with multiple licensed operators producing for both domestic use and export. Greek-produced cannabis flower and extract is exported primarily to Germany and other EU member states. Several international cannabis companies have established Greek operations.',
'Greece''s medical cannabis export sector is expected to continue growing, particularly as Germany''s domestic cultivation ramp-up creates transition demand. Greece is positioning as a major Southern European cannabis producer. Further regulatory streamlining to support exports is expected.',
'EOF (National Organization for Medicines / Εθνικός Οργανισμός Φαρμάκων) regulates medical cannabis products and licensing. Ministry of Rural Development and Food oversees cultivation licensing.',
'Greek Law 4523/2018; EOF regulatory guidance and licensed product database; Ministry of Rural Development cultivation license data; EMCDDA Greece report','Current as of Q2 2026; verified against EOF official guidance','Quarterly','Country-level briefing covering medical program and export-focused cultivation sector',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='GR' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'hungary','country','HU','Prohibited; Limited CBD Tolerance',
'Cannabis is prohibited in Hungary under the Criminal Code and Act L of 2005 on narcotic substances. Hungary has one of the most restrictive cannabis enforcement postures in the EU, with the governing Fidesz party explicitly opposing liberalization. There is no medical cannabis program. CBD products are in a legal gray area and face inconsistent enforcement. Hungary has not aligned with emerging EU medical cannabis norms.',
'No legal patient access to medical cannabis exists. Cannabis-based pharmaceuticals are not accessible through Hungarian healthcare channels.',
'Hungarian physicians cannot prescribe cannabis under the existing legal framework.',
'No licensed cannabis market exists. Hungary''s political environment actively discourages cannabis sector development. CBD products are commercially available but face regulatory uncertainty.',
'No reform is expected under current Fidesz governance. Hungary is likely to remain an EU outlier on cannabis policy for the foreseeable future. Medical reform would require a fundamental change in governing coalition.',
'National Police Headquarters handles drug enforcement. National Institute of Pharmacy and Nutrition (OGYÉI) oversees pharmaceutical regulation.',
'Hungary Criminal Code drug provisions; Act L/2005; OGYÉI pharmaceutical registry; EMCDDA Hungary report','Current as of Q2 2026','Annual','Country-level briefing noting strict prohibition and political resistance to reform',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='HU' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'iceland','country','IS','Medical Legal (Limited)',
'Iceland permits medical cannabis use under the Medicines Act and associated regulations. Medical cannabis products can be prescribed on a named-patient basis with authorization from the Icelandic Medicines Agency. Personal possession of small amounts is treated as a minor offense in practice. Iceland''s geographic isolation and small population (approximately 370,000) limit market scale.',
'Patients access medical cannabis through named-patient authorization from the Icelandic Medicines Agency and pharmacy dispensing with physician prescription. Products are primarily imported. Patient numbers are limited by small population and administrative process.',
'Icelandic physicians may apply for named-patient authorization to prescribe cannabis-based medicines. No domestic production exists, so all products are imported. Specialist recommendation is typically required.',
'Iceland''s medical cannabis market is very small given its population. No domestic cultivation or production is licensed. The market is served entirely by imports under named-patient authorization.',
'Iceland may develop a more structured medical cannabis framework as EU and European Economic Area norms evolve. Population size limits significant market development.',
'Icelandic Medicines Agency (Lyfjastofnun) administers medical cannabis authorizations. Directorate of Customs handles import controls.',
'Iceland Medicines Act; Lyfjastofnun named-patient authorization data; EMCDDA Iceland report','Current as of Q2 2026','Annual','Country-level briefing covering limited named-patient medical access',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='IS' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'ireland','country','IE','Medical Legal; Access Programme',
'Ireland introduced a Medical Cannabis Access Programme (MCAP) in June 2019, initially as a five-year pilot. The program was made permanent through the Health (Cannabis) Act 2023. The program covers three conditions: spasticity associated with multiple sclerosis, intractable nausea and vomiting associated with chemotherapy, and severe, refractory treatment-resistant epilepsy. Products must be imported and meet quality standards. Ireland''s program has been described as one of Europe''s most restrictive medical frameworks.',
'Patients access medical cannabis exclusively through the MCAP with a hospital consultant prescription and HSE pre-authorization. Products are dispensed from designated pharmacies. The three-condition restriction significantly limits patient eligibility. HSE funding for approved patients covers product costs.',
'Access is restricted to hospital consultants (neurologists, oncologists, and other relevant specialists) who must register with the HSE to prescribe under the MCAP. General practitioners cannot prescribe under the program. Administrative requirements are extensive.',
'Ireland''s medical cannabis market is small given the restrictive three-condition program. Product supply relies entirely on licensed importers. Several international cannabis companies supply Irish patients through the import authorization pathway.',
'Ireland''s government is expected to consider MCAP expansion beyond the three qualifying conditions, particularly following the permanent program establishment. A broader medical access framework is advocated by patient organizations. Adult-use legalization has been recommended by an Oireachtas joint committee but is not yet government policy.',
'Health Products Regulatory Authority (HPRA) regulates medical cannabis products and import authorizations. HSE administers the MCAP. Department of Health sets health policy.',
'Health (Cannabis) Act 2023; HPRA regulatory guidance; HSE MCAP administration data; Oireachtas joint committee report; EMCDDA Ireland report','Current as of Q2 2026; verified against HPRA official guidance','Quarterly','Country-level briefing covering MCAP establishment, access restrictions, and reform prospects',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='IE' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'italy','country','IT','Medical Legal; Home Cultivation Court-Permitted',
'Italy has a complex cannabis legal landscape. Medical cannabis has been permitted since 2007 under DM 9 November 2015 regulations. A landmark 2019 Supreme Court ruling (Corte di Cassazione) effectively permitted small-scale home cultivation for personal use, though Parliament has not codified this into legislation. Cannabis light (hemp with low THC) was a major commercial sector before regulatory uncertainty reduced market clarity. Italy is a significant medical cannabis importer and has a military-run domestic production facility (Stabilimento Chimico Farmaceutico Militare).',
'Patients access medical cannabis through licensed pharmacies (farmacie) with physician prescription. Products include standardized preparations from the military facility (FM2 varieties) and imported products. Health insurance reimbursement varies by region — some regions cover costs, others require full patient payment. Patient numbers have grown significantly.',
'Italian physicians (medici) may prescribe medical cannabis for conditions including multiple sclerosis, chronic pain, epilepsy, and palliative care. General practitioners can prescribe with a standard prescription form. Regional health authorities may issue guidance on prioritized indications.',
'Italy has a significant and growing medical cannabis market. The Military Chemical Pharmaceutical Plant produces domestic supply (FM2), supplemented by substantial imports. Canada, Netherlands, Portugal, and other exporters supply Italian pharmacies. The cannabis light (CBD hemp) sector operates in a complex legal environment following court rulings.',
'Italy is expected to expand its medical cannabis framework and increase domestic production capacity. Adult-use legalization has been discussed extensively in Parliament without passage. Further regulatory clarity on home cultivation and cannabis light is anticipated. Italy''s large patient base makes it one of Europe''s most significant medical cannabis markets.',
'AIFA (Agenzia Italiana del Farmaco) regulates medical cannabis products. Stabilimento Chimico Farmaceutico Militare produces domestic supply. Ministry of Health sets clinical guidelines.',
'AIFA regulatory guidance; Italian DM November 2015; Supreme Court ruling 2019; EMCDDA Italy report; SCFM production data','Current as of Q2 2026; verified against AIFA official guidance','Quarterly','Full country-level briefing covering medical program, court-permitted home cultivation, and domestic military production',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='IT' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'kosovo','country','XK','Prohibited',
'Cannabis is prohibited in Kosovo under the Law on Prevention of and Fight against Narcotic Drugs. Kosovo, a partially recognized state, has been working to align its legal framework with EU standards as part of its EU integration aspirations. There is no medical cannabis program. Enforcement capacity is developing as Kosovo strengthens its institutions.',
'No legal patient access exists. Cannabis-based medicines are unavailable through official Kosovar healthcare channels.',
'Kosovar physicians cannot prescribe cannabis under the existing legal framework.',
'No licensed cannabis market exists. Kosovo''s geographic position in the Western Balkans creates some cross-border informal trade dynamics.',
'EU integration aspirations may eventually drive alignment with EU medical cannabis norms. No imminent legislative action is anticipated.',
'Kosovo Police handles drug enforcement. Ministry of Health oversees pharmaceutical regulation.',
'Kosovo Law on Prevention of Narcotic Drugs; Ministry of Health pharmaceutical policy; EU integration monitoring','Current as of Q2 2026','Annual','Country-level briefing noting prohibition with EU integration policy context',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='XK' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'latvia','country','LV','Medical Legal (Limited); CBD Regulated',
'Latvia established a limited medical cannabis framework under pharmaceutical regulations, permitting access to cannabis-based medicines on a named-patient basis. Latvia has also implemented one of the EU''s clearer regulatory frameworks for CBD products, treating them as novel foods under EU Novel Foods Regulation. Recreational use remains prohibited with criminal penalties.',
'Patients may access cannabis-based medicines through named-patient authorization from the State Agency of Medicines with physician prescription. Products must be pharmacy-dispensed. Patient numbers are limited due to administrative requirements.',
'Latvian physicians may apply for named-patient authorization to prescribe cannabis-based medicines. The process involves regulatory approval and is administratively demanding. No domestic production exists.',
'Latvia''s medical cannabis market is very small. The CBD consumer goods market operates under the EU Novel Foods framework. International cannabis companies supply Latvian named-patient prescriptions through import authorizations.',
'Latvia may develop a broader medical cannabis program as EU harmonization progresses. CBD regulatory clarity provides a positive foundation for expanded cannabis product frameworks.',
'State Agency of Medicines (Zāļu valsts aģentūra/ZVA) regulates medical cannabis products and authorizations. Ministry of Health sets health policy.',
'ZVA pharmaceutical registry and authorization data; Latvia Novel Foods CBD framework; EMCDDA Latvia report','Current as of Q2 2026; verified against ZVA official guidance','Annual','Country-level briefing covering limited medical access and regulated CBD framework',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='LV' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'liechtenstein','country','LI','Prohibited; Swiss Framework Adjacent',
'Cannabis is prohibited in Liechtenstein under the Betäubungsmittelgesetz (Narcotics Act). Liechtenstein closely aligns its legal framework with Switzerland given its customs union and economic integration. Switzerland has enacted adult-use pilot programs, but Liechtenstein has not followed with equivalent legislation. There is no medical cannabis program.',
'No formal patient access exists in Liechtenstein. Residents may potentially access Swiss medical cannabis systems given cross-border integration, but no domestic framework exists.',
'Liechtenstein physicians cannot prescribe cannabis domestically. Cross-border access to Swiss medical frameworks may be practically available to some residents.',
'No licensed cannabis market exists in Liechtenstein. Swiss cannabis developments may have indirect influence given economic integration.',
'Liechtenstein may follow Switzerland''s evolution if the Swiss adult-use pilot programs lead to full legalization, but no independent legislative action is expected.',
'Liechtenstein National Police handles drug enforcement. Office for Health handles pharmaceutical regulation.',
'Liechtenstein Betäubungsmittelgesetz; Swiss-Liechtenstein customs union arrangements; EMCDDA monitoring','Current as of Q2 2026','Annual','Country-level briefing noting prohibition with Swiss framework adjacency',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='LI' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'lithuania','country','LT','Medical Legal',
'Lithuania established a medical cannabis framework through the Law on Narcotic and Psychotropic Substances amendments in 2018. The program allows physician prescription of medical cannabis products for qualifying conditions. Lithuania has taken a measured but functional approach to medical access, distinguishing it from some Baltic peers.',
'Patients access medical cannabis through licensed pharmacies with physician prescription. Products include approved cannabis-based medicines available through import authorization. Patient registration is not required. Out-of-pocket costs apply as health insurance reimbursement is limited.',
'Lithuanian physicians may prescribe medical cannabis for conditions including multiple sclerosis, chronic pain, and chemotherapy-related symptoms. No specialist-only restriction applies in general, though complex conditions typically involve specialist input.',
'Lithuania''s medical cannabis market is small but functional. Products are supplied through import authorization pathways. Domestic cultivation has not been licensed for medical purposes, though industrial hemp is grown commercially.',
'Lithuania may develop domestic medical cannabis production as EU harmonization creates market opportunities. Further program expansion is expected as clinical evidence accumulates.',
'State Medicines Control Agency (SMCA/Valstybinė vaistų kontrolės agentūra) regulates medical cannabis products. Ministry of Health sets clinical guidelines.',
'SMCA pharmaceutical registry; Lithuanian Law on Narcotic and Psychotropic Substances 2018 amendment; EMCDDA Lithuania report','Current as of Q2 2026','Annual','Country-level briefing covering functional medical cannabis program',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='LT' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'luxembourg','country','LU','Adult-Use Home Cultivation Legal; Medical Legal',
'Luxembourg became the first European country to fully legalize adult-use cannabis cultivation and possession for personal use in October 2023. Adults may cultivate up to four plants at home and possess up to three grams in public. Commercial adult-use sales remain prohibited pending further regulatory development. Luxembourg also has a medical cannabis program established in 2018, which provides pharmacy-dispensed products under physician prescription.',
'Medical cannabis patients access products through licensed pharmacies with physician prescription. The 2018 medical program covers conditions including multiple sclerosis, chronic pain, and cancer. Adults may also cultivate cannabis at home for personal use under the 2023 reform.',
'Luxembourg physicians may prescribe medical cannabis for qualifying conditions under the 2018 medical framework. General practitioners can prescribe with standard prescription procedures.',
'Luxembourg''s medical cannabis market is small given the country''s population of approximately 660,000. The 2023 home cultivation reform has not yet created commercial sales infrastructure. Interest in commercial adult-use framework development is high given Luxembourg''s role in EU policy signaling.',
'Luxembourg is expected to develop a commercial adult-use sales framework. As the first EU country to permit adult-use possession, Luxembourg''s policy development will be closely watched by EU institutions and member states. Commercial framework details are anticipated over 2025–2027.',
'Direction de la Santé (Health Directorate) regulates medical cannabis products. Ministry of Health sets health policy. Ministère de la Justice oversees drug law enforcement.',
'Luxembourg Law of 19 February 2018 (medical); Law of 8 June 2023 (adult-use home cultivation); Direction de la Santé regulatory guidance; EMCDDA Luxembourg report','Current as of Q2 2026; verified against Direction de la Santé guidance','Quarterly','Country-level briefing covering first EU adult-use legalization (home cultivation) and medical program',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='LU' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'malta','country','MT','Adult-Use Legal (First Full EU Nation); Medical Legal',
'Malta became the first EU member state to legalize adult-use cannabis in December 2021 through the Authority on the Responsible Use of Cannabis Act (ARUCA). Adults may possess up to seven grams and cultivate up to four plants at home. Cannabis clubs (non-profit associations) are licensed to cultivate and distribute to members. Malta also has an existing medical cannabis program established in 2018. Commercial adult-use retail has not been implemented.',
'Patients access medical cannabis through licensed pharmacies with physician prescription under the 2018 medical program. Adults may also access cannabis through non-profit cannabis clubs under ARUCA. The club model requires membership and operates under ARUCA licensing.',
'Maltese physicians may prescribe medical cannabis for qualifying conditions under the 2018 medical framework. ARUCA''s club model also provides a non-medical adult-use pathway.',
'Malta''s cannabis club model has developed slowly since ARUCA''s passage. A small number of clubs have received licenses. The medical cannabis market continues to operate in parallel. Malta''s small size (approximately 500,000 population) limits overall market scale.',
'Malta continues to develop the ARUCA regulatory framework and cannabis club infrastructure. Its role as the first EU nation with full adult-use legislation — even without commercial retail — makes Malta an important EU policy reference. Commercial retail remains under consideration.',
'Authority on the Responsible Use of Cannabis (ARUCA) administers the adult-use framework. Medicines Authority regulates medical cannabis products. Ministry of Health sets health policy.',
'ARUCA Act 2021; Medicines Authority medical cannabis framework; ARUCA annual reports; EMCDDA Malta report','Current as of Q2 2026; verified against ARUCA and Medicines Authority guidance','Quarterly','Country-level briefing covering landmark first-EU adult-use legalization and dual medical/adult-use framework',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='MT' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'moldova','country','MD','Prohibited',
'Cannabis is prohibited in Moldova under the Law on Narcotic Drugs, Psychotropic Substances and Precursors. Moldova maintains prohibition with significant enforcement given its position as a transit country on Balkan drug routes. There is no medical cannabis program. EU association agreement implementation may drive eventual policy modernization.',
'No legal patient access exists. Cannabis-based medicines are unavailable through official Moldovan healthcare channels.',
'Moldovan physicians cannot prescribe cannabis under the existing legal framework.',
'No licensed cannabis market exists. Moldova''s position on transit routes creates enforcement challenges.',
'EU association agreement implementation may eventually influence cannabis policy. No imminent reform is anticipated.',
'Ministry of Internal Affairs handles drug enforcement. Agency of Medicines and Medical Devices (AMDM) oversees pharmaceutical regulation.',
'Moldova Law on Narcotic Drugs; AMDM pharmaceutical registry; EU Association Agreement monitoring; EMCDDA Southeast Europe monitoring','Current as of Q2 2026','Annual','Country-level briefing noting prohibition with EU association context',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='MD' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'monaco','country','MC','Prohibited',
'Cannabis is prohibited in Monaco under the Criminal Code and drug control legislation. As a city-state closely integrated with France, Monaco''s drug policy is strongly influenced by French prohibition. There is no medical cannabis program. Monaco''s very small territory and wealthy population create unique enforcement dynamics.',
'No legal patient access exists. Cannabis-based medicines are unavailable through official Monegasque healthcare channels.',
'Monegasque physicians cannot prescribe cannabis under the existing legal framework.',
'No licensed cannabis market exists. Monaco''s integration with France means drug policy alignment with French national policy.',
'No reform is anticipated independently. If France were to establish medical cannabis, Monaco may follow, but no independent reform is expected.',
'Direction de la Sûreté Publique handles drug enforcement. Department of Health and Social Services oversees health regulation.',
'Monaco Criminal Code drug provisions; Ministry of Health pharmaceutical policy; French drug policy alignment monitoring','Current as of Q2 2026','Annual','Country-level briefing noting prohibition aligned with French policy',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='MC' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'montenegro','country','ME','Decriminalized; No Medical Program',
'Montenegro decriminalized possession of small amounts of cannabis for personal use, treating it as a minor offense subject to fines rather than criminal prosecution. There is no medical cannabis program. Montenegro''s EU accession candidacy creates some alignment pressure toward harm reduction approaches, but no formal medical framework has been enacted.',
'No formal patient access to medical cannabis exists. Cannabis-based pharmaceuticals are not available through official Montenegrin healthcare channels.',
'Montenegrin physicians cannot prescribe cannabis under the existing legal framework.',
'No licensed cannabis market exists. Montenegro''s Adriatic tourism sector may create informal market dynamics similar to neighboring Croatia.',
'EU accession negotiations may drive medical cannabis policy development. No imminent legislative action is confirmed.',
'Montenegro Police handles drug enforcement. Ministry of Health oversees pharmaceutical regulation.',
'Montenegro Criminal Code drug provisions; Ministry of Health pharmaceutical policy; EU accession monitoring; EMCDDA Western Balkans monitoring','Current as of Q2 2026','Annual','Country-level briefing noting decriminalization and absence of medical framework',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='ME' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'north-macedonia','country','MK','Medical Legal',
'North Macedonia introduced a medical cannabis framework in 2016 through amendments to the Law on Psychotropic Substances. The program permits licensed cultivation, processing, and prescription of medical cannabis products. North Macedonia has also developed an export-oriented licensed cannabis cultivation sector targeting EU markets, taking advantage of its climate and lower production costs relative to Western Europe.',
'Patients access medical cannabis through licensed pharmacies with physician prescription. Both domestically produced and imported products are available. Patient registration is required. Limited health insurance coverage exists for specific conditions.',
'Macedonian physicians may prescribe medical cannabis for qualifying conditions including epilepsy, multiple sclerosis, and chronic pain. Specialist recommendation may be required for initial prescriptions.',
'North Macedonia has developed a licensed medical cannabis production sector with export orientation. Several international cannabis companies have established Macedonian growing operations. The export market, primarily targeting Germany and other EU markets, represents a significant economic opportunity.',
'North Macedonia''s medical cannabis sector is expected to continue growing, particularly export capacity. EU accession aspirations may drive further regulatory harmonization. The country''s production cost advantages position it competitively in European supply chains.',
'Agency for Drugs and Medical Devices (MALMED) regulates medical cannabis. Ministry of Agriculture oversees cultivation licensing.',
'North Macedonia Law on Psychotropic Substances 2016; MALMED regulatory guidance; Ministry of Agriculture cultivation license data; EU accession monitoring','Current as of Q2 2026','Quarterly','Country-level briefing covering medical program and export-oriented cultivation sector',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='MK' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'norway','country','NO','Prohibited; Reform Debate',
'Cannabis is prohibited in Norway under the Narcotic Drugs Act. Norway is not an EU member but participates in the European Economic Area, creating some policy alignment. A significant drug reform proposal moving toward decriminalization was debated in the Storting (Parliament) and ultimately rejected in 2021, but reform advocacy continues. There is no formal medical cannabis program, though some named-patient access exists for specific pharmaceutical products.',
'Limited named-patient access exists for specific cannabis-derived pharmaceuticals under exceptional circumstances with approval from the Norwegian Medicines Agency. No systematic medical cannabis program exists.',
'Norwegian physicians may apply for named-patient authorization for specific cannabis-derived pharmaceuticals in exceptional cases. The process is administratively demanding.',
'No licensed cannabis market exists. Norway''s welfare-state model and harm-reduction public health approach create ongoing policy tension between enforcement and treatment.',
'Drug policy reform remains debated in Norway. The failed 2021 decriminalization vote may be revisited in future Storting sessions. Medical cannabis framework development is possible over 2025–2028 as European norms evolve.',
'Norwegian Police Directorate handles drug enforcement. Norwegian Medicines Agency (Statens legemiddelverk) oversees pharmaceutical regulation.',
'Norway Narcotic Drugs Act; Statens legemiddelverk named-patient authorization data; Storting drug reform debates; EMCDDA Norway report','Current as of Q2 2026','Annual','Country-level briefing noting prohibition with ongoing reform debate',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='NO' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'poland','country','PL','Medical Legal',
'Poland legalized medical cannabis in November 2017 through an amendment to the Act on Counteracting Drug Addiction. The program permits the prescription of cannabis flower, extract, and oil for medical purposes. Poland''s large population (approximately 38 million) makes it one of Europe''s most significant potential medical cannabis markets. Patient access has grown considerably since the program launched.',
'Polish patients access medical cannabis through licensed pharmacies (apteki) with a physician prescription (recepta). Products include cannabis flower (suszone kwiatostany) and oil preparations. Both imported products and domestically produced items are available. Out-of-pocket costs apply as NFZ (national health insurance) reimbursement is limited to specific indications.',
'Polish physicians (lekarze) may prescribe medical cannabis for a wide range of conditions without formal specialty restrictions. The Polish Chamber of Physicians has issued guidance on evidence-based prescribing. General practitioners can prescribe; specialist involvement is common for complex conditions.',
'Poland has developed a substantial medical cannabis market. Domestic cultivation and production licenses have been issued to multiple operators. International cannabis companies including Canadian and Dutch LPs have established Polish market presence. Patient numbers are estimated in the hundreds of thousands.',
'Poland''s medical cannabis market is one of Europe''s fastest-growing given population scale. Further domestic production capacity expansion is expected. Adult-use legalization is discussed but not imminent under current political dynamics.',
'Główny Inspektorat Farmaceutyczny (GIF/Chief Pharmaceutical Inspectorate) regulates medical cannabis products. Ministry of Health sets clinical guidelines.',
'Polish Act on Counteracting Drug Addiction 2017 amendment; GIF regulatory guidance and licensed product database; Ministry of Health clinical guidelines; EMCDDA Poland report','Current as of Q2 2026; verified against GIF official guidance','Quarterly','Country-level briefing covering substantial medical program and large patient population',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='PL' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'portugal','country','PT','Decriminalized; Medical Legal; Export Licensed',
'Portugal''s 2001 drug decriminalization reform (Law 30/2000) remains one of the world''s most significant drug policy innovations — all personal use drugs are decriminalized, with users referred to Dissuasion Commissions rather than criminal courts. Medical cannabis was legalized in 2018 (Decree-Law 8/2019) with a full licensing framework for cultivation, processing, and export. Portugal has become a significant European medical cannabis production and export hub.',
'Patients access medical cannabis through licensed pharmacies with physician prescription. Both Portuguese-produced and imported products are available. INFARMED maintains an approved product list. Social security reimbursement is under development for specific conditions. Patient numbers have grown substantially since 2019.',
'Portuguese physicians (médicos) may prescribe authorized medical cannabis products for conditions including multiple sclerosis, chronic pain, and nausea. General practitioners can prescribe; specialist endorsement is common for complex conditions. The Ordem dos Médicos has issued prescribing guidance.',
'Portugal has become a major European medical cannabis production hub. Multiple licensed operators cultivate and process cannabis in Portugal, with significant export to Germany, UK, and other European markets. Portuguese production benefits from climate, agricultural expertise, and relatively streamlined licensing compared to some competitors.',
'Portugal''s medical cannabis export sector is expected to continue growing as European demand increases. Regulatory refinements supporting larger-scale production and export are anticipated. The country''s decriminalization framework is well-established and not under political threat.',
'INFARMED (Autoridade Nacional do Medicamento e Produtos de Saúde) regulates medical cannabis products and licensing. ASAE (Autoridade de Segurança Alimentar e Económica) handles CBD food supplement oversight.',
'Portugal Decree-Law 8/2019; INFARMED regulatory guidance and licensed product database; Law 30/2000 decriminalization framework; EMCDDA Portugal report','Current as of Q2 2026; verified against INFARMED official guidance','Quarterly','Full country-level briefing covering decriminalization legacy, medical program, and export hub development',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='PT' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'romania','country','RO','Prohibited; Limited CBD Tolerance',
'Cannabis is prohibited in Romania under Law 143/2000 on Preventing and Combating Illicit Drug Trafficking and Use. Romania has one of the stricter enforcement postures among EU member states. There is no medical cannabis program. CBD products exist in commercial channels but face regulatory uncertainty. EU membership creates some harmonization pressure.',
'No formal patient access to medical cannabis exists. Cannabis-based pharmaceuticals are not accessible through Romanian healthcare channels.',
'Romanian physicians cannot prescribe cannabis under the existing legal framework.',
'No licensed cannabis market exists. CBD products are commercially available but operate in uncertain legal status. Romania''s agricultural sector has limited hemp cultivation.',
'Romania''s EU membership may eventually drive medical cannabis framework development as harmonization occurs. No imminent legislative action is expected under current governance.',
'Romanian Police handles drug enforcement. National Medicines Agency (ANMDM) oversees pharmaceutical regulation.',
'Romania Law 143/2000; ANMDM pharmaceutical registry; EMCDDA Romania report','Current as of Q2 2026','Annual','Country-level briefing noting strict prohibition in EU context',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='RO' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'serbia','country','RS','Medical Legal; Export Development',
'Serbia legalized medical cannabis in 2019 through amendments to the Law on Psychoactive Controlled Substances. The program permits licensed cultivation, processing, and prescription of medical cannabis products. Serbia has actively developed an export-oriented cannabis production sector. Its position outside the EU provides some regulatory flexibility while its EU accession candidacy creates harmonization incentives.',
'Patients access medical cannabis through licensed pharmacies with physician prescription. Both domestically produced and imported products are available. Limited health insurance coverage exists. Patient registration is required for some product categories.',
'Serbian physicians may prescribe medical cannabis for qualifying conditions including multiple sclerosis, chronic pain, and epilepsy. Specialist recommendation is typically required for complex conditions.',
'Serbia has developed a licensed medical cannabis cultivation and processing industry with export orientation. Several licensed operators produce for European markets. The country''s competitive production costs and agricultural infrastructure make it an attractive production location.',
'Serbia''s medical cannabis export sector is expected to grow. EU accession aspirations will drive further regulatory harmonization. The country positions itself competitively with North Macedonia and other Western Balkan producers.',
'Agency for Medicines and Medical Devices of Serbia (ALIMS) regulates medical cannabis. Ministry of Agriculture oversees cultivation licensing.',
'Serbia Law on Psychoactive Controlled Substances 2019 amendment; ALIMS regulatory guidance; Ministry of Agriculture cultivation data; EU accession monitoring','Current as of Q2 2026','Quarterly','Country-level briefing covering medical program and export-oriented production sector',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='RS' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'slovakia','country','SK','Prohibited; CBD Gray Area',
'Cannabis is prohibited in Slovakia under the Act on Combating Drug Addiction. Slovakia has one of Central Europe''s stricter drug enforcement postures, with no decriminalization framework for personal use. There is no medical cannabis program. CBD products are commercially available but exist in legal uncertainty. Slovakia has not aligned with neighboring Czech Republic''s more progressive approach.',
'No legal patient access to medical cannabis exists. Cannabis-based pharmaceuticals are not available through official Slovak healthcare channels.',
'Slovak physicians cannot prescribe cannabis under the existing legal framework.',
'No licensed cannabis market exists. The CBD sector operates under regulatory uncertainty. Slovakia''s neighboring Czech Republic''s more progressive framework creates cross-border market dynamics.',
'EU membership may eventually drive medical cannabis harmonization. No imminent legislative action is expected under current governance.',
'Slovak Police handles drug enforcement. State Institute for Drug Control (ŠÚKL) oversees pharmaceutical regulation.',
'Slovakia Act on Combating Drug Addiction; ŠÚKL pharmaceutical registry; EMCDDA Slovakia report','Current as of Q2 2026','Annual','Country-level briefing noting strict prohibition in EU context',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='SK' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'slovenia','country','SI','Medical Legal; Decriminalized',
'Slovenia has a medical cannabis framework established under pharmaceutical regulations permitting named-patient access to cannabis-based medicines. Personal possession of small amounts is decriminalized (administrative fine). Slovenia''s healthcare system has integrated medical cannabis prescribing within standard pharmaceutical dispensing channels. CBD products with low THC are commercially available.',
'Patients access medical cannabis through licensed pharmacies with physician prescription. Named-patient authorization may be required for certain preparations. Both imported and pharmacy-compounded preparations are available. Limited social insurance reimbursement exists for specific indications.',
'Slovenian physicians may prescribe medical cannabis for qualifying conditions including chronic pain, multiple sclerosis, and cancer-related symptoms. General practitioners can prescribe standard approved preparations.',
'Slovenia has a small, functional medical cannabis market. Products are primarily imported with some pharmacy magistral preparations. The market serves a growing patient base benefiting from increasingly common prescribing.',
'Slovenia may develop more structured medical cannabis licensing as EU harmonization progresses. The decriminalization framework is well-established and the medical program continues to grow.',
'Javna agencija Republike Slovenije za zdravila in medicinske pripomočke (JAZMP) regulates medical cannabis products. Ministry of Health sets clinical guidelines.',
'JAZMP pharmaceutical registry; Slovenian decriminalization framework; Ministry of Health clinical guidelines; EMCDDA Slovenia report','Current as of Q2 2026','Annual','Country-level briefing covering medical access and decriminalization',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='SI' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'sweden','country','SE','Prohibited; Strict Enforcement; Epidiolex Available',
'Sweden maintains strict cannabis prohibition under the Narcotic Drugs Punishments Act. Sweden''s drug policy is among the most enforcement-focused in the EU, with even personal possession subject to criminal prosecution. Sweden has not implemented decriminalization. Epidiolex (CBD for epilepsy) has received Swedish Medical Products Agency approval for specific epilepsy indications. The political debate over cannabis policy has been intense, with law enforcement and public health perspectives dominating.',
'No general medical cannabis access exists. Epidiolex (cannabidiol) is approved by Läkemedelsverket for treatment of seizures associated with Lennox-Gastaut syndrome and Dravet syndrome, available through specialist prescription. No broader cannabis medicine access pathway exists.',
'Swedish physicians may prescribe Epidiolex for approved epilepsy indications through specialist (neurologist/epileptologist) prescription. No other cannabis-based medicines are accessible through standard Swedish prescribing channels.',
'The Swedish medical cannabis market is extremely limited, restricted to Epidiolex for specific epilepsy conditions. No broader licensed cannabis market exists. Sweden''s strict enforcement framework effectively limits any informal commercial activity.',
'Sweden''s drug policy trajectory remains enforcement-focused. Medical expansion beyond Epidiolex is possible if EU harmonization creates pressure, but the political environment resists liberalization. A change in governing coalition could shift the trajectory.',
'Läkemedelsverket (Swedish Medical Products Agency/LMV) regulates pharmaceutical products. National Police Authority handles drug enforcement.',
'Sweden Narcotic Drugs Punishments Act; Läkemedelsverket pharmaceutical registry; Epidiolex approval data; EMCDDA Sweden report','Current as of Q2 2026; verified against Läkemedelsverket official guidance','Annual','Country-level briefing noting strict prohibition with limited Epidiolex pharmaceutical access',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='SE' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'switzerland','country','CH','Adult-Use Pilot Programs; Medical Legal; CBD Legal',
'Switzerland has developed one of Europe''s most progressive cannabis frameworks. CBD cannabis with THC below 1% (Switzerland uses a 1% threshold vs. the EU''s 0.2%) has been legally sold since 2016. Medical cannabis became accessible through licensed pharmacies with physician prescription in 2022 following regulatory reform. From 2023, Switzerland launched regulated adult-use pilot programs in several cities (Basel, Bern, Geneva, Zurich) under the Federal Act on Research into the Regulated Cannabis Market (Experimentiergesetz), allowing up to 21,000 adult participants to access cannabis through cannabis social clubs, pharmacies, and specialized shops.',
'Patients access medical cannabis through licensed pharmacies with physician prescription. CBD products are widely available commercially. Adults participating in pilot programs can access cannabis through designated distribution points. The pilot programs are research-linked and require participant registration.',
'Swiss physicians (Ärzte/médecins) may prescribe medical cannabis for a wide range of conditions without specialist restriction. Prescription requires standard physician documentation. CBD products are accessible without prescription given their legal consumer goods status.',
'Switzerland has a vibrant CBD cannabis market (one of the world''s largest per capita). The medical cannabis market is growing rapidly following 2022 regulatory reform. The adult-use pilot programs provide a unique regulated access model being studied globally. Multiple Swiss companies operate in cultivation, processing, and retail.',
'Switzerland''s pilot program results will inform potential full adult-use legalization. Voter initiatives for full legalization are expected. The pilot program framework is expected to expand to additional cities. Switzerland''s innovation in regulated access serves as a European reference model.',
'Swissmedic regulates pharmaceutical-grade medical cannabis. BAZG (Federal Office for Customs and Border Security) handles CBD cannabis import/export. FOPH (Federal Office of Public Health) oversees pilot program authorization.',
'Swiss Federal Act on Narcotics; 2022 medical cannabis regulatory reform; Federal Act on Research into Regulated Cannabis Market (Experimentiergesetz); Swissmedic guidance; FOPH pilot program reports','Current as of Q2 2026; verified against Swissmedic and FOPH guidance','Quarterly','Full country-level briefing covering CBD market, medical program, and adult-use pilot programs',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CH' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'turkey','country','TR','Medical Legal (Industrial Hemp Focus); No Adult-Use',
'Turkey legalized medical cannabis cultivation through regulatory amendments in 2016 and expanded the framework through subsequent legislation. Turkey has historically been a significant producer of opium for pharmaceutical purposes (under INCB oversight) and has applied similar state-supervised approaches to cannabis. Industrial hemp cultivation is licensed in multiple provinces. Medical cannabis products including Sativex are available through prescription in the Turkish healthcare system.',
'Patients access approved cannabis-based medicines (including Sativex) through licensed pharmacies with physician prescription. Products must be registered with TITCK. Patient access is limited by product availability and cost.',
'Turkish physicians registered with the Turkish Medical Association may prescribe approved cannabis-based medicines for qualifying conditions including multiple sclerosis spasticity. Specialist (neurologist) prescription is expected for most indications.',
'Turkey has a significant licensed hemp cultivation sector with state oversight through TAPDK. Medical cannabis product access is limited to TITCK-approved products. Turkey''s pharmaceutical manufacturing infrastructure creates potential for domestic medical cannabis product development.',
'Turkey''s medical cannabis framework may expand as TITCK approves additional products. Industrial hemp policy is expected to continue developing. Turkey''s geographic position between European and Middle Eastern markets creates unique commercial opportunities.',
'Türkiye İlaç ve Tıbbi Cihaz Kurumu (TITCK/Turkish Medicines and Medical Devices Agency) regulates cannabis medicines. TAPDK (Tobacco and Alcohol Market Regulatory Authority) oversees hemp cultivation licensing.',
'TITCK pharmaceutical registry; TAPDK hemp cultivation license data; Turkish Medical Association prescribing guidelines; Turkey hemp agriculture statistics','Current as of Q2 2026; verified against TITCK official guidance','Quarterly','Country-level briefing covering medical program and industrial hemp sector',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='TR' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'ukraine','country','UA','Prohibited; Wartime Context; Medical Reform Pending',
'Cannabis is prohibited in Ukraine under the Law on Narcotic Drugs, Psychotropic Substances, Precursors and Combating Their Illicit Trafficking. Ukraine''s ongoing war with Russia (since February 2022) has created a significant policy discussion around medical cannabis access for war veterans and civilian trauma patients. Medical cannabis legalization legislation has been advanced through the Verkhovna Rada as a wartime healthcare priority, reflecting growing international evidence of cannabis''s utility for PTSD and pain management.',
'No formal patient access to medical cannabis exists under current law. The pending medical cannabis legislation, if enacted, would create a physician-prescription pathway primarily focused on trauma and PTSD indications. Access during the conflict period remains under the current prohibition framework.',
'Ukrainian physicians cannot currently prescribe cannabis. If the pending legislation passes, physician prescribing authority for trauma, PTSD, and chronic pain indications is proposed.',
'No licensed cannabis market exists. Post-war reconstruction may create significant demand for pain management and mental health treatments if medical cannabis access is established. Ukraine''s agricultural capacity would allow rapid domestic production development.',
'Ukraine''s medical cannabis legislation has been actively debated and has achieved parliamentary support in multiple readings. Full legalization for medical purposes, particularly for war veterans, is anticipated in 2026. Rapid implementation following legislation is expected given wartime healthcare urgency.',
'Ministry of Health of Ukraine oversees pharmaceutical regulation. Medical cannabis reform is advancing through the Verkhovna Rada Health Committee.',
'Ukraine Law on Narcotic Drugs; Verkhovna Rada medical cannabis bill status; Ministry of Health policy documents; WHO Ukraine health system reports','Current as of Q2 2026; monitoring wartime legislation progress','Quarterly','Country-level briefing covering wartime medical cannabis legalization progress and veteran access priority',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='UA' AND jurisdiction_type='country');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'san-marino','country','SM','Prohibited',
'Cannabis is prohibited in San Marino. As a microstate surrounded by Italy, San Marino''s legal framework is influenced by Italian policy. There is no medical cannabis program. Cannabis light products available in Italy have created some cross-border market dynamics, but San Marino has not established any independent cannabis regulatory framework.',
'No legal patient access exists. Cannabis-based medicines are unavailable through official Sammarinese healthcare channels.',
'San Marino physicians cannot prescribe cannabis under the existing legal framework.',
'No licensed cannabis market exists in this microstate. Italian cannabis light products may informally influence consumer patterns given geographic integration.',
'No independent reform is anticipated. San Marino''s policy is strongly influenced by Italian precedent.',
'Guardia di Rocca and Corpo della Gendarmeria handle law enforcement including drug enforcement. Secretary of State for Health oversees pharmaceutical regulation.',
'San Marino drug control legislation; Italian policy alignment monitoring; microstate regulatory context','Current as of Q2 2026','Annual','Country-level briefing noting prohibition in Italian-adjacent microstate context',DATE '2026-06-21','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='SM' AND jurisdiction_type='country');
