-- Sources for jurisdiction_playbooks batch 22 (part A of B, see batch22b for
-- playbook content + market metrics). Split across two files due to payload size.

INSERT INTO public.source_registry (source_name, source_url, country, iso, region, tier, adapter, crawl_cadence, source_type, notes)
VALUES
  ('International Bar Association — Regulatory evolution of medicinal cannabis and new hemp framework in Peru', 'https://www.ibanet.org/medicinal-cannabis-regulations-peru', 'Peru', 'PE', 'Americas', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'Law No. 32195 (Dec 2024) industrial hemp framework for cosmetics/food/textiles/construction, 27 registered cannabis-derived products (4 medicines, 23 natural products), regional leadership framing'),
  ('CMS Expert Guides — Cannabis law and legislation in Peru', 'https://cms.law/en/int/expert-guides/cms-expert-guide-to-a-legal-roadmap-to-cannabis/peru', 'Peru', 'PE', 'Americas', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'State-exclusive growing/import/commercialization by default, Supreme Decree 004-2023-SA license category breakdown, criminal penalties 8-15 years unlicensed cultivation'),
  ('Herb.co — How to Buy Weed in Peru: Lima, Cusco and South America''s Shifting Cannabis Laws', 'https://herb.co/city-guides/buy-weed-peru', 'Peru', 'PE', 'Americas', 2, 'html_snapshot', 'quarterly', 'news', 'RENPUC patient registry process, foreign medical card non-recognition, Article 299 Penal Code 8g decriminalization threshold explained'),
  ('Harris Sliwoski Canna Law Blog — Peru: New Medical Cannabis Regs', 'https://harris-sliwoski.com/cannalawblog/peru-new-medical-cannabis-regs/', 'Peru', 'PE', 'Americas', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'Droguerias/pharmaceutical laboratory licensing route, psychoactive/non-psychoactive 1% THC classification, DIGEMID import certificate requirement'),
  ('SKNIS (St. Kitts-Nevis Information Service) — AG Wilkin Explains Why Cannabis Cannot Be Fully Legalized Amid Global Banking Risks', 'https://sknis.gov.kn/2026/03/31/attorney-general-wilkin-explains-why-cannabis-cannot-be-fully-legalized-amid-global-banking-risks/', 'Saint Kitts and Nevis', 'KN', 'Americas', 1, 'html_snapshot', 'monthly', 'government_release', 'Official March 31 2026 National Assembly statement: correspondent banking relationship risk explicitly cited as reason full legalization is not feasible'),
  ('CannaCarib — Cannabis in St. Kitts and Nevis: Laws and Tourist Guide', 'https://www.cannacarib.net/saint-kitts-and-nevis/', 'Saint Kitts and Nevis', 'KN', 'Americas', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'Medicinal Cannabis Authority launched April 2025, permit/licence application forms available April 2026, no walk-in dispensaries exist'),
  ('Cannabis Business Plans — St. Kitts and Nevis Cannabis Market', 'https://cannabusinessplans.com/st-kitts-and-nevis-cannabis-market/', 'Saint Kitts and Nevis', 'KN', 'Americas', 2, 'html_snapshot', 'quarterly', 'legal_analysis', 'Cannabis Board formed 2021, Nov 2023 authority transferred Prime Minister to Minister of Agriculture, 2024 subcommittee structure for licensing rollout'),
  ('Leafwell — Is Marijuana Legal in Saint Kitts and Nevis?', 'https://leafwell.com/blog/is-marijuana-legal-in-saint-kitts-and-nevis', 'Saint Kitts and Nevis', 'KN', 'Americas', 2, 'html_snapshot', 'quarterly', 'legal_analysis', 'Full regulatory timeline 2019 High Court ruling through 2023 Rastafari Rights Recognition Act and Freedom of Conscience Act'),
  ('Cannabis Clarity SKN — Public Education Campaign', 'https://cannabisclarityskn.com/', 'Saint Kitts and Nevis', 'KN', 'Americas', 1, 'html_snapshot', 'quarterly', 'government_release', 'Official government education portal: 56g/15g resin thresholds, 5-plant cultivation limit, EC$100 annual Rastafari registration fee waived pre-Dec 2026'),
  ('Herb.co — How to Buy Weed in Panama: Canal Zone, Bocas del Toro and the Central American Gray Area', 'https://herb.co/city-guides/buy-weed-panama', 'Panama', 'PA', 'Americas', 1, 'html_snapshot', 'quarterly', 'news', 'Full regulatory timeline Law 242 through Jan 2026 first pharmacy opening, Decree 6 (Apr 2025) multi-agency licensing rewrite, 2-year domestic cultivation transition period'),
  ('MMJDaily — Panama begins implementation of medical cannabis program after four-year delay', 'https://www.mmjdaily.com/article/9784434/panama-begins-implementation-of-medical-cannabis-program-after-four-year-delay/', 'Panama', 'PA', 'Americas', 1, 'html_snapshot', 'quarterly', 'news', 'April 2026: elimination of mandatory prescriber courses, removal of closed qualifying-conditions list, first Central American country to grant formal medicinal cannabis permits'),
  ('Wikipedia — Cannabis in Panama', 'https://en.wikipedia.org/wiki/Cannabis_in_Panama', 'Panama', 'PA', 'Americas', 2, 'html_snapshot', 'quarterly', 'reference', 'First cannabis-exclusive pharmacy opened 22 Jan 2026, 7 commercialization licenses issued, MINSA/MIDA joint cultivation oversight'),
  ('Lexology — Updates on the regulation of medical cannabis in Panama', 'https://www.lexology.com/library/detail.aspx?g=d3c2571f-ad60-45da-a53d-ef3d455f3c62', 'Panama', 'PA', 'Americas', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'Resolution 212 of 2025 sanitary registration exemption requirements for THC and CBD products'),
  ('Cannabisregulations.ai — Is Weed Legal in Panama? 2026 Medical Cannabis Law Guide', 'https://www.cannabisregulations.ai/country-legality/panama-marijuana', 'Panama', 'PA', 'Americas', 2, 'html_snapshot', 'quarterly', 'legal_analysis', 'Seven license categories under Law 242, five-year licence term, Panamanian-majority ownership requirement for cultivation, no domestic finished product at scale as of 2025'),
  ('Jamaica Observer — New cannabis rules remove barriers for small farmers, says CLA head', 'https://www.jamaicaobserver.com/2026/04/18/new-cannabis-rules-remove-barriers-small-farmers-says-cla-head/', 'Jamaica', 'JM', 'Americas', 1, 'html_snapshot', 'monthly', 'news', 'April 2026 CLA CEO Farrah Blake direct quotes: standardized 3-year licence tenure, employee ID cards, special community permit with no application fee'),
  ('Jamaica Gleaner — Clarendon ganja growers urged to tap into new licensing arrangements', 'https://www.jamaica-gleaner.com/article/news/20260706/clarendon-ganja-growers-urged-tap-new-licensing-arrangements', 'Jamaica', 'JM', 'Americas', 2, 'html_snapshot', 'monthly', 'news', 'March 2026 Minister Aubyn Hill statement on finalizing licensing regulation amendments, community cultivation model up to 10 acres, banking access still unresolved'),
  ('Cannabis Licensing Authority of Jamaica — About the Authority', 'https://cla.gov.jm/page/about-authority', 'Jamaica', 'JM', 'Americas', 1, 'html_snapshot', 'quarterly', 'government_release', 'Official CLA mandate under Dangerous Drug Amendment Act 2015, ISO 9001:2015 QMS, indigenous strain/cultivar IP strategy, religious use excluded from CLA jurisdiction (Ministry of Justice)'),
  ('LegalClarity — Is Marijuana Legal in Jamaica? Decriminalization Facts', 'https://legalclarity.org/what-are-the-current-marijuana-laws-in-jamaica/', 'Jamaica', 'JM', 'Americas', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'Licensing fee schedule: commercial cultivation US$2-3k/year, herb house/retail US$2,500/year, application fees US$300 individual/US$500 company'),
  ('CannaCarib — How Tourists Legally Buy Weed at Jamaica''s Herb Houses (2026 Permit Guide)', 'https://www.cannacarib.net/jamaica/', 'Jamaica', 'JM', 'Americas', 2, 'html_snapshot', 'quarterly', 'news', 'Therapeutic Cannabis Permit for Visitors process, named licensed herb house chains, 2oz/56g decriminalization threshold, 5-plant home cultivation limit')
ON CONFLICT DO NOTHING;
