
insert into public.listings
  (id, category, title, description, product_type, region, price_range, seller_type,
   high_level_specs, status, public_visibility, is_featured, price_amount, price_currency,
   location_country, condition, brand, model, quantity, unit, slug, marketplace_section,
   sold_by_harbourview, sku, stock_qty, lead_time_days, moq, compliance_flags, target_countries,
   created_at, updated_at)
values
(gen_random_uuid(),'consumables','Rockwool Propagation Cubes (Case)','Rockwool propagation cubes for clones and seedlings.','grow_media','north_america','negotiable','distributor','{}','approved',true,false,0.09,'CAD','CA','new','Harbourview Supply','HV-ROCKW-1',1500,'each','rockwool-propagation-cubes-case','consumables',true,'HVP-CUL-ROC',300000,10,1500,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Coco Coir Grow Media (Compressed Bale, 50L Expanded)','Compressed coco coir bale, expands to approx. 50L grow media.','grow_media','north_america','negotiable','distributor','{"expanded_volume":"50L"}','approved',true,false,18.00,'CAD','CA','new','Harbourview Supply','HV-COCO-50',300,'bale','coco-coir-grow-media-50l-bale','consumables',true,'HVP-CUL-COC',2000,14,20,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Cannabis Nutrient Line — Grow Base A/B (20L Jug)','Vegetative-stage base nutrient concentrate, 20L jug.','nutrients','north_america','negotiable','distributor','{"stage":"grow","size":"20L"}','approved',true,false,145.00,'CAD','CA','new','Harbourview Supply','HV-NUT-GROW20',100,'jug','cannabis-nutrient-grow-base-20l','consumables',true,'HVP-CUL-NUTG',400,14,4,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Cannabis Nutrient Line — Bloom Base A/B (20L Jug)','Flowering-stage base nutrient concentrate, 20L jug.','nutrients','north_america','negotiable','distributor','{"stage":"bloom","size":"20L"}','approved',true,false,155.00,'CAD','CA','new','Harbourview Supply','HV-NUT-BLM20',100,'jug','cannabis-nutrient-bloom-base-20l','consumables',true,'HVP-CUL-NUTB',400,14,4,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Trellis Netting (100ft Roll)','Support netting for canopy training, 100ft roll.','trellis','north_america','negotiable','distributor','{"length":"100ft"}','approved',true,false,22.00,'CAD','CA','new','Harbourview Supply','HV-TRELLIS-100',200,'roll','trellis-netting-100ft-roll','consumables',true,'HVP-CUL-TRL',1200,10,10,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Cloning Gel (1L Bottle)','Rooting hormone gel for clone propagation, 1L bottle.','cloning_supply','north_america','negotiable','distributor','{"size":"1L"}','approved',true,false,28.00,'CAD','CA','new','Harbourview Supply','HV-CLONEGEL-1',100,'bottle','cloning-gel-1l-bottle','consumables',true,'HVP-CUL-GEL',600,10,6,'{}','{CA}',now(),now()),
(gen_random_uuid(),'cultivation_equipment','Humidity Dome + Tray Propagation Kit','Propagation tray and humidity dome kit for clones/seedlings.','propagation_kit','north_america','negotiable','distributor','{}','approved',true,false,14.00,'CAD','CA','new','Harbourview Supply','HV-DOME-1',200,'kit','humidity-dome-tray-propagation-kit','equipment',true,'HVP-CUL-DOM',800,10,10,'{}','{CA}',now(),now()),
(gen_random_uuid(),'cultivation_equipment','Commercial LED Grow Light Bar — 640W Full-Spectrum','Commercial-grade full-spectrum LED grow light bar for flowering rooms.','grow_light','north_america','negotiable','distributor','{"wattage":"640W","spectrum":"full"}','approved',true,true,850.00,'CAD','CA','new','Harbourview Supply','HV-LED-640',40,'unit','led-grow-light-bar-640w','equipment',true,'HVP-CUL-LED',40,21,1,'{}','{CA}',now(),now()),
(gen_random_uuid(),'cultivation_equipment','Drip Irrigation Kit (Expandable, Per Zone)','Expandable drip irrigation kit configurable per canopy zone.','irrigation','north_america','negotiable','distributor','{}','approved',true,false,320.00,'CAD','CA','new','Harbourview Supply','HV-DRIP-1',30,'kit','drip-irrigation-kit-expandable','equipment',true,'HVP-CUL-DRP',30,21,1,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Tamper-Evident Sample Collection Bags (Bulk)','Tamper-evident bags for COA/lab sample collection and chain of custody.','lab_supply','north_america','negotiable','distributor','{}','approved',true,false,0.15,'CAD','CA','new','Harbourview Supply','HV-SAMPBAG-1',1000,'each','tamper-evident-sample-collection-bags','labs_testing',true,'HVP-LAB-SMP',20000,10,500,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Lab Pipette Tips (Bulk Case, 1000ct)','Disposable pipette tips for lab sampling and testing workflows.','lab_supply','north_america','negotiable','distributor','{"count":1000}','approved',true,false,0.02,'CAD','CA','new','Harbourview Supply','HV-PIPTIP-1',1000,'each','lab-pipette-tips-bulk-1000ct','labs_testing',true,'HVP-LAB-PIP',500000,10,1000,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','pH / EC Calibration Solution Kit','Calibration solution kit for pH and EC meters.','lab_supply','north_america','negotiable','distributor','{}','approved',true,false,45.00,'CAD','CA','new','Harbourview Supply','HV-CALKIT-1',150,'kit','ph-ec-calibration-solution-kit','labs_testing',true,'HVP-LAB-CAL',600,10,5,'{}','{CA}',now(),now()),
(gen_random_uuid(),'labs_testing','Bench-Top Moisture Analyzer (Halogen, Compliance-Grade)','Halogen moisture analyzer for compliance-grade moisture content testing.','lab_equipment','north_america','negotiable','distributor','{"method":"halogen"}','approved',true,false,2100.00,'CAD','CA','new','Harbourview Supply','HV-MOIST-1',6,'unit','moisture-analyzer-halogen-bench-top','labs_testing',true,'HVP-EQP-MOI',6,21,1,'{}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Dispensary Exit Bag (Opaque, Blank)','Child-resistant opaque exit bag for point-of-sale dispensing.','exit_bag','north_america','negotiable','distributor','{"cr":true}','approved',true,false,0.16,'CAD','CA','new','Harbourview Supply','HV-EXITBAG-1',1000,'each','cr-dispensary-exit-bag-opaque','packaging',true,'HVP-RTL-EXB',15000,10,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','In-Store Compliance Signage Kit (Mandatory Health Warnings)','Retail signage kit covering mandatory in-store cannabis health warning postings.','retail_supply','north_america','negotiable','distributor','{}','approved',true,false,35.00,'CAD','CA','new','Harbourview Supply','HV-SIGNKIT-1',80,'kit','in-store-compliance-signage-kit','consumables',true,'HVP-RTL-SIG',300,14,5,'{}','{CA}',now(),now());
