-- SUPERSEDED. This file's version prefix (20260729010000) does not match
-- its actual applied ledger version. The real applied migration is
-- 20260730103137_fix_missing_public_read_grants.sql (identical GRANT
-- statements for listings, local_authorities, local_intel_coverage,
-- local_open_questions, local_operating_notes, local_subdivisions_intel,
-- operator_countries, cc_watchlist_notifications, subscriptions,
-- workspace_members).
-- Retired per docs/control/PENDING_PRODUCTION_MIGRATION_DECISIONS_2026-08-02.md.
-- No-op placeholder -- do not add statements here.
