-- Reconciled historical seed marker.
--
-- Production records version 20260621220514 as a comment-only reconciliation;
-- it does not execute the incompatible draft seed contained in the former
-- repository file. The draft referenced profile columns and cultivar-category
-- enum values that are not part of the canonical Cultivar Passport Network
-- schema, and the corresponding synthetic profile/passport rows are not present
-- in production.
--
-- Evidence-bearing cultivar and rights-holder records must be introduced only by
-- a separately reviewed, provenance-backed seed or controlled application flow.
