
-- Canada: 10 provinces + 3 territories (all Adult-Use Legal since Oct 17, 2018)

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'ontario','state','CA','CA-ON','Adult-Use Legal; Medical Legal',
'Ontario is Canada''s largest and most commercially developed provincial cannabis market. The province launched adult-use sales on April 1, 2019 under a licensed private retail model overseen by the Alcohol and Gaming Commission of Ontario (AGCO). From fewer than 25 stores at launch, Ontario grew to over 1,800 licensed retail locations by 2026, making it one of the world''s largest regulated cannabis retail ecosystems. Minimum purchase age is 19. Adults may possess up to 30 grams in public and cultivate up to four plants at home under federal rules.',
'Medical patients access cannabis through federally licensed producers (LPs) under Health Canada''s medical access framework, with products delivered by mail or dispensed at LP storefronts. Adult-use consumers purchase from AGCO-licensed private retail stores or the Ontario Cannabis Store (OCS) online. OCS operates as the province''s wholesale distributor to all retail stores and also sells directly to consumers online.',
'Healthcare practitioners registered with Health Canada''s medical program may authorize cannabis for patients without a specific list of qualifying conditions — clinical judgement determines appropriateness. The College of Physicians and Surgeons of Ontario (CPSO) provides guidance encouraging evidence-based authorization.',
'Ontario generates the largest provincial cannabis revenue in Canada, with annual retail sales exceeding CAD 2.5 billion as of 2025. Over 1,800 licensed private retail stores compete in a highly competitive market. OCS handles provincial wholesale distribution. The sector employs tens of thousands and generates significant provincial tax revenue.',
'Ontario''s mature retail market is entering a consolidation phase as smaller operators face competition from multi-location retailers and established chains. OCS continues refining its wholesale distribution and direct online sales model. Regulatory streamlining to reduce licensing friction is ongoing.',
'Alcohol and Gaming Commission of Ontario (AGCO) licenses and regulates retail stores and cannabis employees. Ontario Cannabis Store (OCS) operates provincial wholesale and direct online sales. Health Canada administers federal medical access.',
'AGCO retail licensing database; OCS wholesale data; Health Canada medical program statistics; Ontario Ministry of Finance cannabis tax reports','Current as of Q2 2026; verified against AGCO official data','Quarterly','Full provincial briefing covering private retail model, OCS wholesale, and market scale',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CA' AND state_iso2='CA-ON');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'british-columbia','state','CA','CA-BC','Adult-Use Legal; Medical Legal',
'British Columbia launched adult-use cannabis retail in November 2018 with a hybrid model combining government-operated BC Cannabis Stores and licensed private retail. BC has developed a sophisticated market that reflects its long pre-legalization culture of cannabis use and craft production. Minimum age is 19. Adults may possess up to 30 grams publicly and cultivate up to four plants at home. BC has positioned itself as a craft cannabis production hub with a strong independent producer community.',
'Medical patients access federally licensed producer products via mail or LP storefronts. Adult-use consumers purchase from BC Cannabis Stores (government-operated) or licensed private retailers throughout the province. Online delivery is available through government and select private channels.',
'Healthcare practitioners may authorize medical cannabis for patients under Health Canada''s framework without a prescribed qualifying conditions list. The BC College of Physicians and Surgeons provides guidance on evidence-based practice.',
'BC''s cannabis market is among Canada''s most developed, with hundreds of licensed private retailers complementing government stores. The province has a strong craft producer sector with many small-batch producers licensed under Health Canada''s micro-license category. Annual retail sales are estimated at CAD 800 million and growing.',
'BC is developing enhanced craft cannabis branding and appellations to support its independent producer community. Retail consolidation is ongoing. Regulatory frameworks supporting cannabis tourism and on-site consumption are under development.',
'BC Liquor Distribution Branch (LCRB) licenses private retail stores. BC Cannabis Stores (government retail) operated by BCLDB. Health Canada administers federal medical and producer licensing.',
'LCRB retail licensing data; BCLDB annual reports; Health Canada producer registry; BC cannabis revenue statistics','Current as of Q2 2026; verified against LCRB official data','Quarterly','Full provincial briefing covering hybrid retail model and craft production sector',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CA' AND state_iso2='CA-BC');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'alberta','state','CA','CA-AB','Adult-Use Legal; Medical Legal',
'Alberta was the first Canadian province to fully commit to a private retail model for adult-use cannabis, launching sales on October 17, 2018 — Canada''s federal legalization day. With a minimum purchase age of 18 (the lowest in Canada), Alberta operates a fully private retail system with no government stores, making it the most market-liberal province. The Alberta Gaming, Liquor and Cannabis Commission (AGLC) serves as the provincial wholesaler and licensing authority. Alberta has over 800 licensed retail stores as of 2026.',
'Medical patients access federally licensed producer products through Health Canada''s program. Adult-use consumers purchase from AGLC-licensed private retail stores, which are the only point-of-sale channel. AGLC operates myALBERTA cannabis as the provincial wholesale platform supplying all licensed retailers.',
'Healthcare practitioners authorize medical cannabis under Health Canada''s framework. The College of Physicians and Surgeons of Alberta (CPSA) provides guidance encouraging evidence-based authorization.',
'Alberta''s fully private retail market has produced one of Canada''s most competitive cannabis retail environments. Over 800 stores compete for market share. Annual retail sales exceed CAD 800 million. Alberta is home to several major cannabis retail chains that have expanded nationally and internationally.',
'Alberta''s private retail model is mature and financially stable. AGLC continues refining the wholesale distribution and licensing system. Further market consolidation among retailers is expected. Cannabis tourism interest has grown given the 18+ minimum age.',
'Alberta Gaming, Liquor and Cannabis Commission (AGLC) licenses retailers and operates provincial wholesale. Health Canada administers federal medical and producer licensing.',
'AGLC retail licensing data and wholesale statistics; Health Canada producer registry; Alberta cannabis revenue data; AGLC annual reports','Current as of Q2 2026; verified against AGLC official data','Quarterly','Full provincial briefing covering fully private retail model and market-liberal framework',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CA' AND state_iso2='CA-AB');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'quebec','state','CA','CA-QC','Adult-Use Legal (Restrictive); Medical Legal',
'Quebec operates Canada''s most restrictive provincial adult-use framework. The Société québécoise du cannabis (SQDC) holds a government monopoly on retail sales. Quebec set the minimum purchase age at 21 (raised from 18 in 2020), the highest in Canada. Home cultivation is prohibited by provincial law (though contested against the federal Cannabis Act). Cannabis consumption in public spaces is subject to more restrictions than most provinces. Despite restrictions, the SQDC has grown to over 100 locations province-wide and generates significant revenue.',
'Medical patients access federally licensed producer products through Health Canada''s program independent of the SQDC. Adult-use consumers must purchase exclusively from SQDC stores or the SQDC website with provincial delivery. No private retail is permitted.',
'Healthcare practitioners authorize medical cannabis under Health Canada''s federal framework. Quebec''s medical system follows federal guidelines, with the Collège des médecins du Québec providing provincial guidance.',
'SQDC operates a government monopoly with over 100 retail locations as of 2026 and growing online sales. Annual revenues exceed CAD 500 million. Despite restrictive policies, Quebec''s large population makes it a significant market. The prohibition on home cultivation and minimum age of 21 differentiates Quebec from all other provinces.',
'SQDC expansion continues. Home cultivation prohibition has faced constitutional challenge — federal Cannabis Act permits cultivation, creating legal tension that may eventually require Quebec to align with federal law. The 21+ minimum age may face legal challenge under Charter equality arguments.',
'Société québécoise du cannabis (SQDC) operates retail monopoly. Régie des alcools, des courses et des jeux (RACJ) oversees compliance. Health Canada administers federal medical framework.',
'SQDC annual reports and store data; RACJ regulatory guidance; Health Canada federal program statistics; home cultivation constitutional litigation monitoring','Current as of Q2 2026; verified against SQDC and RACJ official data','Quarterly','Provincial briefing covering government retail monopoly, age-21 restriction, and home cultivation prohibition',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CA' AND state_iso2='CA-QC');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'manitoba','state','CA','CA-MB','Adult-Use Legal; Medical Legal',
'Manitoba adopted a private retail model for adult-use cannabis with the Manitoba Liquor and Lotteries (MLL) Commission overseeing licensing, wholesale distribution, and compliance. Sales launched October 17, 2018. Minimum age is 19. Adults may cultivate up to four plants at home. Manitoba''s market is smaller than Ontario, BC, and Alberta but has developed a stable retail network.',
'Medical patients use Health Canada''s federal program. Adult-use consumers purchase from MLL-licensed private retail stores. MLL operates the provincial wholesale platform and enforces retail regulations.',
'Healthcare practitioners authorize medical cannabis under Health Canada''s federal framework. The College of Physicians and Surgeons of Manitoba provides provincial guidance.',
'Manitoba has a growing number of licensed private cannabis retailers serving the province. Market size is proportional to population (approximately 1.4 million). Annual retail sales are estimated in the range of CAD 120–150 million. Competition between retailers is established.',
'Manitoba''s market is mature at provincial scale. Regulatory refinements continue as the retail sector stabilizes. On-site consumption licensing may be considered in future regulatory reviews.',
'Manitoba Liquor and Lotteries (MLL) licenses retailers and operates wholesale distribution. Health Canada administers federal programs.',
'MLL retail licensing data; Health Canada producer registry; Manitoba cannabis revenue statistics','Current as of Q2 2026','Quarterly','Provincial briefing covering private retail model',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CA' AND state_iso2='CA-MB');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'saskatchewan','state','CA','CA-SK','Adult-Use Legal; Medical Legal',
'Saskatchewan was one of the first provinces to operationalize a fully private retail model when adult-use cannabis launched October 17, 2018. The Saskatchewan Liquor and Gaming Authority (SLGA) oversees licensing and acts as provincial wholesaler. Minimum age is 19. Adults may cultivate up to four plants at home. Saskatchewan has developed an efficient private retail network serving both urban centres and rural communities.',
'Medical patients use Health Canada''s federal program. Adult-use consumers purchase from SLGA-licensed private retail stores. SLGA manages provincial wholesale distribution to all licensed retailers.',
'Healthcare practitioners authorize medical cannabis under Health Canada''s federal framework. The College of Physicians and Surgeons of Saskatchewan provides provincial guidance.',
'Saskatchewan''s market serves a population of approximately 1.2 million. The fully private retail model has resulted in competitive pricing and distribution coverage across urban and rural areas. Annual retail sales are estimated in the range of CAD 100–130 million.',
'Saskatchewan''s established private retail market continues to operate steadily. Further rural retail coverage development is ongoing. Regulatory efficiency improvements are expected.',
'Saskatchewan Liquor and Gaming Authority (SLGA) licenses retailers and operates wholesale. Health Canada administers federal programs.',
'SLGA retail licensing data; Health Canada producer registry; Saskatchewan cannabis revenue statistics','Current as of Q2 2026','Quarterly','Provincial briefing covering private retail model',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CA' AND state_iso2='CA-SK');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'nova-scotia','state','CA','CA-NS','Adult-Use Legal; Medical Legal',
'Nova Scotia launched adult-use cannabis retail through the Nova Scotia Liquor Corporation (NSLC), which initially operated as a government monopoly before introducing limited private retail licensing. Minimum age is 19. Adults may cultivate up to four plants at home. The NSLC operates brick-and-mortar stores and an online delivery platform.',
'Medical patients use Health Canada''s federal program. Adult-use consumers purchase from NSLC-operated stores or licensed private retailers. NSLC manages provincial wholesale.',
'Healthcare practitioners authorize under Health Canada''s federal framework. Nova Scotia College of Physicians and Surgeons provides provincial guidance.',
'Nova Scotia''s market serves a population of approximately 1 million. NSLC has expanded its cannabis retail footprint while introducing private retail competition. Annual retail sales are estimated at CAD 80–100 million.',
'Nova Scotia continues to mature its hybrid government/private retail model. Further private retail licensing is expected as the market develops.',
'Nova Scotia Liquor Corporation (NSLC) operates retail and wholesale. Health Canada administers federal programs.',
'NSLC annual reports; Health Canada producer registry; Nova Scotia cannabis revenue data','Current as of Q2 2026','Quarterly','Provincial briefing covering hybrid government/private retail model',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CA' AND state_iso2='CA-NS');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'new-brunswick','state','CA','CA-NB','Adult-Use Legal; Medical Legal',
'New Brunswick launched adult-use cannabis through Cannabis NB, a Crown corporation. Cannabis NB operates a network of government retail stores and an online platform. Minimum age is 19. Adults may cultivate up to four plants at home. Cannabis NB serves as both retailer and provincial wholesaler.',
'Medical patients use Health Canada''s federal program. Adult-use consumers purchase from Cannabis NB stores or the Cannabis NB website. No private retail operates alongside the government monopoly.',
'Healthcare practitioners authorize under Health Canada''s federal framework. The College of Physicians and Surgeons of New Brunswick provides provincial guidance.',
'New Brunswick''s market serves a bilingual (French/English) population of approximately 800,000. Cannabis NB operates a stable retail network. Annual retail sales are estimated at CAD 60–80 million.',
'Cannabis NB continues operating as the provincial retail monopoly. Private retail licensing has been discussed but not yet implemented. Further store expansions are planned.',
'Cannabis NB (Crown Corporation) operates retail and wholesale. Health Canada administers federal programs.',
'Cannabis NB annual reports; Health Canada producer registry; New Brunswick cannabis revenue data','Current as of Q2 2026','Quarterly','Provincial briefing covering government retail monopoly',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CA' AND state_iso2='CA-NB');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'newfoundland-and-labrador','state','CA','CA-NL','Adult-Use Legal; Medical Legal',
'Newfoundland and Labrador launched adult-use cannabis retail on October 17, 2018 with a private retail model under the Newfoundland and Labrador Liquor Corporation (NLC) oversight. The province was one of the first to authorize private retail stores. Minimum age is 19. Adults may cultivate up to four plants at home.',
'Medical patients use Health Canada''s federal program. Adult-use consumers purchase from NLC-licensed private retail stores or the NLC online store. NLC operates provincial wholesale.',
'Healthcare practitioners authorize under Health Canada''s federal framework. The Newfoundland and Labrador Medical Association provides provincial guidance.',
'Newfoundland and Labrador''s market serves a population of approximately 540,000 including remote coastal communities. Private retail stores operate in major urban areas. Annual retail sales are estimated at CAD 45–60 million.',
'The province continues developing its private retail network with increasing coverage in smaller communities. NLC''s oversight framework continues to mature.',
'Newfoundland and Labrador Liquor Corporation (NLC) licenses retailers and operates wholesale. Health Canada administers federal programs.',
'NLC licensing data; Health Canada producer registry; NL cannabis revenue statistics','Current as of Q2 2026','Quarterly','Provincial briefing covering private retail model',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CA' AND state_iso2='CA-NL');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'prince-edward-island','state','CA','CA-PE','Adult-Use Legal; Medical Legal',
'Prince Edward Island operates adult-use cannabis through the PEI Cannabis Management Corporation, a government entity managing retail and wholesale. The province launched cannabis retail on October 17, 2018. Minimum age is 19. Adults may cultivate up to four plants at home. PEI is the smallest province by population, with a seasonal tourism industry that creates unique market dynamics.',
'Medical patients use Health Canada''s federal program. Adult-use consumers purchase from PEI Cannabis Management Corporation stores or online. The corporation manages provincial retail and wholesale.',
'Healthcare practitioners authorize under Health Canada''s federal framework. The PEI College of Physicians provides provincial guidance.',
'PEI''s market serves a year-round population of approximately 170,000 with significant seasonal tourist influx. Annual retail sales are estimated at CAD 20–30 million with seasonal variation. The small market size supports a limited number of government retail locations.',
'PEI''s government retail model is stable. Tourism seasonality continues to influence sales patterns. Regulatory alignment with federal updates is ongoing.',
'PEI Cannabis Management Corporation operates retail and wholesale. Health Canada administers federal programs.',
'PEI Cannabis Management Corporation reports; Health Canada producer registry; PEI cannabis revenue data','Current as of Q2 2026','Annual','Provincial briefing covering government retail model in smallest Canadian province',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CA' AND state_iso2='CA-PE');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'yukon','state','CA','CA-YT','Adult-Use Legal; Medical Legal',
'Yukon launched adult-use cannabis sales through Cannabis Yukon, a government-operated retailer and wholesaler, on October 17, 2018. The territory also introduced private retail licensing to supplement government stores. Minimum age is 19. Adults may cultivate up to four plants at home. Cannabis Yukon serves a small, geographically dispersed population including First Nations communities, some of which have implemented their own access policies.',
'Medical patients use Health Canada''s federal program. Adult-use consumers purchase from Cannabis Yukon government stores or licensed private retailers. Cannabis Yukon operates provincial wholesale.',
'Healthcare practitioners authorize under Health Canada''s federal framework. The Yukon Medical Association provides guidance relevant to northern healthcare delivery contexts.',
'Yukon''s market serves a population of approximately 45,000, primarily in Whitehorse. Annual retail sales are estimated at CAD 15–25 million. First Nations self-governance arrangements create some variation in access across communities.',
'Cannabis Yukon continues operating government retail alongside a small number of private licenses. First Nations engagement on cannabis governance continues.',
'Cannabis Yukon (Yukon Liquor Corporation) operates retail and wholesale. Health Canada administers federal programs. First Nations self-governance arrangements are respected.',
'Cannabis Yukon annual reports; Health Canada producer registry; First Nations cannabis governance documentation','Current as of Q2 2026','Annual','Territorial briefing covering government retail with private supplement in northern context',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CA' AND state_iso2='CA-YT');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'northwest-territories','state','CA','CA-NT','Adult-Use Legal; Medical Legal',
'Northwest Territories launched adult-use cannabis retail through the NT Liquor and Cannabis Commission (NTLCC), operating government stores in Yellowknife and other communities. Private retail was also licensed to serve the geographically dispersed territory. Minimum age is 19. Adults may cultivate up to four plants at home. Community-level consultation with Indigenous governments has shaped access policies in some communities.',
'Medical patients use Health Canada''s federal program. Adult-use consumers purchase from NTLCC-operated stores or licensed private retailers. NTLCC manages territorial wholesale.',
'Healthcare practitioners authorize under Health Canada''s federal framework, with northern and remote healthcare delivery context acknowledged.',
'The NWT market serves a population of approximately 45,000 spread across a vast territory. Annual retail sales are modest given the small population. Remote community access is a significant logistical challenge.',
'NTLCC continues developing retail coverage for remote communities. Indigenous governance engagement on cannabis access is ongoing.',
'NT Liquor and Cannabis Commission (NTLCC) operates retail and wholesale. Health Canada administers federal programs. Indigenous self-governance arrangements are respected.',
'NTLCC annual reports; Health Canada producer registry; NWT Indigenous governance cannabis documentation','Current as of Q2 2026','Annual','Territorial briefing covering government retail in northern remote context',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CA' AND state_iso2='CA-NT');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'nunavut','state','CA','CA-NU','Adult-Use Legal; Medical Legal',
'Nunavut launched adult-use cannabis retail through Cannabis Nunavut and licensed private retailers in Iqaluit and other communities. Minimum age is 19. Adults may cultivate up to four plants at home, though growing conditions in the Arctic make home cultivation impractical for most residents. Community-level access policies vary across Nunavut''s 25 communities, some of which have implemented local restrictions under Inuit self-governance frameworks.',
'Medical patients use Health Canada''s federal program. Adult-use consumers purchase from Cannabis Nunavut or licensed private retailers. Logistics in remote communities create access challenges.',
'Healthcare practitioners authorize under Health Canada''s federal framework, with Nunavut''s unique northern and Inuit healthcare context acknowledged.',
'Nunavut''s market serves a population of approximately 40,000 in 25 communities across an enormous territory. Annual retail sales are small given population and logistical constraints. Supply chain management is a significant operational challenge.',
'Cannabis Nunavut and licensed retailers continue developing access in Iqaluit and other communities. Inuit self-governance engagement on cannabis access policies is ongoing and will shape the long-term framework.',
'Nunavut Liquor and Cannabis Commission (NULC) oversees retail and wholesale. Health Canada administers federal programs. Inuit self-governance bodies have authority over community access policies.',
'NULC annual reports; Health Canada producer registry; Nunavut Inuit governance cannabis consultation documentation','Current as of Q2 2026','Annual','Territorial briefing covering adult-use retail in Arctic Inuit context with community variation',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='CA' AND state_iso2='CA-NU');
