create table if not exists education_tracks (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  title text not null,
  created_at timestamptz not null default now()
);
create table if not exists education_modules (id uuid primary key default gen_random_uuid(), track_id uuid references education_tracks(id), slug text unique not null, title text not null, publication_state text not null default 'draft', created_at timestamptz not null default now());
create table if not exists education_articles (id uuid primary key default gen_random_uuid(), module_id uuid references education_modules(id), slug text unique not null, title text not null, summary text not null, sensitivity text not null, publication_state text not null default 'draft', source_basis text not null default 'draft', publication_confidence text not null default 'low', last_reviewed_at timestamptz, next_review_due_at timestamptz, created_at timestamptz not null default now());
create table if not exists education_article_sections (id uuid primary key default gen_random_uuid(), article_id uuid references education_articles(id) on delete cascade, section_type text not null, content text not null, position int not null default 0);
create table if not exists education_sources (id uuid primary key default gen_random_uuid(), article_id uuid references education_articles(id) on delete cascade, label text not null, raw_source_url text, reviewer_notes text, contradictory_source_flag boolean not null default false, created_at timestamptz not null default now());
create table if not exists education_reviews (id uuid primary key default gen_random_uuid(), article_id uuid references education_articles(id) on delete cascade, state text not null, reviewer_category text not null, unresolved_issues text[] not null default '{}', confidence_disputes text[] not null default '{}', reviewed_at timestamptz, created_at timestamptz not null default now());
create table if not exists education_glossary_terms (id uuid primary key default gen_random_uuid(), slug text unique not null, term text not null, definition text not null, sensitivity text not null default 'standard', created_at timestamptz not null default now());
create table if not exists education_country_briefs (id uuid primary key default gen_random_uuid(), country_code text unique not null, country_name text not null, readiness_label text not null, summary text not null, source_basis text not null default 'pending-verification', created_at timestamptz not null default now());
create table if not exists education_requests (id uuid primary key default gen_random_uuid(), email text not null, organization text, requested_topic text not null, country text, sensitivity_detected text not null default 'standard', workflow_status text not null default 'new', assigned_reviewer text, created_at timestamptz not null default now());
create table if not exists education_audit_events (id uuid primary key default gen_random_uuid(), actor text not null, event_type text not null, entity_type text not null, entity_id text not null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists education_content_relationships (id uuid primary key default gen_random_uuid(), from_entity_type text not null, from_entity_id text not null, to_entity_type text not null, to_entity_id text not null, relationship_type text not null, created_at timestamptz not null default now());
create table if not exists education_publication_history (id uuid primary key default gen_random_uuid(), article_id uuid references education_articles(id) on delete cascade, from_state text not null, to_state text not null, transitioned_by text not null, transitioned_at timestamptz not null default now());
