-- Canonical product format taxonomy
insert into public.product_formats (slug, name, category, description, sort_order) values
('dried_flower','Dried flower','inhalable','Herbal cannabis flower (whole or milled), typically for vaporization; smoking often separately restricted',10),
('vape_products','Vape cartridges & liquids','inhalable','Pre-filled cartridges, pods and liquids for inhalation devices',20),
('extracts_concentrates','Extracts & concentrates','extract','Resin, rosin, full-spectrum extract, distillate; dispensed directly or as compounding input',30),
('isolates','Cannabinoid isolates','extract','Purified single cannabinoids (e.g. CBD >=98%, dronabinol) as API or finished form',40),
('oral_oil','Oral oils & solutions','oral','Oils, drops, tinctures and oral solutions',50),
('capsules','Capsules & softgels','oral','Hard and soft gel capsules',60),
('tablets','Tablets & pills','oral','Compressed tablets and pills',70),
('oromucosal_spray','Oromucosal & sublingual sprays','oromucosal','Sprays absorbed via oral mucosa (e.g. nabiximols)',80),
('lozenges','Lozenges, pastilles & wafers','oromucosal','Dissolvable oromucosal solids',90),
('edibles','Edibles','edible','Cannabis-infused food products',100),
('beverages','Beverages','edible','Cannabis-infused drinks',110),
('topicals','Topicals & dermal','topical','Creams, balms, cosmetics for external use',120),
('transdermal_patches','Transdermal patches','topical','Systemic delivery via skin patch',130),
('suppositories','Suppositories','rectal','Rectal/vaginal dosage forms',140),
('bulk_api_raw','Bulk raw material / API','raw_material','GMP flower, extract or cannabinoid API as manufacturing/compounding input or trade good',150),
('magistral_preparations','Magistral (compounded) preparations','compounded','Pharmacy-compounded preparations made to individual prescription',160),
('seeds_plants','Seeds & live plants','plant','Seeds, clones and plants for cultivation (home-grow or licensed)',170);

-- Regulatory pathways (priority markets, verified against Jun-Jul 2026 sources where noted)
insert into public.regulatory_pathways
  (country_id, iso_alpha2, slug, name, pathway_type, legal_basis, regulator, status, effective_date, summary, prescription_notes, verification, last_verified_at)
select c.id, v.iso2, v.slug, v.name, v.ptype::public.reg_pathway_type, v.legal, v.reg, v.status, v.eff::date, v.summary, v.rx, v.ver::public.reg_verification_status,
       case when v.ver='verified' then now() else null end
from (values
-- BRAZIL
('BR','br-rdc-1015','Sanitary Authorization for Cannabis Products (RDC 1.015/2026, ex-RDC 327/2019)','domestic_authorization','RDC 1.015/2026 (revokes RDC 327/2019; in force 4 May 2026); RDC 1.004/2025 (IFAV quality); RDC 1.013/2026 (<=0.3% THC medical cultivation)','Anvisa','active','2026-05-04','New framework approved by Dicol 28 Jan 2026 replacing RDC 327. Pharmacy-dispensed Cannabis products under sanitary authorization (~49 products / 24 companies under prior regime). Domestic cultivation <=0.3% THC now permitted for manufacture per STJ IAC 16 compliance.','Prescription-only; THC >0.2% products historically limited to palliative/terminal care (verify carryover in final 1.015 text)','verified',null),
('BR','br-rdc-660','Individual patient import of cannabis-derived products (RDC 660/2022)','special_access_import','RDC 660/2022','Anvisa','active',null,'Import by natural persons for own use on prescription; >660k import authorizations 2015-2025. Still in force but formally flagged by Anvisa (Jan 2026 vote) as a regulatory distortion needing urgent revision - expect a separate normative act.','Prescription from legally qualified professional; industrialized products only','verified',null),
('BR','br-registered-med','Registered cannabis medicine','registered_medicine','Medicine registration (RDC 200/2017 route)','Anvisa','active',null,'One registered cannabis medicine (Mevatyl / nabiximols).',null,'needs_review',null),
('BR','br-rdc-1014-sandbox','Regulatory sandbox: patient associations (RDC 1.014/2026)','pilot_program','RDC 1.014/2026','Anvisa','pilot','2026-02-03','Sandbox assessing cultivation, plant-based API production, and distribution of cannabis preparations by non-profit patient associations to members.',null,'verified',null),
-- UNITED KINGDOM
('GB','gb-cbpm-specials','Unlicensed cannabis-based products for medicinal use (CBPMs / specials)','medical_access_program','Misuse of Drugs Regulations 2001 as amended 2018 (Sch 2); MHRA specials regime','MHRA / Home Office','active','2018-11-01','Specialist-initiated prescriptions for unlicensed CBPMs. NHS prescribing rare (<20k); ~100k patients via private clinics. Imported and domestic products.','Specialist doctor initiation required; private clinic market dominant','verified',null),
('GB','gb-licensed','Licensed cannabis-based medicines','registered_medicine','MHRA marketing authorisations','MHRA','active',null,'Sativex (nabiximols), Epidyolex (CBD), Nabilone.',null,'verified',null),
('GB','gb-cbd-consumer','Consumer CBD (novel foods regime)','low_thc_consumer','FSA novel foods authorisation process; controlled-drug THC limits','FSA / Home Office','active',null,'Ingestible CBD requires novel-food authorisation track; cosmetics separate. CBD flower not permitted.','No prescription; controlled cannabinoid content must be below de-minimis thresholds','needs_review',null),
-- GERMANY
('DE','de-medcang','Medical cannabis (MedCanG prescription medicine)','medical_access_program','MedCanG (Apr 2024, cannabis removed from narcotics list); amendment bill restricting telemedicine/mail-order passed Cabinet 8 Oct 2025, Bundestag first reading 18 Dec 2025, final vote expected H1 2026','BfArM','active','2024-04-01','Standard e-prescription medicine; flower, extracts, dronabinol and finished meds. ~338k+ patients; imports ~81t H1 2025. Pending amendment: in-person first prescription, telemed follow-ups only within 4 quarters of in-person contact, mail-order dispensing ban (pharmacy courier delivery exempt).','Any physician; GKV reimbursement subject to G-BA rules; telemedicine restrictions pending - verify enactment','verified',null),
('DE','de-registered','Registered cannabis medicines','registered_medicine','AMG marketing authorisations','BfArM','active',null,'Sativex, Epidyolex, Canemes (nabilone).',null,'verified',null),
('DE','de-cang-pillar1','CanG Pillar 1: possession, home cultivation, cultivation associations','adult_use_noncommercial','CanG (KCanG), in force 1 Apr 2024','BLE / state authorities','active','2024-04-01','25g public / 50g home possession, 3 plants, non-profit cultivation associations (max 500 members). No commercial retail; Pillar 2 pilot framework still pending.',null,'verified',null),
-- AUSTRALIA
('AU','au-sas-ap','Unapproved medicinal cannabis via SAS-B / Authorised Prescriber (TGO 93 Categories 1-5)','medical_access_program','Therapeutic Goods Act 1989 s19; TGO 93 quality standard','TGA / ODC','active','2016-11-01','~1,000+ unapproved products supplied under SAS/AP; market >AUD 1bn (2025); 41 licensed cultivators, 41t produced 2024. 2025 federal review concluded; medicinal cannabis is a top TGA compliance priority for 2026-27 with tightening expected on advertising, telehealth prescribing and product quality.','Any registered doctor/NP via SAS-B or AP; Cat 2-5 are Schedule 8','verified',null),
('AU','au-registered','Registered cannabis medicines (ARTG)','registered_medicine','ARTG registration','TGA','active',null,'Sativex (nabiximols), Epidyolex (CBD).',null,'verified',null),
('AU','au-cbd-s3','Low-dose CBD Schedule 3 (pharmacist-only) pathway','low_thc_consumer','Poisons Standard Sch 3 entry (<=150mg/day CBD)','TGA','announced',null,'Down-scheduled pathway exists but no CBD product has achieved ARTG registration for S3 supply yet - no lawful OTC product on market.',null,'needs_review',null),
-- POLAND
('PL','pl-raw-material','Pharmaceutical raw material (flower, extracts, resin) for magistral preparation','magistral_compounding','Act on Counteracting Drug Addiction amendment, in force 1 Nov 2017; URPL raw-material marketing authorisations','URPL / GIF','active','2017-11-01','~50 authorized raw-material products (approx. 40 flower, 12 extract, Dec 2025). 5,447 kg flower dispensed 2025; 105k+ patients. Import-reliant; no active domestic cultivation. Telemedicine prescribing restricted since Nov 2024 (in-person consultation), market recovered above pre-ban peak by Dec 2025.','Any licensed physician; narcotic (pink) prescription; pharmacy compounds/doses','verified',null),
('PL','pl-registered','Registered cannabis medicines','registered_medicine','URPL marketing authorisation','URPL','active',null,'Sativex registered.',null,'verified',null),
('PL','pl-cbd-consumer','Consumer CBD / low-THC hemp (<=0.3% THC)','low_thc_consumer','Hemp threshold <=0.3% THC; EU Novel Food regime enforced by GIS','GIS','active',null,'CBD supplements/cosmetics sold subject to Novel Food enforcement (RASFF actions 2025); CBD hemp flower sold as collectible in grey zone.',null,'verified',null),
-- SOUTH AFRICA
('ZA','za-sahpra-s21','SAHPRA Section 21 unregistered medicine access','special_access_import','Medicines and Related Substances Act s21; THC Sch 6, CBD Sch 4 (GN 586/2020)','SAHPRA','active',null,'Named-patient authorization for unregistered cannabis medicines; 6-month approvals with outcome reporting.','Doctor applies per patient; renewal every 6 months','verified',null),
('ZA','za-cbd-exemption','Low-dose CBD complementary/OTC exemption','low_thc_consumer','GN 586 GG 43347 (May 2020): <=600mg CBD/pack & <=20mg/day, low-risk claims; or processed products <=0.0075% CBD & <=0.001% THC','SAHPRA / DoH','active','2020-05-22','Low-dose CBD sold OTC. Mar 2025 blanket ban on cannabis/hemp in foodstuffs was withdrawn after presidential intervention; foodstuff status remains contested pending new rules.',null,'verified',null),
('ZA','za-private-use','Private cultivation and use (CfPPA / Prince judgment)','adult_use_noncommercial','Constitutional Court Prince (2018); Cannabis for Private Purposes Act 7 of 2024 (signed 29 May 2024)','n/a','active','2024-05-29','Private adult possession/cultivation lawful; no commercial retail. Grow/social clubs remain a contested grey zone (Haze Club). Commercialisation Policy targeted for Cabinet Apr 2026; consolidated Cannabis Bill expected mid-2027.',null,'verified',null),
('ZA','za-sahpra-22c','Licensed medicinal cultivation, manufacture and export (s22C)','export_oriented','Medicines Act s22C(1)(b); GMP; hemp redefined <=2% THC under Plant Improvement Act (1 Dec 2025)','SAHPRA / DALRRD','active',null,'~120 export licences, 83+ cultivation licences; EU-facing export market. Hemp (<=2% THC) commercially cultivable under DALRRD permits since Dec 2025.',null,'verified',null),
-- CANADA
('CA','ca-adult-use','Adult-use commercial (Cannabis Act)','adult_use_commercial','Cannabis Act SC 2018 c.16 + Cannabis Regulations','Health Canada / provinces','active','2018-10-17','Full commercial framework across all consumer classes: dried/fresh, extracts, edibles, beverages, topicals, seeds/plants.',null,'needs_review',null),
('CA','ca-medical','Medical access (Cannabis Regulations Part 14)','medical_access_program','Cannabis Regulations Part 14','Health Canada','active','2018-10-17','Registered medical clients via licensed sellers; personal/designated production permitted.','Medical document from HCP','needs_review',null),
('CA','ca-registered','Registered cannabis medicine','registered_medicine','Food and Drugs Act DIN','Health Canada','active',null,'Sativex marketed.',null,'needs_review',null),
-- UNITED STATES
('US','us-state-programs','State-regulated medical and adult-use programs','adult_use_commercial','State statutes; federally Schedule I CSA (rescheduling to Sch III proposed, proceeding stalled)','State agencies / DEA-FDA (federal)','active',null,'Subnational patchwork: ~40 medical / ~24 adult-use states. Formats vary by state (flower, vapes, edibles, beverages, topicals, concentrates). Federal illegality persists; treat state matrix as separate subnational layer.',null,'needs_review',null),
('US','us-hemp','Hemp-derived cannabinoids (2018 Farm Bill, <=0.3% delta-9 THC)','low_thc_consumer','Agriculture Improvement Act 2018','USDA / FDA / states','active','2018-12-20','Hemp products federally lawful by delta-9 threshold; FDA has not authorized CBD in food/supplements; intoxicating hemp derivatives contested state-by-state.',null,'needs_review',null),
('US','us-fda-registered','FDA-approved cannabinoid medicines','registered_medicine','FDA NDA approvals','FDA','active',null,'Epidiolex (CBD), Marinol/Syndros (dronabinol), Cesamet (nabilone).',null,'needs_review',null),
-- NETHERLANDS
('NL','nl-omc','Office for Medicinal Cannabis pharmacy program','medical_access_program','Opium Act exemption; OMC monopoly supply (Bedrocan)','OMC (VWS)','active','2003-09-01','Standardized flower varieties and pharmacy-prepared oils dispensed on prescription; also major exporter of pharmaceutical flower.',null,'needs_review',null),
('NL','nl-experiment','Coffeeshop tolerance + closed-chain supply experiment','pilot_program','Wietexperiment; fully regulated supply in 10 participating municipalities since Apr 2025','VWS / JenV','pilot','2025-04-07','Tolerance policy retail via coffeeshops; participating municipalities restricted to regulated-chain product.',null,'verified',null),
-- SWITZERLAND
('CH','ch-medical','Medical prescription access','medical_access_program','NarcA revision in force 1 Aug 2022 (no federal exceptional authorisation needed)','Swissmedic / FOPH','active','2022-08-01','Physician prescription; magistral preparations, standardized flower and extracts; Sativex registered.',null,'needs_review',null),
('CH','ch-pilot-trials','Adult-use scientific pilot trials','pilot_program','NarcA Art. 8a pilot provision (2021)','FOPH','pilot','2023-01-30','Regulated sales to enrolled participants in Basel, Zurich, Bern, Geneva and other cities; evidence base for national framework.',null,'verified',null),
('CH','ch-low-thc','Low-THC cannabis (<1% THC)','low_thc_consumer','Excluded from NarcA below 1% THC','FOPH','active',null,'CBD flower and products under 1% THC sold as consumer goods (tobacco-substitute rules for smokables).',null,'needs_review',null),
-- THAILAND
('TH','th-controlled-herb','Medical-only controlled herb framework (cannabis flower)','medical_access_program','Notification on Controlled Herbs under Thai Traditional Medicine Act B.E. 2542, effective 25 Jun 2025; Ministerial Reg No.2 B.E. 2569 (Apr 2026) licensing overlay','MoPH / DTAM / Thai FDA','active','2025-06-25','Recreational sale recriminalized 25 Jun 2025. Flower dispensed only against PT33 prescription (max 30 days) at licensed dispensaries with on-site practitioner (Jan 2026 rules); import of flower prohibited; mass dispensary closures through licence attrition.','PT33 prescription from licensed Thai practitioner','verified',null),
('TH','th-narcotic-extracts','High-THC extracts as Category 5 narcotics','medical_access_program','Ministerial Regulation on Category 5 Narcotics (Cannabis/Hemp Extracts) B.E. 2569, published 26 Mar 2026, effective 26 Apr 2026','Thai FDA / ONCB','active','2026-04-26','Extracts >0.2% THC remain Cat 5 narcotics; licences limited to registered medical facilities, pharmacies and herbal shops for medical/research/commercial-extract purposes.',null,'verified',null),
('TH','th-cbd-consumer','CBD consumer products (<0.2% THC)','low_thc_consumer','Product labelling rules','Thai FDA','active',null,'CBD products under 0.2% THC sold without prescription.',null,'verified',null),
-- FRANCE
('FR','fr-permanent','Permanent medical cannabis framework (post-experiment)','medical_access_program','2024 Social Security Financing Act generalisation; framework live 1 Apr 2026','ANSM','active','2026-04-01','Transition from 2021-2025 experiment to permanent framework - the largest single EU market opening of 2026. Launching WITHOUT flower; oil/extract-based formats only. Reimbursement design determines patient scale.','Hospital/specialist initiation expected; verify final prescribing decree detail','verified',null),
('FR','fr-registered','Licensed cannabinoid medicines','registered_medicine','ANSM/EMA authorisations','ANSM','active',null,'Epidyolex available; Sativex authorised 2014 but never marketed (pricing).',null,'needs_review',null),
-- SPAIN
('ES','es-rd903','Hospital magistral medical cannabis (Royal Decree 903/2025)','magistral_compounding','Real Decreto 903/2025','AEMPS','active','2025-10-01','Standardized cannabis extract magistral preparations via hospital pharmacies only; no flower dispensing. Implementation rolling through 2026.','Hospital specialist prescribing; verify condition list and rollout status','verified',null),
('ES','es-registered','Licensed cannabis medicines','registered_medicine','AEMPS authorisations','AEMPS','active',null,'Sativex, Epidyolex.',null,'needs_review',null),
('ES','es-social-clubs','Cannabis social clubs (unregulated grey zone)','adult_use_noncommercial','No national statute; association jurisprudence','n/a','active',null,'~800-1,000 clubs operating without formal legislation; private consumption decriminalised.',null,'verified',null),
-- CZECHIA
('CZ','cz-medical','Medical cannabis program','medical_access_program','Act 50/2013; SUKL/SAKL regime; e-prescription; 90% reimbursement','SUKL / SAKL','active','2013-04-01','Flower and individually prepared (magistral) preparations on e-prescription; expanding market with domestic cultivation licences.',null,'needs_review',null),
('CZ','cz-adult-use','Adult-use personal framework','adult_use_noncommercial','Law passed Jul 2025, effective 1 Jan 2026','Government of Czechia','active','2026-01-01','Adults 21+: 3 plants home cultivation, 100g at home / 25g public possession. No commercial retail (deferred); psychomodulatory low-THC track separate.',null,'verified',null),
-- Registered-medicine + magistral markets and stubs follow in next seed batch
-- ISRAEL
('IL','il-imca','Israel Medical Cannabis (IMCA) prescription reform','medical_access_program','IMCA regulations; 2024 reform shifting from licence to prescription for most indications','IMCA (MoH)','active',null,'Large domestic market; flower, oils, extracts via pharmacies; export permitted since 2020.',null,'needs_review',null),
-- PORTUGAL
('PT','pt-infarmed','Infarmed medical cannabis framework','medical_access_program','Law 33/2018; DL 8/2019','Infarmed','active','2019-02-01','Prescription access to authorized preparations (flower, oral solutions); limited domestic product list; major EU-GMP cultivation/export hub.',null,'needs_review',null),
-- ITALY
('IT','it-magistral','Magistral dispensing (FM-2 + imports)','magistral_compounding','DM 9 Nov 2015; military pharmaceutical plant (SCFM) production + imports','Ministry of Health / SCFM','active','2015-11-09','Pharmacy-compounded preparations from flower/extracts; state production plus imports.',null,'needs_review',null),
('IT','it-cannabis-light','Cannabis light (hemp inflorescences)','low_thc_consumer','Law 242/2016; Apr 2025 security decree criminalising hemp flower trade - under legal challenge','n/a','suspended','2025-04-11','Formerly large <=0.5% THC hemp-flower sector; 2025 decree bans inflorescence trade, litigation ongoing.',null,'needs_review',null),
-- DENMARK
('DK','dk-scheme','Medicinal cannabis scheme (pilot made permanent)','domestic_authorization','Pilot programme 2018-2025; made permanent from 1 Jan 2025','Danish Medicines Agency','active','2025-01-01','Admitted products (flower, oils, capsules) prescribable; Denmark also a significant EU-GMP producer/exporter.',null,'needs_review',null),
-- NEW ZEALAND
('NZ','nz-scheme','Medicinal Cannabis Scheme (verified products)','domestic_authorization','Misuse of Drugs (Medicinal Cannabis) Regulations 2019','Medsafe / MCA','active','2020-04-01','Products meeting minimum quality standard prescribable by any doctor; flower and oral formats verified.',null,'needs_review',null),
-- IRELAND
('IE','ie-mcap','Medical Cannabis Access Programme + ministerial licences','domestic_authorization','MCAP (2019); Misuse of Drugs ministerial licence route','HPRA / DoH','active','2019-06-26','Named product list (oral solutions/oils, some flower via licence route); narrow condition list.',null,'needs_review',null),
-- ARGENTINA
('AR','ar-reprocann','REPROCANN + pharmacy/magistral access','medical_access_program','Law 27.350; Decree 883/2020; REPROCANN registry','ANMAT / MoH','active','2020-11-12','Registered patients may self-cultivate or access via network cultivators; pharmacy magistral and registered products; industrial framework via ARICCAME.',null,'needs_review',null),
-- COLOMBIA
('CO','co-framework','Medical cannabis and export framework','export_oriented','Law 1787/2016; Decree 811/2021 (permits dried flower export)','Minjusticia / INVIMA','active','2016-07-06','Licensed cultivation/manufacture; magistral domestic dispensing; dried flower export permitted since 2021.',null,'needs_review',null),
-- URUGUAY
('UY','uy-adult-use','Adult-use (pharmacies, clubs, home grow)','adult_use_commercial','Law 19.172 (2013)','IRCCA','active','2014-05-06','Registered residents buy flower at pharmacies; membership clubs; home cultivation.',null,'needs_review',null),
('UY','uy-medical','Medical cannabis','medical_access_program','Law 19.172; Decree 46/015','MSP / IRCCA','active',null,'Prescription products incl. oils; export industry active.',null,'needs_review',null),
-- MEXICO
('MX','mx-medical','Medical cannabis regulations','medical_access_program','2021 sanitary regulations (COFEPRIS)','COFEPRIS','active','2021-01-12','Pharmaceutical-derivative access regulated; implementation slow. Adult-use: SCJN declared prohibition unconstitutional; statutory market not enacted.',null,'needs_review',null),
-- JAPAN
('JP','jp-pharma','Cannabis-derived pharmaceuticals pathway','registered_medicine','Revised Cannabis Control Act (Dec 2024): allows approved cannabis-derived medicines; creates use offence; THC ppm limits for CBD goods','MHLW / PMDA','active','2024-12-12','Epidiolex-type approvals now possible; strict THC residual limits govern the CBD consumer market.',null,'needs_review',null),
('JP','jp-cbd','CBD consumer products (THC ppm limits)','low_thc_consumer','Cannabis Control Act amendment ministerial ordinance THC caps','MHLW','active','2024-12-12','CBD lawful within strict residual-THC ppm caps by product type.',null,'needs_review',null),
-- UKRAINE
('UA','ua-medical','Medical cannabis framework','medical_access_program','Law 3528-IX (adopted Dec 2023, effective Aug 2024)','MoH Ukraine','active','2024-08-16','Medical use legalised (war-trauma/PTSD emphasis); registered medicines and licensed circulation; implementation building out.',null,'needs_review',null),
-- MALTA
('MT','mt-medical','Medical cannabis (Production of Cannabis for Medicinal Use Act)','medical_access_program','2018 Act; Medicines Authority control card system','Malta Medicines Authority','active','2018-04-01','Flower and preparations via pharmacies on control card; also EU-GMP production hub.',null,'needs_review',null),
('MT','mt-chra','Adult-use harm reduction associations','adult_use_noncommercial','Cannabis Reform Act 2021 (ARUC)','ARUC','active','2021-12-18','7g possession, 4 plants; non-profit CHRAs supply members; no retail.',null,'needs_review',null),
-- LUXEMBOURG
('LU','lu-medical','Medical cannabis programme','medical_access_program','2018 law; hospital/pharmacy dispensing','Ministry of Health','active','2019-02-01','Flower and extracts dispensed via pharmacies.',null,'needs_review',null),
('LU','lu-home-grow','Adult-use home cultivation','adult_use_noncommercial','2023 law','Ministry of Justice','active','2023-07-21','4 plants per household; possession at home; no commercial sales.',null,'needs_review',null),
-- GREECE
('GR','gr-medical','Medical cannabis production and availability','export_oriented','Law 4523/2018; 4801/2021','EOF / Ministry of Development','active','2018-03-01','Production/export oriented framework; domestic pharmacy availability of final products limited and evolving.',null,'needs_review',null),
-- NORTH MACEDONIA
('MK','mk-framework','Medical cannabis extracts + flower export','export_oriented','2016 law (extracts); 2023 amendments enabling flower export','MALMED','active','2016-06-01','Licensed producers; extracts domestic, flower for export; EU-GMP capacity growing.',null,'needs_review',null),
-- MOROCCO
('MA','ma-anrac','Legal cannabis for medical/industrial/export (ANRAC)','export_oriented','Law 13-21 (2021)','ANRAC','active','2021-07-14','Licensed cultivation in designated provinces; processing for medical, cosmetic, industrial and export purposes; first legal products 2024.',null,'needs_review',null)
) as v(iso2, slug, name, ptype, legal, reg, status, eff, summary, rx, ver)
join public.countries c on c.iso_alpha2 = v.iso2;