-- Global pathway orientation seeds for medical-cannabis prescribing markets.
-- Regulatory guidance only; no dosing protocols.

insert into public.clinical_evidence_records (
  slug, title, summary,
  condition_label, condition_aliases,
  intervention, intervention_class,
  evidence_type, evidence_strength, evidence_strength_method, uncertainty, conflict_status,
  jurisdictions, profession_relevance,
  primary_source_title, primary_source_publisher, primary_source_url, primary_source_id,
  verified_at, supersession_state, review_status
) values
(
  'us-fda-cannabis-products-orientation',
  'United States — FDA cannabis-derived products orientation',
  'The FDA regulates cannabis-derived drugs at the federal level. Most medical cannabis patient access is governed by state programmes, which vary widely. Confirm both FDA-approved product labeling (where applicable) and the relevant state medical programme rules.',
  null, array['FDA', 'state medical cannabis', 'Epidiolex'],
  'Cannabis-derived / cannabinoid medicines',
  'regulated-cannabinoid-drug',
  'regulatory-guidance', 'ungraded',
  'Primary regulator orientation; state law is not encoded here.',
  'State programmes differ; this record is not a 50-state formulary.',
  'none',
  array['United States'], array['doctor','nurse_practitioner','pharmacist','other'],
  'FDA Regulation of Cannabis and Cannabis-Derived Products',
  'U.S. Food and Drug Administration',
  'https://www.fda.gov/news-events/public-health-focus/fda-regulation-cannabis-and-cannabis-derived-products-including-cannabidiol-cbd',
  'fda-cannabis-orientation',
  '2026-08-16T12:30:00Z', 'current', 'published'
),
(
  'fr-ansm-medical-cannabis-orientation',
  'France — ANSM medical cannabis pathway orientation',
  'France operates a supervised medical cannabis framework under ANSM. Prescribing is typically limited to designated centres and pathways defined by national authorities. Confirm current ANSM status (experiment transition / permanent framework) before acting.',
  null, array['ANSM', 'accès précoce', 'medical cannabis France'],
  'Medical cannabis (French framework)',
  'general-cannabis',
  'regulatory-guidance', 'ungraded',
  'Competent-authority orientation only.',
  'Framework details change during transition periods.',
  'none',
  array['France'], array['doctor','pharmacist','other'],
  'ANSM — Agence nationale de sécurité du médicament',
  'ANSM',
  'https://ansm.sante.fr/',
  'fr-ansm-orientation',
  '2026-08-16T12:30:00Z', 'current', 'published'
),
(
  'nl-omc-medical-cannabis-orientation',
  'Netherlands — OMC medical cannabis pathway orientation',
  'Dutch medical cannabis is supplied through the Office for Medicinal Cannabis (OMC) framework. Physicians may prescribe; pharmacies dispense OMC products. Confirm current OMC product list and pharmacy rules.',
  null, array['OMC', 'Bedrocan', 'medicinal cannabis Netherlands'],
  'Medical cannabis (Dutch OMC framework)',
  'general-cannabis',
  'regulatory-guidance', 'ungraded',
  'Competent-authority orientation only.',
  'Reimbursement is insurer-dependent.',
  'none',
  array['Netherlands'], array['doctor','pharmacist','other'],
  'Farmatec / Office for Medicinal Cannabis',
  'Government of the Netherlands',
  'https://english.farmatec.nl/',
  'nl-omc-orientation',
  '2026-08-16T12:30:00Z', 'current', 'published'
),
(
  'il-imca-medical-cannabis-orientation',
  'Israel — IMCA medical cannabis programme orientation',
  'Israel operates a comprehensive medical cannabis programme under the Ministry of Health (IMCA). Prescribers require authorization; patients register centrally; pharmacies dispense under programme rules. Confirm current indication and product guidance.',
  null, array['IMCA', 'Yakar', 'medical cannabis Israel'],
  'Medical cannabis (Israeli programme)',
  'general-cannabis',
  'regulatory-guidance', 'ungraded',
  'Programme orientation only; not a substitute for IMCA circulars.',
  'Indication lists and product catalogues change.',
  'none',
  array['Israel'], array['doctor','pharmacist','other'],
  'Israel Medical Cannabis Agency (IMCA)',
  'Ministry of Health',
  'https://www.gov.il/en/departments/units/cannabis_unit',
  'il-imca-orientation',
  '2026-08-16T12:30:00Z', 'current', 'published'
),
(
  'br-anvisa-cannabis-orientation',
  'Brazil — ANVISA cannabis products orientation',
  'ANVISA regulates cannabis-derived products, including imported products authorized under specific resolutions. Physicians prescribe within ANVISA rules; confirm product registration or import authorization status.',
  null, array['ANVISA', 'cannabis medicinal', 'RDC'],
  'Cannabis-derived products (Brazilian framework)',
  'regulated-cannabinoid-drug',
  'regulatory-guidance', 'ungraded',
  'Regulator orientation only.',
  'Product lists and RDC requirements change.',
  'none',
  array['Brazil'], array['doctor','pharmacist','other'],
  'ANVISA',
  'Government of Brazil',
  'https://www.gov.br/anvisa/pt-br',
  'br-anvisa-orientation',
  '2026-08-16T12:30:00Z', 'current', 'published'
),
(
  'co-invima-medical-cannabis-orientation',
  'Colombia — medical cannabis pathway orientation',
  'Colombia licenses medical cannabis production and products under Ministry of Health and INVIMA frameworks. Confirm licensed product status and prescribing requirements for the specific presentation.',
  null, array['INVIMA', 'cannabis medicinal Colombia'],
  'Medical cannabis (Colombian framework)',
  'general-cannabis',
  'regulatory-guidance', 'ungraded',
  'Regulator orientation only.',
  'Licensing tiers and product rules are detailed at national level.',
  'none',
  array['Colombia'], array['doctor','pharmacist','other'],
  'INVIMA',
  'Government of Colombia',
  'https://www.invima.gov.co/',
  'co-invima-orientation',
  '2026-08-16T12:30:00Z', 'current', 'published'
),
(
  'nz-medicinal-cannabis-scheme-orientation',
  'New Zealand — Medicinal Cannabis Scheme orientation',
  'New Zealand operates a Medicinal Cannabis Scheme under the Ministry of Health. Products must meet scheme standards; prescribers should confirm verified products and current guidance.',
  null, array['Medicinal Cannabis Agency', 'Medsafe'],
  'Medicinal cannabis (NZ scheme)',
  'general-cannabis',
  'regulatory-guidance', 'ungraded',
  'Scheme orientation only.',
  'Product verification status changes as products are assessed.',
  'none',
  array['New Zealand'], array['doctor','nurse_practitioner','pharmacist','other'],
  'Medicinal Cannabis Agency',
  'Ministry of Health New Zealand',
  'https://www.health.govt.nz/our-work/regulation-health-and-disability-system/medicinal-cannabis-agency',
  'nz-mcs-orientation',
  '2026-08-16T12:30:00Z', 'current', 'published'
),
(
  'za-sahpra-cannabis-orientation',
  'South Africa — SAHPRA cannabis medicines orientation',
  'SAHPRA regulates medicines including cannabis-based products and Section 21 access pathways where applicable. Confirm current authorization status of any product before prescribing.',
  null, array['SAHPRA', 'Section 21'],
  'Cannabis-based medicines (South African framework)',
  'regulated-cannabinoid-drug',
  'regulatory-guidance', 'ungraded',
  'Regulator orientation only.',
  'Authorization pathways are product-specific.',
  'none',
  array['South Africa'], array['doctor','pharmacist','other'],
  'SAHPRA',
  'South African Health Products Regulatory Authority',
  'https://www.sahpra.org.za/',
  'za-sahpra-orientation',
  '2026-08-16T12:30:00Z', 'current', 'published'
),
(
  'th-thai-fda-medical-cannabis-orientation',
  'Thailand — medical cannabis pathway orientation',
  'Thailand regulates medical cannabis under the Ministry of Public Health and Thai FDA. Confirm licensed clinic/product requirements under current national rules.',
  null, array['Thai FDA', 'medical cannabis Thailand'],
  'Medical cannabis (Thai framework)',
  'general-cannabis',
  'regulatory-guidance', 'ungraded',
  'Regulator orientation only.',
  'National rules have evolved rapidly; verify current text.',
  'none',
  array['Thailand'], array['doctor','pharmacist','other'],
  'Thai FDA',
  'Ministry of Public Health',
  'https://www.fda.moph.go.th/Pages/Home.aspx',
  'th-fda-orientation',
  '2026-08-16T12:30:00Z', 'current', 'published'
),
(
  'it-aifa-medical-cannabis-orientation',
  'Italy — medical cannabis / magistral pathway orientation',
  'Italian medical cannabis is commonly accessed via physician prescription and magistral pharmacy preparation under Ministry of Health and AIFA frameworks. Domestic supply constraints may affect availability.',
  null, array['AIFA', 'SCFM', 'cannabis terapeutica'],
  'Medical cannabis (Italian framework)',
  'general-cannabis',
  'regulatory-guidance', 'ungraded',
  'Regulator orientation only.',
  'Regional reimbursement rules vary.',
  'none',
  array['Italy'], array['doctor','pharmacist','other'],
  'AIFA',
  'Agenzia Italiana del Farmaco',
  'https://www.aifa.gov.it/',
  'it-aifa-orientation',
  '2026-08-16T12:30:00Z', 'current', 'published'
),
(
  'pl-gif-medical-cannabis-orientation',
  'Poland — medical cannabis prescribing orientation',
  'Poland allows physicians to prescribe medical cannabis preparations dispensed via licensed pharmacies under GIF/URPL pharmaceutical rules. Confirm current product availability and documentation requirements.',
  null, array['GIF', 'URPL', 'medyczna marihuana'],
  'Medical cannabis (Polish framework)',
  'general-cannabis',
  'regulatory-guidance', 'ungraded',
  'Regulator orientation only.',
  'Reimbursement is generally not available; patients often pay out of pocket.',
  'none',
  array['Poland'], array['doctor','pharmacist','other'],
  'GIF / URPL',
  'Polish pharmaceutical authorities',
  'https://www.gif.gov.pl/',
  'pl-gif-orientation',
  '2026-08-16T12:30:00Z', 'current', 'published'
),
(
  'ch-swissmedic-medical-cannabis-orientation',
  'Switzerland — medical cannabis pathway orientation',
  'Switzerland permits medical cannabis under revised narcotics legislation with Swissmedic oversight. Confirm current prescriber, product, and pharmacy requirements.',
  null, array['Swissmedic', 'medical cannabis Switzerland'],
  'Medical cannabis (Swiss framework)',
  'general-cannabis',
  'regulatory-guidance', 'ungraded',
  'Regulator orientation only.',
  'Product authorization status must be checked case by case.',
  'none',
  array['Switzerland'], array['doctor','pharmacist','other'],
  'Swissmedic',
  'Swiss Agency for Therapeutic Products',
  'https://www.swissmedic.ch/swissmedic/en/home.html',
  'ch-swissmedic-orientation',
  '2026-08-16T12:30:00Z', 'current', 'published'
),
(
  'ar-reprocann-orientation',
  'Argentina — REPROCANN / medical cannabis orientation',
  'Argentina operates medical cannabis access pathways including REPROCANN registration under national health rules. Confirm current programme eligibility and ANMAT product requirements.',
  null, array['REPROCANN', 'ANMAT'],
  'Medical cannabis (Argentine framework)',
  'general-cannabis',
  'regulatory-guidance', 'ungraded',
  'Programme orientation only.',
  'National programme rules change; verify official sources.',
  'none',
  array['Argentina'], array['doctor','pharmacist','other'],
  'ANMAT / Ministry of Health',
  'Government of Argentina',
  'https://www.argentina.gob.ar/anmat',
  'ar-reprocann-orientation',
  '2026-08-16T12:30:00Z', 'current', 'published'
),
(
  'pt-infarmed-medical-cannabis-orientation',
  'Portugal — INFARMED medical cannabis orientation',
  'INFARMED authorizes medical cannabis products and oversees pharmacy dispensing in Portugal. Confirm authorized products and prescribing documentation.',
  null, array['INFARMED', 'canábis medicinal'],
  'Medical cannabis (Portuguese framework)',
  'general-cannabis',
  'regulatory-guidance', 'ungraded',
  'Regulator orientation only.',
  'Authorization is product-specific.',
  'none',
  array['Portugal'], array['doctor','pharmacist','other'],
  'INFARMED',
  'INFARMED',
  'https://www.infarmed.pt/',
  'pt-infarmed-orientation',
  '2026-08-16T12:30:00Z', 'current', 'published'
)
on conflict (slug) do update set
  title = excluded.title,
  summary = excluded.summary,
  condition_aliases = excluded.condition_aliases,
  uncertainty = excluded.uncertainty,
  jurisdictions = excluded.jurisdictions,
  primary_source_url = excluded.primary_source_url,
  verified_at = excluded.verified_at,
  review_status = excluded.review_status,
  updated_at = now();
