insert into public.pathway_format_rules
  (pathway_id, format_id, status, thc_limit, cbd_limit, conditions, notes, verification, last_verified_at)
select p.id, f.id, v.status::public.reg_rule_status, v.thc, v.cbd, v.cond::jsonb, v.notes, v.ver::public.reg_verification_status,
       case when v.ver='verified' then now() else null end
from (values
-- ============ BRAZIL ============
('br-rdc-1015','oral_oil','permitted','THC <=0.2% standard; higher-THC historically limited to palliative/terminal (confirm carryover in RDC 1.015 final text)',null,'{"route":"oral"}','Core dispensing format under sanitary authorization; oral route ~91% of the market','verified'),
('br-rdc-1015','capsules','permitted',null,null,'{"route":"oral"}',null,'verified'),
('br-rdc-1015','isolates','permitted',null,'CBD phytopharmaceutical API >=98% purity per RDC 24/2011 quality route','{}','CBD as IFA; plant extract as IFAV per RDC 1.004/2025','verified'),
('br-rdc-1015','bulk_api_raw','permitted','Domestic cultivation input <=0.3% THC (RDC 1.013/2026)',null,'{"import":"RDC 988/2025 procedures"}','IFA/IFAV import and, newly, domestic cultivation for manufacture per STJ IAC 16 compliance','verified'),
('br-rdc-1015','oromucosal_spray','restricted',null,null,'{"routes_prior_regime":["oral","nasal"]}','Buccal/sublingual route expansion proposed in CP 1.316/2025 - confirm inclusion in RDC 1.015 final text','needs_review'),
('br-rdc-1015','vape_products','proposed',null,null,'{}','Inhalation route proposed in 2025 public consultation; confirm final text','needs_review'),
('br-rdc-1015','topicals','proposed',null,null,'{}','Dermatological route proposed in 2025 public consultation; confirm final text','needs_review'),
('br-rdc-1015','magistral_preparations','proposed',null,'Compounding proposed only for >=98% purity CBD','{}','Compounding-pharmacy access proposed in consultation; Dicol kept manipulation restricted pending separate act','verified'),
('br-rdc-1015','dried_flower','prohibited',null,null,'{"smoking_prohibited":true}','Plant/flower in natura not a permitted dispensed product','verified'),
('br-rdc-1015','edibles','prohibited',null,null,'{}','Food formats outside the sanitary-authorization product definition','verified'),
('br-rdc-660','oral_oil','permitted',null,null,'{"route_share":"oral ~90.8% of authorized import list"}','Individual import on prescription; industrialized products only','verified'),
('br-rdc-660','capsules','permitted',null,null,'{}',null,'verified'),
('br-rdc-660','topicals','permitted',null,null,'{"route_share":"topical ~4.7%"}',null,'verified'),
('br-rdc-660','vape_products','restricted',null,null,'{"route_share":"inhalation ~1.7%"}','Small share of authorized list; heightened scrutiny expected in pending RDC 660 revision','needs_review'),
('br-rdc-660','dried_flower','prohibited',null,null,'{}','Herbal cannabis in natura not importable by individuals','verified'),
('br-rdc-660','edibles','prohibited',null,null,'{}',null,'needs_review'),
('br-registered-med','oromucosal_spray','permitted',null,null,'{}','Mevatyl (nabiximols)','needs_review'),
('br-rdc-1014-sandbox','magistral_preparations','restricted',null,null,'{"scope":"non-profit patient associations, members only"}','Association-prepared cannabis preparations within sandbox parameters','verified'),
('br-rdc-1014-sandbox','seeds_plants','restricted',null,null,'{"scope":"association cultivation under sandbox"}',null,'verified'),
-- ============ UNITED KINGDOM ============
('gb-cbpm-specials','dried_flower','permitted',null,null,'{"smoking_prohibited":true,"administration":"vaporization"}','Dominant private-market format','verified'),
('gb-cbpm-specials','oral_oil','permitted',null,null,'{}',null,'verified'),
('gb-cbpm-specials','capsules','permitted',null,null,'{}',null,'needs_review'),
('gb-cbpm-specials','vape_products','permitted',null,null,'{}','Cartridges an expanding CBPM category; regulator concern over adult-use-style branding noted 2025-26','needs_review'),
('gb-cbpm-specials','lozenges','restricted',null,null,'{}','Pastille formats via some clinics','needs_review'),
('gb-cbpm-specials','extracts_concentrates','restricted',null,null,'{}',null,'needs_review'),
('gb-cbpm-specials','edibles','prohibited',null,null,'{}','Food formats not supplied as CBPMs','needs_review'),
('gb-licensed','oromucosal_spray','permitted',null,null,'{}','Sativex (nabiximols)','verified'),
('gb-licensed','oral_oil','permitted',null,null,'{}','Epidyolex (CBD oral solution)','verified'),
('gb-licensed','capsules','permitted',null,null,'{}','Nabilone','verified'),
('gb-cbd-consumer','oral_oil','restricted','Controlled-cannabinoid content must be below de-minimis thresholds',null,'{"fsa_adi":"10 mg/day CBD provisional guidance"}','Sale contingent on FSA novel-food authorisation track','needs_review'),
('gb-cbd-consumer','edibles','restricted',null,null,'{}','Novel-food regime applies','needs_review'),
('gb-cbd-consumer','beverages','restricted',null,null,'{}','Novel-food regime applies','needs_review'),
('gb-cbd-consumer','topicals','permitted',null,null,'{}','Cosmetics route outside novel-food scope','needs_review'),
('gb-cbd-consumer','dried_flower','prohibited',null,null,'{}','CBD flower/bud sales unlawful','verified'),
-- ============ GERMANY ============
('de-medcang','dried_flower','permitted',null,null,'{"pending_amendment":"in-person first Rx; telemed follow-ups only within 4 quarters of in-person contact; mail-order dispensing ban (pharmacy courier exempt)"}','Largest format; pending MedCanG amendment targets flower prescribing channels specifically','verified'),
('de-medcang','extracts_concentrates','permitted',null,null,'{}',null,'verified'),
('de-medcang','oral_oil','permitted',null,null,'{}','Dronabinol drops and oily solutions via Rezeptur','verified'),
('de-medcang','capsules','permitted',null,null,'{}',null,'needs_review'),
('de-medcang','magistral_preparations','permitted',null,null,'{}','Rezeptur compounding standard practice','verified'),
('de-medcang','vape_products','restricted',null,null,'{}','Device vaporization standard; prefilled cartridges a limited category','needs_review'),
('de-medcang','bulk_api_raw','permitted',null,null,'{"note":"imports ~81t H1 2025; temporary import-licence pause reported late 2025"}','EU-GMP flower/extract imports dominate supply; domestic BfArM-licensed cultivation <3t','verified'),
('de-medcang','edibles','prohibited',null,null,'{}',null,'verified'),
('de-registered','oromucosal_spray','permitted',null,null,'{}','Sativex','verified'),
('de-registered','oral_oil','permitted',null,null,'{}','Epidyolex','verified'),
('de-registered','capsules','permitted',null,null,'{}','Canemes (nabilone)','verified'),
('de-cang-pillar1','seeds_plants','permitted',null,null,'{"home_grow":"3 plants per adult","clubs":"propagation for members"}',null,'verified'),
('de-cang-pillar1','dried_flower','permitted',null,null,'{"possession":"25g public / 50g home","supply":"cultivation associations to members only"}','No commercial retail; Pillar 2 pilots pending','verified'),
('de-cang-pillar1','extracts_concentrates','prohibited',null,null,'{}','Associations may not distribute extracts','verified'),
('de-cang-pillar1','edibles','prohibited',null,null,'{}',null,'verified'),
-- ============ AUSTRALIA ============
('au-sas-ap','dried_flower','permitted',null,null,'{"tgo93":true}','Fastest-growing format; high-THC flower leads prescription volume and value','verified'),
('au-sas-ap','oral_oil','permitted',null,null,'{"tgo93":true}','CBD and balanced oils hold consistent share','verified'),
('au-sas-ap','capsules','permitted',null,null,'{}',null,'verified'),
('au-sas-ap','vape_products','permitted',null,null,'{"vaping_reforms_2024":"devices banned generally; MC devices via ARTG-approved list or SAS/AP with pre-import Essential Principles notice"}','Permitted within post-2024 device framework','verified'),
('au-sas-ap','lozenges','permitted',null,null,'{}','Wafer/pastille/lozenge categories in SAS product lists','needs_review'),
('au-sas-ap','extracts_concentrates','permitted',null,null,'{}',null,'needs_review'),
('au-sas-ap','topicals','permitted',null,null,'{}',null,'needs_review'),
('au-sas-ap','oromucosal_spray','permitted',null,null,'{}',null,'needs_review'),
('au-sas-ap','edibles','restricted',null,null,'{}','Gummy-style products under active TGA compliance scrutiny (2026-27 priority area)','needs_review'),
('au-registered','oromucosal_spray','permitted',null,null,'{}','Sativex','verified'),
('au-registered','oral_oil','permitted',null,null,'{}','Epidyolex','verified'),
('au-cbd-s3','oral_oil','proposed',null,'<=150 mg/day CBD (Sch 3 entry)','{}','Pathway exists; no ARTG-registered S3 product yet, so no lawful OTC supply','verified'),
-- ============ POLAND ============
('pl-raw-material','dried_flower','permitted','>0.3% THC = narcotic raw material, prescription-only',null,'{"administration":"vaporization","products":"~40 authorized flower raw materials"}','~77-79% of dispensed market; 5,447 kg in 2025','verified'),
('pl-raw-material','extracts_concentrates','permitted',null,null,'{"products":"12 extract raw materials (Dec 2025)"}','Primarily inputs for magistral preparations','verified'),
('pl-raw-material','magistral_preparations','permitted',null,null,'{}','Pharmacies compound and dose; includes magistral vape cartridges and rosin at some pharmacies','verified'),
('pl-raw-material','vape_products','restricted',null,null,'{"only_as":"magistral preparations"}','No industrially prefilled cartridges as authorized products','verified'),
('pl-raw-material','oral_oil','permitted',null,null,'{"only_as":"compounded preparations"}',null,'verified'),
('pl-raw-material','bulk_api_raw','permitted',null,null,'{"supply":"100% import-reliant; URPL raw-material marketing authorisations (5yr)"}',null,'verified'),
('pl-raw-material','edibles','prohibited',null,null,'{}',null,'verified'),
('pl-registered','oromucosal_spray','permitted',null,null,'{}','Sativex','verified'),
('pl-cbd-consumer','oral_oil','restricted','<=0.3% THC','Novel Food authorisation generally required for ingestible extracts','{"enforcement":"GIS + RASFF actions 2025"}','Ingestibles high enforcement risk; cosmetics route safer','verified'),
('pl-cbd-consumer','topicals','permitted','<=0.3% THC',null,'{}','Cosmetics the most practical consumer lane','needs_review'),
('pl-cbd-consumer','dried_flower','restricted','<=0.3% THC',null,'{}','CBD hemp flower sold as collectible/aromatherapy in grey zone','needs_review'),
-- ============ SOUTH AFRICA ============
('za-sahpra-s21','dried_flower','permitted',null,null,'{"schedule":"THC products Sch 6"}','Named-patient supply of unregistered flower','needs_review'),
('za-sahpra-s21','oral_oil','permitted',null,null,'{"schedule":"CBD Sch 4 above exemption levels"}',null,'verified'),
('za-sahpra-s21','capsules','permitted',null,null,'{}',null,'needs_review'),
('za-sahpra-s21','extracts_concentrates','restricted',null,null,'{}',null,'needs_review'),
('za-cbd-exemption','oral_oil','permitted','Processed-product alternative track: <=0.001% THC','<=600 mg CBD/pack and <=20 mg/day; or <=0.0075% CBD processed products','{"claims":"low-risk/general health only"}','OTC in pharmacies and wellness retail','verified'),
('za-cbd-exemption','topicals','permitted',null,null,'{}',null,'needs_review'),
('za-cbd-exemption','edibles','restricted',null,null,'{}','Mar 2025 blanket foodstuffs ban withdrawn after presidential intervention; foodstuff treatment contested pending replacement rules','verified'),
('za-private-use','seeds_plants','permitted',null,null,'{"scope":"private cultivation; commercial seed/clone sales unlawful"}',null,'verified'),
('za-private-use','dried_flower','permitted',null,null,'{"scope":"private possession/use only; no trade"}','CfPPA 2024 + Prince judgment; quantity regulations pending full commencement detail','verified'),
('za-sahpra-22c','bulk_api_raw','permitted','Hemp track <=2% THC under Plant Improvement Act (since 1 Dec 2025)',null,'{}','GMP cultivation/manufacture; ~120 export licences','verified'),
('za-sahpra-22c','dried_flower','permitted',null,null,'{"purpose":"export to regulated markets"}',null,'verified'),
('za-sahpra-22c','extracts_concentrates','permitted',null,null,'{}',null,'needs_review')
) as v(pslug, fslug, status, thc, cbd, cond, notes, ver)
join public.regulatory_pathways p on p.slug = v.pslug
join public.product_formats f on f.slug = v.fslug;