-- Bind fresh first-party authority snapshots to existing claim-level evidence.
-- Publication remains fail-closed: the resolver also requires the same SHA on the
-- current regulatory_market_access_primary_sources row.
update public.regulatory_market_access_evidence set tier='medical_limited_trade',authority_name='Swissmedic',authority_url='https://www.swissmedic.ch/swissmedic/en/home/humanarzneimittel/besondere-arzneimittelgruppen--ham-/authorised-narcotics/cannabis-agency.html',rationale='Current Swissmedic Cannabis Agency material identifies cannabis for medical purposes within the authorised-narcotics framework and provides licensing, import/export and domestic-trade controls.',source_snapshot_sha256='ec35526b04e58789e479efefce4bafc520eeb45b66a166a123c480b8b7cf3312',verified_at=now(),expires_at=now()+interval '30 days',active=true where evidence_key='hv-mkt-ch-20260907';
update public.regulatory_market_access_evidence set tier='legal_commercial_access',authority_name='Danish Medicines Agency',authority_url='https://laegemiddelstyrelsen.dk/en/licensing/company-authorisations-and-registrations/medicinal-cannabis-programme/',rationale='Current Danish Medicines Agency material expressly provides authorisation to manufacture cannabis bulk and primary/intermediate cannabis products under the medicinal cannabis programme.',source_snapshot_sha256='67d0727d5d3ec2faca2328c9f58a203a15ba00563f382f4473424bba55e7a3df',verified_at=now(),expires_at=now()+interval '30 days',active=true where evidence_key='incb-2023-trade-dk';
update public.regulatory_market_access_evidence set tier='legal_commercial_access',authority_name='Maryland Cannabis Administration',authority_url='https://cannabis.maryland.gov/Pages/Cannabis-Business-Licensing.aspx',rationale='Current Maryland Cannabis Administration material identifies active cannabis business licensing; Maryland law authorizes licensed medical and adult-use cannabis businesses.',source_snapshot_sha256='964d253e5fcd8c95847158aca7f82d96c173f31272f5b376d54f7c4839946430',verified_at=now(),expires_at=now()+interval '30 days',active=true where evidence_key='ncsl-us-md-20260831';
update public.regulatory_market_access_evidence set tier='medical_limited_trade',authority_name='Government of The Bahamas / Cannabis Authority framework',authority_url='https://opm.gov.bs/cannabis-bahamas/',rationale='The official Bahamas government cannabis framework describes medical, scientific and religious cannabis licensing, including cultivation, retail, manufacturing, testing and transport, with regulated import/export authorisations.',source_snapshot_sha256='2bbf701dc9687f420bb0347a9034d8d4dd9da44546e53166a2e253f8ef2eafa8',verified_at=now(),expires_at=now()+interval '30 days',active=true where evidence_key='hv-mkt-complete-bs-20260913';
update public.regulatory_market_access_evidence set tier='legal_commercial_access',authority_name='Illinois Department of Financial and Professional Regulation',authority_url='https://idfpr.illinois.gov/profs/adultusecan.html',rationale='Current Illinois IDFPR material states that the Cannabis Regulation and Tax Act provides for controlled legalization of adult-use cannabis and that IDFPR administers and oversees licensing of dispensing organizations and related cannabis program participants.',source_snapshot_sha256='738b555e965f0d8b5a8607279e0a5b330158b9e56e4a10dd53b548be58e328d5',verified_at=now(),expires_at=now()+interval '30 days',active=true where evidence_key='ncsl-us-il-20260831';

update public.regulatory_market_access_primary_sources set source_snapshot_sha256='ec35526b04e58789e479efefce4bafc520eeb45b66a166a123c480b8b7cf3312',verified_at=now(),expires_at=now()+interval '30 days' where jurisdiction_iso2='CH';
update public.regulatory_market_access_primary_sources set source_snapshot_sha256='67d0727d5d3ec2faca2328c9f58a203a15ba00563f382f4473424bba55e7a3df',verified_at=now(),expires_at=now()+interval '30 days' where jurisdiction_iso2='DK';
update public.regulatory_market_access_primary_sources set source_snapshot_sha256='964d253e5fcd8c95847158aca7f82d96c173f31272f5b376d54f7c4839946430',verified_at=now(),expires_at=now()+interval '30 days' where jurisdiction_iso2='US-MD';
update public.regulatory_market_access_primary_sources set source_snapshot_sha256='2bbf701dc9687f420bb0347a9034d8d4dd9da44546e53166a2e253f8ef2eafa8',verified_at=now(),expires_at=now()+interval '30 days' where jurisdiction_iso2='BS';
insert into public.regulatory_market_access_primary_sources (jurisdiction_iso2,jurisdiction_level,parent_iso2,source_class,authority_name,authority_url,source_title,source_effective_date,source_snapshot_sha256,verified_at,expires_at,notes) values ('US-IL','subnational','US','primary_regulator','Illinois Department of Financial and Professional Regulation','https://idfpr.illinois.gov/profs/adultusecan.html','Adult Use Cannabis Program','2026-09-23','738b555e965f0d8b5a8607279e0a5b330158b9e56e4a10dd53b548be58e328d5',now(),now()+interval '30 days','Current first-party adult-use cannabis licensing/regulation authority.') on conflict (jurisdiction_iso2) do update set authority_name=excluded.authority_name,authority_url=excluded.authority_url,source_title=excluded.source_title,source_effective_date=excluded.source_effective_date,source_snapshot_sha256=excluded.source_snapshot_sha256,verified_at=excluded.verified_at,expires_at=excluded.expires_at,notes=excluded.notes;
select api.refresh_verified_market_access_tiers('bind-fresh-authority-evidence-20260923');
