-- Reconstructed from production.
--
-- This file previously contained no DDL. It carried a short comment saying it
-- had been applied directly to production via Supabase MCP and existed only to
-- satisfy local/remote migration history parity, followed by `SELECT 1;`.
--
-- That placeholder satisfied the version-number ledger while executing nothing,
-- so `supabase db reset --local` could not rebuild the schema this migration is
-- supposed to create. The statements below are the verbatim text production
-- ran, read back from supabase_migrations.schema_migrations.statements for
-- version 20260703120639.
--
-- Rewriting this file cannot affect production: 20260703120639 is already recorded
-- in schema_migrations, so `supabase db push` skips it. This is a
-- repository-only repair of replay fidelity.
--
-- Regenerate with: node scripts/reconstruct-stub-migrations.mjs

insert into education_module_sections (module_id, section_order, heading, body, block_type)
select m.id, v.section_order, v.heading, v.body, v.block_type
from (values
  ('drug-interactions', 5, 'Key Takeaways', 'Assess interaction risk based on actual shared mechanism, particularly hepatic enzyme-mediated metabolic pathways, additive CNS effects, cardiovascular considerations, and anticoagulant interactions specifically, rather than superficial similarity between medication categories. Document which specific interaction categories were assessed as relevant or not relevant for a given patient''s actual medication combination, not just that a general review occurred.

Tailor combination-therapy counselling to the patient''s specific concurrent medications and the corresponding interaction mechanism, rather than relying on generic combination-therapy caution language. And when a patient transitions between product formats, an event that already triggers re-counselling under the pharmacy dispensing framework, specifically address whether the interaction profile with their existing medications changes alongside the format change, not only whether the cannabinoid product''s own behavior differs.

This module is educational and conceptual; it does not provide patient-specific interaction assessment or dosing guidance, which remains the treating clinician and pharmacist''s responsibility using current clinical reference resources.

Finally, given how much interaction risk depends on accurate, current knowledge of a patient''s complete medication list, including over-the-counter medications and supplements a patient may not think to mention as relevant, clinicians and pharmacists should build an explicit, direct prompt for this information into the standard intake and counselling process rather than relying on the patient to proactively volunteer a complete list, since patients frequently underreport over-the-counter and supplement use specifically because they don''t think of it as "real medication" worth mentioning, even where it carries genuine interaction relevance.

Given how broadly hepatic-enzyme-mediated interactions can affect medications with no obvious surface-level connection to cannabis-based treatment, a globally consistent interaction-screening protocol, applied with equal rigor regardless of jurisdiction or perceived local prescribing norms, provides meaningfully better patient protection than allowing screening rigor to vary informally based on individual clinician practice or jurisdiction-specific custom.

A further interaction category worth addressing explicitly concerns interactions with other herbal or complementary supplements specifically, since patients using cannabis-based treatment are statistically more likely than the general prescribed-medication population to also be using other herbal or complementary products, some of which share overlapping hepatic-metabolism pathways with cannabinoids, meaning a genuinely thorough medication-list intake should explicitly prompt for herbal and complementary product use with the same specificity applied to conventional prescribed medications.

It is also worth examining how interaction risk should inform, rather than simply caution against, treatment planning, since in many cases an identified interaction risk can be managed through dose adjustment, increased monitoring frequency, or timing separation between the two medications, rather than necessarily requiring that cannabis-based treatment be avoided entirely, meaning the documentation discipline covered elsewhere in this module should specifically capture which management approach was chosen and why, not merely that an interaction risk was identified.

Finally, prescribers and pharmacists should build awareness of how interaction reference resources themselves vary in currency and comprehensiveness specifically for cannabis-based products, given the relatively recent expansion of formal research in this area, meaning cross-checking a flagged or unflagged interaction against more than one current reference resource, particularly for a less common medication combination, provides a meaningfully more reliable check than relying on a single reference source alone.

A final point worth making explicit: clinical teams should periodically audit a sample of their own documented interaction assessments against current reference standards, treating this as a standing quality-assurance practice rather than a one-time training exercise, since reference standards and the underlying evidence base for specific cannabinoid interactions continue to evolve, and an audit practice catches drift between an individual clinician''s working knowledge and current best evidence before that drift accumulates into a meaningful pattern of under-assessed risk across a patient population.

This periodic audit discipline mirrors the same internal-review logic applied to documentation consistency in the clinical prescribing module elsewhere in this track, reinforcing that interaction-screening quality, like broader prescribing documentation quality, benefits from active internal verification rather than passive assumption that initial training alone keeps pace with an evolving evidence base indefinitely.

A related point worth making explicit: clinics should maintain a simple internal log of any interaction-related adverse events actually observed in their own patient population, reviewed periodically alongside formal reference-resource updates, since this kind of internally accumulated, organization-specific experience can surface patterns relevant to that specific patient population''s characteristics that a general reference resource, built from broader population data, may not fully capture or weight appropriately for the clinic''s own specific case mix. Even a lightweight, informally maintained log meaningfully outperforms relying on individual clinician memory across a growing patient base, and building a brief, structured review of this log into a recurring clinical governance meeting ensures the pattern actually gets surfaced and discussed rather than sitting unreviewed in a file that nobody returns to until a specific incident forces the question. A brief quarterly review of this log, folded into existing clinical governance meetings rather than treated as a separate administrative task, keeps the practice genuinely functioning without adding meaningful burden to clinical staff, and ensures any emerging local pattern gets surfaced and discussed before it accumulates into something more consequential.', 'text'),
  ('patient-access-pathways', 1, 'Why This Matters', 'The route by which an individual patient actually obtains a prescribed cannabis-based product varies enormously across the jurisdictions covered in this education track, and conflating the access-pathway question with the broader prescribing-legality question is a common source of confusion for patients, clinics, and operators alike. A jurisdiction permitting cannabis-based prescribing in principle frequently still requires the patient''s specific access to flow through one of several distinct, named pathways, each with its own eligibility criteria, approval authority, and timeline, exactly the structure seen concretely in the Australian module elsewhere in this track with its four distinct access schemes.

This matters for clinic operators and patient-facing organizations specifically, since the practical patient experience, how long access actually takes, what documentation the patient and prescriber need to assemble, and which specific product formats are actually reachable through a given pathway, depends entirely on correctly identifying which access pathway applies to a given patient''s situation, not on the broader fact that cannabis-based treatment is generally permitted in that jurisdiction.

For an operator building patient-facing services across multiple jurisdictions, understanding access pathways as a distinct layer from prescribing legality, reimbursement, and product registration is foundational to setting accurate patient expectations and building genuinely compliant patient support processes, rather than assuming a single onboarding workflow transfers cleanly across every market served.

A concrete illustrative scenario shows how pathway misclassification creates a worse patient experience. Picture a hypothetical patient with a genuinely severe, urgent condition who would clearly qualify for a jurisdiction''s fastest, notification-only severity-tiered access pathway, but whose case is processed by a clinic defaulting to its more familiar standard pathway requiring a fuller documented justification and longer approval timeline, simply because the clinic''s intake staff weren''t trained to specifically assess eligibility for the faster pathway. The patient experiences a meaningfully longer wait for access than the regulatory framework itself would have actually required for their specific situation, not because the framework failed the patient, but because the clinic''s own intake process failed to correctly route the patient to the pathway genuinely applicable to their case.

The structural access-pathway patterns identified in this module, fully registered, named-patient or individual-import, authorized-prescriber, and severity-tiered, recur in some combination across essentially every jurisdiction covered in this track, meaning an operator encountering a genuinely new jurisdiction not specifically covered elsewhere in this education track can use this module''s four-pattern framework as a starting analytical lens for quickly mapping that jurisdiction''s own specific access structure onto a familiar underlying typology, rather than needing to build an entirely new mental model from scratch.', 'text'),
  ('patient-access-pathways', 2, 'The Core Framework', 'Patient access pathways across the jurisdictions covered in this track cluster into a recognizable set of structural patterns, even where specific names and eligibility criteria differ.

Fully registered or licensed product pathways apply where a specific cannabis-based product has received full marketing authorization or equivalent formal registration, allowing prescribing through the same standard mechanism as any other approved medication, with correspondingly the most straightforward patient access experience but the narrowest set of products actually reaching this status in most jurisdictions, as flagged specifically in the UK module elsewhere in this track where only a small number of products hold this status.

Named-patient or individual-import pathways apply where a specific patient''s access to an unregistered product requires individual approval, frequently tied to a documented clinical justification that registered alternatives can''t meet the patient''s specific need, with approval granted by either the prescriber directly under delegated authority, or by a specific regulatory authority on a case-by-case basis, the structure seen in the UK''s unlicensed CBPM framework and several of Australia''s access scheme categories.

Authorized-prescriber or standing-authorization pathways allow a qualified prescriber to access a defined product or product class for a patient population on an ongoing basis without requiring fresh case-by-case approval for each individual patient, trading a more involved upfront prescriber qualification process for a faster subsequent patient-level experience, the structure behind Australia''s Authorised Prescriber scheme specifically.

Severity or urgency-tiered pathways differentiate access requirements based on how serious or urgent the patient''s condition is, frequently offering a faster, lighter-touch notification-only route for the most severe situations and a more involved, justification-heavy route for less urgent ones, the structure underlying the distinction between Australia''s Category A and Category B access schemes specifically.

It is worth examining the specific documentation burden differences between access pathway tiers in more detail, since this is frequently where patient and clinic frustration concentrates. A faster, notification-only pathway typically requires only confirmation of basic eligibility criteria being met, while a more involved, justification-heavy pathway typically requires detailed documentation of prior treatment history, specific reasons those treatments were inadequate, and sometimes formal review by an external body; a clinic that understands these documentation differences in advance can set patient expectations accurately from the very first conversation, rather than the patient discovering the actual documentation burden only partway through an already-initiated access process.

It is worth connecting this module''s pathway-classification discipline explicitly to the prescribing frameworks module elsewhere in this track, since access pathway and prescriber qualification are two genuinely independent dimensions that nonetheless interact, meaning a globally operating clinic''s patient intake process should assess both dimensions together for every new patient and every new jurisdiction, confirming both which access pathway applies and which prescriber qualification that pathway specifically requires, rather than treating either dimension as fully resolved once the other has been addressed.', 'text')
) as v(slug, section_order, heading, body, block_type)
join education_modules m on m.slug = v.slug;
