-- Stage 3 (INTELLIGENCE_ARCHITECTURE_SPEC.md): the CORRECT promotion path.
-- Replaces score-driven publishing (the inverted score_signal_from_snapshot) with
-- promotion driven by the validated Stage 2 classifier. Two invariants, enforced
-- structurally:
--   (1) PROMOTION ONLY EVER PROMOTES. The only write is reviewed false->true. No code
--       path here sets reviewed=false or deletes. (guardrail: promotion only promotes)
--   (2) VALIDATION-GATED. Publishing is DRY-RUN by default; a real publish requires an
--       explicit p_dry_run=false AND is meant to run only after the classifier clears the
--       eval-set bar (spec 6.2). Not wired to any cron. (guardrail: validate before wiring)
-- Additive + reversible. Rollback:
--   drop function if exists api.promote_classified_signals(numeric,boolean,int);
--   drop table if exists public.signal_classifications;

-- Production classifier output for the live signal pool (distinct from the 202-row
-- intel_eval_predictions, which is validation-only). Populated by hv-classify's pool run.
-- Converted to a no-op stub on 2026-07-22: re-running the CREATE TABLE
-- below fails ("relation already exists"). Confirmed live: both
-- public.signal_classifications and api.promote_classified_signals
-- already exist -- this work was already applied to production under the
-- neighboring version 20260718135702 (same filename).
SELECT 1;
