
-- Australia: 6 states + 2 territories

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'australian-capital-territory','state','AU','AU-ACT','Medical Legal; Decriminalized (Personal Use)',
'The Australian Capital Territory (ACT) enacted landmark legislation in September 2019, effective January 31, 2020, decriminalizing personal cannabis use and home cultivation for adults. Under the Drugs of Dependence (Personal Cannabis Use) Amendment Act 2019, adults may possess up to 50 grams of dried cannabis or 150 grams of fresh cannabis, and cultivate up to two plants per person (maximum four per household). Importantly, this creates a dual legal status: ACT law decriminalizes personal use, but Commonwealth (federal) law under the Criminal Code still technically prohibits it — meaning ACT Police exercise discretion but federal agencies could theoretically prosecute. In practice, personal use and home cultivation are effectively decriminalized. Medical cannabis follows the federal TGA pathway.',
'Medical patients in the ACT access TGA-approved cannabis products through the Therapeutic Goods Administration''s Special Access Scheme (SAS-B) or Authorised Prescriber (AP) pathways, obtaining products from licensed pharmacies. Adult personal use is decriminalized per ACT law, allowing possession and home cultivation within defined limits without criminal penalty.',
'Medical practitioners in the ACT register with TGA as Authorised Prescribers or submit individual Special Access Scheme applications for medical cannabis products. No specialist restriction — GPs can prescribe. The ACT Medical Board provides supplementary guidance.',
'The ACT is home to Canberra, Australia''s capital, with a population of approximately 460,000. The medical cannabis market follows the national TGA-regulated model. The decriminalization framework has not created a formal commercial adult-use market but has normalized personal cultivation and use. Several licensed medical cannabis clinics operate in Canberra.',
'The ACT''s decriminalization framework is unique in Australia and has been watched closely by other states considering similar reforms. NSW has reviewed ACT''s model. The dual state/federal legal status creates ongoing legal ambiguity that a future Commonwealth reform would resolve. ACT is expected to maintain its progressive position.',
'ACT Health oversees territory health regulation. ACT Policing (AFP) exercises discretion under the decriminalization framework. TGA administers national medical cannabis approvals.',
'ACT Drugs of Dependence (Personal Cannabis Use) Amendment Act 2019; TGA SAS-B and AP approval data; ACT Health pharmaceutical guidance; ACT Policing enforcement data','Current as of Q2 2026; verified against ACT Health and TGA guidance','Quarterly','Full territory briefing covering landmark decriminalization and federal medical framework',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='AU' AND state_iso2='AU-ACT');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'new-south-wales','state','AU','AU-NSW','Medical Legal; Recreational Prohibited',
'New South Wales is Australia''s most populous state and its largest medical cannabis market by patient volume. NSW follows the federal Therapeutic Goods Administration (TGA) framework for medical cannabis, with doctors prescribing TGA-approved products through the Special Access Scheme (SAS-B) or as Authorised Prescribers. Recreational cannabis remains prohibited under the Drug Misuse and Trafficking Act 1985. NSW had over 100,000 approved medical cannabis access pathways as of 2025, making it a dominant state market.',
'Medical patients access TGA-approved cannabis products through registered medical practitioners with SAS-B approval or via Authorised Prescribers. Products are dispensed through licensed pharmacies. Telehealth cannabis clinics have significantly improved patient access across the state, including rural and remote areas.',
'NSW medical practitioners access medical cannabis via TGA SAS-B applications or by registering as Authorised Prescribers. No specialist-only requirement — GPs are a major prescribing group. The Medical Council of NSW provides guidance on evidence-based cannabis prescribing.',
'NSW accounts for a substantial share of national medical cannabis approvals given its population of approximately 8.3 million. Multiple licensed medical cannabis clinics, both physical and telehealth-based, serve the NSW market. International and domestic licensed producers supply the NSW pharmacy channel. Annual patient spending on medical cannabis in NSW is estimated in the hundreds of millions of AUD.',
'NSW is developing a review of its drug enforcement approach. The NSW Drug Summit recommendations have included review of low-level cannabis offenses. The ACT decriminalization model is referenced in NSW reform discussions. Medical program expansion, particularly through telehealth, is expected to continue.',
'NSW Health (Ministry of Health) oversees state pharmaceutical regulation and health policy. NSW Police enforce recreational drug laws. TGA administers national medical cannabis approvals.',
'TGA SAS-B and AP approval data; NSW Health pharmaceutical guidance; NSW Police enforcement data; NSW Drug Summit reports','Current as of Q2 2026; verified against NSW Health and TGA guidance','Quarterly','Full state briefing covering large medical market and ongoing reform discussion',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='AU' AND state_iso2='AU-NSW');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'victoria','state','AU','AU-VIC','Medical Legal; Recreational Prohibited',
'Victoria is Australia''s second most populous state and a major medical cannabis market. The state follows the federal TGA framework for medical cannabis access. Recreational cannabis is prohibited under the Drugs, Poisons and Controlled Substances Act 1981. Victoria''s large population (approximately 6.7 million) and metropolitan Melbourne cannabis market make it a key market for licensed producers and telehealth cannabis clinics. Victoria has also explored drug harm reduction policy more broadly.',
'Medical patients access TGA-approved products through registered practitioners via SAS-B or Authorised Prescriber pathways, with dispensing through licensed pharmacies. Telehealth cannabis clinics serve patients across metropolitan and regional Victoria.',
'Victorian medical practitioners access cannabis prescribing through TGA SAS-B or Authorised Prescriber registration. The Medical Board of Australia and Medical Practitioners Board of Victoria provide guidance. No specialist-only requirement.',
'Victoria has a significant medical cannabis patient population. Melbourne-based medical cannabis clinics (both physical and telehealth) are prominent nationally. Multiple licensed producers have Victorian operations or supply Victorian pharmacies. Annual patient spending is estimated in the hundreds of millions of AUD.',
'Victoria is expected to continue growing its medical cannabis market. Broader drug law reform discussions include harm reduction measures. The state government has signaled support for harm reduction approaches that could eventually include personal use decriminalization.',
'Department of Health Victoria oversees state pharmaceutical and health policy. Victoria Police enforce drug laws. TGA administers national medical cannabis approvals.',
'TGA SAS-B and AP data; Department of Health Victoria pharmaceutical guidance; Victoria Police enforcement statistics; harm reduction policy documents','Current as of Q2 2026; verified against Department of Health Victoria and TGA guidance','Quarterly','State briefing covering major medical market and harm reduction policy trajectory',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='AU' AND state_iso2='AU-VIC');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'queensland','state','AU','AU-QLD','Medical Legal; Recreational Prohibited',
'Queensland follows the federal TGA medical cannabis framework. Recreational cannabis is prohibited under the Drugs Misuse Act 1986. Queensland''s large geographic area and population of approximately 5.5 million create a diverse market including major urban centres (Brisbane, Gold Coast) and extensive rural and remote areas. Telehealth cannabis clinics have been particularly impactful in rural Queensland where GP density is lower.',
'Medical patients access TGA-approved products through registered practitioners via SAS-B or Authorised Prescriber pathways. Queensland Health oversees pharmaceutical dispensing. Telehealth services have expanded rural access significantly.',
'Queensland medical practitioners access cannabis prescribing through TGA SAS-B or AP registration. The Medical Board of Australia provides national guidance. No specialist-only restriction.',
'Queensland has a growing medical cannabis patient population. Brisbane-based and telehealth clinics serve the state. The state''s large agriculture sector has also driven interest in hemp cultivation, with Queensland farmers among Australia''s licensed hemp producers.',
'Queensland''s medical cannabis market continues expanding. Drug law reform advocacy has grown but no imminent decriminalization legislation is confirmed. Hemp agricultural sector development is ongoing.',
'Queensland Health oversees state pharmaceutical and health policy. Queensland Police enforce drug laws. TGA administers national medical cannabis approvals.',
'TGA SAS-B and AP data; Queensland Health pharmaceutical guidance; Queensland Police enforcement data; Queensland hemp cultivation statistics','Current as of Q2 2026','Quarterly','State briefing covering medical market and rural access context',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='AU' AND state_iso2='AU-QLD');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'western-australia','state','AU','AU-WA','Medical Legal; Recreational Prohibited',
'Western Australia follows the federal TGA medical cannabis framework. Recreational cannabis is prohibited under the Misuse of Drugs Act 1981. WA''s large geographic area (the largest Australian state) with a population of approximately 2.9 million creates significant rural and remote access challenges. Perth is the dominant urban market. WA has also been a significant licensed hemp cultivation state.',
'Medical patients access TGA-approved products through registered practitioners via SAS-B or Authorised Prescriber pathways. WA Health oversees state pharmaceutical dispensing. Remote access is a challenge given the state''s vast geography.',
'WA medical practitioners access cannabis prescribing through TGA pathways. The Medical Board of Australia and WA Medical Board provide guidance. No specialist-only restriction.',
'WA''s medical cannabis market is growing. Perth clinics serve the urban population while telehealth addresses remote areas. WA is also a significant hemp agricultural producer. Annual patient spending is growing.',
'WA''s medical cannabis market is expected to continue growing. Drug reform advocacy is present but no imminent legislative change is expected.',
'Western Australia Department of Health oversees pharmaceutical policy. WA Police enforce drug laws. TGA administers national medical cannabis approvals.',
'TGA SAS-B and AP data; WA Department of Health pharmaceutical guidance; WA Police enforcement data; WA hemp cultivation statistics','Current as of Q2 2026','Quarterly','State briefing covering medical market in large remote state',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='AU' AND state_iso2='AU-WA');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'south-australia','state','AU','AU-SA','Medical Legal; Decriminalized (Expiation Notices)',
'South Australia has a unique cannabis enforcement framework — possession of up to 100 grams is subject to a cannabis expiation notice (CEN, effectively a civil fine) rather than criminal prosecution under the Controlled Substances Act 1984. This is Australia''s longest-standing decriminalization-adjacent framework, established in 1987. Cultivation for personal use is also subject to expiation notices for small quantities. Medical cannabis follows the federal TGA framework.',
'Medical patients access TGA-approved products through registered practitioners via SAS-B or Authorised Prescriber pathways, with pharmacy dispensing. The expiation notice framework means adult personal use is effectively decriminalized in practice.',
'SA medical practitioners access cannabis prescribing through TGA pathways. No specialist-only restriction. SA Health provides guidance aligned with national standards.',
'South Australia''s medical cannabis market follows national growth trends. The long-standing expiation notice framework for personal use has created a pragmatic enforcement environment. Telehealth cannabis clinics serve both Adelaide and regional SA populations.',
'SA''s expiation notice framework is well-established and politically stable. Medical program expansion continues. Broader reform toward formal personal use legalization is possible given SA''s existing pragmatic approach.',
'SA Health oversees pharmaceutical and health policy. South Australia Police enforce drug laws under the expiation notice framework. TGA administers national medical cannabis approvals.',
'SA Controlled Substances Act 1984 and expiation notice framework; TGA SAS-B and AP data; SA Health pharmaceutical guidance; SA Police enforcement statistics','Current as of Q2 2026; verified against SA Health and TGA guidance','Quarterly','State briefing covering unique expiation notice framework and medical program',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='AU' AND state_iso2='AU-SA');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'tasmania','state','AU','AU-TAS','Medical Legal; Recreational Prohibited',
'Tasmania follows the federal TGA medical cannabis framework. Recreational cannabis is prohibited under the Misuse of Drugs Act 2001. Tasmania has a small population of approximately 570,000 concentrated in Hobart and Launceston. The state has a significant agricultural sector including licensed hemp cultivation. Tasmania''s isolated island geography creates some unique supply chain characteristics for the medical cannabis market.',
'Medical patients access TGA-approved products through registered practitioners via SAS-B or Authorised Prescriber pathways. Pharmacy dispensing is available in major urban areas. Telehealth cannabis clinics serve rural populations.',
'Tasmanian medical practitioners access cannabis prescribing through TGA pathways. No specialist-only restriction. The Medical Council of Tasmania provides supplementary guidance.',
'Tasmania''s small medical cannabis market is served by both locally based practitioners and national telehealth platforms. The state''s agricultural capacity includes licensed hemp cultivation. Annual patient spending is modest given population size.',
'Tasmania''s medical market will continue modest growth. Hemp agricultural sector development is ongoing. No significant recreational reform is anticipated in the near term.',
'Department of Health Tasmania oversees pharmaceutical and health policy. Tasmania Police enforce drug laws. TGA administers national medical cannabis approvals.',
'TGA SAS-B and AP data; Department of Health Tasmania pharmaceutical guidance; Tasmania Police enforcement data; Tasmania hemp cultivation statistics','Current as of Q2 2026','Annual','State briefing covering medical program in small island state',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='AU' AND state_iso2='AU-TAS');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'northern-territory','state','AU','AU-NT','Medical Legal; Recreational Prohibited',
'The Northern Territory follows the federal TGA medical cannabis framework. Recreational cannabis is prohibited under the Misuse of Drugs Act 1990. The NT has a population of approximately 250,000 with a significant Indigenous Australian population (approximately 30% of the territory). Remote communities face significant healthcare access challenges. The NT''s Indigenous community context creates unique considerations for cannabis policy and enforcement.',
'Medical patients access TGA-approved products through registered practitioners via SAS-B or Authorised Prescriber pathways. Access in remote Indigenous communities is a significant challenge requiring telehealth and outreach solutions.',
'NT medical practitioners access cannabis prescribing through TGA pathways. The NT Medical Board and Aboriginal Medical Services provide context-specific guidance for remote and Indigenous healthcare delivery.',
'The NT medical cannabis market is small given the population, with particular access challenges in remote communities. Darwin and Alice Springs are the primary urban markets. Aboriginal Medical Services play a critical role in healthcare delivery including cannabis access pathways.',
'NT medical cannabis access is expected to grow, particularly through telehealth. Indigenous community-specific healthcare frameworks require culturally appropriate access pathways. Broader drug policy reform discussions acknowledge the NT''s unique demographic context.',
'NT Health oversees pharmaceutical and health policy. NT Police enforce drug laws. TGA administers national medical cannabis approvals. Aboriginal Medical Services provide community-based healthcare.',
'TGA SAS-B and AP data; NT Health pharmaceutical guidance; NT Police enforcement statistics; Aboriginal Medical Services documentation','Current as of Q2 2026','Annual','Territory briefing covering medical program with significant Indigenous community context',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='AU' AND state_iso2='AU-NT');
