-- Sources for jurisdiction_playbooks batch 20 (part A of B, see batch20b for
-- playbook content + market metrics). Split across two files due to payload size.

INSERT INTO public.source_registry (source_name, source_url, country, iso, region, tier, adapter, crawl_cadence, source_type, notes)
VALUES
  ('CMS Expert Guides — Cannabis law and legislation in Ukraine', 'https://cms.law/en/int/expert-guides/cms-expert-guide-to-a-legal-roadmap-to-cannabis/ukraine', 'Ukraine', 'UA', 'Europe', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'Law 3528-IX full licensing/quota framework, zero import quota until 2028 exception list, industrial hemp THC 0.2%->0.3% Feb 2027 threshold'),
  ('CMS Law Now — Ukraine approves 2026 quotas for controlled substances including medical cannabis', 'https://cms-lawnow.com/en/ealerts/2026/01/ukraine-approves-2026-quotas-for-controlled-substances-including-medical-cannabis-thc', 'Ukraine', 'UA', 'Europe', 1, 'html_snapshot', 'annual', 'regulatory_filing', 'First-ever 2026 THC storage/production/import/export quotas, 592,068g storage limit'),
  ('Wikipedia — Cannabis in Ukraine', 'https://en.wikipedia.org/wiki/Cannabis_in_Ukraine', 'Ukraine', 'UA', 'Europe', 2, 'html_snapshot', 'quarterly', 'reference', 'Administrative possession threshold 5g, cultivation up to 10 plants administrative not criminal'),
  ('MyCannabis — Is Weed Legal in Ukraine 2026', 'https://www.mycannabis.com/is-weed-legal-in-ukraine/', 'Ukraine', 'UA', 'Europe', 2, 'html_snapshot', 'quarterly', 'legal_analysis', 'War-driven reform context, up to 6M potential patients per Health Ministry estimate'),
  ('Ministry of the Interior Ghana — Ghana Begins Medicinal and Industrial Cannabis Cultivation', 'https://www.mint.gov.gh/ghana-begins-medicinal-and-industrial-cannabis-cultivation/', 'Ghana', 'GH', 'Africa', 1, 'html_snapshot', 'quarterly', 'government_release', 'Official Feb 2026 program launch, 50% Ghanaian ownership requirement, 18+ age requirement'),
  ('Narcotics Control Commission Ghana — Cannabis Regulations', 'https://www.ncc.gov.gh/cannabis-regulations/', 'Ghana', 'GH', 'Africa', 1, 'html_snapshot', 'quarterly', 'regulatory_filing', 'Act 1100 (2023) and L.I. 2475 legal basis, 0.3% THC ceiling, NACOC oversight'),
  ('Herb.co — How to Buy Weed in Ghana in 2026', 'https://herb.co/city-guides/buy-weed-ghana', 'Ghana', 'GH', 'Africa', 2, 'html_snapshot', 'quarterly', 'legal_analysis', '11 NACOC licence categories, Section 45 Act 1019 criminal penalty for unauthorized dealing confirmed still in force'),
  ('The Marijuana Herald — Ghana Opens Cannabis Licenses to Citizens Abroad', 'https://themarijuanaherald.com/2026/04/ghana-opens-cannabis-licenses-to-citizens-abroad-as-hemp-industry-begins-accepting-applications/', 'Ghana', 'GH', 'Africa', 2, 'html_snapshot', 'quarterly', 'news', 'Diaspora investment framing, $7.8B 2025 remittances context, full supply chain licensing scope'),
  ('Cannabis Control & Regulatory Authority Pakistan — Official Site', 'https://www.ccra.gov.pk/', 'Pakistan', 'PK', 'Asia', 1, 'html_snapshot', 'monthly', 'government_release', 'CCRA HQ inaugurated May 2026, E-Licensing Portal live, QR-coded digital licenses'),
  ('Wikipedia — Cannabis Control and Regulatory Authority', 'https://en.wikipedia.org/wiki/Cannabis_Control_and_Regulatory_Authority', 'Pakistan', 'PK', 'Asia', 2, 'html_snapshot', 'quarterly', 'reference', 'CCRA Act 2024 establishment, Cabinet Division oversight, board functions'),
  ('LegalClarity — Is Weed Legal in Pakistan? A Look at Current Laws', 'https://legalclarity.org/is-weed-legal-in-pakistan-a-look-at-current-laws/', 'Pakistan', 'PK', 'Asia', 2, 'html_snapshot', 'quarterly', 'legal_analysis', '5-year license validity, penalty structure PKR 1-10M individuals up to 200M companies, CBD not distinguished from THC'),
  ('The Marijuana Herald — Pakistan Approves Funding to Launch Cannabis Regulatory Office', 'https://themarijuanaherald.com/2026/05/pakistan-approves-funding-to-launch-government-run-cannabis-regulatory-office-in-islamabad/', 'Pakistan', 'PK', 'Asia', 2, 'html_snapshot', 'quarterly', 'news', 'May 2026 ECC Rs.100M supplementary grant for HQ, still-forming institutional capacity signal'),
  ('Business of Cannabis — Inside Slovenia''s New Revolutionary Medical Cannabis Law', 'https://businessofcannabis.com/inside-slovenias-new-revolutionary-medical-cannabis-law/', 'Slovenia', 'SI', 'Europe', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'Act in force 20 Aug 2025, 6-month technical rules deadline, JAZMP 18-month e-records deadline, EUR55M by 2029 forecast'),
  ('Sibiz — Slovenia legalizes medical cannabis: new law effective from August 20 2025', 'https://sibiz.eu/slovenia-legalizes-medical-cannabis-marijuana-new-law-effective-from-august-20-2025/', 'Slovenia', 'SI', 'Europe', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'Any-condition prescribing authority, 1-month non-renewable prescriptions, Medical Chamber concern about scope'),
  ('Marijuana Moment — Slovenian Lawmakers File Bill To Legalize Marijuana For Adults', 'https://www.marijuanamoment.net/slovenian-lawmakers-file-bill-to-legalize-marijuana-for-adults-as-separate-medical-cannabis-measure-passes/', 'Slovenia', 'SI', 'Europe', 2, 'html_snapshot', 'monthly', 'legislative_tracking', 'National Council veto 20-9 then National Assembly override 49-11, adult-use bill still pending as of reporting'),
  ('Prohibition Partners — Slovenia Medical Cannabis Legislation & Legal Status Map', 'https://prohibitionpartners.com/european-cannabis-markets/european-medical-cannabis-legislation-map/slovenia/', 'Slovenia', 'SI', 'Europe', 1, 'html_snapshot', 'quarterly', 'legal_analysis', 'Open licensing system framing, any-operator-qualifies model, JAZMP licensing authority confirmed')
ON CONFLICT DO NOTHING;
