-- Jurisdiction Briefings — AI-synthesised weekly market intelligence per country
-- Generated by the synthesize-jurisdictions cron, reviewed before publishing.

CREATE TABLE public.jurisdiction_briefings (
  id                    uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  country_iso2          text        NOT NULL,
  country_name          text,
  generated_at          timestamptz NOT NULL DEFAULT now(),
  week_ending           date        NOT NULL,
  status                text        NOT NULL DEFAULT 'draft'
                                    CHECK (status IN ('draft', 'published', 'archived')),
  signal_count          int         NOT NULL DEFAULT 0,
  -- Synthesised fields
  headline              text        NOT NULL DEFAULT '',
  legal_status          text        NOT NULL DEFAULT 'unknown',
  market_maturity       text        NOT NULL DEFAULT 'unknown',
  summary               text        NOT NULL DEFAULT '',
  what_changed          text,
  operator_implications text,
  whats_coming          text,
  key_signals           jsonb       NOT NULL DEFAULT '[]',
  -- Provenance
  model_used            text,
  prompt_version        int         NOT NULL DEFAULT 1,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  -- One briefing per country per week
  UNIQUE (country_iso2, week_ending)
);

CREATE INDEX jurisdiction_briefings_country_week
  ON public.jurisdiction_briefings (country_iso2, week_ending DESC);

CREATE INDEX jurisdiction_briefings_published
  ON public.jurisdiction_briefings (status, generated_at DESC)
  WHERE status = 'published';

ALTER TABLE public.jurisdiction_briefings ENABLE ROW LEVEL SECURITY;

-- Anyone can read published briefings
CREATE POLICY "public_read_published"
  ON public.jurisdiction_briefings
  FOR SELECT
  USING (status = 'published');

-- Service role writes (cron + admin)
CREATE POLICY "service_write"
  ON public.jurisdiction_briefings
  FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE TRIGGER set_jurisdiction_briefings_updated_at
  BEFORE UPDATE ON public.jurisdiction_briefings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
