-- Primary Kiribati regulatory enrichment; fail-closed on unsupported dimensions.
update public.regulatory_market_access_evidence set active=false,expires_at=now() where evidence_key='hv-mkt-complete-ki-20260913';
insert into public.regulatory_market_access_evidence (evidence_key,jurisdiction_iso2,tier,rationale,authority_name,authority_url,source_effective_date,verified_at,expires_at,active)
values ('primary-evidence-ki-dangerous-drugs-20260922','KI','prohibited','Kiribati''s Dangerous Drugs Ordinance framework controls cannabis as a dangerous drug. The Kiribati Trade and Investment Portal lists the Dangerous Drugs Ordinance, amendments and regulations, while the Customs law restricts cannabis import except under licence. No commercial cannabis market is established by the cited framework.','Government of Kiribati / Kiribati Trade and Investment Portal','https://kiribati.tradeportal.org/Laws?l=en','1980-02-21',now(),now()+interval '180 days',true)
on conflict (evidence_key) do update set tier=excluded.tier,rationale=excluded.rationale,authority_name=excluded.authority_name,authority_url=excluded.authority_url,source_effective_date=excluded.source_effective_date,verified_at=now(),expires_at=now()+interval '180 days',active=true;
insert into public.regulatory_market_access_claims (evidence_key,jurisdiction_iso2,claim_key,claim_text,product_class,jurisdiction_scope,authority_name,authority_url,source_effective_date,retrieved_at,verified_at,expires_at,evidence_status)
values ('primary-evidence-ki-dangerous-drugs-20260922','KI','primary-evidence-claim:ki-dangerous-drugs-20260922','Kiribati controls cannabis under its dangerous-drugs framework and restricts cannabis import except under licence; the cited primary framework does not establish a commercial cannabis market.','any','national','Government of Kiribati / Kiribati Trade and Investment Portal','https://kiribati.tradeportal.org/Laws?l=en','1980-02-21',now(),now(),now()+interval '180 days','verified')
on conflict (claim_key) do update set claim_text=excluded.claim_text,authority_name=excluded.authority_name,authority_url=excluded.authority_url,source_effective_date=excluded.source_effective_date,retrieved_at=now(),verified_at=now(),expires_at=now()+interval '180 days',evidence_status='verified';
insert into public.source_registry (source_name,source_url,jurisdiction_code,country,iso,tier,source_type,crawl_allowed,is_active,region,language,adapter,crawl_cadence,relevance_status,next_crawl_at,network_status,verification_notes,verification_checked_at,regulator_class,content_type,metadata)
values ('Kiribati Trade and Investment Portal — Dangerous Drugs laws','https://kiribati.tradeportal.org/Laws?l=en','KI','Kiribati','KI',1,'regulator',true,true,'micronesia','en','html_snapshot','weekly','verified',now()+interval '7 days','online','Government Kiribati trade portal primary legislation source verified 2026-09-22.','2026-09-22','drug_control_authority',array['legislation'],jsonb_build_object('primary_source',true))
on conflict (source_url) do update set jurisdiction_code='KI',country='Kiribati',iso='KI',tier=1,source_type='regulator',crawl_allowed=true,is_active=true,relevance_status='verified',next_crawl_at=now()+interval '7 days',network_status='online',verification_notes='Government Kiribati trade portal primary legislation source verified 2026-09-22.',verification_checked_at=now(),regulator_class='drug_control_authority',updated_at=now();
update public.jurisdiction_dimension_coverage set status='verified_populated',evidence_basis='Government Kiribati dangerous-drugs framework and customs restriction verify cannabis prohibition/control.',last_evaluated_at=now(),notes='Verified 2026-09-22 from Government of Kiribati trade portal.' where jurisdiction_key='KI' and dimension_key in ('source_registry','verified_regulatory_evidence','verified_regulatory_claims');
update public.jurisdiction_dimension_coverage set status='verified_empty',evidence_basis='Cited primary framework establishes controls but no commercial cannabis pathway or product-format regime.',last_evaluated_at=now(),notes='No commercial pathway or format rules supported by cited primary framework; fail-closed.' where jurisdiction_key='KI' and dimension_key in ('verified_pathways','verified_format_rules');
update public.jurisdiction_data_depth_tasks set status='verified',updated_at=now(),notes='Verified from primary Kiribati dangerous-drugs framework on 2026-09-22.' where jurisdiction_key='KI' and dimension_key in ('source_registry','verified_regulatory_evidence','verified_regulatory_claims','verified_pathways','verified_format_rules');
