
-- Germany Länder batch A: BY BW BE BB HH HB HE MV (Bavaria through Mecklenburg-Vorpommern)
-- Federal CanG (Cannabis Act) in force from April 1, 2024: adults 18+, up to 25g in public, 50g at home, 3 plants, no commercial dispensaries yet, Cannabis Social Clubs (Anbauvereinigungen) licensed by Länder authorities

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'bavaria','state','DE','DE-BY','Adult-Use (Federal CanG); Medical Legal; Restrictive State Enforcement',
'Bavaria (Bayern) is Germany''s largest state by area and second largest by population (approximately 13.4 million), governed by the conservative CSU party. Despite the federal Cannabis Act (CanG) taking effect April 1, 2024, Bavaria has implemented the most restrictive enforcement posture of any German Land. The Bavarian state government actively opposed cannabis legalization during the legislative process and has pursued aggressive enforcement of buffer zone rules (200m prohibition near schools, playgrounds, and pedestrian zones). Cannabis Social Clubs (Anbauvereinigungen) face stringent licensing requirements in Bavaria, with the state issuing comparatively few approvals. Adult-use possession rights under federal law still apply in Bavaria, but practical access through clubs is more limited than in progressive Länder. Medical cannabis follows the federal framework and is available via prescription at all Bavarian pharmacies.',
'Medical patients access pharmacy-dispensed medical cannabis via physician prescription throughout Bavaria, including major cities (Munich, Nuremberg, Augsburg). TK, AOK Bayern, and other statutory health insurers provide partial reimbursement for specific indications under the federal medical framework. Adult-use consumers access cannabis via licensed Cannabis Social Clubs or home cultivation (3 plants maximum).',
'Bavarian physicians may prescribe medical cannabis under the federal framework without specialist restriction. The Bayerische Landesärztekammer (Bavarian Medical Association) has issued conservative guidance encouraging careful evidence assessment but does not restrict prescribing.',
'Bavaria''s cannabis market is significant given its population but constrained by the state government''s restrictive approach to Cannabis Social Club licensing. Medical cannabis prescribing has grown substantially. Munich, Germany''s third largest city, has a significant patient and adult-use consumer base. The restrictive CSC licensing environment means consumers often access cannabis through home cultivation or clubs in neighboring Länder.',
'Bavaria''s CSU-led government is expected to maintain its maximally restrictive interpretation of the CanG. Legal challenges to Bavaria''s enforcement of buffer zones have been filed. The second phase of cannabis reform (commercial dispensary pilot programs) will face additional resistance from the Bavarian state government.',
'Bayerisches Staatsministerium für Gesundheit und Pflege (Bavarian State Ministry of Health and Care) oversees pharmaceutical regulation. Bayerische Polizei enforces drug laws. Cannabis Social Club licensing falls under state authorities per CanG.',
'German CanG federal legislation; Bavarian state enforcement guidance; Bayerische Landesärztekammer prescribing guidance; Cannabis Social Club licensing data; BFARM medical cannabis pharmacy data','Current as of Q2 2026; verified against Bavarian Ministry of Health guidance','Quarterly','Full Land briefing covering restrictive CSU enforcement posture within federal CanG framework',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='DE' AND state_iso2='DE-BY');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'berlin','state','DE','DE-BE','Adult-Use (Federal CanG); Medical Legal; Progressive Enforcement',
'Berlin, Germany''s capital city-state with a population of approximately 3.8 million, operates under the federal Cannabis Act (CanG) with a distinctly more progressive implementation than conservative Länder. Berlin was among the first German cities to issue Cannabis Social Club (Anbauvereinigung) licenses, and the city''s culture of liberal tolerance has shaped a pragmatic enforcement approach. The SPD/Greens-led Berlin Senate has facilitated club licensing and is participating in the federal commercial pilot dispensary program. Berlin''s international reputation and large young adult population make it a prominent early adopter market for adult-use cannabis.',
'Medical patients access pharmacy-dispensed cannabis via physician prescription throughout Berlin. Multiple cannabis specialist clinics operate in the city. Major statutory health insurers provide reimbursement for approved indications. Adult-use consumers access licensed Cannabis Social Clubs or home cultivation.',
'Berlin physicians prescribe medical cannabis under the federal framework. The Ärztekammer Berlin has issued supportive guidance. Telehealth cannabis prescribing is widely available to Berlin patients.',
'Berlin has a dynamic medical and adult-use cannabis ecosystem. Multiple licensed Cannabis Social Clubs operate, with more under application review. The Berlin cannabis club sector has attracted significant media attention as a model for adult-use access under CanG. Medical cannabis clinics and pharmacies are well-established. Berlin is among the cities applying to participate in Phase 2 commercial dispensary pilot programs.',
'Berlin''s progressive Senate is expected to be an early participant in Phase 2 commercial dispensary pilots under CanG. Cannabis club density will continue growing. Berlin''s experience will be a critical reference for broader German commercial cannabis policy.',
'Senatsverwaltung für Wissenschaft, Gesundheit und Pflege (Berlin Senate Department for Health) oversees pharmaceutical regulation. Berliner Polizei enforces CanG with a stated pragmatic approach. Cannabis Social Club licensing managed by Berlin district authorities.',
'German CanG; Berlin Senate Health Department guidance; Berlin Cannabis Social Club licensing data; BFARM medical cannabis statistics; Berlin pilot dispensary program documentation','Current as of Q2 2026; verified against Berlin Senate Health guidance','Quarterly','Full city-state briefing covering progressive CanG implementation and Cannabis Social Club ecosystem',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='DE' AND state_iso2='DE-BE');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'hamburg','state','DE','DE-HH','Adult-Use (Federal CanG); Medical Legal; Progressive Enforcement',
'Hamburg, Germany''s second largest city and major port (population approximately 1.9 million), operates under the federal CanG with a progressive SPD-led Senate implementing a cooperative approach to Cannabis Social Club licensing. Hamburg has applied to participate in Phase 2 commercial dispensary pilot programs and has been an active voice for pragmatic cannabis implementation at the federal level. The city''s liberal urban culture and significant international population create strong adult-use demand.',
'Medical patients access pharmacy-dispensed cannabis throughout Hamburg via physician prescription. Multiple medical cannabis practices operate. Major health insurers provide reimbursement for approved indications. Adult-use consumers access licensed Cannabis Social Clubs or cultivate at home.',
'Hamburg physicians prescribe under the federal framework. The Ärztekammer Hamburg has issued constructive guidance for evidence-based prescribing. Telehealth services serve Hamburg patients.',
'Hamburg has a growing Cannabis Social Club sector under CanG. Medical cannabis prescribing is well-established with multiple specialist practices. Hamburg''s application for Phase 2 commercial pilot participation positions it as a potential early commercial dispensary market.',
'Hamburg is expected to be among the first German cities with licensed commercial cannabis dispensaries if Phase 2 proceeds. The SPD Senate''s supportive posture will drive progressive implementation.',
'Behörde für Wissenschaft und Gesundheit Hamburg (Hamburg Senate Authority for Health) oversees pharmaceutical regulation. Hamburgische Polizei enforces CanG. Cannabis Social Club licensing managed by Hamburg district authorities.',
'German CanG; Hamburg Senate Health Authority guidance; Cannabis Social Club licensing data; Phase 2 pilot program application; BFARM medical cannabis statistics','Current as of Q2 2026; verified against Hamburg Senate Health guidance','Quarterly','City-state briefing covering progressive CanG implementation and Phase 2 commercial pilot ambition',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='DE' AND state_iso2='DE-HH');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'north-rhine-westphalia','state','DE','DE-NW','Adult-Use (Federal CanG); Medical Legal; Moderate Enforcement',
'North Rhine-Westphalia (NRW) is Germany''s most populous Land with approximately 18 million residents, making it the largest single cannabis market in Germany. NRW is governed by a CDU-led coalition, which has taken a moderate rather than aggressively restrictive approach to CanG implementation, contrasting with Bavaria. The state has processed Cannabis Social Club applications and enforces federal law pragmatically. Major urban centres including Cologne, Düsseldorf, Dortmund, and Essen drive significant medical and adult-use demand.',
'Medical patients access pharmacy-dispensed cannabis throughout NRW via physician prescription. Given NRW''s large population and urban density, cannabis prescribing volumes are among Germany''s highest. Major health insurers provide reimbursement for approved indications.',
'NRW physicians prescribe under the federal framework. The Ärztekammer Nordrhein and Ärztekammer Westfalen-Lippe have issued guidance supporting evidence-based prescribing. No specialist restriction applies.',
'NRW''s cannabis market is Germany''s largest by population scale. Multiple Cannabis Social Clubs have been licensed across the state''s major cities. Medical cannabis prescribing volumes are substantial. The state''s large working-age population creates strong demand across both medical and adult-use channels.',
'NRW''s CDU-led government is expected to implement CanG pragmatically rather than obstructively. Phase 2 commercial pilot dispensary participation is likely in Cologne, Düsseldorf, or other major NRW cities. Market scale will make NRW critical to German cannabis policy outcomes.',
'NRW Ministerium für Arbeit, Gesundheit und Soziales (Ministry of Labour, Health and Social Affairs) oversees pharmaceutical regulation. NRW Polizei enforces CanG. Cannabis Social Club licensing managed by state district authorities.',
'German CanG; NRW Ministry of Health guidance; Cannabis Social Club licensing data NRW; BFARM medical cannabis statistics; Phase 2 pilot program documentation','Current as of Q2 2026; verified against NRW Ministry of Health guidance','Quarterly','Full Land briefing covering Germany''s most populous cannabis market',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='DE' AND state_iso2='DE-NW');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'baden-wurttemberg','state','DE','DE-BW','Adult-Use (Federal CanG); Medical Legal; Moderate-Restrictive Enforcement',
'Baden-Württemberg, Germany''s third largest Land by population (approximately 11.3 million), is governed by a Green-CDU coalition. The Green party component of the coalition has tempered what might otherwise be a more restrictive CDU approach, resulting in moderate implementation of CanG. Major cities include Stuttgart, Mannheim, and Freiburg. Cannabis Social Club licensing has proceeded at a measured pace. The state has a significant pharmaceutical and life sciences industry, which gives medical cannabis commercial development some institutional support.',
'Medical patients access pharmacy-dispensed cannabis throughout Baden-Württemberg via physician prescription. Multiple specialist cannabis practices operate in Stuttgart, Mannheim, and other cities. Health insurers provide reimbursement for approved indications.',
'BW physicians prescribe under the federal framework. The Landesärztekammer Baden-Württemberg has issued guidance supporting evidence-based prescribing. Freiburg, near the Swiss border, benefits from proximity to Switzerland''s legal cannabis pilot context.',
'Baden-Württemberg''s cannabis market is significant given its population. Cannabis Social Club licensing is processing. Medical cannabis is well-established through pharmacies and specialist practices. The state''s pharmaceutical industry base creates potential for cannabis product development.',
'The Green party influence in the BW coalition is expected to produce progressive Phase 2 engagement. Stuttgart and Freiburg are potential Phase 2 pilot dispensary cities. The pharmaceutical industry presence may influence medical cannabis production and product innovation.',
'Ministerium für Soziales, Gesundheit und Integration Baden-Württemberg (Ministry for Social Affairs, Health and Integration) oversees pharmaceutical regulation. Polizei Baden-Württemberg enforces CanG.',
'German CanG; BW Ministry of Health guidance; Cannabis Social Club licensing data BW; BFARM medical cannabis statistics','Current as of Q2 2026; verified against BW Ministry of Health guidance','Quarterly','Land briefing covering moderate Green-CDU coalition implementation of CanG',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='DE' AND state_iso2='DE-BW');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'hesse','state','DE','DE-HE','Adult-Use (Federal CanG); Medical Legal',
'Hesse (Hessen) is a central German Land with approximately 6.4 million residents, governed by a CDU-SPD coalition. Frankfurt, Germany''s financial capital and major international hub, is Hesse''s largest city. Cannabis Social Club licensing under CanG has proceeded at a measured pace under CDU leadership. Frankfurt''s international status creates demand from a diverse population including significant expatriate and tourist communities. The medical cannabis market is well-developed given the population and economic base.',
'Medical patients access pharmacy-dispensed cannabis throughout Hesse via physician prescription. Frankfurt has multiple medical cannabis specialist practices. Health insurers provide reimbursement for approved indications.',
'Hessian physicians prescribe under the federal framework. The Landesärztekammer Hessen has issued relevant guidance. Frankfurt''s international healthcare institutions are familiar with global medical cannabis standards.',
'Hesse''s cannabis market benefits from Frankfurt''s economic activity and international population. Cannabis Social Clubs are operating in Frankfurt and other cities. Medical cannabis prescribing is growing. Frankfurt''s airport status creates specific enforcement considerations for international travelers.',
'Hesse is expected to take a pragmatic approach to Phase 2 commercial pilot dispensary participation given the SPD component of the coalition. Frankfurt is likely to be among Germany''s Phase 2 pilot cities.',
'Hessisches Ministerium für Arbeit, Integration, Jugend und Soziales (Hesse Ministry of Labour and Health) oversees pharmaceutical regulation. Hessische Polizei enforces CanG.',
'German CanG; Hesse Ministry of Health guidance; Cannabis Social Club licensing data Hesse; BFARM medical cannabis statistics','Current as of Q2 2026','Quarterly','Land briefing covering Frankfurt-centric market under CDU-SPD coalition CanG implementation',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='DE' AND state_iso2='DE-HE');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'lower-saxony','state','DE','DE-NI','Adult-Use (Federal CanG); Medical Legal',
'Lower Saxony (Niedersachsen) is a large northern German Land with approximately 8.1 million residents, governed by an SPD-Green coalition. Hannover is the state capital. The SPD-Green coalition has taken a cooperative approach to CanG implementation, facilitating Cannabis Social Club licensing and expressing support for Phase 2 commercial pilot participation. The state has a significant agricultural sector relevant to potential hemp and cannabis cultivation.',
'Medical patients access pharmacy-dispensed cannabis throughout Lower Saxony via physician prescription. Hannover has medical cannabis specialist practices. Health insurers provide reimbursement for approved indications.',
'Lower Saxony physicians prescribe under the federal framework. The Ärztekammer Niedersachsen has issued supportive guidance for evidence-based prescribing.',
'Lower Saxony''s SPD-Green coalition has created a supportive environment for Cannabis Social Club development. Hannover and other cities have clubs under operation or licensing. Medical cannabis prescribing is established. Agricultural interests in hemp are relevant to future cultivation licensing.',
'Lower Saxony is expected to participate actively in Phase 2 commercial dispensary pilots given the SPD-Green coalition''s supportive posture. Hannover is a likely pilot city.',
'Niedersächsisches Ministerium für Soziales, Arbeit, Gesundheit und Gleichstellung (Hanover, Lower Saxony Ministry of Health) oversees pharmaceutical regulation. Niedersächsische Polizei enforces CanG.',
'German CanG; Lower Saxony Ministry of Health guidance; Cannabis Social Club licensing data; BFARM medical cannabis statistics','Current as of Q2 2026','Quarterly','Land briefing covering SPD-Green supportive CanG implementation',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='DE' AND state_iso2='DE-NI');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'mecklenburg-vorpommern','state','DE','DE-MV','Adult-Use (Federal CanG); Medical Legal',
'Mecklenburg-Vorpommern is a northeastern German Land with approximately 1.6 million residents, governed by an SPD-Left coalition. The state is one of Germany''s less densely populated Länder with significant rural areas and the Baltic Sea coast. The SPD-led government has taken a cooperative approach to CanG implementation. Cannabis Social Club licensing is proceeding. The state''s smaller urban centers (Schwerin, Rostock) have developing medical cannabis markets.',
'Medical patients access pharmacy-dispensed cannabis throughout Mecklenburg-Vorpommern via physician prescription. Rostock and Schwerin have medical cannabis prescribing practices. Health insurers provide reimbursement for approved indications.',
'MV physicians prescribe under the federal framework. The Landesärztekammer Mecklenburg-Vorpommern provides relevant guidance.',
'Mecklenburg-Vorpommern has a smaller cannabis market proportional to population. Cannabis Social Club licensing is proceeding in Rostock and Schwerin. Medical cannabis prescribing is growing from a lower base than in major urban Länder. The Baltic Sea coast''s tourism sector creates some seasonal demand dynamics.',
'The SPD-Left coalition is expected to support Phase 2 commercial dispensary participation. Tourism-related demand dynamics in coastal resort areas may create specific regulatory considerations.',
'Ministerium für Wirtschaft, Infrastruktur, Tourismus und Arbeit Mecklenburg-Vorpommern and Ministerium für Soziales und Gesundheit (Ministry of Social Affairs and Health) oversee pharmaceutical regulation. Landespolizei enforces CanG.',
'German CanG; MV Ministry of Health guidance; Cannabis Social Club licensing data MV; BFARM medical cannabis statistics','Current as of Q2 2026','Annual','Land briefing covering CanG implementation in rural northeastern context',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='DE' AND state_iso2='DE-MV');
