-- Research batch 15 of jurisdiction_playbooks: Denmark, Faroe Islands, Fiji, Finland.
-- Denmark was skipped in the earlier alphabetical pass (sits between DRC and
-- Djibouti) and is caught up here. Real, sourced content replacing draft stubs.

INSERT INTO public.source_registry (source_name, source_url, country, iso, region, tier, adapter, crawl_cadence, source_type, notes)
VALUES
  ('LegalClarity — Is Cannabis Legal in Denmark', 'https://legalclarity.org/is-cannabis-legal-in-denmark-the-law-explained/', 'Denmark', 'DK', 'Europe', 2, 'html_snapshot', 'monthly', 'legal_analysis', 'Euphoriant Substances Act, 2026 reimbursement figures, four prescribing frameworks'),
  ('Business of Cannabis — Denmark Legalises Medical Cannabis Permanently', 'https://businessofcannabis.com/denmark-legalises-medical-cannabis-permanently-but-ludicrous-subsidy-gap-remains/', 'Denmark', 'DK', 'Europe', 2, 'html_snapshot', 'monthly', 'trade_press', 'Bill L135 detail, four distinct prescribing frameworks, reimbursement system criticism'),
  ('Herb.co — How to Buy Weed in Denmark 2026', 'https://herb.co/city-guides/buy-weed-denmark', 'Denmark', 'DK', 'Europe', 2, 'html_snapshot', 'monthly', 'trade_press', 'Christiania closure 2024, enhanced penalty zone, 30-day medical import limit'),
  ('Leafwell — Is Marijuana Legal in the Faeroe Islands', 'https://leafwell.com/blog/is-marijuana-legal-in-the-faeroe-islands', 'Faroe Islands', 'FO', 'Europe', 2, 'html_snapshot', 'quarterly', 'legal_analysis', '11-product list, no flower, no MMJ cards, cultivation ban'),
  ('Local.fo — Faroe cannabis enforcement and Cannabis Party context', 'https://local.fo/faroe-coppers-carry-out-huge-cannabis-operation-in-torshavn-meanwhile-cannabis-party-all-but-announces-it-will-run-for-parliament/', 'Faroe Islands', 'FO', 'Europe', 2, 'html_snapshot', 'quarterly', 'news', 'Local enforcement posture, political reform movement context'),
  ('Blimburn Seeds — Is Weed Legal in Fiji', 'https://blimburnseeds.com/blog/news-and-law/is-weed-legal-in-fiji/', 'Fiji', 'FJ', 'Oceania', 2, 'html_snapshot', 'quarterly', 'legal_analysis', '2022 industrial hemp exception, 2024 medical-export policy framework'),
  ('Leafwell — Is Marijuana Legal in Fiji', 'https://leafwell.com/blog/is-marijuana-legal-in-fiji', 'Fiji', 'FJ', 'Oceania', 2, 'html_snapshot', 'quarterly', 'legal_analysis', 'August 2022 hemp Schedule 1 removal detail, named political advocates'),
  ('GanjaVacations — How to Buy Weed in Fiji 2026', 'https://www.ganjavacations.net/how-to-buy-weed-in-fiji-cannabis-laws-penalties-2026/', 'Fiji', 'FJ', 'Oceania', 2, 'html_snapshot', 'monthly', 'trade_press', 'Illicit Drugs Control Act 2004 confirmation, no legal grey zones for visitors'),
  ('CannabisRegulations.ai — Finland marijuana', 'https://www.cannabisregulations.ai/country-legality/finland-marijuana', 'Finland', 'FI', 'Europe', 2, 'html_snapshot', 'monthly', 'legal_analysis', 'Huumausainelaki 373/2008, Fimea special-permit process, Tulli import enforcement'),
  ('CannaInsider — Is Marijuana Legal in Finland (May 2026)', 'https://cannainsider.com/articles/is-weed-legal-in-finland/', 'Finland', 'FI', 'Europe', 2, 'html_snapshot', 'monthly', 'legal_analysis', '2026 parliamentary rejection of legalization proposal by large margin'),
  ('Cannigma — Cannabis Laws in Finland', 'https://cannigma.com/regulation/cannabis-laws-finland/', 'Finland', 'FI', 'Europe', 2, 'html_snapshot', 'quarterly', 'reference', '2019 citizens'' initiative, Green League party program detail')
ON CONFLICT DO NOTHING;

UPDATE public.jurisdiction_playbooks SET
  difficulty = 'moderate', typical_timeline_months = 12,
  estimated_cost_range = 'Licensing for cultivation/production/import/distribution under the permanent program runs through the Danish Medicines Agency. Patient reimbursement: state covers 50% of costs up to DKK 20,000 (~€2,700) per 12-month period (100% for terminally ill), so patients pay up to DKK 10,000 out of pocket before the subsidy caps out.',
  legal_framework_summary = 'Recreational cannabis is illegal in Denmark under the Euphoriant Substances Act (1955, amended), applying equally to residents and visitors; possession alone can bring fines (commonly 2,000+ DKK) or jail time. Denmark operates one of Europe''s most developed medical cannabis frameworks: a pilot program launched January 2018 became a permanent legislative framework on January 1, 2026 under Bill L135, formally adopted by parliament in April 2025. Under the permanent program, any doctor (not just specialists) may prescribe medical cannabis for any condition they judge appropriate, across four distinct frameworks: fully authorized pharmaceutical products (Sativex, Epidyolex), pilot-programme-approved products (like Stenocare''s oil range), unlicensed special-dispensation products (Nabilone, Marinol), and custom pharmacy-compounded magistral products. Roughly 1,800 patients received treatment annually with about 20,000 prescriptions filled since 2018. Christiania''s historically tolerated open cannabis market (Pusher Street) was dismantled in 2024 amid gang violence, and Copenhagen Police created an enhanced-penalty zone around the area from January 2024. CBD is legal under a 0.2% THC threshold for cosmetics/food-adjacent products, but the Danish Medicines Agency treats the only legal ingestible CBD products as prescription-only.',
  steps = '[{"step":"Medical cannabis licensing route","detail":"Apply to the Danish Medicines Agency for cultivation, production, import, or distribution authorization under the permanent program (Bill L135, effective Jan 1 2026); product can be domestically grown or imported as finished product"},{"step":"Understand the four prescribing frameworks","detail":"Authorized pharma products (Sativex, Epidyolex) have the strongest evidence base; pilot-programme and unlicensed/magistral routes offer broader but less-established options depending on patient need"},{"step":"Do not plan around Christiania or informal retail","detail":"Pusher Street''s open cannabis market was permanently dismantled in 2024, and an enhanced-penalty zone has applied in the area since January 2024"}]'::jsonb,
  key_regulators = '["Danish Medicines Agency (Lægemiddelstyrelsen) — licensing, prescribing guidance, Central Reimbursement Register","Danish Patient Safety Authority — driving-impairment criteria","Ministry of the Interior and Health","Copenhagen Police (Christiania enforcement zone)"]'::jsonb,
  common_pitfalls = ARRAY[
    'Assuming Christiania still offers a workable tourist cannabis-buying route — Pusher Street''s open market was permanently dismantled in 2024 and an enhanced-penalty zone has applied since January 2024',
    'Assuming the reimbursement system is straightforward — a widely criticized imbalance has concentrated an outsized share of the ~85% government reimbursement rate at a single pharmacy, a structural issue the permanent law carried over from the pilot largely unchanged',
    'Assuming any CBD product is a casual loophole — the Danish Medicines Agency treats the only legal ingestible CBD products as prescription-only, distinct from cosmetic/technical CBD'
  ],
  status = 'published', last_reviewed = CURRENT_DATE,
  confidence_label = 'high — extensively corroborated across the Danish Medicines Agency-sourced reporting, multiple trade-press outlets, and a licensed operator (Stenocare) directly engaged in the legislative process',
  last_verified_at = now(),
  source_id = (SELECT id FROM public.source_registry WHERE source_url = 'https://legalclarity.org/is-cannabis-legal-in-denmark-the-law-explained/')
WHERE country_iso2 = 'DK';

UPDATE public.jurisdiction_playbooks SET
  difficulty = 'high', typical_timeline_months = 18,
  estimated_cost_range = 'No licensing pathway for cultivation exists (illegal for both medical and recreational purposes). Medical access is limited to 11 pre-approved imported products dispensed by prescription; costs are patient-borne with no equivalent to Denmark''s reimbursement structure identified in available sources.',
  legal_framework_summary = 'Recreational cannabis use is "completely forbidden" under the Faroese Policy on Alcohol and Drugs, which explicitly aims to keep the islands drug-free. Medical cannabis is legal but far narrower than in Denmark (of which the Faroe Islands is a self-governing part): only 11 specific cannabis-based products are approved for prescription, none of which include raw flower or buds, and the Faroes do not use medical marijuana cards. A doctor''s prescription is required, granted only as a last-resort option after other treatments have failed, and cultivation is illegal even for approved medical patients — patients cannot grow their own supply under any circumstance. There is no indication the Faroe Islands will adopt Denmark''s broader pilot-turned-permanent medical program; a local "Cannabis Party" campaign has pushed for legalization (medical first, recreational eventually) but has not achieved parliamentary representation, and police enforcement (including proactive night patrols in areas known for cannabis use) remains active.',
  steps = '[{"step":"Narrow medical route only","detail":"A doctor may prescribe from a fixed list of 11 approved cannabis-based products (no flower) as a last-resort treatment after other options have failed; no MMJ card system exists"},{"step":"Do not plan around cultivation","detail":"Growing cannabis is illegal in the Faroe Islands for both medical and recreational purposes, with no exception for approved patients"}]'::jsonb,
  key_regulators = '["Faroese Ministry of Health","Faroe Islands Police","Faroese pharmacies (limited to the 11-product approved list)"]'::jsonb,
  common_pitfalls = ARRAY[
    'Assuming Denmark''s broader medical cannabis program (including the 2026 permanent framework) extends to the Faroe Islands — the Faroes maintain a distinct, much narrower 11-product list with no flower and no MMJ cards',
    'Assuming any home cultivation is possible for medical patients — cultivation is banned outright regardless of prescription status',
    'Assuming political reform is imminent — a local Cannabis Party campaign exists but has not achieved parliamentary representation, and police enforcement remains active'
  ],
  status = 'published', last_reviewed = CURRENT_DATE,
  confidence_label = 'high — consistently corroborated across Leafwell''s detailed program description and independent local news on enforcement posture and political context',
  last_verified_at = now(),
  source_id = (SELECT id FROM public.source_registry WHERE source_url = 'https://leafwell.com/blog/is-marijuana-legal-in-the-faeroe-islands')
WHERE country_iso2 = 'FO';

UPDATE public.jurisdiction_playbooks SET
  difficulty = 'high', typical_timeline_months = 18,
  estimated_cost_range = 'Industrial hemp (under 1% THC) was removed from Schedule 1 of the Illicit Drugs Control Act in August 2022, permitting import, possession, cultivation, sale, and supply — standard agricultural licensing costs apply, no unusual barrier identified. General cannabis cultivation/sale for any THC-bearing product remains illegal with no licensing pathway.',
  legal_framework_summary = 'Cannabis is classified as a prohibited/dangerous drug under the Fiji Illicit Drugs Control Act 2004, with possession, cultivation, and distribution all criminal offenses; possession can carry imprisonment (some sources cite up to 20 years depending on quantity and criminal history, others describe shorter terms for smaller amounts). There is no domestic medical cannabis program, though registered pharmacists are nominally permitted to manufacture extracts/tinctures of "Indian hemp" under older statutory language — a provision no other source confirms is actively used. A significant carve-out exists for industrial hemp: in August 2022, Fiji''s parliament removed hemp (defined as cannabis containing less than 1% THC) from Schedule 1 of the Illicit Drugs Control Act, legalizing its importation, possession, cultivation, sale, and supply — a move championed by MPs seeking an alternative industry to Fiji''s declining sugar sector. In 2024, the government separately endorsed a policy framework to investigate the potential export of medical cannabis, though domestic medical use remains off the table and this remains at the investigative-policy stage rather than an operative licensing regime. Despite legal risk, cannabis remains widely available through Fiji''s black market and is a significant illicit export via inter-island trafficking routes.',
  steps = '[{"step":"Industrial hemp route","detail":"Import, cultivate, sell, or supply hemp (under 1% THC) under the August 2022 Schedule 1 removal — this is the only currently operative legal cannabis-adjacent pathway"},{"step":"Monitor the medical-export policy framework","detail":"Track development of the 2024-endorsed policy framework investigating medical cannabis export; as of the most recent reporting this remains investigative, not an operative license regime, and domestic medical use is explicitly excluded"}]'::jsonb,
  key_regulators = '["Fiji Police Force (Illicit Drugs Control Act enforcement)","Ministry of Health (nominal pharmacist extract-manufacturing provision)","Ministry responsible for the 2024 medical-cannabis-export policy framework"]'::jsonb,
  common_pitfalls = ARRAY[
    'Assuming the 2022 industrial hemp exception or 2024 medical-export policy discussion means general cannabis is legal — recreational and general medical cannabis (THC-bearing) remain fully illegal with active police enforcement',
    'Assuming the 2024 medical-export policy framework is an operative licensing regime — available sources describe it as investigative/exploratory, not yet a functioning program, and domestic medical use remains excluded entirely',
    'Assuming Rastafari cultural presence signals legal tolerance — recreational marijuana use is not legally permitted regardless of religious or cultural context'
  ],
  status = 'published', last_reviewed = CURRENT_DATE,
  confidence_label = 'high — well corroborated across multiple independent legal-analysis sources with consistent detail on the August 2022 hemp exception and named political advocates',
  last_verified_at = now(),
  source_id = (SELECT id FROM public.source_registry WHERE source_url = 'https://leafwell.com/blog/is-marijuana-legal-in-fiji')
WHERE country_iso2 = 'FJ';

UPDATE public.jurisdiction_playbooks SET
  difficulty = 'high', typical_timeline_months = 18,
  estimated_cost_range = 'No licensing pathway for cultivation exists (illegal). Medical access requires a Fimea special permit (erityislupa) applied for by a physician on behalf of an individual patient — not a scalable commercial channel. CBD/hemp: standard EU agricultural compliance costs for cultivation under the 0.2% THC limit; ingestible CBD products face EU Novel Food authorization costs with no product yet approved.',
  legal_framework_summary = 'Recreational cannabis is illegal in Finland under the Narcotics Act (Huumausainelaki 373/2008) and Chapter 50 of the Penal Code, which transpose UN Single Convention scheduling into domestic law; a basic narcotics offense carries up to 2 years imprisonment and an aggravated offense up to 10 years, though police/prosecutors retain discretion to waive charges (day-fines) for small personal-use amounts. Medical cannabis has been available since 2008 through Fimea (the Finnish Medicines Agency), which issues case-by-case special permits (erityislupa) under Section 21f of the Medicines Act after a physician certifies standard therapies have failed; uptake remains very small (roughly 250-500 patients), with Sativex the only product holding full Finnish marketing authorization and Bedrocan/Bediol/Bedica imported from the Netherlands via special permit accounting for most other dispensed product. CBD sits in a narrow, EU-Novel-Food-constrained lane: pure CBD is not itself scheduled as a narcotic, but Fimea has held since 2019 (reaffirmed 2022) that any CBD product marketed with health claims requires pharmaceutical marketing authorization, and no ingestible CBD product has completed EU Novel Food authorization, so Finnish authorities consider such products non-marketable; hemp cultivation under 0.2% THC is legal for industrial/cosmetic purposes. As recently as 2026, Finnish lawmakers rejected the latest citizen-initiated legalization proposal by a large margin, continuing a pattern (a 2019 decriminalization petition with ~59,600 signatures also did not result in legislative change), even as the Green League party has included cannabis legalization/regulation in its official program since 2021.',
  steps = '[{"step":"Industrial hemp/CBD route","detail":"Cultivate under 0.2% THC for industrial/cosmetic use; avoid health claims on CBD products, since Fimea treats health-claim CBD as requiring pharmaceutical marketing authorization; do not market ingestible CBD without EU Novel Food clearance, which no product has yet obtained"},{"step":"Medical cannabis route (narrow)","detail":"A physician applies to Fimea for a case-by-case special permit after documenting that standard therapies have failed; most product beyond Sativex is imported from the Netherlands via the Office for Medicinal Cannabis"}]'::jsonb,
  key_regulators = '["Finnish Medicines Agency (Fimea) — special permits, CBD health-claim enforcement","Tulli (Finnish Customs) — active narcotics-import interdiction, including mail-order seizures","Valvira and Ruokavirasto — food/novel-food oversight for CBD products","Finnish police and prosecutors (Chapter 50 Penal Code enforcement)"]'::jsonb,
  common_pitfalls = ARRAY[
    'Relying on a fabricated claim of "licensed dispensaries open to adults 21+" citing the US 2018 Farm Bill — this appeared in one low-quality templated source and is nonsensical for Finland (a US federal law has no bearing on Finnish law); no dispensaries or adult-use market exist',
    'Assuming CBD products are broadly legal for ingestion — Fimea treats health-claim CBD as requiring drug marketing authorization, and no ingestible CBD product has completed EU Novel Food authorization, making such products effectively non-marketable',
    'Assuming the 2026 legalization proposal''s parliamentary rejection signals settled policy — citizen-initiative pressure and Green League party advocacy continue, so monitor for renewed legislative activity'
  ],
  status = 'published', last_reviewed = CURRENT_DATE,
  confidence_label = 'high — extensively corroborated across Wikipedia, Fimea-referencing legal-analysis sources, and a May 2026-dated source confirming the recent parliamentary rejection; one fabricated low-quality source was identified and discarded',
  last_verified_at = now(),
  source_id = (SELECT id FROM public.source_registry WHERE source_url = 'https://www.cannabisregulations.ai/country-legality/finland-marijuana')
WHERE country_iso2 = 'FI';

UPDATE public.jurisdiction_playbooks_research_queue
SET playbook_status = 'published', last_researched_at = now(), last_researched_by = 'claude-agent'
WHERE country_code IN ('DK','FO','FJ','FI');
