
-- Germany Länder batch B: BB RP SL SN ST SH TH (Brandenburg through Thuringia)

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'brandenburg','state','DE','DE-BB','Adult-Use (Federal CanG); Medical Legal',
'Brandenburg surrounds Berlin and has approximately 2.6 million residents, governed by an SPD-CDU coalition. The state''s proximity to Berlin creates significant cross-border cannabis market dynamics, with Brandenburg residents accessing Berlin''s more developed Cannabis Social Club ecosystem. Potsdam is the state capital. Brandenburg''s largely rural character and flat plains distinguish its market from major urban Länder.',
'Medical patients access pharmacy-dispensed cannabis via physician prescription. Potsdam and Brandenburg an der Havel have medical cannabis prescribing practices. Berlin proximity gives Brandenburg residents easy access to a wider clinical ecosystem.',
'Brandenburg physicians prescribe under the federal framework. The Landesärztekammer Brandenburg provides relevant guidance.',
'Brandenburg''s cannabis market is closely linked to Berlin''s given geographic proximity. Cannabis Social Clubs in Potsdam and other towns supplement Berlin club access for Brandenburg residents. Medical prescribing is developing.',
'Brandenburg is expected to implement CanG cooperatively. Berlin''s Phase 2 commercial dispensary program, if successful, will directly influence Brandenburg consumer patterns given the state''s encirclement of Berlin.',
'Ministerium für Soziales, Gesundheit, Integration und Verbraucherschutz Brandenburg (Ministry of Social Affairs and Health) oversees pharmaceutical regulation. Polizei Brandenburg enforces CanG.',
'German CanG; Brandenburg Ministry of Health guidance; Cannabis Social Club licensing data; BFARM medical cannabis statistics','Current as of Q2 2026','Annual','Land briefing covering Berlin-adjacent market dynamics',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='DE' AND state_iso2='DE-BB');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'rhineland-palatinate','state','DE','DE-RP','Adult-Use (Federal CanG); Medical Legal',
'Rhineland-Palatinate (Rheinland-Pfalz) has approximately 4.1 million residents and is governed by an SPD-Green-FDP coalition — the coalition that originally advanced the federal CanG at national level. Mainz is the state capital. The state has strongly supportive leadership for cannabis reform, with significant political ownership of the CanG legislation. Wine-growing culture and proximity to France, Luxembourg, and Belgium give the state a liberal orientation toward regulatory reform.',
'Medical patients access pharmacy-dispensed cannabis throughout the state via physician prescription. Mainz and Kaiserslautern have medical cannabis specialist practices. Health insurers provide reimbursement for approved indications.',
'Rhineland-Palatinate physicians prescribe under the federal framework. The Landesärztekammer Rheinland-Pfalz has issued supportive guidance.',
'Rhineland-Palatinate has a politically supportive environment for cannabis development. Cannabis Social Clubs are active in major cities. Medical cannabis prescribing is growing. Cross-border dynamics with Luxembourg (adult-use home cultivation legal) and France are relevant.',
'Given RLP''s SPD-Green-FDP coalition — the original architects of CanG — the state is positioned as one of Germany''s most active Phase 2 commercial dispensary participants. Mainz is a likely pilot city.',
'Ministerium für Wissenschaft und Gesundheit Rheinland-Pfalz (RLP Ministry of Science and Health) oversees pharmaceutical regulation. Polizei RLP enforces CanG.',
'German CanG; RLP Ministry of Health guidance; Cannabis Social Club licensing data RLP; BFARM medical cannabis statistics; RLP cannabis policy documentation','Current as of Q2 2026','Quarterly','Land briefing covering CanG''s politically home state and progressive implementation',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='DE' AND state_iso2='DE-RP');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'saarland','state','DE','DE-SL','Adult-Use (Federal CanG); Medical Legal',
'Saarland is Germany''s smallest Land by area (excluding city-states) with approximately 980,000 residents, governed by a CDU-led coalition. It borders France and Luxembourg, creating unique cross-border cannabis market dynamics — Luxembourg''s home cultivation legalization and proximity to French consumer patterns influence the Saarland market. Saarbrücken is the state capital. The CDU-led government has taken a moderate approach to CanG implementation.',
'Medical patients access pharmacy-dispensed cannabis via physician prescription. Saarbrücken has medical cannabis prescribing practices. Cross-border access to Luxembourg''s legal home cultivation framework creates informational cross-pollination.',
'Saarland physicians prescribe under the federal framework. The Ärztekammer des Saarlandes provides relevant guidance.',
'Saarland''s cannabis market is small but influenced by its borders with Luxembourg and France. Cannabis Social Club licensing is proceeding. Cross-border market dynamics with Luxembourg are notable.',
'Saarland''s CDU government will implement CanG moderately. Cross-border dynamics with Luxembourg may create some pressure for pragmatic enforcement given resident cross-border behaviors.',
'Ministerium für Arbeit, Soziales, Frauen und Gesundheit Saarland (Ministry of Labour, Social Affairs, Women and Health) oversees pharmaceutical regulation. Saarländische Polizei enforces CanG.',
'German CanG; Saarland Ministry of Health guidance; Cannabis Social Club licensing data; BFARM medical cannabis statistics; Luxembourg cross-border dynamics','Current as of Q2 2026','Annual','Land briefing covering small cross-border market adjacent to Luxembourg',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='DE' AND state_iso2='DE-SL');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'saxony','state','DE','DE-SN','Adult-Use (Federal CanG); Medical Legal; Variable Enforcement',
'Saxony (Sachsen) has approximately 4 million residents and is governed by a CDU-SPD-Green coalition. Leipzig and Dresden are the major cities with distinct cannabis market profiles. Dresden has seen high-profile enforcement operations against informal markets since CanG implementation. Leipzig, with a younger population and more liberal culture, has developed a more active Cannabis Social Club ecosystem. The CDU component of the coalition creates some tension with progressive implementation.',
'Medical patients access pharmacy-dispensed cannabis via physician prescription. Leipzig and Dresden have medical cannabis specialist practices. Health insurers provide reimbursement for approved indications.',
'Saxony physicians prescribe under the federal framework. The Sächsische Landesärztekammer provides relevant guidance.',
'Saxony''s cannabis market varies significantly between Dresden (more enforcement-focused) and Leipzig (more progressive CSC ecosystem). Medical prescribing is growing across the state. Cannabis Social Clubs in Leipzig are among the more active in eastern Germany.',
'Saxony''s CDU-led enforcement approach creates variable implementation. Leipzig is likely to be a strong Phase 2 commercial dispensary candidate given its demographics and political culture.',
'Sächsisches Staatsministerium für Soziales und Gesellschaftlichen Zusammenhalt (Saxon State Ministry for Social Affairs) oversees pharmaceutical regulation. Polizei Sachsen enforces CanG.',
'German CanG; Saxony Ministry of Health guidance; Cannabis Social Club licensing data Saxony; BFARM medical cannabis statistics; Dresden/Leipzig enforcement comparison','Current as of Q2 2026','Quarterly','Land briefing covering variable Dresden/Leipzig enforcement and market dynamics',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='DE' AND state_iso2='DE-SN');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'saxony-anhalt','state','DE','DE-ST','Adult-Use (Federal CanG); Medical Legal',
'Saxony-Anhalt has approximately 2.1 million residents and is governed by a CDU-SPD-FDP coalition. Halle and Magdeburg are the major cities. The CDU-led government has taken a moderate approach to CanG implementation. Saxony-Anhalt is one of the less economically dynamic eastern German Länder, with demographic and economic challenges relevant to market development.',
'Medical patients access pharmacy-dispensed cannabis via physician prescription. Halle and Magdeburg have medical cannabis prescribing practices.',
'Saxony-Anhalt physicians prescribe under the federal framework. The Ärztekammer Sachsen-Anhalt provides relevant guidance.',
'Saxony-Anhalt''s cannabis market is developing. Cannabis Social Club licensing is proceeding. Medical prescribing is growing from a lower base.',
'Saxony-Anhalt is expected to implement CanG moderately. Phase 2 commercial dispensary participation is possible through Halle or Magdeburg.',
'Ministerium für Arbeit, Soziales, Gesundheit und Gleichstellung Sachsen-Anhalt (Ministry of Labour, Social Affairs, Health and Equality) oversees pharmaceutical regulation. Polizei Sachsen-Anhalt enforces CanG.',
'German CanG; Saxony-Anhalt Ministry of Health guidance; Cannabis Social Club licensing data; BFARM medical cannabis statistics','Current as of Q2 2026','Annual','Land briefing covering CanG implementation in eastern German context',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='DE' AND state_iso2='DE-ST');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'schleswig-holstein','state','DE','DE-SH','Adult-Use (Federal CanG); Medical Legal',
'Schleswig-Holstein is a northern German Land bordering Denmark, with approximately 2.9 million residents, governed by a CDU-led government. Kiel is the state capital, and Lübeck and Flensburg are notable cities. The Danish border creates cross-border market dynamics — Denmark has an established medical cannabis pilot program. The CDU government has taken a moderate approach to CanG implementation, with Cannabis Social Club licensing proceeding.',
'Medical patients access pharmacy-dispensed cannabis via physician prescription. Kiel, Lübeck, and Flensburg have medical cannabis prescribing practices. Cross-border dynamics with Denmark''s medical program are relevant for patients near the Danish border.',
'Schleswig-Holstein physicians prescribe under the federal framework. The Ärztekammer Schleswig-Holstein provides relevant guidance.',
'Schleswig-Holstein''s cannabis market benefits from its urban centers and border dynamics with Denmark. Cannabis Social Clubs are being licensed. Medical prescribing is growing.',
'The CDU government is expected to implement CanG moderately. Border dynamics with Denmark and proximity to Hamburg''s more progressive ecosystem will influence market development.',
'Ministerium für Soziales, Gesundheit, Jugend, Familie und Senioren Schleswig-Holstein (Ministry of Social Affairs and Health) oversees pharmaceutical regulation. Polizei Schleswig-Holstein enforces CanG.',
'German CanG; Schleswig-Holstein Ministry of Health guidance; Cannabis Social Club licensing data; BFARM medical cannabis statistics; Denmark border dynamics','Current as of Q2 2026','Annual','Land briefing covering CanG implementation with Denmark border dynamics',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='DE' AND state_iso2='DE-SH');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'thuringia','state','DE','DE-TH','Adult-Use (Federal CanG); Medical Legal',
'Thuringia (Thüringen) has approximately 2.1 million residents, governed by an SPD-BSW-CDU coalition following complex 2024 state elections. Erfurt is the state capital. The complex coalition dynamics have created some uncertainty in state-level CanG implementation. Thuringia is a centrally located Land with connections to Bavaria, Saxony, and Hessen. Medical cannabis prescribing has developed in Erfurt and other cities.',
'Medical patients access pharmacy-dispensed cannabis via physician prescription. Erfurt has medical cannabis prescribing practices. Health insurers provide reimbursement for approved indications.',
'Thuringia physicians prescribe under the federal framework. The Landesärztekammer Thüringen provides relevant guidance.',
'Thuringia''s cannabis market is developing. Cannabis Social Club licensing is proceeding under the complex coalition government. Medical prescribing is growing.',
'The complex BSW-SPD-CDU coalition creates some uncertainty about the pace of Phase 2 commercial dispensary engagement. Implementation of CanG is expected to continue at a moderate pace.',
'Thüringer Ministerium für Arbeit, Soziales, Gesundheit, Frauen und Familie (Thuringia Ministry of Social Affairs and Health) oversees pharmaceutical regulation. Polizei Thüringen enforces CanG.',
'German CanG; Thuringia Ministry of Health guidance; Cannabis Social Club licensing data TH; BFARM medical cannabis statistics','Current as of Q2 2026','Annual','Land briefing covering CanG implementation under complex coalition government',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='DE' AND state_iso2='DE-TH');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'bremen','state','DE','DE-HB','Adult-Use (Federal CanG); Medical Legal; Progressive Enforcement',
'Bremen is Germany''s smallest Land by population (approximately 680,000), consisting of the cities of Bremen and Bremerhaven, governed by an SPD-Green-Volt coalition — one of Germany''s most progressive state governments. Bremen''s SPD-Green government has been among the most vocal Land-level supporters of cannabis reform. Cannabis Social Club licensing has proceeded quickly in Bremen, and the state has actively pursued Phase 2 commercial dispensary pilot participation.',
'Medical patients access pharmacy-dispensed cannabis via physician prescription. Multiple medical cannabis practices operate in Bremen. Health insurers provide reimbursement for approved indications.',
'Bremen physicians prescribe under the federal framework. The Ärztekammer Bremen has issued supportive guidance.',
'Bremen''s small but progressive market is one of Germany''s most per-capita active Cannabis Social Club locations. Medical prescribing is well-established. The state''s SPD-Green government has been the Land most publicly supportive of cannabis reform.',
'Bremen is expected to be among the first German Länder to operationalize Phase 2 commercial dispensary pilot programs. Its progressive coalition makes it a model Land for monitoring how commercial adult-use dispensaries function in Germany.',
'Senatorin für Gesundheit (Senator for Health, Free Hanseatic City of Bremen) oversees pharmaceutical regulation. Polizei Bremen enforces CanG.',
'German CanG; Bremen Senate Health guidance; Cannabis Social Club licensing data Bremen; BFARM medical cannabis statistics; Phase 2 pilot dispensary documentation','Current as of Q2 2026; verified against Bremen Senate Health guidance','Quarterly','City-state briefing covering Germany''s most progressive Land-level CanG implementation',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='DE' AND state_iso2='DE-HB');
