INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'puerto-rico','state','US','US-PR','Medical Legal',
'Puerto Rico is an unincorporated US territory with significant self-governance. Medical cannabis has been legal in Puerto Rico since 2015 under Executive Order OE-2015-10 (signed by Governor García Padilla), subsequently codified into Act 42-2017 (the Puerto Rico Medical Cannabis Act). Adults with qualifying conditions may obtain medical cannabis cards and purchase from licensed dispensaries. A dispensary network of approximately 120–150 licensed dispensaries operated across the island as of mid-2026. Personal possession limits and cultivation rules follow the regulatory framework established by the Department of Health. Federal cannabis prohibition (CSA) technically applies but federal enforcement in the medical context has been consistent with Cole Memo-era non-intervention policy.',
'Puerto Rico patients access medical cannabis through licensed dispensaries upon obtaining a medical cannabis card from a registered physician. Qualifying conditions include cancer, HIV/AIDS, PTSD, chronic pain, multiple sclerosis, Parkinson''s disease, and over 20 other conditions. Online pre-ordering and curbside pickup are available at many dispensaries. Card holders may possess up to 2.5 ounces (71g) per 14-day period.',
'Puerto Rico-licensed physicians may recommend medical cannabis to patients with qualifying conditions after a medical consultation. Physicians must register with the Department of Health''s SIMETRIA system. The medical cannabis recommendation is not a prescription in the DEA sense but a physician recommendation under territorial law. Telehealth recommendations are available.',
'Puerto Rico''s medical cannabis market has grown substantially since 2015. The dispensary sector generates approximately $300–400M USD annually. Tourism interest in Puerto Rico''s cannabis program has increased following adult-use legalisation in the continental US. Several mainland US cannabis companies have entered the Puerto Rico market. Local cultivators and processors operate under Department of Health licensing.',
'Puerto Rico''s medical-only framework is stable. The Legislative Assembly has debated adult-use legalisation but has not enacted it as of mid-2026. Federal rescheduling of cannabis (if it occurs at the federal level) would significantly affect Puerto Rico''s framework given its territorial relationship with the US federal government. Congressional representation considerations are relevant to any federal reclassification.',
'Puerto Rico Department of Health (Departamento de Salud) — Cannabis Medicinal Division; Puerto Rico Police Bureau (PRPB) for enforcement',
'Puerto Rico Department of Health SIMETRIA system data; Act 42-2017 and amendments; dispensary licence registry',
'Current as of Q2 2026; verified against Puerto Rico Department of Health official publications',
'Quarterly','Full territory briefing on Puerto Rico''s medical cannabis framework, dispensary market, patient card system, and adult-use legislative outlook',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='US' AND state_iso2='US-PR');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'guam','state','US','US-GU','Medical Legal',
'Guam is an unincorporated US territory in the western Pacific. Medical cannabis has been legal in Guam since the Joaquin "KC" Concepcion II Compassionate Cannabis Use Act of 2014 (Public Law 32-237). The program was operationalised and dispensaries opened in 2019–2020 following rulemaking completion. A small number of licensed dispensaries (approximately 5–10) operate on the island. Qualifying patients may possess up to 2.5 ounces of dried cannabis. Guam has also passed adult-use cannabis legislation (Adult Use Cannabis Safety Act, Bill 213-35) though full adult-use retail implementation was still in progress as of mid-2026.',
'Guam medical cannabis patients access dispensaries with a patient registration card from the Department of Public Health and Social Services (DPHSS). Qualifying conditions include cancer, PTSD, chronic pain, HIV/AIDS, and other serious conditions. Patient numbers are growing but remain modest given the island''s ~160,000 population.',
'Guam-licensed physicians may recommend medical cannabis to patients with qualifying conditions. Physicians must be licensed to practice in Guam. Telehealth recommendations are available for some providers.',
'Guam''s cannabis market is small given its population. The adult-use framework, when fully operational, is expected to expand the market significantly and capture tourism demand from the large Japanese and South Korean tourist base. Several local operators hold both medical and anticipated adult-use licences.',
'Guam is transitioning toward adult-use retail implementation. The DPHSS is developing the regulatory framework for adult-use sales. Japan and South Korea''s strict cannabis prohibition creates reputational sensitivity around cannabis-related tourism in Guam — the territory must balance tourism market development against diplomatic sensitivities.',
'Guam Department of Public Health and Social Services (DPHSS) — Cannabis Control Division; Guam Police Department (GPD) for enforcement',
'DPHSS Cannabis Control Division published data; Guam Legislature cannabis laws; DPHSS patient registry data',
'Current as of Q2 2026; verified against DPHSS official publications and Guam Legislature records',
'Quarterly','Full territory briefing on Guam''s medical cannabis framework, adult-use implementation progress, Japanese/Korean tourism sensitivity, and Pacific regulatory context',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='US' AND state_iso2='US-GU');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'us-virgin-islands','state','US','US-VI','Adult-Use Legal; Medical Legal',
'The US Virgin Islands (USVI) — comprising St. Croix, St. Thomas, and St. John — enacted adult-use cannabis legalisation via the Cannabis Use Act (Act 8279) signed by Governor Albert Bryan Jr. in 2021. The USVI was one of the first US jurisdictions to legalise adult-use cannabis, enabling possession of up to 1 ounce by adults 21+. A licensing framework for retail dispensaries, cultivators, and processors was established through the Virgin Islands Cannabis Advisory Board (VICAB) and the Bureau of Economic Development. Cannabis retail shops began opening in 2023. The USVI also has an active medical cannabis program established in 2019.',
'USVI medical cannabis patients registered under the medical program access dispensaries with a patient card. Medical patients may possess up to 4 ounces — a higher limit than the adult-use 1-ounce possession limit. Medical patients have access to a broader range of products and higher-potency formulations.',
'USVI-licensed physicians may recommend medical cannabis. The USVI Medical Cannabis Patient Protection Act establishes the framework. Telehealth recommendations are available.',
'The USVI adult-use retail market is developing. A small number of licensed adult-use dispensaries operate on St. Thomas and St. Croix as of mid-2026. Tourism demand from the US mainland is a significant market driver — St. Thomas is a major Caribbean cruise destination with approximately 2M+ annual tourists. Revenue potential relative to population (~100,000 residents) is substantial.',
'The USVI adult-use framework is maturing. The VICAB and Bureau of Economic Development continue to issue licences. Federal rescheduling could accelerate market investment. The USVI''s relationship with the US federal government creates the same CSA-federal conflict as the continental states.',
'Virgin Islands Cannabis Advisory Board (VICAB); Bureau of Economic Development (BED); Virgin Islands Police Department (VIPD) for enforcement; Department of Health for medical program',
'VICAB published licence data; BED regulatory publications; USVI Legislature records; Act 8279 (Adult-Use) and Act 7950 (Medical)',
'Current as of Q2 2026; verified against VICAB official publications',
'Quarterly','Full territory briefing on USVI adult-use and medical cannabis frameworks, tourism-driven market dynamics, and federal relationship context',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='US' AND state_iso2='US-VI');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'northern-mariana-islands','state','US','US-MP','Adult-Use Legal; Medical Legal',
'The Commonwealth of the Northern Mariana Islands (CNMI) was the first US jurisdiction — state or territory — to enact adult-use cannabis legalisation, via the CNMI Cannabis Act (Public Law 20-36) signed in September 2018. This predated even Illinois and Michigan''s adult-use legalisation. Adults 21+ may possess up to 1 ounce of cannabis and grow up to 6 plants at home. A licensing framework for cannabis businesses was established. The CNMI also has a medical cannabis programme. The CNMI''s small population (~50,000) and its position as a Pacific island commonwealth (with significant ties to Japan and China tourism) create a unique market context.',
'CNMI medical cannabis patients access registered dispensaries with a patient card issued by the Department of Public Health (DPH). Medical patients have access to higher quantities and a broader product range than adult-use consumers.',
'CNMI-licensed physicians may recommend medical cannabis under the medical programme.',
'The CNMI adult-use market is very small due to the limited resident population. Tourism — primarily from Japan, South Korea, and China — represents a theoretical market driver but cannabis consumption by these tourists is culturally sensitive and legally precarious (cannabis is prohibited in their home countries). Licensed retailers serve primarily local residents. Revenue is modest by US cannabis market standards.',
'The CNMI''s adult-use framework is established and stable. As a pioneering US adult-use jurisdiction, the CNMI has operational experience. Federal rescheduling developments will affect the CNMI on the same timeline as continental states. Japan and Chinese tourism sensitivity remains a consideration for marketing and retail positioning.',
'CNMI Cannabis Licensing Board (CLB); Department of Public Health (DPH); CNMI Department of Public Safety (DPS) for enforcement',
'CNMI CLB published licence data; DPH publications; CNMI Legislature records; Public Law 20-36',
'Current as of Q2 2026; verified against CNMI CLB official publications',
'Quarterly','Full territory briefing on CNMI''s pioneering adult-use status (first US adult-use jurisdiction, 2018), medical programme, small-population market, and Pacific tourism sensitivity',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='US' AND state_iso2='US-MP');

INSERT INTO cc_jurisdiction_briefings (jurisdiction_slug,jurisdiction_type,country_iso2,state_iso2,program_status,public_summary,patient_access,physician_access,market_dynamics,regulatory_outlook,regulatory_body,data_source_summary,verification_summary,update_cadence,coverage_summary,last_reviewed_date,watch_regions,change_notes,review_state)
SELECT 'american-samoa','state','US','US-AS','Prohibited',
'American Samoa is an unincorporated US territory in the South Pacific. Cannabis is prohibited under both US federal law (Controlled Substances Act) and American Samoa territorial law. American Samoa has not enacted medical or adult-use cannabis legislation and has shown no legislative interest in doing so. The territory is governed by a highly conservative sociocultural environment strongly shaped by Samoan fa''asamoa (traditional culture) and Congregationalist/LDS church influence, which is deeply opposed to substance liberalisation. American Samoa is the only US territory that has restricted birthright US citizenship — territorial nationals are US nationals but not automatically citizens, creating a distinct political relationship with Washington.',
'No medical cannabis programme exists in American Samoa. Patients with serious conditions requiring cannabis-based treatments would need to access US mainland frameworks, which is logistically very challenging.',
'American Samoan physicians are not authorised to recommend cannabis under any territorial framework.',
'No cannabis market exists or is contemplated. American Samoa''s geographic isolation, small population (~56,000), conservative culture, and high poverty rates make it effectively irrelevant to commercial cannabis market planning.',
'No cannabis reform is under consideration. American Samoa''s traditional governance structures (including Matai chieftain system) and church influence create strong institutional resistance to any substance liberalisation. Federal rescheduling would not automatically create a territorial medical programme.',
'American Samoa Department of Health; Department of Public Safety (DPS) for enforcement',
'American Samoa Government health publications; US federal CSA for law reference',
'Current as of Q2 2026',
'Annually','Territory briefing on American Samoa''s full prohibition status, fa''asamoa cultural context, conservative institutional resistance to reform, and absence of any cannabis market',DATE '2026-06-22','[]'::jsonb,'[]'::jsonb,'reviewed'
WHERE NOT EXISTS (SELECT 1 FROM cc_jurisdiction_briefings WHERE country_iso2='US' AND state_iso2='US-AS');
