-- Replay-only relation foundation for the production _claude_push_staging table.
--
-- The production table is referenced by the recovered security-hardening migration,
-- but no canonical CREATE TABLE migration exists in the repository history. The
-- temporary relation is intentionally minimal because this replay only requires
-- the relation to exist for RLS/grant hardening. It is never a production migration
-- or migration-ledger entry.
create table if not exists public._claude_push_staging (
  id bigint generated by default as identity primary key
);
