
insert into public.listings
  (id, category, title, description, product_type, region, price_range, seller_type,
   high_level_specs, status, public_visibility, is_featured, price_amount, price_currency,
   location_country, condition, brand, model, quantity, unit, slug, marketplace_section,
   sold_by_harbourview, sku, stock_qty, lead_time_days, moq, compliance_flags, target_countries,
   created_at, updated_at)
values
(gen_random_uuid(),'packaging','CR Silicone Concentrate Container — 5mL (Opaque)','Child-resistant opaque silicone concentrate container, non-stick interior.','concentrate_packaging','north_america','negotiable','distributor','{"size":"5mL","material":"silicone","cr":true}','approved',true,false,0.32,'CAD','CA','new','Harbourview Supply','HV-CONC-SIL5',1000,'each','cr-silicone-concentrate-container-5ml','packaging',true,'HVP-CNC-SIL',15000,10,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Glass Concentrate Jar — 5mL','Child-resistant glass concentrate jar with CR lid, opaque black.','concentrate_packaging','north_america','negotiable','distributor','{"size":"5mL","material":"glass","cr":true}','approved',true,false,0.48,'CAD','CA','new','Harbourview Supply','HV-CONC-GLS5',1000,'each','cr-glass-concentrate-jar-5ml','packaging',true,'HVP-CNC-GLS',12000,12,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Unbleached Parchment / Wax Paper Squares (Bulk)','Non-stick unbleached parchment squares for concentrate handling and packaging.','concentrate_supply','north_america','negotiable','distributor','{}','approved',true,false,0.02,'CAD','CA','new','Harbourview Supply','HV-PARCH-1',1000,'each','unbleached-parchment-wax-paper-squares','consumables',true,'HVP-CNC-PAR',200000,7,5000,'{}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Tincture Bottle — 30mL Amber Glass w/ Dropper','Child-resistant amber glass tincture bottle with graduated dropper cap.','tincture_packaging','north_america','negotiable','distributor','{"size":"30mL","material":"amber glass","cr":true}','approved',true,true,0.14,'CAD','CA','new','Harbourview Supply','HV-TINC-30',1000,'each','cr-tincture-bottle-30ml-amber-dropper','packaging',true,'HVP-TIN-030',18000,10,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Tincture Bottle — 10mL Amber Glass w/ Dropper','Child-resistant amber glass tincture bottle with graduated dropper cap.','tincture_packaging','north_america','negotiable','distributor','{"size":"10mL","material":"amber glass","cr":true}','approved',true,false,0.11,'CAD','CA','new','Harbourview Supply','HV-TINC-10',1000,'each','cr-tincture-bottle-10ml-amber-dropper','packaging',true,'HVP-TIN-010',20000,10,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Graduated Glass Droppers (Bulk)','Bulk calibrated glass droppers for tincture bottle assembly.','tincture_supply','north_america','negotiable','distributor','{"graduated":true}','approved',true,false,0.06,'CAD','CA','new','Harbourview Supply','HV-DROP-1',1000,'each','graduated-glass-droppers-bulk','consumables',true,'HVP-TIN-DRP',25000,10,1000,'{}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Topical Jar — 50g (Opaque, CR Lid)','Child-resistant opaque jar for topical creams/balms.','topical_packaging','north_america','negotiable','distributor','{"size":"50g","cr":true}','approved',true,false,0.38,'CAD','CA','new','Harbourview Supply','HV-TOP-JAR50',1000,'each','cr-topical-jar-50g','packaging',true,'HVP-TOP-JAR',10000,12,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Topical Stick / Tube (Deodorant-Style)','Child-resistant deodorant-style twist-up tube for topical sticks.','topical_packaging','north_america','negotiable','distributor','{"format":"twist-up stick","cr":true}','approved',true,false,0.42,'CAD','CA','new','Harbourview Supply','HV-TOP-STICK',1000,'each','cr-topical-stick-tube','packaging',true,'HVP-TOP-STK',8000,12,500,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'packaging','CR Topical Pump Bottle — 100mL','Child-resistant pump-top bottle for liquid/lotion topicals.','topical_packaging','north_america','negotiable','distributor','{"size":"100mL","format":"pump","cr":true}','approved',true,false,0.55,'CAD','CA','new','Harbourview Supply','HV-TOP-PUMP100',1000,'each','cr-topical-pump-bottle-100ml','packaging',true,'HVP-TOP-PMP',6000,14,250,'{"CA":{"child_resistant":true,"tamper_evident":true,"opaque":true,"plain_packaging":true,"csa_z76_1":true}}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Master Shipping Case (Corrugated, Retail-Ready)','Corrugated master shipping case sized for retail-ready cannabis product cartons.','shipping_supply','north_america','negotiable','distributor','{}','approved',true,false,1.35,'CAD','CA','new','Harbourview Supply','HV-CASE-1',500,'each','master-shipping-case-corrugated','consumables',true,'HVP-SHP-CAS',6000,10,100,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Void Fill Air Pillows (Bulk)','Bulk air pillow void fill for shipping cartons.','shipping_supply','north_america','negotiable','distributor','{}','approved',true,false,0.02,'CAD','CA','new','Harbourview Supply','HV-VOID-1',5000,'each','void-fill-air-pillows-bulk','consumables',true,'HVP-SHP-VOI',500000,7,10000,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Pallet Stretch Wrap (Bulk Rolls)','Machine-grade stretch wrap for palletized shipments.','shipping_supply','north_america','negotiable','distributor','{}','approved',true,false,18.00,'CAD','CA','new','Harbourview Supply','HV-WRAP-1',200,'roll','pallet-stretch-wrap-bulk-rolls','consumables',true,'HVP-SHP-WRP',1500,7,20,'{}','{CA}',now(),now()),
(gen_random_uuid(),'consumables','Tamper-Evident Security Tape (Case Sealing)','Security tape with void/tamper-evident pattern for shipping case sealing.','shipping_supply','north_america','negotiable','distributor','{}','approved',true,false,4.20,'CAD','CA','new','Harbourview Supply','HV-TAPE-1',200,'roll','tamper-evident-security-tape','consumables',true,'HVP-SHP-TAP',3000,7,50,'{}','{CA}',now(),now()),
(gen_random_uuid(),'processing_equipment','Tincture Filling Machine (Semi-Automatic, Volumetric)','Semi-automatic volumetric filling machine for tincture and topical liquid bottles.','filling_equipment','north_america','negotiable','distributor','{"mechanism":"volumetric"}','approved',true,false,6500.00,'CAD','CA','new','Harbourview Supply','HV-TINCFIL-1',2,'unit','tincture-filling-machine-semi-auto','processing',true,'HVP-EQP-TFL',2,28,1,'{}','{CA}',now(),now()),
(gen_random_uuid(),'processing_equipment','Semi-Automatic Case Erector/Sealer','Semi-automatic case erector and sealer for shipping carton assembly.','packing_equipment','north_america','negotiable','distributor','{}','approved',true,false,8900.00,'CAD','CA','new','Harbourview Supply','HV-CASESEAL-1',2,'unit','semi-automatic-case-erector-sealer','processing',true,'HVP-EQP-CES',2,35,1,'{}','{CA}',now(),now()),
(gen_random_uuid(),'processing_equipment','Induction Sealer (Foil Liner Sealing for Bottles)','Induction sealer for foil-liner sealing of tincture/topical bottle caps.','sealing_equipment','north_america','negotiable','distributor','{}','approved',true,false,2600.00,'CAD','CA','new','Harbourview Supply','HV-INDSEAL-1',4,'unit','induction-sealer-foil-liner','processing',true,'HVP-EQP-IND',4,21,1,'{}','{CA}',now(),now());
