-- Market Entry OS durable execution state.
-- This migration creates the audit boundary for generated plans and task execution.
-- It does not mutate production data or grant public access.

create table if not exists public.market_entry_missions (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  origin_iso2 text not null check (origin_iso2 ~ '^[A-Z]{2}$'),
  destination_iso2 text not null check (destination_iso2 ~ '^[A-Z]{2}$'),
  product_class text not null check (product_class in ('any','flower','extract','finished_product','starting_material')),
  status text not null default 'draft' check (status in ('draft','blocked','orientation','ready','in_progress','completed')),
  plan_version integer not null default 2,
  plan_snapshot jsonb not null,
  evidence_snapshot jsonb not null,
  reproducibility_key text not null,
  checkout_session_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint market_entry_missions_distinct_corridor check (origin_iso2 <> destination_iso2)
);

create index if not exists market_entry_missions_owner_idx
  on public.market_entry_missions(owner_user_id, created_at desc);

create index if not exists market_entry_missions_corridor_idx
  on public.market_entry_missions(origin_iso2, destination_iso2, product_class);

create table if not exists public.market_entry_tasks (
  id uuid primary key default gen_random_uuid(),
  mission_id uuid not null references public.market_entry_missions(id) on delete cascade,
  task_key text not null,
  title text not null,
  description text not null,
  side text not null check (side in ('export','import','shared')),
  status text not null default 'pending' check (status in ('pending','blocked','in_progress','complete')),
  prerequisite_task_keys text[] not null default '{}',
  estimated_weeks numeric,
  evidence_ids text[] not null default '{}',
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(mission_id, task_key)
);

create index if not exists market_entry_tasks_mission_idx
  on public.market_entry_tasks(mission_id, status);

create table if not exists public.market_entry_events (
  id bigint generated by default as identity primary key,
  mission_id uuid not null references public.market_entry_missions(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  from_status text,
  to_status text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists market_entry_events_mission_idx
  on public.market_entry_events(mission_id, created_at desc);

alter table public.market_entry_missions enable row level security;
alter table public.market_entry_missions force row level security;
alter table public.market_entry_tasks enable row level security;
alter table public.market_entry_tasks force row level security;
alter table public.market_entry_events enable row level security;
alter table public.market_entry_events force row level security;

drop policy if exists market_entry_missions_owner_select on public.market_entry_missions;
create policy market_entry_missions_owner_select
  on public.market_entry_missions for select
  using (owner_user_id = auth.uid());

drop policy if exists market_entry_missions_owner_insert on public.market_entry_missions;
create policy market_entry_missions_owner_insert
  on public.market_entry_missions for insert
  with check (owner_user_id = auth.uid());

drop policy if exists market_entry_missions_owner_update on public.market_entry_missions;
create policy market_entry_missions_owner_update
  on public.market_entry_missions for update
  using (owner_user_id = auth.uid())
  with check (owner_user_id = auth.uid());

drop policy if exists market_entry_missions_owner_delete on public.market_entry_missions;
create policy market_entry_missions_owner_delete
  on public.market_entry_missions for delete
  using (owner_user_id = auth.uid());

drop policy if exists market_entry_tasks_owner_select on public.market_entry_tasks;
create policy market_entry_tasks_owner_select
  on public.market_entry_tasks for select
  using (exists (
    select 1 from public.market_entry_missions m
    where m.id = mission_id and m.owner_user_id = auth.uid()
  ));

drop policy if exists market_entry_tasks_owner_insert on public.market_entry_tasks;
create policy market_entry_tasks_owner_insert
  on public.market_entry_tasks for insert
  with check (exists (
    select 1 from public.market_entry_missions m
    where m.id = mission_id and m.owner_user_id = auth.uid()
  ));

drop policy if exists market_entry_tasks_owner_update on public.market_entry_tasks;
create policy market_entry_tasks_owner_update
  on public.market_entry_tasks for update
  using (exists (
    select 1 from public.market_entry_missions m
    where m.id = mission_id and m.owner_user_id = auth.uid()
  ))
  with check (exists (
    select 1 from public.market_entry_missions m
    where m.id = mission_id and m.owner_user_id = auth.uid()
  ));

drop policy if exists market_entry_tasks_owner_delete on public.market_entry_tasks;
create policy market_entry_tasks_owner_delete
  on public.market_entry_tasks for delete
  using (exists (
    select 1 from public.market_entry_missions m
    where m.id = mission_id and m.owner_user_id = auth.uid()
  ));

drop policy if exists market_entry_events_owner_select on public.market_entry_events;
create policy market_entry_events_owner_select
  on public.market_entry_events for select
  using (exists (
    select 1 from public.market_entry_missions m
    where m.id = mission_id and m.owner_user_id = auth.uid()
  ));

drop policy if exists market_entry_events_owner_insert on public.market_entry_events;
create policy market_entry_events_owner_insert
  on public.market_entry_events for insert
  with check (
    actor_user_id = auth.uid()
    and exists (
      select 1 from public.market_entry_missions m
      where m.id = mission_id and m.owner_user_id = auth.uid()
    )
  );

revoke all on table public.market_entry_missions from anon;
revoke all on table public.market_entry_tasks from anon;
revoke all on table public.market_entry_events from anon;

grant select, insert, update, delete on public.market_entry_missions to authenticated;
grant select, insert, update, delete on public.market_entry_tasks to authenticated;
grant select, insert on public.market_entry_events to authenticated;
