-- REHYDRATE Market Access heatmap: full US + CA + AU + DE after coverage regression.
-- Upsert only (no broad deactivate of unrelated evidence). Then refresh published tiers.

insert into public.regulatory_market_access_evidence
  (evidence_key, jurisdiction_iso2, tier, rationale, authority_name, authority_url,
   source_effective_date, verified_at, expires_at, active)
values
  ('hv-rehydrate-us-ak-20260925','US-AK','legal_commercial_access',
   'AK operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Alaska Alcohol and Marijuana Control Office','https://www.commerce.alaska.gov/web/amco/',
   '2016-02-24', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-az-20260925','US-AZ','legal_commercial_access',
   'AZ operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Arizona Department of Health Services — Cannabis','https://www.azdhs.gov/licensing/cannabis/index.php',
   '2020-11-30', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-ca-20260925','US-CA','legal_commercial_access',
   'CA operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'California Department of Cannabis Control','https://cannabis.ca.gov/',
   '2018-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-co-20260925','US-CO','legal_commercial_access',
   'CO operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Colorado Marijuana Enforcement Division','https://med.colorado.gov/',
   '2014-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-ct-20260925','US-CT','legal_commercial_access',
   'CT operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Connecticut Department of Consumer Protection — Cannabis','https://portal.ct.gov/dcp/cannabis',
   '2023-01-10', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-de-20260925','US-DE','legal_commercial_access',
   'DE operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Delaware Division of Public Health — Medical Marijuana','https://dhss.delaware.gov/dhss/dph/hsp/mmp.html',
   '2023-08-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-il-20260925','US-IL','legal_commercial_access',
   'IL operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Illinois Department of Financial and Professional Regulation — Cannabis','https://idfpr.illinois.gov/',
   '2020-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-ma-20260925','US-MA','legal_commercial_access',
   'MA operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Massachusetts Cannabis Control Commission','https://masscannabiscontrol.com/',
   '2018-11-20', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-me-20260925','US-ME','legal_commercial_access',
   'ME operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Maine Office of Cannabis Policy','https://www.maine.gov/dafs/ocp/',
   '2020-10-09', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-md-20260925','US-MD','legal_commercial_access',
   'MD operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Maryland Cannabis Administration','https://mmcc.maryland.gov/',
   '2023-07-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-mi-20260925','US-MI','legal_commercial_access',
   'MI operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Michigan Cannabis Regulatory Agency','https://www.michigan.gov/cra',
   '2019-12-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-mn-20260925','US-MN','legal_commercial_access',
   'MN operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Minnesota Office of Cannabis Management','https://mn.gov/ocm/',
   '2023-08-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-mo-20260925','US-MO','legal_commercial_access',
   'MO operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Missouri Division of Cannabis Regulation','https://health.mo.gov/safety/cannabis/',
   '2023-02-03', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-mt-20260925','US-MT','legal_commercial_access',
   'MT operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Montana Cannabis Control Division','https://mtrevenue.gov/cannabis/',
   '2022-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-nj-20260925','US-NJ','legal_commercial_access',
   'NJ operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'New Jersey Cannabis Regulatory Commission','https://www.nj.gov/cannabis/',
   '2022-04-21', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-nm-20260925','US-NM','legal_commercial_access',
   'NM operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'New Mexico Cannabis Control Division','https://www.rld.nm.gov/cannabis/',
   '2022-04-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-nv-20260925','US-NV','legal_commercial_access',
   'NV operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Nevada Cannabis Compliance Board','https://ccb.nv.gov/',
   '2017-07-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-ny-20260925','US-NY','legal_commercial_access',
   'NY operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'New York Office of Cannabis Management','https://cannabis.ny.gov/',
   '2022-12-29', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-oh-20260925','US-OH','legal_commercial_access',
   'OH operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Ohio Division of Cannabis Control','https://com.ohio.gov/divisions-and-programs/cannabis-control',
   '2023-12-07', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-or-20260925','US-OR','legal_commercial_access',
   'OR operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Oregon Liquor and Cannabis Commission','https://www.oregon.gov/olcc/marijuana/pages/default.aspx',
   '2015-10-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-ri-20260925','US-RI','legal_commercial_access',
   'RI operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Rhode Island Office of Cannabis Regulation','https://dbr.ri.gov/cannabis',
   '2022-12-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-vt-20260925','US-VT','legal_commercial_access',
   'VT operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Vermont Cannabis Control Board','https://ccb.vermont.gov/',
   '2022-10-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-wa-20260925','US-WA','legal_commercial_access',
   'WA operates a state-licensed adult-use and/or dual adult-use+medical cannabis market under the cited state regulator.',
   'Washington State Liquor and Cannabis Board','https://lcb.wa.gov/',
   '2014-07-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-al-20260925','US-AL','medical_limited_trade',
   'AL operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'Alabama Medical Cannabis Commission','https://amcc.alabama.gov/',
   '2022-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-ar-20260925','US-AR','medical_limited_trade',
   'AR operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'Arkansas Medical Marijuana Commission','https://www.mmc.arkansas.gov/',
   '2017-05-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-dc-20260925','US-DC','medical_limited_trade',
   'DC operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'DC Alcoholic Beverage and Cannabis Administration','https://abca.dc.gov/',
   '2015-02-26', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-fl-20260925','US-FL','medical_limited_trade',
   'FL operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'Florida Office of Medical Marijuana Use','https://knowthefactsmmj.com/',
   '2017-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-ga-20260925','US-GA','medical_limited_trade',
   'GA operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'Georgia Access to Medical Cannabis Commission','https://www.gmc.georgia.gov/',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-hi-20260925','US-HI','medical_limited_trade',
   'HI operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'Hawaii Department of Health — Medical Cannabis','https://health.hawaii.gov/medicalcannabisunit/',
   '2000-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-ky-20260925','US-KY','medical_limited_trade',
   'KY operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'Kentucky Office of Medical Cannabis','https://kymedcan.ky.gov/',
   '2024-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-la-20260925','US-LA','medical_limited_trade',
   'LA operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'Louisiana Department of Health — Medical Marijuana','https://ldh.la.gov/page/medical-marijuana',
   '2019-08-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-ms-20260925','US-MS','medical_limited_trade',
   'MS operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'Mississippi State Department of Health — Medical Cannabis','https://msdh.ms.gov/',
   '2022-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-nd-20260925','US-ND','medical_limited_trade',
   'ND operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'North Dakota DHHS — Medical Marijuana','https://www.hhs.nd.gov/health/medical-marijuana',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-ne-20260925','US-NE','medical_limited_trade',
   'NE operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'Nebraska Legislature — medical cannabis framework','https://nebraskalegislature.gov/',
   '2024-11-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-nh-20260925','US-NH','medical_limited_trade',
   'NH operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'New Hampshire Department of Health and Human Services — Therapeutic Cannabis','https://www.dhhs.nh.gov/programs-services/health-care/therapeutic-cannabis',
   '2013-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-ok-20260925','US-OK','medical_limited_trade',
   'OK operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'Oklahoma Medical Marijuana Authority','https://oklahoma.gov/omma.html',
   '2018-07-26', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-pa-20260925','US-PA','medical_limited_trade',
   'PA operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'Pennsylvania Department of Health — Medical Marijuana','https://www.health.pa.gov/topics/programs/Medical-Marijuana/Pages/Medical-Marijuana.aspx',
   '2016-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-sd-20260925','US-SD','medical_limited_trade',
   'SD operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'South Dakota Department of Health — Medical Cannabis','https://medcannabis.sd.gov/',
   '2021-07-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-tx-20260925','US-TX','medical_limited_trade',
   'TX operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'Texas Department of Public Safety — Compassionate Use','https://www.dps.texas.gov/section/compassionate-use-program',
   '2015-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-ut-20260925','US-UT','medical_limited_trade',
   'UT operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'Utah Department of Health — Medical Cannabis','https://medicalcannabis.utah.gov/',
   '2018-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-va-20260925','US-VA','medical_limited_trade',
   'VA operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'Virginia Cannabis Control Authority','https://cca.virginia.gov/',
   '2021-07-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-wv-20260925','US-WV','medical_limited_trade',
   'WV operates a regulated medical cannabis programme; adult-use retail is not treated as the published pathway for this state.',
   'West Virginia Office of Medical Cannabis','https://dhhr.wv.gov/bph/Pages/Medical-Cannabis.aspx',
   '2019-07-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-ia-20260925','US-IA','cbd_hemp_only',
   'IA does not operate a full THC adult-use retail market; published pathway is limited to hemp/low-THC/CBD frameworks.',
   'Iowa Department of Health — Medical Cannabidiol','https://hhs.iowa.gov/',
   '2017-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-in-20260925','US-IN','cbd_hemp_only',
   'IN does not operate a full THC adult-use retail market; published pathway is limited to hemp/low-THC/CBD frameworks.',
   'Indiana State Department of Agriculture — Hemp','https://www.in.gov/isda/divisions/hemp/',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-ks-20260925','US-KS','cbd_hemp_only',
   'KS does not operate a full THC adult-use retail market; published pathway is limited to hemp/low-THC/CBD frameworks.',
   'Kansas Department of Agriculture — Industrial Hemp','https://agriculture.ks.gov/',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-nc-20260925','US-NC','cbd_hemp_only',
   'NC does not operate a full THC adult-use retail market; published pathway is limited to hemp/low-THC/CBD frameworks.',
   'North Carolina Department of Agriculture — Hemp','https://www.ncagr.gov/',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-sc-20260925','US-SC','cbd_hemp_only',
   'SC does not operate a full THC adult-use retail market; published pathway is limited to hemp/low-THC/CBD frameworks.',
   'South Carolina Department of Agriculture','https://agriculture.sc.gov/',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-wi-20260925','US-WI','cbd_hemp_only',
   'WI does not operate a full THC adult-use retail market; published pathway is limited to hemp/low-THC/CBD frameworks.',
   'Wisconsin Department of Agriculture — Hemp','https://datcp.wi.gov/',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-wy-20260925','US-WY','cbd_hemp_only',
   'WY does not operate a full THC adult-use retail market; published pathway is limited to hemp/low-THC/CBD frameworks.',
   'Wyoming Department of Agriculture — Hemp','https://wyagric.state.wy.us/',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-id-20260925','US-ID','prohibited',
   'ID does not operate a verified medical or adult-use THC cannabis retail market for globe publication.',
   'State controlled-substances framework','https://www.ncsl.org/health/state-medical-cannabis-laws',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-tn-20260925','US-TN','prohibited',
   'TN does not operate a verified medical or adult-use THC cannabis retail market for globe publication.',
   'State controlled-substances framework','https://www.ncsl.org/health/state-medical-cannabis-laws',
   '2019-01-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-ca-ab-20260925','CA-AB','legal_commercial_access',
   'Canadian province/territory AB participates in the federal Cannabis Act licensed adult-use and medical framework administered with Health Canada oversight.',
   'Health Canada — Cannabis','https://www.canada.ca/en/health-canada/services/drugs-medication/cannabis.html',
   '2018-10-17', now(), now() + interval '365 days', true),
  ('hv-rehydrate-ca-bc-20260925','CA-BC','legal_commercial_access',
   'Canadian province/territory BC participates in the federal Cannabis Act licensed adult-use and medical framework administered with Health Canada oversight.',
   'Health Canada — Cannabis','https://www.canada.ca/en/health-canada/services/drugs-medication/cannabis.html',
   '2018-10-17', now(), now() + interval '365 days', true),
  ('hv-rehydrate-ca-mb-20260925','CA-MB','legal_commercial_access',
   'Canadian province/territory MB participates in the federal Cannabis Act licensed adult-use and medical framework administered with Health Canada oversight.',
   'Health Canada — Cannabis','https://www.canada.ca/en/health-canada/services/drugs-medication/cannabis.html',
   '2018-10-17', now(), now() + interval '365 days', true),
  ('hv-rehydrate-ca-nb-20260925','CA-NB','legal_commercial_access',
   'Canadian province/territory NB participates in the federal Cannabis Act licensed adult-use and medical framework administered with Health Canada oversight.',
   'Health Canada — Cannabis','https://www.canada.ca/en/health-canada/services/drugs-medication/cannabis.html',
   '2018-10-17', now(), now() + interval '365 days', true),
  ('hv-rehydrate-ca-nl-20260925','CA-NL','legal_commercial_access',
   'Canadian province/territory NL participates in the federal Cannabis Act licensed adult-use and medical framework administered with Health Canada oversight.',
   'Health Canada — Cannabis','https://www.canada.ca/en/health-canada/services/drugs-medication/cannabis.html',
   '2018-10-17', now(), now() + interval '365 days', true),
  ('hv-rehydrate-ca-ns-20260925','CA-NS','legal_commercial_access',
   'Canadian province/territory NS participates in the federal Cannabis Act licensed adult-use and medical framework administered with Health Canada oversight.',
   'Health Canada — Cannabis','https://www.canada.ca/en/health-canada/services/drugs-medication/cannabis.html',
   '2018-10-17', now(), now() + interval '365 days', true),
  ('hv-rehydrate-ca-nt-20260925','CA-NT','legal_commercial_access',
   'Canadian province/territory NT participates in the federal Cannabis Act licensed adult-use and medical framework administered with Health Canada oversight.',
   'Health Canada — Cannabis','https://www.canada.ca/en/health-canada/services/drugs-medication/cannabis.html',
   '2018-10-17', now(), now() + interval '365 days', true),
  ('hv-rehydrate-ca-nu-20260925','CA-NU','legal_commercial_access',
   'Canadian province/territory NU participates in the federal Cannabis Act licensed adult-use and medical framework administered with Health Canada oversight.',
   'Health Canada — Cannabis','https://www.canada.ca/en/health-canada/services/drugs-medication/cannabis.html',
   '2018-10-17', now(), now() + interval '365 days', true),
  ('hv-rehydrate-ca-on-20260925','CA-ON','legal_commercial_access',
   'Canadian province/territory ON participates in the federal Cannabis Act licensed adult-use and medical framework administered with Health Canada oversight.',
   'Health Canada — Cannabis','https://www.canada.ca/en/health-canada/services/drugs-medication/cannabis.html',
   '2018-10-17', now(), now() + interval '365 days', true),
  ('hv-rehydrate-ca-pe-20260925','CA-PE','legal_commercial_access',
   'Canadian province/territory PE participates in the federal Cannabis Act licensed adult-use and medical framework administered with Health Canada oversight.',
   'Health Canada — Cannabis','https://www.canada.ca/en/health-canada/services/drugs-medication/cannabis.html',
   '2018-10-17', now(), now() + interval '365 days', true),
  ('hv-rehydrate-ca-qc-20260925','CA-QC','legal_commercial_access',
   'Canadian province/territory QC participates in the federal Cannabis Act licensed adult-use and medical framework administered with Health Canada oversight.',
   'Health Canada — Cannabis','https://www.canada.ca/en/health-canada/services/drugs-medication/cannabis.html',
   '2018-10-17', now(), now() + interval '365 days', true),
  ('hv-rehydrate-ca-sk-20260925','CA-SK','legal_commercial_access',
   'Canadian province/territory SK participates in the federal Cannabis Act licensed adult-use and medical framework administered with Health Canada oversight.',
   'Health Canada — Cannabis','https://www.canada.ca/en/health-canada/services/drugs-medication/cannabis.html',
   '2018-10-17', now(), now() + interval '365 days', true),
  ('hv-rehydrate-ca-yt-20260925','CA-YT','legal_commercial_access',
   'Canadian province/territory YT participates in the federal Cannabis Act licensed adult-use and medical framework administered with Health Canada oversight.',
   'Health Canada — Cannabis','https://www.canada.ca/en/health-canada/services/drugs-medication/cannabis.html',
   '2018-10-17', now(), now() + interval '365 days', true),
  ('hv-rehydrate-ca-20260925','CA','legal_commercial_access',
   'Canada licenses adult-use and medical cannabis under the federal Cannabis Act.',
   'Health Canada — Cannabis','https://www.canada.ca/en/health-canada/services/drugs-medication/cannabis.html',
   '2018-10-17', now(), now() + interval '365 days', true),
  ('hv-rehydrate-us-20260925','US','medical_limited_trade',
   'State markets operate under state law; no verified nationwide interstate commercial cannabis pathway is published for globe colouring.',
   'US FDA — cannabis and cannabis-derived products','https://www.fda.gov/news-events/public-health-focus/fda-regulation-cannabis-and-cannabis-derived-products-including-cannabidiol-cbd',
   '1970-10-27', now(), now() + interval '365 days', true),
  ('hv-rehydrate-au-act-20260925','AU-ACT','medical_limited_trade',
   'Australian jurisdiction ACT participates in the TGA medicinal cannabis scheme; adult-use commercial retail is not authorised at Commonwealth level.',
   'Therapeutic Goods Administration — Medicinal cannabis','https://www.tga.gov.au/products/medicinal-cannabis',
   '2016-11-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-au-nsw-20260925','AU-NSW','medical_limited_trade',
   'Australian jurisdiction NSW participates in the TGA medicinal cannabis scheme; adult-use commercial retail is not authorised at Commonwealth level.',
   'Therapeutic Goods Administration — Medicinal cannabis','https://www.tga.gov.au/products/medicinal-cannabis',
   '2016-11-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-au-nt-20260925','AU-NT','medical_limited_trade',
   'Australian jurisdiction NT participates in the TGA medicinal cannabis scheme; adult-use commercial retail is not authorised at Commonwealth level.',
   'Therapeutic Goods Administration — Medicinal cannabis','https://www.tga.gov.au/products/medicinal-cannabis',
   '2016-11-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-au-qld-20260925','AU-QLD','medical_limited_trade',
   'Australian jurisdiction QLD participates in the TGA medicinal cannabis scheme; adult-use commercial retail is not authorised at Commonwealth level.',
   'Therapeutic Goods Administration — Medicinal cannabis','https://www.tga.gov.au/products/medicinal-cannabis',
   '2016-11-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-au-sa-20260925','AU-SA','medical_limited_trade',
   'Australian jurisdiction SA participates in the TGA medicinal cannabis scheme; adult-use commercial retail is not authorised at Commonwealth level.',
   'Therapeutic Goods Administration — Medicinal cannabis','https://www.tga.gov.au/products/medicinal-cannabis',
   '2016-11-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-au-tas-20260925','AU-TAS','medical_limited_trade',
   'Australian jurisdiction TAS participates in the TGA medicinal cannabis scheme; adult-use commercial retail is not authorised at Commonwealth level.',
   'Therapeutic Goods Administration — Medicinal cannabis','https://www.tga.gov.au/products/medicinal-cannabis',
   '2016-11-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-au-vic-20260925','AU-VIC','medical_limited_trade',
   'Australian jurisdiction VIC participates in the TGA medicinal cannabis scheme; adult-use commercial retail is not authorised at Commonwealth level.',
   'Therapeutic Goods Administration — Medicinal cannabis','https://www.tga.gov.au/products/medicinal-cannabis',
   '2016-11-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-au-wa-20260925','AU-WA','medical_limited_trade',
   'Australian jurisdiction WA participates in the TGA medicinal cannabis scheme; adult-use commercial retail is not authorised at Commonwealth level.',
   'Therapeutic Goods Administration — Medicinal cannabis','https://www.tga.gov.au/products/medicinal-cannabis',
   '2016-11-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-de-bb-20260925','DE-BB','medical_limited_trade',
   'Brandenburg operates under Germany''s federal medicinal-cannabis framework (BtMG/CanG).',
   'BfArM — Medizinisches Cannabis','https://www.bfarm.de/DE/Bundesopiumstelle/Cannabis/_node.html',
   '2024-04-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-de-be-20260925','DE-BE','medical_limited_trade',
   'Berlin operates under Germany''s federal medicinal-cannabis framework (BtMG/CanG).',
   'BfArM — Medizinisches Cannabis','https://www.bfarm.de/DE/Bundesopiumstelle/Cannabis/_node.html',
   '2024-04-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-de-bw-20260925','DE-BW','medical_limited_trade',
   'Baden-Württemberg operates under Germany''s federal medicinal-cannabis framework (BtMG/CanG).',
   'BfArM — Medizinisches Cannabis','https://www.bfarm.de/DE/Bundesopiumstelle/Cannabis/_node.html',
   '2024-04-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-de-by-20260925','DE-BY','medical_limited_trade',
   'Bayern operates under Germany''s federal medicinal-cannabis framework (BtMG/CanG).',
   'BfArM — Medizinisches Cannabis','https://www.bfarm.de/DE/Bundesopiumstelle/Cannabis/_node.html',
   '2024-04-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-de-hb-20260925','DE-HB','medical_limited_trade',
   'Bremen operates under Germany''s federal medicinal-cannabis framework (BtMG/CanG).',
   'BfArM — Medizinisches Cannabis','https://www.bfarm.de/DE/Bundesopiumstelle/Cannabis/_node.html',
   '2024-04-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-de-he-20260925','DE-HE','medical_limited_trade',
   'Hessen operates under Germany''s federal medicinal-cannabis framework (BtMG/CanG).',
   'BfArM — Medizinisches Cannabis','https://www.bfarm.de/DE/Bundesopiumstelle/Cannabis/_node.html',
   '2024-04-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-de-hh-20260925','DE-HH','medical_limited_trade',
   'Hamburg operates under Germany''s federal medicinal-cannabis framework (BtMG/CanG).',
   'BfArM — Medizinisches Cannabis','https://www.bfarm.de/DE/Bundesopiumstelle/Cannabis/_node.html',
   '2024-04-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-de-mv-20260925','DE-MV','medical_limited_trade',
   'Mecklenburg-Vorpommern operates under Germany''s federal medicinal-cannabis framework (BtMG/CanG).',
   'BfArM — Medizinisches Cannabis','https://www.bfarm.de/DE/Bundesopiumstelle/Cannabis/_node.html',
   '2024-04-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-de-ni-20260925','DE-NI','medical_limited_trade',
   'Niedersachsen operates under Germany''s federal medicinal-cannabis framework (BtMG/CanG).',
   'BfArM — Medizinisches Cannabis','https://www.bfarm.de/DE/Bundesopiumstelle/Cannabis/_node.html',
   '2024-04-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-de-nw-20260925','DE-NW','medical_limited_trade',
   'Nordrhein-Westfalen operates under Germany''s federal medicinal-cannabis framework (BtMG/CanG).',
   'BfArM — Medizinisches Cannabis','https://www.bfarm.de/DE/Bundesopiumstelle/Cannabis/_node.html',
   '2024-04-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-de-rp-20260925','DE-RP','medical_limited_trade',
   'Rheinland-Pfalz operates under Germany''s federal medicinal-cannabis framework (BtMG/CanG).',
   'BfArM — Medizinisches Cannabis','https://www.bfarm.de/DE/Bundesopiumstelle/Cannabis/_node.html',
   '2024-04-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-de-sh-20260925','DE-SH','medical_limited_trade',
   'Schleswig-Holstein operates under Germany''s federal medicinal-cannabis framework (BtMG/CanG).',
   'BfArM — Medizinisches Cannabis','https://www.bfarm.de/DE/Bundesopiumstelle/Cannabis/_node.html',
   '2024-04-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-de-sl-20260925','DE-SL','medical_limited_trade',
   'Saarland operates under Germany''s federal medicinal-cannabis framework (BtMG/CanG).',
   'BfArM — Medizinisches Cannabis','https://www.bfarm.de/DE/Bundesopiumstelle/Cannabis/_node.html',
   '2024-04-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-de-sn-20260925','DE-SN','medical_limited_trade',
   'Sachsen operates under Germany''s federal medicinal-cannabis framework (BtMG/CanG).',
   'BfArM — Medizinisches Cannabis','https://www.bfarm.de/DE/Bundesopiumstelle/Cannabis/_node.html',
   '2024-04-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-de-st-20260925','DE-ST','medical_limited_trade',
   'Sachsen-Anhalt operates under Germany''s federal medicinal-cannabis framework (BtMG/CanG).',
   'BfArM — Medizinisches Cannabis','https://www.bfarm.de/DE/Bundesopiumstelle/Cannabis/_node.html',
   '2024-04-01', now(), now() + interval '365 days', true),
  ('hv-rehydrate-de-th-20260925','DE-TH','medical_limited_trade',
   'Thüringen operates under Germany''s federal medicinal-cannabis framework (BtMG/CanG).',
   'BfArM — Medizinisches Cannabis','https://www.bfarm.de/DE/Bundesopiumstelle/Cannabis/_node.html',
   '2024-04-01', now(), now() + interval '365 days', true)
on conflict (evidence_key) do update set
  tier = excluded.tier,
  rationale = excluded.rationale,
  authority_name = excluded.authority_name,
  authority_url = excluded.authority_url,
  source_effective_date = excluded.source_effective_date,
  verified_at = excluded.verified_at,
  expires_at = excluded.expires_at,
  active = true;

-- Ensure these keys win resolve (latest verified_at already set to now()).
-- Do NOT deactivate other jurisdictions' evidence.

select * from api.refresh_verified_market_access_tiers('heatmap-rehydrate-us-ca-au-de-20260925');
