import type {
  MonetizationAccessProduct,
  PartnerEcosystemRecord,
  RevenueIntelligenceItem,
  InstitutionalReport,
  GlobalExpansionCoverage,
  GovernanceQualityItem,
  SuccessFeeOpportunity,
  SubscriptionTier,
} from './types'

export const accessProducts: MonetizationAccessProduct[] = [
  {
    id: 'ap-001',
    product_type: 'qualified_buyer_access',
    name: 'Qualified Buyer Access',
    description: 'Direct access to verified cannabis buyers across EU, APAC, and LATAM markets. Includes buyer profiling, demand signals, and introduction workflow.',
    price_usd: 4500,
    delivery_workflow: 'Analyst-curated buyer shortlist → introductory call facilitation → deal room setup',
    eligibility_criteria: ['Licensed cannabis producer or exporter', 'GMP certification or equivalent', 'Minimum 500kg inventory available'],
    linked_ctas: ['Request Buyer Introductions', 'View Buyer Demand Report'],
    revenue_potential: 'high',
    conversion_funnel: 'Signal capture → Buyer match → Introduction → Deal room → Success fee',
    status: 'active',
  },
  {
    id: 'ap-002',
    product_type: 'seller_listing_intake',
    name: 'Seller Listing Intake',
    description: 'Structured onboarding for cannabis sellers seeking to list inventory on the Harbourview marketplace. Includes documentation review and market readiness assessment.',
    price_usd: 1200,
    delivery_workflow: 'Document submission → analyst review → listing approval → marketplace publication',
    eligibility_criteria: ['Active production licence', 'COA documentation available', 'Export capability confirmed'],
    linked_ctas: ['Submit Listing', 'Download Documentation Checklist'],
    revenue_potential: 'medium',
    conversion_funnel: 'Seller onboarding → Listing → Buyer match → Introduction',
    status: 'active',
  },
  {
    id: 'ap-003',
    product_type: 'market_access_review',
    name: 'Market Access Review',
    description: 'Comprehensive assessment of a target market\'s regulatory pathway, import requirements, and route-to-market options for a specific product category.',
    price_usd: 3500,
    delivery_workflow: 'Market selection → regulatory pathway analysis → partner mapping → written report delivery',
    eligibility_criteria: ['Active cannabis business', 'Defined target market', 'Product specifications available'],
    linked_ctas: ['Request Market Review', 'View Sample Report'],
    revenue_potential: 'high',
    conversion_funnel: 'Market interest → Access review → Partner introduction → Deal room',
    status: 'active',
  },
  {
    id: 'ap-004',
    product_type: 'importer_introduction',
    name: 'Importer Introduction',
    description: 'Facilitated introduction to vetted cannabis importers in target markets. Includes importer profile, demand assessment, and introduction letter.',
    price_usd: 2800,
    delivery_workflow: 'Importer shortlist → profile review → introduction facilitation → deal room access',
    eligibility_criteria: ['Verified exporter status', 'GMP-compliant product', 'Target market specified'],
    linked_ctas: ['Find Importers', 'View Importer Directory'],
    revenue_potential: 'high',
    conversion_funnel: 'Exporter onboarding → Importer match → Introduction → Success fee',
    status: 'active',
  },
  {
    id: 'ap-005',
    product_type: 'distributor_introduction',
    name: 'Distributor Introduction',
    description: 'Connect with licensed cannabis distributors operating in your target markets. Includes distributor profiling and route-to-market mapping.',
    price_usd: 2500,
    delivery_workflow: 'Distributor shortlist → profile review → introduction facilitation → deal room access',
    eligibility_criteria: ['Licensed producer or importer', 'Product category confirmed', 'Distribution volume defined'],
    linked_ctas: ['Find Distributors', 'View Distribution Map'],
    revenue_potential: 'medium',
    conversion_funnel: 'Producer onboarding → Distributor match → Introduction → Commercial terms',
    status: 'active',
  },
  {
    id: 'ap-006',
    product_type: 'documentation_readiness_review',
    name: 'Documentation Readiness Review',
    description: 'Expert review of your regulatory documentation package against target market requirements. Identifies gaps and provides a remediation roadmap.',
    price_usd: 1800,
    delivery_workflow: 'Document upload → analyst review → gap analysis → remediation report',
    eligibility_criteria: ['Active cannabis business', 'Documentation package available', 'Target market identified'],
    linked_ctas: ['Submit Documents', 'View Documentation Checklist'],
    revenue_potential: 'medium',
    conversion_funnel: 'Documentation review → Gap closure → Market readiness → Introduction',
    status: 'active',
  },
  {
    id: 'ap-007',
    product_type: 'intelligence_subscription',
    name: 'Intelligence Subscription',
    description: 'Ongoing access to Harbourview\'s regulatory intelligence, market signals, and deal flow data across selected markets and categories.',
    price_usd: 890,
    delivery_workflow: 'Market selection → subscription activation → weekly signal digest → monthly market brief',
    eligibility_criteria: ['Cannabis industry participant', 'Defined market focus'],
    linked_ctas: ['Start Subscription', 'View Sample Signal Digest'],
    revenue_potential: 'medium',
    conversion_funnel: 'Trial → Subscription → Upsell to access products',
    status: 'active',
  },
  {
    id: 'ap-008',
    product_type: 'enterprise_operator_seat',
    name: 'Enterprise Operator Seat',
    description: 'Full platform access for enterprise cannabis operators. Includes all intelligence modules, deal room access, and dedicated analyst support.',
    price_usd: null,
    delivery_workflow: 'Enterprise discovery → scope definition → onboarding → dedicated support',
    eligibility_criteria: ['Multi-market cannabis operator', 'Revenue >$10M annually', 'Executive sponsor identified'],
    linked_ctas: ['Contact Enterprise Sales', 'View Enterprise Features'],
    revenue_potential: 'high',
    conversion_funnel: 'Enterprise discovery → Proof of value → Contract → Expansion',
    status: 'active',
  },
  {
    id: 'ap-009',
    product_type: 'deal_room_access',
    name: 'Deal Room Access',
    description: 'Secure deal room environment for cannabis trade negotiations. Includes document sharing, milestone tracking, and analyst oversight.',
    price_usd: 950,
    delivery_workflow: 'Deal initiation → room setup → counterparty onboarding → milestone tracking',
    eligibility_criteria: ['Active trade negotiation in progress', 'Both parties identified'],
    linked_ctas: ['Open Deal Room', 'Learn About Deal Rooms'],
    revenue_potential: 'high',
    conversion_funnel: 'Introduction → Deal room → Closing → Success fee',
    status: 'active',
  },
  {
    id: 'ap-010',
    product_type: 'partner_directory_access',
    name: 'Partner Directory Access',
    description: 'Searchable directory of vetted Harbourview partners including importers, distributors, GMP consultants, labs, and logistics providers.',
    price_usd: 450,
    delivery_workflow: 'Category selection → directory search → partner profile review → contact facilitation',
    eligibility_criteria: ['Active cannabis business'],
    linked_ctas: ['Browse Directory', 'Become a Listed Partner'],
    revenue_potential: 'low',
    conversion_funnel: 'Directory search → Partner contact → Introduction upsell',
    status: 'active',
  },
  {
    id: 'ap-011',
    product_type: 'market_brief_access',
    name: 'Market Brief Access',
    description: 'On-demand access to Harbourview\'s institutional market briefs covering regulatory pathways, buyer demand, and commercial opportunities by market.',
    price_usd: 650,
    delivery_workflow: 'Market selection → brief delivery → follow-up analyst Q&A session',
    eligibility_criteria: ['Active cannabis business', 'Target market selected'],
    linked_ctas: ['Browse Market Briefs', 'Request Custom Brief'],
    revenue_potential: 'medium',
    conversion_funnel: 'Brief purchase → Market interest → Access product upsell',
    status: 'active',
  },
  {
    id: 'ap-012',
    product_type: 'custom_opportunity_memo',
    name: 'Custom Opportunity Memo',
    description: 'Bespoke opportunity analysis memo covering a specific counterparty, market, or category. Analyst-authored with primary research and recommendation.',
    price_usd: 2200,
    delivery_workflow: 'Brief intake → primary research → analyst authoring → review → delivery',
    eligibility_criteria: ['Active cannabis business', 'Specific opportunity defined'],
    linked_ctas: ['Request Opportunity Memo', 'View Sample Memo'],
    revenue_potential: 'medium',
    conversion_funnel: 'Memo request → Delivery → Introduction upsell → Deal room',
    status: 'in_development',
  },
]

export const partnerEcosystemRecords: PartnerEcosystemRecord[] = [
  {
    id: 'pe-001',
    partner_type: 'importer',
    name: 'EuroMed Cannabis Imports GmbH',
    markets: ['DE', 'AT', 'CH'],
    categories: ['cannabis_inventory', 'eu_gmp'],
    relationship_stage: 'strategic',
    opportunity_mapping: ['DE importer introductions', 'EU-GMP supply matching', 'Deal room facilitation'],
    status: 'active',
  },
  {
    id: 'pe-002',
    partner_type: 'importer',
    name: 'Pharmabis UK Ltd',
    markets: ['UK'],
    categories: ['cannabis_inventory', 'services'],
    relationship_stage: 'active',
    opportunity_mapping: ['UK importer introductions', 'Schedule 2 import pathway', 'Buyer demand signals'],
    status: 'active',
  },
  {
    id: 'pe-003',
    partner_type: 'distributor',
    name: 'CannaDistri Portugal Lda',
    markets: ['PT', 'ES'],
    categories: ['cannabis_inventory', 'market_access'],
    relationship_stage: 'active',
    opportunity_mapping: ['PT distributor introductions', 'Iberian route-to-market', 'Pharmacy channel access'],
    status: 'active',
  },
  {
    id: 'pe-004',
    partner_type: 'gmp_consultant',
    name: 'PharmaBridge Consulting',
    markets: ['DE', 'NL', 'PL', 'CZ'],
    categories: ['eu_gmp', 'services'],
    relationship_stage: 'strategic',
    opportunity_mapping: ['EU-GMP gap analysis', 'Documentation readiness review', 'Regulatory pathway advisory'],
    status: 'active',
  },
  {
    id: 'pe-005',
    partner_type: 'lab',
    name: 'CannaLab Analytics',
    markets: ['DE', 'NL'],
    categories: ['services', 'eu_gmp'],
    relationship_stage: 'active',
    opportunity_mapping: ['COA validation', 'Testing referrals', 'Quality assurance review'],
    status: 'active',
  },
  {
    id: 'pe-006',
    partner_type: 'legal_compliance',
    name: 'Green Regulation Partners',
    markets: ['CA', 'AU', 'UK'],
    categories: ['services', 'market_access'],
    relationship_stage: 'engaged',
    opportunity_mapping: ['Regulatory pathway advisory', 'Licence application support', 'Compliance audit services'],
    status: 'active',
  },
  {
    id: 'pe-007',
    partner_type: 'logistics',
    name: 'CannaTrans Global Logistics',
    markets: ['DE', 'NL', 'PL', 'CZ', 'PT'],
    categories: ['services', 'cannabis_inventory'],
    relationship_stage: 'active',
    opportunity_mapping: ['Cross-border logistics facilitation', 'Cold chain management', 'Customs clearance support'],
    status: 'active',
  },
  {
    id: 'pe-008',
    partner_type: 'packaging_supplier',
    name: 'MedPack Solutions',
    markets: ['DE', 'UK', 'NL'],
    categories: ['packaging', 'services'],
    relationship_stage: 'engaged',
    opportunity_mapping: ['Compliant packaging supply', 'Child-resistant packaging', 'Labelling compliance'],
    status: 'prospective',
  },
  {
    id: 'pe-009',
    partner_type: 'equipment_vendor',
    name: 'CannaEquip International',
    markets: ['CA', 'AU', 'NL'],
    categories: ['equipment', 'services'],
    relationship_stage: 'contacted',
    opportunity_mapping: ['Cultivation equipment supply', 'Extraction equipment', 'Processing line setup'],
    status: 'prospective',
  },
  {
    id: 'pe-010',
    partner_type: 'insurer',
    name: 'Apex Cannabis Risk Solutions',
    markets: ['CA', 'UK', 'AU'],
    categories: ['services', 'market_access'],
    relationship_stage: 'identified',
    opportunity_mapping: ['Product liability insurance', 'Cargo insurance for cannabis shipments', 'D&O coverage'],
    status: 'prospective',
  },
  {
    id: 'pe-011',
    partner_type: 'financier',
    name: 'GreenVest Capital',
    markets: ['CA', 'AU', 'UK'],
    categories: ['services', 'market_access'],
    relationship_stage: 'engaged',
    opportunity_mapping: ['Trade finance facilitation', 'Working capital solutions', 'M&A advisory'],
    status: 'active',
  },
  {
    id: 'pe-012',
    partner_type: 'ma_advisor',
    name: 'Harbourside M&A Advisory',
    markets: ['CA', 'AU', 'DE', 'UK'],
    categories: ['services', 'market_access'],
    relationship_stage: 'active',
    opportunity_mapping: ['Acquisition target sourcing', 'Due diligence support', 'Deal structuring'],
    status: 'active',
  },
  {
    id: 'pe-013',
    partner_type: 'country_market_advisor',
    name: 'PolskaKanna Advisory',
    markets: ['PL'],
    categories: ['market_access', 'services'],
    relationship_stage: 'active',
    opportunity_mapping: ['Polish market entry advisory', 'Regulatory liaison', 'Local partner introductions'],
    status: 'active',
  },
  {
    id: 'pe-014',
    partner_type: 'country_market_advisor',
    name: 'CzechCanna Partners',
    markets: ['CZ', 'SK'],
    categories: ['market_access', 'services'],
    relationship_stage: 'engaged',
    opportunity_mapping: ['Czech market entry', 'Central European distribution', 'Regulatory pathway mapping'],
    status: 'prospective',
  },
  {
    id: 'pe-015',
    partner_type: 'route_to_market',
    name: 'LATAM Cannabis Gateway',
    markets: ['LATAM'],
    categories: ['market_access', 'distributors'],
    relationship_stage: 'contacted',
    opportunity_mapping: ['LATAM market entry', 'Regional distributor network', 'Regulatory pathway advisory'],
    status: 'prospective',
  },
  {
    id: 'pe-016',
    partner_type: 'data_intelligence',
    name: 'CannaIntel Data Services',
    markets: ['DE', 'UK', 'CA', 'AU'],
    categories: ['services', 'market_access'],
    relationship_stage: 'strategic',
    opportunity_mapping: ['Market intelligence co-development', 'Data sharing agreement', 'White-label reports'],
    status: 'active',
  },
  {
    id: 'pe-017',
    partner_type: 'white_label',
    name: 'PharmaFlow Platform Solutions',
    markets: ['DE', 'NL', 'PT'],
    categories: ['services', 'market_access'],
    relationship_stage: 'identified',
    opportunity_mapping: ['White-label platform deployment', 'EU market intelligence integration', 'Channel partner programme'],
    status: 'prospective',
  },
  {
    id: 'pe-018',
    partner_type: 'enterprise_client',
    name: 'NorthernLeaf Exports Inc',
    markets: ['CA', 'DE', 'UK', 'AU'],
    categories: ['cannabis_inventory', 'eu_gmp'],
    relationship_stage: 'strategic',
    opportunity_mapping: ['Enterprise operator seat', 'Multi-market deal facilitation', 'Buyer introductions', 'Deal room access'],
    status: 'active',
  },
]

export const revenueIntelligenceItems: RevenueIntelligenceItem[] = [
  {
    id: 'ri-001',
    revenue_type: 'importer_introduction',
    title: 'DE Importer Introduction — NorthernLeaf',
    entity_label: 'NorthernLeaf Exports Inc',
    market: 'DE',
    category: 'cannabis_inventory',
    expected_revenue: 2800,
    estimated_deal_value: 420000,
    success_fee_potential: 21000,
    conversion_probability: 0.72,
    stage: 'negotiation',
    next_action: 'Facilitate deal room setup with EuroMed Cannabis Imports',
    owner: 'Analyst Team',
    created_at: '2026-03-15T09:00:00Z',
  },
  {
    id: 'ri-002',
    revenue_type: 'market_access_review',
    title: 'UK Market Access Review — CannaCo Australia',
    entity_label: 'CannaCo Australia Pty',
    market: 'UK',
    category: 'eu_gmp',
    expected_revenue: 3500,
    estimated_deal_value: 0,
    success_fee_potential: 0,
    conversion_probability: 0.85,
    stage: 'proposal',
    next_action: 'Deliver market access review report',
    owner: 'Analyst Team',
    created_at: '2026-04-02T10:30:00Z',
  },
  {
    id: 'ri-003',
    revenue_type: 'deal_room',
    title: 'PT Supply Deal — CannaDistri Integration',
    entity_label: 'CannaDistri Portugal Lda',
    market: 'PT',
    category: 'cannabis_inventory',
    expected_revenue: 950,
    estimated_deal_value: 185000,
    success_fee_potential: 9250,
    conversion_probability: 0.6,
    stage: 'negotiation',
    next_action: 'Confirm commercial terms and open deal room',
    owner: 'Analyst Team',
    created_at: '2026-04-10T14:00:00Z',
  },
  {
    id: 'ri-004',
    revenue_type: 'intelligence_subscription',
    title: 'Annual Intelligence Subscription — MedGroup DE',
    entity_label: 'MedGroup Deutschland GmbH',
    market: 'DE',
    category: 'market_access',
    expected_revenue: 10680,
    estimated_deal_value: 0,
    success_fee_potential: 0,
    conversion_probability: 0.9,
    stage: 'closed_won',
    next_action: 'Onboarding complete — schedule quarterly review',
    owner: 'Sales Team',
    created_at: '2026-01-20T08:00:00Z',
  },
  {
    id: 'ri-005',
    revenue_type: 'enterprise_seat',
    title: 'Enterprise Operator Seat — NorthernLeaf',
    entity_label: 'NorthernLeaf Exports Inc',
    market: 'CA',
    category: 'market_access',
    expected_revenue: 48000,
    estimated_deal_value: 0,
    success_fee_potential: 0,
    conversion_probability: 0.78,
    stage: 'proposal',
    next_action: 'Present enterprise proposal to executive sponsor',
    owner: 'Sales Team',
    created_at: '2026-05-01T09:00:00Z',
  },
  {
    id: 'ri-006',
    revenue_type: 'success_fee',
    title: 'UK Import Deal Closing — PharmaBridge',
    entity_label: 'Pharmabis UK Ltd',
    market: 'UK',
    category: 'cannabis_inventory',
    expected_revenue: 18500,
    estimated_deal_value: 370000,
    success_fee_potential: 18500,
    conversion_probability: 0.55,
    stage: 'negotiation',
    next_action: 'Confirm deal closing milestone and invoice success fee',
    owner: 'Analyst Team',
    created_at: '2026-05-15T11:00:00Z',
  },
  {
    id: 'ri-007',
    revenue_type: 'access_product',
    title: 'Documentation Readiness Review — PL Entrant',
    entity_label: 'WarsawCanna Sp. z o.o.',
    market: 'PL',
    category: 'eu_gmp',
    expected_revenue: 1800,
    estimated_deal_value: 0,
    success_fee_potential: 0,
    conversion_probability: 0.95,
    stage: 'closed_won',
    next_action: 'Deliver gap analysis report',
    owner: 'Analyst Team',
    created_at: '2026-05-20T09:00:00Z',
  },
  {
    id: 'ri-008',
    revenue_type: 'distributor_introduction',
    title: 'NL Distributor Introduction — AU Exporter',
    entity_label: 'Southern Cross Cannabis AU',
    market: 'NL',
    category: 'cannabis_inventory',
    expected_revenue: 2500,
    estimated_deal_value: 210000,
    success_fee_potential: 10500,
    conversion_probability: 0.45,
    stage: 'qualified',
    next_action: 'Shortlist NL distributors and send profiles',
    owner: 'Analyst Team',
    created_at: '2026-06-01T10:00:00Z',
  },
  {
    id: 'ri-009',
    revenue_type: 'partner_referral',
    title: 'GMP Consulting Referral — CZ Market',
    entity_label: 'PharmaBridge Consulting',
    market: 'CZ',
    category: 'eu_gmp',
    expected_revenue: 850,
    estimated_deal_value: 0,
    success_fee_potential: 0,
    conversion_probability: 0.7,
    stage: 'proposal',
    next_action: 'Confirm referral agreement and send introduction',
    owner: 'Partner Team',
    created_at: '2026-06-05T09:00:00Z',
  },
  {
    id: 'ri-010',
    revenue_type: 'market_access_review',
    title: 'LATAM Market Access Review — CA Producer',
    entity_label: 'CanadaGreen Producers Inc',
    market: 'LATAM',
    category: 'market_access',
    expected_revenue: 3500,
    estimated_deal_value: 0,
    success_fee_potential: 0,
    conversion_probability: 0.6,
    stage: 'identified',
    next_action: 'Qualify opportunity and send market access review scope',
    owner: 'Analyst Team',
    created_at: '2026-06-08T09:00:00Z',
  },
  {
    id: 'ri-011',
    revenue_type: 'access_product',
    title: 'Qualified Buyer Access — PT Seller',
    entity_label: 'Lusitania Cannabis Lda',
    market: 'PT',
    category: 'cannabis_inventory',
    expected_revenue: 4500,
    estimated_deal_value: 340000,
    success_fee_potential: 17000,
    conversion_probability: 0.65,
    stage: 'proposal',
    next_action: 'Deliver buyer shortlist and facilitate introductory calls',
    owner: 'Analyst Team',
    created_at: '2026-06-10T09:00:00Z',
  },
  {
    id: 'ri-012',
    revenue_type: 'intelligence_subscription',
    title: 'Market Intelligence Subscription — AU Operator',
    entity_label: 'Pacific Cannabis Ventures',
    market: 'AU',
    category: 'market_access',
    expected_revenue: 5340,
    estimated_deal_value: 0,
    success_fee_potential: 0,
    conversion_probability: 0.8,
    stage: 'qualified',
    next_action: 'Send subscription proposal and onboarding guide',
    owner: 'Sales Team',
    created_at: '2026-06-12T09:00:00Z',
  },
  {
    id: 'ri-013',
    revenue_type: 'deal_room',
    title: 'DE Supply Deal Room — EU-GMP Certified',
    entity_label: 'AlpineCanna AG',
    market: 'DE',
    category: 'eu_gmp',
    expected_revenue: 950,
    estimated_deal_value: 520000,
    success_fee_potential: 26000,
    conversion_probability: 0.5,
    stage: 'identified',
    next_action: 'Validate EU-GMP status and qualify buyer demand',
    owner: 'Analyst Team',
    created_at: '2026-06-13T09:00:00Z',
  },
  {
    id: 'ri-014',
    revenue_type: 'stale_opportunity',
    title: 'PL Import Introduction — Stale Lead',
    entity_label: 'Krakow MedPharm S.A.',
    market: 'PL',
    category: 'importers',
    expected_revenue: 2800,
    estimated_deal_value: 95000,
    success_fee_potential: 4750,
    conversion_probability: 0.2,
    stage: 'qualified',
    next_action: 'Re-engage or mark as closed lost after 30 days',
    owner: 'Analyst Team',
    created_at: '2025-12-01T09:00:00Z',
  },
  {
    id: 'ri-015',
    revenue_type: 'importer_introduction',
    title: 'CA Importer Introduction — UK Producer',
    entity_label: 'BritGreen Exports Ltd',
    market: 'CA',
    category: 'cannabis_inventory',
    expected_revenue: 2800,
    estimated_deal_value: 290000,
    success_fee_potential: 14500,
    conversion_probability: 0.4,
    stage: 'identified',
    next_action: 'Identify CA importers and send buyer demand report',
    owner: 'Analyst Team',
    created_at: '2026-06-14T09:00:00Z',
  },
  {
    id: 'ri-016',
    revenue_type: 'success_fee',
    title: 'AU Export Deal Closing — Multi-market',
    entity_label: 'Cann Group AU',
    market: 'AU',
    category: 'cannabis_inventory',
    expected_revenue: 24000,
    estimated_deal_value: 480000,
    success_fee_potential: 24000,
    conversion_probability: 0.68,
    stage: 'negotiation',
    next_action: 'Confirm deal structure and milestone schedule',
    owner: 'Analyst Team',
    created_at: '2026-05-28T09:00:00Z',
  },
  {
    id: 'ri-017',
    revenue_type: 'access_product',
    title: 'Market Brief Access — CZ Pharmaceutical Group',
    entity_label: 'Praha Pharma s.r.o.',
    market: 'CZ',
    category: 'market_access',
    expected_revenue: 650,
    estimated_deal_value: 0,
    success_fee_potential: 0,
    conversion_probability: 0.95,
    stage: 'closed_won',
    next_action: 'Deliver CZ market brief and schedule follow-up Q&A',
    owner: 'Analyst Team',
    created_at: '2026-06-15T09:00:00Z',
  },
  {
    id: 'ri-018',
    revenue_type: 'enterprise_seat',
    title: 'Enterprise Seat — AU Medical Cannabis Group',
    entity_label: 'MedCannAU Holdings',
    market: 'AU',
    category: 'market_access',
    expected_revenue: 60000,
    estimated_deal_value: 0,
    success_fee_potential: 0,
    conversion_probability: 0.35,
    stage: 'identified',
    next_action: 'Schedule executive discovery call',
    owner: 'Sales Team',
    created_at: '2026-06-16T09:00:00Z',
  },
  {
    id: 'ri-019',
    revenue_type: 'partner_referral',
    title: 'Logistics Partner Referral — DE Supply Chain',
    entity_label: 'CannaTrans Global Logistics',
    market: 'DE',
    category: 'services',
    expected_revenue: 620,
    estimated_deal_value: 0,
    success_fee_potential: 0,
    conversion_probability: 0.88,
    stage: 'proposal',
    next_action: 'Confirm logistics partner referral agreement',
    owner: 'Partner Team',
    created_at: '2026-06-17T09:00:00Z',
  },
  {
    id: 'ri-020',
    revenue_type: 'distributor_introduction',
    title: 'UK Distributor Introduction — NL Producer',
    entity_label: 'Bedrocan Netherlands BV',
    market: 'UK',
    category: 'distributors',
    expected_revenue: 2500,
    estimated_deal_value: 175000,
    success_fee_potential: 8750,
    conversion_probability: 0.52,
    stage: 'qualified',
    next_action: 'Shortlist UK distributors and send introductory profiles',
    owner: 'Analyst Team',
    created_at: '2026-06-18T09:00:00Z',
  },
]

export const institutionalReports: InstitutionalReport[] = [
  {
    id: 'ir-001',
    report_type: 'market_brief',
    title: 'Germany Medical Cannabis Market Brief — Q2 2026',
    market: 'DE',
    category: 'cannabis_inventory',
    status: 'published',
    completeness_pct: 100,
    sections: ['Regulatory Overview', 'Buyer Demand Analysis', 'Import Pathway', 'Key Importers', 'Pricing Intelligence', 'Commercial Opportunities'],
    created_at: '2026-04-01T09:00:00Z',
    last_updated: '2026-06-01T09:00:00Z',
  },
  {
    id: 'ir-002',
    report_type: 'market_brief',
    title: 'United Kingdom Cannabis Market Brief — Q2 2026',
    market: 'UK',
    category: 'cannabis_inventory',
    status: 'published',
    completeness_pct: 100,
    sections: ['Regulatory Framework', 'Schedule 2 Import Pathway', 'Buyer Demand', 'Key Operators', 'Market Sizing', 'Entry Strategy'],
    created_at: '2026-04-05T09:00:00Z',
    last_updated: '2026-06-02T09:00:00Z',
  },
  {
    id: 'ir-003',
    report_type: 'market_brief',
    title: 'Portugal Medical Cannabis Market Brief — H1 2026',
    market: 'PT',
    category: 'cannabis_inventory',
    status: 'ready_for_review',
    completeness_pct: 88,
    sections: ['Regulatory Status', 'Import Requirements', 'Pharmacy Channel', 'Distributor Landscape', 'Pricing Benchmarks'],
    created_at: '2026-05-01T09:00:00Z',
    last_updated: '2026-06-10T09:00:00Z',
  },
  {
    id: 'ir-004',
    report_type: 'market_brief',
    title: 'Australia TGA Cannabis Market Brief — Q2 2026',
    market: 'AU',
    category: 'eu_gmp',
    status: 'published',
    completeness_pct: 95,
    sections: ['TGA Regulatory Framework', 'SAS-B Import Pathway', 'Buyer Demand Signals', 'Key Importers', 'Quality Requirements'],
    created_at: '2026-03-15T09:00:00Z',
    last_updated: '2026-05-28T09:00:00Z',
  },
  {
    id: 'ir-005',
    report_type: 'market_brief',
    title: 'Poland Medical Cannabis Market Brief — H1 2026',
    market: 'PL',
    category: 'cannabis_inventory',
    status: 'draft',
    completeness_pct: 62,
    sections: ['Regulatory Overview', 'Import Framework', 'Market Participants'],
    created_at: '2026-05-20T09:00:00Z',
    last_updated: '2026-06-12T09:00:00Z',
  },
  {
    id: 'ir-006',
    report_type: 'market_brief',
    title: 'Czech Republic Cannabis Market Brief — H1 2026',
    market: 'CZ',
    category: 'cannabis_inventory',
    status: 'draft',
    completeness_pct: 55,
    sections: ['Regulatory Status', 'Import Requirements', 'Market Opportunity'],
    created_at: '2026-06-01T09:00:00Z',
    last_updated: '2026-06-15T09:00:00Z',
  },
  {
    id: 'ir-007',
    report_type: 'opportunity_memo',
    title: 'NorthernLeaf DE Market Entry Opportunity',
    market: 'DE',
    category: 'cannabis_inventory',
    status: 'shared',
    completeness_pct: 100,
    sections: ['Executive Summary', 'Counterparty Profile', 'Market Fit Assessment', 'Recommended Importers', 'Commercial Structure', 'Next Steps'],
    created_at: '2026-04-20T09:00:00Z',
    last_updated: '2026-05-15T09:00:00Z',
  },
  {
    id: 'ir-008',
    report_type: 'opportunity_memo',
    title: 'AU-UK Export Opportunity — Southern Cross Cannabis',
    market: 'UK',
    category: 'eu_gmp',
    status: 'published',
    completeness_pct: 92,
    sections: ['Executive Summary', 'Regulatory Pathway', 'Buyer Demand', 'Recommended Importers', 'Commercial Recommendation'],
    created_at: '2026-05-10T09:00:00Z',
    last_updated: '2026-06-05T09:00:00Z',
  },
  {
    id: 'ir-009',
    report_type: 'opportunity_memo',
    title: 'PT Pharmacy Channel Entry — CannaDistri',
    market: 'PT',
    category: 'distributors',
    status: 'ready_for_review',
    completeness_pct: 80,
    sections: ['Executive Summary', 'Pharmacy Channel Analysis', 'Distributor Options', 'Commercial Structure'],
    created_at: '2026-06-01T09:00:00Z',
    last_updated: '2026-06-14T09:00:00Z',
  },
  {
    id: 'ir-010',
    report_type: 'opportunity_memo',
    title: 'LATAM Market Expansion Opportunity — CA Producer',
    market: 'LATAM',
    category: 'market_access',
    status: 'draft',
    completeness_pct: 40,
    sections: ['Executive Summary', 'Market Overview'],
    created_at: '2026-06-10T09:00:00Z',
    last_updated: '2026-06-17T09:00:00Z',
  },
  {
    id: 'ir-011',
    report_type: 'document_readiness_summary',
    title: 'Document Readiness Summary — WarsawCanna PL',
    market: 'PL',
    category: 'eu_gmp',
    status: 'published',
    completeness_pct: 100,
    sections: ['Document Inventory', 'Gap Analysis', 'Remediation Plan', 'Priority Actions', 'Estimated Timeline'],
    created_at: '2026-05-22T09:00:00Z',
    last_updated: '2026-06-01T09:00:00Z',
  },
  {
    id: 'ir-012',
    report_type: 'document_readiness_summary',
    title: 'Document Readiness Summary — BritGreen CA Export',
    market: 'CA',
    category: 'cannabis_inventory',
    status: 'ready_for_review',
    completeness_pct: 85,
    sections: ['Document Inventory', 'Regulatory Requirements', 'Gap Analysis', 'Next Steps'],
    created_at: '2026-06-05T09:00:00Z',
    last_updated: '2026-06-16T09:00:00Z',
  },
  {
    id: 'ir-013',
    report_type: 'document_readiness_summary',
    title: 'Document Readiness Summary — AlpineCanna DE',
    market: 'DE',
    category: 'eu_gmp',
    status: 'draft',
    completeness_pct: 70,
    sections: ['Document Inventory', 'EU-GMP Requirements', 'Gap Analysis'],
    created_at: '2026-06-08T09:00:00Z',
    last_updated: '2026-06-15T09:00:00Z',
  },
  {
    id: 'ir-014',
    report_type: 'document_readiness_summary',
    title: 'Document Readiness Summary — Pacific Cannabis AU',
    market: 'AU',
    category: 'eu_gmp',
    status: 'shared',
    completeness_pct: 95,
    sections: ['Document Inventory', 'TGA Requirements', 'Gap Analysis', 'Remediation Plan', 'Certification Roadmap'],
    created_at: '2026-05-15T09:00:00Z',
    last_updated: '2026-06-10T09:00:00Z',
  },
  {
    id: 'ir-015',
    report_type: 'executive_dashboard',
    title: 'Harbourview Executive Dashboard — June 2026',
    market: 'Global',
    category: 'market_access',
    status: 'published',
    completeness_pct: 100,
    sections: ['Revenue Pipeline', 'Market Coverage', 'Partner Ecosystem', 'Governance Quality', 'Signal Freshness', 'Expansion Priorities'],
    created_at: '2026-06-01T09:00:00Z',
    last_updated: '2026-06-19T09:00:00Z',
  },
  {
    id: 'ir-016',
    report_type: 'partner_ecosystem_report',
    title: 'Partner Ecosystem Report — H1 2026',
    market: 'Global',
    category: 'market_access',
    status: 'ready_for_review',
    completeness_pct: 90,
    sections: ['Partner Overview', 'Ecosystem by Market', 'Relationship Stages', 'Revenue Opportunity Mapping', 'Strategic Partner Recommendations'],
    created_at: '2026-06-05T09:00:00Z',
    last_updated: '2026-06-18T09:00:00Z',
  },
  {
    id: 'ir-017',
    report_type: 'revenue_opportunity_report',
    title: 'Revenue Opportunity Report — Q2 2026',
    market: 'Global',
    category: 'market_access',
    status: 'published',
    completeness_pct: 100,
    sections: ['Pipeline Summary', 'Access Product Revenue', 'Success Fee Opportunities', 'Subscription Revenue', 'Enterprise Pipeline', 'Forecast'],
    created_at: '2026-06-01T09:00:00Z',
    last_updated: '2026-06-19T09:00:00Z',
  },
  {
    id: 'ir-018',
    report_type: 'intelligence_coverage_report',
    title: 'Intelligence Coverage Report — June 2026',
    market: 'Global',
    category: 'market_access',
    status: 'draft',
    completeness_pct: 75,
    sections: ['Market Coverage Summary', 'Signal Freshness Analysis', 'Source Quality Review', 'Coverage Gaps', 'Priority Expansion'],
    created_at: '2026-06-10T09:00:00Z',
    last_updated: '2026-06-18T09:00:00Z',
  },
]

export const executiveDashboardMetrics: { id: string; label: string; value: number; unit: string; trend: 'up' | 'down' | 'stable'; target: number }[] = [
  { id: 'edm-001', label: 'Revenue Pipeline Total', value: 243280, unit: 'USD', trend: 'up', target: 300000 },
  { id: 'edm-002', label: 'Active Subscribers', value: 147, unit: 'subscribers', trend: 'up', target: 200 },
  { id: 'edm-003', label: 'Success Fee Pipeline', value: 148750, unit: 'USD', trend: 'up', target: 200000 },
  { id: 'edm-004', label: 'Markets Covered', value: 12, unit: 'markets', trend: 'stable', target: 20 },
  { id: 'edm-005', label: 'Active Partners', value: 11, unit: 'partners', trend: 'up', target: 20 },
  { id: 'edm-006', label: 'Closed Won Revenue (QTD)', value: 67180, unit: 'USD', trend: 'up', target: 100000 },
  { id: 'edm-007', label: 'Published Reports', value: 9, unit: 'reports', trend: 'up', target: 15 },
  { id: 'edm-008', label: 'Access Products Active', value: 11, unit: 'products', trend: 'stable', target: 13 },
  { id: 'edm-009', label: 'Average Deal Value', value: 312500, unit: 'USD', trend: 'up', target: 350000 },
  { id: 'edm-010', label: 'Governance Score (Avg)', value: 74, unit: 'score', trend: 'up', target: 85 },
  { id: 'edm-011', label: 'Deal Rooms Open', value: 3, unit: 'rooms', trend: 'up', target: 5 },
  { id: 'edm-012', label: 'Signal Freshness (Avg Days)', value: 8, unit: 'days', trend: 'down', target: 5 },
  { id: 'edm-013', label: 'Enterprise Pipeline Value', value: 108000, unit: 'USD', trend: 'up', target: 150000 },
  { id: 'edm-014', label: 'Partner Introductions (QTD)', value: 14, unit: 'introductions', trend: 'up', target: 20 },
  { id: 'edm-015', label: 'Buyer Demand Signals (Active)', value: 38, unit: 'signals', trend: 'up', target: 50 },
  { id: 'edm-016', label: 'Market Briefs Delivered', value: 4, unit: 'briefs', trend: 'stable', target: 6 },
  { id: 'edm-017', label: 'Document Reviews Completed', value: 7, unit: 'reviews', trend: 'up', target: 10 },
  { id: 'edm-018', label: 'Conversion Rate (Qualified→Won)', value: 38, unit: '%', trend: 'up', target: 50 },
  { id: 'edm-019', label: 'NPS Score (Partners)', value: 62, unit: 'NPS', trend: 'stable', target: 70 },
  { id: 'edm-020', label: 'Subscription MRR', value: 18940, unit: 'USD', trend: 'up', target: 25000 },
]

export const governanceQualityItems: GovernanceQualityItem[] = [
  {
    id: 'gq-001',
    quality_dimension: 'source_confidence',
    title: 'DE Import Regulatory Sources',
    entity_label: 'BfArM Source Registry',
    market: 'DE',
    score: 92,
    status: 'approved',
    reviewer: 'Lead Analyst',
    created_at: '2026-05-01T09:00:00Z',
  },
  {
    id: 'gq-002',
    quality_dimension: 'evidence_quality',
    title: 'UK Schedule 2 Import Evidence',
    entity_label: 'Home Office UK Sources',
    market: 'UK',
    score: 85,
    status: 'approved',
    reviewer: 'Lead Analyst',
    created_at: '2026-05-05T09:00:00Z',
  },
  {
    id: 'gq-003',
    quality_dimension: 'report_readiness',
    title: 'PT Market Brief Readiness',
    entity_label: 'Portugal Market Brief Q2',
    market: 'PT',
    score: 88,
    status: 'pending_review',
    reviewer: 'Senior Analyst',
    created_at: '2026-06-10T09:00:00Z',
  },
  {
    id: 'gq-004',
    quality_dimension: 'partner_quality',
    title: 'EuroMed Cannabis Imports Partner Quality',
    entity_label: 'EuroMed Cannabis Imports GmbH',
    market: 'DE',
    score: 90,
    status: 'approved',
    reviewer: 'Partner Manager',
    created_at: '2026-04-15T09:00:00Z',
  },
  {
    id: 'gq-005',
    quality_dimension: 'data_freshness',
    title: 'PL Regulatory Signal Freshness',
    entity_label: 'Polish URPL Sources',
    market: 'PL',
    score: 58,
    status: 'flagged',
    reviewer: 'Data Team',
    created_at: '2026-06-01T09:00:00Z',
  },
  {
    id: 'gq-006',
    quality_dimension: 'document_readiness',
    title: 'WarsawCanna Documentation Package',
    entity_label: 'WarsawCanna Sp. z o.o.',
    market: 'PL',
    score: 72,
    status: 'approved',
    reviewer: 'Compliance Analyst',
    created_at: '2026-06-01T09:00:00Z',
  },
  {
    id: 'gq-007',
    quality_dimension: 'analyst_review',
    title: 'CZ Market Intelligence Review',
    entity_label: 'Czech Republic Market Coverage',
    market: 'CZ',
    score: 48,
    status: 'incomplete',
    reviewer: 'Unassigned',
    created_at: '2026-06-05T09:00:00Z',
  },
  {
    id: 'gq-008',
    quality_dimension: 'commercial_action_status',
    title: 'NorthernLeaf DE Deal Progress',
    entity_label: 'NorthernLeaf Exports Inc',
    market: 'DE',
    score: 78,
    status: 'approved',
    reviewer: 'Deal Lead',
    created_at: '2026-05-20T09:00:00Z',
  },
  {
    id: 'gq-009',
    quality_dimension: 'report_quality',
    title: 'AU Market Brief Quality Audit',
    entity_label: 'Australia TGA Market Brief',
    market: 'AU',
    score: 95,
    status: 'approved',
    reviewer: 'Lead Analyst',
    created_at: '2026-05-28T09:00:00Z',
  },
  {
    id: 'gq-010',
    quality_dimension: 'outcome_capture',
    title: 'UK Deal Outcome Tracking',
    entity_label: 'Pharmabis UK Deal Room',
    market: 'UK',
    score: 65,
    status: 'pending_review',
    reviewer: 'Deal Lead',
    created_at: '2026-06-05T09:00:00Z',
  },
  {
    id: 'gq-011',
    quality_dimension: 'score_update_history',
    title: 'NL Signal Score Update History',
    entity_label: 'Netherlands Market Sources',
    market: 'NL',
    score: 80,
    status: 'approved',
    reviewer: 'Data Team',
    created_at: '2026-06-01T09:00:00Z',
  },
  {
    id: 'gq-012',
    quality_dimension: 'operator_approval',
    title: 'Revenue Opportunity Report Approval',
    entity_label: 'Q2 2026 Revenue Report',
    market: 'Global',
    score: 100,
    status: 'approved',
    reviewer: 'Operations Lead',
    created_at: '2026-06-19T09:00:00Z',
  },
  {
    id: 'gq-013',
    quality_dimension: 'recommendation_status',
    title: 'LATAM Expansion Recommendations',
    entity_label: 'LATAM Market Brief',
    market: 'LATAM',
    score: 42,
    status: 'incomplete',
    reviewer: 'Unassigned',
    created_at: '2026-06-10T09:00:00Z',
  },
  {
    id: 'gq-014',
    quality_dimension: 'source_confidence',
    title: 'CA Health Canada Source Confidence',
    entity_label: 'Health Canada Regulatory Sources',
    market: 'CA',
    score: 88,
    status: 'approved',
    reviewer: 'Lead Analyst',
    created_at: '2026-05-10T09:00:00Z',
  },
  {
    id: 'gq-015',
    quality_dimension: 'data_freshness',
    title: 'CZ Signal Freshness Review',
    entity_label: 'SÚKL Czech Sources',
    market: 'CZ',
    score: 52,
    status: 'flagged',
    reviewer: 'Data Team',
    created_at: '2026-06-12T09:00:00Z',
  },
  {
    id: 'gq-016',
    quality_dimension: 'evidence_quality',
    title: 'PT Import Evidence Quality',
    entity_label: 'INFARMED Portugal Sources',
    market: 'PT',
    score: 76,
    status: 'pending_review',
    reviewer: 'Senior Analyst',
    created_at: '2026-06-08T09:00:00Z',
  },
]

export const globalExpansionCoverage: GlobalExpansionCoverage[] = [
  {
    id: 'ge-001',
    market: 'DE',
    region: 'Europe',
    pathway_coverage: 95,
    partner_coverage: 90,
    buyer_demand_coverage: 92,
    supply_relevance: 88,
    documentation_requirements: ['EU-GMP certificate', 'BfArM import permit', 'CoA per batch', 'Narcotics export certificate', 'Country of origin certificate'],
    source_coverage: 94,
    signal_freshness_days: 4,
    route_to_market_readiness: 'ready',
    revenue_potential: 'high',
    priority: 'tier_1',
  },
  {
    id: 'ge-002',
    market: 'UK',
    region: 'Europe',
    pathway_coverage: 90,
    partner_coverage: 82,
    buyer_demand_coverage: 88,
    supply_relevance: 85,
    documentation_requirements: ['Schedule 2 import licence', 'Home Office approval', 'CoA per batch', 'GMP certificate', 'MHRA product approval'],
    source_coverage: 88,
    signal_freshness_days: 5,
    route_to_market_readiness: 'ready',
    revenue_potential: 'high',
    priority: 'tier_1',
  },
  {
    id: 'ge-003',
    market: 'PT',
    region: 'Europe',
    pathway_coverage: 82,
    partner_coverage: 75,
    buyer_demand_coverage: 78,
    supply_relevance: 80,
    documentation_requirements: ['INFARMED import approval', 'EU-GMP or equivalent', 'Narcotics permit', 'CoA documentation', 'Distributor agreement'],
    source_coverage: 80,
    signal_freshness_days: 7,
    route_to_market_readiness: 'partial',
    revenue_potential: 'medium',
    priority: 'tier_1',
  },
  {
    id: 'ge-004',
    market: 'AU',
    region: 'Asia-Pacific',
    pathway_coverage: 88,
    partner_coverage: 80,
    buyer_demand_coverage: 85,
    supply_relevance: 82,
    documentation_requirements: ['TGA SAS-B import permit', 'ODC import licence', 'CoA per batch', 'GMP certificate', 'Product registration'],
    source_coverage: 86,
    signal_freshness_days: 6,
    route_to_market_readiness: 'ready',
    revenue_potential: 'high',
    priority: 'tier_1',
  },
  {
    id: 'ge-005',
    market: 'CA',
    region: 'North America',
    pathway_coverage: 85,
    partner_coverage: 78,
    buyer_demand_coverage: 80,
    supply_relevance: 76,
    documentation_requirements: ['Health Canada export permit', 'Licence holder verification', 'CoA per shipment', 'Security clearance', 'Importer-of-record confirmation'],
    source_coverage: 82,
    signal_freshness_days: 5,
    route_to_market_readiness: 'ready',
    revenue_potential: 'high',
    priority: 'tier_1',
  },
  {
    id: 'ge-006',
    market: 'PL',
    region: 'Europe',
    pathway_coverage: 65,
    partner_coverage: 60,
    buyer_demand_coverage: 62,
    supply_relevance: 70,
    documentation_requirements: ['GIF import permit', 'EU-GMP certificate', 'Narcotics documentation', 'Quality certificates', 'Importer licence'],
    source_coverage: 60,
    signal_freshness_days: 12,
    route_to_market_readiness: 'partial',
    revenue_potential: 'medium',
    priority: 'tier_2',
  },
  {
    id: 'ge-007',
    market: 'CZ',
    region: 'Europe',
    pathway_coverage: 58,
    partner_coverage: 50,
    buyer_demand_coverage: 55,
    supply_relevance: 65,
    documentation_requirements: ['SÚKL import permit', 'EU-GMP certificate', 'Controlled substance documentation', 'Distributor agreement'],
    source_coverage: 55,
    signal_freshness_days: 15,
    route_to_market_readiness: 'building',
    revenue_potential: 'medium',
    priority: 'tier_2',
  },
  {
    id: 'ge-008',
    market: 'NL',
    region: 'Europe',
    pathway_coverage: 78,
    partner_coverage: 72,
    buyer_demand_coverage: 75,
    supply_relevance: 78,
    documentation_requirements: ['IGJ import approval', 'EU-GMP certificate', 'Narcotics export permit', 'CoA documentation', 'OMC supplier registration'],
    source_coverage: 74,
    signal_freshness_days: 8,
    route_to_market_readiness: 'partial',
    revenue_potential: 'medium',
    priority: 'tier_2',
  },
  {
    id: 'ge-009',
    market: 'LATAM',
    region: 'Latin America',
    pathway_coverage: 40,
    partner_coverage: 30,
    buyer_demand_coverage: 45,
    supply_relevance: 60,
    documentation_requirements: ['Country-specific import permits', 'Regulatory authority approval', 'Quality certification', 'Controlled substance documentation'],
    source_coverage: 38,
    signal_freshness_days: 22,
    route_to_market_readiness: 'building',
    revenue_potential: 'medium',
    priority: 'tier_2',
  },
  {
    id: 'ge-010',
    market: 'US',
    region: 'North America',
    pathway_coverage: 30,
    partner_coverage: 25,
    buyer_demand_coverage: 50,
    supply_relevance: 40,
    documentation_requirements: ['DEA Schedule I restrictions — limited', 'State-level programme review', 'Federal pathway monitoring'],
    source_coverage: 45,
    signal_freshness_days: 10,
    route_to_market_readiness: 'gap',
    revenue_potential: 'high',
    priority: 'tier_2',
  },
  {
    id: 'ge-011',
    market: 'INT',
    region: 'International',
    pathway_coverage: 20,
    partner_coverage: 15,
    buyer_demand_coverage: 25,
    supply_relevance: 35,
    documentation_requirements: ['UN Single Convention compliance', 'Country-specific import permits', 'INCB reporting requirements'],
    source_coverage: 22,
    signal_freshness_days: 30,
    route_to_market_readiness: 'gap',
    revenue_potential: 'low',
    priority: 'tier_3',
  },
  {
    id: 'ge-012',
    market: 'Emerging',
    region: 'Global',
    pathway_coverage: 15,
    partner_coverage: 10,
    buyer_demand_coverage: 20,
    supply_relevance: 30,
    documentation_requirements: ['Market-specific regulatory assessment required', 'No established pathway documentation'],
    source_coverage: 18,
    signal_freshness_days: 45,
    route_to_market_readiness: 'gap',
    revenue_potential: 'low',
    priority: 'tier_3',
  },
]

export const successFeeOpportunities: SuccessFeeOpportunity[] = [
  {
    id: 'sf-001',
    title: 'NorthernLeaf × EuroMed DE Import Deal',
    entity_label: 'NorthernLeaf Exports Inc',
    market: 'DE',
    category: 'cannabis_inventory',
    fee_basis: '5% of deal value on first shipment',
    estimated_fee: 21000,
    deal_value: 420000,
    probability: 0.72,
    status: 'negotiating',
    owner: 'Analyst Team',
    created_at: '2026-03-15T09:00:00Z',
  },
  {
    id: 'sf-002',
    title: 'Pharmabis UK Import Closing',
    entity_label: 'Pharmabis UK Ltd',
    market: 'UK',
    category: 'cannabis_inventory',
    fee_basis: '5% of first contract value',
    estimated_fee: 18500,
    deal_value: 370000,
    probability: 0.55,
    status: 'negotiating',
    owner: 'Analyst Team',
    created_at: '2026-05-15T09:00:00Z',
  },
  {
    id: 'sf-003',
    title: 'CannaDistri PT Supply Agreement',
    entity_label: 'CannaDistri Portugal Lda',
    market: 'PT',
    category: 'cannabis_inventory',
    fee_basis: '5% of annual supply contract',
    estimated_fee: 9250,
    deal_value: 185000,
    probability: 0.6,
    status: 'tracking',
    owner: 'Analyst Team',
    created_at: '2026-04-10T09:00:00Z',
  },
  {
    id: 'sf-004',
    title: 'Cann Group AU Multi-Market Export',
    entity_label: 'Cann Group AU',
    market: 'AU',
    category: 'cannabis_inventory',
    fee_basis: '5% of deal value across all markets',
    estimated_fee: 24000,
    deal_value: 480000,
    probability: 0.68,
    status: 'negotiating',
    owner: 'Analyst Team',
    created_at: '2026-05-28T09:00:00Z',
  },
  {
    id: 'sf-005',
    title: 'Southern Cross × NL Distributor Deal',
    entity_label: 'Southern Cross Cannabis AU',
    market: 'NL',
    category: 'cannabis_inventory',
    fee_basis: '5% of first annual distribution contract',
    estimated_fee: 10500,
    deal_value: 210000,
    probability: 0.45,
    status: 'tracking',
    owner: 'Analyst Team',
    created_at: '2026-06-01T09:00:00Z',
  },
  {
    id: 'sf-006',
    title: 'Lusitania Cannabis PT Buyer Introduction',
    entity_label: 'Lusitania Cannabis Lda',
    market: 'PT',
    category: 'cannabis_inventory',
    fee_basis: '5% of deal value on signed supply agreement',
    estimated_fee: 17000,
    deal_value: 340000,
    probability: 0.65,
    status: 'tracking',
    owner: 'Analyst Team',
    created_at: '2026-06-10T09:00:00Z',
  },
  {
    id: 'sf-007',
    title: 'BritGreen × CA Importer Introduction',
    entity_label: 'BritGreen Exports Ltd',
    market: 'CA',
    category: 'cannabis_inventory',
    fee_basis: '5% of first contract value',
    estimated_fee: 14500,
    deal_value: 290000,
    probability: 0.4,
    status: 'identified',
    owner: 'Analyst Team',
    created_at: '2026-06-14T09:00:00Z',
  },
  {
    id: 'sf-008',
    title: 'AlpineCanna DE Supply Deal',
    entity_label: 'AlpineCanna AG',
    market: 'DE',
    category: 'eu_gmp',
    fee_basis: '5% of supply contract value',
    estimated_fee: 26000,
    deal_value: 520000,
    probability: 0.5,
    status: 'identified',
    owner: 'Analyst Team',
    created_at: '2026-06-13T09:00:00Z',
  },
]

export const subscriptionTiers: SubscriptionTier[] = [
  {
    id: 'st-001',
    name: 'Starter Intelligence',
    tier: 'starter',
    price_usd: 99,
    billing_period: 'monthly',
    features: ['1 market signal digest (weekly)', 'Access to public market briefs', 'Basic regulatory updates', 'Email support'],
    markets_included: ['1 market of choice'],
    status: 'active',
    subscriber_count: 42,
  },
  {
    id: 'st-002',
    name: 'Starter Intelligence (Annual)',
    tier: 'starter',
    price_usd: 890,
    billing_period: 'annual',
    features: ['1 market signal digest (weekly)', 'Access to public market briefs', 'Basic regulatory updates', 'Email support', '2 months free'],
    markets_included: ['1 market of choice'],
    status: 'active',
    subscriber_count: 18,
  },
  {
    id: 'st-003',
    name: 'Professional Intelligence',
    tier: 'professional',
    price_usd: 445,
    billing_period: 'monthly',
    features: ['Up to 5 market signal digests (weekly)', 'Full access to market briefs', 'Regulatory pathway reports', 'Buyer demand signals', 'Analyst Q&A (monthly)', 'Priority email support'],
    markets_included: ['DE', 'UK', 'PT', 'AU', 'CA'],
    status: 'active',
    subscriber_count: 61,
  },
  {
    id: 'st-004',
    name: 'Professional Intelligence (Annual)',
    tier: 'professional',
    price_usd: 4450,
    billing_period: 'annual',
    features: ['Up to 5 market signal digests (weekly)', 'Full access to market briefs', 'Regulatory pathway reports', 'Buyer demand signals', 'Analyst Q&A (monthly)', 'Priority email support', '2 months free'],
    markets_included: ['DE', 'UK', 'PT', 'AU', 'CA'],
    status: 'active',
    subscriber_count: 26,
  },
  {
    id: 'st-005',
    name: 'Enterprise Intelligence',
    tier: 'enterprise',
    price_usd: 1990,
    billing_period: 'monthly',
    features: ['Unlimited markets', 'All signal digests and market briefs', 'Deal flow reports', 'Opportunity memos', 'Analyst Q&A (weekly)', 'Partner directory access', 'Deal room access', 'Dedicated account manager'],
    markets_included: ['All covered markets'],
    status: 'active',
    subscriber_count: 0,
  },
  {
    id: 'st-006',
    name: 'Custom Enterprise',
    tier: 'custom',
    price_usd: 0,
    billing_period: 'annual',
    features: ['Bespoke intelligence scope', 'White-label option', 'API data access', 'Custom report cadence', 'Dedicated analyst team', 'SLA-backed support', 'Multi-seat access'],
    markets_included: ['Custom scope'],
    status: 'draft',
    subscriber_count: 0,
  },
]
